### ISSUE TITLE
Nodemon command immediately crashing.

### ISSUE THREAD

**Issue by lordliquid** [remy/nodemon#1000]
This is the first time I have written an issue, please bare with me. 

**The Setup:**
**OS:** Windows 10
**Nodemon:** installed via npm -global 
**Node:** version 6.9.2
**NPM:** version 3.10.9
Paths are included in my Environment Variables.

**I have tried:** 
Uninstalling and installing again globally.
Uninstalling globally and installing locally.

**Issue:**
I run command prompt in Windows (Administrator Mode).
CD to my local project which includes my Server.js file.
Type **nodemon server.js** and press enter.
**_The command prompt immediately closes with no debug information supplied._**

I have searched for resources on this particular issue but have found nothing.  
Because it gives me no information, I have no idea where to even begin to fix this, aside from what I have already tried (listed above).

**_Any help would be greatly appreciated._**

**Comment by remy** [comment]
Can you reliably replicate using a script that contains only
`console.log("hello world")`?

**Comment by lordliquid** [comment]
Yes, it happens even with a hello world script and just by typing nodemon command.

**Comment by remy** [comment]
Can you provide a screenshot of what you're seeing (which I appreciate is very little). Just adding some context.

**Comment by lordliquid** [comment]
I cant snap a screen shot that fast. I type the command and my command prompt closes. :(

**Comment by remy** [comment]
Screen cast?

**Comment by KhizerRehan** [comment]
I have installed nodemon globally (npm install -g nodemon) 
When running this command getting this issue @remy  help please! Thanks.
![screenshot_15](https://cloud.githubusercontent.com/assets/17727069/24309605/47ea0f5e-10ee-11e7-8571-f8ab8e6fd5ff.png)

**Comment by jlkalberer** [comment]
+1

I've spent the better half of my day trying to track this one down.  I'm on node `v6.10.1`

**Comment by yeskunall** [comment]
+1 to the screenshot posted by @KhizerRehan. Getting the same exact error.
