### ISSUE TITLE
cannot find module 'c:\bin\www'

### ISSUE THREAD

**Issue by kosnkow** [remy/nodemon#1001]
when I run npm start then server starts fine, when I try nodemon then I got

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./bin/www`
module.js:472
    throw err;
    ^

Error: Cannot find module 'c:\bin\www'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3

**Comment by remy** [comment]
How do you run the command without nodemon (i.e. with node) - can you share
the full command you're using?

**Comment by kosnkow** [comment]
npm start that starts the server without any problems besides in my package.json I have "start": "node ./bin/www"

**Comment by kosnkow** [comment]
ok started working after I removed autorun string with c:\ from 
HKEY_CURRENT_USER\Software\Microsoft\Command Processor

**Comment by remy** [comment]
Sounds like you're sorted now then.

**Comment by ifredom** [comment]
Setting the command line default path is for convenience.This problem makes it impossible to set the command line default path
