### ISSUE TITLE
Ignoring all node_modules except for one

### ISSUE THREAD

**Issue by shawninder** [remy/nodemon#1008]
I'm trying to have nodemon ignore all node_modules except for one (a dependency I am developping concurrently with my main project), but I can't find any way to do this. Glob patterns would support this use-case, and so would regular expressions. However, since these ignore strings are converted from a glob-style pattern to regular expressions before being passed to chokidar, I can no longer find any way to include negations in my ignore strings.

For example:

**nodemon.json**

```json
{
  "ignoreRoot": [
    ".git",
    ".nyc_output",
    ".sass-cache",
    "bower-components",
    "coverage"
  ],
  "ignore": [
    "node_modules/!(is-node)",
    "node_modules/is-node/node_modules"
  ]
}
```

Here the negation character `!` simply becomes a litteral `!` in the regular expression sent to chokidar.
A similar thing happens when I try negative look-ahead syntax:

```json
{
  "ignoreRoot": [
    ".git",
    ".nyc_output",
    ".sass-cache",
    "bower-components",
    "coverage"
  ],
  "ignore": [
    "node_modules/(?!is-node)",
    "node_modules/is-node/node_modules"
  ]
}
```

@remy Is there anything in the existing stable nodemon which could support this use-case of ignoring all node_modules except for one of them?

**more details**: I made a stackoverflow question for this with more details before I had understood why this wasn't working.

**Comment by remy** [comment]
Honestly, I'm not sure. I wonder if a PR that passes the pattern directly to chokidar would fix it? Though I'm really not sure of the impact of such a change…

**Comment by shawninder** [comment]
I'm pretty sure it would fix it, but it might indeed be tricky to allow this without breaking things in existing code. Nodemon would have to differentiate the current pattern from a regular expression, but the path separator `/` and regular expression literal character `/` are the same character, so this is not trivial.

If, in addition to `nodemon.json`, nodemon also considered a `nodemon.js`, then we could then pass in a real regexp object instead of just strings... Just a thought

**Comment by shawninder** [comment]
@remy I made a PR which solves the issue: https://github.com/remy/nodemon/pull/1027

Care to take a look?

**Comment by remy** [comment]
Thank you for the work, and I hope this doesn't discourage, but I can't merge a change that makes nodemon even more complicated. Adding *another* way to configure nodemon just makes it harder to understand how to use it. I'd merge a change that silently fixes this, but I can't by adding nodemon.js

**Comment by shawninder** [comment]
Well the other option to solve my issue would be to re-instate the option to have regular expressions by prefixing an ignore string with `:` directly in **nodemon.json** or even in the legacy **.nodemonignore** or super-legacy **nodemon.ignore**.

Any possibility of something like this coming back to nodemon? Do you remember why this was taken out?

I understand the need to keep things simple, but I can't believe I'm the only one who needs more than glob patterns. Chokidar supports anything `anymatch` supports, so it's pretty surprising that nodemon doesn't.

**Comment by PabloMessina** [comment]
Wouldn't it be easier to have "ignore" patterns and "white list" patterns? Say, you ignore everything in the ignore patterns except if they match a white list pattern. Actually, I came here because I'm trying to ignore everything except a specific folder with my  source code (nodemon was restarting my express server just because I modified a line in my package.json, which is totally outside the folder with the server's source code).

**Comment by Siilwyn** [comment]
What about moving away from the JSON config format to JS? A lot of tools support JS configs because they open up capabilities without increasing the complexity. Also writing a config in JS is a lot more forgiving than JSON with it's double quotes and strict comma placement.
