### ISSUE TITLE
Changes are not detected if a path contains special characters

### ISSUE THREAD

**Issue by YSidorka** [remy/nodemon#1011]
Windows
e:\\!--test--!\app.js
![image](https://cloud.githubusercontent.com/assets/19983256/24963071/491219f0-1fa6-11e7-988e-f54f84dc2af0.png)
e:\\!--test--!\nodemon.json
![image](https://cloud.githubusercontent.com/assets/19983256/24963122/6827f80a-1fa6-11e7-8ba4-def406c95cca.png)
Step 1: run app.js
![image](https://cloud.githubusercontent.com/assets/19983256/24963212/a07e7c74-1fa6-11e7-9471-94a56e1e5da7.png)
Step 2: change & save app.js
![image](https://cloud.githubusercontent.com/assets/19983256/24963324/f1bb63c2-1fa6-11e7-9101-61d6801a2bb1.png)
RESULT: no changes
![image](https://cloud.githubusercontent.com/assets/19983256/24963370/12cdf782-1fa7-11e7-9ef8-670154435f02.png)

But everything is ok in this case:
![image](https://cloud.githubusercontent.com/assets/19983256/24963598/b3f9773a-1fa7-11e7-8e6e-0a0bcfe66a8c.png)

**Comment by ntkzwane** [comment]
I've experienced this too, is there any work being done on this issue?
