### ISSUE TITLE
Not starting in windows

### ISSUE THREAD

**Issue by joselevelsup** [remy/nodemon#1012]
So I have been trying to use Nodemon in Windows but each time I run Nodemon with my `server.js` file, it throws this. Mind you I am in a different directory where the file is actually in and not in my root D drive. Works fine in Linux but not in windows. Any idea why this happens?
![nodemon](https://cloud.githubusercontent.com/assets/10066172/25068219/5cb48962-222a-11e7-942d-26838e7ce829.PNG)

**Comment by lulzmachine** [comment]
What does your package.json look like?
