### ISSUE TITLE
nodemon doesn't restart on style files changes(.css and .scss at least)

### ISSUE THREAD

**Issue by arquadrado** [remy/nodemon#1013]
I noticed that nodemon doesn't restart on style files changes(.css and .scss at least). Is there any way to explicitly make nodemon watch for changes in stylesheets?

**Comment by remy** [comment]
Yes, you need to monitor those extensions directly. See docs for help.

**Comment by arquadrado** [comment]
I saw that we can specify the extensions when we start the nodemon but is it possible to add those extensions to the nodemon config file?

**Comment by darrenklein** [comment]
@arquadrado The documentation wasn't explicit about it, but I was able to monitor all of the .js and .css files in my app by adding

`"ext": "js css"`

To my `nodemon.json` file.

**Comment by ratneshchandna** [comment]
> @arquadrado The documentation wasn't explicit about it, but I was able to monitor all of the .js and .css files in my app by adding
> 
> `"ext": "js css"`
> 
> To my `nodemon.json` file.

Only seemed to work once on my end. CSS changes stopped restarting nodemon after a day or two. Checked my `nodemon.json` file just to be sure and found that it wasn't being overwritten or anything (i.e. it had `"ext": "js css" in it)`

**Comment by MindLaborDev** [comment]
Got it to work like this:

`nodemon -e js,scss`
