### ISSUE TITLE
Discord bot - nodemon makes a "clean exit" even though it is not supposed to

### ISSUE THREAD

**Issue by saileille** [remy/nodemon#1015]
I have indeed been writing a Discord bot for a few days now, using just one JavaScript file. When I surpassed the "milestone" of 30 kB in file size, nodemon all of a sudden started clean-exiting at infrequent intervals. I reverted back to the last functioning version, sized 29.9 kB, and everything worked. First, I started trouble-shooting by adding snippets of code from the most recent version, and noticed that whatever I added, the issue always returned. Then, I experimented by adding a lengthy comment to the functional version, and it stopped working, too. I removed the comment, and everything worked just fine once more.

Do you have an idea what the issue could be? I have included a download link to my bot; if you could have a look at it, I would be very grateful.

Download link: http://www.mediafire.com/file/dcg9z0b85x7cjt9/DiscordBot.zip

bot.js - Stable version with the comment included.
bot_stable.js - Stable version without the comment.
bot_latest.js - I noticed the issue first with this version.

P.S. It seems the clean-exiting happens occasionally with the stable version as well, but not nearly as often as with the others.

And finally, a screenshot from the command prompt:
![image](https://cloud.githubusercontent.com/assets/24235334/25299497/68b9677c-2708-11e7-8045-3b57069e1db7.png)

EDIT: I forgot to mention that I am using nodemon 1.11.0.

**Comment by tgfirefighter** [comment]
q
