### ISSUE TITLE
exec with express 4 causes "clean exit"

### ISSUE THREAD

**Issue by alpalmerxactware** [remy/nodemon#1017]
I'm trying to get nodemon to run my typescript compile via --exec when it restarts the server. I understand that things are a bit wonky under express 4 but that running the nodemon command as "nodemon" should work. and it does. I can access the server via port 3000 etc. 

However, when I add the --exec command, it runs the command, but then I get the following: 

[nodemon] clean exit - waiting for changes before restart

And the server is not accessible. Is this a nodemon issue? or something that I have missed?

**Comment by remy** [comment]
Unlikely, nodemon doesn't need any setup generally.

When you run without typescript do you get the same issue?

**Comment by lukasoppermann** [comment]
I am having the same issue, using `exec: 'ts-node app.js',` in the options. Can I provide and info to help solve this?

**Comment by mrksbnch** [comment]
I have the same issue using `nodemon --exec 'eslint .'`.
