### ISSUE TITLE
Deactivate nodemon through command line flag

### ISSUE THREAD

**Issue by aug-riedinger** [remy/nodemon#1024]
I know nodemon is for dev environment.

But in order to refactor my scripts, I'd like to write:

```
nodemon --active $($NODE_ENV == 'development') app.js
```

so that the command remains the same in production. Would that make sense?

**Comment by remy** [comment]
Nodemon shouldn't touch a live environment at all. Typically this is done through `npm run dev` vs `npm start`. Or the conditional can be via the environment, but I won't support anything that makes it easier to (accidentally) include nodemon in a production flow (sorry!).
