### ISSUE TITLE
Error While Installing npm install nodemon

### ISSUE THREAD

**Issue by asheeshthakur** [remy/nodemon#1029]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\nodemon\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "nodemon"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! file C:\Users\acer\AppData\Roaming\npm-cache\is-number\2.1.0\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: C:\Users\acer\AppData\Roaming\npm-cache\is-number\2.1.0\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     D:\study\Node\App3\npm-debug.log

**Comment by lulzmachine** [comment]
Sounds like your is-number package is broken. Try to to clear your cache they install again? Something like `npm cache clear` then `npm i`

**Comment by stguitar** [comment]
i had the same error, and clearing the cache didnt resolve it for me.

**Comment by loremarguimaraes** [comment]
It worked for me, thanks!

**Comment by crownlessking** [comment]
Worked for me also. *Thanks*.

**Comment by RohitoOo** [comment]
Clearing the cache did not work for me.

**Comment by suresh-anumolu** [comment]
Looks like Malware bytes blocking some of npm installation folders, pausing the antivirus should help in some of the cases

**Comment by ankitbhadana** [comment]
The following trick worked for me:
1. I added an entry for nodemon in my package.json and specified a version 
2. Hit "npm install" in the terminal. Finally, I could see nodemailer folder in the node_modules.
3. Added an entry in my package.json as follows:
"scripts": {
  "serve": "nodemon server.js" //server.js being my launch file
}

This trick has almost always worked for me.

**Comment by HamzaJirah** [comment]
**npm cache clear** didn't work until i added --force flag. So, run, 
**npm cache clear --force** if **npm cache clear**  doesn't work.
Hopefully, this helps someone.

**Comment by isaacssemugenyi** [comment]
> 
> 
> The following trick worked for me:
> 
>     1. I added an entry for nodemon in my package.json and specified a version
> 
>     2. Hit "npm install" in the terminal. Finally, I could see nodemailer folder in the node_modules.
> 
>     3. Added an entry in my package.json as follows:
>        "scripts": {
>        "serve": "nodemon server.js" //server.js being my launch file
>        }
> 
>     4. Hit "npm run serve"
> 
> 
> And, nodemon started working like a charm for me.

You are a lifesaver man, this has worked for me

**Comment by Dev-Harmattan** [comment]
npm cache clear --force 
it really work for me.
thanks.

**Comment by PreetSingh619** [comment]
Worked for me as well. Thanks!!

**Comment by fredozone** [comment]
i tried with this code and worked for me:
- copy and paste the next code in the terminal
sudo npm install nodemon --save -g

**Comment by anash3420** [comment]
> The following trick worked for me:
> 
> 1. I added an entry for nodemon in my package.json and specified a version
> 2. Hit "npm install" in the terminal. Finally, I could see nodemailer folder in the node_modules.
> 3. Added an entry in my package.json as follows:
>    "scripts": {
>    "serve": "nodemon server.js" //server.js being my launch file
>    }
> 4. Hit "npm run serve"
> 
> And, nodemon started working like a charm for me.

Damn man, nothing worked for me but this worked!! Kudos !

**Comment by henil0604** [comment]
yeyyyyyyyyyyyyyyyyy! Clearing cache Worked for me

**Comment by osasereweb** [comment]
1. I added an entry for nodemon in my package.json and specified a version

2. Hit "npm install" in the terminal. Finally, I could see nodemailer folder in the node_modules.

3. Added an entry in my package.json as follows:
   "scripts": {
   "serve": "nodemon server.js" //server.js being my launch file
   }

4. Hit "npm run serve"

This also worked for me

**Comment by amit-1712** [comment]
amit@amit-VivoBook-15-ASUS-Laptop-X507UAR:~/Desktop/love$ npm install nodemon -global
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/nodemon/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/amit/.npm/_logs/2021-06-11T06_43_20_659Z-debug.log

**Comment by swetachauha** [comment]
npm install nodemon --save -g
This worked for me

**Comment by YahyaFTW** [comment]
> i tried with this code and worked for me:
> 
> * copy and paste the next code in the terminal
>   sudo npm install nodemon --save -g

thanks a lot ,you are a lifesaver, it worked for me
