### ISSUE TITLE
Evaluate --exec on restart

### ISSUE THREAD

**Issue by Diokuz** [remy/nodemon#1030]
@remy what do you think about evaluating `--exec` arg each time `nodemon` restart the script?

For example, I tried to do such a thing:

```
.PHONY: nodemon
nodemon: rev
	nodemon --watch server --watch .env --watch config -e js,tmpl,env \
	--exec "test -f .env && export eval `cat .env` || true && node ./server/index.js"
```

but it only evaluates `.env` file once, at the first run.

I think I'll use `dotenv` now. But anyway, do you think it is a good idea (to evaluate `--exec` string each time), or bad?

**Comment by mistralol** [comment]
It does. You simply don't pass it what you think you are passing because you don't understand that bash is passing the contents of .env to nodemon rather than the `cat .env`. You can test this on a shell script yourself by running

echo "test ; `cat /proc/loadavg`"
