### ISSUE TITLE
Ignore pattern with wildcard matching root dir

### ISSUE THREAD

**Issue by slikts** [remy/nodemon#1033]
nodemon 1.11.0

If the root dir is named `bla-example` and nodemon is started with `nodemon --ignore "example/*"`, it somehow matches the ignore pattern to the root directory and stops monitoring for any changes. Matching the pattern to the root directory doesn't make sense, and it's doubly-broken, since the pattern isn't `*example/*` so it shouldn't match anyway.

**Comment by sbarwe** [comment]
Under bash shell etc. you need tp disabled wildcard expansion with (set -o noglob) before execution .
E.g. set -o noglob && nodemon --ignore "example/*"

or even better: use a nodemon config file and execute with nodemon --config myconfig.json
