### ISSUE TITLE
Option to allow stdin to be inherited

### ISSUE THREAD

**Issue by binki** [remy/nodemon#1036]
I have a finicky process which only works if stdin is not a pipe. How can I tell `nodemon` to not mess with the stdio streams? If I do `nodemon -I` it still intercepts stdin.

**Comment by VictorioBerra** [comment]
+1 im using blessed and nothing is clickable. It just vomits out input sequences on my screen.

**Comment by seventyeight** [comment]
+1 I'm using blessed and no input possible when running with nodemon.

**Comment by remy** [comment]
Can anyone create the simplest test case that I can test with? Or even better, dig into the code with a PR to fix?

**Comment by dominykas** [comment]
I am able to reproduce odd behavior with the `readline` example code from node docs:
```
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

rl.question('What do you think of Node.js? ', (answer) => {
  // TODO: Log the answer in a database
  console.log(`Thank you for your valuable feedback: ${answer}`);

  rl.close();
});
```

Behavior:

* When running with `node`, this exits after it receives an answer.
* When running with `nodemon` it seems to receive the answer, but does not exit. It also accepts `rs` to restart.
* When running with `nodemon -I` it seems to not receive the answer

**Comment by systemmonkey42** [comment]
Can you add '-I' to the help? Nodemon help is missing options.
