### ISSUE TITLE
nodemon and inquirer.js don't work together

### ISSUE THREAD

**Issue by imkimchi** [remy/nodemon#1041]
To use `list` feature of inquirer, user uses arrow keys to move list on menu.

but everytime I use arrow keys, I just get random characters like `^[[B^[[B^[[B^[[B^[[B^[[B` I'm definitely sure It's nodemon's issue because It works fine when I run this without nodemon. 

Does nodemon support input like arrow keys? if not, It'd be great if we can make the feature

**Comment by imkimchi** [comment]
I just found a same issue in inquirer repo
https://github.com/SBoudrias/Inquirer.js/issues/429

**Comment by remy** [comment]
I wouldn't recommend trying to use nodemon with inquirer. It becomes a mess of input. Sorry.

**Comment by imkimchi** [comment]
would you merge if I make a PR for the feature though?

**Comment by remy** [comment]
I'd rather hear how it would work first. A core design principle of nodemon
is: less features - which has already spiraled out of control, so it would
need to be careful thought through so it makes sense for a broad range of
use cases rather than just a single case..

**Comment by boxpositron** [comment]
I found a solution to this.
You can tell nodemon to stop listening its restart command.
You can find more information about this in faq link below

https://github.com/remy/nodemon/blob/master/faq.md#nodemon-doesnt-work-with-my-repl

**Comment by vinaysharma14** [comment]
Use nodemon command with `--no-stdin` flag.

**Comment by guillempuche** [comment]
*SOLVED*

For me, the solution was setting up `stdin` to `false` (more on [GitHub](https://github.com/remy/nodemon/blob/master/lib/config/defaults.js))
