### ISSUE TITLE
file name with 'coverage' gets ignored

### ISSUE THREAD

**Issue by tsargent** [remy/nodemon#1042]
I have a file in the directory that nodemon is watching named `coverageLineBuckets.js`.  I think the substring `coverage` is causing the file to be ignored.  If it's named `coverage.js`, `fooCoverage.js`, `coverageFoo.js`, changes are not detected.  I've changed it to `cverage.js` and everything works as expected.  

Also it seems to be case-sensitive.  `Coverage` works as expected.

**Comment by tsargent** [comment]
Looks like it might be because of this dependency: https://github.com/novemberborn/ignore-by-default
used here: https://github.com/remy/nodemon/blob/master/lib/config/defaults.js#L1

**Comment by btakita** [comment]
I'm also having an issue within directories that have '.git' (i.e. btakita.github.com).

**Comment by btakita** [comment]
To fix this issue, I overrode the ignoreRoot configuration to include a trailing '/' for each of the directories.

```
{
  "ignoreRoot": [
    ".git/",
    ".nyc_output/",
    ".sass-cache/",
    "bower_components/",
    "coverage/",
    "node_modules/"
  ]
}
```

**Comment by mdrobny** [comment]
@remy Do you see any way to avoid ignoring everything called `coverage*` by default?
It's a big issue I think that when my project is called let's say `coverage-status` nodemon just doesn't work at all
