### ISSUE TITLE
Ignore quotation marks in arguments

### ISSUE THREAD

**Issue by Deilan** [remy/nodemon#1044]
Please make nodemon to ignore quotation marks (`""`) in passed arguments. Some third-party tools generate them automatically which results in nodemon refusing to start.

**Comment by Deilan** [comment]
@remy This is not stale.

**Comment by remy** [comment]
You're going to have to clarify by what you mean by "ignore quotation marks".

If you run: `nodemon test.js "remy sharp"`, then you get this:

```
❯ nodemon test.js "remy sharp"
[nodemon] 0.0.0-development
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node test.js "remy sharp"`
[ '/Users/remy/.nvm/versions/node/v8.9.1/bin/node',
  '/Users/remy/Dropbox/Notes/remysharp.com/test.js',
  'remy sharp' ]
[nodemon] clean exit - waiting for changes before restart
```
vs. without nodemon:

```
node test.js "remy sharp"
[ '/Users/remy/.nvm/versions/node/v8.9.1/bin/node',
  '/Users/remy/Dropbox/Notes/remysharp.com/test.js',
  'remy sharp' ]
```

Same result. The quotes are slurped by the OS.

So I'm not sure what you mean.

**Comment by remy** [comment]
Closing as idle, and with apologies for (me) being so late to reply. Happy to reopen if there's a bug here that I can replicate.
