### ISSUE TITLE
Make a property in config to pass additional arguments before `exec`

### ISSUE THREAD

**Issue by Deilan** [remy/nodemon#1045]
Please make a property (`args` or `runtimeArgs` for example) in `nodemon.json` config file to pass additional arguments before `exec`. It may be unknown for `nodemon` but valid for `node`, e.g. `--debug`, `--debug-brk`, `--inspect`, `--inspect-brk`, etc.

**Comment by Deilan** [comment]
@remy This is not stale.

**Comment by remy** [comment]
I'm testing a feature change that will expose this in the nodemon.json file.
