### ISSUE TITLE
nodemon doesn't see changes if there's brackets ( ) in path on Windows

### ISSUE THREAD

**Issue by ghhv** [remy/nodemon#1047]
Hi,
On Windows 7, discovered that if the file path of the folder includes brackets, nodemon does not see changes to files in the folder. 

I'm using this start in package.json
"start": "nodemon ./index.js --ignore node_modules/ -e js,html,css"

works fine once the brackets in the path were removed. 

Am using version 1.11.0

**Comment by madfrag** [comment]
Windows 10, the same issue

**Comment by Kirill255** [comment]
Windows 8, the same issue
