### ISSUE TITLE
Nodemon crashes first restart then works ok the second one when started like nodemon --inspect=0.0.0.0:9229 app.js

### ISSUE THREAD

**Issue by rluncasu** [remy/nodemon#1050]
```sh
nodemon --inspect=0.0.0.0:9229 /app/server.js
```
inside a container based on
```
FROM node:8.1.0
```
with a shared volume on sources. Whenever I save a file on the sources volume, nodemon restarts but crashes with 
```
[nodemon] restarting due to changes...
  nodemon bus emit: restart +13s
  nodemon bus.emit(exit) via SIGUSR2 +14ms
  nodemon bus emit: exit +0ms
[nodemon] starting `node --inspect=0.0.0.0:9229 /app/server.js`
  nodemon spawning node --inspect=0.0.0.0:9229 /app/server.js +1ms
  nodemon bus emit: start +7ms
  nodemon bus new listener: exit (1) +1ms
  nodemon start watch on: *.* +0ms
  nodemon:watch early exit on watch, still watching (1) +1ms
Starting inspector on 0.0.0.0:9229 failed: address already in use
[nodemon] app crashed - waiting for file changes before starting...
```

Re-saving the same file, again restarts but works ok this time.

**Comment by Thr1ve** [comment]
I ran into this issue as well when using nodemon with the inspect flag within a docker container. Oddly, it only seems to happen when I add [heapdump](https://github.com/bnoordhuis/node-heapdump) to the project along with the requisite python dependency for node-gyp. 

Perhaps this is related to using a native module somehow?

**Comment by lea-anthony** [comment]
This has been an issue for me also. Ideally there'd be a flag specifying a delay between shutdown and startup so that the tcp port has enough time to close.

**Comment by yujiahaol68** [comment]
Just kill inspector and start inspector again
here is our team's solution in our package.json

```
"inspect": "kill-port --port 9229 && node --inspect=0.0.0.0:9229 build/startup.js",
"start_watch_inspect": "nodemon --delay 80ms --watch build/ build/startup.js --exec 'npm run inspect'",
```

**Comment by rluncasu** [comment]
@yujiahaol68 good workaround, just used it, thanks !

**Comment by Dim73** [comment]
@yujiahaol68 What is the kill-port command? I don't have this one

**Comment by yujiahaol68** [comment]
That is a npm package. A command line tool.

**Comment by remy** [comment]
Closing with the work around mentioned earlier.

**Comment by seromenho** [comment]
Nice workaround! Thanks

**Comment by TristanMarion** [comment]
As mentionned [here](https://github.com/remy/nodemon/issues/1346#issuecomment-401218386), instead of the `kill-port` package you can use `fuser` which is an UNIX command.

**Comment by DimitrK** [comment]
If there is no reason to update nodemon, previous version 1.17.4 seems to work trouble free.

**Comment by justinpage** [comment]
@DimitrK Keep in mind that `1.18.7` and above resolves a major vulnerability:

https://github.com/remy/nodemon/commit/21e052e

**Comment by johnbindel** [comment]
Works with fuser command even in alpine images without requiring the kill-port package:

```nodemon --delay 80ms --exec 'fuser -k 56745/tcp; node --inspect=0.0.0.0:56745 ./app/http.js'```

Credit to @abou7mied: https://github.com/remy/nodemon/issues/1346#issuecomment-401218386

**Comment by jwhitmarsh** [comment]
MacOS equivalent for `fuser` which doesn't ship with the `k` flag:

`nodemon --exec lsof -nti:56745 | xargs kill -9; node --inspect=0.0.0.0:56745 index.js`

**Comment by Cleomir** [comment]
> Works with fuser command even in alpine images without requiring the kill-port package:
> 
> `nodemon --delay 80ms --exec 'fuser -k 56745/tcp; node --inspect=0.0.0.0:56745 ./app/http.js'`
> 
> Credit to @abou7mied: [#1346 (comment)](https://github.com/remy/nodemon/issues/1346#issuecomment-401218386)

Adding `--delay 80ms` solved my problem.

**Comment by kasvtv** [comment]
I don't understand how this got closed. This is a pretty common setup and the workaround is hacky.

**Comment by andness** [comment]
I just ran into this and I very much agree with @kasvtv, it seems very strange to just close the issue. Running dev environments in docker containers seems pretty common these days?

**Comment by santiagosemhan** [comment]
Nowaday it's super common to have nodemon running on docker containers, so I think this ticket should be reopened. I don't know how nodemon works internally but I think having an internal flag that indicates to process to close the port and then watch files again could be a simple workaround.

**Comment by remy** [comment]
Short reply - I don't use docker (not once for any client project or side project), so please send PR to fix with tests that show the fix works. Happy to merge. Otherwise, this issue is closed because there's a solution (pending your PRs). Sorry (docker) folks, just saying 'I think this is strange' doesn't solve the core issue. Ta.
