### ISSUE TITLE
Cannot do cleanup on process restart

### ISSUE THREAD

**Issue by kylelamse** [remy/nodemon#1051]
So this has been frustrating me for hours.  I made a simple script that borrows from the example in the docs:
## test.js
```javascript
process.once('SIGUR2', function() {
	console.log('Doing cleanup here...');
	gracefulShutdown(function () {
	  process.kill(process.pid, 'SIGUSR2');
	});
});

while(true){}
```

I try to restart the server, and should expect the message `Doing cleanup here...` to be displayed in the console.  Here is what I actually get:
```console
[nodemon] 1.11.0
[nodemon] to restart at any time,
[nodemon] watching: *.*
[nodemon] starting `node test.js`
rs
[nodemon] starting `node test.js`
```

Why am I not getting that `console.log` statement?

**Comment by kevn-xyz** [comment]
I think `while (true)` hogs the event loop. Try using `process.stdin.resume();` instead of that.

**Comment by remy** [comment]
@kevn-xyz is right. The tight loop won't release the CPU
