### ISSUE TITLE
Cannot read property 'sort' of undefined

### ISSUE THREAD

**Issue by stevenvachon** [remy/nodemon#1058]
```js
nodemon({ watch: ['dir/file1', 'dir/file2'] })
```
When overwriting one of those files, I get:
```
Uncaught TypeError: Cannot read property 'sort' of undefined
      at match (node_modules/nodemon/lib/monitor/match.js:132:22)
```

**Comment by stevenvachon** [comment]
I dunno what happened, but I'm no longer experiencing this issue after waking my computer from sleep.

**Comment by Izhaki** [comment]
I do!

**Comment by andrewquartey** [comment]
has any one been able to resolve this issue?

**Comment by remy** [comment]
@andrewquartey if you're seeing nodemon crashing can you file a new issue with full details? This issue is likely unrelated as there's been a number of new releases since it was opened. Thanks!
