### ISSUE TITLE
Cannot start nodemon

### ISSUE THREAD

**Issue by zwilliamsdev** [remy/nodemon#1063]
I am having an issue with nodemon both globally and locally where in module.js it cannot find the nodemon.js module?

```
$ nodemon app.js
module.js:487
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\Git\node_modules\nodemon\bin\nodemon.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
$ node --version
v8.1.3
$ npm --version
5.0.3

```

**Comment by Diplomat82** [comment]
Did you get this fixed? I'm having the same error?

**Comment by zwilliamsdev** [comment]
I managed to fix it on my own however I am sorry to admit I no longer remember what I did. I think I reinstalled Node and it started working. Cheers and good luck! Sorry I can't be of more help.

**Comment by Diplomat82** [comment]
lol 
Thanks
