### ISSUE TITLE
readline.on("line") writes extra line when using nodemon

### ISSUE THREAD

**Issue by ben-denzer** [remy/nodemon#1064]
```
const readLine = require("readline");
const rl = readLine.createInterface({
    input: process.stdin,
    output: process.stdout
});

rl.on("line", input => {
    console.log(`input is ${input}`);
});
```

Input:
Hello World

Expected:
Hello World
input is Hello World

Actual:
Hello World
Hello World
input is Hello World

This works as expected using 'node app.js', (node 6.x and 8.x) but not when using 'nodemon app.js'

**Comment by remy** [comment]
Are you using the readline stdin thing option in nodemon? I forget what it actually is, someone else needed it so it's used rarely

**Comment by ben-denzer** [comment]
I found this in the docs, is this what you're referring to? But the answer is no, I'm not doing anything nodemon specific - no config file or any other command line arguments.

### Pipe output to somewhere else

nodemon({
  script: ...,
  stdout: false // important: this tells nodemon not to output to console
}).on('readable', function() { // the `readable` event indicates that data is ready to pick up
  this.stdout.pipe(fs.createWriteStream('output.txt'));
  this.stderr.pipe(fs.createWriteStream('err.txt'));
});

**Comment by ilya-moskovtsev** [comment]
Fixed by adding to package.json:
"nodemonConfig": {
    "stdin": false
}
