### ISSUE TITLE
Consider updating dependency on package "touch".

### ISSUE THREAD

**Issue by blieque** [remy/nodemon#1072]
Currently `nodemon` depends on v1.0.0 of [`touch`](https://github.com/isaacs/node-touch/). This version creates a shell command called `touch`, which takes precedence over the usual coreutils `touch` if an NPM `.bin` directory is present early in the `$PATH` environment variable. As this is the case when using `npm run <script>`, one has to override `$PATH` or reference `touch` as `/usr/bin/touch` in such scripts.

The name of the CLI installed by the package was changed to `nodetouch` in v2.0.0 ([commit](https://github.com/isaacs/node-touch/commit/8fe84ea23bb1048453b175c59dbc6d2857914b7a)). To save me from the torturous trauma of one unnecessarily long line in a Makefile, could this be updated?

**Comment by KarboniteKream** [comment]
Based on commits, the `touch` package can be updated to v2.0.2 without an issue.

**Comment by hxsf** [comment]
+1, update the touch > v2.0.0
