### ISSUE TITLE
Deprecation warning in Node 8.2.1 regarding os.tmpdir()

### ISSUE THREAD

**Issue by randyxli** [remy/nodemon#1073]
I'm seeing the following deprecation warning after upgrading to Node 8:
```
(node:31493) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```
This change was introduced in Node 7.0.0: https://github.com/nodejs/node/commit/5e5ec2cd1e

I've traced the deprecation warning to the package `os-tmpdir`, which comes from the following dependency chain: dependency `configstore`. 
`nodemon` -> `update-notifier` -> `configstore` -> `os-tmpdir`

All the dependencies in this chain except for `nodemon` no longer us `os-tmpdir`, so my suggested action is to upgrade to `nodemon` 2.0.0 or above (see https://github.com/yeoman/update-notifier/commit/f1de1bfd71d11cf57675b562e115b13875bbe9eb#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

**Comment by remy** [comment]
Fixed and live.

**Comment by JaylyLiu** [comment]
Sorry, but how you solved the problem ?
