### ISSUE TITLE
Send an extra environment variable on restart only

### ISSUE THREAD

**Issue by msikma** [remy/nodemon#1075]
I'm running Nodemon to live reload my Express app during development.

One of the things I do is I open a browser window with the root page when the server is started. But I've had to disable that, because when updating any code, Nodemon causes a restart, which causes the page to be reopened.

If I could get an extra environment variable that is only set on restart, I could just skip the code that opens the browser window.

**Comment by remy** [comment]
Closing as per details on #1077.
