### ISSUE TITLE
Regarding Recommend Practices For NodeJs Restarting

### ISSUE THREAD

**Issue by mdemarco1234** [remy/nodemon#1078]
Hello,

I have read various articles and I need to know the recommended practice for production. We certainly want to minimize downtime. If I have a 1000 people using the server and I do a file change and it restarts we are in trouble particularly if signatures or interfaces are changed. We have a WebApi and another Server for the Angular2 Client. Is node. I think there are use cases where you have to shutdown the server as in a interface changes so that the client side service calls and the server side are always in sync. Let me know the use cases for which we need to send out a maintenance message versus ones where a quick restart can occur.

**Comment by remy** [comment]
Best practice for production: do not use nodemon for production.

Thanks.

**Comment by mdemarco1234** [comment]
Hi,
 
    I need an approach that minimizes any downtime if a restart is not needed and if needed I need to know the best way to restart other than manually in production. What tools will do this? Can you point me to a link?

Regards,

Michael
