### ISSUE TITLE
nodemon not restarting when using --ignore

### ISSUE THREAD

**Issue by skleeschulte** [remy/nodemon#1079]
Using `nodemon ./bin/www`, everything works fine and my express app is restarted when files change. I have a folder `dev` at the project root which I want to exclude from triggering restarts, so I tried `nodemon ./bin/www --ignore dev/`, but this leads to nodemon not restarting at all anymore.

This is the output with `--verbose` added:

    > nodemon ./bin/www --verbose --ignore dev/
    
    [nodemon] 1.11.0
    [nodemon] to restart at any time, enter `rs`
    [nodemon] ignoring: .git .nyc_output .sass-cache bower_components coverage C:\dev\myproject\api\node_modules/**/* C:\dev\myproject\api\dev/**/*
    [nodemon] watching: *.*
    [nodemon] watching extensions: js,json
    [nodemon] starting `node ./bin/www`
    [nodemon] child pid: 7288
    [nodemon] watching 0 files

I use Windows 7 x64

**Comment by skleeschulte** [comment]
It looks as if the problem is that the whole project is in a folder called `dev`. Changing the command to `nodemon ./bin/www --ignore ./dev/` (`./dev/` instead of `dev/`) does work.

Notably, nodemon reports that it is ignoring the exact same folders when using the `--verbose` option:

    ignoring: .git .nyc_output .sass-cache bower_components coverage C:\dev\myproject\api\node_modules/**/* C:\dev\myproject\api\dev/**/*

At least the output of the verbose option for "ignoring" is wrong.

**Comment by remy** [comment]
Thanks 👍

**Comment by skleeschulte** [comment]
Has this issue been resolved (fixing the debug output)?
