### ISSUE TITLE
nodemon is reading package.json scripts, but not running them properly?

### ISSUE THREAD

**Issue by djMax** [remy/nodemon#1080]
It seems that in absence of other info, nodemon is reading the "scripts.start" property in package.json and then running it directly. But this isn't the same as "npm run start" because it misses all of the env setup that npm does. It seems like if it reads the exec command from scripts, it should exec `npm start`, not shell the contents of that key.

**Comment by remy** [comment]
No, it doesn't and can't full pick up the npm ENV and bin helpers that npm does from the scripts. I suggest not using that approach if possible.
