### ISSUE TITLE
Is there an option to only run when files change?

### ISSUE THREAD

**Issue by SteveALee** [remy/nodemon#1082]
I'm using (and loving) nodemon to run a deploy npm script. 

I'd like it to not run the script **until** files have changed, ie not when I run nodemon.

Is there such an option? I know it's a little different than the initial use case.

**Comment by remy** [comment]
Yes. From `nodemon --help`:

```-C, --on-change-only ..... execute script on change only, not startup```

**Comment by SteveALee** [comment]
I only read the readme :)
