### ISSUE TITLE
Nodemon isn't working on basic node server

### ISSUE THREAD

**Issue by Jakobud** [remy/nodemon#1086]
I have a barebones Node server:

index.js
```
const http = require('http')  
const port = 3000

const requestHandler = (request, response) => {  
  console.log(request.url)
  response.end('Hello Node.js Server!')
}

const server = http.createServer(requestHandler)

server.listen(port, (err) => {  
  if (err) {
    return console.log('something bad happened', err)
  }

  console.log(`server is listening on ${port}`)
})
```

When I run `nodemon` in this directory I get:

```
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
server is on 8888
```

And now whenever I change index.js, nothing happens. Server does not restart. I don't know how to simplify this any more than this. There are no 3rd party dependencies here or anything. It simply does not work at all.

**Comment by dvdknaap** [comment]
I got the same issue on 

> [nodemon] Looking in package.json for nodemonConfig
> [nodemon] 1.12.0
> [nodemon] reading config /project/api/package.json
> [nodemon] to restart at any time, enter `rs`
> [nodemon] ignoring: /project/api/.git/**/* .nyc_output .sass-cache bower_components coverage /project/api/node_modules/**/*
> [nodemon] watching: *.*
> [nodemon] watching extensions: js,json
> [nodemon] starting `node socketAPI.js`
> [nodemon] child pid: 5461
> [nodemon] watching 11 files
> Server listening at port 3000

i'm using vagrant with debian 8

**Comment by Jakobud** [comment]
I have discovered the issue. It is because it's on Vagrant. The `-L` option is the key. This uses a legacy polling method for watching the file changes. The underlying issue is something to do with how the shared folder is setup between the virtual and host systems.
