### ISSUE TITLE
Windows: nodemon is passing executable and parameters to OS as one command

### ISSUE THREAD

**Issue by csebold** [remy/nodemon#1089]
When I run nodemon with no configuration and package.json has under "scripts" a "start" script that runs my node package with "node server.js" or "node ./server.js" or any variation that makes sense, nodemon is telling Windows to run a command called "node server.js" not a command called "node" running parameters "server.js".

True since 1.12.0 came out, 1.11.1 is fine.

**Comment by alex-shamshurin** [comment]
The same issue is here. Is there a temporary workaround?

**Comment by alexlopezc** [comment]
Same here executing npm tasks with nodemon on Windows.

Meanwhile, you can set  version 1.11.1 in package.json
