### ISSUE TITLE
Nodemon crashes when updated to version 1.12.0

### ISSUE THREAD

**Issue by gittestcoder** [remy/nodemon#1091]
Hello, today I updated nodemon to version 1.12.0 (from 1.10.2). When I run my npm command I get the following error: 

> '\"npm run build:dev && node compiled\server.dev.js\"' is not recognized as an internal or external command,
> operable program or batch file.

When I downgrade back to 1.10.2 it works fine. I'm using "reactGo" as my boilerplate so you can see how the package.json looks here: https://github.com/reactGo/reactGo/blob/master/package.json.

**Comment by remy** [comment]
Can you replicate with a simplified example and help diagnose?

**Comment by jameswilddev** [comment]
I am also seeing this.

**Comment by jameswilddev** [comment]
Here's the simplest repro; just put this package.json in an empty dir and `npm install`, should print the NPM version to the console:
```
{
  "scripts": {
	"postinstall": "nodemon --watch Anything --exec \"npm -v\""
  },
  "devDependencies": {
    "nodemon": "1.11.0"
  }
}
```

Replace with the latest version and you get the above error:
```
{
  "scripts": {
	"postinstall": "nodemon --watch Anything --exec \"npm -v\""
  },
  "devDependencies": {
    "nodemon": "1.12.0"
  }
}
```

**Comment by gittestcoder** [comment]
Thanks @jameswilddev, you beat me to it

**Comment by Potentiator** [comment]
I am also seeing this when I updated to the latest version. Rolling back to 1.11.0 fixed it.

**Comment by graham-sportsmgmt** [comment]
Can confirm this also breaks when you run a basic express app.  Just run these three commands to replicate:

```
express
npm install
nodemon
```

> '\"node .\bin\www\"' is not recognized as an internal or external command,
> operable program or batch file.

Quitting nodemon and running `node .\bin\www\` works just fine.

**Comment by remy** [comment]
If anyone with Windows can help with a PR, I'd be mighty grateful.

**Comment by jameswilddev** [comment]
I am unable to reproduce this with 1.12.1, 1.12.2, 1.12.3 or 1.12.14, looks fixed?

**Comment by remy** [comment]
@jameswilddev woot!

**Comment by yogain123** [comment]
Apparently, the issue still persists with new updates.
I downgraded to 1.10.0 and its working fine

**Comment by remy** [comment]
@yogain123 no real details included in your report, but I'm glad you have a work around 👍
