### ISSUE TITLE
Unexpected quotation mark behavior on Windows 10

### ISSUE THREAD

**Issue by tedcurrent** [remy/nodemon#1092]
On Windows 10 nodemon completely disregards the fact that a command line argument is wrapped in quotation marks. The image below explains the whole situation. 
![nodemon_plsss](https://user-images.githubusercontent.com/7895034/30241224-d74a4420-9587-11e7-9110-875ea6c54b67.PNG)
Does anyone have a workaround for this? Can anyone reproduce this? What is really at fault here? There's no difference in behavior between these commands on OS X, but I'd like to get this working on Windows.

**Comment by remy** [comment]
Bit late to the party, but did you try running that outside of npm, and does it make a difference?

i.e. `nodemon notindex.js -- -b "hello - world"`

**Comment by remy** [comment]
Closing due to idle. Happy to reopen if there's still an issue around this.
