### ISSUE TITLE
update to v1.12.0 cause crash when pass argument to node

### ISSUE THREAD

**Issue by lerit** [remy/nodemon#1095]
i update nodemon from v1.11.0 to v.12.0
but it fail when i use it.
this is my nodemon.json:
  "execMap": {
    "js": "node --harmony --trace-warnings"
  },
the error mean:"node --harmony --trace-warnings" Is Not internal or external commands
i must remove the argument or degrade to version 1.11.0, and it work fine again
![1 11](https://user-images.githubusercontent.com/4743467/30356033-82ec9132-9869-11e7-84dd-33a015ec678a.png)
![1 12](https://user-images.githubusercontent.com/4743467/30356034-82ef055c-9869-11e7-9e8b-bca77e4efd28.png)

**Comment by lpgera** [comment]
I am getting the same error with node --trace-warnings, after updating to nodemon 1.12.0.

Windows 64bit, Node 8.3.0

```
[nodemon] starting `node --trace-warnings ./src/server.js`
[nodemon] child pid: 28200
'\"node --trace-warnings\"' is not recognized as an internal or external command,
operable program or batch file.
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by remy** [comment]
Can someone try a PR to fix this windows issue? Obviously ppl are seeing
it, i just don't have Windows to hand to fix as easily. Thanks in advance.
