### ISSUE TITLE
Cannot find module 'es6-promise' on 1.12.1

### ISSUE THREAD

**Issue by MickL** [remy/nodemon#1097]
I updated to 1.12.1 and get the error:
`Cannot find module 'es6-promise'`

Node-Version: v8.2.1

**Comment by remy** [comment]
That's the output you get when you run `nodemon` with no arguments?

**Comment by MickL** [comment]
Yes:

test.js: `console.log('hello');`
Run: `nodemon test.js`

**Comment by remy** [comment]
Can you:

```
npm un -g nodemon
npm i -g nodemon
```

Or if local, obviously omit the `-g`.
