### ISSUE TITLE
Nodemon keeps restarting endlessly if a file has been changed

### ISSUE THREAD

**Issue by ramseydsilva** [remy/nodemon#11]
My platform is ubuntu:

Linux Ubuntu-1010-maverick-64-minimal 2.6.35-25-server #44-Ubuntu SMP Fri Jan 21 19:09:14 UTC 2011 x86_64 GNU/Linux

Node version 0.2.6

Nodemon version 0.2.0

Not sure if this is a bug, but any suggestion is appreciated.

**Comment by woutercleymans** [comment]
I have the exact same issue. Server now restarts 2 to 4 times (random) after running `sudo touch ./`

**Comment by remy** [comment]
Can you confirm the time on the VM and the local mac machine? (I'm looking
for time drift)

**Comment by woutercleymans** [comment]
It looks like the problem is gone now. I haven't changed anything on my VM or host os. Probably vagrant reload or restart of host os fixed the issue.

Time:
Guest os: **mon Jan 5 06:29:04 UTC 2015**
Host os: **mon 5 jan 2015 07:28:51 CET**

**Comment by oferh** [comment]
getting this issue when setting node timezone to UTC:

```
let server = nodemon({
        script: "./built/app.js",
        watch: ["built/**/*.*"],
        env: {
            "NODE_ENV": process.env.NODE_ENV || "development",
            "TZ": "UTC+0"
        },
        delay: 300,
        exec: cmd,
    });
```

tried running gulp with `TZ="UTC+0"` too but it didn't help
