### ISSUE TITLE
Nodemon doesn't watch files

### ISSUE THREAD

**Issue by piton13** [remy/nodemon#1101]
The nodemon doesn't watch files of application when path to directory where located application contains exclamation point.
version 1.12.1.
path to folder example: 'some-path/!node-example/node-application'

**Comment by dvdknaap** [comment]
I have the same thing when i execute nodemon with the absolute path i doesn't watch any files
`sudo nodemon -L /folder/directory/nodejsFile.js -V`
> The output will be '[nodemon] watching 0 files'

When i first go to the path and the only use the filename it sees my files
```
cd /folder/directory/
sudo nodemon -L nodejsFile.js -V
```
> The output will be '[nodemon] watching 12 files'

**Comment by remy** [comment]
This path handling is intended behaviour.

**Comment by dvdknaap** [comment]
Maybe create an new param where you can specify the path then ?
