### ISSUE TITLE
Watch all kind of files in the directory

### ISSUE THREAD

**Issue by gabrielfern** [remy/nodemon#1103]
Hey, it seems that nodemon only take care about js files, i'm wanting to add a full directory to watch over, not only js, like html files, but i need to add every file in a '-w'  to achieve, how can i set the behavior to when i pass a full directory to the nodemon, it watch to all kind of files? Instead of need to add every file that are not js manually.

**Comment by remy** [comment]
You can manage extensions using the `--ext` argument
