### ISSUE TITLE
Auto restarting when REQUEST

### ISSUE THREAD

**Issue by shihabmridha** [remy/nodemon#1104]
When I call an endpoint using Postman Nodemon auto restart so I get no response error. If I go through a browser to that endpoint it shows "Method Not Allowed".

**Comment by remy** [comment]
nodemon doesn't have endpoints. It's a wrapper to the executable script you give it… Closing as I'm fairly sure this doesn't match up to what nodemon does.

**Comment by shihabmridha** [comment]
Actually what I meant is, I send request to my application's endpoint.
If I start my app using usual "node app.js" and send request to my app using postman it response. But starting my app using nodemon doesn't response to the sent request from postman.
