### ISSUE TITLE
Idea: Add `npmmon` as a replacement for `npm`

### ISSUE THREAD

**Issue by scottrippey** [remy/nodemon#1112]
I most often use `nodemon` for running my `npm` scripts, by doing `nodemon -x "npm run test"` etc.
It' would be awesome if installing `nodemon` would also install a global `npmmon`!

**Comment by scottrippey** [comment]
I mean, for now, I just added this to my `.bash_profile`:
```
npmmon() {
	nodemon -x "npm $@"
}
```

**Comment by remy** [comment]
I think that's a blog post/faq tip 👍 😉
