### ISSUE TITLE
`debug`/`inspect` switches in api?

### ISSUE THREAD

**Issue by JasonKleban** [remy/nodemon#1114]
In my webpack.config.js (webpack 3) I'm trying to enable the debugger for a `webpack --watch` configuration.  The nodemon part itself works, but I can't get the debugger going.  I've tried:

`new NodemonPlugin({ debug: true})`
`new NodemonPlugin({ inspect: true})`
`new NodemonPlugin({ inspect: 9229 })`

The nodemon documentation only mentions the cli `--debug` flag.  And nothing for inspect, although there's mention of it in *issues*.

How can we debug with webpack 3 `--watch` and the nodemonplugin?

Thanks!

**Comment by remy** [comment]
Isn't it `nodeArgs`? That said, I wrote nodemon and I've never seen
NodemonPlugin.

**Comment by JasonKleban** [comment]
migrated to the plugin issue board.

**Comment by Izhaki** [comment]
For late arrivals. From [nodemon's tests](https://github.com/remy/nodemon/blob/be5d4e8d13a6dcc16c65b5bce59edef54496a8ae/test/cli/exec.test.js#L36):

```javascript
  it('should support --debug=XXXX', function () {
    var options = exec({ script: 'app.js', nodeArgs: [ '--debug=9999' ]});
    var cmd = toCmd(options);
    assert(cmd.string === 'node --debug=9999 app.js', cmd.string);
    assert(options.exec === 'node');
    assert(options.ext.indexOf('js') !== -1);
  });
```
