### ISSUE TITLE
events.js:182 throw er; // Unhandled 'error' event Error: spawn cmd ENOENT

### ISSUE THREAD

**Issue by Mohammad-Quanit** [remy/nodemon#1118]
Hello guys,
I installed nodemon by npm install nodemon -g and it installed successfully but when I m starting nodemon it gives me an error. Please help me.
Here's the error code.

  `events.js:182
      throw er; // Unhandled 'error' event^
     Error: spawn cmd ENOENT
    at _errnoException (util.js:1021:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by rajiretheesh** [comment]
I have the same issue..,

**Comment by Mohammad-Quanit** [comment]
bro I have solved this issue.
Copy this and paste it to environment variables path option.
c:\windows\system32

**Comment by OmarJaber** [comment]
Same error

**Comment by remy** [comment]
Closing - @Mohammad-Quanit answered himself.

**Comment by madhav1993** [comment]
Same error,
If You are a windows user having a 32bit system then try to use Node js cmd.
In my case, it's working.
