### ISSUE TITLE
Can I change colors of Nodemon stdout output?

### ISSUE THREAD

**Issue by wzup** [remy/nodemon#1123]
Currently the output is yellow and green:

![nodemon - mingw64 - 2017-10-28 12 32 33](https://user-images.githubusercontent.com/3880497/32131268-80533d36-bbdc-11e7-827f-f0b6c66abe95.png)

Is it possible to set custom colors for example for filenames, or some other lines of the output?

**Comment by remy** [comment]
No, but you can disable them AFAIK
