### ISSUE TITLE
NODE_ENV not set

### ISSUE THREAD

**Issue by wackazong** [remy/nodemon#1125]
When I use 

    NODE_ENV=development nodemon -e js,json,yaml,graphql --use_strict 

then ```NODE_ENV``` ist not set. It works when I use

    NODE_ENV=development nodemon --use_strict  -e js,json,yaml,graphql

I am on a Mac

**Comment by remy** [comment]
I can reopen this issue if a paired down example is provided. I'm fairly sure this is the script running (btw, the use_strict, I think, is being ignored).
