### ISSUE TITLE
How to run the modemon in background?

### ISSUE THREAD

**Issue by a-tomal** [remy/nodemon#1127]
Hi. How to run the modemon in background?

## if I run the modemon by nohup
![vskokx5](https://user-images.githubusercontent.com/22172500/32462797-54a8d5ba-c343-11e7-9351-d528b416a2f9.png)

Thanks!

**Comment by remy** [comment]
I'm not sure. There's a werid thing with `nohup` that I've never solved because I'm not familiar with it. Feel free to take a stab if you can.
