### ISSUE TITLE
Can't get nodemon to restart on file change

### ISSUE THREAD

**Issue by tom-tom-cp** [remy/nodemon#1129]
I'm having trouble getting nodemon to restart on file change. I'm on macOS Sierra 10.12.6. I've tried uninstalling and reinstalling but it didn't work. I looked around for various similar issues but none worked for me. Could you help me solve the issue?

**Comment by fishnux** [comment]
Same issue inside Docker (node:8.9-slim). What's your nodemon version? Mine is 1.12.1.

**Comment by remy** [comment]
@tom-tom-cp you're going to have to provide a lot more information for anyone to be able to help I'm afraid. Will close for now unless there's more information.

**Comment by tom-tom-cp** [comment]
I'm developing applications locally and nodemon doesn't restart on save. 

I installed in following the instructions and I used the -g flag to install it globally. I can fire up the server using the nodemon command, but I always need to use the rs command to restart it manually.

Any commands I can run to help debug?

Any help is appreciated. Thanks.

**Comment by remy** [comment]
Can you provide a pared down version of code that doesn't restart on change
and include your OS, versions and really anything to help people understand
what's going on
