### ISSUE TITLE
Process terminated when ignoring a folder.

### ISSUE THREAD

**Issue by CaballoCarpiano** [remy/nodemon#1130]
Hello! I have been using nodemon the last months without any problem.
Recently I added a folder to the ignore option of my nodemoon.json.  After that nodemon crashes when trying to watch the files, but the worse is that the process of my application don't stop and gets stuck using the port,
The new rule that I added to ignore is:

_"temp/**"_

This is the error that I get:

[nodemon] 1.12.1
[nodemon] reading config E:\workspace\generator\app\nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] ignoring: E:\workspace\generator\.git/**/* .nyc_output .sass-cache bower_components coverage E:\workspace\generator\node_modules/**/* temp/***/* templates/***/* public/***/* app/assets/***/* app/views/***/* games/***/* docs/***/*
[nodemon] watching: *.*
[nodemon] watching extensions: js,json
[nodemon] starting `node app/server.js`
[nodemon] child pid: 9100
[nodemon] watching 31 files
[nodemon] Internal watch failed: Error watching file for changes: EPERM
[nodemon] exiting
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! knotion_templates@1.0.0 start:dev: `nodemon app/server.js --config app/nodemon.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the knotion_templates@1.0.0 start:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Knotion\AppData\Roaming\npm-cache\_logs\2017-11-13T17_00_12_102Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! knotion_templates@1.0.0 start: `npm run start:dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the knotion_templates@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Knotion\AppData\Roaming\npm-cache\_logs\2017-11-13T17_00_12_117Z-debug.log

After that the process continue executing and the output streams gets buggy. I have changed that folder name and it seems to work.

**Comment by remy** [comment]
Seems like nodemon doesn't have permission to read the files: `Error watching file for changes: EPERM`
