### ISSUE TITLE
version 1.12.3 raised the minimum node version to 6.  This breaks our builds

### ISSUE THREAD

**Issue by Noyabronok** [remy/nodemon#1144]
version 1.12.3 raised the node version to >= 6 
https://github.com/remy/nodemon/compare/v1.11.0...v1.12.3

This is breaking installs that specify `engine-strict = true` in .npmrc and the node engine version listed in package.json is < 6.

Is 6 really the minimum supported version for nodemon, or can we set it to something less, like 4?

**Comment by remy** [comment]
1.12.x is making use of more es6 which 4 may not have support for. 

Also: I'm pretty sure 4 is not supported and not part of long term support on node's roadmap (known and open security issues), but also: nodemon is a development tool, so why is it failing a build process? (Obviously I don't know the context of your software).

I can't support unsupported versions of node though.

**Comment by Noyabronok** [comment]
Going from Node 0.8 to 6 should not be a minor but a major version increase.  Our local install is failing because we have `engine-strict=true` in our `.npmrc` file.   Node 4 supports a decent amount of ES6, and you can check the features here http://node.green/

We've been running nodemon under Node 4 without any problems for a while now.  Node 4 is officially supported as maintenance release until April 2018.  Can you please re-open this issue.

**Comment by remy** [comment]
I'm inclined to agree that nodemon should have had a major bump. If you raise a PR that changes the engine down and adds Travis tests back in, and the tests pass, then I'll merge and release. How does that sound?

**Comment by Noyabronok** [comment]
I created two pull request, choose one:
Revert down to Node 0.10: https://github.com/remy/nodemon/pull/1148
Revert down to Node 4: https://github.com/remy/nodemon/pull/1149

**Comment by remy** [comment]
Just had a quick look at both and it looks like neither are passing tests.

**Comment by Noyabronok** [comment]
The tests should be passing.  I'm seeing Travis fail during `npm install`
```
$ npm install 
Error: Failed to replace env in config: ${NPM_TOKEN}
```

**Comment by remy** [comment]
@Noyabronok merge the latest commit from master and you'll get a fix in the `.travis.yml` file for that.

**Comment by Noyabronok** [comment]
@remy Are you referring to https://github.com/remy/nodemon/commit/57c14a2b5867905247442e657f0942cebab35c6d ?
It's already included in my branch

**Comment by remy** [comment]
Damn, yeah, I was. It is possible the `.npmrc` file is left in a cache on the test? (I'll take a quick look at both PRs and clean any caches).

**Comment by remy** [comment]
I'm restarting the #1149 test now with a clear cache - but looking at another PR, I'm getting the sense that my bash command to generate that file on master isn't working.

Aside: you'll need to update the `.travis.yml` file to include the new test targets (i.e. `- '4'`, etc).

**Comment by remy** [comment]
Can you try with this commit added to your branch? https://github.com/remy/nodemon/commit/183add9166507ffbd0b704a13c0a136307a2afc3

**Comment by Noyabronok** [comment]
Doesn't seem to help

**Comment by remy** [comment]
Damnit. I'll have to make a new repo to get this working. I'll try to do this tonight if possible.

**Comment by Noyabronok** [comment]
@remy tests are passing now

**Comment by remy** [comment]
You've not actually tested the code in the target environment though. You need to add the versions you want to add to the .travis.yml file
