### ISSUE TITLE
ENOSPC error on symlinks/local dependencies installed by npm 5.x

### ISSUE THREAD

**Issue by scottdear** [remy/nodemon#1152]
- `nodemon -v`: 1.12.5
- `node -v`: 9.2.0
-  `lsb_release -d`: Ubuntu 16.04.3 LTS
- Command you ran: nodemon server.js

### Expected behaviour 
I'm expecting nodemon to not to throw an error and start the server

### Actual behaviour
I get [nodemon] Internal watch failed: watch /longpath/mainmodule/node_modules/othermodule/node_modules/yetanothermodule/node_modules/andanothermodule/nodemodules/somefile.js ENOSPC

### Steps to reproduce
Create a main package that has local dependencies, e.g. file:../othermodule
In the othermodule package, make it dependent on a local module as well e.g. file:../yetanothermodule
In yetanothermodule give it a local dependency e.g. file:../andanothermodule.

Inside all of the modules include some decent sized dependencies on a regular modules, like aws-sdk.

Inside mainmodule do an npm install

Now I believe this is a problem with the new npm install.  It used to be that npm install would make copies of othermodule, yetanothermodule and andanothermodule inside of mainmodule/node_modules.

With the new npm, it instead makes symlinks inside of mainmodule/node_modules that point to ../../othermodule, etc.

For development, I was using npm link to create a symlink for only the modules I wanted to debug.  I noticed that if I had too many symlinks I would get the above described error.  Removing the symlinks in mainmodule/node_modules fixed the issue.

I can work around the issue by doing "nodemon -i ./node_modules server.js", but then I don't get automatic server restart on changes in these modules.  I realize this may be a problem with the underlying libraries you are using, but I'm hoping there is a reasonable solution.
---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by remy** [comment]
Can you try running this command and retest?

```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

**Comment by scottdear** [comment]
I did try that and I also upgraded nodemon to 1.5.0-alpha4 and I did not
get the error, but it never started the server.

As it turns out, I ran the test, it failed w/ ENOSPC, then I set the
max_user_watches, then it would not start the server.

This morning on a fresh boot, I retested and it now works.

I imagine that once you get ENOSPC it puts the system into a state where
it will not work, even with the max_user_watches config change, you must
re-boot to reset whatever state was brought about by getting the ENOSPC
error in the first place.

I event added -w ./node_modules just to be sure it was picking up the
symlinked local modules.

Thanks for the quick response, and great tool.  You can close this one
out as a system config issue.  Sorry for the goose chase :)

**Comment by remy** [comment]
No problem.
