### ISSUE TITLE
Never receiving SIGUSR2 signal

### ISSUE THREAD

**Issue by popey456963** [remy/nodemon#1153]
- `nodemon -v`: v1.11.0
- `node -v`: v8.2.1
- Command you ran: `nodemon slave.js`

### Expected behaviour
Listening to `SIGUSR2` allows us to listen to when Nodemon restarts our process.

### Actual behaviour
That signal is never detected.

### Steps to reproduce
Run `nodemon` on:

```
process.once('SIGUSR2', graceful_shutdown)
process.once('SIGTERM', graceful_shutdown)

console.log('Listening to process signals.')

// Don't clean exit.
setInterval(() => {}, 10000)

function graceful_shutdown(sig) {
  console.log('Detected shutdown / restart.')
  process.exit(0)
} 
```

**Comment by remy** [comment]
Can you replicate with current latest nodemon@1.12.x?

And what OS? Thanks

**Comment by popey456963** [comment]
Oh crap, my bad!  I was on Windows, I can't replicate with the latest version.

Thanks for a great development tool! 🙂
