### ISSUE TITLE
Release 1.12.x broke my project which uses grunt-nodemon

### ISSUE THREAD

**Issue by mherodev** [remy/nodemon#1158]
It seems like if you're no longer going to support certain node versions, you'd jump a major version to avoid cases like this. I don't know if there's any way to rectify it now, but we've had to go back and force `nodemon` to `1.11.0` such that `grunt-nodemon` would inherit that version.

**Comment by mherodev** [comment]
I am no semver expert though, so apologies if this is off-base. `grunt-nodemon` being no longer published to makes for its own issue.

**Comment by remy** [comment]
There's a PR in the process of reverting support back to 4.x. Just got some merge issues to solve today (ideally).
