### ISSUE TITLE
Add -L Flag to docs

### ISSUE THREAD

**Issue by rightisleft** [remy/nodemon#1160]
- `nodemon -v`: 1.12.6
- `node -v`: 6.9.1 
- Command you ran: ./node_modules/nodemon/bin/nodemon.js --help

### Expected behaviour

Should show the -L flag from 
https://github.com/remy/nodemon/issues/419

### Actual Behavior

the -L flag is ommited 

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by remy** [comment]
Thanks. Fixed in nodemon@1.12.7

**Comment by AndrewRayCode** [comment]
FWIW my moderately upvoted stackoverflow answer looks like it's popular because --quiet was removed from the main help page in the commit related to this ticket. SO: https://stackoverflow.com/a/44936750/743464

**Comment by remy** [comment]
@AndrewRayCode yeah, that should be on the main help actually - probably replacing the `verbose`.
