### ISSUE TITLE
Cannot use chrome debugger with nodemon v1.12.7 (latest)

### ISSUE THREAD

**Issue by RooSoft** [remy/nodemon#1165]
- `nodemon -v`:
1.12.7

- `node -v`:
v8.9.0

- Command you ran:
`nodemon --inspect index`

### Expected behaviour
Chrome debugger activates and allows step-by-step debugging of the executing node app

### Actual behaviour
Chrome debugger doesn't work.... it does though when replacing `nodemon` by `node`. Used to work flawlessly weeks ago. In fact, that tool was a very important part of my toolset, had to revert to basic node interpreter.

### Steps to reproduce
with an express app in an index.js file, run `nodemon --inspect index`
notice that Chrome debugger doesn't react as it would using `node --inspect index`

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by RooSoft** [comment]
Works with 1.11.1, reverting to that version for now...

**Comment by RooSoft** [comment]
Tried every version up until the 1.12.7 just to find out where this issue started appearing...

Well, I am glad to say that I cannot reproduce that problem anymore. It works in every version I have tried.

Makes me wonder why...

**Comment by RooSoft** [comment]
Reboot... back to non-working state...

**Comment by remy** [comment]
OS? I was testing this last night on Mac and .7 patch was to fix this precise issue…

**Comment by RooSoft** [comment]
MacOS Sierra 10.12.6

**Comment by remy** [comment]
Here's what I'm getting with nodemon@1.12.7:

<img width="898" alt="screen shot 2017-12-14 at 21 00 39" src="https://user-images.githubusercontent.com/13700/34014113-e253b6dc-e111-11e7-944f-94c288d71adc.png">

Based on this setup: https://gist.github.com/remy/968b8937a153127cfae4a173b6000c1e

Can you share a similar screenshot of what you're seeing?

**Comment by RooSoft** [comment]
Using `--inspect`, not `--inspect-brk`, as is the new method in Node 8+ as far as I'm concerned..

**Comment by remy** [comment]
Same thing: 

<img width="890" alt="screen shot 2017-12-14 at 21 04 20" src="https://user-images.githubusercontent.com/13700/34014242-5f271258-e112-11e7-80ba-6a3c94e95d33.png">

It's just my index.js tries to log and exits immediately.

**Comment by RooSoft** [comment]
```
$ nodemon --inspect index
[nodemon] 1.12.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js --inspect index`
2017-12-14 16:05:32.297 debug: ... loading resources from remote host
```

no `Debugger listening` message...

a think I am figuring out though... the command includes an `index.js` between `node` and `--inspect` which seems wrong...

**Comment by remy** [comment]
Can you share a paired down version of your package and index.js in a gist? Similar to this: https://gist.github.com/remy/968b8937a153127cfae4a173b6000c1e - it'll help me understand what's going on (I suspect it's linked to how nodemon is reading your package)

**Comment by RooSoft** [comment]
not using package.json for this, issuing the command by hand in the command line... literally typing `nodemon --inspect index`. not sure what the index.js could do to alter nodemon's work.

**Comment by remy** [comment]
Got it (and am able to replicate).

For now, the work around is `nodemon --inspect index.js` (not `index`). Nodemon isn't expanding out the `index`. I'm not 100% sure it should either - I appreciate node _does_ but nodemon isn't entirely bound to node as the exec.

Need to think whether this is a bug or a documented design decision.

**Comment by RooSoft** [comment]
Yup, it works! Thanks remy!

**Comment by RooSoft** [comment]
I believe I will not be the only one trying to use nodemon that way...

**Comment by Darmikon** [comment]
I've just updated nodemon to `"nodemon": "^1.14.3",` and 
`"start": "cross-env NODE_ENV=development nodemon --inspect ./src",` it started working
`node -v
v7.8.0
` and `nodemon -v
1.14.3
`
