### ISSUE TITLE
Can't install nodemon

### ISSUE THREAD

**Issue by uluhonolulu** [remy/nodemon#1172]
Windows 7, node v8.9.1, npm 1.4.9. Running `npm install -g nodemon` failed, saying it cannot find `remy/pstree`.

Here's the console output:
npm install -g nodemon
npm http GET https://registry.npmjs.org/nodemon
npm http 304 https://registry.npmjs.org/nodemon
npm http GET https://registry.npmjs.org/es6-promise
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/ignore-by-default
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/lodash.defaults
npm http GET https://registry.npmjs.org/touch
npm http GET https://registry.npmjs.org/update-notifier
npm http GET https://registry.npmjs.org/chokidar
npm http GET https://registry.npmjs.org/undefsafe
npm http GET https://registry.npmjs.org/remy/pstree
npm http 304 https://registry.npmjs.org/es6-promise
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/ignore-by-default
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/lodash.defaults
npm http 304 https://registry.npmjs.org/touch
npm http 304 https://registry.npmjs.org/update-notifier
npm http 304 https://registry.npmjs.org/undefsafe
npm http 304 https://registry.npmjs.org/chokidar
npm http 404 https://registry.npmjs.org/remy/pstree
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'remy/pstree' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'nodemon'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "nodemon"
npm ERR! cwd D:\Projects\qwatch
npm ERR! node -v v8.9.1
npm ERR! npm -v 1.4.9
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\Projects\qwatch\npm-debug.log
npm ERR! not ok code 0

**Comment by remy** [comment]
Please update npm to 5 (npm v1 doesn't have scoped package support…not quite sure how you managed to keep on latest node and be on super old npm! 😺 )

**Comment by udaykiranvasireddy** [comment]
We have the same issue with node versions 8 and 6, npm version 5.6.

**Comment by uluhonolulu** [comment]
@remy thanks, removing the old version of npm did it!

**Comment by svb007** [comment]
@remy Getting similar error when installing nodemon : 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'nodemon@^1.9.2' ]
2 info using npm@5.3.0
3 info using node@v6.12.0
4 verbose npm-session 95dc948f76b98c70
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 http://npm.chc.tlocal/nodemon 727ms (from cache)
8 silly pacote range manifest for nodemon@^1.9.2 fetched in 757ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule nodemon@1.13.3 checking installable status
14 http fetch GET 304 http://npm.chc.tlocal/chokidar 516ms (from cache)
15 silly pacote range manifest for chokidar@^1.7.0 fetched in 521ms
16 silly resolveWithNewModule chokidar@1.7.0 checking installable status
17 http fetch GET 304 http://npm.chc.tlocal/debug 523ms (from cache)
18 silly pacote range manifest for debug@^2.6.8 fetched in 529ms
19 silly resolveWithNewModule debug@2.6.9 checking installable status
20 http fetch GET 304 http://npm.chc.tlocal/es6-promise 529ms (from cache)
21 silly pacote range manifest for es6-promise@^3.3.1 fetched in 532ms
22 silly resolveWithNewModule es6-promise@3.3.1 checking installable status
23 http fetch GET 304 http://npm.chc.tlocal/lodash.defaults 664ms (from cache)
24 silly pacote range manifest for lodash.defaults@^3.1.2 fetched in 667ms
25 silly resolveWithNewModule lodash.defaults@3.1.2 checking installable status
26 http fetch GET 304 http://npm.chc.tlocal/update-notifier 684ms (from cache)
27 http fetch GET 304 http://npm.chc.tlocal/undefsafe 688ms (from cache)
28 silly pacote range manifest for update-notifier@^2.3.0 fetched in 689ms
29 silly resolveWithNewModule update-notifier@2.3.0 checking installable status
30 http fetch GET 304 http://npm.chc.tlocal/touch 691ms (from cache)
31 http fetch GET 304 http://npm.chc.tlocal/ignore-by-default 694ms (from cache)
32 silly pacote version manifest for undefsafe@0.0.3 fetched in 694ms
33 silly resolveWithNewModule undefsafe@0.0.3 checking installable status
34 silly pacote range manifest for touch@^3.1.0 fetched in 695ms
35 silly resolveWithNewModule touch@3.1.0 checking installable status
36 silly pacote range manifest for ignore-by-default@^1.0.1 fetched in 697ms
37 silly resolveWithNewModule ignore-by-default@1.0.1 checking installable status
38 http fetch GET 404 http://npm.chc.tlocal/@remy%2fpstree 931ms
39 silly fetchPackageMetaData error for @remy/pstree@^1.1.0 404 Not Found: @remy/pstree@^1.1.0
40 verbose stack Error: 404 Not Found: @remy/pstree@^1.1.0
40 verbose stack     at fetch.then.res (/usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:41:19)
40 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
40 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
40 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
40 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
40 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
40 verbose stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
40 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
40 verbose stack     at Immediate.Async.drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
40 verbose stack     at runCallback (timers.js:672:20)
40 verbose stack     at tryOnImmediate (timers.js:645:5)
40 verbose stack     at processImmediate [as _immediateCallback] (timers.js:617:5)
41 verbose cwd /opt/telogis/nodejs/dcm_ui_staging.chef
42 verbose Linux 3.10.0-693.11.1.el7.x86_64
43 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "nodemon@^1.9.2"
44 verbose node v6.12.0
45 verbose npm  v5.3.0
46 error code E404
47 error 404 Not Found: @remy/pstree@^1.1.0
48 verbose exit [ 1, true ]
