### ISSUE TITLE
npm install is not working for @remy/pstree": "^1.1.0

### ISSUE THREAD

**Issue by akhilshastri** [remy/nodemon#1180]
- Does the bug occur on [latest nodemon](https://github.com/remy/nodemon/releases)? **Yes**
- `nodemon -v`: **i m using gulp-nodemon@2.2.1**
- `node -v`: **8.x**
- Operating system/terminal environment: **windows 7 (64-bit)**
- Command you ran: **npm install gulp-nodemon@2.2.1**

### Expected behaviour
It should install gulp-nodemon

### Actual behaviour
yarn is saying "Could not find package @remy/pstree on npm repository"
npm is saying "code E400, 400 bad request @remy/pstree@^1.1.0

### Steps to reproduce
npm install gulp-nodemon

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by krumax** [comment]
same here on installing swagger via npm, Ubuntu 16.04

**Comment by remy** [comment]
I'm going to rename the @remy/pstree module and push a fix release today.
