### ISSUE TITLE
Server infinitely restarts without --ext mjs

### ISSUE THREAD

**Issue by jaydenseric** [remy/nodemon#1182]
- Does the bug occur on [latest nodemon](https://github.com/remy/nodemon/releases)?  Yes.
- `nodemon -v`: v1.13.3
- `node -v`: v8.9.3
- Operating system/terminal environment: macOS 10.13.2, VS Code integrated terminal.
- Command you ran:

```
"dev": "nodemon",
"start": "node --require @std/esm --require dotenv/config server.mjs"
```

```
npm run dev
```

### Expected behaviour

The server starts once, and listens for changes.

### Actual behaviour

Server starts, then infinitely restarts "due to changes":

<img width="613" alt="screen shot 2017-12-20 at 6 03 55 pm" src="https://user-images.githubusercontent.com/1754873/34195142-36aea7bc-e5b0-11e7-81e2-25c2b2ba8b46.png">

Interestingly, running nodemon with `--ext mjs` works as expected:

```
"dev": "nodemon --ext mjs"
```

<img width="613" alt="screen shot 2017-12-20 at 6 08 19 pm" src="https://user-images.githubusercontent.com/1754873/34195290-d0d39f00-e5b0-11e7-90cf-66ee9271dfe6.png">

`.mjs` is meant to be supported without a flag since [v1.12.3](https://github.com/remy/nodemon/releases/tag/v1.12.3).

**Comment by remy** [comment]
Can you provide a gist with a sample package.json and main script to help replicate?

**Comment by remy** [comment]
Oh, can you also screenshot the output with the `--verbose` flag on so I can see what's triggering the change?

**Comment by jaydenseric** [comment]
You can see it in action by cloning and npm installing, and running [this example API](https://github.com/jaydenseric/apollo-upload-examples/blob/master/api/package.json#L35) with and without the flag.

**Comment by remy** [comment]
@jaydenseric as I suspected, running with `--verbose` shows that there's a file that's constantly changing causing the restart:

<img width="953" alt="screen shot 2017-12-20 at 12 57 31" src="https://user-images.githubusercontent.com/13700/34208200-682a31ce-e585-11e7-9e60-ae1dd6a272ed.png">

I don't know how your code (or deps) work, but I suspect that there's something touching `db.json` upon startup, which nodemon picks up as a change, which triggers a restart (since default monitor includes json), which starts nodemon which sends the entire process into a loop.

If you add this to your package.json, then it watches without a problem:

```json
"nodemonConfig": {
  "ignore": ["db.json"]
}
```

**Comment by jaydenseric** [comment]
Thanks, good pickup. But I did your suggestion and the server would not restart on changing .mjs files.

Using `--verbose` mode, it seems only `js,json` are being watched:

<img width="806" alt="screen shot 2017-12-21 at 1 32 26 pm" src="https://user-images.githubusercontent.com/1754873/34237966-7834f27e-e653-11e7-8f0f-82c37282c24f.png">

I thought `.mjs` was meant to now be a default watch extension?

**Comment by jaydenseric** [comment]
It looks like it was mistakenly added only for coffee?

https://github.com/JayBeavers/nodemon/blob/master/lib/config/exec.js#L141

**Comment by remy** [comment]
Sod, yeah I saw that in the PR too but didn't quite put it together. Do you want to send a PR to fix? Suspect the change is in defaults.js

**Comment by remy** [comment]
Turns out the change isn't in defaults.js, but if you search through the code you'll find where it sets is,json as the default

**Comment by remy** [comment]
I'm going to (re)close this issue as the original issue is addressed. But please go ahead and raise a new issue with the default not watching mjs
