### ISSUE TITLE
Add ability to read config from package.json

### ISSUE THREAD

**Issue by xeoneux** [remy/nodemon#1205]
### Expected behaviour
Read nodemon config from package.json

### Actual behaviour
Read nodemon config from nodemon.json

**Comment by remy** [comment]
What exactly is the issue here? As far as I know, nodemon _does_ read the `nodemonConfig` from the `package.json` … unless you're seeing something different?

**Comment by xeoneux** [comment]
Hehehe, my bad. I was using `nodemon` instead of `nodemonConfig` key in the file 🙈

**Comment by xeoneux** [comment]
Thanks @remy

**Comment by remy** [comment]
np 👍
