### ISSUE TITLE
Cannot install nodemon ... duplexer3 and timed-out modules gone

### ISSUE THREAD

**Issue by azizghuloum** [remy/nodemon#1210]
When I install, I get:
```
...
npm http fetch GET 200 https://registry.npmjs.org/is-retry-allowed 28ms
npm http fetch GET 200 https://registry.npmjs.org/is-redirect 29ms
npm http fetch GET 200 https://registry.npmjs.org/url-parse-lax 27ms
npm http fetch GET 200 https://registry.npmjs.org/unzip-response 29ms
npm http fetch GET 200 https://registry.npmjs.org/duplexer3 31ms
npm http fetch GET 200 https://registry.npmjs.org/create-error-class 34ms
npm http fetch GET 200 https://registry.npmjs.org/lowercase-keys 46ms
npm http fetch GET 200 https://registry.npmjs.org/timed-out 49ms
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: timed-out@^4.0.0 (node_modules/nodemon/node_modules/got/node_modules/timed-out):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: No valid versions available for timed-out

npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for duplexer3

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-06T19_04_24_986Z-debug.log
The command '/bin/sh -c npm install nodemon -g' returned a non-zero code: 1
```

It seems that `timed-out` and `duplexer3` were removed from npmjs:
https://www.npmjs.com/package/duplexer3  returns 404
https://www.npmjs.com/package/timed-out  also returns 404

**Comment by MathRobin** [comment]
It's the same of https://github.com/remy/nodemon/issues/1211.

**Comment by LeeCheneler** [comment]
I've had duplexer3 and pinkie-pomise packages timeout this evening too :(

**Comment by azizghuloum** [comment]
@LeeCheneler It seems like npmjs is a little flaky tonight. It's back online just now.

**Comment by LeeCheneler** [comment]
Yeah something is up, getting a different issue now:

```
λ yarn add nodemon --dev
yarn add v1.3.2
[1/4] Resolving packages...
error Received malformed response from registry for "timed-out". The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

status.npmjs.org isn't reporting anything yet :(

**Comment by Theo-** [comment]
@azizghuloum the package `timed-out` is effectively not on NPM anymore: https://www.npmjs.com/package/timed-out

I tried to republish it, but I'm getting an NPM error: `Package name too similar to existing packages;`

**Comment by remy** [comment]
This looks like both of the modules belong to updater:

<img width="618" alt="screen shot 2018-01-06 at 20 03 40" src="https://user-images.githubusercontent.com/13700/34643480-bbdb32ce-f31c-11e7-972d-a5e93712956a.png">

I can't personally fix right now, but if anyone can get a PR (that doesn't remove `update-notifier`, then I'm able to merge).

**Comment by remy** [comment]
Might even be a PR to the `got` module?

**Comment by Theo-** [comment]
This is apparently a wide-spread issue on the NPM repository: https://news.ycombinator.com/item?id=16087024#16087108

**Comment by remy** [comment]
Possibly related: https://news.ycombinator.com/item?id=16087024

**Comment by azizghuloum** [comment]
https://github.com/npm/registry/issues/255

**Comment by remy** [comment]
Just been doing some quick reading. Firstly, npm are on it: https://status.npmjs.org

Secondly it looks like (from comments on the npm/registry issues) that duplexer3 has been hijacked. I'm not 100% sure if the package-lock.json file that nodemon has protects you, but just be wary.

**Comment by remy** [comment]
Looks like npm has solved this issue now: https://status.npmjs.org/incidents/41zfb8qpvrdj

If you reinstall, it should come down with the correct dependencies. If you do happen to see the "old" duplexer3 _hijacked_ message, try to `npm uninstall --save-dev nodemon` and re-install (I noticed that once duplexer3 was in my package-lock.json file, it seemed to install the _bad_ one again until the lock file was cleaned).
