### ISSUE TITLE
Don't show: Files triggering change check and changes after filters

### ISSUE THREAD

**Issue by mjarkk** [remy/nodemon#1216]
- `nodemon -v`: 1.14.7  
- `node -v`: 9.3.0  
- Operating system/terminal environment: Ubuntu 17.10, default shell  
- Command you ran: yarn start (this will start a script that will ran: nodemon serv.js)

### Expected behaviour
Not show :  
[nodemon] files triggering change check: some/directory/some.file  
[nodemon] changes after filters (before/after): 1/0  

### Actual behaviour
I have a view directories that need to be ignored but every time there is a change in that directory it outputs this:  
[nodemon] files triggering change check: some/directory/some.file  
[nodemon] changes after filters (before/after): 1/0  
Is there a way to stop that because i can't find my application console.log lines  

### Screenshot:
![Screenshot](https://i.imgur.com/l2Yg3Za.png)

### Nodemon Dump
```
{ run: false,
  system: { cwd: '/home/mark/Documents/plex-like-web-app' },
  required: false,
  dirs: [ '/home/mark/Documents/plex-like-web-app' ],
  timeout: 1000,
  options: 
   { dump: true,
     verbose: true,
     ignore: 
      [ '**/.git',
        '**/.nyc_output',
        '**/.sass-cache',
        '**/bower_components',
        '**/coverage',
        '**/node_modules',
        'cache/*',
        'errors/*',
        'appdata/*',
        'conf/*',
        'dev/*',
        'node_modules/*',
        'routes/*',
        'www/*',
        '.git/*',
        '.gitignore',
        'LICENSE',
        'README.json',
        'yarn.lock',
        re: /.*.*\/\.git|.*.*\/\.nyc_output|.*.*\/\.sass\-cache|.*.*\/bower_components|.*.*\/coverage|.*.*\/node_modules|cache\/.*|errors\/.*|appdata\/.*|conf\/.*|dev\/.*|node_modules\/.*|routes\/.*|www\/.*|\.git\/.*|\.gitignore|LICENSE|README\.json|yarn\.lock/ ],
     trickrestart: true,
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot: 
      [ '**/.git',
        '**/.nyc_output',
        '**/.sass-cache',
        '**/bower_components',
        '**/coverage',
        '**/node_modules' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     signal: 'SIGUSR2',
     stdout: true,
     watchOptions: {},
     execOptions: 
      { script: 'serv.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        execArgs: [],
        ext: 'js,mjs,json',
        env: {} },
     monitor: 
      [ '*.*',
        '!**/.git',
        '!**/.nyc_output',
        '!**/.sass-cache',
        '!**/bower_components',
        '!**/coverage',
        '!**/node_modules',
        '!cache/**/*',
        '!errors/**/*',
        '!appdata/**/*',
        '!conf/**/*',
        '!dev/**/*',
        '!node_modules/**/*',
        '!routes/**/*',
        '!www/**/*',
        '!.git/**/*',
        '!.gitignore',
        '!LICENSE',
        '!README.json',
        '!yarn.lock' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [ '/home/mark/Documents/plex-like-web-app/nodemon.json' ],
  watchInterval: null,
  signal: 'SIGUSR2',
  command: 
   { raw: { executable: 'node', args: [ 'serv.js' ] },
     string: 'node serv.js' } }
```
--------------

**Comment by remy** [comment]
I think I already have a fix for this in the wings.

Can you try with the debug version of nodemon (`npm install nodemon@debug`)

**Comment by mjarkk** [comment]
Thx that fixed the problem

**Comment by remy** [comment]
Live in nodemon@1.1.4.9

**Comment by SharpBCD** [comment]
Is it fixed in 1.1.4.9? I use 1.18.3 and I still got this problem.
Since my app is generating jsons, I see far too often the message.

**Comment by ernest-okot** [comment]
i'm seeing this issue with 1.18.3

```
"watch": "nodemon -V -w src -x \"yarn build && yarn rnstl\"",
```

this logs 
```

**Comment by gajjardarshithasmukhbhai** [comment]
i have problem when i change the code. nodemon 1.18.9 is reload .and display [nodemon] restarting due to changes... but the output is not change in localhost:3000

**Comment by hutber** [comment]
Indeed, I'm having this problem with `v19: "nodemon": "^1.19.1"`. This will only happen when I get an error inside the app. Otherwise the reloading is fine.

I am using `--experimental-modules` though so I am wondering if this is a problem for it:

`nodemon --inspect -w -- --experimental-modules server.js server.js`
