### ISSUE TITLE
npm list errors if nodemon is install

### ISSUE THREAD

**Issue by zer09** [remy/nodemon#1217]
- `nodemon -v`: 1.14.9
- `node -v`: v8.9.3
- Operating system/terminal environment:  Fedora 27/gnome terminal
- Command you ran: npm list --depth=0

### Expected behaviour
It will just list the installed packages, without the errors.

### Actual behaviour
It list all all the installed packages, but with errors on the end.

### Steps to reproduce
I tried to use fresh expressjs.

- install express by ```express --view=pug app_name```
- install the packages
- do ```npm list --depth=0``` "no errors found"
- do ```npm install --save nodemon```
- then do ```npm list --depth=0```

---
![screenshot from 2018-01-08 22-50-25](https://user-images.githubusercontent.com/780780/34676745-d992c374-f4c8-11e7-8d8a-93e4d0c1228b.png)

P.S. It still working even there is an error on npm list, but if I will check the installed packages I need to scroll up to the terminal to see i t.

**Comment by remy** [comment]
It looks like these are coming from Chokidar's optional dependencies:

```bash
root@7615cb759a50:/src/app_name# npm ls node-pre-gyp
app-name@0.0.0 /src/app_name
└─┬ nodemon@1.14.9
  └─┬ chokidar@1.7.0
    └─┬ UNMET OPTIONAL DEPENDENCY fsevents@1.1.3
      └── UNMET OPTIONAL DEPENDENCY node-pre-gyp@0.6.39

root@7615cb759a50:/src/app_name# npm ls readable-stream
app-name@0.0.0 /src/app_name
└─┬ nodemon@1.14.9
  └─┬ chokidar@1.7.0
    ├─┬ UNMET OPTIONAL DEPENDENCY fsevents@1.1.3
    │ └─┬ UNMET OPTIONAL DEPENDENCY node-pre-gyp@0.6.39
    │   ├─┬ UNMET OPTIONAL DEPENDENCY npmlog@4.1.0
    │   │ └─┬ UNMET OPTIONAL DEPENDENCY are-we-there-yet@1.1.4
    │   │   └── UNMET DEPENDENCY readable-stream@2.2.9
    │   └─┬ UNMET OPTIONAL DEPENDENCY tar-pack@3.4.0
    │     └── UNMET DEPENDENCY readable-stream@2.2.9
    └─┬ readdirp@2.1.0
      └── readable-stream@2.3.3

npm ERR! missing: readable-stream@2.2.9, required by are-we-there-yet@1.1.4
npm ERR! missing: readable-stream@2.2.9, required by tar-pack@3.4.0
```

There's nothing I can do about this, but I think those aren't really npm errors, but rather warnings (since they come from the optional deps). Hope that's all cool.

**Comment by zer09** [comment]
Thanks, this was gone on ```v1.14.10```.
