### ISSUE TITLE
Nodemon 1.14.7 not restarting when saving file, previous version works

### ISSUE THREAD

**Issue by eablokker** [remy/nodemon#1218]
- `nodemon -v`: 1.14.7
- `node -v`: v6.0.0
- Operating system/terminal environment: Mac OS Sierra 10.12.6, Terminal default shell
- Command you ran: `NODE_ENV=development nodemon app.js`

### Expected behaviour
Nodemon should restart when I save a file

### Actual behaviour
Nodemon does not restart when I save a file. Nothing happens, no error messages.

### Steps to reproduce
Was able to fix by uninstalling 1.14.7 and installing 1.12.5. No other change but different nodemon version.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Can you test with latest, and run with the `-V` flag and include the output here when you've changed a file and expect it to restart.

**Comment by eablokker** [comment]
Ok installed nodemon 1.14.9

This is what I get when starting with -V flag.
There is no output at all when I save a file and expect it to restart. Nothing at all happens.

```
NODE_ENV=development nodemon app.js -V
[nodemon] 1.14.9
[nodemon] reading config ./nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 13607 to restart
[nodemon] ignoring: public/javascripts/**/* user/**/static/**/*
[nodemon] watching: *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
[nodemon] forking
[nodemon] child pid: 13609
TypeError: Cannot read property 'on' of null
    at Object.run (/Users/Austen/.nvm/versions/node/v6.0.0/lib/node_modules/nodemon/lib/monitor/run.js:266:16)
    at /Users/Austen/.nvm/versions/node/v6.0.0/lib/node_modules/nodemon/lib/nodemon.js:221:13
    at /Users/Austen/.nvm/versions/node/v6.0.0/lib/node_modules/nodemon/lib/config/index.js:82:7
```

Also of note is when I type `rs` and hit return I get this error:
```
[nodemon] starting `node app.js`
[nodemon] forking
[nodemon] child pid: 13670
[nodemon] exiting
/Users/Austen/.nvm/versions/node/v6.0.0/lib/node_modules/nodemon/lib/monitor/run.js:266
    child.stdin.on('error', () => { });
               ^

TypeError: Cannot read property 'on' of null
    at Object.run (/Users/Austen/.nvm/versions/node/v6.0.0/lib/node_modules/nodemon/lib/monitor/run.js:266:16)
    at ChildProcess.<anonymous> (/Users/Austen/.nvm/versions/node/v6.0.0/lib/node_modules/nodemon/lib/monitor/run.js:174:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

I wonder what the minimum Node version is required for this version of nodemon?

**Comment by remy** [comment]
Node 4 is the minimum requirement. It looks like you're on 6.0.0.

Am I right in reading that nodemon is blowing up entirely?

**Comment by remy** [comment]
Darnit, I'm able to replicate the `-V` error output, and it crashes with the "rs" trigger too.

**Comment by remy** [comment]
I'm pretty sure there's actually two things going on here:

1. I'm now [logging out](https://github.com/remy/nodemon/blob/e95ea6f656bfc2a368362e7f6729da297b463031/lib/config/index.js#L85) any syntax errors in nodemon - but I'm fairly sure this is non destructive
2. The `rs` causing a crash - this is definitely new

Then there's your original issue, but I wonder if (1) is causing the process to bail quietly…

**Comment by remy** [comment]
I think I've found it. There's a difference in the fork api between node@6 and node@6.4.0. Although ideally I just support the latest version of node on each LTS, I've got a fix in place ready for live testing.

If you can try with the debug version: `npm install nodemon@debug` and re-test with your current version of node, I believe it is fixed.

If so, please let me know (and I suggest I bump of your node version too).

**Comment by eablokker** [comment]
Thank you. 1.14.10 works for me now.
