### ISSUE TITLE
nodemon --inspect doesn't launch the debugger.

### ISSUE THREAD

**Issue by vascofg** [remy/nodemon#1226]
- `nodemon -v`: 1.14.1
- `node -v`: 8.9.3
- Operating system/terminal environment: Docker /_/node:8 image
- Command you ran: `nodemon --inspect`

This runs: `node ./bin/www --inspect` which doesn't start the debugger.
Running `node --inspect ./bin/www` (with the argument before the file) actually launches the debugger.

PS: The behaviour is the same with --debug flag

**Comment by remy** [comment]
Can you upgrade to latest nodemon? I believe it's fix in there.

**Comment by remy** [comment]
Oh wait… can you share your `package.json` file? I suspect you've got `scripts.start: "node ./bin/www"` which isn't really possible for nodemon to wildy guess as to what's in the command and then splitting it up to insert flags.

Can you just check those two things (the version and your package)

**Comment by vascofg** [comment]
Indeed my package.json has:
```
  "scripts": {
    "start": "node ./bin/www"
  }
```

nodemon version is 1.14.11

**Comment by vascofg** [comment]
I've tested this a bit and turns out the only thing you need is the main prop. If you have that it works without specifying the file to nodemon.
This is actually in the documentation:

> If you have a package.json file for your app, you can omit the main script entirely and nodemon will read the package.json for the main property and use that value as the app.

>nodemon will also search for the scripts.start property in package.json (as of nodemon 1.1.x).
This part could mislead people since this was what it was doing in my case and wasn't working as expected. Maybe a warning when using `--inspect` or `--debug` flags when nodemon can't find the main prop?

**Comment by remy** [comment]
I'm not entirely sure what the right move here is. I'm not keen on the idea of parsing the `script.starts` value and then trying to maintain all the node arguments and splicing them in. It's almost worth considering dropping support for `script.starts` which makes the most (technical) sense, but I'm worried it's a nicety that's pretty useful, albeit brittle.

**Comment by remy** [comment]
I'm not sure there's anything to do here. You mentioned the docs _could_ mislead people, do you have a change in mind that could help clarify? I'm going to close as it's not a bug per se, but possibly a PR on the docs.
