### ISSUE TITLE
Auto-restart not working

### ISSUE THREAD

**Issue by devamaz** [remy/nodemon#1228]
- `nodemon -v`: 1.14.11
- `node -v`: 8.0.0
- Operating system/terminal environment: OS X 10.12.6
- Command you ran: nodemon

### Expected behaviour
Should Auto-restart after saving  after saving file

### Actual behaviour
Not Auto-restarting after saving file

**Comment by remy** [comment]
Can you provide a screenshot when running with `--verbose`?

**Comment by devamaz** [comment]
Thank problem fixed after updating  nodemon
