### ISSUE TITLE
can't resolve correct relative path as node at windows 7 command line

### ISSUE THREAD

**Issue by 404157386** [remy/nodemon#1231]
- `nodemon -v`:1.14.11
- `node -v`:v8.4.0
- Operating system/terminal environment: windows7
- Command you ran:
nodemon build/dev-server.js

I run this command at path "D:\code\admin-ui>"

### Expected behaviour
starting `node .\build\dev-server.js`

### Actual behaviour
Error: Cannot find module 'D:\build\dev-server.js'

### Steps to reproduce
hope you can fix this issue, thx!

![image](https://user-images.githubusercontent.com/16297662/35132424-24dd6da8-fd06-11e7-9b53-7abadb516db9.png)

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Can you try with `./build/server`

**Comment by remy** [comment]
Any joy?

**Comment by 404157386** [comment]
No.  `nodemon ./build/server`  doesn't work either

**Comment by remy** [comment]
@404157386 can you replicate with a simple server.js file, something like:

```js
require('http').createServer((req, res) => res.end('ok')).listen(3000)
```

**Comment by 404157386** [comment]
i create the server.js your give, but also hit error
![image](https://user-images.githubusercontent.com/16297662/35489843-b674db8a-04d5-11e8-8a5b-c96f15b15163.png)

**Comment by remy** [comment]
@404157386 can you try running `npm --version` and sharing the result?

**Comment by 404157386** [comment]
@remy 5.3.0

**Comment by remy** [comment]
I'm kinda grabbing at straws, but is there any chance that you installed node via nvm for windows?

**Comment by 404157386** [comment]
Yes, I installed node via nvm.

**Comment by remy** [comment]
Is it possible you're experiencing this issue: https://github.com/coreybutler/nvm-windows/issues/302

There's a workaround in the thread too: https://github.com/coreybutler/nvm-windows/issues/302#issuecomment-340249164 - could you try that and let me know how you get on?
