### ISSUE TITLE
Nodemon not starting in Git Bash

### ISSUE THREAD

**Issue by sixtiiine** [remy/nodemon#1232]
- `nodemon -v`: 1.14.9
- `node -v`: 6.11.0
- Operating system/terminal environment: Windows 10, Git Bash
- Command you ran: `nodemon --use-strict index.js --debug` also just `nodemon`

### Expected behaviour
Nodemon launches server

### Actual behaviour
Nodemon does not launch server and instead error below displays:
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\Git\node_modules\nodemon\bin\nodemon.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

### Steps to reproduce
Not sure how this started manifesting on my machine, but suddenly nodemon just stopped working on Git Bash. Apparently, the path that's referencing nodemon is incorrect. Whenever I try nodemon in PowerShell, it works alright though.

**Comment by remy** [comment]
Can you try uninstalling and reinstalling?

**Comment by remy** [comment]
Any joy?

**Comment by sixtiiine** [comment]
Thanks. I've tried uninstalling and reinstalling multiple times already, but am still getting the error :(

**Comment by sixtiiine** [comment]
Hello! Managed to fix this on my machine by creating a symbolic link for the node modules path.

mklink /D node_modules %USERPROFILE%\AppData\Roaming\npm\node_modules

Hope this helps!!!

**Comment by sixtiiine** [comment]
(Just still haven't figured out why it stopped working in the first place... ?_? but at least it's working again now 👍)
