### ISSUE TITLE
node < 6.4.0, no child.stdout exist

### ISSUE THREAD

**Issue by sairoutine** [remy/nodemon#1234]
- `nodemon -v`: v1.14.11
- `node -v`: v6.0.0
- Operating system/terminal environment: OS X EI Capitan 10.11.6(Terminal default shell)
- Command you ran: `nodemon -e js -i assets -i node_modules -x "npm run build" -V`

### Expected behaviour
No error occurs.

### Actual behaviour
the following error has occurred.
```
$ nodemon -e js -i assets -i node_modules -x "npm run build" -V
[nodemon] 1.14.11
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 21348 to restart
[nodemon] ignoring: ./assets/**/* ./node_modules/**/*
[nodemon] watching: *.*
[nodemon] watching extensions: js
[nodemon] starting `npm run build`
[nodemon] spawning
[nodemon] child pid: 21350
TypeError: Cannot read property 'pipe' of null
    at Object.run (/repos-path/node_modules/nodemon/lib/monitor/run.js:263:19)
    at /repos-path/node_modules/nodemon/lib/nodemon.js:221:13
    at /repos-path/node_modules/nodemon/lib/config/index.js:82:7
```

### Steps to reproduce
To run the above command.

**Comment by remy** [comment]
Are you able to upgrade to the latest *stable* node 6?

**Comment by sairoutine** [comment]
>Are you able to upgrade to the latest stable node 6?

In Node v6.9.0 (LTS), It works with no error.

**Comment by sairoutine** [comment]
I think the following code is correct.
https://github.com/remy/nodemon/blob/e90f15aa8a2afffe67fa7a86208587b8cdc34f3e/lib/monitor/run.js#L263
```diff
-      child.stdout.pipe(process.stdout);
+      if (child.stdout) {
+        child.stdout.pipe(process.stdout);
+      }
```
It has worked on Node v.6.0.0.

**Comment by sairoutine** [comment]
Thank you!
