### ISSUE TITLE
jsbn version is resolved to 0.1.1 with yarn

### ISSUE THREAD

**Issue by dlebedynskyi** [remy/nodemon#1235]
- `nodemon -v`: 1.14.11
- `node -v`: 8.9.1
- Operating system/terminal environment: Docker image & Mac
- Command you ran:
yarn install resolved jsbn to 0.1.1 due to hard dependency on [ecc-jsb ](https://github.com/remy/nodemon/blob/66e0d133f52255b62d354579a77e601c74900059/package-lock.json#L1197) to 
```
"requires": {
        "jsbn": "0.1.1"
      }
```

### Expected behaviour

do not have hard dependency to long deprecated version of jsbn - latest is 1.1.0

### Actual behaviour

Causes docker container failure since jsbn version can not be correctly resolved. 

This is caused by chokidar update (chokidar => fsevents => .... ecc-jsb)

### Steps to reproduce
I have been using yarn@1.3.2 
1. install any package that has jsbn in deps - see  jsbn resolved to 1.1.0
2. install nodemon (may need to remove .lock file) - see jsbn resolved to 0.1.0

**Comment by remy** [comment]
Please can you provide a dockerfile that I can use to reproduce the error. I can't really follow your description. Sorry.

**Comment by dlebedynskyi** [comment]
@remy 
I'll try to explain a bit better and min reproduce scenario 
1. create a package with jsbn dependency 
https://gist.github.com/dlebedynskyi/62bb7408664bc053bd18b5c11ef2f9d1

2. create another package that will use one above 
https://gist.github.com/dlebedynskyi/8528b304eb04f873a872a7b1b05682bd

you can check node_modules/jsbn/package.json  
> "version": "1.1.0"

3. now add nodemon  (1.14.11 ) to sample-nodemon
https://gist.github.com/dlebedynskyi/5593f73046ce114850c9a19f2281b0ae

Check node_modules/jsbn/package.json
> "version": "0.1.1"

as you can see nodmon dep (chokidar) installs jsbn version 0.1.1

**Comment by remy** [comment]
I've not tried to test this yet, but reading the files, I actually think this isn't an issue with nodemon but actually and issue with yarn and/or npm.

If you repeat the entire process, but with npm only (not using yarn or yarn locks at all), do you get the same issue?

I'm very certain you won't (and I've got a suspicion that I read about a similar issue being addressed on the npm issue lists…just can't remember exactly what it was).

I'm going to close this issue with the recommendation that you raise the same issue (with the details from your latest comment) against npm and yarn - as I'm not sure which one is breaking interop.

If this really issue an issue in nodemon, I'm very happy to reopen and see if there's something I've missed.

**Comment by dlebedynskyi** [comment]
> I've got a suspicion that I read about a similar issue being addressed on the npm issue lists…just can't remember exactly what it was)
yeah I felt like this is not an issue with nodemon directly. It is still a good to know issue since we got  it after update of nodemon. 
Thanks for looking into this.
