### ISSUE TITLE
Cannot find module .\custom-loader.mjs

### ISSUE THREAD

**Issue by nicolasparada** [remy/nodemon#1236]
- `nodemon -v`: 1.14.11
- `node -v`: v9.4.0
- Operating system/terminal environment: Windows 10/PowerShell Core 6.0
- Command you ran: `nodemon -x \"node --experimental-modules --loader ./custom-loader.mjs\" -e graphql,js,mjs,json main.js`

### Expected behaviour
I'm using [node loader hooks](https://nodejs.org/dist/latest-v9.x/docs/api/esm.html#esm_loader_hooks) to use ES6 modules with .js extension. I know this is a experimental thing, but it does work. It doesn't when I try it with nodemon tho. I mean, this script does works:
`node --experimental-modules --loader ./custom-loader.mjs main.js`

### Actual behaviour
Cannot find module .\custom-loader.mjs

### Steps to reproduce
`nodemon -x \"node --experimental-modules --loader ./custom-loader.mjs\" -e graphql,js,mjs,json main.js`

---

```bash
[nodemon] 1.14.11
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
--------------
node: v9.4.0
nodemon: 1.14.11
command: C:\Program Files\nodejs\node.exe C:\Users\nicolas\Documents\node-graphql-boilerplate\node_modules\nodemon\bin\nodemon.js -x node --experimental-modules --loader ./custom-loader.mjs -e graphql,js,mjs,json --dump main.js
cwd: C:\Users\nicolas\Documents\node-graphql-boilerplate
OS: win32 x64
--------------
{ run: false,
  system:
   { cwd: 'C:\\Users\\nicolas\\Documents\\node-graphql-boilerplate' },
  required: false,
  dirs: [ 'C:\\Users\\nicolas\\Documents\\node-graphql-boilerplate' ],
  timeout: 1000,
  options:
   { exec: 'node --experimental-modules --loader ./custom-loader.mjs',
     dump: true,
     ignore:
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**',
        re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot:
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     signal: 'SIGUSR2',
     stdout: true,
     watchOptions: {},
     execOptions:
      { script: 'main.js',
        exec: 'node --experimental-modules --loader ./custom-loader.mjs',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        execArgs: [],
        ext: 'graphql,js,mjs,json',
        env: {} },
     monitor:
      [ '*.*',
        '!**/.git/**',
        '!**/.nyc_output/**',
        '!**/.sass-cache/**',
        '!**/bower_components/**',
        '!**/coverage/**',
        '!**/node_modules/**' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  signal: 'SIGUSR2',
  command:
   { raw:
      { executable: 'node --experimental-modules --loader ./custom-loader.mjs',
        args: [ 'main.js' ] },
     string: 'node --experimental-modules --loader ./custom-loader.mjs main.js' } }
--------------
```

**Comment by remy** [comment]
Can you give me a gist containing `custom-loader.mjs` and `main.js`? They don't have to be your original code, but enough to replicate the bug.

**Comment by nicolasparada** [comment]
Oh yeah, I forgot that.
Here: https://github.com/nicolasparada/node-graphql-boilerplate/blob/master/custom-loader.mjs
It's like the example in the node docs.

**Comment by remy** [comment]
Quick update, found the source - running inside of nodemon is "normalizing" the path to the custom loader (which means the loader goes from `./custom-loader.mjs` to `.\custom-loader.mjs`) and this causes node to fail to load.

Investigating now if I can remove the line or not.

**Comment by remy** [comment]
Think I've got it. PR inbound.

**Comment by nicolasparada** [comment]
Thank you very much. It's working fine now 👏
