### ISSUE TITLE
update-notifier

### ISSUE THREAD

**Issue by Starystars67** [remy/nodemon#1237]
- `nodemon -v`: latest (installed today) 
- `node -v`: 0.12.2
- Operating system/terminal environment: 
- Command you ran: nodemon and nodemon app.js. This returns an error 

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by Starystars67** [comment]
Damn, sorry was hoping I could attach a screenshot. It comes back with

' require(' update-notifier') ({pkg}). Notify () ;

Syntaxerror: unexpected token}

**Comment by remy** [comment]
Node 0.12.x isn't supported I'm afraid. Node LTS and upwards (node@4.x). Sorry.
