### ISSUE TITLE
web_1    | [nodemon] restarting due to changes...

### ISSUE THREAD

**Issue by leninworld** [remy/nodemon#1238]
Nodejs detects the file changes, but will not restart. please help on this.

- `nodemon -v`: 1.14.11
- `node -v`: v9.4.0
- Operating system/terminal environment: MacOS Sierra 10.12.6
- Command you ran:  
nodemon --delay 2500ms -L app/bin/www

### Expected behaviour
after any changes in the file, I expect nodeman to restart server and reflect changes

### Actual behaviour
Nodeman able to detect changes and says restarting, but i dont see it reflects changes.
It gets hanged in below line.

"web_1    | [nodemon] restarting due to changes..."

### Steps to reproduce
1) using docker to up the nodejs .
2) package.json is having below script
"scripts": {
    "start": "nodemon --delay 2500ms -L app/bin/www",
    "test": "mocha"
  }
3) docker-compose build and then do docker-compose up.
4) change some console.log print statement values in index.js file.
5) It hangs in below line in the server.
"web_1    | [nodemon] restarting due to changes..."

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
You're going to need to provide dockerfile and docker-compose files to replicate. Otherwise I can't replicate, and I can't help. Sorry (assume, rightly, that I know little-to-nothing about docker etc)

**Comment by Ra1da35ma** [comment]
so I get this ...
```
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
```

instead of this
```
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] starting `node server.js --fe_ip localhost`
API running on localhost:8080
Connected to MongoDB: mongodb://localhost/bop-solution
...
```

**Comment by remy** [comment]
Again, I know nothing about docker compose, so I can't replicate this. Unless I get a PR for this or I get details on _how_ to replicate, I'll close in the next few days.

**Comment by Ra1da35ma** [comment]
I'm not using docker anyways.. 

see #763

**Comment by leninworld** [comment]
It works in windows, and not works in mac with same docker files. I downgraded the version of nodemon to see if it works. but , it never worked. I switched to supervisor instead of nodemon. I no more need this resolved. thanks!
