### ISSUE TITLE
Does not exclude node_modules when watching parent to cwd

### ISSUE THREAD

**Issue by dkebler** [remy/nodemon#1246]
- `nodemon -v`: 1.14.2
- `node -v`: 9.4
- Operating system/terminal environment: linux/xenial
- Command you ran:
`"node_modules/.bin/nodemon --require @std/esm --watch ../ examples/bus",`

### Expected behaviour

runs without issue

### Actual behaviour

the watcher is watching node_modules folders and throws errors

### Steps to reproduce

set up a two repos.  Fire up nodemon in one repo (cwd) but watch the parent folder for both repos (`--watch ../`).  

Note: The repo running the code with nodemon has dependencies I am changing in the other allied repo(s) thus my desire to watch them.  I import those module dependencies directly during during development before publishing and using npm for import since they too are under development and was wanting nodemon to watch them.

---

output when running the command above. uci/uci-logger is another repo/directory.  The CWD was uci/uci-bus.

  [nodemon] 1.14.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /opt/uci/**/*
[nodemon] starting `node --require @std/esm examples/bus src/bus`
{ id: 'i2c-bus', us: { path: '/opt/uci/unix.sock' } }
[nodemon] Internal watch failed: watch /opt/uci/uci-base/node_modules/urlgrey/package.json ENOSPC
[nodemon] Internal watch failed: watch /opt/uci/uci-logger/node_modules/make-dir/node_modules/pify/readme.md ENOSPC

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.
```
--------------
node: v9.4.0
nodemon: 1.14.12
command: /usr/local/bin/node /opt/uci/uci-i2c-bus/node_modules/.bin/nodemon --require @std/esm --dump --watch ../ examples/bus
cwd: /opt/uci/uci-i2c-bus
OS: linux arm
--------------
{ run: false,
  system: { cwd: '/opt/uci/uci-i2c-bus' },
  required: false,
  dirs: [ '/opt/uci' ],
  timeout: 1000,
  options: 
   { dump: true,
     watch: [ '../', re: /\.\.\// ],
     ignore: 
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**',
        re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/ ],
     ignoreRoot: 
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     signal: 'SIGUSR2',
     stdout: true,
     watchOptions: {},
     execOptions: 
      { script: 'src/bus',
        exec: 'node',
        args: [ '--require', '@std/esm', 'examples/bus' ],
        scriptPosition: 3,
        nodeArgs: undefined,
        execArgs: [],
        ext: 'js,mjs,json',
        env: {} },
     monitor: 
      [ '/opt/uci/**/*',
        '!**/.git/**',
        '!**/.nyc_output/**',
        '!**/.sass-cache/**',
        '!**/bower_components/**',
        '!**/coverage/**',
        '!**/node_modules/**' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  signal: 'SIGUSR2',
  command: 
   { raw: 
      { executable: 'node',
        args: [ '--require', '@std/esm', 'examples/bus', 'src/bus' ] },
     string: 'node --require @std/esm examples/bus src/bus' } }

```

**Comment by remy** [comment]
Can you try [this](https://stackoverflow.com/a/32600959/22617) first. You're getting the `ENOSPC` error, so I did a quick google, and I wonder if that would solve the issue.

**Comment by remy** [comment]
Another question (sorry, I found your issue a bit confusing to follow), when nodemon is failing on this:

```
[nodemon] Internal watch failed: watch /opt/uci/uci-base/node_modules/urlgrey/package.json ENOSPC
[nodemon] Internal watch failed: watch /opt/uci/uci-logger/node_modules/make-dir/node_modules/pify/readme.md ENOSPC
``

Did you expect nodemon to watch these, or not?

**Comment by dkebler** [comment]
no should not watch any files in a node_modules folder (that is supposed to be the default) and it does work normally when watched files are under the cwd.  But here I am asking to watch in a parent to cwd and that's where the issue arises.   FYI, After throwning those nodemon exists

**Comment by dkebler** [comment]
I can up the number of inoftify watches but it's only reaching that huge number because it's watching node_modules files.  My actual repo files in that parent only come to maybe 50 or so if their respective node_modules folders are excluded.

**Comment by dkebler** [comment]
assuming this deosn't happen for you using `--watch ../` could it then be using @std/esm ??

**Comment by remy** [comment]
Okay, I follow what's happening. node_modules are ignored relative from the root, so it's *including* those that are not hanging off the cwd.

I'll mark as a bug and take a shot at a fix when I have time, unless you raise a PR first.

**Comment by dkebler** [comment]
I'd like to tackle a PR but probably not going to happen.  Not a big deal at this moment but something nice to have when I am developing multiple dependent modules concurrently.   Can wait.  Thx

**Comment by dkebler** [comment]
BTW because of your log message in nodemon install I started participating in the open collective.  When they get paypal going even with some $, good idea that.  So no PR :-( but appreciate your efforts and try to repay with putting out useful repos made on the shoulders of projects like nodemon.
