### ISSUE TITLE
Use absolute path to node executable

### ISSUE THREAD

**Issue by poke** [remy/nodemon#125]
I’m on Windows, and I don’t have the node executable in my PATH. As nodemon only uses `node` to start the process, the spawn in `startNode` will fail:

```
child = spawn(program.options.exec, program.args);
```

I have solved this locally by getting the absolute path for the node executable from `process.execPath`. Obviously this will only work for the node executable, and a similar solution should be made for CoffeeScript:

```
if (program.options.exec === 'node')
  program.options.exec = process.execPath;
```

I don’t know how this works on Unix, so if anyone can give me some input on that, or an idea for solving this dynamically for CoffeeScript, I’d gladly create a full pull request with all necessary changes to make this work.

**Comment by remy** [comment]
Why not just put node in your PATH?
