### ISSUE TITLE
[new feature] Add timer so we know how long did the script run

### ISSUE THREAD

**Issue by junajan** [remy/nodemon#1252]
Hello all,
I am using `nodemon` together with `mocha` to run tests and restart them when I make some change in the code:
```
nodemon --watch lib --watch spec --watch lib -x "npm test"
```

I was thinking that it would be nice to have there some flag which would enable a debug info at the end when the script ends - like how long did it run, what resources did it use, etc..

**Comment by remy** [comment]
That's very specific to mocha, but also node. There's no reason you couldn't run that program to inspect your exec target. Say this program is called "inspect-resources":

```
nodemon --watch lib --watch spec --watch lib -x "inspect-resources npm test"
```

Then `before-exit` it would dump resources. In theory you could use heap dumps and some kind of coverage reporter… maybe? 

Still, out of scope for this project (so am closing, but thank you for the suggestion).

**Comment by junajan** [comment]
Thanks for your response.. maybe some simple `... -x "time npm test"` will be enough for now
