### ISSUE TITLE
Ubuntu: No valid versions available for AOS (Laravel Mix)

### ISSUE THREAD

**Issue by prajapatim** [remy/nodemon#1254]
First I run this command 

- npm install

This is my log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'AOS' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose npm-session e673c5335f65c9bd
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/AOS 1268ms (from cache)
8 silly fetchPackageMetaData error for AOS@latest No valid versions available for AOS
9 verbose type tag
10 verbose stack AOS: No valid versions available for AOS
10 verbose stack     at pickManifest (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/npm-pick-manifest/index.js:20:11)
10 verbose stack     at fetchPackument.then.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:39:14)
10 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
10 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
10 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
10 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
10 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
10 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
10 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
10 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
10 verbose stack     at runCallback (timers.js:756:18)
10 verbose stack     at tryOnImmediate (timers.js:717:5)
10 verbose stack     at processImmediate [as _immediateCallback] (timers.js:697:5)
11 verbose cwd /var/www/html/tatmasters
12 verbose Linux 4.13.0-32-generic
13 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "AOS"
14 verbose node v9.4.0
15 verbose npm  v5.6.0
16 error code ENOVERSIONS
17 error No valid versions available for AOS
18 verbose exit [ 1, true ]

**Comment by remy** [comment]
I don't see how this is relevant to nodemon. It doesn't appear anywhere in your log, and you're not trying to install it. I'll close this issue for now.
