### ISSUE TITLE
Deprecated dependency used

### ISSUE THREAD

**Issue by igor-savin-ht** [remy/nodemon#1256]
### Expected behaviour
Nodemon depends on up-to-date "coffeescript" dependency.

### Actual behaviour

Nodemon depends on "coffee-script" which is throwing deprecation warnings.

**Comment by remy** [comment]
For testing - which is fine for it's needs.

**Comment by igor-savin-ht** [comment]
@remy Problem is that it transitively comes to whatever project that depends on it and clutters console with warnings. Any particular reasons why update is undesirable?
