### ISSUE TITLE
Had to downgrade

### ISSUE THREAD

**Issue by staeke** [remy/nodemon#1261]
Sorry for a bad bug report. If you want me to provide more details or discuss this, pls let me know.

Just FYI really (you can close this if you want). I downgraded to 1.10 as described in https://github.com/remy/nodemon/issues/895 from latest version (1.14) and now it worked. 1.14 was all messed up and didn't restart until a LONG period had a elapsed and was then stuck between restarting and starting. Restarted computer. Uninstalled and reinstalled. Downgraded was the only thing that worked.

Platform
Mac 10.13.3

**Comment by remy** [comment]
Sounds like an IO thing on the disk, and moving to 1.10 is possibly pre-chokidar. If that works for you, then it's cool. As you suggested, I'll close. Thanks all the same.
