### ISSUE TITLE
Custom livereload

### ISSUE THREAD

**Issue by CrackerakiUA** [remy/nodemon#1262]
I want to create custom livereload and what i need, is to have a callback when any file change under the project, but also i want to restart the restart only on specific watch and to have specific ignore. That can be easly solve with what we currectly have is to manually restart the server with script check of files is changed and simply somehow disable restart.

**Comment by remy** [comment]
I'd suggest using nodemon as a required module and you'll have the control you want from the [events](https://github.com/remy/nodemon/blob/master/doc/events.md)

**Comment by CrackerakiUA** [comment]
I have seen those events, how can i disable the restart of the server?

**Comment by remy** [comment]
I'm not sure you can. But you _can_ only restart on a specific watch list (or inversely ignore files).

**Comment by CrackerakiUA** [comment]
My post was about that feature.

**Comment by CrackerakiUA** [comment]
Like i said, i need to check if any file is changed in the project, but i don't need restart on any file change. So i would like to restart manually, you have that option, and somehow disable the automatically restart.

**Comment by remy** [comment]
I think being able to prevent the restart event has been looked at before, but it didn't really get anywhere.

If it's what you're after, I think I've got an idea as to how you could handle it. Something like this added to the [first line of `restartBus`](https://github.com/remy/nodemon/blob/1cda8fae4333f3e37c54d0923d99b9132fb6a010/lib/monitor/watch.js#L203):

```js
// in restartBus
let prevent = false;
bus.emit('restart?', (value = true) => prevent = value);
if (prevent) {
  // user prevented restart
  return;
}
```

Then in your user code, you'd do something like:

```js
nodemon.on('restart?', prevent => {
  if (shouldRestartNodemon() === false) {
    prevent();
  }
});

// later…
nodemon.emit('restart'); // manually restart
```

How does that look/read?

**Comment by CrackerakiUA** [comment]
Checking it.

**Comment by CrackerakiUA** [comment]
Yes, but i am using nodemon in many computer, so i need something without the package. This will not work for PR.
Prefferably something like 
```
var nodemon = require('nodemon');
nodemon({
  disabled_reload: true,
  ...
});
