### ISSUE TITLE
Nodemon interferes with reading keypress events

### ISSUE THREAD

**Issue by stockholmux** [remy/nodemon#1265]
- `nodemon -v`: 1.15.1
- `node -v`: v6.9.4
- Operating system/terminal environment:  macOS 10.12.6 
- Command you ran: `nodemon index.js` (see below)

### Expected behaviour
Nodemon will not interfere with keypress events on scripts being executed/watched.

### Actual behaviour
In a script that uses [chjj/blessed](https://github.com/chjj/blessed) ran under nodemon, keypress events are not generated on actual key presses, but after the enter/return key is pressed. The same script ran with just `node` instead of `nodemon` events are dispatched on every key press.

### Steps to reproduce
This script will work properly under `node`, logging each key press as soon as it happens. Under `nodemon` you see the keys on the screen and once hitting enter, the events will all come at once.
```
const
  blessed   = require('blessed'),
  screen    = blessed.screen();

screen.render();
screen.on('keypress', function(ch, key){
  console.log(JSON.stringify(key));
});
```
I suspect this has something to do with `nodemon`'s 'rs' feature.

(cross posted on [blessed](https://github.com/chjj/blessed/issues/334#issuecomment-368033168))

**Comment by remy** [comment]
Via `nodemon --help options`:

```
  -I, --no-stdin ........... nodemon passes stdin directly to child process
```

Using `nodemon -I index.js` works.

**Comment by remy** [comment]
The next release will make it clearer in `nodemon --help` where there are more options (since I don't think it was entirely clear from the current help):

<img width="945" alt="screen shot 2018-02-26 at 22 08 11" src="https://user-images.githubusercontent.com/13700/36698367-95873bac-1b41-11e8-8ea1-f62ba2bbfb64.png">

**Comment by stockholmux** [comment]
Thanks! I kinda expected there to be an option to do this.

And yeah, I did run `--help`, but I totally didn't expect to literally run `nodemon --help options`. It currently doesn't look like one command.

Underlining helps from your screenshot, but it might be more visible as a single command with double quotes around it but YMMV.

Great work on nodemon, btw.
