### ISSUE TITLE
zsh:command not found:nodemon

### ISSUE THREAD

**Issue by zoiew** [remy/nodemon#1266]
when i have installed nodemon,i excuted nodemon server.js,but my computer report an error : zsh:command not found:nodemon.
why,what should i do,you had better express in Chines if you can,thank you

**Comment by remy** [comment]
Recommend uninstalling nodemon and possibly npm and reinstalling both. This doesn't really seem like a nodemon issue (so closing). Happy to reopen with more information or specific details how this is nodemon.
