### ISSUE TITLE
Pretty output when using through Node.js API

### ISSUE THREAD

**Issue by Sawtaytoes** [remy/nodemon#1267]
- `nodemon -v`: 1.15.0
- `node -v`: 8.9.4
- Operating system/terminal environment:  Windows 10 64-bit using Cmder in `cmd` mode.
- Command you ran: `nodemon .` vs `node .`

### Expected behaviour
I get pretty print output and CLI colors when using Nodemon from the console.
```
[FILE_PATH]\runScript.js:50
throw 'hi'
^
hi
[nodemon] app crashed - waiting for file changes before starting...
[nodemon] restarting due to changes...
[nodemon] starting `node index.js index`
```

### Actual behaviour
No output except what I've configured myself when using the `.on()` listener functions.

### Steps to reproduce
Require Nodemon through Node.js instead of running as a separate command.

## Issue
Normally, I can run Nodemon using `nodemon .`, and I can use this in the `scripts` part of `package.json`.

I moved to doing everything in a shared npm package. If I want to run `nodemon` now, I can't do `npm run X` because `X` in this case is in the local package.json, not the package.json for an npm package.

My workaround is doing everything through Node.js directly. I did `require('nodemon')` and was able to achieve similar results to running it normally.

This is an example:
```json
// package.json
{
  "scripts": { "start": "node ." }
}
```

```shell
# Shell Command
npm start monitor
```

```js
// index.js
process.argv[2] === 'monitor'
? (
  nodemon({
    args: process.argv.slice(3)
  })
)
: require('./app')
```

**Comment by remy** [comment]
Can you give me full details on how to replicate? I tried your code above without changes, and the first obvious missing part is that nodemon isn't required at all - so I'm suspecting I'm getting a snippet rather than a replicable example.

If you can send me that, I can take a look.

**Comment by remy** [comment]
Okay, I got there in the end.

You need to use the [documentation](https://github.com/remy/nodemon/blob/master/doc/events.md#messages) and use the `colour` prop if you want colour output:

```js
	nodemon({
      args: process.argv.slice(3)
    }).on('log', ({ colour }) => {
      console.log(colour);
    })
```

**Comment by Sawtaytoes** [comment]
This was example code to detail the process I'm using. Colors weren't the issue so much as there was no logging info unless I setup `.on()` listeners.

Are you saying if I use `.on('log', ({ colour }) => console.log(colour))`, it will do the pretty output that Nodemon normally has when the `log` listener is fired?

**Comment by remy** [comment]
Yup
