### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by dhffdh** [remy/nodemon#1276]
- `nodemon -v`: 1.17.0
- `node -v`: v8.9.4
- Operating system/terminal environment: 
- Command you ran: nodemon server.js

[nodemon] 1.17.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
TypeError: Assignment to constant variable.
    at Object.run (D:\WORKING\projects\mongosse-lesson-1\node_modules\nodemon\lib\monitor\run.js:70:8)
    at D:\WORKING\projects\mongosse-lesson-1\node_modules\nodemon\lib\nodemon.js:221:13
    at D:\WORKING\projects\mongosse-lesson-1\node_modules\nodemon\lib\config\index.js:82:7
    at <anonymous>
(node:13808) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Assignment to constant variable.
(node:13808) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled
will terminate the Node.js process with a non-zero exit code.

###WTF???

**Comment by remy** [comment]
So…should I just ignore the "what the fuck" part? And try to fix your bug instead?

**Comment by remy** [comment]
Fixed being deployed to 1.17.1 now: https://travis-ci.org/remy/nodemon/builds/346891485

**Comment by Odrinwhite** [comment]
How did you manage to have that const assignment in production code?

**Comment by remy** [comment]
No idea. Particularly as there's so many tests. I did notice that they tests went a bit weird and release 3 tagged versions, so _maybe_ they did some kind of weird run. Again, no idea. It should have passed tests.

**Comment by Odrinwhite** [comment]
Well shit happens, keep up the good work : )

**Comment by dhffdh** [comment]
Soo, What do I need to do to make the code work?

**Comment by remy** [comment]
Bump to latest 1.17.1
