### ISSUE TITLE
Issue with using nodemon 

### ISSUE THREAD

**Issue by efidje** [remy/nodemon#1278]
- `nodemon -v`: 1.17.1
- `node -v`: 8.9.4
- Operating system/terminal environment: Windows 10 / Cmder
- Command you ran: nodemon www

### Expected behaviour
Followed this youtube tutorial;
https://www.youtube.com/watch?v=bf8L9tQi_MQ
At 12:55 into the video the instructor is targeting a different route and gets the expected response in the browser. 

### Actual behaviour
With nodemon running, I get a 404 error at this point in the browser (chrome) when I try to change the route in the same way as in the tutorial.
I stopped nodemon and just did node www before trying the same route in the browser. This time it worked OK and gave the expected response.
Probably a minor "bug" somewhere.

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
I've not looked at the video (yet), but are you able to provide code to replicate what you're seeing?

**Comment by efidje** [comment]
Hi Remy,

I have not looked further into it. I've just been following some
tutorial videos on Node.js programming where they have used nodemon.
It's worked fine up till now and I'm not sure if it is actually
nodemon that's at fault, could maybe be the browser. It was the first
time I noticed a difference between running node versus running
nodemon with a xxxx.js file

Regards

**Comment by remy** [comment]
If you can provide example code and the commands you're running then I
might be able to give you a better answer.
