### ISSUE TITLE
issue with nodemon 

### ISSUE THREAD

**Issue by littleski** [remy/nodemon#1280]
- `nodemon -v`:1.17.1
- `node -v`: 6.13.1
- Operating system/terminal environment:  mac os
- Command you ran: gulp serve

### Summary

Last version of nodemon is causing me issues. It may be due to gulp-nodemon not being up to date in its use of nodemon, or in nodemon itself. I will try bypassing gulp-nodemon to check, but it really feel like something has been broken down. 

It was working nicely with 1.14.11, and we haven't got an issue with it for more than 1 year.

### Expected behaviour

Proper running, i-e, something like this
16:55:08] Using gulpfile ~/Documents/portal/gulpfile.js
[16:55:08] Starting 'serve'...
[16:55:09] Finished 'serve' after 193 ms
[16:55:09] [nodemon] 1.11.0
[16:55:09] [nodemon] to restart at any time, enter `rs`
[16:55:09] [nodemon] watching: index.js config.json package.json /Users/ski/Documents/api/lib/**/*
[16:55:09] [nodemon] starting `node index.js`
portal: web listening on 0.0.0.0:7000

### Actual behaviour
[16:56:14] Using gulpfile ~/Documents/portal/gulpfile.js
[16:56:14] Starting 'serve'...
[16:56:15] Finished 'serve' after 201 ms
/Users/ski/Documents/portal/node_modules/gulp-nodemon/node_modules/nodemon/lib/config/load.js:74
          const n = options.scriptPosition || options.args.length;
                                                          ^

TypeError: Cannot read property 'length' of undefined
    at /Users/ski/Documents/portal/node_modules/gulp-nodemon/node_modules/nodemon/lib/config/load.js:74:59
    at callback (/Users/ski/Documents/portal/node_modules/gulp-nodemon/node_modules/nodemon/lib/config/load.js:174:5)
    at /Users/ski/Documents/portal/node_modules/gulp-nodemon/node_modules/nodemon/lib/config/load.js:214:5
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)

Users/ski/Documents/portal/node_modules/gulp-nodemon/node_modules/nodemon/lib/config/load.js:74
          const n = options.scriptPosition || options.args.length;
                                                          ^
TypeError: Cannot read property 'length' of undefined
    at /Users/ski/Documents/portal/node_modules/gulp-nodemon/node_modules/nodemon/lib/config/load.js:74:59
    at callback (/Users/ski/Documents/portal/node_modules/gulp-nodemon/node_modules/nodemon/lib/config/load.js:174:5)
    at /Users/ski/Documents/portal/node_modules/gulp-nodemon/node_modules/nodemon/lib/config/load.js:214:5
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)

### Steps to reproduce

gulp file is quite straigth forward
```
gulp.task('serve', function () {
    return $.nodemon({
  "verbose": false,
  "env": {
    "DEBUG": "ionisx*"
  },
  "watch": [
    "index.js",
    "config.json",
    "package.json",
    "lib/"
  ]
});
});

```
---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
> gulp file is quite straigth forward

Sorry, but believe it or not, I've don't use (and haven't used) gulp, so can you provide at least a package.json file so that I can actually replicate?

**Comment by littleski** [comment]
in package.json, have :
    "gulp": "^3.9.1",
    "gulp-nodemon": "^2.2.1",

gulpfile.js, something like this should do the trick
```
const gulp        = require('gulp');

// Load plugins
const $           = require('gulp-load-plugins')();

gulp.task('serve', function () {
    return $.nodemon({
  "verbose": false,
  "watch": [
    "index.js",
    "config.json",
    "package.json",
    "lib/"
  ]
});
});
```

If you want to test with 14.1.1, you can add
    "nodemon": "=1.14.11", to package.json
and change the gulpfile to 

```
gulp.task('serve', function () {
    return $.nodemon({
 "nodemon": require('nodemon'),
  "verbose": false,
  "watch": [
    "index.js",
    "config.json",
    "package.json",
    "lib/"
  ]
});
});
```

I use this workaround for the moment to resume working, since we use nodemon only in dev.
