### ISSUE TITLE
Vulnerable dependencies; problematic for local installs

### ISSUE THREAD

**Issue by srcspider** [remy/nodemon#1284]
- `npx nodemon -v`: 1.17.1
- `node -v`: v8.9.3
- Operating system/terminal environment: ubuntu 16.04
- Command you ran:  n/a

**Steps to Reproduce**

```bash
# npx just conveniently lets you run things installed in your local ./node_modules/bin
yarn global add npx

# intentionally not installing globally
yarn add nodemon@1

# nsp is a vulnerability checkers
yarn add nsp
npx nsp
```

Links:
 - https://www.npmjs.com/package/npx
 - https://www.npmjs.com/package/nsp

### Expected behaviour

Output of `npx nsp` should be something along the lines of
```
No vulnerabilities found.
```

### Actual behaviour

```
(+) 1 vulnerability found
┌────────────┬────────────────────────────────────────────────────────────────────┐
│            │ Prototype pollution attack                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Name       │ hoek                                                               │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ CVSS       │ 4 (Medium)                                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Installed  │ 2.16.3                                                             │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Vulnerable │ <= 4.2.0 || >= 5.0.0 < 5.0.3                                       │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Patched    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                        │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Path       │ *************** > nodemon@1.17.1 > chokidar@2.0.2 >              │
│            │ fsevents@1.1.3 > node-pre-gyp@0.6.39 > hawk@3.1.3 > hoek@2.16.3    │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ More Info  │ https://nodesecurity.io/advisories/566                             │
└────────────┴────────────────────────────────────────────────────────────────────┘
```

Seems you need to update this `hawk` package.

When installed globally this warning doesn't appear, but if installed locally using vulnerable packages (even if it's inconsequential here I think) the dependencies have to be clean unfortunately.

**Why not install globally?**

It's less of a hassle. No shared cross-project globals (outside of `npx`). I know everything works this way.

**Comment by remy** [comment]
I'd rather the issue was raised with proper investigation… "seems you need to update hawk package" isn't the case.

Hawk is at 7, but hawk@3 is used by [node-pre-gyp](https://snyk.io/test/npm/node-pre-gyp?severity=high&severity=medium&severity=low). 

You can track the _actual_ vuln update here: https://github.com/mapbox/node-pre-gyp/issues/346

Closing, but as soon as the update is pushed to the deep dependencies, it should automatically inherit via new dep installation.
