### ISSUE TITLE
Complete ignore path documentation

### ISSUE THREAD

**Issue by marcospgp** [remy/nodemon#1291]
I'm trying to ignore all `.json` files under a particular directory, including all subfolders.

Will this work?

`"nodemonConfig": {
    "ignore": [
      "example/**/*.json"
    ]
  },`

If possible, please update the readme with this information.

Thank you very much for all your hard work!

**Comment by remy** [comment]
I'm not sure if that rule will work without spinning up the directory and testing it…which I suspect you might be able to confirm faster than me.

Re: updating the readme - is there something incorrect in there, or are you just suggesting adding?

**Comment by marcospgp** [comment]
I tested it and it seems to work, how is the ignore path handled under the hood?

Also yes, I was suggesting adding 😄

**Comment by woodardj** [comment]
This probably ought to be addressed… I just discovered that:

```
"ignore": [
      "__tests__/*",
      "docs/*",
      "public/*",
    ]
```
and 
```
"ignore": [
      "__tests__/*",
      "docs/*",
      "public/",
    ]
```
Have pretty different outcomes in terms of which files get ignored. (The former will ignore BOTH `<project root>/public/` and `<project root>/some/file/path/public/` whereas the second only ignores the former. Had to read the code and ended up making a wild guess to ignore the one but watch the other.
