### ISSUE TITLE
Idea: Don't start, just watch if file doesn't exist

### ISSUE THREAD

**Issue by ThisIsMissEm** [remy/nodemon#1297]
I'm building a new project where the server is compiled with webpack, consequently, `build/server.js` doesn't actually exist until webpack has done the first build. On the first run, the following error is produced:
```
[nodemon] starting `node build/server.js`
module.js:540
    throw err;
    ^

Error: Cannot find module '/Users/emelia/Work/UnobviousTechnology/repos/privatepatrons/build/server.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
[nodemon] app crashed - waiting for file changes before starting...
```

It might be an idea to actually test "does the supplied file actually exist?" before trying to run the `--exec`, I'm using:

```
nodemon --watch 'build/server.js' --exec 'node build/server.js'
```

The reason for using `--watch` and `--exec` is to work-around the same issue — if I just do `nodemon build/server.js`, then nodemon starts, but it fails to actually watch and restart when `build/server.js` is created.

I'm not sure what the right answer here is, and this is really just my hack/idea around it, and I couldn't find any other reasonable solutions (that worked).

Mainly the thing that is irking me is the stacktrace there because in the past traces such as that have caused coworkers quite some confusion, thinking that there's something wrong when really it's just business as usual.

- `nodemon -v`: 1.17.2
- `node -v`: v8.9.4
- Operating system/terminal environment: os x Sierra
- Command you ran: `yarn start:dev` (this is the nodemon command above)

**Comment by ThisIsMissEm** [comment]
Here's the full setup if you'd like to play around with it: https://github.com/Unobvious-Technology/privatepatrons/commit/2c420efeef7b621e1b8a33574df903dfc0bab102

Just doing `yarn` and `yarn start:dev` will get you the working server and you'll see what I mean.

**Comment by remy** [comment]
Out of interest, what does node do if you pass it a non existent file? (Can't test myself right now - got a self inflicted ban on the laptop over the long weekend! 🙂)

**Comment by remy** [comment]
Broke my embargo! 

```bash
node remy
module.js:538
    throw err;
    ^

Error: Cannot find module '/Users/remy/Sites/nodemon/remy'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

I _think_ it makes more sense to be consistent with the executing process.

I wonder if you used the `--on-change-only` flag when starting nodemon, whether it would mitigate the thrown error you're seeing?

**Comment by ThisIsMissEm** [comment]
I'd have to test this later, but I don't think so. Because you also want the server to start straight away if it can.

**Comment by pasan9** [comment]
Any updates on this?

Right now I'm using a work around like

`mkdir -p dist && touch ./dist/app.js && nodemon --watch ./dist ./dist/app.js`

Creating an empty file. This removes the error, but is not the right solution.

**Comment by ThisIsMissEm** [comment]
I think perhaps it could log that it couldn't find the file to watch, and then check every N seconds, perhaps with a back off.

**Comment by kaisellgren** [comment]
I'm also having this problem. Since nodemon is a watcher whose purpose is to run the process after a change, I think it only makes sense that it will wait until the file that's being monitored exists before running it.

@pasan9 solution works perfectly, but it's a shame we have to do this manually by ourselves. Maybe some future version of nodemon could handle this situation better.

**Comment by raphaelpreston** [comment]
Would love to see this feature!

**Comment by daniel-nagy** [comment]
I just ran into this issue and it was incredibly difficult to debug because I was using nodemon with concurrently. For some reason, when the file did not exist nodemon would restart concurrently causing an infinite loop.
