### ISSUE TITLE
failed to start process, "source" exec not found

### ISSUE THREAD

**Issue by lsimmons2** [remy/nodemon#1298]
I'm editing a bash file and want to monitor it and source it whenever it changes, but nodemon is not able to run the source command.

`file_im_editing.sh`

    #!/bin/bash

    function_im_editing(){
        echo "sup?"
    }

`nodemon --exec source ./file_im_editing.sh`

gives:

    [nodemon] 1.17.2
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: *.*
    [nodemon] starting `source ./file_im_editing.sh`
    sh: 1: source: not found
    [nodemon] failed to start process, "source" exec not found
    [nodemon] Error
        at Bus.utils.bus.on (/home/leo/.nvm/versions/node/v6.11.2/lib/node_modules/nodemon/lib/nodemon.js:147:25)
        at emitOne (events.js:101:20)
        at Bus.emit (events.js:188:7)
        at ChildProcess.<anonymous> (/home/leo/.nvm/versions/node/v6.11.2/lib/node_modules/nodemon/lib/monitor/run.js:157:11)
        at emitTwo (events.js:106:13)
        at ChildProcess.emit (events.js:191:7)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

`nodemon --exec source ./file_im_editing.sh --dump`

gives:

    [nodemon] 1.17.2
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: *.*
    --------------
    node: v6.11.2
    nodemon: 1.17.2
    command: /home/leo/.nvm/versions/node/v6.11.2/bin/node /home/leo/.nvm/versions/node/v6.11.2/bin/nodemon --exec source ./file_im_editing.sh --dump
    cwd: /home/leo
    OS: linux x64
    --------------
    { run: false,
      system: { cwd: '/home/leo' },
      required: false,
      dirs: [ '/home/leo' ],
      timeout: 1000,
      options: 
       { exec: 'source',
         dump: true,
         ignore: 
          [ '**/.git/**',
            '**/.nyc_output/**',
            '**/.sass-cache/**',
            '**/bower_components/**',
            '**/coverage/**',
            '**/node_modules/**',
            re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/ ],
         watch: [ '*.*', re: /.*\..*/ ],
         ignoreRoot: 
          [ '**/.git/**',
            '**/.nyc_output/**',
            '**/.sass-cache/**',
            '**/bower_components/**',
            '**/coverage/**',
            '**/node_modules/**' ],
         restartable: 'rs',
         colours: true,
         execMap: { py: 'python', rb: 'ruby' },
         stdin: true,
         runOnChangeOnly: false,
         verbose: false,
         signal: 'SIGUSR2',
         stdout: true,
         watchOptions: {},
         execOptions: 
          { script: './file_im_editing.sh',
            exec: 'source',
            args: [],
            scriptPosition: 0,
            nodeArgs: undefined,
            execArgs: [],
            ext: 'sh,json',
            env: {} },
         monitor: 
          [ '*.*',
            '!**/.git/**',
            '!**/.nyc_output/**',
            '!**/.sass-cache/**',
            '!**/bower_components/**',
            '!**/coverage/**',
            '!**/node_modules/**' ] },
      load: [Function],
      reset: [Function: reset],
      lastStarted: 0,
      loaded: [],
      watchInterval: null,
      signal: 'SIGUSR2',
      command: 
       { raw: { executable: 'source', args: [ './file_im_editing.sh' ] },
         string: 'source ./file_im_editing.sh' } }
    -

os is ubuntu 16

**Comment by remy** [comment]
Is there a version of nodemon where this ever worked (ie. Is it a regression)?

**Comment by lsimmons2** [comment]
Doesn't look like it. Versions 1.12.1 and 1.0.0 give:

    ~$ nodemon --exec source file_im_editing.sh 
    [nodemon] 1.12.1
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: *.*
    [nodemon] starting `source file_im_editing.sh`
    sh: 1: source: not found
    [nodemon] failed to start process, "source" exec not found
    events.js:165
          throw err;
          ^
    Error: Uncaught, unspecified "error" event. (127)
        at Bus.emit (events.js:163:17)
        at ChildProcess.<anonymous> (/home/leo/.nvm/versions/node/v6.11.2/lib/node_modules/nodemon/lib/monitor/run.js:128:11)
        at emitTwo (events.js:106:13)
        at ChildProcess.emit (events.js:191:7)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)



    ~$ nodemon --exec source file_im_editing.sh 
    21 Mar 14:37:24 - [nodemon] v1.0.0
    21 Mar 14:37:24 - [nodemon] to restart at any time, enter `rs`
    21 Mar 14:37:24 - [nodemon] watching: /home/leo
    21 Mar 14:37:24 - [nodemon] starting `source file_im_editing.sh`
    [nodemon] unable to spawn executable: source

**Comment by remy** [comment]
@stalebot hold off.

@lsimmons2 I don't know for certain, but I think this is a system level problem that node can't spawn `source` to run the command. Oddly I _can_ spawn source on a mac.

A comparable test would be to use `source` in an npm script to see if `npm run X` is able to spawn the command?

**Comment by removed-usr** [comment]
This used to work for me, I used to run python scripts. 

Back then I installed node using apt or installers, now I just used the binary. 

I wonder if that's the cause.

**Comment by removed-usr** [comment]
I "fixed" this

Instead of writing source, we have to write the language of the script 

Instead of this
`nodemon --exec source  test.py`
do this
``nodemon --exec python3  test.py``
