### ISSUE TITLE
Opt out of postinstall

### ISSUE THREAD

**Issue by mlucool** [remy/nodemon#1299]
Hi,

I completely get why you would want something that you know some people see, but it has interfered with things that parse output. I am seeing the use of the postinstall step growing in a large number of libraries. To help with this (especially in CI), what do you think about something like putting `NODE_NO_SUPPORT_MESSAGE=true` in your environment to opt out? Since this is explicit, you know people will have at least seen your plea for help.

Thanks for the consideration!

**Comment by remy** [comment]
Firstly, you're using freeware, so it comes with the software.

More importantly, I've put down a proposal for how this should and could be handled (storing a token similarly to update notifier) and yet no one has sent a PR to implement. 

Closing (again) in lieu of that PR.

**Comment by remy** [comment]
(sorry if I sound tetchy, it's not the first time this kind of discussion has come up!)

**Comment by mlucool** [comment]
I understand @remy. Do you have a link to the proposal?

**Comment by remy** [comment]
It was this (in a locked and closed issue):

> a PR that's smart that detects that the message has been shown in the last 24 hours and doesn't show it again for that day using a (root) config flag?

I think looking at how update notifier works would benefit from using the same package for state storage too.
