### ISSUE TITLE
nodemon does not work with bash

### ISSUE THREAD

**Issue by ghost** [remy/nodemon#130]
> nodemon --exec '/bin/bash nodesRunning.bash'
> 9 Dec 18:07:36 - [nodemon] v0.6.23
> 9 Dec 18:07:36 - [nodemon] watching: /home/rumplefraggle/home
> 9 Dec 18:07:36 - [nodemon] starting `/bin/bash nodesRunning.bash`
> (Not all processes could be identified, non-owned process info
>  will not be shown, you would have to be root to see it all.)
> process tcp 0 0 0.0.0.0:5000 0.0.0.0:\* LISTEN 538/node
> process tcp 0 0 0.0.0.0:7535 0.0.0.0:\* LISTEN 460/node
> 9 Dec 18:07:36 - [nodemon] clean exit - waiting for changes before restart

i change things in the directory and it does not restart
it seems to be just a problem with bash

**Comment by KyleMit** [comment]
If you're on windows, you'll need to explicitly pass the shell that's executing the script in the `--exec` param like this:

```diff
- nodemon --exec "./script.sh" "*.js"
+ nodemon --exec "bash ./script.sh" "*.js"
```
