### ISSUE TITLE
No response, cannot use  -v  -h  etc.

### ISSUE THREAD

**Issue by joshuajoconnell** [remy/nodemon#1300]
I have an issue where I cannot get 'nodemon -v' or 'nodemon -h' or any response out of any nodemon command except 'command not found'.

installed with sudo npm install -g nodemon
installation completes with no errors reported

I am using bash, I have un-installed it and re-installed it multiple times. I tried to install it globally and locally neither have worked. I have uninstalled and re-installed node and then installed globally nodemon again. I know the issue is with me or something I don't know, I am still new to node but I have searched for hours over a fix and found none.

- `nodemon -v`:   1.17.2
- `node -v`: 9.9.0
- Operating system/terminal environment: Mac High Sierra terminal bash
- Command you ran: nodemon -v, nodemon -h, nodemon app.js

### Expected behaviour
It to show me the help, version, just work, etc.

### Actual behaviour
'command not found' to every command I try and send to it.

**Comment by remy** [comment]
It seems more like nodemon isn't on your path somehow.

Can you test and post the output from `which nodemon`. This is what I get:

```bash
❯ which nodemon
/Users/remy/.nvm/versions/node/v8.9.1/bin/nodemon
```

**Comment by joshuajoconnell** [comment]
So sorry for the delay. When I run which nodemon I get no response, just a new command line loads ready for a new command.

**Comment by remy** [comment]
This means it's not installed, or its installed in a place your command line can't find.

**Comment by remy** [comment]
Reinstall node (which will reinstall npm and restore your paths which I'm guessing are wrong).
