### ISSUE TITLE
nodemon and set DEBUG won't work

### ISSUE THREAD

**Issue by starfilledjar** [remy/nodemon#1301]
Hello,

I'm very new to nodejs, and thus nodemon as well. I'm on a windows machine, and when I try having the following start script in my package.json I get the subesquent error:

package.json
`  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "set DEBUG=app:* & nodemon app.js",
    "lint": "eslint app.js"
  }`

error:

> events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE :::4000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (C:\Users\CG042557\library\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\Users\CG042557\library\app.js:50:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

However, when I change my start script to read `"set DEBUG=app:* & node app.js` everything runs smoothly. Am I using the wrong syntax?

Any help is greatly appreciated, let me know if I can provide more details/specifics.

Thanks. 
- `nodemon -v`: 1.17.2
- `node -v`: 8.10.0
- Operating system/terminal environment: windows 10

**Comment by remy** [comment]
The error suggests that your server is already running, but it does seem odd that without nodemon it runs fine. 

I'll try to test with my windows machine some point. Are you using the CMD.exe prompt?

**Comment by starfilledjar** [comment]
If by 'using the CMD.exe prompt' you mean: am I running this through command line using npm start. The answer is yes. If not, I might be too beginner to even understand the question, heh.

**Comment by remy** [comment]
No, I mean, which program are you using to get to the command line. Frustratingly, Windows offers about 5 different kinds of command prompt, each have an effect on how commands run. As screenshot would be the fastest way to be sure.

**Comment by starfilledjar** [comment]
Oh, I am using VS Code. The weird thing is...I came in to work this morning and gave it a try, all the same stuff, in VS Code, and now it's working. I'm not sure what changed between yesterday afternoon and this morning, but I think it was probably something I was doing on my side, since I'm new to all of this. I appreciate you taking the time to look into it and respond to me though.

**Comment by remy** [comment]
No problem.
