### ISSUE TITLE
Feature request-detect already running nodemon and be able resolve the conflict by killing it

### ISSUE THREAD

**Issue by capaj** [remy/nodemon#1303]
There is quite a few issues here where people are claiming that they are getting `EADDRINUSE` error. There's even open one right now with the tag "can't replicate" . IMHO most of those people experienced two nodemon instances running in a single directory and both fighting each other making it very confusing. I had this happened today and lost couple hours on it debugging anything related to process signals until I realised that I just have another nodemon process running in the same directory.
So I would request that:

1. upon startup detect if another nodemon is running in the same dir
2. if it does, prompt user `There is already nodemon running in this folder, do you want to kill it? (y/n)`
3. when user chose `y` it should kill the process, if `n`, just exit

or maybe just kill the old one without asking?

**Comment by remy** [comment]
Just for clarity, that isnt the problem that they've outlined. It's that nodemon restarts leaving the original child running. 

But also, I think this approach has multiple problems: firstly, most importantly: how? Also, running two nodemon's doing the exact same task, seems more like an edge case, and what's more likely is that you're running two to perform two separate tasks.

I appreciate you got caught out by this yourself, but if you take nodemon out the equation, you're left with the same problem you faced when you spend time debugging. 

I'm going to close this based on it being an edge case. If many others have the same confusion, then I'd be happy to reopen if it has a PR attached. 

Thanks so much.
