### ISSUE TITLE
zsh: command not found

### ISSUE THREAD

**Issue by TheDom1** [remy/nodemon#1304]
- `nodemon -v`: couldn't get it installed 
- `node -v`: 9.9.0
- Operating system/terminal environment: MacOS, ZSH
- Command you ran: sudo npm i -g nodemon

### Expected behaviour
Installation to make use of nodemon functionality in project

### Actual behaviour
zsh: command not found: nodemon

### Steps to reproduce
sudo npm i -g nodemon
zsh: command not found: nodemon

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Reinstall node (which will reinstall npm and restore your paths which I'm guessing are wrong).

**Comment by TheDom1** [comment]
That also has not fixed the issue.

**Comment by remy** [comment]
I think this is an npm problem on your machine, and not specific to nodemon. I suggest raising with npm as they'll be able to help you diagnose.
