### ISSUE TITLE
nodemon 1.17.3 infinite watch node_modules folder

### ISSUE THREAD

**Issue by darky** [remy/nodemon#1305]
- `nodemon -v`: 1.17.3
- `node -v`: 9.10.1
- Operating system/terminal environment: Arch linux 4.15.13
- Command you ran: nodemon -e ts,js,tsx,jsx,jade --inspect=9229 ./bin/www

### Expected behaviour
Not watch node_modules folder, because it not exist in *nodemon.json*

### Actual behaviour
Nodemon try to watch node_modules folder and do it infinitely on same locations

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by markonyango** [comment]
I have the same issue. My --dump output is as follows:
`[nodemon] 1.17.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
--------------
node: v9.8.0
nodemon: 1.17.3
command: /usr/bin/node /home/mark/.npm-global/bin/nodemon --dump bin/www
cwd: /home/mark/Dokumente/quasi-express
OS: linux x64
--------------
{ run: false,
  system: { cwd: '/home/mark/Dokumente/test' },
  required: false,
  dirs: [ '/home/mark/Dokumente/test' ],
  timeout: 1000,
  options: 
   { dump: true,
     ignore: 
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**',
        './uploads/*',
        'morganlog.txt',
        re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*|\.\/uploads\/.*|morganlog\.txt/ ],
     verbose: false,
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot: 
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     signal: 'SIGUSR2',
     stdout: true,
     watchOptions: {},
     execOptions: 
      { script: 'bin/www',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        execArgs: [],
        ext: 'js,hbs',
        env: {} },
     monitor: 
      [ '*.*',
        '!**/.git/**',
        '!**/.nyc_output/**',
        '!**/.sass-cache/**',
        '!**/bower_components/**',
        '!**/coverage/**',
        '!**/node_modules/**',
        '!./uploads/**/*',
        '!morganlog.txt' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [ '/home/mark/Dokumente/test/package.json' ],
  watchInterval: null,
  signal: 'SIGUSR2',
  command: 
   { raw: { executable: 'node', args: [ 'bin/www' ] },
     string: 'node bin/www' } }
--------------
`

**Comment by markonyango** [comment]
I may already have a solution to this: I run VS Code to edit my files. Although my local settings force VS Code to not watch node_modules (file-watcher), it seems to ignore my settings. Once I close VS Code I can run nodemon again, no issues whatsoever. When I open it again, I can't run nodemon from neither the internal console of VS Code nor Ubuntus terminal.
It would seem that the latest version of VS Code is hogging all the file-watch handles, causing nodemon to get the last few remaining which is apparently not enough.

**Comment by markonyango** [comment]
For now check out the link to see my "fix". I really don't want to mess with sysctl and I believe this to not be an issue of nodemon but of VS Code unless OP says this is VS Code unrelated (i.e. he doesn't use it).

**Comment by hugoduraes** [comment]
This is happening for me as well and I don't use VS Code. As a workaround, I've added `node_modules` to `.nodemodignore` file.

**Comment by remy** [comment]
@darky you haven't included the nodemon.json file you're using. Can you do so, so I can attempt to replicate?

**Comment by remy** [comment]
@darky and others - please can you include your nodemon.json file so that I can see the config you're using?
