### ISSUE TITLE
Vulnerability for Prototype pollution attack found

### ISSUE THREAD

**Issue by maevadevs** [remy/nodemon#1308]
- `nodemon -v`: 1.17.3
- `node -v`: v8.11.1
- Operating system/terminal environment: OSX 10.13.3 / Terminal & iTerm
- Command you ran: 
  - Install global `nsp`: `npm i -g nsp`
  - cd into the nodemon module folder: `cd [...]/.nvm/versions/node/v8.11.1/lib/node_modules/nodemon`
  - Run security check: `nsp check`

### Expected behaviour
(+) No known vulnerabilities found

### Actual behaviour
(+) 1 vulnerability found
![screenchot](https://user-images.githubusercontent.com/6579094/38452358-759cadaa-3a08-11e8-9368-91964f05b8b9.png)
Prototype pollution attack
More Info │ https://nodesecurity.io/advisories/566

### Steps to reproduce
- Install global `nsp`: `npm i -g nsp`
- `cd` into the `nodemon` module folder: `cd [...]/.nvm/versions/node/v8.11.1/lib/node_modules/nodemon`
- Run security check: `nsp check`

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.
N/A

**Comment by remy** [comment]
Dupe. Please search issues for my original response
