### ISSUE TITLE
Restarts on Atom file open

### ISSUE THREAD

**Issue by arei** [remy/nodemon#1309]
May be related to #1307 

- `nodemon -v`: 1.17.3
- `node -v`: 8.9.1
- Operating system/terminal environment: Windows 10, Batch file
- Command you ran: nodemon -V --watch ../Common.Node -- watch ./src --ext js.json,ts --ignore ../Common.Node/node_modules

### Expected behaviour

Opening a file in Atom should not cause nodemon to fire a restart.

### Actual behaviour

Opening a file in Atom causes nodemon to restart.

```
[nodemon] 1.17.3
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 30004 to restart
[nodemon] ignoring: C:\DEV\WORKSPACE\Cyber\Solution\Common.Node\node_modules/**/*
[nodemon] watching: C:\DEV\WORKSPACE\Cyber\Solution\Common.Node/**/* C:\DEV\WORKSPACE\Cyber\Solution\Services.Request\src/**/*
[nodemon] watching extensions: js,json,ts
[nodemon] starting `node src/StartServer.js`
[nodemon] forking
[nodemon] child pid: 16312
[nodemon] watching 409 files
```

```
[nodemon] files triggering change check: ..\Common.Node\APIServer\src\AbstractController.js
[nodemon] matched rule: **\C:\DEV\WORKSPACE\Cyber\Solution\Common.Node/**/*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] ..\Common.Node\APIServer\src\AbstractController.js

[nodemon] starting `node src/StartServer.js`
[nodemon] forking
[nodemon] child pid: 48180
```

### Steps to reproduce

1. Start application via nodemon that is watching some directory.
2. Open a file that is being watched by nodemon in Atom.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
What's causing `..\Common.Node\APIServer\src\AbstractController.js` to change?

**Comment by arei** [comment]
A more detailed test...

1). Create and enter a new directory: `nodemon-test`
2). Create a `package.json` in it.
```
{
  "main": "test.js",
  "dependencies": {
	  "nodemon": "*"
  }
}
```

3). Installed nodemon into it: `npm install nodemon`
4). Create `test.js`
```
console.log("Started.");
setInterval(()=>{
	console.log("hello.");
},500);
```

5). Create `runme.bat`
```
@ECHO OFF

REM Where is nodemon...
SET NODEMON=%CD%/node_modules/.bin/nodemon.cmd

REM Create our test files...
IF EXIST test_files RD test_files /s/q
MKDIR test_files
echo console.log(process.argv); >test_files\open_me_in_atom_0.js
echo console.log(process.argv); >test_files\open_me_in_atom_1.js
echo console.log(process.argv); >test_files\open_me_in_atom_2.js
echo console.log(process.argv); >test_files\open_me_in_atom_3.js
echo console.log(process.argv); >test_files\open_me_in_atom_4.js
echo console.log(process.argv); >test_files\open_me_in_atom_5.js
echo console.log(process.argv); >test_files\open_me_in_atom_6.js
echo console.log(process.argv); >test_files\open_me_in_atom_7.js
echo console.log(process.argv); >test_files\open_me_in_atom_8.js
echo console.log(process.argv); >test_files\open_me_in_atom_9.js

REM Run nodemon...
%NODEMON% -V test.js %*
```
6). Open Atom.
7). Create a project for nodemon-test.
8). Execute `runme.bat` from DOS.
9). Watch it run for a second. Very exciting.
10). In Atom, locate the `test_files` subdirectory and open any sub file under the directory.
11). You will see the following:
```
hello.
hello.
[nodemon] files triggering change check: test_files\open_me_in_atom_6.js
[nodemon] matched rule: **\*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] Test_files\open_me_in_atom_6.js

[nodemon] starting `node test.js`
[nodemon] forking
[nodemon] child pid: 46100
Started.
hello.
hello.
```

That's it, that's my test script.

Please note, you may need to close Atom between executions of `runme.bat`. I believe that once Atom "sees" a file, it will no longer trigger the nodemon restart on edit.

**Comment by arei** [comment]
Thinking about the last line above, I wonder if nodemon and whatever is doing the file watching in atom is in some sort of contest when the watch begins... Just musing though.

**Comment by arei** [comment]
I also find this is compounded by multiple nodemon processes watching common directories when atom is running.  If I start a second nodemon, for example, it fires a whole slew of restarts immediately. (Below is just a small example of the number of restarts triggered.) No action on the user is needed, just starting a second process while atom is running. The first, original, nodemon process also triggers a whole slew of restarts as well.

```
[nodemon] files triggering change check: ..\Common.Node\Log\package.json
[nodemon] matched rule: **\C:\DEV\WORKSPACE\CYBER\solution\Common.Node/**/*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] ..\Common.Node\Log\package.json

[nodemon] files triggering change check: ..\Common.Node\Log\src\Log.js
[nodemon] matched rule: **\C:\DEV\WORKSPACE\CYBER\solution\Common.Node/**/*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] ..\Common.Node\Log\src\Log.js

[nodemon] files triggering change check: ..\Common.Node\Clustering\package.json
[nodemon] matched rule: **\C:\DEV\WORKSPACE\CYBER\solution\Common.Node/**/*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] ..\Common.Node\Clustering\package.json

[nodemon] files triggering change check: ..\Common.Node\Clustering\src\Clustering.js
[nodemon] matched rule: **\C:\DEV\WORKSPACE\CYBER\solution\Common.Node/**/*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] ..\Common.Node\Clustering\src\Clustering.js
```

**Comment by arei** [comment]
I wonder if the act of watching a file somehow changes it. So if Atom starts watching a file (triggered by opening said file) it causes some changes that nodemon restarts on. Likewise, if I start the second nodemon process, that triggers other nodemon processes of changes...
