### ISSUE TITLE
Implement support dot env file

### ISSUE THREAD

**Issue by RobinCK** [remy/nodemon#1312]
- `nodemon -v`:
- `node -v`:
- Operating system/terminal environment: 
- Command you ran:

### Expected behaviour
add setting `env_file` in config file (nodemon.json)

```
{
  "ignore": [ ],
  "verbose": false,
  "watch": [  ],
  "delay": 2500,
  "env": {},
  "env_file": "",
  "ext": "js json ts"
}
```

Thanks

**Comment by remy** [comment]
Env loading should be separate, and won't be part of nodemon.

I use @remy/envy. Pick your own poison.
