### ISSUE TITLE
[warn] fsevents optional depends on Unsupported platform

### ISSUE THREAD

**Issue by marxenegls** [remy/nodemon#1315]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/nodemon/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

- `nodemon -v`: 1.17.3
- `node -v`: v8.9
- Operating system/terminal environment: linux x64 Debian stretch
- Command you ran: npm install -g nodemon

##I'm Considering 
shrinkwrap-scalpel

**Comment by remy** [comment]
If the shrink-wrap works for you, then definitely do that. 

fsevents comes via chokidar, which nodemon relies on, so there's nothing (so far as I know) that I *could* change here.

**Comment by marxenegls** [comment]
Hi remy ,
 schrinkwrap-scalpel didn't help, it threw the same error fsevents depend not satisfied ..
