### ISSUE TITLE
[Feature request] add option to clear the console when restarting

### ISSUE THREAD

**Issue by luisrudge** [remy/nodemon#1318]
Currently, I'm doing this:

```js
//clear.js
console.log('\x1Bc');
```

```js
//index.js
console.log('something something');
```

```json
//package.json
"scripts": {
  "run": "nodemon -q -x \"node clear && node index\""
}
```

I want to clean the console everytime nodemon restarts the process

**Comment by luisrudge** [comment]
I can add a PR if you think this is worth i

**Comment by luisrudge** [comment]
While I agree with you, my use case is very specific: I'm teaching javascript and I don't want to add a console.clear on top of every file and say "console is something we haven't studied yet, but we're using this to clear the console etc". I just want a clean file. I understand it's not a big deal for most people, I just thought it'd be a good option to have.

**Comment by remy** [comment]
This is what the nodemon events are for. You can include either a global or local `nodemon.json` file as per the following to do what you're after. 

As per the [design principles](https://github.com/remy/nodemon#design-principles), I'd rather re-use the current tech rather than introduce new features:

```json
{
  "events": {
    "start": "echo \"\\x1Bc\""
  }
}
```

**Comment by luisrudge** [comment]
I didn't think about this. Thanks!

**Comment by iki** [comment]
Nice solution!

Regarding implementation, Windows and some shells may not support hex code escaping, so if you want to allow people running the thing on more platforms, you can change it to:
```
{
  "events": {
    "start": "echo console.clear() | node"
  }
}
```

**Comment by invegat** [comment]
on Ubuntu  18.04 I had to but single quotes around 'console.clear'

**Comment by amiralies** [comment]
I use this in command line
```sh
nodemon -x "clear;node" file.js
```

**Comment by KostyaTretyak** [comment]
> I had issues with `"start": "node -e console.clear()"`. So instead I just have
> 
> ```js
> "events": {
>     "start": "clear"
> }
> ```

On Windown it's works?

**Comment by Sam5399** [comment]
app.listen(PORT, () => {
    console.clear();
    console.log(`server is listening at port number:${PORT}`);
})

do like this , it will clear the console everytime you will make changes and then save it .

**Comment by jamesvillarrubia** [comment]
Struggled with this on my mac in terminal.  Ended up doing in `package.json`

```json
"test": "printf '\\33c\\e[3J' && npm run lint && npm run mocha",
```

**Comment by remy** [comment]
@jamesvillarrubia did this not work for you? https://github.com/remy/nodemon/issues/1318#issuecomment-530999082 - the `nodemon.json` method should be fairly clean.

**Comment by tinyroy** [comment]
To clear terminal and clear scrollback history, in `nodemon.json` : 

```
{
  "events": {
    "start": "clear && printf \"\\e[3J\""
  }
}
```

**Comment by masihjahangiri** [comment]
# Windows OS
## Javascript:
```
"start": "nodemon -x \"cls && node\" index.js",
```
## Typescript:
```
"start": "nodemon -x \"cls && ts-node\" index.ts",
```

**Comment by MohamedFaroukAbdelazeem** [comment]
`"start:dev":"nodemon -x 'clear;printf \"\\e[3J\";node' app.js "`

**Comment by cuppachino** [comment]
This preserves the scrollback buffer on Windows

```json
{
  "scripts": {
    "watch": "nodemon --watch ./src -x \"pnpm build && pnpm clear && pnpm start\"",
    "clear": "node -e \"process.stdout.write('\\u001B[2J\\u001B[0;0f')\""
  }
}
```

**Comment by shrutsureja** [comment]
A Simple and Short way is this and i find it effective because some time i need to clear the console and sometimes not so, Hope it helps
```
//backend/index.js - at the end 
app.listen(3000, ()=>{
  setTimeout(()=>{
    console.clear();
    console.log("listing on port 3000");
  }, 3000)
});
```

and in the `package.json` 
```
{ 
...
 "scripts": {
    "start" : "nodemon index.js"
  }
...
}
```
