### ISSUE TITLE
Run webpack to transpile to ES5 before restarting the server

### ISSUE THREAD

**Issue by aftabnaveed** [remy/nodemon#1319]
I am working on an application which requires my project to be transpiled to ES5 using Babel before the server can actually start. Is there a way to run the webpack and transpile the file before restarting the node server? 

Here is how I do it now: 
Step 1: 
`webpack --config config/webpack.ssr.config.js
`
Step 2
`node ssr/hypernova.js`

Now when I run nodemon on
` nodemon ssr/hypernova.js
`

It works perfectly fine and restarts hypernova.js when I change files, but my hypernova.js server needs a transpiled file. How do I combine those two steps into one using nodemon?

**Comment by remy** [comment]
I'm not entirely clear on what you're asking or saying, but as a stab at a guess, is this the same as this issue/feature request: #1297 ?
