### ISSUE TITLE
Restarts for non watched files

### ISSUE THREAD

**Issue by mrchief** [remy/nodemon#1320]
- `nodemon -v`: 1.17.3
- `node -v`: 8.9.4
- Operating system/terminal environment: Win 7 x64
- Command you ran: `nodemon index.js --inspect --exec babel-node`

**nodemon.json**

```
{
  "delay": "2500",
  "watch": [
    "index.js",
    "tools/webpack/",
    "!tools/webpack/webpack.server.babel.js",
    "src/server.js",
    "src/utils/Html.js"
  ]
}
```

### Expected behaviour
Nodemon should not restart if the files being watched have not changed

### Actual behaviour
Nodemon restarts arbitrarily

### Steps to reproduce
I'm using hot reload to watch/reload for client side file changes (which are other files in `src` folder) and nodemon to restart the process when only those files listed in the config changes. 

This worked fine in 1.15.0.

However, starting few days back, I started seeing same errors as #1259 (been using this setup without issues for last 6 months).  I saw the fix and decided to upgrade. Now with current version, nodemon is restarting more often. #1260 seems like a suspect but I'm not sure.

You can use create-react-app along with the provided nodemon.json to reproduce this. Doesn't happen consistently but happens frequently enough.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

--------------

```
node: v8.9.4
nodemon: 1.17.3
command: C:\Program Files (x86)\Nodist\v-x64\8.9.4\node.exe D:\git\myapp\node_modules\nodemon\bin\nodemon.js index.js --inspect --dump --exec babel-node
cwd: D:\git\myapp
OS: win32 x64
--------------
{ run: false,
  system: { cwd: 'D:\\git\\myapp' },
  required: false,
  dirs:
   [ 'D:\\git\\myapp\\index.js',
     'D:\\git\\myapp\\tools\\webpack',
     'D:\\git\\myapp\\src\\server.js',
     'D:\\git\\myapp\\src\\utils\\Html.js' ],
  timeout: 1000,
  options:
   { dump: true,
     exec: 'babel-node',
     delay: '2500',
     watch:
      [ 'index.js',
        'tools/webpack/',
        '!tools/webpack/webpack.server.babel.js',
        'src/server.js',
        'src/utils/Html.js',
        re: /index\.js|tools\/webpack\/|!tools\/webpack\/webpack\.server\.babel\.js|src\/server\.js|src\/utils\/Html\.js/ ],
     ignore:
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**',
        re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/ ],
     ignoreRoot:
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     signal: 'SIGUSR2',
     stdout: true,
     watchOptions: {},
     execOptions:
      { script: 'index.js',
        exec: 'babel-node',
        args: [ '--inspect' ],
        scriptPosition: 0,
        nodeArgs: undefined,
        execArgs: [],
        ext: 'js,mjs,json',
        env: {} },
     monitor:
      [ 'index.js',
        'D:\\git\\myapp\\tools\\webpack/**/*',
        '!tools/webpack/webpack.server.babel.js',
        'src/server.js',
        'src/utils/Html.js',
        '!**/.git/**',
        '!**/.nyc_output/**',
        '!**/.sass-cache/**',
        '!**/bower_components/**',
        '!**/coverage/**',
        '!**/node_modules/**' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [ 'D:\\git\\myapp\\nodemon.json' ],
  watchInterval: null,
  signal: 'SIGUSR2',
  command:
   { raw: { executable: 'babel-node', args: [ 'index.js', '--inspect' ] },
     string: 'babel-node index.js --inspect' } }
--------------
```

**Comment by mrchief** [comment]
Dummy reply to keep this active

**Comment by baileyandy** [comment]
I am seeing this issue too.

`nodemon -v`: 1.17.4
`node -v`: 10.1.0
Operating system/terminal environment: OSX 10.13.x
Command you ran: `DEBUG=nodemon nodemon server/index.js`
`nodemon.json` contents:
```
{
  "verbose": true,
  "watch": [
    "assets/",
    "server/",
    "app.js"
  ]
}
```

I am only specifically watching 2 directories and 1 file in the root of the project directory but nodemon is watching the entire project directory still. This only occurs when I add the file; watching 2 directories is working as expected.

After some digging, I found the code is [specifically removing](https://github.com/remy/nodemon/blob/master/lib/monitor/watch.js#L55) the file part. The comment suggests it is because of Windows but on OSX this causes the project directory to be watched.

I agree that #1259 and #1260 are the cause and specifically 1cda8fae4333f3e37c54d0923d99b9132fb6a010. Reverting to `1.15.0` has solved this for me.

**Comment by kurtmilam** [comment]
Similar (perhaps identical) behavior started occurring recently for me, as well. This is new behavior (started within the past couple of weeks).

## Issues
1. `nodemon` is restarting my node application arbitrarily, at an estimated average rate of once per 30 seconds, even when no files in the watched directory have been changed. It reports triggering files, but those files have not been changed.
2. `nodemon` seems to disregard the `ignore` settings in my config file, as it reports files under ignored directories as the triggers for restarts, even when those files have not been changed by any process.

To clarify, `nodemon` reports trigger files under ignored and watched directories, even when those files have not been changed by any process.

## Environment
WSL on Windows 10 Pro 64bit

`nodemon -v`: 1.17.3
I have also tried with versions 1.15.0 and 1.17.4 . 1.17.4 seems best-behaved but is still restarting arbitrarily, reporting triggering files that have not changed. It seems to respect the `ignore` settings in my config file, which is an improvement.
`node` -v: 8.11.1

`nodemon.json`:
```javascript
{
  "verbose": true,
  "ignore": [
    ".idea/*",
    "migrations/*",
    "fixtures/*"
  ]
}
```

**Comment by remy** [comment]
@kurtmilam can you share the output of `--dump` and include the log of the restart? Maybe even with `DEBUG=nodemon*` as an env value which would give me more to debug with.

**Comment by kurtmilam** [comment]
@remy I added the dump info to my [original comment ^^](https://github.com/remy/nodemon/issues/1320#issuecomment-388338609)

Thanks for taking a look!

**Comment by keijoko** [comment]
Same is happening for me. Nodemon triggers restarts arbitrarily on files that have not changed and seems not to respect --ignore from command line. 
WSL (Ubuntu) on Windows 10 Pro 64bit
node -v: 8.11.1
nodemon -v: 1.17.3

Same setup used to work fine and it started a week ago, around the same time Windows and WSL update was released (running Version 10.0.17134 Build 17134).

**Comment by lpgera** [comment]
I am having a similar issue, with restarts triggering by unchanged files.
OS: Windows 10 64bit
node: 8.11.2
nodemon: 1.17.4

I could narrow down the problem by running a `chokidar.watch(...)` in parallel with nodemon, and chokidar also reports changes to the same files, but the only thing changing in their stats is the access time:

```
Stats {
 dev: 841653718,
 mode: 33206,
 nlink: 1,
 uid: 0,
 gid: 0,
 rdev: 0,
 blksize: undefined,
 ino: 281474976810702,
 size: 18028,
 blocks: undefined,
 atimeMs: 1527068199042.346,
 mtimeMs: 1487846793076.423,
 ctimeMs: 1487846793076.423,
 birthtimeMs: 1487846793074.4097,
 atime: 2018-05-23T09:36:39.042Z,
 mtime: 2017-02-23T10:46:33.076Z,
 ctime: 2017-02-23T10:46:33.076Z,
 birthtime: 2017-02-23T10:46:33.074Z }
```

**Comment by LuckStock** [comment]
Having similar issue recently: https://github.com/remy/nodemon/issues/1354
Earlier, hadn't experienced this weird issue.
Running in legacy mode (with -L) helped, but it needs a native fix.
OS: Windows 10 64bit,
nodemon: 1.17.5
node: 8.11.2

Tried to revert to 1.11., seems working yet, but who knows, can't find the regularity of the issue.

**Comment by baileyandy** [comment]
There are instructions on how to reproduce this in my earlier comment. I am seeing too many files being watched on the latest version (1.17.5)

**Comment by baileyandy** [comment]
Still seems to be an issue

**Comment by hadikcz** [comment]
Win 10 64bit
nodemon 1.11.0
node v9.3.0

still not fixed.. its anoying

**Comment by remy** [comment]
I'm not a regular windows user, so if you're finding this issue annoying, I'd strongly encourage you to help via a pull request that either fixes, or helps others to debug.

**Comment by remy** [comment]
I have looked at that comment, and I also know that the line was added to fix another bug.

That line does indeed to tell chokidar to watch the directory, but the actual triggering isn't dealt with in that code, it fires a change and then it filters through the `match` code. Only if that passes does it actually restart.

But I'd love it if I actually had a PR that gave me a test and the fix (because if I reverse that change, it'll cause a regression).

**Comment by mrchief** [comment]
This is great!! Thanks for the quickfix!

**Comment by baileyandy** [comment]
Thanks for fixing this. 1.18.0 is behaving exactly as expected! 👍

**Comment by webextensions** [comment]
@remy Thanks for the fix :-)
