### ISSUE TITLE
rs not working, when app crashed

### ISSUE THREAD

**Issue by darky** [remy/nodemon#1322]
- `nodemon -v`: 1.17.1
- `node -v`: 9.11.1
- Operating system/terminal environment: Arch linux

### Expected behaviour
type `rs` in stdin should restart application, even if app crashed.
Very inconvinience to change file for this purpose

### Actual behaviour
`rs`not working, when app crashed

### Steps to reproduce
Simply run via nodemon app, which will be crashed, and try to restart it via typing `rs` to stdin

**Comment by remy** [comment]
After testing, it looks to be a bug with node 9 and nodemon.

**Comment by remy** [comment]
For reference, test case is here: https://github.com/remy/nodemon-test-cases/tree/master/1322 (comment will also remove stale tag)

**Comment by remy** [comment]
I must get stalebot to ignore bugs.

**Comment by darky** [comment]
Hey! Stale bot so tricky here.
Need to reopen it, and mark stale bot to ignore some issues by tag or another way.

**Comment by stevefan1999** [comment]
Was also forseeing the same problem, but I'm using Windows.
