### ISSUE TITLE
nodemon under Node v6.1.0 isn't printing stderr

### ISSUE THREAD

**Issue by drhayes** [remy/nodemon#1323]
- `nodemon -v`: 1.17.3
- `node -v`: v6.1.0
- Operating system/terminal environment: OSX 10.13.4 in iTerm2 running bash
- Command you ran:

I ran `npm run dev`. `nodemon` is installed as a `devDependency`. My `dev` script is `. etc/local.env && nodemon` in `package.json`.

We're constrained to this node version because we're using AWS lambda.

### Expected behaviour

If there is a stacktrace or a `console.error` statement in my code I should see it on the terminal after `nodemon` starts my app.

I expected to see this on the terminal:

```
[~/src/nodemon-stderr-bug (master)] ➔  npm run dev

> nodemon-stderr-bug@1.0.0 dev /Users/drhayes/src/nodemon-stderr-bug
> nodemon

[nodemon] 1.17.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
catpants
[nodemon] clean exit - waiting for changes before restart
^C
```

### Actual behaviour

I don't see any `console.error` output or stacktraces when my app crashes.

When using my test repo, here's the terminal output:
```
[~/src/nodemon-stderr-bug (master)] ➔  npm run dev

> nodemon-stderr-bug@1.0.0 dev /Users/drhayes/src/nodemon-stderr-bug
> nodemon

[nodemon] 1.17.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
[nodemon] clean exit - waiting for changes before restart
^C
```

### Steps to reproduce

Here's a repo: https://github.com/drhayes/nodemon-stderr-bug

I *think* it has something to do with using node v6.1.0 via nvm; I don't see this bug under v8.5.0.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

```
[~/src/nodemon-stderr-bug (master)] ➔  node_modules/.bin/nodemon --dump
[nodemon] 1.17.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
--------------
node: v6.1.0
nodemon: 1.17.3
command: /Users/drhayes/.nvm/versions/node/v6.1.0/bin/node /Users/drhayes/src/nodemon-stderr-bug/node_modules/.bin/nodemon --dump
cwd: /Users/drhayes/src/nodemon-stderr-bug
OS: darwin x64
--------------
{ run: false,
  system: { cwd: '/Users/drhayes/src/nodemon-stderr-bug' },
  required: false,
  dirs: [ '/Users/drhayes/src/nodemon-stderr-bug' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**',
        re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot:
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     signal: 'SIGUSR2',
     stdout: true,
     watchOptions: {},
     execArgs: [],
     execOptions:
      { script: 'index.js',
        exec: 'node',
        args: [],
        scriptPosition: null,
        nodeArgs: undefined,
        execArgs: [],
        ext: 'js,mjs,json',
        env: {} },
     monitor:
      [ '*.*',
        '!**/.git/**',
        '!**/.nyc_output/**',
        '!**/.sass-cache/**',
        '!**/bower_components/**',
        '!**/coverage/**',
        '!**/node_modules/**' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  signal: 'SIGUSR2',
  command:
   { raw: { executable: 'node', args: [ 'index.js' ] },
     string: 'node index.js' } }
--------------
```

**Comment by remy** [comment]
I can replicate, but node 6.1.0 isn't the Lambda supported version, node 6.10.3 is, which does work:

<img width="759" alt="screen shot 2018-04-30 at 16 17 05" src="https://user-images.githubusercontent.com/13700/39434959-067332a4-4c92-11e8-96ed-d3df1fca4a09.png">

/ref [AWS docs](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html)

<img width="1280" alt="screen shot 2018-04-30 at 16 18 05" src="https://user-images.githubusercontent.com/13700/39435000-22bbe24e-4c92-11e8-986e-2b2b21168bad.png">

Going to close as I believe it's all good.

**Comment by drhayes** [comment]
Ah, well-spotted! You likely saved us from other bugs down the road, too. Thanks Remy!
