### ISSUE TITLE
Windows 10 hanging when restart

### ISSUE THREAD

**Issue by wstaeblein** [remy/nodemon#1329]
- `nodemon -v`: 1.14.11
- `node -v`: 9.8.0
- Operating system/terminal environment:  Windows 10 cmd
- Command you ran: nodemon

### Expected behaviour
Start the node app from package.json's main field

### Actual behaviour
App started ok but nodemon is unable to restart it. It shows no error msgs, just hangs there.

### Steps to reproduce
npm init on a folder
Create index.js with the code from this page:
https://blog.risingstack.com/your-first-node-js-http-server/

---

I use nodemon for some 2 or 3 years now in all my projects. It's been a little while since it stopped working for me. I tried many things, read many articles, posts and issues and nothing worked. From any of my websites and apps to the simple code above, all show the same behavior. Below is the output from the code above when started with nodemon:
```
H:\tests\nodemontest>nodemon
[nodemon] 1.14.11
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
server is listening on 3000
[nodemon] restarting due to changes...
```
The last line appears when a change is made to a file (in this case index.js). But the change is not reflected in the browser when it is refreshed. Also, when I close the terminal window nodemon appears to restart the app just before the close takes place. I tried all this with the latest nodemon, then downgraded to 1.17.11 and then further to at 1.14.11 and they all do the same.

Any advice?

**Comment by remy** [comment]
Can you report back with the following:

- `nodemon --verbose`
- Try also with node@8 rather than 9 (just to rule it out).

**Comment by wstaeblein** [comment]
The output below is from the same basic webserver I posted before, this time with the verbose flag and still on Node 9.8.0.

````
H:\Tests\nodemontest>nodemon --verbose index.js
[nodemon] 1.14.11
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 7248 to restart
[nodemon] watching: *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js`
[nodemon] forking
[nodemon] child pid: 15052
[nodemon] watching 3 files
[nodemon] files triggering change check: Index.js
[nodemon] matched rule: **\*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] Index.js

server is listening on 3000
[nodemon] files triggering change check: Index.js
[nodemon] matched rule: **\*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] Index.js

[nodemon] files triggering change check: Index.js
[nodemon] matched rule: **\*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] Index.js

/
/favicon.ico
[nodemon] files triggering change check: Index.js
[nodemon] matched rule: **\*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] Index.js
````
I changed the index.js file a few times (so that it would show up on the browser) and, although nodemon reacted it was not able to restart the application and the browser output remained the same.

Below is the same thing but with Node 8.1.1:

```
H:\Tests\nodemontest>nodemon --verbose index.js
[nodemon] 1.14.11
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 8084 to restart
[nodemon] watching: *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js`
[nodemon] forking
[nodemon] child pid: 9028
[nodemon] watching 3 files
server is listening on 3000
/
/favicon.ico
/
/favicon.ico
[nodemon] files triggering change check: Index.js
[nodemon] matched rule: **\*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] Index.js

/
/favicon.ico
```

**Comment by remy** [comment]
Can you try with `nodemon --signal SIGTERM index.js` and report back?

**Comment by remy** [comment]
So that time around it didn't even detect that you changed any files?

**Comment by wstaeblein** [comment]
Yes.

**Comment by remy** [comment]
I don't see why it wouldn't. The only change you made was to the way that the child process would be shutdown. I'd expect to have seen _at least_ the same result.

Can you debug further and let me know how you get on.

**Comment by remy** [comment]
I've also published `nodemon@debug` (version: 1.17.5-alpha.2) which includes more debugging output for Windows. If you can try it with the `set DEBUG=nodemon*` in the cmd.exe prompt, then run nodemon, it should give some error details if the kill process is failing.

**Comment by remy** [comment]
This is [another](https://superuser.com/a/1299350) method to kill in windows (if the other methods linked don't work).

**Comment by wstaeblein** [comment]
It may be a permission issue. It seems to me that this taskkill program can only be run as administrator. In my case I run a batch file that, among other things, calls nodemon with the node app to run. That is a normal command window and nodemon is not able to kill the node process . If I run it as an administrator (elevated command window) then it works. I also tried running taskkill alone from a standard command window and then from an elevated command window. Only the latter worked.

One workaround (in my case) is to right-click the batch shortcut, choose Properties from the menu, then click Advanced and check Run as Administrator.

The best solution would be for nodemon be able to kill the node process from a standard command window.

**Comment by remy** [comment]
@wstaeblein is it possible that your process that you're running (not nodemon) is running as admin? Typically admin isn't required to run `taskkill`, so I'm suspecting something bespoke to your setup…

**Comment by AyoubEd** [comment]
Hello, I am experiencing the same problem on windows 10, when I run nodemon the changes get detected but the server does not restart it just stays hanging.

This is a simple run, i did only one file "server.js", the output to _nodemon --verbose_ : 
`[nodemon] 1.17.4`
`[nodemon] to restart at any time, enter rs`
`[nodemon] or send SIGHUP to 8624 to restart`
`[nodemon] watching: *.*`
`[nodemon] watching extensions: js,mjs,json`
`[nodemon] starting node server.js`
`[nodemon] forking`
`[nodemon] child pid: 8332`
`[nodemon] watching 3 files`
`listening on port 3000`
`[nodemon] files triggering change check: server.js`
`[nodemon] matched rule: **\*.*`
`[nodemon] changes after filters (before/after): 1/1`
`[nodemon] restarting due to changes...`
`[nodemon] Server.js`

**Comment by RichardRosario** [comment]
I have had the same issue with Window 10.. has this issue been resolved? can you guys please share your solution? I really need this thing to work..

thanks a ton!

**Comment by AyoubEd** [comment]
I'm still having the issue sill Richard.

**Comment by RichardRosario** [comment]
Man. i have been scouring the net for solution to this.. and i got nothing yet.. I hope Remy can resolve this.. or the other masters around here.

**Comment by RichardRosario** [comment]
by the way.. can you share your package.json content.. just want to compare with mine regarding running the scripts..
