### ISSUE TITLE
nodemonConfig- ignore not working

### ISSUE THREAD

**Issue by MohammedBakri** [remy/nodemon#1336]
version @1.17.4 - ignoring files in nodemonConfig not working in both package.json or nodemon.json

**Comment by remy** [comment]
Not much to test from, but I can confirm:

```
❯ tre
      1 .
      2 ├── .vscode
      3 │   └── settings.json
      4 ├── foo
      5 │   └── index.js
      6 ├── index.js
      7 ├── nodemon.json
      8 └── package.json
```

```
❯ DEBUG=nodemon* nodemon -i foo
  ####### ✂ snip ✂ ######
  '**/.nyc_output/**',
  '**/.sass-cache/**',
  '**/bower_components/**',
  '**/coverage/**',
  '**/node_modules/**',
  'foo',
  re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*|foo/ ] +0ms
  nodemon:watch watching dir: /Users/remy/Sites/nodemon/issues/1336/index.js +0ms
  nodemon:watch watching dir: /Users/remy/Sites/nodemon/issues/1336/nodemon.json +0ms
  nodemon:watch watching dir: /Users/remy/Sites/nodemon/issues/1336/package.json +0ms
  nodemon:watch watching dir: /Users/remy/Sites/nodemon/issues/1336/foo/index.js +1ms
  nodemon watch is complete +76ms
```

Using `-i '**/foo/*'` is a work around until I release a fix.

The issue is [this change](https://github.com/remy/nodemon/commit/97f8d0a1750003b5bc9a6fe7c676b1d996b13c88#diff-b2048f4188632273753b02bbcc2e31deL64) which keeps fixing some problems and breaking others…

**Comment by remy** [comment]
Just to follow up from my testing - the directory isn't ignored during the watch, but it is ignored when it comes to triggering restart. @MohammedBakri is that your experience too?

**Comment by remy** [comment]
I've got a PR ready, but can you also test with the debug version I released.

You can install using `nodemon@debug` - you should get `nodemon@1.17.5-alpha.1`.

**Comment by MohammedBakri** [comment]
issue fixed with debug version -  nodemon@1.17.5-alpha.1 
Now Ignore specific files like package.json working fine. thanks a lot

**Comment by remy** [comment]
When I'm back home, I'll fix the current failing tests and merge to release.

**Comment by MohammedBakri** [comment]
thanks for your interest.
