### ISSUE TITLE
Security vulnerabilities in nodemon

### ISSUE THREAD

**Issue by ar-to** [remy/nodemon#1339]
- `nodemon -v`: 1.17.4
- `node -v`:  9.11.1
- Operating system/terminal environment: OSX High Sierra
- Command you ran: npm audit

### Expected behaviour
Should not have security vulnerabilities.

### Actual behaviour
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ Prototype Pollution                                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ deep-extend                              
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nodemon [dev]                              
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nodemon > chokidar > fsevents > node-pre-gyp > rc >          │
│               │ deep-extend                              
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/612                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

```

### Steps to reproduce

`npm install nodemon@1.17.4 --save-dev`

---

**Comment by remy** [comment]
Can you include where else you've filed this issue?

**Comment by remy** [comment]
The problem (why I have to do this leg work and npm's security doesn't do this… I don't know), but the problem is with [fsevents](https://github.com/strongloop/fsevents). It bundled node-pre-gyp@0.9.1 - http://registry.npmjs.org/fsevents/latest - please file your issue there.

Closing as once you issue is fixed on fsevents, nodemon will automatically inherit the fix.

**Comment by remy** [comment]
You can track progress here https://github.com/strongloop/fsevents/pull/219

**Comment by ar-to** [comment]
@remy Only filed an issue here. Thanks !!
