### ISSUE TITLE
Fails to pass npm v6 audit test

### ISSUE THREAD

**Issue by Triforcey** [remy/nodemon#1340]
- `nodemon -v`: 1.17.4
- `node -v`: 10.0.0
- Operating system/terminal environment: Mac OSX
- Command you ran: npm install

### Expected behavior
Should install without any audit warnings from npm.

### Actual behavior
Raises an audit warning from npm.

### Steps to reproduce
Make sure you're on npm 6.
Install nodemon as a non-global dependency with `--save`.
Run `npm audit`.

### Probable fix:
Update nodemon's dependencies. Specifically the offending package: deep-extend

**Comment by remy** [comment]
Dupe of #1339. Please read my closing comment to understand how to fix.

**Comment by remy** [comment]
You can track progress here: https://github.com/strongloop/fsevents/pull/219
