### ISSUE TITLE
reload when sass changes

### ISSUE THREAD

**Issue by o-t-w** [remy/nodemon#1345]
I am using NPM scripts as a build tool for Sass. 
```
"scripts": { 
"sass": "node-sass --output-style compressed -o public/css src/sass/style.scss"
```

Is it possible for nodemon to watch sass files and run the sass command when sass files are saved?

**Comment by remy** [comment]
Yes. See the help, and `nodemon --help options`. Something like `nodemon -x "node-sass --output-style compressed -o public/css" -e scss -w src/sass/`
