### ISSUE TITLE
Upgrade Chokidar

### ISSUE THREAD

**Issue by natewaite** [remy/nodemon#1347]
Upgrade chokidar to newest version. 2.0.3 or above
### Expected behaviour
https://nodesecurity.io/advisories/566
https://nodesecurity.io/advisories/534
 https://nodesecurity.io/advisories/606
 https://nodesecurity.io/advisories/525
https://nodesecurity.io/advisories/612
### Steps to reproduce
npm audit

**Comment by remy** [comment]
You are kidding me right?

`npm i nodemon` pulls the latest `fsevents` - which is part of the chokidar@^2.0.2.
