### ISSUE TITLE
dynamic import is not supporting by nodemon

### ISSUE THREAD

**Issue by rizwan92** [remy/nodemon#1352]
having issue with dynamic import in nodemon with babel-node
here is my package.json file
[my package.json](https://gist.github.com/rizwan92/8041b8c1831c22bb7064fefe0f2bbab2
)
- `nodemon -1.17.2`:
- `node -v8.11.2`:
- Operating system/terminal environment: 
- Command you ran:
     nodemon --exec babel-node server/server.js --ignore public/

### Actual behaviour:- but throwing an error that is Unexpected token import
here is problem :- 
![screenshot from 2018-05-23 17-59-44](https://user-images.githubusercontent.com/19162978/40431667-7f82203e-5ec5-11e8-8a92-3adefae40172.png)

i ran my server/server.js file with command babel server/server.js 
it is working fine
pic:- 
![screenshot from 2018-05-23 18-08-04](https://user-images.githubusercontent.com/19162978/40431684-8da5a0a0-5ec5-11e8-9a42-4963c3bcd678.png)

**Comment by rizwan92** [comment]
hello sir,
i  have created very small and super minimal project that uses dynamic
imports in gihub., you can run and checkout the issue i am getting here.

link is :- https://github.com/rizwan92/dynamic-import

run project with two commands:-
npm run webpack
npm start

localhost://8000

**Comment by rizwan92** [comment]
i solved this issue 
reference link :- [checkout this issue](https://github.com/babel/babel/issues/8013)

**Comment by remy** [comment]
Sorry for the slow follow up - but to clarify - have you solved the problem? If so, I can go ahead and close the issue.
