### ISSUE TITLE
Relative files with leading `./` are not watched

### ISSUE THREAD

**Issue by OliverJAsh** [remy/nodemon#1355]
- `nodemon -v`: 1.8.1
- `node -v`: 9.8.0
- Operating system/terminal environment: macOS
- Command you ran: `nodemon --watch ./foo/bar.js --exec 'echo foo'`

### Expected behaviour

When editing `./foo/bar.js`, watch should trigger.

### Actual behaviour

When editing `./foo/bar.js`, watch does not trigger.

I have to remove the leading `./` from the path in order for this to work.

`nodemon --watch foo/bar.js --exec 'echo foo'`

However, nodemon should allow the leading `./`, as this is a valid path.

**Comment by remy** [comment]
Please update nodemon and retest.

**Comment by OliverJAsh** [comment]
Same issue with 1.17.5.

**Comment by AckerApple** [comment]
Hey thanks this issue led me to remove my opening ./

Now my commands are working... Using npm version ^1.17.5 on Mac

Hope it gets fixed for other casual users

**Comment by OliverJAsh** [comment]
This is still an issue.

**Comment by OliverJAsh** [comment]
This is still an issue. Is there any way to mark this issue as non-stale so the bot doesn't keep trying to close it?

**Comment by remy** [comment]
@OliverJAsh I'm not sure, but it's definitely a bit annoying - I guess the point is that conversation continues, and in an ideal world there's a PR that comes along…
