### ISSUE TITLE
nodemon stuck at restarting

### ISSUE THREAD

**Issue by TFKED** [remy/nodemon#1356]
- `nodemon -v`: 1.12.1 and 1.17.5 (I have tried nodemon@latest)
- `node -v`: 8.4.0
- `npm -v`: 5.0.3
- Operating system/terminal environment: Windows 10 using Node.js command prompt
- Command you ran: nodemon

### Expected behaviour

When I save my sever.js file, it should console.log('test') again and the port it is listening at.

### Actual behaviour

![image](https://user-images.githubusercontent.com/33427562/40712425-a072bb84-63f5-11e8-963b-284f0467845d.png)

### Steps to reproduce

Not sure how to reproduce it.

It is the exact same issue as: #813 

I know this isn't a lot of information, but I don't know much and I'm hoping by creating this it will highlight if I'm not the only one with this issue. If you need anything else from me, please let me know.

**Comment by remy** [comment]
First question: does it suddenly drop into a restart loop?

If so, can you include the output but run nodemon using the `--verbose` flag?

**Comment by AbdelrahmanHafez** [comment]
Hello, @remy I am somewhat active on GitHub, and have been facing the issue for quite a while now.
Let me know how I can help.

Yes, sometimes it suddenly drops into a restart loop, and when I used `--verbose` before, it restarted on every file being opened by Node `require(...)` function, I don't even open them in my text editor or anything.

Can't reproduce the bug now, using nodemon with `--verbose`, will post the results once it happens again.

**Comment by balciseri** [comment]
as https://github.com/remy/nodemon/issues/1354#issuecomment-392681579 
try to run `fsutil behavior set disablelastaccess 1` from an elevated shell.

did it fix it?

**Comment by AbdelrahmanHafez** [comment]
Gave it a try, as an initial result, the bug was fixed.

I'll post here if the issue happens again.

**Comment by TFKED** [comment]
Apologies for the late reply.

I deleted nodemon from my global installs and ran it locally and it seems to be working fine now. I could try and install it globally again and see if I get the same issue if you'd like. Will do it at a later time though as busy at the moment.

**Comment by TFKED** [comment]
Hi all, it's been a long time but I found a solution to my problem at last.

If I run nodemon locally, it works fine, it only does this when I run it globally.

I've tried uninstalling and reinstalling globally, but no luck. No idea why this is the case, but we can close now.

**Comment by awesomebanana123** [comment]
@TFKED how did you install nodemon locally? I used npm install nodemon without the g, but when I did, my terminal said that it doesn't recognize nodemon as a command.

**Comment by TFKED** [comment]
@awesomebanana123 it won't. You have to run it like this if running locally: ./node_modules/.bin/nodemon --watch server.js
