### ISSUE TITLE
Nodemon doesn't watch hidden files and dirs together

### ISSUE THREAD

**Issue by borekb** [remy/nodemon#1357]
- `nodemon -v`: 1.17.5
- `node -v`: v8.11.1
- Operating system/terminal environment: Windows 10, Git Bash
- Command you ran: `nodemon -w 'src/.env' -w 'src' --exec ts-node -- src/server.ts`

I'm trying to make nodemon watch my TypeScript sources as usual and also a `src/.env` file. (Note: this is not about nodemon adding support for .env, I just want to restart the server when the file changes.)

This works:

```
nodemon -w 'src/.env' --exec ts-node -- src/server.ts
```

but then my TypeScript files are not watched.

This works for TypeScript files:

```
nodemon -w 'src' --exec ts-node -- src/server.ts
```

(I could also omit the `-w` entirely in which case nodemon reports `[nodemon] watching: *.*`, but it works).

But if I combine the two, .env changes aren't watched:

```
nodemon -w 'src/.env' -w 'src' --exec ts-node -- src/server.ts
```

Slightly suspicious is this line:

```
[nodemon] watching: src/.env C:\Dev\myproject\src/**/*
```

as it uses different slashes. Or maybe I'm using the CLI incorrectly?

**Comment by remy** [comment]
I'm pretty sure this is a combination of watching the directory _and_ watching a hidden file in the same directory that's doing it. Also, IIRC, the `watching…` text might be visual sugar (in that the actual file paths are fully resolved using the OS slashes).

**Comment by augustosamame** [comment]
I am also having the same issue. Watching the hidden .env file along with changes to regular files in the  same directory results in unpredictable behavior (will watch one or the other).

In my case I'm setting the values through the nodemon.json config file:

For example, this works

```
{
  "ignore": ["test/*", "docs/*"],
  "watch": [".env", "server.js", "app/*.*"],
  "ext": "js,json,html"
}
```

but this:

```
{
  "ignore": ["test/*", "docs/*"],
  "watch": [".env", "*.js", "app/*.*"],
  "ext": "js,json,html"
}

```

will stop watching changes to server.js file.
