### ISSUE TITLE
Restart using scripts rather than main

### ISSUE THREAD

**Issue by Elrendio** [remy/nodemon#1359]
- `nodemon -v`: 1.17.2
- `node -v`:v9.8.0
- Operating system/terminal environment: macOS 10.13.3, Iterm2 3.1.5, zsh
- Command you ran: nodemon

### Expected behaviour
I'd like it possible to configure using scripts to relaunch my server rather than having to write it each time in command line. Right now I have to run ```nodemon --exec "npm run start"```. 

### Actual behaviour
Launches ```node ./package.json#main```

**Comment by remy** [comment]
The way do this is:

```json
{
  "main": "./foo/index.js",
  "scripts": {
    "dev": "nodemon --exec 'npm start'",
    "start": "..."
  }
}
