### ISSUE TITLE
nodemon auto restart without any changes in app.js file

### ISSUE THREAD

**Issue by gogoIsComing** [remy/nodemon#1360]
- `nodemon -1.17.3`:
- `node -8.9.4`:
- Operating system/terminal environment: win10
- Command you ran: `nodemon app.js`

i am using nodemon and every thing is fine , but when i write some code ( to read and write JSON files in my computer ) , nodemon start auto restarting without any changes in app.js 

Any Help :)

app.js 

![code](https://user-images.githubusercontent.com/33967218/40987468-433594c2-68f1-11e8-8289-984bb224a805.png)

![untitled](https://user-images.githubusercontent.com/33967218/40987504-5a4e460e-68f1-11e8-841f-02e8e3fc33bb.png)

**Comment by remy** [comment]
This looks like a dupe of an existing issue - can you search the open issues.

Also, not sure who you're referring to with "hey guys"…

**Comment by remy** [comment]
Dupe of #1354
