### ISSUE TITLE
Feature request, bash scripts with no extension

### ISSUE THREAD

**Issue by babakness** [remy/nodemon#1361]
Hello,

It would be great if it were possible to add files without an extension to the list of files that are watch if changed. Currently doing this:

`nodemon -e 'yaml,' --exec "path/to/executable"`

This project involves kicking off a bash script that reads data from a `yaml` file then does something. Each time the yaml file changes, the script should re-run; however, each time the bash script itself is modified, it should also re-run.

The current work around is to either
1. Give the bash script an extension
2. Add the bash script as a watch parameter; unfortunately this won't watch other directories and globs aren't utilized (from my understanding).
3. Concurrently run two instances of `nodemon`, with one dedicated to just the file without an extension.

One of two features that would be great is an additive watch parameter (thereby adding just that no-extension file) or ability to add no-extension scripts.

**Comment by remy** [comment]
I'm not quite sure how to go about solving this. I wonder if `yaml,*` is at least a little more explicit, but then I don't want `*` matching all extensions, only those files _without_ a period in them… which is kinda confusing.

Is there any other prior art that solves this that nodemon could use as inspiration?

**Comment by babakness** [comment]
In *nix the `find` command can use regular expression and find files without an extension like so

```bash
find . -type f  ! -name "*.?*"
```

Admittedly, this is difficult to implement, however, leveraging the unix philosophy, perhaps `nodemon` can receive a list of files via pipe.

 ```bash
find . -type f  \( ! -name "*.?*" -o -iname "*.yaml" \) | nodemon --exec 'a/b/c' --read-from-pipe
```

allowing for complex scenarios to be offloaded and leverage, and become part of, the power of the platform.

**Comment by babakness** [comment]
@remy hey!

**Comment by remy** [comment]
Okay, there's no sensible way to do this through the `--ext` option, but I do have a solution/workaround:

```bash
$ ls
foo   foo.sh   bar
$ nodemon -x ./foo -w foo -w bar
# will ignore changes to foo.sh
```

Piping the files to nodemon isn't entirely worthwhile, since it can't then handle new files or regexp for directories, and then adds confusion as to what takes priority (along with adding more options, which we don't want).

Not perfect, but certainly a work around.
