### ISSUE TITLE
Add a command to stop nodemon

### ISSUE THREAD

**Issue by Ronanb3** [remy/nodemon#1366]
Hi, I didn't find a command to stop nodemon.
A bit like rs force a restart, a command to stop nicely nodemon owuld be great;

**Comment by remy** [comment]
ctrl+c

**Comment by joeytwiddle** [comment]
You could also do it the shell way:

```sh
# Start nodemon in the background
nodemon ... &

# Get the PID that nodemon ran with
nodemon_pid="$!"

# Later, stop the process
kill "${nodemon_pid}"
```

**Comment by Ronanb3** [comment]
Thanks for the reply, I am already doing it through CTRL+C.
In my point of view, having a stop command would be cleaner. 
Just my 2 cents.
