### ISSUE TITLE
rs command isn't restarting nodemon, need to full stop and restart

### ISSUE THREAD

**Issue by KyleWMiller** [remy/nodemon#1371]
- `nodemon -v`: 1.17.5
- `node -v`: 10.4.1
- Operating system/terminal environment: CentOS / ssh'd terminal
- Command you ran: rs (while program is running)

### Expected behaviour

To restart the server

### Actual behavior

Nothing

### Steps to reproduce

I'm running a backend server, and while running tests from the frontend sometimes they are crashing my backend server. Trying to use rs to restart the app vs. using Ctl-c + up arrow enter. I'm running an ExpressJS app, and the command that is erroring is using PythonShell. I don't know if the error being passed from python3.6 to JS is whats causing the issue or not. I'm handling the python error through a `throw err` in the JS file. 

Just updated all packages and tried again the same result. 

BTW Thanks for this awesome daemon! This is my go-to tool for all deving
![screen shot 2018-06-25 at 9 44 07 am](https://user-images.githubusercontent.com/16582136/41857698-1b3eaf10-7866-11e8-83ca-b7cc0b7a6fc9.png)

**Comment by remy** [comment]
Can you provide example code to replicate with? This isn't normal behaviour so I'm suspecting something in the setup that I'd need to be able to debug properly.

**Comment by jefflung** [comment]
I got this crashed warning also and below message when I used --quite option, console 
'clear' is not recognized as an internal or external command, operable program or batch file
node: bad option: --quite
[nodemon] app crashed - waiting for file changes before starting...

**Comment by remy** [comment]
Idle and no info. Closing.
