### ISSUE TITLE
Running multiple instances of nodemon in requireable mode

### ISSUE THREAD

**Issue by mochini** [remy/nodemon#1373]
Thank you so much for developing this powerful software - it is exactly what my team is looking for on our project!

My question is - and I have searched the documentation as well as read through the code - is how do I run multiple instances of nodemon in the requirable mode. My code looks like this:

```
import nodemon from 'nodemon'
import path from 'path'

const serverWatch = (entity, watch, script) => {

  nodemon({
    watch: path.join('src', 'app', watch),
    script: path.join('src', 'app', script),
    exec: 'babel-node',
    ext: 'js'
  }).on('start', () => {
    console.log(`${entity} has started`);
  }).on('quit', () => {
    console.log(`${entity} has quit`)
    process.exit();
  }).on('restart', (files) => {
    console.log(`${entity} restarted due to: ${files}`)
  })

}

serverWatch('server', path.join('admin','api'), 'server.js')
serverWatch('websocket', path.join('admin','api'), 'socket.js')
serverWatch('cron', path.join('cron'), 'cron.js')
serverWatch('worker', path.join('queues'), 'worker.js')
```

but when I run it at from command line, I see:

```
worker has started
worker has started
worker has started
worker has started
```

it appears to me as if only the final invocation of nodemon is being executed - ignoring the previous three calls.

**Comment by remy** [comment]
nodemon is actually a singleton, and it runs state across the imported library (using a singleton event bus), so, although I'm not 100% of your code, it does sound like nodemon is behaving as I'd expect - and not give you the functionality you're after. Sorry.

**Comment by mochini** [comment]
@remy, final question. I totally understand that nodemon is a singleton and your reasons for responding as you did. Is there a way to have an array or object in the configuration, such that you can have multiple families of watched directories? It would be awesome to have something like:

```
nodemon([
  {
    watch: path.join('src', 'app', 'server'),
    script: path.join('src', 'app', 'server.js'),
    exec: 'babel-node',
    ext: 'js'
  }, {
    watch: path.join('src', 'app', 'cron'),
    script: path.join('src', 'app', 'cron.js'),
    exec: 'babel-node',
    ext: 'js'
  }, {
    watch: path.join('src', 'app', 'queues'),
    script: path.join('src', 'app', 'worker.js'),
    exec: 'babel-node',
    ext: 'js'
  }
]).on('start', () => {
    console.log('server has started');
  }).on('quit', () => {
    console.log('server has quit`)
    process.exit();
  }).on('restart', (files) => {
    console.log('server restarted due to: ${files}`)
  })
```

**Comment by mochini** [comment]
@remy, I read through your documentation more carefully and it looks like this can be achieved through spawning child processes:

```
import { spawn } from 'child_process'
import path from 'path'

const serverWatch = (entity, watch, script) => {

  const proc = spawn('nodemon', [
    path.join('src', 'app', script),
    '--watch',
    path.join('src', 'app', watch),
    '--exec',
    'babel-node'
  ], {
    stdio: ['pipe', 'pipe', 'pipe', 'ipc']
  })

  proc.on('message', function (event) {
    if (event.type === 'start') {
      console.log(`${entity} has started`)
    } else if (event.type === 'crash') {
      console.log(`${entity} has crashed`)
    }
  })

  proc.on('error', function (e) {
    console.log(`${entity} has error ${e}`)
  })

  proc.on('exit', function () {
    console.log(`${entity} has quit`)
  })

}

serverWatch('server', path.join('admin','api'), 'server.js')
serverWatch('websocket', path.join('admin','api'), 'socket.js')
serverWatch('cron', path.join('cron'), 'cron.js')
serverWatch('worker', path.join('queues'), 'worker.js')
```

Now when I run my code, i see the following in my console:

```
sevrer has started
cron has started
worker has started
websocket has started
```

**Comment by dextermb** [comment]
@remy I've just come across this ticket and I'm attempting to do what @mochini was doing.

> Is there a way to have an array or object in the configuration, such that you can have multiple families of watched directories? It would be awesome

@mochini Do you remember how you worked around this issue? @remy Was this suggest ever implemented?
