### ISSUE TITLE
Nodemon restarts on save

### ISSUE THREAD

**Issue by Kishan08** [remy/nodemon#1376]
- `nodemon -v`: 1.17.5
- `node -v`: 10.5.0
- Operating system/terminal environment: Windows 10 (64 bit) / CMD
- Command you ran: nodemon ./server.js localhost 8080

### Expected behaviour
nodemon should restart only after files have been changed.

### Actual behaviour
nodemon restarts server when I save the file without any changes.

### Steps to reproduce
Open any file and save it without making any changes.

---

[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
--------------
node: v10.5.0
nodemon: 1.17.5
command: C:\Program Files\nodejs\node.exe C:\Users\UserName\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.js ./server.js localhost 8080 --dump
OS: win32 x64
--------------
{ run: false,
  system: { cwd: '' },
  required: false,
  dirs: [ '' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**',
        re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot:
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     signal: 'SIGUSR2',
     stdout: true,
     watchOptions: {},
     execOptions:
      { script: './server.js',
        exec: 'node',
        args: [ 'localhost', '8080' ],
        scriptPosition: 0,
        nodeArgs: undefined,
        execArgs: [],
        ext: 'js,mjs,json',
        env: {} },
     monitor:
      [ '*.*',
        '!**/.git/**',
        '!**/.nyc_output/**',
        '!**/.sass-cache/**',
        '!**/bower_components/**',
        '!**/coverage/**',
        '!**/node_modules/**' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  signal: 'SIGUSR2',
  command:
   { raw:
      { executable: 'node',
        args: [ './server.js', 'localhost', '8080' ] },
     string: 'node ./server.js localhost 8080' } }
--------------

**Comment by remy** [comment]
Dupe or #1354

**Comment by AbdelrahmanHafez** [comment]
I think this is a different issue. This has been the behavior for me since I started using nodemon, that I think this is the norm now.
`fsutil behavior set disablelastaccess 1` doesn't affect that behavior.
