### ISSUE TITLE
How can I get changed files in script?

### ISSUE THREAD

**Issue by kalinichenko88** [remy/nodemon#1383]
- `nodemon -v`: 1.17.5
- `node -v`: v10.6.0
- Operating system/terminal environment: Ubuntu 16.04
- Command you ran: node bin/dev.js

### Expected behaviour

1. run nodemon
2. change files
3. process on changed files
4. reload exec or script param

### Actual behaviour

No changed files.
Event `restart` not I need. Event triggired when restart on going, but not before this.

### Steps to reproduce

Now, my run script looks like this:

```javascript
nodemon({
	script: "bin/server.js",
	ext: "json",
	ignore: [".git", "node_modules/**/node_modules"],
	watch: watchPath
})
```

**Comment by remy** [comment]
When you say "event `restart` is not what you need…" that event tells you which files [triggered the restart](https://github.com/remy/nodemon/blob/master/doc/events.md#states)

I don't understand what it is you actually need if you don't need to changed file…

Can you clarify?

**Comment by kalinichenko88** [comment]
@remy process on restart event ended after reload nodemon

**Comment by kalinichenko88** [comment]
I tried this code

```javascript
nodemon({
	script: "bin/server.js",
	ext: "json",
	ignore: [".git", "node_modules/**/node_modules"],
	watch: watchPath
})
.on("restart", files => {
 /// process files
});
```

**Comment by kalinichenko88** [comment]
Thank for your help! I found little bug in my code. All work good. RTFM :-)
