### ISSUE TITLE
ctrl+c stops nodemon server but along errno 130 elifecycle error

### ISSUE THREAD

**Issue by maulberto3** [remy/nodemon#1390]
Hi. However, `ctrl+c` after `node server.js` does exit and stops gracefully (no errno 130 elifecycle). 
```
- node 8.9.4
- nodemon 1.18.1. 
```
Any solution?

**Comment by remy** [comment]
Please can you try with the current debug version: `npm install -g nodemon@debug` (1.18.2-alpha.1)

**Comment by remy** [comment]
Technically ctrl-c isn't a graceful exit, it's a SIGINT with an exit code
of 130 (it's just somehow the new way I was going it was confusing npm) -
you can validate this by checking ctrl-c on npm and `echo $?`

**Comment by sumAlbert** [comment]
I also meet this problem today. When I use nodemon in CLI, it's ok. However, I use npm script to run it, it doesn't work properly.

**Comment by Akallabet** [comment]
@remy it is 130 indeed :)
@sumAlbert `nodemon@debug` (1.18.2-alpha.1) fixes the problem also when running nodemon from npm script

**Comment by sumAlbert** [comment]
@Akallabet Maybe it is related to your project. I run two different projects with npm script. One is ok, the other is 130. nodemon@debug (1.18.2-alpha.1)

**Comment by Akallabet** [comment]
@sumAlbert definitely possible, btw I'm running with 
```
node@10.6.0
npm@6.1.0
```
Hope it helps

**Comment by DiegoRBaquero** [comment]
Having this issue in 1.18.3

**Comment by subatomicglue** [comment]
Me too, also in 1.18.3, downgraded back to 1.17.5 and ctrl-c exiting works again without LIFECYCLE 130 errors...

**Comment by artem-tolstykh** [comment]
I have this issue in 1.18.3 too!

**Comment by alexandersokolov** [comment]
Not sure if this is the best way to go about it but I got an easy solution for now. A workaround to suppress that error can be done by adding this to the main node file:

`process.on('SIGINT', () => {
  process.exit()
})`

This ensures that the program exists gracefully without the 130 error

**Comment by Adverbly** [comment]
Upgrading to 1.18.5 seems to have fixed this for me.

**Comment by VictorKolb** [comment]
Having this issue in 1.18.6

**Comment by kuzmicheff** [comment]
Updating to 1.18.7 has solved this issue for me.

**Comment by GeaGo** [comment]
Having this issue in 1.18.11

**Comment by MagnusFrater** [comment]
Also having this issue in 1.18.9

**Comment by MickL** [comment]
@remy Please reopen!

**Comment by jesusvallez** [comment]
1.18.10 :(

**Comment by lacek** [comment]
Still having the same issue on 1.19.0 ☹️

**Comment by bharathgrk** [comment]
1.19.1 ☹️

**Comment by meszaros-lajos-gyorgy** [comment]
It is not likely, that it will be fixed anytime soon: https://github.com/remy/nodemon/issues/1424#issuecomment-433826772

**Comment by remy** [comment]
Pretty amazed by the ratio of "still happening" to PRs on this particular issue! 😄

**Comment by meszaros-lajos-gyorgy** [comment]
Hi everyone!

I found a bug ticket on the node github page, which addresses a very similar - if not the same - issue and it was fixed a week ago:

https://github.com/nodejs/node/issues/21213

I have node `10.4.0` which I've updated it to `10.4.1` and seems like it solves the issue.
I know, that `10.4.x` is not the latest LTS, but it worked for me so far. I'll check the newer minors too to see, if it is working fine there.

**Comment by Tolga-FNT** [comment]
I also have this issue. Still not solved!

**Comment by meszaros-lajos-gyorgy** [comment]
> [nodemon] 1.19.1
> I also have this issue. Still not solved!

Check your node and npm versions and try updating them! There is a good chance, that it will solve the issue for you too.

**Comment by rishikesh67** [comment]
> Hi. However, `ctrl+c` after `node server.js` does exit and stops gracefully (no errno 130 elifecycle).
> 
> ```
> - node 8.9.4
> - nodemon 1.18.1. 
> ```
> 
> Any solution?

Thank you very much. It works.

**Comment by evantahler** [comment]
If you put some logging in, it looks like the `SIGINT` actually ends up at your program twice fairly rapidly:

```
^C2020-09-03T00:34:38.425Z - notice: [ SIGNAL ] - SIGINT
2020-09-03T00:34:38.426Z - notice: stopping process...
[nodemon] still waiting for 6 sub-processes to finish...
2020-09-03T00:34:38.668Z - notice: [ SIGNAL ] - SIGINT
npm ERR! code ELIFECYCLE
npm ERR! errno 130
npm ERR! @grouparoo/app-staging-public@0.1.12-alpha.0 dev: `cd node_modules/@grouparoo/core && GROUPAROO_MONOREPO_APP=staging-public ./api/bin/dev`
npm ERR! Exit status 130
npm ERR!
npm ERR! Failed at the @grouparoo/app-staging-public@0.1.12-alpha.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/evan/.npm/_logs/2020-09-03T00_34_38_811Z-debug.log
```

**Comment by borracciaBlu** [comment]
Hi @remy sorry to bother you on this again but on `/node_modules/nodemon/lib/monitor/run.js@465` we got:
```
// because windows borks when listening for the SIG* events
if (!utils.isWindows) {
  bus.once('boot', () => {
    // usual suspect: ctrl+c exit
    process.once('SIGINT', () => bus.emit('quit', 130)); <- SIGINT IS ctrl+c!!!!!
    process.once('SIGTERM', () => {
      bus.emit('quit', 143);
      if (child) { child.kill('SIGTERM'); }
    });
  })
}
```

so now my question is : why do we have `process.once('SIGINT', () => bus.emit('quit', 130));`? What's the reason for that
because that is the cause of the 130..

`!utils.isWindows` explains why it is not happening on windows.

If there is no good reason for throwing a `130` to a `SIGINT` let me know and i'll PR

Thanks.

**Comment by remy** [comment]
@borracciaBlu best to track the git blame on that line. The project is coming up on 10 years old and there's so many tiny changes for specific systems to make it all hang together I can't recall _why_ but I'm sure it's there on purpose. It's not the kind of copy you'd see in copy/paste mistake.

**Comment by abdouakhad** [comment]
npm install -g nodemon@debug

This one that Remy made, fixes the problem for me

**Comment by thiagoolsilva** [comment]
@abdouakhad thanks for your reply. After changing the nodemon version 2.0.7 to 2.0.14-alpha.1 the problem was fixed.
