### ISSUE TITLE
unable to launch localhost in browser automatically with nodemon

### ISSUE THREAD

**Issue by Villadshammershoi** [remy/nodemon#1391]
Hello everyone, first time posting here, so go easy on me
I was wondering if nodemon can be configured to automatically launch a browser instance with the specified localhost (e.g. localhost:8080). So far I have been unable to locate any solution for this on google and other forums.

I've had my dev command on npm run to look like the following setups:
- dev": "nodemon --inspect --watch config --watch src/server/main.js"
"dev": "nodemon --inspect --watch config --watch src/server/main.js localhost 8080"
"dev": "nodemon --inspect --watch config --watch src/server/main.js --run localhost 8080"
(figured run is a webpack flag, but i tried it anyway, just because i couldn't find an overall view of the available flags

I want to my script to automatically launch my default browser when running nodemon

**Comment by remy** [comment]
You need to put the opening browser logic in your own code (assuming `src/server/main.js`?). Using something like [open](https://www.npmjs.com/package/open) - nodemon doesn't support this as a native feature (to ensure that nodemon remains agnostic to the tech you're using it for).
