### ISSUE TITLE
Nothing happens when pressing backspace in the console when trying to remove input

### ISSUE THREAD

**Issue by swessey** [remy/nodemon#1394]
- `nodemon -v`:
1.18.1

- `node -v`:
v8.11.3

- Operating system/terminal environment: 
   Linux raspbian arm

- Command you ran:

   while true; do nodemon index.js; done

### Expected behaviour
According to me it is supposed to remove the input.

### Actual behaviour
As soon as the server starts running, whenever I type somehing in the console I cannot remove it using backspace || delete. The only thing I can do is pressing return.

### Steps to reproduce
1, Start script with terminal.
2, Wait until the server is on.
3, type something in the console.
4, pressing backspace or delete.
5, nothing happens.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

--------------
node: v8.11.3
nodemon: 1.18.1
command: /usr/bin/node /usr/bin/nodemon --dump
cwd: /home/linus
OS: linux arm
--------------
{ run: false,
  system: { cwd: '/home/linus' },
  required: false,
  dirs: [ '/home/linus' ],
  timeout: 1000,
  options: 
   { dump: true,
     ignore: 
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**',
        re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot: 
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     signal: 'SIGUSR2',
     stdout: true,
     watchOptions: {},
     execOptions: 
      { script: null,
        exec: 'node',
        args: [],
        scriptPosition: null,
        nodeArgs: undefined,
        execArgs: [],
        ext: 'js,mjs,json',
        env: {} },
     monitor: 
      [ '*.*',
        '!**/.git/**',
        '!**/.nyc_output/**',
        '!**/.sass-cache/**',
        '!**/bower_components/**',
        '!**/coverage/**',
        '!**/node_modules/**' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  signal: 'SIGUSR2',
  command: { raw: { executable: 'node', args: [] }, string: 'node' } }

**Comment by remy** [comment]
Please use nodemon@latest - it'll fix your issue.
