### ISSUE TITLE
Webstorm Tab freezes on error after 1.17.x -> 1.18.x

### ISSUE THREAD

**Issue by ivan-kleshnin** [remy/nodemon#1395]
After I updated Nodemon from 1.18.x from 1.17.5, it started to freeze a tab in Webstorm IDE after an error.
Ctrl-C, or `rs` don't help (as previously did) – I need to close and reopen a tab each time an error, happens which is impossible to tolerate in the long term :(

**Comment by remy** [comment]
Can you provide any debugging information? 

One big help would be to know exactly which nodemon you're referring to?

**Comment by ivan-kleshnin** [comment]
What do you mean by "which"? I gave two version numbers, what else can I add?

**Comment by remy** [comment]
By "which" I mean 1.18.x isn't a specific version. Some patch versions of 1.18.x have bugs, some don't. So it's important for me to know exactly what version you're using (hence the issue template - which I think you removed).

I just need the result from `nodemon -v`.

Can you provide the `server.js` you're using (ideally with no deps or a package.json so I can replicate the issue). I don't use webstorm, so I'll have to download it to see if I can replicate what you're seeing.

**Comment by ivan-kleshnin** [comment]
Ok, got it. I'll try to experiment with different 1.18 patches first and if the problem is present in all of them –  I'll make a test example with all that data for you.

**Comment by ivan-kleshnin** [comment]
Can't reproduce reliably – maybe a Webstorm issue. Let me close this and reopen in case I get proves that it's about Nodemon.
