### ISSUE TITLE
How to show the wrong number of lines

### ISSUE THREAD

**Issue by Mr-jiangzhiguo** [remy/nodemon#1397]
- `nodemon -v`:1.11.0
- `node -v`:10.6.0
- Operating system/terminal environment: mac  iterminal2
- Command you ran: npm run dev

### Expected behaviour
When throw Error, i hope it can show the error which file and the number of line

### Actual behaviour
but now, it is `[nodemon] app crashed - waiting for file changes before starting...`

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Your nodemon is wildly out of date. Can you update and report back?

Also, with current nodemon, I see this:

```
nodemon http.js
[nodemon] master: 363891ff3d9bb71f27b303a40947334645bd3979
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node http.js`
/Users/remy/Sites/nodemon/issues/1397/http.js:1
(function (exports, require, module, __filename, __dirname) { require('http').createServer((req, res) => { res.end('ok'); throw new Error('fail');}).listen(8000);
                                                                                                                          ^

Error: fail
    at Server.require.createServer (/Users/remy/Sites/nodemon/issues/1397/http.js:1:129)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:602:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
[nodemon] app crashed - waiting for file changes before starting...
```

Where http.js is [this code](https://gist.github.com/remy/6647e5ca3e5c28872eca3cbd42aeba26)
