### ISSUE TITLE
detached child processes are killed when nodemon resets

### ISSUE THREAD

**Issue by Autre31415** [remy/nodemon#1398]
- `nodemon -v`: 8.11.3
- `node -v`: 1.18.3
- Operating system/terminal environment:  macOS iTerm2
- Command you ran: `nodemon -v app.js --development-mode`

### Expected behaviour
[Detached child processes](https://nodejs.org/api/child_process.html#child_process_options_detached) should survive a nodemon reset, just as they would survive a CTRL+C.

### Actual behaviour
Detached child processes are killed on reset. If that child process happens to be a java process the app directory will also get spammed with hs_err_pidxxxx.log files that indicate `SIGSEGV` errors. Example:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000010da86c68, pid=13670, tid=0x0000000000000307
```

### Steps to reproduce
1. In macOS start up a node process in nodemon which spawns a detached child process.
2. Reset by either editing a watched file or using `rs`

Note: I don't believe this issue exists on windows.

**Comment by remy** [comment]
@alallier I'm all the maintainers and owner. I don't have a solution, and so it's stale as no one has come forth.

Can @Autre31415 provide parred down code to replicate? I'm not sure this is fixable (again, since no one has offered any solution), as nodemon is doing exactly what it's supposed to do (end all the subprocesses).

**Comment by wsmd** [comment]
I'm also dealing with this issue. I'm spawning worker processes as detached children that are not part of the codebase I'm using nodemon with, so when the parent process exists, ideally, I'd like for those processes to keep running, even during development. 

For example:

```js
const worker = spawn('some_command', args, {
  stdio: 'ignore',
  detached: true,
});

worker.unref()
```

Using `detached` and `unref()` has no effect when the application is running with nodemon as it ends up killing all child processes in the tree on restart anyways:

https://github.com/remy/nodemon/blob/7e00a30d31c5a464f7a2bee0657a4aa5e702236a/lib/monitor/run.js#L323-L343

I can't think of an elegant way to exclude processes that are explicitly detached, but maybe we can add a `--no-tree-kill` flag for this kind of scenarios. I know that fewer flags is one of the design principles of nodemon, but there isn't really a workaround here, is there?

Could you please consider reevaluating this issue?

**Comment by remy** [comment]
Nodemon is a development tool for shutting down and restarting. If a process is being "detected", then the dev cycle is to shut it down - not ignore it.

If you need to use nodemon with your codebase in this fashion, the best approach is to spawn the subprocess *outside* of what's being monitored by nodemon.
