### ISSUE TITLE
if no file is specified use package.json's main property

### ISSUE THREAD

**Issue by dylang** [remy/nodemon#14]
A simple short for lazy developers - if no command line arguments and package.json exist then use the main property.   

EDIT: was use index.js

**Comment by FagnerMartinsBrack** [comment]
Makes no sense, this is ridiculous. Using "main" violates the principle of least astonishment. Node CLI DOES NOT uses "main" for starting the server, that's used for import clients not server start clients.

I'm using the same project as a import to other bounded contexts to be able to execute code owned by one domain boundary and the server startup that uses npm run dev to start a specific server file using nodemon start-server. My npm start uses node start-server which works.

How do I prevent this completely unexpected and erroneous behaviour?

Please guys, avoid trying to do magic, I beg you. Nodemon is a great tool don't destroy it.
