### ISSUE TITLE
stopping nodemon doesn't release the port

### ISSUE THREAD

**Issue by sachshar** [remy/nodemon#1400]
- `nodemon -v`:
1.17.5
- `node -v`:
v10.0.0
- Operating system/terminal environment: 
Mac OSX(Sierra)
- Command you ran:
Started the node.js app server using "nodemon .". While trying to stop it, it takes CTRL+C twice. 

### Expected behaviour
CTRL+C should stop the nodemon and should release the port

### Actual behaviour
To stop the nodemon, we have to presss CTRL+C twice. Even after that port continues to listen and we have to kill it manually via process kill

### Steps to reproduce
This is a little bit tough part. I have been using loopback(3.20.0) with Oracle as the datasource. If I don't use it with Oracle database, it works fine. To reproduce, create a loopback app (as per https://loopback.io) and connect it with Oracle database as datasource. Start the app using "nodemon ." and try to stop it.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

After stopping the nodemon, when i look for my port(3001)'s  active process, below is the log
Command used: "lsof -i :3001"

COMMAND   PID    USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
firefox   763  sachin  103u  IPv4 0xd63d94b789266837      0t0  TCP localhost:62339->localhost:redwood-broker (ESTABLISHED)
node    10755  sachin   20u  IPv4 0xd63d94b78908bf3f      0t0  TCP *:redwood-broker (LISTEN)
node    10755  sachin   21u  IPv4 0xd63d94b7836cd267      0t0  TCP localhost:redwood-broker->localhost:62339 (ESTABLISHED)

**Comment by sachshar** [comment]
Command output wasn't clear so attaching the image

<img width="1063" alt="screen shot 2018-08-02 at 6 07 55 pm" src="https://user-images.githubusercontent.com/9347057/43584111-130b04f6-967f-11e8-8f51-365e6b32ba5b.png">

**Comment by whymarrh** [comment]
[You can format the command output as a code block using three backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to make it a bit more readable (than an image)

**Comment by remy** [comment]
Given:

> This is a little bit tough part. I have been using loopback(3.20.0) with Oracle as the datasource. If I don't use it with Oracle database, it works fine. 

Is this an issue that's specific to your usage with this database? If you can replicate without the whole hog, then I could look at it and try to see what's going on - but without a sample I've nothing to work with. Unless you're able to debug and fix within your own dev env.
