### ISSUE TITLE
err_connection_refused when redirecting

### ISSUE THREAD

**Issue by juberjj** [remy/nodemon#1404]
- nodemon v1.18.3
- node v8.6.0
- Fedora 27
- Command you ran: nodemon

### Expected behaviour
Response.redirect should redirect to the right landing page

### Actual behaviour

Getting err_connection_refused 

### Steps to reproduce

I have an small node app using express. One section of the app I use to add assessments, once it's done I have a redirect in place to refresh the page accordingly but using nodemon I get the error. If I start the app using "node app.js" it does work and I see the page refreshing accordingly. This seems to be happening only when using nodemon, if I manually refresh the page it does render. No errors on console whatsoever.

---

**Comment by remy** [comment]
Please can you provide a sample of your app. Otherwise I can't replicate your bug.

**Comment by juberjj** [comment]
@remy Absolutely, those are the methods called.

'use strict';

const accounts = require ('./accounts.js');
const moment = require('moment');
const _ = require('lodash');
const logger = require('../utils/logger');
const assessmentStore = require('../models/assessment-store');
const memberstore = require('../models/member-store');
const uuid = require('uuid');
const gymutil = require('../utils/gymutility');

const dashboard = {
  index(request, response) {
    logger.info('dashboard rendering');
    const loggedInUser = accounts.getCurrentUser(request);
    logger.info(loggedInUser);
    const assessment = assessmentStore.getUserAssessment(loggedInUser.id);
    const viewData = {
      title: 'Dashboard',
      assessment: _.sortBy(assessment, assessment.date).reverse(),
      member: memberstore.getUserById(loggedInUser.id),
      bmi:  gymutil.bmi(loggedInUser),
      idealweight: gymutil.idealweight(loggedInUser),
    };
    response.render('dashboard', viewData);
  },

  deleteAssessment(request, response) {
    const assessmentId = request.params.id;
    logger.debug(`Deleting Assessment ${assessmentId}`);
    assessmentStore.removeAssessment(assessmentId);
    response.redirect('/dashboard');
  },

  addAssessment(request, response) {
    const loggedInUser = accounts.getCurrentUser(request);
    const newAssessment = {
      id: uuid(),
      userid: loggedInUser.id,
      username: loggedInUser.name,
      date:  moment().format('DD MMM YYYY, h:mm:ss a'),
      weight: request.body.weight,
      chest: request.body.chest,
      thigh: request.body.thigh,
      upperarm: request.body.upperarm,
      waist: request.body.waist,
      hips: request.body.hips,
    };
    logger.debug('Creating a new Assessment', newAssessment);
    assessmentStore.addAssessment(newAssessment);
    response.redirect('/dashboard' );
  },
};

module.exports = dashboard;

**Comment by remy** [comment]
Can you cut that down so I'm able to replicate? Obviously I don't have any of your deps, so I'm looking for a parred down case.

**Comment by juberjj** [comment]
Oops sorry, Can you grab it here https://github.com/juberjj/play-gym-js

**Comment by juberjj** [comment]
@remy any news mate? were you able to replicate the issue? Cheers.

**Comment by chandrakumarreddy** [comment]
facing similar issue.

**Comment by misjaz** [comment]
Facing same issue.
