### ISSUE TITLE
Cannot pass awaitWriteFinish option to the watcher

### ISSUE THREAD

**Issue by dnohales** [remy/nodemon#1405]
So I wanted to pass the Chokidar's option `awaitWriteFinish: true` to the nodemon watcher, but it's not taking the option from my `nodemon.json` file:

```
{
    "ext": "js,json",
    "watchOptions": {
        "awaitWriteFinish": true
    }
}
```

After a bit of debugging, I noted that the Chokidar options are passed [here](https://github.com/remy/nodemon/blob/master/lib/monitor/watch.js#L73) and then I printed the value of the `config` variable to find this:

```
{
    run: true,
    system: 
    {
        cwd: '<a dir>'
    },
    required: false,
    dirs: [
        '<a dir>'
    ],
    timeout: 1000,
    options: 
    {
        verbose: true,
        watch: [ 'server.lib/', re: /server\.lib\// ],
        watchOptions: {
            awaitWriteFinish: true
        },
        ignore: 
        [
            '**/.git/**',
            '**/.nyc_output/**',
...
```

So, the line previously mentioned should be:

```diff
  var watcher = chokidar.watch(
    dirs,
-   Object.assign({}, watchOptions, config.watchOptions || {})
+   Object.assign({}, watchOptions, config.options.watchOptions || {})
  );
```

Is this an actual typo or am I doing something wrong?

**Comment by remy** [comment]
This is a typo in the code. Happy to take a PR to fix it if you'd like?

**Comment by dnohales** [comment]
FYI, I opened I PR for this some days ago, thanks!
