### ISSUE TITLE
What is the correct configuration to ignore all sub-directories except one?

### ISSUE THREAD

**Issue by redonkulus** [remy/nodemon#1411]
- `nodemon -v`: 1.18.3
- `node -v`: v10.7.0
- Operating system/terminal environment: Mac
- Command you ran: grunt nodemon

I would like to be able to watch a directory that exists in the `node_modules` folder, but not watch the entire `node_modules` (for perf). For example:

```
- node_modules/foo
- node_modules/bar <-- watch only this one
- node_modules/baz
```

There is documentation in the [faq](https://github.com/remy/nodemon/blob/master/faq.md#overriding-the-underlying-default-ignore-rules) that mentions how to override the default `ignoreRoot`, but I haven't been able to get it working in the scenario above.

I have tried:

```
options: {
    delay: 1000,
    ignore: [
        'build/**/'
    ],
    ignoreRoot: [
        '.git',
        '.nyc_output',
        '.sass-cache',
        'bower_components',
        'coverage',
        'node_modules/!(foo)'
    ],
    ext: 'js json'
}
```

I had to copy the ignoreRoot defaults since it gets them from the `ignore-by-default` npm module. I've tested by adding `** **` around the glob too, but it doesn't help. Am I configuring this correctly?

**Comment by redonkulus** [comment]
Bump

**Comment by redonkulus** [comment]
Lol

**Comment by redonkulus** [comment]
😳

**Comment by redonkulus** [comment]
🤫

**Comment by redonkulus** [comment]
😳

**Comment by JhinDeng** [comment]
I maybe have the some problem like you. different is i want watch my won node_modules. 

my config:
```
{
  "verbose": true,
  "watch": [
    "*",
    "lib/node_modules"
  ],
  "ext": "js,json,json5"
}
```
but it not works when I have some change in these files under lib/node_modules

**Comment by redonkulus** [comment]
🙏

**Comment by remy** [comment]
The short version of this is: I don't think you can, without listing all the modules manually.

The only answer to this would be to generate each directory on the fly, which could be achieved if there was support for `nodemon.js` over `nodemon.json`.

**Comment by dkebler** [comment]
It's the default watch/ignore assumptions that preclude this.  Essentially watch everything under cwd except what is in the ignoreRoot   

How about a new flag that can be set if users want to set their own watches. Basically a flag that disables any default watches and ignores.

so a flag say `noDefaults` which mean nodemon will not watch or ignore anything by default.  It then would be the responsibility of the user to set all the watches they need 

so like this example for nodemon.json

options: {
    noDefaults: true,  
    "watch": ["src","index.js","test",node_modules/@uci/*/src"]
}

I'll start a new issue
