### ISSUE TITLE
Are there any known type definitions for nodemon?

### ISSUE THREAD

**Issue by robbyemmert** [remy/nodemon#1414]
- `nodemon -v`: 1.18.4
- `node -v`: v10.9.0
- Operating system/terminal environment: macOS High Sierra
- Command you ran: npm install @types/nodemon

### Expected behaviour
Either type definitions should be included with the package, or a type definition should be published to DefinitelyTyped @types repository.

Reasons:
- Many code editors pick up on type definitions for intellisense/autocomplete purposes (even in a non-typescript environment). This increases discoverability and adoption rates for JS developers, and drastically reduces human error.
- Using untyped libraries in Typescript is difficult to impossible, depending on the environment. Everyone ends up hacking together their own ad-hoc type definitions, which is time consuming and can cause difficult-to-trace runtime issues if poorly done. Ad-hoc type definitions also need to be updated manually on every upgrade. This ultimately decreases the usability of the library for TS projects.

My opinion:
Anyone can technically create some type definitions and publish them via DefinitelyTyped. However, it would be far better in my opinion to keep the typing in the package itself. This way you don't run in to any versioning issues, and the community here gets to control them.

Question:
Do any typings for nodemon currently exist? If so, we should probably import them into the project like so: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

If not, I'll probably have to hack together some type defs for my current project, and I'd be happy to donate them such as they will be.

### Actual behaviour
No types exist

### Steps to reproduce
Install nodemon, then try to use autocomplete, or import it into a typescript file.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Short answer: no.

And wow, "untyped libraries in Typescript is difficult to impossible" - I'm kind of amazed that people have been able to use nodemon for 8 years without it!!!

Happy to take a PR. I don't use autocomplete nor typescript, so I'm one of those edge cases that didn't find it impossible - but that also means I've no idea how to implement or test.

**Comment by gaoxiaoliangz** [comment]
It would be nice to have type definition.

**Comment by MarcelRittershaus** [comment]
@types/nodemon
https://www.npmjs.com/package/@types/nodemon
npm i @types/nodemon
