### ISSUE TITLE
events.exit: Wait for child process to finish before triggering restart ? 

### ISSUE THREAD

**Issue by gomesalexandre** [remy/nodemon#1419]
- `nodemon -v`: 1.18.3
- `node -v`: v8.11.3
- Operating system/terminal environment: OSX 10.13.6, zsh
- Command you ran: `nodemon app.js`

### Expected behaviour

**nodemon.json**
```javascript
{
  "ignore": ["dist/*"],
  "events": {
    "exit": "npm run build"
  }
}
```

I'd expect the `build` process to exit before restart happens, so the app gets built. 

### Actual behaviour

Because it doesn't, it is still using the old files by the time it restarts. 

### Steps to reproduce

- Build a simple express server 
- Use the `nodemon.json` provided herre
---

Is there anyway to execute such command on exit, and wait until it exits before firing the restart event ? 
For anyone interested, I ended up making a `wait-for-it.js` file which is essentially running the build step and the server thanks to `shelljs`: 

**wait-for-it.js**
```javascript
const shellJs = require('shelljs');

shellJs.exec(`./node_modules/.bin/flow-remove-types src/ -d dist`);
shellJs.exec(`node -r esm dist/server.js`);
```

Because this is synchronous, there is no problem of dist not being outputted yet anymore. 

However that's far from an ideal solution IMO

**Comment by gomesalexandre** [comment]
@nomcopter Please consider using my workaround if that works for you. You can tweak it to e.g wait a few seconds, same idea here, as this will be synchronous (shellJS isn't async) it will virtually solve the issue.

**Comment by justjake** [comment]
@nomcopter I'm here with the same problem, similarly frustrated. The last time I solved this issue, it was by explicitly shutting down my listeners in a signal handler. This time around, I don't want to mess with existing handlers. I'll probably add waiting or retry code to my `server.listen(...)` calls.

**Comment by remy** [comment]
Happy to reopen if someone includes a PR or even some inkling of proposal.

**Comment by nomcopter** [comment]
`--waitForExit` makes `nodemon` wait until the child completely exists before firing any events or attempting a restart.

**Comment by remy** [comment]
Sure, that's a flag, but how are you implementing this (particularly as the default state is to wait until the process has finished, otherwise nodemon isn't doing its job and you'd see 1,000s of 👍 asking for this functionality - ie. It's specific to the use case, which as yet hasn't been detailed)

**Comment by nomcopter** [comment]
The default state is to wait until the process has finished? In my project nodemon does not wait at all, and immediately starts another one.

**Comment by remy** [comment]
So pare the code down so it's still replicable and post it here…

**Comment by nomcopter** [comment]
Replication [here](https://github.com/nomcopter/nodemon-no-wait-repro) @remy. Looks like an interaction with `--inspect` in my case.

**Comment by nomcopter** [comment]
Although now looking at the original issue, I misread it. I'm going to start a separate issue for this.

**Comment by mdobroggg** [comment]
I'm having the same issue. I think it has to do with using an async call in `process.on` to exit. It seems like nodemon is acting on the original kill signal rather than the one re-thrown from process.on
