### ISSUE TITLE
Add optional timestamp on output

### ISSUE THREAD

**Issue by crystalfp** [remy/nodemon#1420]
### This is a feature request.

- `nodemon -v`: 1.18.4
- `node -v`: 10.9.0
- Operating system/terminal environment: Windows 10 64bits
- Command you ran: `nodemon --watch server --ext js,json,yaml -- server/app.js --configuration server/config.yaml`

### Expected behaviour
Please add a switch to output a timestamp to the usual messages:

```
[nodemon] restarting due to changes...
[nodemon] starting `node server\app.js --configuration server\config.yaml`
```
Sometimes it is hard to see when the server restarted and how many times restarted.

Thanks!
mario

**Comment by remy** [comment]
What is the use case for knowing how many times the server has restarted?

**Comment by crystalfp** [comment]
I use nodemon in development and sometime I'm not sure if the server has restarted or I should restart it manually (eg to reread configuration). Package "supervisor" had it and was quite handy. Anyway, it is a minor feature. I have to check if this can be simulated with "events" attached to "start" and "restart".
In any case, thanks for the tool!
mario

**Comment by remy** [comment]
You can also hook into the events using the JSON config to echo out an environment counter.

In general I prefer to reuse the existing tech over adding new features if possible and where it makes sense. 

If you can't see how it's done, ping me next week and I'll mock together an example config (I'm only on my phone for the next few days)

**Comment by crystalfp** [comment]
OK, solved. Maybe could be useful to others.

In `nodemon.json` add:

```
{
  "events": {
    "start": "node printdate.js"
  }
}
```
In the working directory put the `printdate.js` that contains (well, I tried to be a little sophisticate):
```
const today = new Date();
let dd = today.getDate();
if(dd < 10) dd = "0" + dd;
let mm = today.getMonth() + 1; // January is 0!
if(mm < 10) mm = "0" + mm;
const yyyy = today.getFullYear();
let hh = today.getHours();
if(hh < 10) hh = "0" + hh;
let ii = today.getMinutes();
if(ii < 10) ii = "0" + ii;
let ss = today.getSeconds();
if(ss < 10) ss = "0" + ss;

console.log("[nodemon]", `${yyyy}-${mm}-${dd} ${hh}:${ii}:${ss}`);
```
So I'm happy and close this feature request.
Thanks!
mario

**Comment by mohanraj-r** [comment]
Thanks @crystalfp 

I added a similar nodemon.json

```json
{
  "events": {
    "start": "printf '%s\n' ----------------------------------------; date"
  }
}
```

This is very useful to me. Could be useful to many if nodemon output this info by default I guess.

**Comment by chucklu** [comment]
This should be the default behavior output log with a timestamp.

**Comment by chucklu** [comment]
npm i -g date-time
and [configure the NODE_PATH for win 10 ](https://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows)
```js
const dateTime = require('date-time');
var currentTime = dateTime({local: true, showTimeZone: true, showMilliseconds: true});
console.log(currentTime)
```
The ouput looks like 2020-12-23 18:10:27 758ms UTC+8
