### ISSUE TITLE
Stop watching command

### ISSUE THREAD

**Issue by ILoveYouDrZaius** [remy/nodemon#1423]
I think a command for stop watching would be useful. This command would allows you continue editing code without pain while your script is finalizing, and it should have another command to return to watching.

These possible commands would work like the 'rs' command.

Thank you.

**Comment by remy** [comment]
There are two commands (certainly work on the mac), once nodemon is running in the terminal:

1. To stop: ctrl-c
2. To resume: ⬆️↩️ (up + enter)

👍

**Comment by ILoveYouDrZaius** [comment]
Yes, also in Windows.

But it stops the execution of the program. I mean stop only watching. That way, you can continue editing files without fear of stopping the execution of the program.

Thanks for reply.
