### ISSUE TITLE
Weird character showing while running nodemon

### ISSUE THREAD

**Issue by lawchihon** [remy/nodemon#1428]
- `nodemon -v`: 1.17.1
- `node -v`: v6.10.2
- Operating system/terminal environment: macOS High Sierra Version 10.13.4
- Command you ran: nodemon server

### Expected behaviour
[nodemon] 1.17.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server`

### Actual behaviour
ÄnodemonÅ 1.17.1
ÄnodemonÅ to restart at any time, enter érsé
ÄnodemonÅ watching: *.*
ÄnodemonÅ starting énode serveré

### Steps to reproduce
Just start the nodemon

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
You're going to need to provide more information than "just start nodemon" - because I don't see this and I'm pretty sure it's linked to your own local configuration.

I guess a starting point would be switch to either terminal.app or iterm2.app and try again.
