### ISSUE TITLE
Support for npm start script

### ISSUE THREAD

**Issue by johngeorgewright** [remy/nodemon#143]
Hey there,

Is there any way of using nodemon with npm's start script?

I tried:

``` sh
$ nodemon -x npm start
```

and

``` sh
$ nodemon -x "npm start"
```

and also just `nodemon` on it's own, but I just get the help dialogue with no error.

**Comment by toymachiner62** [comment]
I would also like to use nodemon to run `$ npm start` because I want it to also run the prestart script which lints my project.

Example:
// package.json snippet
"scripts": {
    "prestart": "eslint index.js",
    "start": "node index.js",

if i run `$ npm start`, it first runs `$ npm prestart`.
I want to somehow do this with nodemon so that it runs not only the start script but also the prestart script.

Any ideas?

**Comment by remy** [comment]
The pre and post hooks for npm aren't supported. The solution here would be to change the `start` value to `nodemon index.js`.

**Comment by toymachiner62** [comment]
That won't work exactly for me b/c I used npm start in production.

But that did spark a light bulb. I can do something like this:

```js
"prestart": "eslint .",
    "start": "node index.js",
    "predev": "eslint .",
    "dev": "nodemon index.js"
}
```

and then `$ npm start` will work for prod and `$ npm run dev` will work for development.

BOOYA!

Thanks for your help.

**Comment by toymachiner62** [comment]
Crap i spoke too soon. It only runs the `predev` script on initial launch. Subsequent file changes only run nodemon again and not the `predev` npm script.

**Comment by nathanhleung** [comment]
Here was my solution:
```
"scripts": {
    "prestart": "eslint .",
    "start": "node app",
    "dev": "nodemon --exec npm start"
  },
```

Nodemon will automatically catch any errors with eslint and then restart on changes.

**Comment by VictorioBerra** [comment]
@nathanhleung Does that mean eslint will run even in production via "npm start" instead of "npm dev"?

**Comment by nathanhleung** [comment]
@VictorioBerra yes, since the prestart hook will run eslint. However, eslint will only run once if you invoke `npm start` directly.

Alternatively, you could try this approach:

```
"scripts": {
    "predev": "eslint .",
    "dev": "npm start",
    "start": "node app",
    "nodemon": "nodemon --exec npm dev"
  },
```

You'd run `npm run nodemon` to lint on changes, and `npm start` directly to run the server without linting.

**Comment by VictorioBerra** [comment]
@nathanhleung I needed to add `run` into `npm dev` for `npm run dev`

**Comment by ORESoftware** [comment]
Are there hooks we can put in `nodemon.json` instead of npm scripts?
