### ISSUE TITLE
TAB and ARROWS keys has strange behavior in shell prompt

### ISSUE THREAD

**Issue by ildella** [remy/nodemon#1445]
**-**- `nodemon -v`: 1.18.5
- `node -v`: 11.0.0
- Operating system/terminal environment: Ubuntu Linux 18.10

### Expected behaviour
nodemon should work as node

### Actual behaviour
With nodemon, tab and arrows keys behave differently, making the experience different from the real app and impossible to work with during development.

### Steps to reproduce
Create a simple nodejs file with this code:

```const readline = require('readline')
const ui = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  prompt: 'MyShell>'
})
ui.prompt()
```
Run this with node and then with nodemon. 
Play with ARROWS key with nodemon will print ```> ^[[A^[[A^[[A``` or similar. 
TAB key just print some blank spaces and messes up with the actual input. 

In node they both behave properly.

PS: I have the same issue with 'forever' as well.

---

**Comment by remy** [comment]
How are you running nodemon?

**Comment by ildella** [comment]
> How are you running nodemon?

```
npm i -g nodemon
nodemon file.js
```

**Comment by remy** [comment]
So you need to pass stdin to your script using the `-I` flag: https://github.com/remy/nodemon/blob/master/doc/cli/options.txt#L16

**Comment by waynebloss** [comment]
This is not working for me no matter what I do in XFCE terminal. If I press Ctrl+C only once, my up arrow doesn't work.

**Comment by waynebloss** [comment]
OK nevermind - it's a yarn problem. Everything works if I use npm to run the task.
