### ISSUE TITLE
[nodemon] clean exit - waiting for changes before restart

### ISSUE THREAD

**Issue by c-y-q** [remy/nodemon#1448]
l have this questions,and can't resolve it,it is here:
[nodemon] clean exit - waiting for changes before restart
![jsmdndmnfmdfndmf](https://user-images.githubusercontent.com/24750024/48600106-7fee4f00-e9a5-11e8-9dec-f5653bb85bba.png)
The application cannot be started and cannot be accessed.

**Comment by ingpedrorr** [comment]
Try running the following commands:

`yarn add express`
then
`nodemon index.js`

it worked for me.

**Comment by c-y-q** [comment]
> Try running the following commands:
> 
> `yarn add express` or ` npm install express`
> then
> `nodemon index.js`
> 
> it worked for me.

l am using koa2 for my app,the problem of nodemon do not work in latest days.

**Comment by Manish-Jaiswal** [comment]
If using mac goto activity monitor and force quit all node process.

**Comment by ptflores1** [comment]
I fixed it by changing the version of node from 14.5 to 13.5
