### ISSUE TITLE
Feature request: Restart on SIGUSR1

### ISSUE THREAD

**Issue by sabrehagen** [remy/nodemon#1449]
I have many nodemon instances. After booting my stack many are in the 'unclean exit - waiting for changes' state. This requires me to navigate to the codebase and Ctrl+S on a file to get nodemon to reload that project.

This issue arises because nodemon is not watching my `build` directory where my typescript code is compiled to, only the `src` directory where my `.ts` files are stored.

If I could send a process signal e.g. SIGUSR1 that would cause nodemon restart its child script, that would allow me to automate this manual command performed in multiple places with one command :)

**Comment by remy** [comment]
Use the --signal option.
