### ISSUE TITLE
restarting continuously in CMDER console  

### ISSUE THREAD

**Issue by bharathnallamothu** [remy/nodemon#1458]
- `nodemon -v`:1.18.6
- `node -v`:v10.4.0
- Operating system/terminal environment: windows 10/ CMDER terminal
![image](https://user-images.githubusercontent.com/17136986/48900115-7ff3c080-ee77-11e8-9db0-47ea757c8b0c.png)

**Comment by remy** [comment]
Can you run with `--verbose` to see what's causing the restart?

**Comment by remy** [comment]
Can't replicate due to lack of information. Happy to reopen with info on how to replicate and ideally a PR.

**Comment by bharathnallamothu** [comment]
![image](https://user-images.githubusercontent.com/17136986/49141640-106d4d80-f31d-11e8-8c34-67789dfa5b51.png)
