### ISSUE TITLE
Nodemon - app crashes when restarting due to Node already running on that port

### ISSUE THREAD

**Issue by Nmoleo64** [remy/nodemon#1464]
- `nodemon -v`:1.18.6
- `node -v`:8.10.0
- Operating system/terminal environment: 
- Command you ran:

### Expected behaviour
Nodemon closes the old Node process and creates a new one

### Actual behaviour
Nodemon doesn't stop the old Node process and then the new one crashes because it's trying to run on the same port

### Steps to reproduce
Run Nodemon and save the file after making changes

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by RoyalHunt** [comment]
Found same solution... With "pstree.remy": "1.1.0" which use ps-tree library it is work fine.

**Comment by forsigner** [comment]
My solution:

```yarn add kill-port```

in  ```nodemon.json```:

```json
{
  "events": {
    "restart": "kill-port 5000",
    "crash": "kill-port 5000"
  }
}
```

Replace your port: 

```json
"restart": "kill-port [my port]",
```

**Comment by murrayju** [comment]
@RoyalHunt be careful with rolling back `pstree.remy`, that upgrade eliminated malicious code in the dependency tree. See #1442 and also dominictarr/event-stream#116.

@remy any idea what is causing this bug? Breaks my entire workflow that depends on nodemon restarts...

**Comment by jordie23** [comment]
@murrayju Thanks for the heads up. Did the same, restricted ours to `pstree.remy@1.1.0` and `event-stream@3.3.4`. Not using yarn, I set these in our top level package.json file and rebuilt our shrinkwrap, and because NPM likes to dedup it'll use these versions for other packages that have them as deps and matches the semver.

**Comment by remy** [comment]
I need to know your OS…

**Comment by ravid87** [comment]
i have this problem with :
Ubuntu 18.04
node 8.13.0

**Comment by remy** [comment]
@ravid87 do you have a pared down version of a script that I can replicate with? 

I'm using this in ubuntu (in docker) and I can't replicate either when it's a triggered restart or `rs` restart:

```js
const express = require('express');

const app = express();

app.use((req, res, next) => {
    res.send('<h1>Hello from Express!</h1>');
});

app.listen(3000)
```

**Comment by ravid87** [comment]
@remy 

https://github.com/ravid87/testmon

**Comment by remy** [comment]
Track here https://github.com/remy/nodemon/issues/1463#issuecomment-441964924

**Comment by arabrain** [comment]
Change the port to any other port number, just not  3000.
 for exemple make it 5000 or 4000 it will be okay
------------------------
with port = 4000 
![image](https://user-images.githubusercontent.com/27920730/62434532-a48e8080-b706-11e9-8171-cb0f0138d803.png)

------------------------
With port = 3000
![image](https://user-images.githubusercontent.com/27920730/62434454-58dbd700-b706-11e9-8765-0ebf40c2b8bc.png)

**Comment by aymather** [comment]
I am still having this problem using Node v8.11.3, on MacOS 10.14.3.

**Comment by arabrain** [comment]
@Aymather u need to kill the process work on the port for exemple 3000 and restart everything.Or u will take my idea, that mean u will change the port every time when u have the same problem.

**Comment by aymather** [comment]
When I tried restarting on different ports I still had the same issue. Right now my fix is to use the following command in the command line: `lsof -ti tcp:5000 | xargs kill` and then running `npm run dev` but even then sometimes I'll get the same error.

**Comment by Alvaro-Vargas** [comment]
I made a dummy change in the code (Added a single space and saved), this forced the nodemon to restart and then I could stop it (crtl + c).

**Comment by AndrewOdiit** [comment]
do this in package.json
"scripts": {
    "start": "node server",
    "server": "fuser -k 8000/tcp && nodemon server"
  },
this will kill the old process running on port8080 before nodemon restarts

**Comment by TCarmine** [comment]
This is happening again. I am wondering if the fix introduced [https://github.com/remy/nodemon/commit/c05d2d1e3a1977692d36def8c5d64c73046965c1](url) has again been overrided wrongly

**Comment by TCarmine** [comment]
for the moment similar to   aymather , I am killing forcely all the process on that port with `sudo kill -9 $(sudo lsof -t -i:3000)` and I put that in the package.json  script that I run on my convenience  (like clean)

**Comment by remy** [comment]
@TCarmine if you're seeing a new issue you'll want to create a new issue (even though it has similar symptoms to this issue raised last year). You'll also need to make sure you're on the latest nodemon, currently 2.0.1

**Comment by remy** [comment]
I'm going to lock this issue to encourage any new issues into new (and monitored) discussion 👍
