### ISSUE TITLE
Potential security issue with dependency, underlying maintainers seem unresponsive.

### ISSUE THREAD

**Issue by parktheredcar** [remy/nodemon#1467]
There seems to be something suspicious going on in your dependency chain, and maintainers down the line aren't being super responsive. Just wanted to get this on your radar.
```
`-- nodemon@1.18.6
  `-- pstree.remy@1.1.0
    `-- ps-tree@1.1.0
      `-- event-stream@3.3.6
        `-- flatmap-stream@0.1.2
```
https://github.com/indexzero/ps-tree/issues/33

https://github.com/dominictarr/event-stream/issues/116

**Comment by cnorthwood** [comment]
Think this is a dupe of https://github.com/remy/nodemon/issues/1451

**Comment by indexzero** [comment]
FYI `ps-tree@1.1.1` locked to `event-stream@3.3.4` (which if I read this thread correctly pre-dates the questionable changes). 

Thanks to folks for bringing it to my attention: https://github.com/indexzero/ps-tree/pull/34

**Comment by remy** [comment]
@gftea upgrade to the patched/latest nodemon, it would have saved you from posting
