### ISSUE TITLE
Missing flatmap-stream dependency - Failing to install

### ISSUE THREAD

**Issue by mikebm** [remy/nodemon#1468]
npm install fails due to a dependency not resolving.
The dependency is flatmap-stream and appears to no longer exist in the npm repository.
https://www.npmjs.com/package/flatmap-stream

### Expected behaviour
nodemon should install

### Actual behaviour
nodemon fails to install with the following error:
npm ERR! code E404
npm ERR! 404 Not Found: flatmap-stream@^0.1.0

### Steps to reproduce
Simply run npm install

**Comment by rdunk** [comment]
Looks like `flatmap-stream` has been removed from npm:
https://github.com/dominictarr/event-stream/issues/116

**Comment by stevelacy** [comment]
@remy Thanks for updating pstree.remy to remove ps-tree. Could you publish the latest on master as well? Should fix the issue now that npm has removed flatmap-stream

**Comment by jakepeyser** [comment]
For additional context on why `flatmap-stream` was removed from npm https://github.com/dominictarr/event-stream/issues/116

**Comment by jnv** [comment]
I think this is due to locked dependencies and it can be fixed by reinstalling nodemon, i.e.: `npm uninstall nodemon; npm i -D nodemon`. This will (hopefully) pull in the latest version of `pstree.remy` without affected dependencies.

**Comment by spiritson** [comment]
Is the fix published to npm?

**Comment by jnv** [comment]
@spiritson The latest published version of pstree.remy is 1.1.2 which is fixed.

**Comment by jay-hankins** [comment]
@spiritson Yes, the fix is in a dependency pstree.remy@1.1.2. Just uninstall and reinstall nodemon in your project using npm or yarn appropriately.

**Comment by mikebm** [comment]
Closed since pstree.remy has been fixed.

**Comment by anton-mladenov** [comment]
@jnv YOU saved the day! You deserve a prize! Thank you! 🥳
