### ISSUE TITLE
Nodemon fails to restart process with EADDRINUSE

### ISSUE THREAD

**Issue by aecorredor** [remy/nodemon#1473]
I have a simple express sever at https://github.com/aecorredor/express-graphql-postgres-starter that uses nodemon to restart my server when a file changes. Every time I make a change, nodemon tries to restart but fails with the error `EADDRINUSE `.

Note that I am not using concurrently (which has been mentioned in other issues as a possible cause). I just run `nodemon --exec babel-node index.js`.

- `nodemon -v`:
^1.18.6

- `node -v`:
10.14.0

- Operating system/terminal environment: 
MacOS Mojave 10.14

- Command you ran:

### Expected behaviour
Nodemon automatically restarts node process when a change is made.

### Actual behaviour
Nodemon fails to restart the node process saying that the port is already in use.

### Steps to reproduce
Clone this repo: https://github.com/aecorredor/express-graphql-postgres-starter and run yarn and then yarn start, make a change, save, and see the error.

**Comment by wtgtybhertgeghgtwtg** [comment]
The example works if you bump to `nodemon@1.18.7`, at least locally.

**Comment by remy** [comment]
I'll mark 1.18.6 as deprecated, that bug was fixed in the .7 patch as @wtgtybhertgeghgtwtg said

**Comment by trevorhreed** [comment]
I had this problem in v1.18.9. Used the following code at the bottom of my server.js/app.js file. Putting this here in case it's helpful to anyone else who stumbled upon this from Google, like I did.

```javascript

// ...

const server = app.listen(PORT)

process.once('SIGUSR2', function () {
  server.close(function () {
    process.kill(process.pid, 'SIGUSR2')
  })
})
```
