### ISSUE TITLE
nodemon fails to restart when you prompt with the readline module

### ISSUE THREAD

**Issue by Adimvicky** [remy/nodemon#1474]
I'm on Windows 10 and i'm using node v10.13.0 and nodemon v1.18.2
My code uses the readline  module to create an REPL interface that prompts the user for input after i run `nodemon filename.js`. After making changes to filename.js, nodemon does not restart the app. I'd have to exit the app and run `nodemon filename.js` again to see my changes.

**Comment by remy** [comment]
Can you start by upgrading nodemon to latest - just to rule that out?

**Comment by Adimvicky** [comment]
I just upgraded to the latest version `v1.18.7`, and the issue persists
