### ISSUE TITLE
Error: Cannot find module '.../nodemon/bin/postinstall'

### ISSUE THREAD

**Issue by hubitor** [remy/nodemon#1478]
I'm getting following error when I try to install nodemon globally:

```
/home/user/.nvm/versions/node/v10.14.0/bin/nodemon -> /home/user/.nvm/versions/node/v10.14.0/lib/node_modules/nodemon/bin/nodemon.js

> nodemon@1.18.7 postinstall /home/user/.nvm/versions/node/v10.14.0/lib/node_modules/nodemon
> node bin/postinstall || exit 0

internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module '/home/user/.nvm/versions/node/v10.14.0/lib/node_modules/nodemon/bin/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:826:3)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/nodemon/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ nodemon@1.18.7
updated 1 package in 3.795s
```

- `nodemon -v`: 1.18.4
- `node -v`: v10.14.0
- Operating system/terminal environment: Antergos (Arch Linux) / zsh
- Command you ran: $ sudo npm install -g nodemon

**Comment by remy** [comment]
Have you tried installing without sudo?

**Comment by remy** [comment]
Okay, to rule things out, do you get the error when you install nodemon locally as a development dependency? (without sudo).

(Aside, you'll want to fix your permissions, I'm sure there's an article I've come across in the past by npm that explains how to fix it - the biggest potential threat is a malicious package is downloads and run under your sudo access)

**Comment by hubitor** [comment]
> Okay, to rule things out, do you get the error when you install nodemon locally as a development 
dependency? (without sudo).

No. Locally it gets installed normally (two warnings about fsevents like before but no error ).

> (Aside, you'll want to fix your permissions, I'm sure there's an article I've come across in the past by npm that explains how to fix it - the biggest potential threat is a malicious package is downloads and run under your sudo access)

Thanks for the tip! I'll look into it.

**Comment by hafbau** [comment]
I've recently got this problem within my docker environment. @hubitor how were you able to resolve this please?

**Comment by hubitor** [comment]
@hafbau Sorry for the late response. I've just seen your comment.

To be honest I don't remember, but I think it was because of "sudo" like @remy mentioned.
Check these links:
https://www.tilcode.com/install-npm-packages-globally-without-sudo/
https://www.competa.com/blog/how-to-run-npm-without-sudo/

**Comment by BransonGitomeh** [comment]
I got this error too when running `npx nodemon` inside npm scripts inside a docker container.
