### ISSUE TITLE
nodemon doesn't monitor changes in views/partials/

### ISSUE THREAD

**Issue by starleaf1** [remy/nodemon#1480]
I installed nodemon globally, which I set to `~/.npm-global/`. Nodemon is run directly from the project's root directory.

- `nodemon -v`: `1.18.7`
- `node -v`: `v8.12.0`
- Operating system/terminal environment: Ubuntu 18.04.1 x86_64
- Command you ran: `nodemon`

### Expected behaviour
Nodemon restarts the app.

### Actual behaviour
Nodemon does nothing.

### Steps to reproduce

1. Create an Express.js app
2. Use `hbs` as view engine
3. Store your partials in `views/partials/`
4. Create an `hbs` file in `views/partials/`
5. Change the file. Nodemon won't restart the app.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
You need to tell nodemon to watch hbs files. It only watches js and JSON by default
