### ISSUE TITLE
Can we update lock dependencies to not have that module at all?

### ISSUE THREAD

**Issue by marharyta** [remy/nodemon#1482]
I noticed you had pstree.remy in package lock file. Should we update or remove it from there also? Related to a commit: https://github.com/remy/nodemon/commit/21e052eddf144b27a7c0eb9c603236707003d75d
https://github.com/remy/nodemon/blob/2dcdd0eb8928144eedaa3577b19cfc611bf9f298/package-lock.json#L4373

**Comment by mauriciosouto** [comment]
Same issue here!
Can't deploy to heroku

```
Build failed
remote:  !     The flatmap-stream module has been removed from the npm registry
remote: 
remote:        On November 26th, npm was notified of a malicious package that had made its
remote:        way into event-stream, a popular npm package. After triaging the malware,
remote:        npm responded by removing flatmap-stream and event-stream@3.3.6 from the Registry
remote:        and taking ownership of the event-stream package to prevent further abuse.
```

**Comment by remy** [comment]
@marharyta sorry, I'm not sure I follow what you're asking. pstree.remy@1.1.2 is a required dependency of nodemon.

@mauriciosouto (ignoring that you're deploying nodemon to a server…) why are you getting that failure with the latest nodemon? It's not part of the dep tree:

<details><summary>$ npm ls event-stream</summary>

```
❯ npm i nodemon

> fsevents@1.2.4 install /Users/remy/Sites/tmp/nodemon/node_modules/fsevents
> node install

[fsevents] Success: "/Users/remy/Sites/tmp/nodemon/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> nodemon@1.18.7 postinstall /Users/remy/Sites/tmp/nodemon/node_modules/nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN tmp@1.0.0 No description
npm WARN tmp@1.0.0 No repository field.

+ nodemon@1.18.7
added 291 packages from 146 contributors and audited 2238 packages in 11.22s
found 0 vulnerabilities

 ~/Sites/tmp/nodemon ⮀
❯ npm ls event-stream
tmp@1.0.0 /Users/remy/Sites/tmp/nodemon
└── (empty)
```

**Comment by remy** [comment]
Closing as I'm pretty sure this isn't an issue - pstree.remy has no deps as of nodemon@1.18.7 onwards.

**Comment by marcosmartinez7** [comment]
Using nodemon 1.18.9 having the same issue https://github.com/remy/nodemon/issues/1498

**Comment by remy** [comment]
Repeating here too - nodemon's current package-lock file does not include the vulnerable dependencies: https://github.com/remy/nodemon/blob/master/package-lock.json#L4371
