### ISSUE TITLE
Malware found in dependency (windows / upgrade didn't work fully)

### ISSUE THREAD

**Issue by HectorCastelli** [remy/nodemon#1487]
On windows machine.
Xeon E5-2694 v4
16.0 GB RAM
Nodemon version: 1.18.7
Found with Trend Micro OfficeScan

#### SHA ENCRYPTED
- coinminer.win32.malbtc.aa 
- C:\Users\xxx\AppData\Roaming\npm-cache\_cacache\content-v2\sha512\94\0a\
- b8b4b616(...)

#### APPLICATION ROOT(?)
- coinminer.js.malbtc.aa 
- C:\Users\xxx\AppData\Roaming\npm\node_modules\nodemon\node_modules\flatmap-stream\
- index.min.js

#### ?
- coinminer.js.malbtc.aa.component
- C:\Users\xxx\AppData\Roaming\npm\node_modules\nodemon\node_modules\flatmap-stream\test
- data.js

**Comment by remy** [comment]
Hmm. That's odd, since nodemon @ 1.18.7 doesn't include that package anywhere in it's dep tree. 1.18.6 _did_, but .7 does not.

How did you upgrade?

**Comment by remy** [comment]
For more complete view on what's happening, please paste the contents of `C:\Users\xxx\AppData\Roaming\npm\node_modules\nodemon\package.json` here.

Thanks.

**Comment by HectorCastelli** [comment]
Sorry! I made a typo on the report. I was indeed using 1.18.6.

Since this dependency is now removed, should we close this issue?

**Comment by remy** [comment]
Yes, it's been resolved and entirely removed in 1.18.7.
