### ISSUE TITLE
Starting inspector on 0.0.0.0:9229 failed: address already in use

### ISSUE THREAD

**Issue by xDelph** [remy/nodemon#1492]
- `nodemon -v`: 1.18.8
- `node -v`: 9.4.0
- Operating system/terminal environment: ubuntu 18.04
- Using Docker? What image: docker -> FROM node:slim
- Command you ran: ./node_modules/.bin/nodemon --inspect=0.0.0.0 --legacy-watch ./src ./src/index.js

### Expected behaviour
inspector restart on file change 

### Actual behaviour
Starting inspector on 0.0.0.0:9229 failed: address already in use

### Steps to reproduce
using a dockerfile like : 
```
FROM node:slim

# Create app directory
WORKDIR /usr/app

# Install app dependencies
COPY package.json /usr/app/
RUN npm install

# Bundle app source
COPY . /usr/app

CMD [ "npm", "run", "watch" ]
```

**Comment by remy** [comment]
Is the `watch` scripts entry the same as `./node_modules/.bin/nodemon --inspect=0.0.0.0 --legacy-watch ./src ./src/index.js`?

And can you replicate with this script:

```js
require('http').createServer((req, res) => res.end('ok')).listen(8000);
```

**Comment by xDelph** [comment]
> Is the `watch` scripts entry the same as `./node_modules/.bin/nodemon --inspect=0.0.0.0 --legacy-watch ./src ./src/index.js`?
> 
> And can you replicate with this script:
> 
> ```js
> require('http').createServer((req, res) => res.end('ok')).listen(8000);
> ```

yes, this is the watch entry
and yes i replicate the problem with index.js containing only this line of code

**Comment by xDelph** [comment]
here is my package.json if needed

```
{
  "name": "",
  "version": "1.4.1",
  "main": "index.js",
  "scripts": {
    "start": "node ./src/index.js",
    "watch": "./node_modules/.bin/nodemon --inspect --watch ./src ./src/index.js",
    "test": "echo 'no test implemented !!'"
  },
  "license": "MIT",
  "dependencies": {
    "axios": "^0.18.0",
    "body-parser": "^1.18.3",
    "dotenv": "^6.0.0",
    "express": "^4.16.3",
    "foreman": "^3.0.1",
    "jsonwebtoken": "^8.3.0",
    "mongodb": "^2.2.14",
    "mssql": "^4.1.0",
    "nodemon": "^1.18.8"
  }
}

```

docker-compose : 1.22.0
docker : 18.09.0

**Comment by remy** [comment]
Can you provide a full working `Dockerfile` and `docker-compose.yml` file? I know _very little_ about docker, so it's hard for me to replicate fully to debug. (and possibly how to start the container…)

**Comment by xDelph** [comment]
you will find a project setup to reproduce the issue here : https://github.com/xDelph/nodemon-issue-inspector

just launch `docker-compose up` at the root

**Comment by remy** [comment]
Sorry - I've _just_ solved the issue (with a lot of messing on the command line).

If you do a hard upgrade of nodemon, it should include the latest pstree.remy@1.1.5 (a quick check with `npm ls pstree.remy` should validate). If you have that sub-dep, then you'll find it properly kills the inspector.

**Comment by xDelph** [comment]
great, it's ok now
thansk for your help ;)

**Comment by justinpage** [comment]
As described in #1476 I'm still seeing this issue with `1.18.9`.

The issue is intermittent with the following start command:

`./node_modules/.bin/nodemon --inspect=0.0.0.0:9229 ./index.js`

**Comment by JonDum** [comment]
I get this issue all the time. Not sure when exactly it started happening, but it didn't use to happen.

node v11.11.0 via alpine-v11

```
─┬ nodemon@1.18.10
  └── pstree.remy@1.1.6
```
```
"dev": "nodemon -L -d 2 --inspect=0.0.0.0:9229 -- --icu-data-dir=$NODE_ICU_DATA_PATH index.js"
```

Would be happy to retrieve any logs or additional info to help narrow this down.

**Comment by srfrnk** [comment]
> I get this issue all the time. Not sure when exactly it started happening, but it didn't use to happen.
> 
> node v11.11.0 via alpine-v11
> 
> ```
> ─┬ nodemon@1.18.10
>   └── pstree.remy@1.1.6
> ```
> ```
> "dev": "nodemon -L -d 2 --inspect=0.0.0.0:9229 -- --icu-data-dir=$NODE_ICU_DATA_PATH index.js"
> ```
> Would be happy to retrieve any logs or additional info to help narrow this down.

@JonDum - Happens to me as well. See logs below:
```
[nodemon] starting `node --inspect -r ts-node/register ./src/index.ts`
Debugger listening on ws://127.0.0.1:9229/5c2962b0-43a0-4210-93ac-fc81e6d537f8
For help, see: https://nodejs.org/en/docs/inspector
Example app listening on port 3000!
[nodemon] restarting due to changes...
[nodemon] starting `node --inspect -r ts-node/register ./src/index.ts`
Debugger listening on ws://127.0.0.1:9229/f0c7fdda-8b0f-4ebe-8a79-37099d8596d6
For help, see: https://nodejs.org/en/docs/inspector
Example app listening on port 3000!
[nodemon] restarting due to changes...
[nodemon] starting `node --inspect -r ts-node/register ./src/index.ts`
Debugger listening on ws://127.0.0.1:9229/3336a7df-a763-440e-9e92-20ec0811726b
For help, see: https://nodejs.org/en/docs/inspector
Example app listening on port 3000!
[nodemon] restarting due to changes...
[nodemon] starting `node --inspect -r ts-node/register ./src/index.ts`
[nodemon] restarting due to changes...
Debugger listening on ws://127.0.0.1:9229/cc164e40-316f-4b07-8bc2-c2dc80f5d515
For help, see: https://nodejs.org/en/docs/inspector
[nodemon] starting `node --inspect -r ts-node/register ./src/index.ts`
Debugger listening on ws://127.0.0.1:9229/86884f82-93b2-4885-a580-3f29b00f1065
For help, see: https://nodejs.org/en/docs/inspector
Example app listening on port 3000!
[nodemon] restarting due to changes...
[nodemon] starting `node --inspect -r ts-node/register ./src/index.ts`
[nodemon] app crashed - waiting for file changes before starting...
Starting inspector on 127.0.0.1:9229 failed: address already in use
[nodemon] restarting due to changes...
[nodemon] starting `node --inspect -r ts-node/register ./src/index.ts`
[nodemon] app crashed - waiting for file changes before starting...
Starting inspector on 127.0.0.1:9229 failed: address already in use
[nodemon] restarting due to changes...
[nodemon] starting `node --inspect -r ts-node/register ./src/index.ts`
[nodemon] app crashed - waiting for file changes before starting...
Starting inspector on 127.0.0.1:9229 failed: address already in use
[nodemon] restarting due to changes...
[nodemon] starting `node --inspect -r ts-node/register ./src/index.ts`
[nodemon] app crashed - waiting for file changes before starting...
Starting inspector on 127.0.0.1:9229 failed: address already in use
```

**Comment by csalvato** [comment]
Happens to me as well:

```
nodemon@^1.18.11:
  version "1.18.11"
  resolved "https://registry.yarnpkg.com/nodemon/-/nodemon-1.18.11.tgz#d836ab663776e7995570b963da5bfc807e53f6b8"
  integrity sha512-KdN3tm1zkarlqNo4+W9raU3ihM4H15MVMSE/f9rYDZmFgDHAfAJsomYrHhApAkuUemYjFyEeXlpCOQ2v5gtBEw==
  dependencies:
    chokidar "^2.1.5"
    debug "^3.1.0"
    ignore-by-default "^1.0.1"
    minimatch "^3.0.4"
    pstree.remy "^1.1.6"
    semver "^5.5.0"
    supports-color "^5.2.0"
    touch "^3.1.0"
    undefsafe "^2.0.2"
    update-notifier "^2.5.0"
```

Not sure why it's happening.  Here's my package.json script...:

```

**Comment by srfrnk** [comment]
Maybe my workaround can help you guys:
https://stackoverflow.com/questions/43898947/docker-node-app-always-crashes-on-file-change-using-nodemon/55881699#55881699

**Comment by Shahor** [comment]
Sorry for upping this, but I'm having the exact same issue :|

**Comment by ssas01** [comment]
My code is wrong, so it appears.

**Comment by nanxiaobei** [comment]
Just add `--delay 300ms` into the command.

https://github.com/remy/nodemon#delaying-restarting

**Comment by Arman92** [comment]
> Just add `--delay 300ms` into the command solved my problem.
> 
> https://github.com/remy/nodemon#delaying-restarting

Thank you, it fixed in my case.

**Comment by erikeckhardt** [comment]
I fixed my problem by changing the npm `dev` script and the nodemon `exec` command, to move the time of setting NODE_OPTIONS later, from this:
```
package.json: "dev": "NODE_OPTIONS=--inspect=0.0.0.0:9229 nodemon -L src/index.ts"
nodemon.json: "exec": "ts-node -r dotenv/config"
```
to this:
```
package.json: "dev": "nodemon -L src/index.ts"
nodemon.json: "exec": "NODE_OPTIONS=--inspect=0.0.0.0:9229 ts-node -r dotenv/config"
```
What must have been happening was that node and/or nodemon was taking over listening on the port, but ts-node was also trying to do the same thing. By setting the environment variable later, that is avoided.
