### ISSUE TITLE
Nodemon clears the console after running the script while using the "start" event

### ISSUE THREAD

**Issue by YannickFricke** [remy/nodemon#1494]
First of all: Thanks for this awesome piece of software! <3

- `nodemon -v`: 1.18.8
- `node -v`: 9.11.1
- Operating system/terminal environment: Linux Mint (Ubuntu Xenial) / zsh
- Using Docker? What image: No
- Command you ran:
`nodemon -e py -x "python main.py"`

### Expected behaviour
Nodemon should clear the console before it runs the script.

### Actual behaviour
Console gets cleared after the script ran.

Here is a quick [demo](https://asciinema.org/a/e2b9Iewgo35rlaUdM3ecDXeVI)
And here is the test [repository](https://github.com/YannickFricke/nodemon-python-issue)

### Steps to reproduce
Run the following command:
```
nodemon -e py -x "python main.py"
```
I should mention that it works with pytest (the testing library for python) and other programs (i.e. PHP, Golang)

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.
```
[nodemon] 1.18.8
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
--------------
node: v9.11.1
nodemon: 1.18.8
command: /home/yfr/.nvm/versions/node/v9.11.1/bin/node /home/yfr/.yarn/bin/nodemon -e py -x python main.py --dump
cwd: /srv/PyCIn
OS: linux x64
--------------
{ run: false,
  system: { cwd: '/srv/PyCIn' },
  required: false,
  dirs: [ '/srv/PyCIn' ],
  timeout: 1000,
  options: 
   { exec: 'python main.py',
     dump: true,
     events: { start: 'node -e "console.clear()"' },
     ignore: 
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**',
        re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot: 
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     signal: 'SIGUSR2',
     stdout: true,
     watchOptions: {},
     execOptions: 
      { script: null,
        exec: 'python main.py',
        args: [],
        scriptPosition: null,
        nodeArgs: undefined,
        execArgs: [],
        ext: 'py',
        env: {} },
     monitor: 
      [ '*.*',
        '!**/.git/**',
        '!**/.nyc_output/**',
        '!**/.sass-cache/**',
        '!**/bower_components/**',
        '!**/coverage/**',
        '!**/node_modules/**' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [ '/srv/PyCIn/nodemon.json' ],
  watchInterval: null,
  signal: 'SIGUSR2',
  command: 
   { raw: { executable: 'python main.py', args: [] },
     string: 'python main.py' } }
--------------
```

**Comment by YannickFricke** [comment]
Any news on this? :)

**Comment by YannickFricke** [comment]
@remy Do you need any further informations?
Cause it also happens sometimes to php related software.

**Comment by remy** [comment]
I'm just commenting because I've worked out what's going on here. Though I'm not totally sure it's a quick fix.

Run.js does the following:

1. Spawns the child process
2. Emits the 'start' event
3. On the start event the value is spawned

Moving (2) to before (1) doesn't make any difference, because it still spawns _after_ (or however long it takes) (1) - which is why there's a weird race condition on the clear screen.

I'll revisit this with some thoughts.

**Comment by remy** [comment]
Took a while to get to the bottom of this, but it boils down to boot time. Your python process boots faster than the node process (that clears the screen).

I've updated the FAQ to include the "best" way to [clear the screen](https://github.com/remy/nodemon/blob/master/faq.md#how-to-clear-the-console-on-restart).
