### ISSUE TITLE
Package.lock using a infected lib

### ISSUE THREAD

**Issue by marcosmartinez7** [remy/nodemon#1498]
Detected this issue today 

![image](https://user-images.githubusercontent.com/14795944/50658699-eee52e80-0f78-11e9-980e-a13c14d3de32.png)

The problem is related to this: https://medium.com/intrinsic/compromised-npm-package-event-stream-d47d08605502

I check who is including that library and i found this:

![image](https://user-images.githubusercontent.com/14795944/50658763-2653db00-0f79-11e9-8068-7caffbfed4c6.png)

And then event-stream 

![image](https://user-images.githubusercontent.com/14795944/50658779-379ce780-0f79-11e9-8d78-c38833d7f832.png)

I also found this library using the event stream.. so i search who imported that lib:

Found this

![image](https://user-images.githubusercontent.com/14795944/50658891-8ba7cc00-0f79-11e9-8d84-2975fb3cab72.png)

Then i check for that library and i found this on the package.lock and yarn.lock. 

![image](https://user-images.githubusercontent.com/14795944/50658940-b4c85c80-0f79-11e9-81a3-f578b3b8b410.png)

Any ideas if this is related with nodemon or gulp-nodemon?

I have read this issue https://github.com/remy/nodemon/issues/1482, but im using a greater version, the 1.18.9 version... so according to that issue this lib must not be included

**Comment by marcosmartinez7** [comment]
I have deleted node_modules, lockfiles and checked that gulp-nodemon is using the last version of nodemon (it saids ^1.18.7)

My installed version is 1.18.9 and the pstree.remy library stills installed.

**Comment by remy** [comment]
The current package-lock file does *not* include the vulnerable dependencies: https://github.com/remy/nodemon/blob/master/package-lock.json#L4371

The package-lock.json file for the latest build of nodemon uses pstree.remy@1.1.6 which does not carry the vuln deps. Please update your own deps (note also that gulp-nodemon is not my project so I can't make any changes to it).

**Comment by marcosmartinez7** [comment]
So, gulp-nodemon is using the last version of nodemon. 

The last version of nodemon is using the last version of pstree.remy

If you said that pstree.remy@1.1.6 does not has the vulnerability then the only explanation is that windows defender is reading the trojan database and recognizing it as a vulnerability as a false positive.
