### ISSUE TITLE
[nodemon] Internal watch failed: errmap.get is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by toscanoGithub** [remy/nodemon#1499]
- `nodemon -v`:
- `node -v`:
- Operating system/terminal environment: 
- Using Docker? What image: 
- Command you ran:

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by toscanoGithub** [comment]
nodemon express-middleware.js
Output:
[nodemon] 1.17.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node express-middleware.js`
[nodemon] Internal watch failed: errmap.get is not a function or its return value is not iterable

PS:
node express-middleware.js works as expected
Thank you

**Comment by remy** [comment]
Out of date nodemon (also issue is missing other required info).

Please update.

**Comment by toscanoGithub** [comment]
Edited on first comment.
Thank you

**Comment by remy** [comment]
Again, can you update to latest nodemon, and retest?

**Comment by toscanoGithub** [comment]
Thank you for your effort,
I can'n update to the latest version of nodemon. Here is my terminal log with commands

AITASSOUs-MacBook-Pro:~ aitassouabdelkader$ nodemon -v
1.17.3
AITASSOUs-MacBook-Pro:~ aitassouabdelkader$ sudo npm -g uninstall nodemon
Password:
removed 291 packages in 2.112s
AITASSOUs-MacBook-Pro:~ aitassouabdelkader$ sudo npm i -g nodemon
/Users/aitassouabdelkader/.npm-global/bin/nodemon -> /Users/aitassouabdelkader/.npm-global/lib/node_modules/nodemon/bin/nodemon.js

> fsevents@1.2.4 install /Users/aitassouabdelkader/.npm-global/lib/node_modules/nodemon/node_modules/fsevents
> node install

[fsevents] Success: "/Users/aitassouabdelkader/.npm-global/lib/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> nodemon@1.18.9 postinstall /Users/aitassouabdelkader/.npm-global/lib/node_modules/nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

+ nodemon@1.18.9
added 291 packages from 146 contributors in 6.158s
AITASSOUs-MacBook-Pro:~ aitassouabdelkader$ nodemon -v
1.17.3
AITASSOUs-MacBook-Pro:~ aitassouabdelkader$


??????
??
??
??
??
??
??
??
??
??
??
??
??


??
??
________________________________

-cre??z votre site web (blog) gratuitement et facilement<http://www.viteblog.com/>:www.viteblog.com
??-passez vos annonces gratuitement cliquez ici<http://www.bicoeur.com/>: www.bicoeur.com



<http://www.bicoeur.com/>
??

________________________________

**Comment by remy** [comment]
My bet is when you ran `sudo npm -g uninstall nodemon` nodemon was still installed.

You've got somehow got your install locations in a bit of a mess.

Also, where those extra 17 lines of `?` characters part of your terminal output or should it be ignored?

**Comment by toscanoGithub** [comment]
Managed to install the latest version of nodemon but still get the same error.


AITASSOUs-MacBook-Pro:node aitassouabdelkader$ node -v
v11.6.0
AITASSOUs-MacBook-Pro:node aitassouabdelkader$ nodemon -v
1.18.9
AITASSOUs-MacBook-Pro:node aitassouabdelkader$ nodemon express-post-data.js --dump
[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
--------------
node: v11.6.0
nodemon: 1.18.9
command: /usr/local/bin/node /usr/local/bin/nodemon express-post-data.js --dump
cwd: /Users/aitassouabdelkader/Downloads/Diaz/course/node
OS: darwin x64
--------------
{ run: false,
  system:
   { cwd: '/Users/aitassouabdelkader/Downloads/Diaz/course/node' },
  required: false,
  dirs: [ '/Users/aitassouabdelkader/Downloads/Diaz/course/node' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**',
        re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot:
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     signal: 'SIGUSR2',
     stdout: true,
     watchOptions: {},
     execOptions:
      { script: 'express-post-data.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        execArgs: [],
        ext: 'js,mjs,json',
        env: {} },
     monitor:
      [ '*.*',
        '!**/.git/**',
        '!**/.nyc_output/**',
        '!**/.sass-cache/**',
        '!**/bower_components/**',
        '!**/coverage/**',
        '!**/node_modules/**' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  signal: 'SIGUSR2',
  command:
   { raw: { executable: 'node', args: [ 'express-post-data.js' ] },
     string: 'node express-post-data.js' } }
--------------
AITASSOUs-MacBook-Pro:node aitassouabdelkader$


??????
??
??
??
??
??
??
??
??
??
??
??
??


??
??
________________________________

-cre??z votre site web (blog) gratuitement et facilement<http://www.viteblog.com/>:www.viteblog.com
??-passez vos annonces gratuitement cliquez ici<http://www.bicoeur.com/>: www.bicoeur.com



<http://www.bicoeur.com/>
??

________________________________

**Comment by remy** [comment]
Can you 

1. Provide a script that I can replicate your bug
2. Stop with the patronising series of `?` in your issue, it's getting on my wick.

**Comment by toscanoGithub** [comment]
Thank you for your help.
It’s working now. I had to restart my computer .


Sent from my iPhone

On Jan 6, 2019, at 6:59 AM, Remy Sharp <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you

  1.  Provide a script that I can replicate your bug
  2.  Stop with the patronising series of ? in your issue, it's getting on my wick.

**Comment by maihannijat** [comment]
Updated to [nodemon] 1.18.10 and have this error now. Tried uninstalling and installing it again but did not help. Restart my computer, killed previous node process, installed globally with save flag - Nothing resolved the problem.

**Comment by remy** [comment]
I'd look to node as the potential problem, or npm permissions
