### ISSUE TITLE
Error on nodemon install

### ISSUE THREAD

**Issue by charles-dejager** [remy/nodemon#1500]
- `nodemon -v`: v1.18.9
- `node -v`: v11.4.0
- Operating system/terminal environment: OSx x64 v18.2.0
- Using Docker? What image: No
- Command you ran: npm install --save-dev nodemon

### Actual behaviour
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@11.4.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
../fsevents.cc:63:6: warning: field 'async_resource' will be initialized after field 'lockStarted' [-Wreorder]
   : async_resource("fsevents:FSEvents"), lockStarted(false) {
     ^
1 warning generated.
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/djagercd/dev/sdm/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

> nodemon@1.18.9 postinstall /Users/djagercd/dev/sdm/node_modules/nodemon

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Is this a warning (as it looks like it is) or an error?

It also looks like it was installed, going by your version number.

**Comment by charles-dejager** [comment]
Hi Remy.  Yes. It seems you are correct.  It is only a warning.

Thanks

**Comment by charles-dejager** [comment]
> Is this a warning (as it looks like it is) or an error?
> 
> It also looks like it was installed, going by your version number.

Hi Remny.  Yes, it looks like it is only a warning.

Thanks.

**Comment by remy** [comment]
I think then, the issue should be raised against fsevents as that's the dependency throwing the warning (though I'm not 100% sure what the solution is, as I suspect it's using the warning as more _info_ than anything else).

> node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@11.4.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)

Closing this source issue, but thanks for raising 👍
