### ISSUE TITLE
nodemon 1.18.9 not working in windows 10 *64

### ISSUE THREAD

**Issue by Devpokhariya** [remy/nodemon#1501]
I have installed nodemon
 _npm install nodemon --g_
and the server is starting as it is suppose to but then while i change in my file 
it says 
_restarting due to changes..._ 
and nothing other then this line and the weird thing is 
the server didnot restart i have restarted my pc tried updating the nodemon my friend is using same thing and in his computer it worked but not mine. I m not sure what the isuue is.
Can anyone help me here.
` nodemon index.js
[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
the app is running....
[nodemon] restarting due to changes...`

**Comment by NinthAutumn** [comment]
I have this exact problem! it works on my macbook but not in my windows.... =_=

**Comment by RitvikSangwan** [comment]
I am also facing the same problem on windows 8.1 and nodemon version 1.18.9

**Comment by llupRisingll** [comment]
I got the glitch this glitch after installing the latest update of nodemon. So I tried to revert back to the old version and it doesn't do anything. I think the update does something on the windows operating system that cannot remove even after uninstall and installing (reinstall) the nodemon package. 
I believe the problem can be solve by reinstalling the os as stated on the previous Issue, https://github.com/remy/nodemon/issues/1461#issuecomment-442487389 but this isn't an efficient fix.

**Comment by llupRisingll** [comment]
I tries debugging by reverting back to old versions... and guess what?
For windows machine, please stick with version 1.17.15. It is working well and will fix the bug.
Use `npm i -g nodemon@1.17.15` hope that helps.

**Comment by remy** [comment]
Those old versions also include deep vulnerabilities, which is why older versions are not supported.

**Comment by llupRisingll** [comment]
I am using version for about 1.17.15 and it was stuck at restarting due to changes. The same issue in version 1.18.x. 
It stopped working after a trying to save changes multiple times before the "Starting node app.js" message appear.
The problem is somewhat hard to figure out since the installation also WARNs about the optional module `fsevent` not being able to install.

**Comment by bke-daniel** [comment]
Hello everyone,

some goes for OSX. Info nodemon is installed locally, not globally.
`node -v v8.15.0
npx nodemon -v 1.18.9 `

We had this in #1435 

Cheers,
Daniel

**Comment by LemuelCushing** [comment]
Same here, been looking for a solution all over. Windows 10, reverting to @1.17.15 didn't make a difference

**Comment by remy** [comment]
Can you all retest with nodemon@1.18.10 - it might fix the issue you were seeing.

Otherwise, since there's been no interest in finding the source of the issue on this thread, I'll close it in a few days.

**Comment by LemuelCushing** [comment]
Hi @remy, I've upgraded to 1.18.10, but to no avail..

**Comment by remy** [comment]
@LemuelCushing can you detail what you're seeing and how you're able to replicate with as little code as possible?

**Comment by tylerreece22** [comment]
If you want to use nodemon on Windows 10 but can't get it to work globally you can always install it as a dev dependency, cd into your project directory, and run `yarn run nodemon` or `npm run nodemon` and it will function the same. Hope that helps.

**Comment by LemuelCushing** [comment]
@remy sorry for the delay - I've just set up a simple package with nothing but nodemon and the [basic  "hello world" app.js](https://nodejs.org/en/docs/guides/getting-started-guide/) file. I'm using nodemon as a dev dependency, and my ```yarn start``` is set to `nodemon app.js`.
When I start it, I get the usual message:
<pre>
 ⨯ Lemuel Cushing@CUTHBERT  C\..\nodemon_test  yarn start
yarn run v1.13.0
$ nodemon app.js
[nodemon] 1.18.10
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
Server running at http://127.0.0.1:3000/
</pre>
When I make a change to app.js and save it, I get
`[nodemon] restarting due to changes...`
Which just hangs. 

If I add the -V flag, the follwing is displayed:
<pre>
 Lemuel Cushing@CUTHBERT  C\..\nodemon_test  yarn start
yarn run v1.13.0
$ nodemon -V app.js
[nodemon] 1.18.10
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 34116 to restart
[nodemon] watching: *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
[nodemon] forking
[nodemon] child pid: 10640
[nodemon] watching 3 files
Server running at http://127.0.0.1:3000/
</pre>
And after I save a change:
<pre>
[nodemon] files triggering change check: app.js
[nodemon] matched rule: **\*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] app.js

[nodemon] files triggering change check: app.js
[nodemon] matched rule: **\*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] app.js
</pre>

**Comment by icetbr** [comment]
The problem is when nodemon first detects a change, it spawns a new node process.

**Comment by markwilliamson05** [comment]
I'm having same issue on Windows Server 2016. I've tried nodemon globally and locally and no luck. If I run in verbose mode it says watching 0 files despite having my app.js file clearly present. It also reads that it's watching *.* with extensions: js,mjs,json ... anybody having luck with this?

**Comment by jordanbtucker** [comment]
The issue is with chokidar since 2.1.3. See https://github.com/paulmillr/chokidar/issues/812

This can be fixed in nodemon by setting `atomic` to `false` in the options for `chokidar.watch`.

**Comment by paulmillr** [comment]
Fixed chokidar.

**Comment by remy** [comment]
Star, I'll push a bumpped version of nodemon to pull the updated dep
(others: you sho be able to reinstall nodemon and it *should* pick up the
latest change in chokidar.

**Comment by d4rth-v4d3r** [comment]
I'm having a similiar issue in Windows 10 Pro and nodemon@1.18.10. I'm using the command:

` yarn cross-env NODE_ENV=development nodemon --watch dist-dev --inspect dist-dev/lib/index.js`

Nodemon is not restarting when a file is modified 😢. I installed version 1.18.0 and this command works like a charm. 🐱‍🐉

**Comment by jordanbtucker** [comment]
@d4rth-v4d3r What do you get when you run this?

```
npm ls | findstr "chokidar"
```

If you see `chokidar@2.1.3` or `chokidar@2.1.4`, then that's your problem. It needs to be `chokidar@2.1.5` or later.

**Comment by jordanbtucker** [comment]
> Star, I'll push a bumpped version of nodemon to pull the updated dep (others: you sho be able to reinstall nodemon and it *should* pick up the latest change in chokidar.

@remy Can you bump the chokidar dependency to 2.1.5? Currently, reinstalling nodemon doesn't work if chokidar@2.1.3 is already in the dependency tree either directly or from another package.

For example, if I run `npm i -D chokidar@2.1.3`, reinstalling nodemon is not going to pull down chokidar@2.1.5. It's just going to use 2.1.3, which has the bug.

Nuking `node_modules` should work, but only if another package hasn't pinned chokidar@2.1.3.

**Comment by d4rth-v4d3r** [comment]
This is my output 

`| +-- chokidar@1.7.0`
`| +-- chokidar@2.1.4 extraneous`

**Comment by jordanbtucker** [comment]
@d4rth-v4d3r That's strange. What are the `dependencies` and `devDependencies` in `package.json`?

**Comment by d4rth-v4d3r** [comment]
```
```

**Comment by remy** [comment]
@d4rth-v4d3r your version of nodemon is 1.18.0 not the latest.

@jordanbtucker thank you for your support on this thread - much appreciated 👍 ❤️ 

I'm pushing a release that upgrades chokidar directly - though most users should get the dep upgrade automatically as it pulls chokidar@^2.1.0

**Comment by jordanbtucker** [comment]
@d4rth-v4d3r I installed your dependencies. I was able to get it working by reinstalling nodemon.

```
npm uninstall --save-dev nodemon
npm install --save-dev nodemon
```

Since nodemon is the only dependency that requires chokidar@2.1, chokidar@2.1 will also get reinstalled at the latest version. Note that this is different than `npm update nodemon` as that won't necessarily update chokidar, at least not until remy bumps the chokidar dependency in nodemon.

**Comment by d4rth-v4d3r** [comment]
@remy I revert from version 1.18.10 to 1.18.0 because it was not working

**Comment by victorblq** [comment]
I'm having this issue with 1.19.0, windows 10 64bits also.

**Comment by jordanbtucker** [comment]
@victorblq What do you get when you run this?

```
npm ls | findstr "chokidar"
```

I just want to rule out whether it's an issue with chokidar.

**Comment by victorblq** [comment]
@jordanbtucker this:
```
$ npm ls | findstr "chokidar"
  +-- chokidar@2.1.6
```

**Comment by jordanbtucker** [comment]
Thanks. How about this?

```
npx cross-env DEBUG=nodemon nodemon -V -w dir dir
```

Replace `dir` twice with the name of the directory you want to watch.

**Comment by victorblq** [comment]
I'm following an expressjs tutorial, if I run:
```
yarn start
```
it works, but not refresh with code changes (this original issue)
and when I run with yout snippet, replacing "dir" with "src", that in my case contains a index.js file, I get this: 

```
$ npx cross-env DEBUG=nodemon nodemon -V -w src src
npx: instalou 10 em 1.335s
  nodemon bus new listener: reset (0) +0ms
  nodemon bus new listener: reset (0) +1ms
  nodemon bus new listener: quit (0) +8ms
  nodemon bus new listener: quit (0) +0ms
  nodemon bus new listener: restart (0) +0ms
  nodemon bus new listener: restart (0) +0ms
  nodemon bus new listener: reset (2) +3ms
  nodemon bus emit: reset +1ms
  nodemon resetting watchers +0ms
  nodemon reset +0ms
  nodemon config: dirs [ 'C:\\Users\\victo\\Workspaces\\express\\src' ] +0ms
[nodemon] 1.19.0
[nodemon] to restart at any time, enter `rs`
  nodemon bus new listener: error (0) +44ms
  nodemon bus new listener: error (0) +0ms
[nodemon] or send SIGHUP to 16560 to restart
[nodemon] watching: C:\Users\victo\Workspaces\express\src/**/*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node src`
[nodemon] forking
  nodemon fork C:\Windows\system32\cmd.exe /d /s /c node src +0ms
[nodemon] child pid: 18212
  nodemon bus new listener: exit (0) +8ms
  nodemon bus new listener: exit (0) +0ms
  nodemon start watch on: [ 'src', re: /src/ ] +1ms
  nodemon start watch on: C:\Users\victo\Workspaces\express\src +53ms
  nodemon ignored [
  '**/.git/**',
  '**/.nyc_output/**',
  '**/.sass-cache/**',
  '**/bower_components/**',
  '**/coverage/**',
  '**/node_modules/**',
  re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/
] +0ms
  nodemon watch is complete +37ms
[nodemon] watching 1 file
C:\Users\victo\Workspaces\express\src\index.js:1
import express from 'express';
       ^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by jordanbtucker** [comment]
This looks like a different issue since it's actually watching the file:

```
[nodemon] watching 1 file
```

The error you're getting is because it needs to be transpiled with something like babel.

Try this:

```
npx cross-env DEBUG=nodemon nodemon -V -w src --exec babel-node src
```

**Comment by shahidfoy** [comment]
I had the same issue Windows 10, for whatever reason nodemon wont run on some of my projects,

here's a duck-tape work around, ask npm to run a nodemon script in package.json
`
"scripts": {
    "dev": "nodemon server"
  },
`

then just run `npm run dev`
currently works for me

**Comment by jordanbtucker** [comment]
@shahidfoy Just running `nodemon` will run the global install of nodemon. You can find out what version that is by running `npm ls -g nodemon`. Running `npm run dev` will run the version of nodemon installed in `node_modules`. That's probably why you're seeing different behavior.

**Comment by Charlotte000** [comment]
I had the same problem on win 7. The issue was founded accidentally. My solution wa adding C:\Windows\System32\ to the system variable in the PATH.

**Comment by jhonissongabriel** [comment]
This work with me!


npm install -g nodemon

npm install --save-dev nodemon

npm config get prefix

set PATH=%PATH%;C:\Users\"Your User"\AppData\Roaming\npm;

Source:
https://cursos.alura.com.br/forum/topico-nao-consigo-instalar-o-nodemon-23149

**Comment by bernarddoci** [comment]
You should run PowerShell as administrator then:
`**PS C:\WINDOWS\system32>** Set-ExecutionPolicy RemoteSigned`
and press A

**Comment by deepak-singh343** [comment]
> I had the same problem on win 7. The issue was founded accidentally. My solution was adding C:\Windows\System32\ to the system variable in the PATH.

it also worked for me in windows 10 64bit

**Comment by fpsantos86** [comment]
I'm having the same problem, can you help me please??? How can i solve it???

**Comment by deepak-singh343** [comment]
add C:\\Windows\System32\ in your path in envrionment variable

**Comment by fpsantos86** [comment]
> @remy sorry for the delay - I've just set up a simple package with nothing but nodemon and the [basic "hello world" app.js](https://nodejs.org/en/docs/guides/getting-started-guide/) file. I'm using nodemon as a dev dependency, and my `yarn start` is set to `nodemon app.js`.
> When I start it, I get the usual message:
> 
>  ⨯ Lemuel Cushing@CUTHBERT  C\..\nodemon_test  yarn start
> yarn run v1.13.0
> $ nodemon app.js
> [nodemon] 1.18.10
> [nodemon] to restart at any time, enter `rs`
> [nodemon] watching: *.*
> [nodemon] starting `node app.js`
> Server running at http://127.0.0.1:3000/
> When I make a change to app.js and save it, I get
> `[nodemon] restarting due to changes...`
> Which just hangs.
> 
> If I add the -V flag, the follwing is displayed:
> 
>  Lemuel Cushing@CUTHBERT  C\..\nodemon_test  yarn start
> yarn run v1.13.0
> $ nodemon -V app.js
> [nodemon] 1.18.10
> [nodemon] to restart at any time, enter `rs`
> [nodemon] or send SIGHUP to 34116 to restart
> [nodemon] watching: *.*
> [nodemon] watching extensions: js,mjs,json
> [nodemon] starting `node app.js`
> [nodemon] forking
> [nodemon] child pid: 10640
> [nodemon] watching 3 files
> Server running at http://127.0.0.1:3000/
> And after I save a change:
> 
> [nodemon] files triggering change check: app.js
> [nodemon] matched rule: **\*.*
> [nodemon] changes after filters (before/after): 1/1
> [nodemon] restarting due to changes...
> [nodemon] app.js
> 
> [nodemon] files triggering change check: app.js
> [nodemon] matched rule: **\*.*
> [nodemon] changes after filters (before/after): 1/1
> [nodemon] restarting due to changes...
> [nodemon] app.js

@LemuelCushing Can you solve it??? 

Send me a message to fpsantos86@hotmail.com, if you can please

**Comment by fpsantos86** [comment]
> Can you all retest with nodemon@1.18.10 - it might fix the issue you were seeing.
> 
> Otherwise, since there's been no interest in finding the source of the issue on this thread, I'll close it in a few days.

@remy I retested it but when I update the file and make a new request I get the previous result, even with the nodemon running.

Note: I started getting this problem with the latest version of the nodemon: 2.0.2

**Comment by fpsantos86** [comment]
@remy 

It seems that this problem has returned, the nodemon even runs the application, but after I change a file and save the request executed by Insomnia (a program like the postman) it returns the same value as before.

BEFORE CHANGING THE NORMAL EXECUTE FILE:
![image](https://user-images.githubusercontent.com/1225727/74894838-d992b580-536e-11ea-8a40-c6ae5b33733b.png)

NOTICE THAT AFTER I CHANGE FROM "CLÁUDIO" TO "ROBSON" THE ANSWER IN INSOMNIA:
![image](https://user-images.githubusercontent.com/1225727/74894909-fe872880-536e-11ea-94e1-ad1a17e02672.png)

Help me please. I've searched a lot on the internet but I think this is the right place.

**Comment by copiyot** [comment]
https://github.com/remy/nodemon/issues/1619#issuecomment-544145862 .... That link has the answer.

**Comment by postoyevstanislav** [comment]
1. Start Windows PowerShell with the "Run as Administrator" option. Only members of the 
    Administrators group on the computer can change the execution policy.

2. Enable running unsigned scripts by entering:

   set-executionpolicy remotesigned
