### ISSUE TITLE
Snyk Issue chownr

### ISSUE THREAD

**Issue by ruipaulo** [remy/nodemon#1502]
- `nodemon -v`: 1.18.9

After updating nodemon to 1.18.9 I get a snyk warning about chownr (https://app.snyk.io/vuln/npm:chownr:20180731). I am not sure if this is relevant to you, but I did not find any issues related to it, so I just wanted to let you know.

The issue surfaced only because I had nodemon installed as a dependency instead of a devDependency, so it might not be urgent.

**Comment by remy** [comment]
The PR needs to be on the `tar` module (having just run through snyk's tree of vulns), but currently there's no resolution for the vulnerability as per https://snyk.io/vuln/SNYK-JS-CHOWNR-73502

However, there's a full explanation here https://github.com/isaacs/chownr/issues/14#issuecomment-451543037 so I'm not sure what @snyk needs to do on that particular reported vulnerability.

**Comment by lirantal** [comment]
Snyk addressed the vulnerability report and maintainer's comments on the issue.
Upgrading to chownr version >= 1.1.1 should not report any vulnerabilities with chownr.
