### ISSUE TITLE
VSCode debugging setup with nodemon and docker

### ISSUE THREAD

**Issue by marcospgp** [remy/nodemon#1505]
I was setting up VSCode debugging with nodemon and docker and it wasn't working properly.

I noticed my start command was `./node_modules/.bin/nodemon --legacy-watch --inspect=0.0.0.0:9222 --nolazy --ignore public/` instead of `./node_modules/.bin/nodemon --legacy-watch --inspect=0.0.0.0:9222 --nolazy --ignore public/ app.js` (note the missing file name at the end).

This fixed the problem and it now works just fine.

This is the output I got with the wrong command:

```
web_1            | [nodemon] starting `node app.js --inspect=0.0.0.0:9222`
web_1            | ✓ App is running at http://localhost:8080 in development mode
```

and this is the output I get with the right command:

```
web_1            | [nodemon] starting `node --inspect=0.0.0.0:9222 --nolazy app.js`
web_1            | Debugger listening on ws://0.0.0.0:9222/d6b49a0a-5a45-4ee6-937d-d92e538584f6
web_1            | For help see https://nodejs.org/en/docs/inspector
web_1            | ✓ App is running at http://localhost:8080 in development mode
```

My impression is that the wrong command shouldn't even work, and I'm not sure where nodemon could be getting the `app.js` filename from.

_Originally posted by @marcospgp in https://github.com/remy/nodemon/issues/1503#issuecomment-454475600_

**Comment by remy** [comment]
So, if I parsed your issue correctly, I _think_ you're filing two issues:

1. Running nodemon without a script argument you didn't expect it to work
2. Running nodemon without a script argument isn't parsing and passing all the command line args to node `--nolazy` specifically.

To answer:

1. This is intended behaviour to mirror now node works. nodemon will read your package.json file and look for `main` entry (and then I think the `npm start` entry - I thought this was documented but I can't find it).
2. This looks like a bug that should be reasonably straightforward to replicate.

However, before I address (2) can you confirm the questions that were in the issue originally? node version, nodemon version, OS, etc (you deleted them so you can see the prompts from a new issue).

**Comment by marcospgp** [comment]
I'll give you that information today, thanks for the feedback!

I didn't delete the issue template, it never appeared since I created this issue from a comment. 

Cheers!

**Comment by marcospgp** [comment]
- `nodemon -v`: 1.17.4
- `node -v`: 8.9.4
- Operating system/terminal environment: Windows 10
- Using Docker? What image: `node:8.12.0-alpine` with `mongo:4.0`

**Comment by remy** [comment]
Can you upgrade to the current and supported version of nodemon - and retest.

**Comment by marcospgp** [comment]
Oops, my bad, that is the version of my global installation of nodemon, but this happens with the local installation which is `^1.18.7` (in `package.json`)
