### ISSUE TITLE
The first time you quit the app and it doesn't take effect when you use restart.

### ISSUE THREAD

**Issue by FishOrBear** [remy/nodemon#1506]
ver :"nodemon": "^1.18.9"

When the first reboot fails, using restart again will restart correctly.

The example is like this:
```
const nodemon = require('nodemon');
nodemon("dev2.js")
    .on("exit", () =>
    {
        console.log("Try Restart");
        nodemon.restart();
    });

```

dev2.js
```
console.log("Start");
process.exit();
```

**Comment by remy** [comment]
Not sure what you're trying to do. Not sure you need to call nodemon.restart… can you explain?

**Comment by FishOrBear** [comment]
I want to automatically restart when the app exits.

**Comment by remy** [comment]
Is this a graceful exit you're trying to restart on?

**Comment by FishOrBear** [comment]
yes
