### ISSUE TITLE
fs.writeFileSync causes Nodemon to continuously restart

### ISSUE THREAD

**Issue by clockworkpc** [remy/nodemon#1509]
- `nodemon -v`: 1.18.9
- `node -v`: 10.15.0
- Operating system/terminal environment: Pop OS (Ubuntu 18.04)
- Using Docker? What image: N/A
- Command you ran: `nodemon json.js`
- Editing the file inside Atom.  Tried using gedit as well and behaves the same way.

### NOTE
I can confirm that this bug first appears in v1.18.6.
WHERE nodemon version =< 1.18.5, no bug.
WHERE nodemon version >= 1.18.6, this behaviour is reproducible.

### Expected behaviour
Nodemon runs the JS file once.

### Actual behaviour
Nodemon continuously restarts even though I am not editing the file.

### Steps to reproduce
Created a file called `json.js` and started nodemon

```
$ nodemon --verbose json.js
[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 13097 to restart
[nodemon] watching: *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node json.js`
[nodemon] forking
[nodemon] child pid: 13110
[nodemon] watching 2 files
[nodemon] clean exit - waiting for changes before restart

```
Wrote the following code:

```
const fs = require( 'fs' );

var originalNote = {
  title: 'Some title',
  body: 'Some body'
};

var originalNoteString = JSON.stringify( originalNote );
//fs.writeFileSync( 'notes.json', originalNoteString );

```

Saved the file; it worked as expected.

Then, I uncommented the line and saved the file:
`//fs.writeFileSync( 'notes.json', originalNoteString );`

And got an unending stream of restarts:

```
[nodemon] starting `node json.js`
[nodemon] forking
[nodemon] child pid: 13659
[nodemon] files triggering change check: notes.json
[nodemon] matched rule: **/*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] notes.json

[nodemon] starting `node json.js`
[nodemon] forking

[nodemon] child pid: 13669
[nodemon] files triggering change check: notes.json
[nodemon] matched rule: **/*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] notes.json

[nodemon] starting `node json.js`
[nodemon] forking
[nodemon] child pid: 13678
[nodemon] files triggering change check: notes.json
[nodemon] matched rule: **/*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] notes.json

[nodemon] starting `node json.js`
[nodemon] forking
[nodemon] child pid: 13688
[nodemon] files triggering change check: notes.json
[nodemon] matched rule: **/*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] notes.json

[nodemon] starting `node json.js`
[nodemon] forking
[nodemon] child pid: 13700
[nodemon] files triggering change check: notes.json
[nodemon] matched rule: **/*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] notes.json
```
etc.

As soon as comment that same line, the behaviour stops: `//fs.writeFileSync( 'notes.json', originalNoteString );`

One especially strange thing is if I call the file `notes.txt` nodemon behaves normally, but as soon as I call it `notes.json`, it continuously restarts. 
It doesn't matter what the file basename is, or what the JS file is called.  If it includes `fs.writeFileSync` and the file to be written to is `.json`, nodemon will restart ad infinitum.

---

**Comment by remy** [comment]
Your issue title says *read* but the issue itself is about writing.

If indeed it's writing, then yes, if you write to files that nodemon is watching for changes it will restart.

nodemon watches js and JSON by default iirc. So if you start it with `--ext js` it should only watch JavaScript and not JSON.

**Comment by clockworkpc** [comment]
> Your issue title says _read_ but the issue itself is about writing.

Sorry, my mistake.

> If indeed it's writing, then yes, if you write to files that nodemon is watching for changes it will restart.

But my issue is that it was restarting even when I was NOT writing to the file.
Until version 1.18.5, nodemon restarts only when I write to the file.
From version 1.18.6 nodemon restarts continuously even when I do not write to the file. 

> nodemon watches js and JSON by default iirc. So if you start it with `--ext js` it should only watch JavaScript and not JSON.

But in the example I gave, it makes no sense that nodemon should restart continuously when I am not writing to the file at all.  And if my code relies on reading JSON, it makes sense that nodemon should watch that too -- as long as it restarts only when there is a change to the file, not ad infinitum.

**Comment by remy** [comment]
Obviously I based my response on your writing a file. You're right it shouldn't restart on read - obviously that's not intended behaviour.

Can you update your original issue - I'm suspecting this is to do with Ubuntu as I can't replicate on my Mac.

I'll see if I can get something together to help test to narrow down the issue.

**Comment by clockworkpc** [comment]
Here is a demonstration of the difference in behaviour from 1.18.5 to 1.18.6.
https://youtu.be/7JNR-gBLrZc

**Comment by remy** [comment]
On reflection - this isn't actually a bug, this is intended behaviour.

You've got a race condition:

1. nodemon watches js, json, etc
2. nodemon starts your script
3. your script writes to json
4. nodemon restart - goto (1)

**Comment by JusticeBringer** [comment]
I suggest looking at [this answer](https://stackoverflow.com/a/38362633/11322237).

In case the url will not work, I copy-paste the answer here:

Add the name/s of the file/s you're creating to a file called `nodemon.json`, and place it at the root of your working folder:

`{
  "ignore": ["*.test.txt", "myfiles/*"]
}` 

In my case, I created a file `nodemon.json` where I wrote this:

`{
  "ignore": ["messages.json"]
}`

**Comment by yossi-ka** [comment]
k
