### ISSUE TITLE
Accept a nodemon.js config file

### ISSUE THREAD

**Issue by DanielHoffmann** [remy/nodemon#1510]
Currently nodemon only accepts a nodemon.json config file, several tools have been moved to accept dynamic .js files for configuration as well (eslint, prettier, jest).

Rationality:
I have several projects that I want to share tooling configuration, so I moved all that configuration to an npm dependency, for example, the `.eslintrc.js` file in my project looks like this:

```
module.exports = require('mytooling-config').eslint;
```

my `.prettierrc.js` file looks like this:

```
module.exports = require('mytooling-config').prettier;
```

and so on

Supporting dynamic .js config files has been a standard way for tooling to behave for a while now and it is quite odd that nodemon does not support this, nodemon requires static nodemon.json configuration making sharing nodemon configuration in this manner impossible. Any way I can think of to share nodemon configuration would be very ugly (like a npm `prestart` script to copy `node_modues/mytooling-config/nodemon.json` to the root of the project)

Dynamic nodemon configs might have other uses as well besides my use-case. For example someone might want to watch some files but not others based on something more complex than a regex.

**Comment by remy** [comment]
These configs are also dotfiles whereas the nodemon.json is not - happy to take a PR to support this feature (with tests). 

I think there is a broader issue about having a file called `nodemon.js` in the root of a directory which doesn't read as a config file. 

Feel free to discuss.

**Comment by DanielHoffmann** [comment]
@remy Thanks for the reply! So prettier uses this lib called cosmiconfig:
https://github.com/davidtheclark/cosmiconfig
apparently it handles all the searching of configuration. I will try to come up with a PR during this weekend.
Are you okay with using it? Anything I should watch out? Of course I would keep support for `nodemon.json` on top of the default ones from cosmiconfig:

```
[
  'package.json',
  `.${moduleName}rc`,
  `.${moduleName}rc.json`,
  `.${moduleName}rc.yaml`,
  `.${moduleName}rc.yml`,
  `.${moduleName}rc.js`,
  `${moduleName}.config.js`,
]
```

From a quick glance of the codebase, I only need to change this file:
https://github.com/remy/nodemon/blob/master/lib/config/load.js
correct?

**Comment by remy** [comment]
/lib/config/load.js is correct for the only place the config is read.

I'm not 100% sure about cosmiconfig - I'm just wary of dependencies that I bring in to the project, and just for the yml support it'll bring in Esprima, which seems excessive...

I could be convinced - I think it makes a lot of sense to support a wide number of filenames out of the box if it's supported (as per {name}rc, {name}rc.json, {name}rs.js, etc)…

**Comment by DanielHoffmann** [comment]
Prettier uses cosmiconfig and prettier is becoming near-ubiquitous. The nodemon repo itself is already using esprima through a peer-dependency somewhere:

```
nodemon git:(master) cat node_modules/esprima/package.json | grep \"version\"
    "type": "version",
  "version": "2.7.3"
```

I am trying to trackdown what eslint uses, it doesn't look like it uses cosmiconfig, but I am not sure what they use instead or if they manually check all the files.

It is up to you, I can do it either way, but I feel using a battle-tested lib would be less bugprone.

**Comment by remy** [comment]
Esprima is being used in nodemon via devDeps (i.e. users don't receive it).

I'm really on the fence at the moment:

- Upside: like you said, battle tested dep is good - more exposure to edge cases, more issues raised (on cosmiconfig) - i.e. positive factor
- Downside: brings a lot of deps along for the ride to support a very wide range of configuration types

There's more pros and cons than that, but those are the two strongest. I'm giving this some thought, and I suspect I'll fall on the side of _not_ including a new dep to solve this, but give me a day to think about it (equally - jump in with your own thoughts).

**Comment by remy** [comment]
Having given it some thought, I think I prefer to keep the dependency count down when I can, so if you're happy to manually implement the additional config support, I'd be happy to add it in.

I'm happy for you to mirror the cosmiconfig file types (excluding yaml - and perhaps the `.config.js` one). One thing you'll need to check and maintain is if the global (at `$HOME` level) config is _merged_ with the local config or not.

I _think_ it is merged, i.e. it's used as fallback defaults. But I'm not 100% sure I remember!

**Comment by lonix1** [comment]
@DanielHoffmann Did you manage to work up something for this?

**Comment by DanielHoffmann** [comment]
@lonix1 it is on my todo list. I have to do this on my spare time unfortunately, so I can't promise when I will be able to get around doing it.
If you want to take on the PR please feel free to do so, but let me know first :)

**Comment by lonix1** [comment]
@DanielHoffmann I wouldn't know where to start :) I'm using a workaround for now, but then again my use case is simpler/different to yours.

**Comment by fguille94** [comment]
has anyone been able to PR a fix for this yet?
I am in need of using dynamic `.env` files depending on some functions and I can't use `.json` for the nodemon config!
