### ISSUE TITLE
Never receiving SIGUSR2 signal on Windows

### ISSUE THREAD

**Issue by scott-boe** [remy/nodemon#1514]
- `nodemon -v`: v1.18.9
- `node -v`: v8.12.10 and v10.15.1
- Operating system/terminal environment: Windows Server 2008 SP1, Windows 7 Enterprise SP1, Windows 10
- Command you ran: `nodemon test.js`

### Expected behaviour
Listening to SIGUSR2 allows us to listen to when Nodemon restarts our process.

### Actual behaviour
That signal is never detected.

### Steps to reproduce
Run `nodemon` on:

```javascript
process.once('SIGUSR2', graceful_shutdown)
process.once('SIGTERM', graceful_shutdown)

console.log('Listening to process signals.')

// Don't clean exit.
setInterval(() => {}, 10000)

function graceful_shutdown() {
  console.log('Detected shutdown / restart.')
  process.exit(0)
}
```

**Comment by MystK** [comment]
I am also running into this issue. I want to catch when nodemon is restarting my process so I can gracefully shutdown. I see this has been an issue for over 5 years ago in a previous ticket, #140. Does anyone have any solutions?

**Comment by ChristianIvicevic** [comment]
Please refer to #1567 with a suggestion on how to enable SIGUSR2 handling for Windows.

**Comment by cope** [comment]
@ChristianIvicevic, I looked at #1567 but I see no solution there, only that it has been closed after many people bumped it.

I am currently having the same issue on Windows no signal, no matter what :(

I tried --signal with SIGNIT, with SIGTERM and with SIGUSR2 - nothing :(
