### ISSUE TITLE
When using `--no-stdin` and subproc quits, no way to exit

### ISSUE THREAD

**Issue by remy** [remy/nodemon#1516]
- `nodemon -v`: 1.18.9
- `node -v`: v10.14.1
- Operating system/terminal environment: OSX 10.13.6
- Command you ran: nodemon -I nodemon-issue.js

### Expected behaviour

When the child process has exited, stdin should be handed back to nodemon so that `ctrl-c` works.

### Actual behaviour

Cannot exit nodemon. Also hoses the ctrl-c on terminal (in zsh certainly).

### Steps to reproduce

Run [this script](https://gist.github.com/remy/0176433eb50c89a7ee78c95460536dbb) - requires blessed dep.

**Comment by remy** [comment]
Muppet. That works now.

Not sure how.

**Comment by OoDeLally** [comment]
Any way to have this work? :pray:
