### ISSUE TITLE
Nodemon restarts when a file located in an ignored directory changes.

### ISSUE THREAD

**Issue by aprilmintacpineda** [remy/nodemon#1517]
- `nodemon -v`:
- `node -v`:
- Operating system/terminal environment: 
- Using Docker? NO
- Command you ran: nodemon build/server.js --ignore build/static/

### How I do it

I have my frontend and backend together on the same project. Backend is using express-js. Frontend is using inferno-js. First I run `webpack-dev-server` which builds, watches, and serves the frontend on localhost:3000. Then I run `node ./node_modules/@babel/cli/bin/babel.js src-server --out-dir build`. Note that the building for the frontend and backend are separate, with frontend using webpack and backend only babel. Frontend and backend are inside different directories, `build/src-front`, `build/src-back` but when built, goes to the same directory `root/build` BUT the frontend codes are always in `build/static`.

Express serves the files, that's how I used to develop at first, but every time I make changes to the frontend codes, the server has to restart, which basically clears the session. I'm using express-session with connect-redis.

So I separated the frontend and backend during development, I used webpack-dev-server to serve the frontend and separately start another server for the backend. Then I ignored `build/static/`, so that when a frontend file changes, nodemon wouldn't have to restart (at least that's my assumption). Still after editing my frontend codes, it still restarted.

I also tried doing `nodemon src-server/server.js` which now, uses the *unbuilt* files. Still after editing the frontend codes, nodemon restarted again.

I've tried all that I could to figure out what's going on, after so many tries, still no good outcome.

**Comment by remy** [comment]
Can you provide some working code to test with?
