### ISSUE TITLE
Ubuntu Installation Warnings of Nodemon

### ISSUE THREAD

**Issue by rkishan516** [remy/nodemon#1518]
When I installed the Nodemon Package in Ubuntu 18.04 then Two warnings comeup to my terminal window.
These Warning are because of fsevent dependencies which is for OS X.

Warning :- 
1. Skipping failed optional dependency /nodemon/chokidar/fsevents
2.  Not compatible with your operating system or architecture: fsevents@1.2.7
![screenshot from 2019-02-02 17-52-05](https://user-images.githubusercontent.com/34465683/52164182-6d1d2800-2713-11e9-958b-a38df77a3a99.png)

**Comment by remy** [comment]
These are just warnings from a sub dep. Nothing to worry about.
