### ISSUE TITLE
Send Message Via Nodemon

### ISSUE THREAD

**Issue by nahtnam** [remy/nodemon#1519]
- `nodemon -v`:1.18.9
- `node -v`:10.14.2
- Operating system/terminal environment: MacOS High Sierra
- Using Docker? What image: No
- Command you ran: Used `required` version of nodemon

So I have a weird/interesting use case of nodemon. I want to conditionally restart the server (which is possible), however the times I don't want to restart the server, I would like to send a message/event to the child process/instance of my code.

### Expected behaviour
I have looked at the docs and skimmed through the source code, I don't think its possible.

### Actual behaviour
Nothing happens

### Steps to reproduce
Here is the code I use:

```js
const server = nodemon({
  watch: ['src'],
  ext, // assume .js
  ignore: [path.join(cwd, `./src/routes/**/*.${ext}`)], // i am excluding this folder so I can conditionally restart
  exec, // node src/index.js
});

// this is fine
server.on('start', function () {
  console.log('nodemon started');
}).on('crash', function () {
  console.log('script crashed for some reason');
}).on('restart', () => {
  console.log('nodemon is restarting')
})

chokidar.watch(
  path.join(cwd, './src/routes', `**/*.js`),
  {
    ignored: /(^|[\/\\])\../, // ignore dot files
  }
).on('change', (path) => {
  if (something) {
    nodemon.restart(); // great
  } else {
    nodemon.send('message', 'dont restart but do this'); // UNIMPLEMENTED/HOW DO I DO THIS?
  }
});
```

One possible solution is to give access to the child_process that nodemon opens up.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by nahtnam** [comment]
Bump!

**Comment by remy** [comment]
By "send message" - can you be more specific? What exactly do you want to send?

**Comment by nahtnam** [comment]
@remy Kind of like emitting events to a child process. https://medium.com/@NorbertdeLangen/communicating-between-nodejs-processes-4e68be42b917 Something like this but the events should go to my server such that I can tell it to hot swap the module instead of restarting

**Comment by nahtnam** [comment]
Bump!

**Comment by nahtnam** [comment]
@remy Any thoughts on this issue?

**Comment by remy** [comment]
Your original reply didn't really answer my question.

> nodemon.send('message', 'dont restart but do this'); // UNIMPLEMENTED/HOW DO I DO THIS?

nodemon supports postMessage for RPC, but your slim example is two things: 1) don't restart, 2) "this"

What is "this" supposed to be. Can you provide an example of exactly what you would like to do?

**Comment by nahtnam** [comment]
@remy 

Sorry for the late response. So here is my use case: I am working on a "framework"/library for my app where it will hot-swap certain modules so the server doesn't have to restart (boot-time is a few seconds) only in development mode. I would however like to use `nodemon` to restart the server if any of the files that are not in that specific folder change.

Here is how I start the server in my CLI program:

```js
const server = nodemon({
  watch: ['src'],
  ext, // assume .js
  ignore: [path.join(cwd, `./src/routes/**/*.${ext}`)], // i am excluding this folder so I can conditionally restart
  exec: 'node src/index.js',
});
```

Notice how I ignore the routes folder. I then set up chokidar to watch the routes folder manually:

```js
chokidar.watch(
  path.join(cwd, './src/routes', `**/*.js`),
  {
    ignored: /(^|[\/\\])\../, // ignore dot files
  }
).on('change', (path) => {
  if (shouldFullyRestartServer) {
    nodemon.restart(); // great
  } else {
    # HERE
  }
});
```

Where it says HERE, I want to tell the child process which is running `node src/index.js` to emit a "swapModule" event or something which would trigger the child app to swap out the modules.

Maybe there is a simpler solution that I can't see, but basically, I would like the ability for the parent process running nodemon via script to be able to send messages to the child process that nodemon starts.

Thanks!

**Comment by remy** [comment]
Okay, I can follow your code example. You want to push the message directly into the child but it needs to go via nodemon. I think I can see how that would work.

I'll have to come back to you (though the stalebot will keep trying to close this issue - sorry!)

**Comment by nahtnam** [comment]
Hey!

Thank you! I think the opposite should also work (and I might need it for that specific use case). If the child emits an event, nodemon could capture it and add a "event" hook or something that the parent can listen on.

Thanks,
@nahtnam

**Comment by nahtnam** [comment]
bump!

**Comment by nahtnam** [comment]
Bump (because it looks like there is some progress being made).

Unfortunately I don't need this feature anymore (I ended up with a better solution) but hopefully, someone finds this useful. Thank you!
