### ISSUE TITLE
nodemon stuck at restarting

### ISSUE THREAD

**Issue by CHENXINNN** [remy/nodemon#1520]
I am pretty sure it has something to do with the system environment path variable since I encoutered this propblem after I mistakenly delete some  environment path variable. But I don't know how to fix it.

- `nodemon -v`: 1.18.9
- `node -v`: 10.15.1
- Operating system:  win7 

### Actual behaviour
![image](https://user-images.githubusercontent.com/45284685/52177680-a7fc8a00-27ff-11e9-817c-5528c097ddb0.png)

**Comment by dobesv** [comment]
Can you provide the contents of `app.js` or some simplified version of it that shows the problem?  Are you sure `app.js` isn't changing any files on startup?  Have you tried running `nodemon` in verbose mode to see if it tells you what file it thinks has changed?

**Comment by deveshsinghal22** [comment]
This is happening with me as well. I will share a my app.js
