### ISSUE TITLE
make --delay to wait until it checks if file exists

### ISSUE THREAD

**Issue by ArtDesire** [remy/nodemon#1521]
I use a concurrently script that builds and runs nodemon with --delay. the problem is delay makes no sense in my case as it runs npm:start right away since the file it needs to run is not yet compiled.
Delay is not present on the initial nodemon start but only after file change is detected.

### Expected behaviour
run specified script after specified delay

### Actual behaviour
runs npm:start if specified script does not exist on run no matter if delay option is present

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
You're going to need to provide a parred down example, as I don't really follow what you're trying to do.

**Comment by remy** [comment]
This issue doesn't have much detail, but if you use nodemon as a required module, you can control when it restarts (…I think). Closing for now.

**Comment by pasan9** [comment]
Any updates on this?

Right now I'm using a work around like

`mkdir -p dist && touch ./dist/app.js && nodemon --watch ./dist ./dist/app.js`

Creating an empty file. This removes the error, but is not the right solution.
