### ISSUE TITLE
Nodemon is not starting

### ISSUE THREAD

**Issue by WaseemAhmadNaeem** [remy/nodemon#1524]
- `nodemon -v`: 1.18.10
- `node -v`: 10.15.0
- Operating system/terminal environment: Window 10 x64
- Using Docker? What image: 
- Command you ran: `nodemon index.js`

### Expected behaviour

Server started and start serving

### Actual behaviour

Stuck at [nodemon] starting 'node index.js'

### Steps to reproduce

nodemon index.js
---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

###Code in Index.js
```
var express = require('express')
var app = express();


app.get('/',(req,res)=>{
    res.send('Hello World');
});

app.listen(3000);`
``

**Comment by remy** [comment]
Are you able to share a screen of what you're seeing?

**Comment by remy** [comment]
Dupe of #1520
