### ISSUE TITLE
File changes not picked up by nodemon when rsync or scp'd 

### ISSUE THREAD

**Issue by STLMikey** [remy/nodemon#1526]
Bumping the chokidar version in this commit: https://github.com/remy/nodemon/commit/fb0c078 causes nodemon to no longer restart when files it is watching are changed via rsync or scp (at least when run via docker)

- `nodemon -v`: 1.18.10
- `node -v`: 10.6.0
- Operating system/terminal environment: Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-139-generic x86_64)
- Using Docker? What image: node:10-slim
- Command you ran: nodemon server.js

### Expected behaviour
When running nodemon in docker (without docker is untested), nodemon should restart when files it is watching are changed via "rsync'd" or "scp'd"

### Actual behaviour
Nodemon no longer restarts when files it is watching are changed via rsync or scp

### Steps to reproduce
    clone following repo to /path/on/machine
        git clone https://github.com/STLMikey/node-debug.git /path/on/machine

    cd /path/on/machine && docker build -t debugimage . && docker run -it --rm --name debug -v /path/on/machine/app/example:/usr/src/app/example debugimage

    echo "console.log('modified from rsync');" > /different/path/app/example/example.js

    echo "console.log('modified directly');" > /path/on/machine/app/example/example.js
        notice nodemon restarts example.js as expected

    rsync -azP --force /different/path/* /path/on/machine
        notice nodemon does not restart example.js, despite file contents changing

**Comment by michaelgmcd** [comment]
Seeing this is as well. Tried the `-L` with no luck.

**Comment by STLMikey** [comment]
@michaelgmcd a temporary workaround is to include `"chokidar": "2.0.4"` as a direct dependency to your project

**Comment by michaelgmcd** [comment]
@remy This is definitely still an issue. Not sure what the next steps are, just following the bot's instructions :)

**Comment by remy** [comment]
@michaelgmcd did you try debugging it and get anywhere?

**Comment by SvanT** [comment]
It seems to work when using the --inplace rsync flag, rsync does by default upload to a temp file and then rename it to make the replace atomic, so I guess nodemon is not picking up the inodes of the new files?
