### ISSUE TITLE
exit after test complete

### ISSUE THREAD

**Issue by converge** [remy/nodemon#1529]
- `nodemon -v`: 1.18.9
- `node -v`: v11.2.0
- Operating system/terminal environment: MacOS
- Using Docker? What image: 
- Command you ran:

```"test:backend": "nodemon --exec 'mocha -R min'"```

### Expected behaviour

Exit nodemon.

### Actual behaviour

```[nodemon] clean exit - waiting for changes before restart```

### Steps to reproduce

I'm running some tests using nodemon and mocka to test mongoDB especially, and I need it to exit() after test complete.

I'm using CI, and it waits for the test to completo, to advance for the next item on the pipeline to execute.

Is there some way to exit nodemon after my test completed?

This is my test:
```js
require('dotenv').config({ path: __dirname + '/../src/services/.env' })
const mongoose = require('mongoose').set('debug', true)

// enable ES6 for mongoose
mongoose.Promise = global.Promise;

before(function (done) {
  // connect
  mongoose.connect(process.env.MONGODB_TEST_SUITE, { useNewUrlParser: true, useCreateIndex: true })
  mongoose.connection.once('open', function () {
    console.log('MongoDB is connected!')
    done()
  }).on('error', (error) => {
    console.warn('MongoDB connection error:', error)
  })
})

beforeEach(function (done) {
  mongoose.connection.db.dropDatabase(function () {
    done();
  })
})
```

**Comment by remy** [comment]
Nodemon is designed to keep the process running and auto restart on changes. So this isn't really the intended use (to exit on sub process 0).

**Comment by converge** [comment]
I ended up using supertest lib for that with mocha:
```"test:api": "mocha --exit --timeout 5000 'test/apiTest.js'"```
