### ISSUE TITLE
Logging with nodemon

### ISSUE THREAD

**Issue by fuentecilla86** [remy/nodemon#153]
Hey everyone!

I am using console.log for loggin but it does not work with nodemon. It works when I started the server with node but not with nodemon.

I have been reading that it can be because of the version, but I have the 0.7,3 and it should work. Could anyone help me?

Thanks in advance!

**Comment by nainglinaung** [comment]
I also face with same issue, my code is as follow 

```
var express = require('express');
var path = require('path');
var app = express();

app.set('view engine','jade');
app.set('views', __dirname + '/views');

var db = require('./config')(app,express);
var base_url = path.normalize(__dirname+'/..');
console.log('hi');

app.use('/static', express.static(base_url+'/public/components'));
app.use('/public', express.static(base_url+'/public/custom'));


// seed 
/*
var seeds = require('./server/seeds/seeds');
seeds.set();
*/
// route 

var routes = require('./routes')(app);
var port = process.env.PORT || 8080;

app.listen(port);
console.log('magic happened at'+port);
```

and nodemon as follows

```
> nodemon ./server/index.js

23 Jan 18:23:01 - [nodemon] v1.2.1
23 Jan 18:23:01 - [nodemon] to restart at any time, enter `rs`
23 Jan 18:23:01 - [nodemon] watching: *.*
23 Jan 18:23:01 - [nodemon] starting `node ./server/index.js`
23 Jan 18:25:36 - [nodemon] restarting due to changes...
23 Jan 18:25:36 - [nodemon] starting `node ./server/index.js`
23 Jan 18:25:44 - [nodemon] restarting due to changes...
23 Jan 18:25:44 - [nodemon] starting `node ./server/index.js`
```

I currently working on OSX Yosemite, node verison is 1.0.4

**Comment by alanshaw** [comment]
I got the same problem with iojs v1.2.0 and nodemon v1.2.1. Upgrading to nodemon v1.3.7 fixed it for me.

**Comment by BenjaminConant** [comment]
@alanshaw thank for the answer ... I also had this issue, for me updating from `nodemon 1.2.1` to `nodemon 1.3.7` fixed it as well.

**Comment by nikitabanthiya** [comment]
can i use nodemon and foever together.. I used it but imnot able to see console.log
