### ISSUE TITLE
mac control +c  unable to kill process

### ISSUE THREAD

**Issue by yangchongduo** [remy/nodemon#1531]
- `nodemon -v`:    "nodemon": "1.18.10",

- `node -v`: v10.15.0 
- Operating system/terminal environment: 
- Using Docker? What image: 
- Command you ran:

```
 "start:dev": "nodemon",

nodemon.json
{
  "watch": ["src"],
  "ext": "ts",
  "ignore": [
    "src/**/*.spec.ts",
    "src/graphql.schema.ts"
  ],
   "env": {
     "NODE_ENV": "development"
   },
  "exec": "ts-node -r tsconfig-paths/register src/main.ts"
}

```

### Expected behaviour

mac control +c  unable to kill process
### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Please provide pared down example to replicate from
