### ISSUE TITLE
[Feature Request] Allow nodemon.json to include comments ("jsonc")

### ISSUE THREAD

**Issue by lonix1** [remy/nodemon#1532]
Please allow the `nodemon.json` config file to include comments. That means the `jsonc` standard.

Many modern tools allow this - because it is hard to maintain json files without being able to document them. Of all the config files I've got, I think most already allow this, including ts, angular, etc.

I assume/hope this is a simple matter of a config option on the json parser, or a newer parser.

**Comment by remy** [comment]
I'm not keen since it's not JSON, the configuration should be .js if it's going to support comments (there's a PR in the works for this, please feel free to contribute to that).

Otherwise I use "//": "some comment" in my JSON when I absolutely have to add a comment.

**Comment by lonix1** [comment]
I didn't realise the config supports `js`... is there an example somewhere I can look at?

**Comment by remy** [comment]
https://github.com/remy/nodemon/issues/1510
