### ISSUE TITLE
Restart count.

### ISSUE THREAD

**Issue by rickysullivan** [remy/nodemon#1533]
How can you check the number of times a script has been restarted?

I want to run a function in my `index.js` on start, but then if `restartCount > 0` then don't run it again.

**Comment by rickysullivan** [comment]
Surely the parent process would know.

**Comment by rickysullivan** [comment]
Unstale.

**Comment by remy** [comment]
Sorry, I never replied to this. Short version is you can't, but if you're using nodemon as a required module then you can manage this directly yourself (as a viable workaround).

Sounds good?

**Comment by rickysullivan** [comment]
Thanks for the reply. It does. I didn't see that section.
