### ISSUE TITLE
Additional argument leads to 'argument-mismatch'

### ISSUE THREAD

**Issue by alcero** [remy/nodemon#1538]
- `nodemon -v`: 1.18.10
- `node -v`: v11.9.0
- Operating system/terminal environment: Ubuntu 18.04.2 LTS
- Using Docker? What image: No
- Command you ran: nodemon index

### Expected behaviour
process.argv[0] = /home/(...)/bin/node
process.argv[1] = /home/(...)/index
process.argv[2] = undefined
process.argv[3] = undefined

### Actual behaviour
process.argv[0] = /home/(...)/bin/node
process.argv[1] = /home/(...)/index.js
**process.argv[2] = index.js**
process.argv[3] = undefined

### Steps to reproduce
console.log ("process.argv[0] = " + process.argv[0]);
console.log ("process.argv[1] = " + process.argv[1]);
console.log ("process.argv[2] = " + process.argv[2]);
console.log ("process.argv[3] = " + process.argv[3]);

---
My usecase: For missing arguments node should use a default value. By adding an argument this doeas not work properly developing with nodemon.

Thank you.

**Comment by remy** [comment]
As a workaround, you can use `nodemon ./index.js` - but I understand what you're seeing.

**Comment by remy** [comment]
Not stale
