### ISSUE TITLE
Cannot use node --require 

### ISSUE THREAD

**Issue by angry-dan** [remy/nodemon#1539]
- `nodemon -v`: 1.18.9
- `node -v`: 8.11.3
- Operating system/terminal environment: Mac
- Using Docker? What image: n/a
- Command you ran: webpack -dw

### Expected behaviour
```
[nodemon] starting `node --inspect --require dotenv/config ./dist/local-server.js`
```

### Actual behaviour
```
node: bad option: --require dotenv/config
[nodemon] starting `node --inspect "--require dotenv/config" ./dist/local-server.js`
[nodemon] app crashed - waiting for file changes before starting...
```

### Steps to reproduce

I'm using Node v8.11.3 with nodemon v8.11.3 and  nodemon-webpack-plugin:
```
    new NodemonPlugin({
      watch: "./dist/local-server.js",
      script: "./dist/local-server.js",
      nodeArgs: ["--inspect", "--require dotenv/config"],
    }),
```

The appropriate syntax for calling node with the require argument (https://nodejs.org/api/cli.html#cli_r_require_module) is `node -r modulename` or `node --require modulename` but it does not support an equals sign (`node --require=modulename`) and nor does it support wrapping the argument and value in quotes (`node "--require modulename"`)

Unfortunately, the `utils.stringify` function adds quotes to any argument that contains whitespace making it impossible to use this tool calling node with -r.

**Comment by trxcllnt** [comment]
@angry-dan pretty sure the `--require` and `dotenv/config` need to be separate elements in your array, like this: `nodeArgs: ["--inspect", "--require", "dotenv/config"]`

**Comment by angry-dan** [comment]
That's a good point, wish I'd thought of that at the time!
