### ISSUE TITLE
Nodemon restarts on writeFile in ignored directories

### ISSUE THREAD

**Issue by minotaurrr** [remy/nodemon#1543]
- `nodemon -v`: 1.18.9
- `node -v`: 10.15.3
- Operating system/terminal environment:  Windows 7
- Using Docker? What image: 
- Command you ran: nodemon --config nodemon.json

### Expected behaviour
Nodemon to not restart

### Actual behaviour
Nodemon restarts when a new file is created in the ignored directory

### Steps to reproduce
nodemon.json
```
{
    "verbose": true,
    "ignore": ["logs/*", "db/data/*", "dist/db/data/*"]
}
```

As soon as the code hits below nodemon restarts
```
        const stream = fs.createWriteStream(fileName);

        stream.once('open', fd => {
            stream.write(json);
            stream.end();
        });
```

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.
```
[nodemon] watching 414 files
[nodemon] 1.18.9
[nodemon] reading config .\nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 1892 to restart
[nodemon] ignoring: logs/**/* db/data/**/*
[nodemon] watching: *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node dist/main.js`
[nodemon] forking
[nodemon] child pid: 10656
[nodemon] watching 413 files

```

**Comment by remy** [comment]
Can you include the log line that shows what file is triggering the restart?

**Comment by danyweed952** [comment]
The same thing happens to me too, I can not get nodemon to ignore changes in the .json file,
try these confirmations :   "ignore": ["./Data/*.json", "Data/*", "*.json", "Data/data.json", "./Data/", "./**/*.json"]

**Comment by pconerly** [comment]
I'm also having problems ignoring a specific json file:
```
  "nodemonConfig": {
    "ignore": [
      "./src",
      "./config/webpack",
      "./build/manifest.json", /// this!
      "./build/public"
    ],
    "delay": "2500"
  },
```
And nodemon restarts when build/manifest is written anyway. `App restarted due to:  [ '/Users/peterconerly/code/secretdir/frontend/build/manifest.json' ]`

```
$ node -v
v8.12.0
$ ./node_modules/.bin/nodemon -v
1.18.11
```

**Comment by LeonDWong** [comment]
Same problem here. I'm using cli flag to ignore directory, but files in directory fire restart when they has been changed, specially, the directory is a `dist` directory which is created by build script. 
And it's weird if `dist` already exist before nodemon start, the ignore flag will work.
Could anyone help?
```bash
 $ node -v
v8.16.2
$ nodemon -v
1.19.4
```

**Comment by nmccready** [comment]
@remy please re-open. I am also seeing this issue.

**Comment by remy** [comment]
Please go ahead and create a new issue (as this original one uses out of
date code) with a pared down example to replicate with.
