### ISSUE TITLE
Node modules not correctly resolved when running under nodemon

### ISSUE THREAD

**Issue by mattezell** [remy/nodemon#1545]
- `nodemon -v`: 1.18.3
- `node -v`: 10.15.0
- Operating system/terminal environment:  Windows 7 / CMD
- Using Docker? What image: N/A
- Command you ran: nodemon --config nodemon-debug.json
- nodemon config:
```
{
  "watch": ["src"],
  "ext": "ts",
  "ignore": ["src/**/*.spec.ts"],
  "exec": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register src/main.ts"
}
```

### Expected behaviour
When using nodemon to monitor source changes, I'd expect that node applications behave identically to how they would when running directly under node.

### Actual behaviour
When using the above nodemon configuration, nested child_process.spawn calls seemingly fail with "is not recognized as an internal and external command" when 2 children deep - specifically when npm-lifecycle executes scripts, such as postinstall. I personally encountered this issue on a RESTful node build API, in which a project dependency included an opencollective postinstall script - which results in "'opencollective' is not recognized as an internal and external command"... When I bypass nodemon by directly running "node --inspect-brk -r tsconfig-paths/register -r ts-node/register src/main.ts", everything works as expected (e.g. opencollective postinstall is successfully executed).

### Steps to reproduce
The easiest way that I am aware of would be to start with a copy of the nestjs starter project: https://github.com/nestjs/typescript-starter

I modified the app.controller.ts getHello method to the following:
```
getHello(): string {
    const projectDir = `C:\\w\\Playground\\opencollective-postinstall-problem\\app-example`;
    process.chdir(projectDir);
    const spawnOpts = {
      shell: true,
      env: {
        ...process.env,
        NODE_ENV: 'development'
      },
      cwd: projectDir,
    };
    var cp = child_process.spawn('npm', ['i'], spawnOpts);
    cp.stdout.on('data', data => {
      console.log(`stdout data: ${data}`);
    });
    cp.stderr.on('data', data => {
      console.log(`stderr data: ${data}`);
    });
    cp.on('close', async code => {
      console.log(`close code: ${code}`);
    });
    return 'working on it - watch console.';
  }
}
```

Note: 'projectDir' needs to be a project which includes a dependency on a project which includes a postinstall script which relies on a dependency binary, such as opencollective... one such project is @compodoc/compodoc@1.1.7 (I've submitted a workaround to this project, which has been merged, so this will likely not be reproducible with this library at versions later than 1.1.7). 

```
...
devDependencies: {
  "@compodoc/compodoc": "1.1.7"
}
```

**Comment by jayfunk** [comment]
I am seeing this as well. I am using this script in my package.json file:
`"build:watch": "nodemon -e js,scss,css -w src -x 'nwb build-react-component --no-demo --copy-files'",`

**Comment by jayfunk** [comment]
Never mind. My issue appears to have been related to using `'` to quote around my -x command and not `"` which windows apparently cares about.

**Comment by ytldev** [comment]
I have same problem on my windows 

```
[nodemon] files triggering change check: app.js
[nodemon] matched rule: **\*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] app.js
```

**Comment by mattezell** [comment]
Yes, this is still an issue as described.
