### ISSUE TITLE
Nodemon not watching scss errors

### ISSUE THREAD

**Issue by mrzaheer** [remy/nodemon#1546]
I am using nodemon in my react project to watch for changes in .ts and .scss files. It watches for the changes, but it doesn't show the error in scss, instead the page stops loading. For eg. I changed the Image src from "/static/images/file.png" to "./images/file.png" (It should show an error, but it does not). 
Is there any solution for this?

This is my nodemon.json file: 

> {
    "watch": [
        "server",
        "config"
    ],
    "ext": "ts,yaml,yml,css,scss",
    "exec": "ts-node --project tsconfig.server.json server/index.ts"
}

**Comment by remy** [comment]
Can you provide a pared down example (perhaps without TS if you're able to replicate without it)

**Comment by mrzaheer** [comment]
for eg. this is my .scss code:

> &:after {
        content: "";
        width: 38px;
        height: 7px;
        background: url("../images/swirls.png") no-repeat left top;
        background-size: 38px;
        height: 7px;
        display: block;
        position: absolute;
        bottom: 0;
        left: 0;
    }
This should give an error, when I run it through nodemon, but it does not and page stops working.
I am using next.js, so the correct image url should be like url("/static/images/swirls.png) .
It gives the right error, when I stop the nodemon and build it using my build command. 

This is my package.json:

> "scripts": {
    "dev": "nodemon",
    "build": "rimraf build && tsc --project tsconfig.server.json && next build"
  }

**Comment by remy** [comment]
I can't replicate with that code. Nothing happens (suspect there's not enough in your issue to replicate)
