### ISSUE TITLE
I want to know if nodemon should handle meteor autorestart of crash ?

### ISSUE THREAD

**Issue by crotel** [remy/nodemon#1547]
- `nodemon -v`:latest stable
- `node -v`:latest stable
- Operating system/terminal environment: centos 7 64bit
- Using Docker? What image: x
- Command you ran:

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
You're better off asking meteor community to see if anyone has used this combo before. As for me: no idea.
