### ISSUE TITLE
Monitoring changes on node_modules when using pnpm

### ISSUE THREAD

**Issue by dkebler** [remy/nodemon#1550]
On selected projects I've started using pnpm https://pnpm.js.org/

During some development I have need to monitor `node_modules` for changes.
This all works fine when using npm with `ignoreRoot` set.

but pnpm does not use simple flat folder structure like npm.  As a result nodemon doesn't catch changes to a package I'm working on.

Looks like nodemon ignores directories with leading `.`.  So my solution is as simple as a setting in nodemon.json.  I need to include folders starting with `.` and/or follow symlinks (if you did a `pnpm install` you would see why).   Is it possible to set this from the nodemon.json file?  Can't find anything at your repo to indicate how.  Do I use minimatch?  If so what's the syntax for adding to nodemon.json.

**Comment by dkebler** [comment]
found your sample
https://github.com/remy/nodemon/blob/master/doc/sample-nodemon.md
tried this
`"watch":[".*/**/*.js"]`
no love

**Comment by dkebler** [comment]
Hmm digging further.
https://github.com/remy/nodemon/blob/master/lib/config/defaults.js

I see `watchOptions`  is that minimatch options?

I tired adding
`"watchOptions":{"dot":true}`
still no love

IMO little bit better verbage in readme on nodemon.json would be warranted, noting all possible settings (a clear link to that sample file would be ok if it had included ALL the possible options with example).  Might have been able to avoid having to make this issue.

**Comment by dkebler** [comment]
Dr Mr. Bot, no love from @remy yet, please keep this issue open.

**Comment by remy** [comment]
@dkebler sorry for the radio silence. I think there should be entries added to the FAQ for pnpm. I've only played with it briefly so I'm not _that_ familiar with it's node_modules structure.

To be clear: your aim is to *positively watch* node_modules changes, correct?

Were you able to find a way from adjusting the chokidar watch options?
