### ISSUE TITLE
nodemon ignoring .jst files

### ISSUE THREAD

**Issue by HosseinAlipour** [remy/nodemon#1569]
I use [DoT template](https://olado.github.io/doT/index.html) system with .jst extension, later DoT converts this template to a .js file. I use the following command to ignore only *.js files 

- `nodemon --ignore "template/*.js"`:

### Expected behaviour
not ignoring *.jst files but only *.js files

### Actual behaviour
ignoring both *.jst files and *.js files

### Steps to reproduce
https://github.com/HosseinAlipour/nodemonignore.git

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Can you provide a screenshot (or paste the output) with `--verbose` and the change in .jst triggering a reload? (It'll help me see what's causing the match and reload)

**Comment by HosseinAlipour** [comment]
the problem has been solved, I needed to add the extensions by `nodemon ... -e js,jst ...`
