### ISSUE TITLE
Feature request: option to ignore all patterns in .gitignore

### ISSUE THREAD

**Issue by callumlocke** [remy/nodemon#1572]
It would be handy if I could put something like `"gitignore": true` in my `nodemon.json` to automatically ignore everything that git ignores.

I know nodemon already defaults to ignoring a few specific things like `node_modules` and `.sass-cache`, but I often have a few other directories for stuff like build artifacts, caches, etc, and I frequently want these files ignored by *both* git and nodemon. Currently I have to duplicate these directories/patterns in `.gitignore` and `nodemon.json#ignore`, which is a slight maintenance burden.

**Comment by remy** [comment]
I'd take a PR for this. I'd also assume it completely overrides the existing nodemon ignore logic, in that it completely switches to gitignore.

**Comment by andrisi** [comment]
Just had this idea. I guess it would be an option to add patterns from gitignore to others in the ignore array.

**Comment by lukechilds** [comment]
Also running into this issue. Just as a suggestion for another approach, it would be nice to be able to provide a `ignoreFile` that nodemon interprets as a list of globs. Then you have the freedom to set `ignoreFile: '.gitignore'` if you want to use `.gitignore` or `ignoreFile: '.nodemonignore'` if you want something more specific.
