### ISSUE TITLE
nodemon doesn't restart whenever I change some code in index.js

### ISSUE THREAD

**Issue by anmolk1115** [remy/nodemon#1573]
- `nodemon -v`:
- `node -v`:
- Operating system/terminal environment: 
- Using Docker? What image: 
- Command you ran:

### Expected behaviour
[nodemon] clean exit - waiting for changes before restart
[nodemon] restarting due to changes...
[nodemon] starting `node index.js`

### Actual behaviour

F:\ANMOL\pear-system\node\task-manager>nodemon src/index.js
[nodemon] 1.19.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node src/index.js`
index hashing commented
server is listening at port 3000

[nodemon] restarting due to changes...
[nodemon] restarting due to changes...

### Steps to reproduce
nodemon src/index.js

---
nodemon --dump output -->

nodemon --dump
[nodemon] 1.19.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
--------------
node: v10.14.1
nodemon: 1.19.0
command: C:\Program Files\nodejs\node.exe C:\Users\vishnu-pc\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.js --dump
cwd: F:\ANMOL\pear-system\node\task-manager
OS: win32 x64
--------------
{ run: false,
  system: { cwd: 'F:\\ANMOL\\pear-system\\node\\task-manager' },
  required: false,
  dirs: [ 'F:\\ANMOL\\pear-system\\node\\task-manager' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**',
        re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot:
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby', ts: 'ts-node' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     signal: 'SIGUSR2',
     stdout: true,
     watchOptions: {},
     execOptions:
      { script: 'index.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        execArgs: [],
        ext: 'js,mjs,json',
        env: {} },
     monitor:
      [ '*.*',
        '!**/.git/**',
        '!**/.nyc_output/**',
        '!**/.sass-cache/**',
        '!**/bower_components/**',
        '!**/coverage/**',
        '!**/node_modules/**' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  signal: 'SIGUSR2',
  command:
   { raw: { executable: 'node', args: [ 'index.js' ] },
     string: 'node index.js' } }
--------------

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by goto1** [comment]
The issue you are describing above seems to be the same as the one in [#1544](https://github.com/remy/nodemon/issues/1544)
