### ISSUE TITLE
Nodemon automatically starts npm:start if file doesn't exist

### ISSUE THREAD

**Issue by alexeychikk** [remy/nodemon#1574]
When I run `npm run start:server:dev` and when there is no `/build/server/lib/index.js` file - instead of waiting for this file to be created nodemon just runs `npm start` for unknown reason.
```json
{
  "scripts": {  
    "start": "env-cmd development webpack-dev-server --config webpack.config.js --hot",
    "start:server": "node build/server/lib/index.js",
    "start:server:dev": "concurrently --kill-others \"npm run watch\" \"npm run autorestart\"",
    "build": "tsc -p server/tsconfig.json",
    "watch": "npm run build -- -w",
    "autorestart": "set DEBUG=* && nodemon --inspect ./build/server/lib/index.js",
  }
}
```
I could build my project first and then run nodemon but the problem is that build is running in a watch mode and in order to properly start nodemon it has to be built twice.

### Expected behaviour
nodemon waits for file to be created and then starts

### Actual behaviour
nodemon runs `npm start`

**Comment by Yangfan2016** [comment]
+1 why

**Comment by remy** [comment]
It's how nodemon works. If index doesn't exist, it'll look for npm.start. if nodemon can't find a script to run, it exists, as per pretty much every other command line tool.
