### ISSUE TITLE
[Help wanted] Can nodemon execute cmd with conditions?

### ISSUE THREAD

**Issue by drewxiuxiuxiu** [remy/nodemon#1575]
I have a repo with complex bootstrapping. One of step is to compile template (.mjml) files. Can I watch those files and execute only on piece of cmd, instead of the whole cmd chain? And this may have derivative cases (other than extensions I think). 

I've go through the document seems there is no related config. Any opinion would be helpful!

Thanks!

**Comment by noru** [comment]
@remy Sorry to bother, but a simple can/cannot will be appreciated!
