### ISSUE TITLE
Nodemon command not found in Visual Studio Terminal

### ISSUE THREAD

**Issue by Julianna120** [remy/nodemon#1577]
- `nodemon -v`:
- `node -v`:
- Operating system/terminal environment: 
- Using Docker? What image: 
- Command you ran:

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by Julianna120** [comment]
[Julianna-Computer-2:~/flashcards] julianna% nodemon
nodemon: Command not found.

**Comment by remy** [comment]
Happy to reopen if you add any detail (as per the issue template) 👍
