### ISSUE TITLE
Ignore a single file in a monitored folder

### ISSUE THREAD

**Issue by scaljeri** [remy/nodemon#1578]
- `nodemon -v`: 1.19.0
- `node -v`:v11.10.1
- Operating system/terminal environment: macOS 10.14.4
- Using Docker? What image: nope
- Command you ran: nodemon -e ts --ignore ./src/main-bar.ts --watch './src/**/*.ts' --exec yarn run:barfoo

### Expected behaviour
A change to the file main-bar.ts should not trigger nodemon to restart the yarn process

### Actual behaviour
Any change inside `./src` triggers nodemon and restarts the yarn process

I've posted this question on [SO](https://stackoverflow.com/questions/56418497/nodemon-ignore-a-single-file-in-a-monitored-folder) but didn't receive any suggestions. 

Is this a (known) bug or expected behaviour? If this cannot or won't be fixed or is correct behaviour, is there a way I can fix my issue?

**Comment by Axxxx0n** [comment]
Dummy comment for activity

**Comment by Axxxx0n** [comment]
I have the same problem

**Comment by remy** [comment]
Provide example code that can replicate the issue, otherwise the issue is left closed. As per the original issue, assume no knowledge of tech, especially TS

**Comment by JensForstmann** [comment]
Ran into the same issue. Solution was to NOT prefix paths with "./":

Bad example: 
```json
"ignore": ["./src/routes.ts"]
```

Good example:

```json
"ignore": ["src/routes.ts"]
```

(Posted if anybody founds this having also the same problem.)
