### ISSUE TITLE
Specifying a missing file only shows usage - no helpful error

### ISSUE THREAD

**Issue by wyckster** [remy/nodemon#1580]
- `nodemon -v`: 1.19.1
- `node -v`: v8.11.2
- Operating system/terminal environment:  Windows 10 win32 x64
- Using Docker?  Nope
- Command you ran: `nodemon thisfiledoesnotexist.js`

### Expected behaviour
Should produce an informative error.  Perhaps something like "Cannot find the file 'thisfiledoesnotexist.js'"

### Actual behaviour
It shows the *usage* blurb.  It is uninformative as to why it is doing so.  It is difficult to diagnose the problem (that the file does not exist) from the usage error alone.  The usage is technically correct.  (Syntactically and grammatically valid set of command line arguments).  It just so happens that the file does not exist.  That's not a usage problem.  That's a run-time error.  I expect that a helpful and informative error should be reported to assist the user in diagnosing the problem.

### Steps to reproduce

Run nodemon and specify any script file that does not exist.  e.g.:

```
nodemon thisfiledoesnotexist.js
```

**Comment by Grantlyk** [comment]
I could potentially work on this as no one has claimed it
