### ISSUE TITLE
High severity vulnerabilities found in dependency: chokidar

### ISSUE THREAD

**Issue by rossanthony** [remy/nodemon#1582]
A dependency of nodemon is being flagged by Snyk as having the following vulnerabilities:
```
✗ High severity vulnerability found in set-value
  Description: Prototype Pollution
  Info: https://snyk.io/vuln/SNYK-JS-SETVALUE-450213
  Introduced through: chokidar@2.1.6, anymatch@2.0.0, nodemon@1.19.1
  From: chokidar@2.1.6 > braces@2.3.2 > snapdragon@0.8.2 > base@0.11.2 > cache-base@1.0.1 > set-value@2.0.0
  From: anymatch@2.0.0 > micromatch@3.1.10 > snapdragon@0.8.2 > base@0.11.2 > cache-base@1.0.1 > set-value@2.0.0
  From: anymatch@2.0.0 > micromatch@3.1.10 > braces@2.3.2 > snapdragon@0.8.2 > base@0.11.2 > cache-base@1.0.1 > set-value@2.0.0
  and 51 more...
  Remediation:
    Some paths have no direct dependency upgrade that can address this issue. Run `snyk wizard` to explore remediation options.
    Upgrade direct dependency anymatch@2.0.0 to anymatch@3.0.0 (triggers upgrades to anymatch@3.0.0)
```
```
✗ High severity vulnerability found in mixin-deep
  Description: Prototype Pollution
  Info: https://snyk.io/vuln/SNYK-JS-MIXINDEEP-450212
  Introduced through: chokidar@2.1.6, anymatch@2.0.0, nodemon@1.19.1
  From: chokidar@2.1.6 > braces@2.3.2 > snapdragon@0.8.2 > base@0.11.2 > mixin-deep@1.3.1
  From: anymatch@2.0.0 > micromatch@3.1.10 > snapdragon@0.8.2 > base@0.11.2 > mixin-deep@1.3.1
  From: anymatch@2.0.0 > micromatch@3.1.10 > braces@2.3.2 > snapdragon@0.8.2 > base@0.11.2 > mixin-deep@1.3.1
  and 24 more...
```
- `nodemon -v`: 1.19.1
- `node -v`: 10.15.0
- Operating system/terminal environment: MacOS 10.12.6 / iTerm2
- Command you ran: `snyk test --file=package.json --severity-threshold=high`

### Expected behaviour

No high severity vulnerabilities found

### Actual behaviour

2 x high severity vulnerabilities found by snyk:

<img width="902" alt="Screen Shot 2019-06-20 at 5 23 44 PM" src="https://user-images.githubusercontent.com/2789355/59882569-8cde8100-9380-11e9-9266-ba7771fd22d0.png">

### Steps to reproduce

Run: `snyk test --file=package.json --severity-threshold=high`

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by mohsen1** [comment]
if you are using Yarn chokidar@3 is compatible 

```js
"resolutions": {
    "chokidar": "3"
  }
```

**Comment by rossanthony** [comment]
@mohsen1 we are indeed using yarn. Will adding this to our project's package.json override all sub-dependencies using chokidar to use v3?

**Comment by mohsen1** [comment]
@rossanthony [yes](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/)

**Comment by gainhad** [comment]
Bump for the stale bot. Still an issue

**Comment by poorejc** [comment]
Still an issue.

**Comment by cloakedninjas** [comment]
Tried raising a PR bumping `chokidar` to latest but tests fail. Haven't investigated further

```
test/events/complete.test.js


  events should follow normal flow on user triggered change
    ✓ start (41ms)
    ✓ config:update
    ✓ exit (103ms)
    ✓ stdout
    1) restart


  4 passing (31s)
  1 failing

  1) events should follow normal flow on user triggered change restart:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by remy** [comment]
Quick question - can a forked process be affected by the prototype chain of it's child?

If not, doesn't that mean this *potential* vuln has zero possibility of affecting user code? If it does, then I'll be looking at the PRs that come in (so far none) to get them merged.

**Comment by remy** [comment]
Both set-value and mixin-deep have been patched to fix these vulns, and thus nodemon is no longer affected (whether it was or not…).

Ensure you do a clean install! 👍
