### ISSUE TITLE
Nodemon does not working on Windows 10 64 version 1903 

### ISSUE THREAD

**Issue by joaodjtr** [remy/nodemon#1586]
Hello everybody. After update my Windows to the last version (1903), some npm´s packages and shortcuts used on terminal, like "code ." from VS Code does not work anymore, Nodemon are one of them. I uninstalled and installed Nodemon using npm, but the cmd don't reconigze the "nodemon" command. Are someone having the same issue?

Npm and node are working fine.

**Comment by SebastianHerrera** [comment]
i have the same problem.

**Comment by joaodjtr** [comment]
I solved the problem adding a new environment variable of type "path". Add this: "C:\Users\_username_\AppData\Roaming\npm", and will work fine. Apparently Windows deleted some environment variable after I updated the SO. 
I found the solution on this link [https://stackoverflow.com/questions/30710550/node-js-npm-modules-installed-but-command-not-recognized](url)
