### ISSUE TITLE
Nodemon doesn't work in windows 10 

### ISSUE THREAD

**Issue by SebastianHerrera** [remy/nodemon#1587]
---

Hi. Recently i update my compter to the last one Windows 10 version. But, when i wanna start my proyects (that work in ubuntu). Nodemon does not working. Nodemon install conrrectly, but when i write "npm start" or "nodemon src/app". The system He does not recognize the comand "nodemon"

```
"nodemon" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api-lol@1.0.0 start: `nodemon src/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the api-lol@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

When i write the command `npm install nodemon -g`:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\nodemon\node_modules\fsevents):            npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ nodemon@1.19.1
updated 1 package in 33.788s
```

But, when i again write the command `npm start` doesn´t work.

**Comment by BigUlises-97** [comment]
Hi, I had the same problem, I solved it re-installing node entirely, hope it can help you!
