### ISSUE TITLE
bash: nodemon: command not found

### ISSUE THREAD

**Issue by bcackerman** [remy/nodemon#159]
I'm getting this error after I ran `sudo npm install nodemon -g`

Anyone else getting this?

**Comment by sudeepdk** [comment]
I m getting error ...

npm WARN install Couldn't install optional dependency: Unsupported
contactlistapp@1.0.0 D:\sudeep_dk\MEAN\node\Mean\contact_passport
└── nodemon@1.8.1

**Comment by web-jenezis** [comment]
The same problem for me. 
I installed the nodemon `npm install -g nodemon` it was installed into `/usr/local/lib/node_modules/nodemon` but in console it was unavailable...

I solve the issue:
I unistalled the nodemon and reinstalled it with root permissions: `sudo npm install -g nodemon` and all works fine for me now.

**Comment by davidmungai** [comment]
thanx web-jenezis solved mine too

**Comment by maratmkhitaryan** [comment]
npm install nodemon
$HOME/node_modules/nodemon/bin/nodemon.js

**Comment by anonewb** [comment]
The simplest way to fix this bug on windows 10 i found was to reinstall node and git completely.

**Comment by beeti1sushruth** [comment]
> The same problem for me.
> I installed the nodemon `npm install -g nodemon` it was installed into `/usr/local/lib/node_modules/nodemon` but in console it was unavailable...
> 
> I solve the issue:
> I unistalled the nodemon and reinstalled it with root permissions: `sudo npm install -g nodemon` and all works fine for me now.

this is working thanks

**Comment by axelpale** [comment]
First, I was running nodemon via npm scripts without any problems. Had installed it only locally `npm install nodemon`.

```
...
"scripts": {
  "start": "nodemon test.js",
  "test": "tape test.js"
},
...

But suddenly, it stopped working, giving the `nodemon: command not found` error. I tried reinstall my package deps by `npm install` but no help.

Finally, I closed the terminal, reopened it, ran `npm install nodemon` again, and boom, it worked like before. There is something strange in the air.

Nodemon 1.19.0
Node 8.15.1
macOS Mojave 10.14.3
