### ISSUE TITLE
[nodemon] unable to run executable: "craco start"

### ISSUE THREAD

**Issue by mtjn** [remy/nodemon#1592]
- `nodemon -v`: 1.19.1 (ran `"test-nodemon": "nodemon -w spec -e js -x \"bash -c 'npm -v'\""`)
- `node -v`: v12.6.0
- Operating system/terminal environment: Ubuntu 19.04
- Using Docker? What image: No
- Command you ran: `yarn start` 
- "start" command from `package.json`: `"nodemon -w craco.config.js -w ./antd.customize.less --exec 'craco start'"`

### Expected behaviour
Nodemon sets up watchers for the specified files and then executes `craco start` (starts a development server for the react application)

### Actual behaviour
Nodemon throws an error and fails

```
yarn run v1.17.3
$ nodemon -w craco.config.js -w ./antd.customize.less --exec 'node_modules/.bin/craco start'
[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: craco.config.js ./antd.customize.less
[nodemon] starting `node_modules/.bin/craco start`
[nodemon] Error
    at Bus.<anonymous> (/home/michael/projects/frontend/node_modules/nodemon/lib/nodemon.js:156:25)
    at Bus.emit (events.js:208:15)
    at ChildProcess.<anonymous> (/home/michael/projects/frontend/node_modules/nodemon/lib/monitor/run.js:149:9)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[nodemon] unable to run executable: "node_modules/.bin/craco start"
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Steps to reproduce
On my system, just run `yarn start`. I don't have a test repository available so not sure how someone else could reproduce the error.

---

from --dump:

```
--------------
node: v12.6.0
nodemon: 1.19.1
command: /usr/bin/node /home/$USER/path/to/project/node_modules/.bin/nodemon --dump -w craco.config.js -w ./antd.customize.less --exec node_modules/.bin/craco start
cwd: /home/$USER/projects/frontend
OS: linux x64
--------------
{
  run: false,
  system: { cwd: '/home/$USER/path/to/project' },
  required: false,
  dirs: [
    '/home/michael/projects/frontend/craco.config.js',
    '/home/michael/projects/frontend/antd.customize.less'
  ],
  timeout: 1000,
  options: {
    dump: true,
    watch: [
      'craco.config.js',
      './antd.customize.less',
      re: /craco\.config\.js|\.\/antd\.customize\.less/
    ],
    exec: 'node_modules/.bin/craco start',
    ignore: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**',
      re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/
    ],
    ignoreRoot: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**'
    ],
    restartable: 'rs',
    colours: true,
    execMap: { py: 'python', rb: 'ruby', ts: 'ts-node' },
    stdin: true,
    runOnChangeOnly: false,
    verbose: false,
    signal: 'SIGUSR2',
    stdout: true,
    watchOptions: {},
    execOptions: {
      script: null,
      exec: 'node_modules/.bin/craco start',
      args: [],
      scriptPosition: null,
      nodeArgs: undefined,
      execArgs: [],
      ext: 'js,mjs,json',
      env: {}
    },
    monitor: [
      'craco.config.js',
      './antd.customize.less',
      '!**/.git/**',
      '!**/.nyc_output/**',
      '!**/.sass-cache/**',
      '!**/bower_components/**',
      '!**/coverage/**',
      '!**/node_modules/**'
    ]
  },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  signal: 'SIGUSR2',
  command: {
    raw: { executable: 'node_modules/.bin/craco start', args: [] },
    string: 'node_modules/.bin/craco start'
  }
}
--------------
Done in 0.34s.
```

**Comment by remy** [comment]
If you can't provide any way to replicate it might be near impossible to fix (as it can't verified). Of course, you're able to replicate so _that_ might be way to fix on your machine and then send a PR.

Otherwise, what happens when you run the following command from the `/home/$USER/projects/frontend` directory?

```
node_modules/.bin/craco start
```

**Comment by mtjn** [comment]
Thanks for the quick reply!

Running `node_modules/.bin/craco start` works fine. I was troubleshooting the error and found what seems to the culprit. It is the following line in my `~/.config/fish/config.fish` file (local configuration for the Fish shell):

`set -g PATH (yarn global bin) "$HOME/.local/bin" $PATH`

This is a line I added based on the instructions from yarn for enabling globally installed packages: https://yarnpkg.com/lang/en/docs/cli/global/

It also seemed to cause issues with several other CLI tools like `jest`, and `fisher`. The funny thing is that it was working fine for weeks, then suddenly caused these issues, and as far as I can tell I haven't made any system changes which could've caused this.

**Comment by mtjn** [comment]
Quick update, I was advised that fish offers a utility variable for safely permanently updating the path:

`set -U fish_user_paths DIR_TO_APPEND`

Using this technique instead does not cause the above mentioned issues. But perhaps there is some way that nodemon could handle whatever issue is arising when the path is modified in Fish via the original technique?

**Comment by mtjn** [comment]
After further review it seems like this boils down to a fish issue when not following recommended behavior to set the path. Nodemon is not at fault so will close.

c.f. https://github.com/jorgebucaran/fisher/issues/540
