### ISSUE TITLE
Can't install nodemon on my Mac.

### ISSUE THREAD

**Issue by edeIweiss** [remy/nodemon#1593]
- `nodemon -v`: can't install :(
- `node -v`: v10.16.0
- Operating system/terminal environment: Mac, OS X
- Using Docker? What image: 
- Command you ran: npm install -g nodemon

### Expected behaviour

probably should have been downloaded? D:
I checked to see if it was several times but my terminal always tells me no. :/

### Actual behaviour

npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Mac/.npm/_logs/2019-07-23T14_52_13_066Z-debug.log
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

Thanks!

**Comment by mkotamies** [comment]
It seems that you are trying to install nodemon globally. Is that really what you want?

Couple of options
1. Use sudo if you want to install nodemon globally
2. Add nodemon as a dependency to a project you want use it

**Comment by AngryKiller** [comment]
It may have something to do with the way you installed Node. You should install it using Homebrew, a package manager for macOS or nvm.

**Comment by remy** [comment]
Closing as this isn't a nodemon issue but an issue with either local machine's permissions or npm's permissions on local machine. Either way, not specific to nodemon. Feel free to continue discussion here if you need (just keeping issues specific to nodemon).
