### ISSUE TITLE
nodemon crash when test fails using Mocha

### ISSUE THREAD

**Issue by JavierPons** [remy/nodemon#1594]
When running test using Mocha and nodemon at same time. If some test fails nodemon crash. 
If all test are correct it works ok. No crashes. 
In terminal:
Report fails and passing plus at the end
`[nodemon] app crashed - waiting for file changes before starting...`
if pass all test 
`[nodemon] clean exit - waiting for changes before restart`

package.json:
`"test": "concurrently 'nodemon '  '--exec 'mocha --exit -R '' --delay 1"`
and I have tested with this as well
`"test": "concurrently 'nodemon '  '--exec 'mocha || true'' --delay 1"`
Does the same. Anyone works.
I want that, even if test fails nodemon doesn't crash,  it carry on. 
Any help?
I have been reading #496 but I didn't find solution for this issue.

- `nodemon -v`: 1.19.1
- `node -v`: 11.14.0
- `mocha`: 6.1.4
- `chai`: 4.2.0
- Operating system: macOS Mojave

**Comment by JavierPons** [comment]
I need nodemon working and mocha at same time. Importing files from db and testing them. Nodemon / Mocha works well importing/testing until some test file. Then the crash of nodemon. I try to keep this as clear as possible.

**Comment by remy** [comment]
What happens when you remove concurrently?

**Comment by JavierPons** [comment]
It happens the same issue.

**Comment by JavierPons** [comment]
As well when terminal inform
`[nodemon] app crashed - waiting for file changes before starting...`
I can add a new file to the db. So, in some way nodemon is working.

**Comment by JavierPons** [comment]
Solved.

**Comment by JavierPons** [comment]
I find out that it exist an error even with above code. That one works for me. I paste here is someone needs to take a look.

`"test": "concurrently 'nodemon'  'nodemon --exec 'mocha  || exit 1'' --delay 1 "`
