### ISSUE TITLE
be able to use `rs` when app crached

### ISSUE THREAD

**Issue by Darkein** [remy/nodemon#1603]
- `nodemon -v`: 1.18.4
- `node -v`: 10.16.3
- Operating system/terminal environment: ubuntu 19.04
- Using Docker? What image: nop
- Command you ran: node --inspect=9002 --signal SIGTERM -r ts-node/register -r tsconfig-paths/register src/main.ts

### Expected behaviour
when my application crash, I want to be able to restart it with `rs`

### Actual behaviour
when my application crash, tapping `rs` does nothing I have to stop it with `CTRL+C`, then restart it, or edit a watched file.
``` bash
[nodemon] starting `node --inspect=9002 -r ts-node/register -r tsconfig-paths/register src/main.ts`
Starting inspector on 127.0.0.1:9002 failed: address already in use
[nodemon] app crashed - waiting for file changes before starting...
rs
rs
# file edition
[nodemon] restarting due to changes...
```

### Steps to reproduce
launch an app which crash after few seconds then try to tap `rs`

**Comment by remy** [comment]
The `rs` does work. I suspect this is linked to something in your codebase. Can you provide a replicable example of code?

**Comment by Darkein** [comment]
it's a nestjs project generated with nest cli. I will try with a new project, to be sure

**Comment by Darkein** [comment]
like my other issue, updating to 1.19.2 fixed the problem. Thanks, and sorry again !
