### ISSUE TITLE
Identify if nodemon restarted process?

### ISSUE THREAD

**Issue by naveensky** [remy/nodemon#1606]
Hi There, 

I am using nodemon in my development environment. 

My dev environment has front-end built on NuxtJS, which support hot-loading and the backend is Koa, for which I am using nodemon to reload server files. 

The way the dev environment is set up, the koa backends compile and loads nuxt front-end. The problem is that whenever we are working with koa related files since nodemon restarts the entire process, the nuxt front-end is compiled each time. For large projects, this compile-time is up to 10 mins, which makes it impossible to work with backend. 

I can easily circumvent this if I am able to understand if the nodemon has started a process. Is there any way for me to understand in the code is the current process is an original start process or if restarted via nodemon. 

Does nodemon set an ENV variable or can pass any argument when restarting the process. 

Please suggest

**Comment by remy** [comment]
You might be able to solve it using nodemon in a required setting: https://github.com/remy/nodemon/wiki/Events#using-nodemon-events
