### ISSUE TITLE
Add a noDefaults flag to allow full control custom watches

### ISSUE THREAD

**Issue by dkebler** [remy/nodemon#1609]
Per #1411 it's not possible to watch a single node_modules directory/dependency.  But if users could disable the default watch/ignore assumptions and manually set watches this would be possible

It's the default watch/ignore assumptions that preclude this.  Essentially watch everything under cwd except what is in the ignoreRoot   

How about a new flag that can be set if users want to set their own watches.  If set nodemon will not watch/ignore the entire cwd.  Basically a flag that disables any default watches and ignores.

So a flag say `noDefaults` which means nodemon will not watch or ignore anything by default.  It then would be the responsibility of the user to set all the watches they need 

so like this example for nodemon.json

options: {
    noDefaults: true,  
    "watch": ["src","index.js","test",node_modules/@uci/*/src"]
}

Not sure the easiest way to do this here are the lines of interest
https://github.com/remy/nodemon/blob/12b66cd492b4b06ffc91da57eca4794c25f05632/lib/config/defaults.js#L16
https://github.com/remy/nodemon/blob/12b66cd492b4b06ffc91da57eca4794c25f05632/lib/config/index.js#L51
https://github.com/remy/nodemon/blob/12b66cd492b4b06ffc91da57eca4794c25f05632/lib/nodemon.js#L162

If you don't have time to do this then if you give me some suggestions about how best to proceed I'd try a PR

**Comment by remy** [comment]
How is this different from using this?

```json
{
 ignoreRoot: [],
 "watch": ["src","index.js","test",node_modules/@uci/*/src"]
}
```
