### ISSUE TITLE
Internal watch failed: EMFILE: too many open files, watch

### ISSUE THREAD

**Issue by houzehang** [remy/nodemon#1610]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mingxi@1.0.42 watch: `nodemon --watch . --watch config ./boot.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mingxi@1.0.42 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/***/.npm/_logs/2019-09-17T02_38_17_710Z-debug.log

**Comment by remy** [comment]
As per the output, you're watching too many files. I suspect there's a subdirectory that contains a LOT of files that needs ignoring.

Create a `nodemon.json` and add the dir to the `ignore` config, say if it's `logs/*` you need to do this:

```json
{
  "ignore": ["logs"]
}
```

**Comment by Jiao1008** [comment]
[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): server/**/*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server/index.js`
[nodemon] Internal watch failed: EMFILE: too many open files, watch '/headless/data/sources/Education_Web/Education_Web/server'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! roncoo-education-web@9.0.0-RELEASE dev: `cross-env NODE_ENV=development nodemon server/index.js --watch server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the roncoo-education-web@9.0.0-RELEASE dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /headless/.npm/_logs/2022-03-28T06_42_16_878Z-debug.log

**Comment by IvanPostarnak** [comment]
Good day! Feel sorry to complain about it again, but this error kind of persist...

**console output**
[nodemon] 3.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node ./src/index.ts`
[nodemon] Internal watch failed: EMFILE: too many open files, watch '/media/shelfy/SSD/_Coding/quotes-server/src'

**after a second it starts the server ANYWAY**
⚡️Server is running on port 7000

(but you cannot control it - I cannot restart it using `rs` or stop it using `ctrl + c` - it is detouched somehow...
I've tried increase `ulimit -n` from 1024 and more, but it won't work(

**I RUN**
```bash
"dev": "nodemon"
```

**My nodemon.json**
```json
{
    "watch": ["src"],
    "ext": "ts",
    "exec": "ts-node ./src/index.ts"
}
```

**My versions**
```json
{
    "nodemon": "^3.0.1",
    "ts-node": "^10.9.1",
}
```

Do not understand what does this error is related to =(
