### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by SheetJSDev** [remy/nodemon#1615]
Github does not recognize a license for this project.  Unfortunately it looks for specific text within a LICENSE or COPYING file, so linking to the license from the README is insufficient.

**Comment by remy** [comment]
"Insufficient" - can you expand? To what in particular?

**Comment by SheetJSDev** [comment]
The issue arises because GH can't detect the license for the project.  The license shows up in two places:

- Top bar that lists the number of commits, branches, etc.   The bar for [Vue.js](https://github.com/vuejs/vue) mentions "MIT" at the right side and links to the license, while nodemon has no such mention.

- GH Search results. https://github.com/search?o=desc&q=nodemon&s=stars&type=Repositories you'll see the listing for nodemon has no license but other listings have "MIT license" mentioned

Adding the license text as a file would immediately make github able to determine that this project is MIT licensed and 

PS: At first blush it would seem like you actually need to include the text as well:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Since you run the mit-license.org site that you reference in the README, presumably you verified that merely linking to the license is OK.

**Comment by remy** [comment]
I'm not sure what you mean by:

> presumably you verified that merely linking to the license is OK

It's okay with me…it's been okay for the last several years and no technical or legal problems have come up. 

If it doesn't integrate tightly with Github's platform that's not something I'm particularly bothered by. Am I missing something (genuinely asking - I know tone can be lost in text).

**Comment by SheetJSDev** [comment]
There are two subquestions:

1) What would make github happy? (and your response was that it didn't bother you that github didn't automatically detect the MIT license)
2) What does the MIT License actually require?

Based on my reading, the actual MIT license text asserts you need to include the actual license text, not just link to it:

> **The above copyright notice** and this permission notice **shall be included** in all copies or substantial portions of the Software.

AFAICT that is not currently the case:

```
$ git clone --depth=1 https://github.com/remy/nodemon/
$ cd nodemon/
$ grep -RIil --exclude-dir test copyright .
./.git/hooks/pre-rebase.sample
```

Normally I would've sent a PR with the license and moved on, but you run that mit-license.org site that you use in the README.  Maybe it's better to ask point blank: are you sure that linking to the license text complies with the license?  Given how MIT license is written, that is entirely unclear.

PS: both GPLv2 and GPLv3 have explicit language that permits referencing the license by link.  Here's a sample from https://www.gnu.org/licenses/gpl-3.0.en.html :

> tells the user ... how to view a copy of this License. 

The short-form notice also includes appropriate language:

```
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
```

**Comment by schalkneethling** [comment]
Hey @remy,

Firstly, thank you for this amazing piece of software. Secondly, would you be opposed to simply adding essentially the contents of https://rem.mit-license.org/ as a `LICENSE` file to the repo?

I do not believe it will cause any maintenance overhead. Let me know.

**Comment by remy** [comment]
The only maintenance is that each year the license needs to be updated with the new year - which is why I made a service in the first place.

**Comment by SheetJSDev** [comment]
The year need not be specified, as is the case with [react](https://github.com/facebook/react/blob/master/LICENSE)

In fact, years ago they used to specify the [end date "present"](https://github.com/facebook/react/commit/bef45b0b1a98ea9b472ba664d955a039cf2f8068#diff-9879d6db96fd29134fc802214163b95a), which avoids the yearly refresh

**Comment by remy** [comment]
Fair enough. On that idea, I'm happy to add in a license pointing to present.

**Comment by schalkneethling** [comment]
Thank you for the feedback @remy. @SheetJSDev you want to open a PR for it? I am more than happy to but as you brought this up, I would defer to you.

**Comment by SheetJSDev** [comment]
It looks like @markokajzer already submitted a PR https://github.com/remy/nodemon/pull/1617 -- probably best for him to fix the PR (it should be a clean rebase)

**Comment by remy** [comment]
I've added the review to the PR and once updated, I'll merge.
