### ISSUE TITLE
nodemon not able to use due to disabled script

### ISSUE THREAD

**Issue by dk445** [remy/nodemon#1619]
PS E:\nodejs\New folder\notes-app> nodemon app.js
nodemon : File C:\Users\zaheet\AppData\Roaming\npm\nodemon.ps1 cannot be loaded because running scripts is disabled on this system. For more
information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1

nodemon app.js
  + CategoryInfo          : SecurityError: (:) [], PSSecurityException
  + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by zaheet** [comment]
same issue

**Comment by adelbs** [comment]
It's a security restriction of the Windows PowerShell.

1) Open up a powershell command window (open it as administrator)
2) To check out current restrictions type "Get-ExecutionPolicy"
3) Enable powershell by typing "Set-ExecutionPolicy remotesigned"

Just got the solution from this link:
https://stackoverflow.com/questions/32692087/nuget-give-this-error-ps1-cannot-be-loaded-because-running-scripts-is-disabled

**Comment by remy** [comment]
It this worth adding to the FAQ?

**Comment by MarwaAbuEssa** [comment]
@adelbs It worked for me , thanks

**Comment by remy** [comment]
Closing and updating FAQ (as there's a solid answer).

**Comment by MdSamsuzzohaShayon** [comment]
This should work

open your power-shell as administration and type 
```
Get-ExecutionPolicy
```
Expected result `RemoteSigned`

```
Set-ExecutionPolicy remotesigned
```

**Enjoy**

**Comment by Baypars** [comment]
> It's a security restriction of the Windows PowerShell.
> 
> 1. Open up a powershell command window (open it as administrator)
> 2. To check out current restrictions type "Get-ExecutionPolicy"
> 3. Enable powershell by typing "Set-ExecutionPolicy remotesigned"
> 
> Just got the solution from this link:
> https://stackoverflow.com/questions/32692087/nuget-give-this-error-ps1-cannot-be-loaded-because-running-scripts-is-disabled

thank you sir, it worked for me.

**Comment by NAVOM7** [comment]
> It's a security restriction of the Windows PowerShell.
> 
> 1. Open up a powershell command window (open it as administrator)
> 2. To check out current restrictions type "Get-ExecutionPolicy"
> 3. Enable powershell by typing "Set-ExecutionPolicy remotesigned"
> 
> Just got the solution from this link:
> https://stackoverflow.com/questions/32692087/nuget-give-this-error-ps1-cannot-be-loaded-because-running-scripts-is-disabled

It worked also for me..
Thanks

**Comment by Eman152** [comment]
i tried that but doesn't work..any other suggestions!

**Comment by zain148** [comment]
> > It's a security restriction of the Windows PowerShell.
> > 
> > 1. Open up a powershell command window (open it as administrator)
> > 2. To check out current restrictions type "Get-ExecutionPolicy"
> > 3. Enable powershell by typing "Set-ExecutionPolicy remotesigned"
> > 
> > Just got the solution from this link:
> > https://stackoverflow.com/questions/32692087/nuget-give-this-error-ps1-cannot-be-loaded-because-running-scripts-is-disabled
> 
it's not working

**Comment by anshu-20166** [comment]
> > It's a security restriction of the Windows PowerShell.
> > 
> > 1. Open up a powershell command window (open it as administrator)
> > 2. To check out current restrictions type "Get-ExecutionPolicy"
> > 3. Enable powershell by typing "Set-ExecutionPolicy remotesigned"
> > 
> > Just got the solution from this link:
> > https://stackoverflow.com/questions/32692087/nuget-give-this-error-ps1-cannot-be-loaded-because-running-scripts-is-disabled
> 
> It worked also for me..
> Thanks

thanks it worked for me as well

**Comment by Satyam-code143** [comment]
@adelbs 
Worked for me!
Thank You!!

**Comment by juniorbuba** [comment]
If you're on windows you can try: settings>>update & security>>for developers>> check the allow powershell to run scripts without signing box

**Comment by KennyLeungCB** [comment]
> If you're on windows you can try: settings>>update & security>>for developers>> check the allow powershell to run scripts without signing box

Thx.
