### ISSUE TITLE
nodemon stuck on "[nodemon] restarting due to changes..." 

### ISSUE THREAD

**Issue by amanullah28** [remy/nodemon#1621]
- `nodemon -v`: 1.19.4 (tried with many other previous version but didn't work)
- `node -v`: 10.15.1
- Operating system/terminal environment: windows 10/cmd and vs code integrated terminal
- Command you ran: npm start it runs nodemon app.js

### Expected behavior
After detecting change nodemon should restart the server

### Actual behaviour
after saving any changes nodemon should restart the server but it fails to do that I get a message [nodemon] restarting due to changes...
 
output
> nodemon app.js

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json  
[nodemon] starting `node app.js`
Server has started!
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...

### Steps to reproduce
console.log("stuck")
while(1){
}

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Okay, so this issue has been raised before, but no information was provided to actually resolve the issue. Let's try to get under the core of the issue here and find out what's going on.

Related:

- #1520
- #1530

For others that find this issue: not looking for "this happens to me too" but more importantly: here's a pared down version of my code that it definitely happens on.

The later will allow us to replicate, diagnose and resolve.

**Comment by amanullah28** [comment]
@remy recently I used nodemon in another machine with the same development environment it working fine, Is that problem related to system environmental variable?

**Comment by remy** [comment]
I'm pretty sure, based on the other issues filed that it's speicific to
Windows and maybe even a particular build.

**Comment by amanullah28** [comment]
Yes, it can be possible, I am going to reset my laptop if it will work after reset then I will update you ):

**Comment by amanullah28** [comment]
After resetting my laptop everything works fine, As Remy said it was windows specific problem.

**Comment by stgonzales** [comment]
Guys, please help me here, I am facing the same problem and CAN'T figure out.

Here's the Dockerfile:
```
FROM node:12.16.3

WORKDIR /usr/src/twa

COPY package*.json ./

RUN npm ci

COPY . .

```

Here's the Docker-compose file:

```
version: '3.7'

services:
    node:
        container_name: node
        build: .
        user: node
        ports: 
            - "3000:3000"
        volumes: 
            - ".:/usr/src/twa"
        command: "npm run dev"
```

Here's package.json file:

```
{
  "name": "api_twa",
  "version": "1.0.0",
  "description": "Api to query on SQL Server database and provide for front end.",
  "main": "index.js",
  "scripts": {
    "start": "node src/server.js",
    "dev": "nodemon --watch src src/server.js"
  },
  "author": "Stephen Goncalves",
  "license": "MIT",
  "dependencies": {
    "express": "^4.17.1",
    "sequelize": "^5.21.7",
    "tedious": "^8.3.0"
  },
  "devDependencies": {
    "nodemon": "^2.0.3",
    "sequelize-cli": "^5.5.1"
  }
}
```
Here's the app file:

```
const express = require('express')
const routes = require('./routes')

require('./database')

const port = process.env.PORT || 3000

const app = express()

app.use(express.json())
app.use(routes)

app.listen(port, () => console.log(`Server running on port ${port}`))
```

I am using Docker version 19.03.8
![image](https://user-images.githubusercontent.com/12421471/81225743-a52fac80-8fe1-11ea-8804-cf94d1c3e6d1.png)

Windows 10 Pro (fresh installed)
![image](https://user-images.githubusercontent.com/12421471/81225828-cbede300-8fe1-11ea-8f5e-0cf4ffdc4056.png)

I noticed that `nodemon` only run when I run docker compose up:
![image](https://user-images.githubusercontent.com/12421471/81226223-677f5380-8fe2-11ea-92fc-54eeefbb3147.png)

If I try to restart the container, it doesn't do anything.

If anyone PLEASE help me here, I'm stuck with this...

**Comment by JonatanOrtiz** [comment]
Same

**Comment by ridbay** [comment]
Use the alternative package called supervisor, click [https://www.npmjs.com/package/supervisor](https://www.npmjs.com/package/supervisor) to read more about it
