### ISSUE TITLE
-bash: nodemon: command not found

### ISSUE THREAD

**Issue by Rmantatikar** [remy/nodemon#1624]
None of the following commands work
- `nodemon -v`:
- `node -v`:
- Operating system/terminal environment: 
- Using Docker? What image: 
- Command you ran:
**nodemon -h
-bash: nodemon: command not found**

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
With zero information I can only assume you didn't install nodemon. Please see installing in the resdme of this project.
