### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by ehouarn-perret** [remy/nodemon#1625]
- `nodemon -v`: 1.19.4
- `node -v`: v13.0.1
- Operating system/terminal environment: Windows 10 Enterprise
- Using Docker? nope
- Command you ran: `npm run serve-fake-api`

in `package.json`:
```json
"serve-fake-api": "nodemon --exec \"ts-node\" fake-api/server.ts --watch fake-api/*.ts"
```

`fake-api/server.ts`:
```
import FakeApiServer from "./FakeApiServer";

const fakeApiServer = new FakeApiServer(3000);
fakeApiServer.start();
```

`fake-api/FakeApiServer.ts`:
```
import fs from "fs";
import jsonServer from "json-server";
import path from "path";

export default class FakeApiServer {

	readonly routesFileName = "routes.json";
	readonly middlewareFileName = "middleware.ts";
	readonly databaseFileName = "db.json";

	readonly port: number;

	constructor(port: number) {
		this.port = port;
	}

	public start(): void {

		const server = jsonServer.create();
		const defaultMiddleware = jsonServer.defaults();

		// It is recommended to use the bodyParser middleware before any other middleware in your application
		server.use(jsonServer.bodyParser);

		server.use(defaultMiddleware);

		// Define custom routes (routes.json)
		const routes = JSON.parse(fs.readFileSync(path.join(__dirname, this.routesFileName), "utf-8"));
		server.use(jsonServer.rewriter(routes));

		// Add custom middleware before JSON Server router
		const customMiddleware = require(path.join(__dirname, this.middlewareFileName));
		server.use(customMiddleware);

		// This is where `json-server`'s magic happens ;)
		const router = jsonServer.router(path.join(__dirname, this.databaseFileName));

		// Start the application by listening to the given port,
		// Although this won't print the nice starting message you see when
		// running `json-server` as CLI command, it still runs the app correctly.
		server.use(router);
		server.listen(this.port, () => {
				// tslint:disable-next-line: no-console
				console.log("JSON Server is running");
		});
	}
}
```

### Expected behaviour
`import FakeApiServer from "./FakeApiServer";` can be processed...

### Actual behaviour
```bash
PS C:\Users\eperret\Desktop\combo\ui> npm run serve-fake-api

> rm-combo@0.1.0 serve-fake-api C:\Users\eperret\Desktop\combo\ui
> nodemon --exec "ts-node" fake-api/server.ts --watch fake-api/*.ts

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): fake-api\*.ts
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node fake-api/server.ts`
C:\Users\eperret\Desktop\combo\ui\fake-api\server.ts:1
import FakeApiServer from "./FakeApiServer";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:891:16)
    at Module._compile (internal/modules/cjs/loader.js:941:27)
    at Module.m._compile (C:\Users\eperret\Desktop\combo\ui\node_modules\ts-node\src\index.ts:530:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\eperret\Desktop\combo\ui\node_modules\ts-node\src\index.ts:533:12)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1051:12)
    at main (C:\Users\eperret\Desktop\combo\ui\node_modules\ts-node\src\bin.ts:212:14)
    at Object.<anonymous> (C:\Users\eperret\Desktop\combo\ui\node_modules\ts-node\src\bin.ts:470:3)
[nodemon] app crashed - waiting for file changes before starting...
Terminate batch job (Y/N)? Y
```

**Comment by remy** [comment]
I can't replicate. Here's the pared down code: https://gist.github.com/remy/135411e4645c7e6750c7515577a43ed7 - please go ahead and let me know if you can replicate with this code (possible it's windows, but doubt it), otherwise the StaleBot will auto close in a week or so… Good luck.

**Comment by psnehas** [comment]
Observed something similar when I tried to run a simple code.
`import React, { Component } from 'react';

class Counter extends Component {
    render() { 
        return <div><h1>Hello</h1><button>Increment</button></div>;
    }
}
 
export default Counter;`

The error obtained is:
`import React from "react";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
[nodemon] app crashed - waiting for file changes before starting...`

I appreciate any leads in solving this error.

**Comment by cychainey** [comment]
Had a similar issue running in a container

`package.json`:

`"start": "nodemon --exec babel-node src/server.js"`

fix was to add a `.babelrc` into the container with:

`{
  "presets": ["@babel/preset-env"]
}`

the alternative was to just use `require`

**Comment by ehouarn-perret** [comment]
`{ "presets": ["@babel/preset-env"] }`
Interesting 🤔 

I solved my issue by changing the module type with `commonjs` in `tsconfig.json` instead of `esnext`:
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
...
```

and adapting my `packages.json` as follows:

```
...
  "scripts": {
    "serve-fake-api": "nodemon fake-api/index.ts --watch fake-api/*.*",
    "serve-vue": "vue-cli-service serve",
    "serve": "concurrently -k \"npm run serve-fake-api\" \"npm run serve-vue\"",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
...
```
now it works like a charm ~~

**Comment by Nditah** [comment]
**Update 3:** Since Node 13, you can use either the .mjs extension or set "type": "module" in your package.json. You don't need to use the `--experimental-modules` flag.

**Update 2:** Since Node 12, you can use either the .mjs extension or set "type": "module" in your package.json. And you need to run node with the `--experimental-modules`  flag.

**Update:** In Node 9, it is enabled behind a flag, and uses the .mjs extension.

`node --experimental-modules my-app.mjs`

https://stackoverflow.com/questions/39436322/node-js-syntaxerror-unexpected-token-import?rq=1

**Comment by MelMacaluso** [comment]
> Had a similar issue running in a container
> 
> `package.json`:
> 
> `"start": "nodemon --exec babel-node src/server.js"`
> 
> fix was to add a `.babelrc` into the container with:
> 
> `{ "presets": ["@babel/preset-env"] }`
> 
> the alternative was to just use `require`

`nodemon --exec babel-node src/index.js` did it
