### ISSUE TITLE
Errors during installation with Darwin but successful added 

### ISSUE THREAD

**Issue by ArtKoKo** [remy/nodemon#1628]
- `nodemon -v`: 1.19.4
- `node -v`: v12.13.0
- Operating system/terminal environment: 
Darwin 18.7.0 / Bash
- Command you ran:
sudo npm install --global nodemon

### Expected behaviour
no Error, no Warn

### Actual behaviour
Errors during installation

### Steps to reproduce
Just install

npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
/opt/local/bin/nodemon -> /opt/local/lib/node_modules/nodemon/bin/nodemon.js

> fsevents@1.2.9 install /opt/local/lib/node_modules/nodemon/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.9 and node@12.13.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/opt/local/lib/node_modules/nodemon/node_modules/fsevents/lib' 
gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/Users/atkteam/Library/Caches/node-gyp/12.13.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/local/lib/node_modules/nodemon/node_modules/fsevents/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/local/lib/node_modules/nodemon/node_modules/fsevents/.node-gyp'
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/local/lib/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=/opt/local/lib/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /opt/local/lib/node_modules/nodemon/node_modules/fsevents
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/opt/local/bin/node /opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/local/lib/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/opt/local/lib/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/local/lib/node_modules/nodemon/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/nodemon/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /opt/local/lib/node_modules/nodemon/node_modules/fsevents
node-pre-gyp ERR! node -v v12.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/opt/local/bin/node /opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/local/lib/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/opt/local/lib/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)

> nodemon@1.19.4 postinstall /opt/local/lib/node_modules/nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/nodemon/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ nodemon@1.19.4
added 221 packages from 128 contributors in 12.257s

**Comment by karamiomid** [comment]
Exactly the same issue on macOS catalina (10.15.1) with the same version of node (12.13.0) and npm version (6.12.0). Both of node and npm were installed by node installer from (nodejs.org/en/).

**Comment by remy** [comment]
I suspect this is because nodemon support node@4 and upward, and fsevents is v1 - and just warning/complaining.

What you're seeing is that the binary is going to be compiled (because only the new ones are hosted) and then there's some permission issues related your own machine. 

Going to close, but will potentially inherit fsevents@2 with the chokidar upgrade in PR #1622.
