### ISSUE TITLE
Error: listen EADDRINUSE 

### ISSUE THREAD

**Issue by baryon** [remy/nodemon#1629]
ref: #1316

nodemon -v: 1.19.4
node -v: v10.17.0
Operating system/terminal environment: MacOS 10.15.1（19B88）
Command you ran: nodemon app.js
Expected behaviour
Should restart the app when there are changes using the same http server (host & server)

Actual behaviour
Restarts the app but throwing an error saying the EADDRINUSE.

**Comment by remy** [comment]
See PR #1579 - suspect it will help, though also suspect there's something in your process that's leaving node running and nodemon can't shut it down. Will close, and release the PR - let _me_ know if you continue to have this problem.
