### ISSUE TITLE
Having an unrelated folder/file (in a sub-folder) in watch list breaks nodemon: it stops triggering changes when some other file is deleted and then re-created

### ISSUE THREAD

**Issue by dko-slapdash** [remy/nodemon#1639]
Nodemon version 2.0.1, Docker with Ubuntu 18.04.3 LTS (image: "ubuntu:18.04").

Normally, if I have some explicit file in `watch` list, then I remove and add the file back, it triggers the change. Which is great.

But this (triggering after remove+add-back sequence) stops working when watch-list has not just the list of files in the current directory, but also an unrelated entry in a sub-folder. 

I localized this to the minimal example below. Add an entry `"folder/some.txt"` with subfolder - it stops working; remove `"folder/some.txt"` line - it starts working again. And it's indeed correlated with subfolders.

```bash
echo '{
  "exec": "echo changed",
  "watch": [
    "folder/some.txt",
    "other.txt",
    "trigger.txt"
  ],
  "ignoreRoot": [],
  "ignore": [],
  "ext": "*",
  "delay": "50",
  "quiet": true
}' > nodemon.json

mkdir -p folder
touch trigger.txt other.txt folder/some.txt
node_modules/.bin/nodemon --config nodemon.json

# in another console:
touch trigger.txt   # <-- triggers the change, OK
rm trigger.txt
touch trigger.txt   # <-- DOES NOT trigger changes anymore
touch trigger.txt   # <-- broken starting from now on
```

UPD:
1. -L flag doesn't help
2. installing of inotify-tools doesn't help
3. nodemon breaks in case of not only a subfolder, but also in case of having an unrelated ../some-file.txt entry or even in case of an /absolute/path.txt.

**Comment by dko-slapdash** [comment]
Hi @remy , I would greatly appreciate your opinion on this. The repro is stable.

**Comment by remy** [comment]
I'll look at this today.

**Comment by remy** [comment]
Can you confirm the version of chokidar being used?

```
npm ls chokidar
```

Expecting `chokidar@3.3.0`

**Comment by dko-slapdash** [comment]
Yes, nodemon uses chokidar@3.3.0.

Just followed the steps in the issue description again and confirming that it still clearly reproduces.

```
# npm ls chokidar
slapdash-client@1.0.0 /srv/slapdash
├─┬ @babel/cli@7.6.2
│ └── chokidar@2.1.8
├─┬ nodemon@2.0.2
│ └── chokidar@3.3.0
├─┬ typescript-plugin-css-modules@2.0.2
│ └─┬ sass@1.22.12
│   └── chokidar@3.1.1
└─┬ webpack@4.40.2
  └─┬ watchpack@1.6.0
    └── chokidar@2.1.8  deduped
```

**Comment by JulianNicholls** [comment]
@dko-slapdash I confirmed it on Ubuntu 19.10 too, while Remy was livestreaming on 11/12/2019.

**Comment by dko-slapdash** [comment]
@remy yep, it’s still happening... you think it’s a chokidar issue, not nodemon’s?
