### ISSUE TITLE
all console.log disappeared

### ISSUE THREAD

**Issue by infFenrir** [remy/nodemon#1641]
- `nodemon`: 2.0.1
- `node `: 12.13.1
- `Windows`: 10 
- project use electron and webpack 
- Command you ran: "wait-on http://localhost:3000 && nodemon --watch . --exec \"electron . --debug\""

When switching to nodemon v2.0.1 all console.log from the electron disappeared, only webpack logs left :(

**Comment by remy** [comment]
I can't replicate the bug you're seeing (because there's no repo to work with), but can you try with nodemon@2.0.2 and let me know what you see.

**Comment by infFenrir** [comment]
Yes in @2.0.2 everything works as before, thanks :)
