### ISSUE TITLE
nodemon "still waiting for 1 sub-process to finish..." when using cluster

### ISSUE THREAD

**Issue by ezze** [remy/nodemon#1643]
- `nodemon -v`: 2.0.1
- `node -v`:
- Operating system/terminal environment: Kubuntu 18.04.1
- Using Docker? What image: no
- Command you ran: `nodemon --watch server.js`

### Expected behaviour

nodemon restarts on `rs` command or detected changes.

### Actual behaviour

nodemon doesn't restart with the following multiple messages:

> [nodemon] still waiting for 1 sub-process to finish...

![issue](https://user-images.githubusercontent.com/665479/70231315-205b1100-176b-11ea-89bc-9488a3bb8b7c.png)

### Steps to reproduce

[Here is a repo to reproduce](https://github.com/ezze/nodemon-cluster-issue)

**Comment by ezze** [comment]
If you install 2.0.0 everything works as expected:

```bash
$ yarn add nodemon@2.0.0 --dev
$ yarn start
```

**Comment by lorenc-tomasz** [comment]
@ezze Thanks for raising this issue.

**Comment by sytana** [comment]
Is it a problem with version 2.0.1?

When can it be updated?

Thanks!

**Comment by remy** [comment]
@sytana not to point out the obvious, but this is an open source project, so it can be updated as soon as people contribute. 

Thus far it's only me - and I have been working on this issue between working (my "real" job) and the tests weren't passing. So I'll happily take some help to get those passing.

Thanks!

**Comment by sytana** [comment]
@remy Oh, sorry i'm ignorant about this, But thank you very much for your contribution!

**Comment by remy** [comment]
So nodemon@2.0.2 has been released - if you can re-test, but I'm not 100% hopeful as this is cluster and there's not a great deal of testing against cluster.

**Comment by ezze** [comment]
@remy, works for me. Thanks a lot for your work!

**Comment by remy** [comment]
Cool - I just confirmed too 👍

**Comment by zachncst** [comment]
Still broke for me unfortunately. I'll inspect as to why.

**Comment by thanhdevapp** [comment]
confirmed still error 2.0.2

**Comment by kolchurinvv** [comment]
this happens to my setup while using `"nodemon -x 'node --loader ts-node/esm server.ts'"` on nodemon -v: 2.0.15
