### ISSUE TITLE
zsh: command not found: nodemon

### ISSUE THREAD

**Issue by neelchanda** [remy/nodemon#1644]
- `nodemon -v`: 2.0.1 (Cannot run `nodemon -v` have to run `npm view -g nodemon version`)
- `node -v`: 12.13.1
- Operating system/terminal environment: macOS Catalina 10.15.1 / zsh
- Using Docker? What image: N/A
- Command you ran: `nodemon index.js`

### Expected behaviour
After installing globally with `npm i -g nodemon` should be able to run `nodemon` command in any node project file. 

### Actual behaviour
`zsh: command not found: nodemon`

### Steps to reproduce
1. Ran `npm i -g nodemon`
2. cd into node project directory
3. Ran `nodemon index.js`

### Also Tried
Uninstalling and reinstalling nodemon globally, yet getting the same response of `zsh: command not found: nodemon` whenever trying to run the nodemon command

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by neelchanda** [comment]
Also noticed this is a dupe of a previous issue. Reposting because I attempted uninstalling node / npm / and nodemon all together. After reinstalling, I'm still having the same issue 🙃

**Comment by neelchanda** [comment]
_UPDATE_

Seems like installing node using homebrew was the culprit. Uninstalled node with `brew uninstall`, reinstalled node without brew, and everything works now

**Comment by superhackerboy** [comment]
I'm getting this problem having installed npm via their website. Can't figure it out.

**Comment by neelchanda** [comment]
I’ve had this issue after updating Mac OS to Catalina. Haven’t had issues since I changed NPM’s default directory. 

Try following the steps here: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by lubuggiano** [comment]
SOLUTION: 
...
in your package.json add:

"scripts": {
    "auto": "npx nodemon server.js"
  },
...
then run:

npm run auto

**Comment by SPH73** [comment]
> SOLUTION:
> ...
> in your package.json add:
> 
> "scripts": {
> "auto": "npx nodemon server.js"
> },
> ...
> then run:
> 
> npm run auto

This solution has worked for me today when nothing else did - thank you to @lubuggiano

**Comment by michaelhardie63** [comment]
> > SOLUTION:
> > ...
> > in your package.json add:
> > "scripts": {
> > "auto": "npx nodemon server.js"
> > },
> > ...
> > then run:
> > npm run auto
> 
> This solution has worked for me today when nothing else did - thank you to @lubuggiano

This was an amazing fix thank you :)
