### ISSUE TITLE
how can I exit on "clean exit - waiting for changes before restart"

### ISSUE THREAD

**Issue by dave-dm** [remy/nodemon#1645]
I need nodemon to exit on clean exit, not wait for changes. I only need it to restart if I make changes to files.

If not possible, does anyone know a way to restart on file change, but exit on error/clean exit? Maybe using some other program. I wouldn't mind modifying nodemon either if needed, just need to know where/how.

**Comment by remy** [comment]
You might be able to require nodemon and use the event handlers to do this, or just use chokidar directly, but this requirement is outside the scope of what nodemon should do - so I'll close this as an issue (I keep issues to problems that need resolution).

Thanks

**Comment by ccheever** [comment]
@dave-dm A way that I was able to get this to happen was to use `patch-package` with this patch:

```
--- a/node_modules/nodemon/lib/monitor/run.js
+++ b/node_modules/nodemon/lib/monitor/run.js
@@ -209,6 +209,7 @@ function run(options) {
       }
 
       if (code === 0) { // clean exit - wait until file change to restart
+        process.exit();
         if (runCmd) {
           utils.log.status('clean exit - waiting for changes before restart');
         }
```
