### ISSUE TITLE
editing any file restarts the bot

### ISSUE THREAD

**Issue by ProgrammerPlays** [remy/nodemon#1646]
- `nodemon -v`: 2.0.1
- `node -v`: 10.15.2
- Operating system/terminal environment: Ubuntu 19.10, tmux
- Using Docker? What image: None
- Command you ran: nodemon --inspect=127.0.0.1=9223

By 'bot', I mean Discord.js bot.

### Expected behaviour
The bot is supposed to normallly write to files (like my database.json and database-level.json) and the bot continues to run.

### Actual behaviour
Whenever the bot edits any files (like database files for example), it restarts the bot because of a "file change".

### Steps to reproduce
1. Make a Discord.js bot that edits files with fs.writeFile().
2. Have a JSON file that get parsed at the beginning.
3. Have it write to the JSON file.

---

Extra: this happens with pretty much any files in the directory. If this isn't an issue, how can I override it? 

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Please provide a screenshot of the full running command and the restart with `--verbose` passed to nodemon

**Comment by remy** [comment]
There's no much info, but nodemon will restart when .json files are touched. So, change this to `nodemon --ext js`.

Otherwise, I'm struggling with the "Make a Discord.js bot" 😄 

I'm pretty sure it's nodemon watching the json file, so I'll close on that assumption.
