### ISSUE TITLE
High CPU usage within docker when using -L

### ISSUE THREAD

**Issue by timcosta-tempus** [remy/nodemon#1648]
- `nodemon -v`: v2.0.1
- `node -v`: v10.17.0
- Operating system/terminal environment:
  - Host:
    - macOS 10.15.1
    - zsh in iTerm
  - Container:
    - [node:dubnium](https://github.com/nodejs/docker-node/blob/f5875531604b4b3b9fbc36437182781c3655c8ae/10/stretch/Dockerfile)
    - Version listed are from within the container
- Using Docker? What image: `node:dubnium`
- Command you ran:
```bash
NODE_ENV=development nodemon -L --watch src index.js
```

### Expected behaviour
nodemon watches the src directory for changes and idles at low-ish CPU due to polling in chokidar.

### Actual behaviour
I have an 6 physical/12 virtual core 2019 MBP that runs at 50-65% usage total full time with the above command. output with `-V` is
```bash
web_1   | > NODE_ENV=development nodemon -V -L --watch src index.js
web_1   |
web_1   | [nodemon] 2.0.1
web_1   | [nodemon] to restart at any time, enter `rs`
web_1   | [nodemon] or send SIGHUP to 18 to restart
web_1   | [nodemon] watching dir(s): src/**/*
web_1   | [nodemon] watching extensions: js,mjs,json
web_1   | [nodemon] starting `node index.js`
web_1   | [nodemon] forking
web_1   | [nodemon] child pid: 31
web_1   | [nodemon] watching 594 files
```

Given that the `-L` flag is required for seeing changes when in docker using mounted volumes, i hope it's possible to somehow relax the polling as to not peg half of a top of the line CPU.

### Steps to reproduce
Run nodemon with `-L` in docker.

**Comment by remy** [comment]
`-L` doesn't use chokidar, it uses `find` to poll all files, so this is expected whilst having to fall back to the legacy mode.

Sorry I can't be more help on this.

**Comment by carlos00027** [comment]
+1
