### ISSUE TITLE
Feature Request - Please add a command to quit nodemon.

### ISSUE THREAD

**Issue by jennifer-abu** [remy/nodemon#1651]
Feature request:

Can we have a **quit** command similar to the **restart** command **rs**.

Maybe something like **stop**, **quit**, or **exit**.

Currently I hit Control C but I prefer not to do it this way.

Thanks for your consideration.

**Comment by razielll** [comment]
ye, something like

var nodemon = require('nodemon');

// force a quit
nodemon.emit('quit');

https://stackoverflow.com/questions/43832516/cant-stop-server-running-by-nodemon

**Comment by jennifer-abu** [comment]
I should have been more specific for the feature request.

Something I can enter in the bash shell.  You can type **rs** into the bash shell and I also want to be able to type **quit**.

I already know how to stop it using Control C and I have seen that post which uses JavaScript.

Thanks for your consideration.

**Comment by Haple** [comment]
What is the problem with Ctrl + C?

**Comment by jennifer-abu** [comment]
There is no "problem" with Ctrl + C, that is why I submitted this as a "feature request".  I was assuming it would be easy to add this feature.

**Comment by remy** [comment]
I think the best path for this request is to use nodemon as a required module and emit quit when "quit" or some other input is entered. 

It doesn't quite make sense as a feature for nodemon (going by the design principles).

Though, I'm not so sure it's "easy" there's a bit of messing you have to do on stdin - but if you look at lib/nodemon.js you'll find clues there.
