### ISSUE TITLE
nodemon not really restarting

### ISSUE THREAD

**Issue by TheAndroidGuy** [remy/nodemon#1652]
Suddenly nodemon stopped properly restarting the app. I am using globally installed version of nodemon.

- `nodemon -v`: `2.0.2`
- `node -v`: `v13.0.1`
- Operating system/terminal environment: `Windows 10 x64` - `command prompt`
- Using Docker? What image:  `no`
- Command you ran: `nodemon`

### Expected behaviour
I am not an expert but i think when it restarts the app it should also print the console logs i have in the `app.js` but it only prints them when i stop the execution and run `nodemon` manually.
Also `rs` is not working. (i can't enter anything in the console except `ctrl+c`)

### Actual behaviour
Not really restarting the app.

### Steps to reproduce
```
C:\Users\Aleksandar\Desktop\ETES>nodemon
[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
app running on port: 3001
[nodemon] restarting due to changes...
GET /products/142318/edit 200 120.430 ms - 46459
GET /products/142318/edit 200 26.663 ms - 46459
[nodemon] restarting due to changes...
GET /products/142318/edit 200 18.230 ms - 46459
GET /products/142318/edit 200 15.528 ms - 46459
```

---

```
{
  "name": "etes",
  "version": "0.0.0",
  "main": "app.js",
  "private": true,
  "scripts": {
    "start": "node app.js"
  },
  "dependencies": {
    "@hapi/joi": "^16.1.8",
    "body-parser": "^1.19.0",
    "cookie-parser": "~1.4.4",
    "cors": "^2.8.5",
    "debug": "~2.6.9",
    "ejs": "^3.0.1",
    "express": "~4.16.1",
    "knex": "^0.20.1",
    "morgan": "~1.9.1",
    "mysql": "^2.17.1",
    "wkhtmltopdf": "^0.3.4"
  },
  "devDependencies": {}
}
```

```
[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
--------------
node: v13.0.1
nodemon: 2.0.2
command: C:\Program Files\nodejs\node.exe C:\Users\Aleksandar\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.js --dump
cwd: C:\Users\Aleksandar\Desktop\ETES
OS: win32 x64
--------------

{
  run: false,
  system: { cwd: 'C:\\Users\\Aleksandar\\Desktop\\ETES' },
  required: false,
  dirs: [ 'C:\\Users\\Aleksandar\\Desktop\\ETES' ],
  timeout: 1000,
  options: {
    dump: true,
    ignore: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**',
      re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/
    ],
    watch: [ '*.*', re: /.*\..*/ ],
    ignoreRoot: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**'
    ],
    restartable: 'rs',
    colours: true,
    execMap: { py: 'python', rb: 'ruby', ts: 'ts-node' },
    stdin: true,
    runOnChangeOnly: false,
    verbose: false,
    signal: 'SIGUSR2',
    stdout: true,
    watchOptions: {},
    execOptions: {
      script: 'app.js',
      exec: 'node',
      args: [],
      scriptPosition: 0,
      nodeArgs: undefined,
      execArgs: [],
      ext: 'js,mjs,json',
      env: {}
    },
    monitor: [
      '*.*',
      '!**/.git/**',
      '!**/.nyc_output/**',
      '!**/.sass-cache/**',
      '!**/bower_components/**',
      '!**/coverage/**',
      '!**/node_modules/**'
    ]
  },
  load: [Function (anonymous)],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  signal: 'SIGUSR2',
  command: {
    raw: { executable: 'node', args: [ 'app.js' ] },
    string: 'node app.js'
  }
}

```

**Comment by razielll** [comment]
Hi, that sounds alittle weird.
If you run node app.js from native terminal (windows or linux), does rs work there ? 
(assuming you're running in VScode's built in terminal)

secondly, add console.log('1') in app.js (while nodemon app.js is running) and start hitting ctrl+s (save), your terminal's console isn't showing the console logs ?
For further debug i'll run 'nodemon app.js' in the root, instead of the nodemon script, tho i really do not think that that has anything to do with it.

Sorry for so much text, i think its related to your environment and not nodemon.

**Comment by TheAndroidGuy** [comment]
@razielll Thank you for your interest.
It does not work from native terminal too. I was running it previously from there but i also tried from `vscode` because you mentioned it.
I was doing some testing and this is what i noticed.
![screen fw](https://user-images.githubusercontent.com/17319245/70856315-17d8a800-1eda-11ea-986c-0b886ebc431b.png)

**Comment by razielll** [comment]
Ok, this is a long shot but i feel you have a permission issue.
Try (if not already) running cmd as administrator and reproduce this.
Interesting bug, as you can see, nodemon works OK, your system is hanging the process thread, or so it seems/feels, to me.

thanks for the update

**Comment by TheAndroidGuy** [comment]
@razielll I tried running cmd as administrator but it is the same as regular cmd.
Could `windows linux subsystem` have something to do with this problem? That, and `wkhtmltopdf` are the last things i remember installed before this problem started) To be honest IDK why i enabled `windows linux subsystem` from `windows features`, but i unchecked it later, and nodemon still doesn't work)

**Comment by razielll** [comment]
Before going to permissions and stuff in the linux sub system,
uninstall nodemon from npm, and go, sudo npm install -g nodemon.

good luck

**Comment by TheAndroidGuy** [comment]
I am using Windows. I tried reinstalling nodemon as administrator but nothing works.
Maybe I will try making restore point or reinstall windows.

**Comment by TheAndroidGuy** [comment]
I tried restoring previous system changes but it still doesn't work.
I also tried the app on another machine and nodemon works fine.
Since the issue is probably not with nodemon, I am closing this issue.
