### ISSUE TITLE
How to add file extension to package.json config!?

### ISSUE THREAD

**Issue by blaasvaer** [remy/nodemon#1654]
Is it just me or are these docs completely 'unfinished' ... how do I add file extensions to the package.json config part for nodemon!?

Please, provide a COMPLETE example of how to configure nodemon using the package.json file when you claim that you can use it for that purpose ... the one provided (removing the weird bits) is not working.

**Comment by remy** [comment]
Which "one" is provided?

**Comment by blaasvaer** [comment]
Exactly – not clear at all. Under the paragraph with the headline of “package.json” is a code snippet ... but in my case I managed to wild guess my way through with the use of google. Maybe just clear the readme completely and replace it with a link to the google search engine?
