### ISSUE TITLE
Error while installing nodemon globally

### ISSUE THREAD

**Issue by alogim** [remy/nodemon#1658]
I am a relative newbie to `node` and `npm` but still I think this should not happen.
I am running Archlinux with the following:

- `nodemon -v`: 2.0.2
- `node -v`: 13.5.0 
- `npm -v`: 6.13.4
- Operating system/terminal environment: Archlinux with xfce4-terminal
- Command you ran: `sudo npm install -g nodemon` 

### Expected behaviour
Should install the package globally with no errors.

### Actual behaviour
Displays the following
```
<blah>/.nvm/versions/node/v13.5.0/bin/nodemon -> <blah>/.nvm/versions/node/v13.5.0/lib/node_modules/nodemon/bin/nodemon.js

> nodemon@2.0.2 postinstall <blah>/.nvm/versions/node/v13.5.0/lib/node_modules/nodemon
> node bin/postinstall || exit 0

internal/modules/cjs/loader.js:969
    throw err;
    ^

Error: Cannot find module '<blah>/.nvm/versions/node/v13.5.0/lib/node_modules/nodemon/bin/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/nodemon/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ nodemon@2.0.2
updated 1 package in 17.053s
```

**Comment by tonylucaas** [comment]
please, anyone? i'm with the same issue

**Comment by remy** [comment]
Try without `sudo`?

This isn't a nodemon problem but related to the operating system and how your permissions are set up.

**Comment by deeRAWAT** [comment]
@remy 
It is showing the error 
I tried running the command:   npm install nodemon -g


And the following error came:
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/lib/node_modules/nodemon
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/nodemon'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/nodemon'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/lib/node_modules/nodemon'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/deepanshu/.npm/_logs/2020-10-30T11_33_09_315Z-debug.log

(using linux mint 19.1)

**Comment by remy** [comment]
@deeRAWAT 

> permission denied, mkdir '/usr/lib

There's your problem.
