### ISSUE TITLE
l have this questions,and can't resolve it,it is here:

### ISSUE THREAD

**Issue by Jackwew** [remy/nodemon#1660]
[nodemon] clean exit - waiting for changes before restart
```js
(node:15160) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, mkdir 'D:\web_rd_project\www\n-dist\components'
(node:15160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated 
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[nodemon] clean exit - waiting for changes before restart
```

I don't know where the configuration is not written correctly, and I don't seem to write the nodemon configuration file separately

Hope you can help me, thanks!

**Comment by remy** [comment]
You didn't actually ask a question. Though looking at the dump of output there looks to be a bug in your code. To rule nodemon out, remove it from the code execution

**Comment by Jackwew** [comment]
There is no error in the code, it appears, when I start the project, `` js [nodemon] clean exit-waiting for changes before restart` '' appears in the console. When this line of code, I just need to enter rs in the console to restart nodemon can run my project normally. But I want to know what causes this situation.
I use the project built by nuxt + kor2,thanks
