### ISSUE TITLE
Feature request: add an option to filter the running process output

### ISSUE THREAD

**Issue by dko-slapdash** [remy/nodemon#1662]
Currently to hide some non-interesting output lines in the running process, we have to do:

```
nodemon -q --inspect=0.0.0.0:9229 dist/worker.* 2>&1 | egrep --line-buffered -v 'Debugger listening on|For help, see: https://nodejs.org'
```

This is a little ugly (and it also loses the exitcode of the process since it returns the exitcode of grep). Since nodemon is a dev tool, would be cool if nodemonConfig had an option for this:

```
"nodemonConfig": {
  ...
  "stderrFilter": [
    "Debugger listening on|For help, see: https://nodejs.org"
  ],
  "stdoutFilter": "something-else"
}
```

**Comment by remy** [comment]
I won't implement this in core of nodemon (see design principles), but you'd be able to extend nodemon by requiring it and adding this to your own runner 👍
