### ISSUE TITLE
The token '||' is not a valid statement separator in this version.

### ISSUE THREAD

**Issue by mankinchi** [remy/nodemon#1663]
- `nodemon -v`: Can't install (i'm doing locally)
- `node -v`:  12.10.0
- Operating system/terminal environment: Window 10
- Using Docker? What image: None
- Command you ran:
npm i nodemon --save-dev

### Expected behaviour
Install correctly

### Actual behaviour
`node bin/postinstall || exit 0`
`At line:1 char:22
+ node bin/postinstall || exit 0
+                      ~~
The token '||' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine`

### Steps to reproduce
- Create empty folder
- Run `npm init` with all default value
- Run `npm i nodemon--save-dev`

**Comment by remy** [comment]
Is this using powershell? (The issue does ask but it's not clear from your answer so hard to debug)

**Comment by Alchemistst** [comment]
I have been having this issue as well. I'm ussing powershell 6 (also tried with powershell 5.1 and got the same result).

As OP mentions, this is what I've done:
`
npm init
`
Everything goes all right. Then I execute:
`
npm install nodemon --save-dev
`
And the output I get is this:
`
> node bin/postinstall || exit 0

At line:1 char:22
+ node bin/postinstall || exit 0
+                      ~~
The token '||' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine
 
npm WARN index.js@1.0.0 No description
npm WARN index.js@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodemon@2.0.2 postinstall: `node bin/postinstall || exit 0`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodemon@2.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Javi\AppData\Roaming\npm-cache\_logs\2020-02-09T13_01_40_897Z-debug.log
`

I have previously used nodemon (a month ago probably) in another project through this exact same install command and everything worked fine. Now, in that project, deleting the node_modules folder and running npm install yields the same output as above.
It seems there's something wrong with the command node bin/postinstall || exit 0
'||' is not a powershell operator.

I'm glad to give any more details if needed.

**Comment by remy** [comment]
Needs to run on windows to investigate alternative fix.

**Comment by remy** [comment]
I can't replicate this at all. I've provisioned a Windows 10 machine from AWS and connect to it using Windows Remote Client, then go through the motion.

Attached is a screenshot of Powershell running the postinstall command, without error and I'm on a 5.x version of PS. 

<img width="1262" alt="Screenshot 2020-04-08 at 20 42 18" src="https://user-images.githubusercontent.com/13700/78826497-7d94f680-79d9-11ea-9939-293307231860.png">

If anyone is able to replicate this in a parred down example and able to offer a fix to the || statement, I'd love to hear about it.

I'll leave this open for the time being, but if it remains inactive, it'll close by itself (I hope that's fine).

**Comment by ttomm** [comment]
I have the same problem.
I use Windows 10, I have Nodemon installed globally in version 2.0.3, but when I try to install  Nodemon locally, in project folder, I get the same error

![image](https://user-images.githubusercontent.com/10185576/79041679-dd65ea00-7bf1-11ea-8268-17e372833645.png)

So I downloadad Nodemon from https://github.com/remy/nodemon as a zip file and unpacked next to my project folder , after that I removed `|| exit 0` from package.json and from my project folder I ran command 
```
npm install ../nodemon-master
```

This not-very-elegant workaround works.

**Comment by remy** [comment]
And what if you do what I did and run the npm script directly? (In the name
of solving this issue)

**Comment by Alchemistst** [comment]
I ended up switiching to Linux. Definitely not the best solution, but had the chance to do it and did it. Working seamlessly on Linux.

**Comment by karanloona** [comment]
> I have been having this issue as well. I'm ussing powershell 6 (also tried with powershell 5.1 and got the same result).
> 
> As OP mentions, this is what I've done:
> 
> ```
> `
> npm init
> `
> Everything goes all right. Then I execute:
> `
> npm install nodemon --save-dev
> `
> And the output I get is this:
> `
> > node bin/postinstall || exit 0
> 
> At line:1 char:22
> + node bin/postinstall || exit 0
> +                      ~~
> The token '||' is not a valid statement separator in this version.
>     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
>     + FullyQualifiedErrorId : InvalidEndOfLine
>  
> npm WARN index.js@1.0.0 No description
> npm WARN index.js@1.0.0 No repository field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! nodemon@2.0.2 postinstall: `node bin/postinstall || exit 0`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the nodemon@2.0.2 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Javi\AppData\Roaming\npm-cache\_logs\2020-02-09T13_01_40_897Z-debug.log
> ```
> 
> I have previously used nodemon (a month ago probably) in another project through this exact same install command and everything worked fine. Now, in that project, deleting the node_modules folder and running npm install yields the same output as above.
> It seems there's something wrong with the command node bin/postinstall || exit 0
> '||' is not a powershell operator.
> 
> I'm glad to give any more details if needed.

Same error with me

**Comment by remy** [comment]
I [tried](https://github.com/remy/nodemon/issues/1663#issuecomment-611155999) to replicate this and could not. And since no one was posting any pull requests to fix it, it'll close itself and won't be fixed. 

I'm going to close this and encourage anyone who _is_ able to replicate to offer a solution that allows the `OR exit 0` to run cross platform. Thanks in advance.

**Comment by FieryRMS** [comment]
Hi all,
I managed to fix it sort of, run the following commands in order,
```
npm config set script-shell cmd

npm i nodemon

npm config set script-shell powershell
```

and for anyone trying to replicate the problem, run, ```npm config set script-shell powershell``` before ```npm i nodemon```
hope it help!

**Comment by ArmaanTechDeveloper** [comment]
> * `nodemon -v`: Can't install (i'm doing locally)
> * `node -v`:  12.10.0
> * Operating system/terminal environment: Window 10
> * Using Docker? What image: None
> * Command you ran:
>   npm i nodemon --save-dev
> 
> ### Expected behaviour
> Install correctly
> 
> ### Actual behaviour
> `node bin/postinstall || exit 0` `At line:1 char:22
> 
> * node bin/postinstall || exit 0
> * ```
>                    ~~
>   ```
> 
> The token '||' is not a valid statement separator in this version. + CategoryInfo : ParserError: (:) [], ParentContainsErrorRecordException + FullyQualifiedErrorId : InvalidEndOfLine`
> 
> ### Steps to reproduce
> * Create empty folder
> * Run `npm init` with all default value
> * Run `npm i nodemon--save-dev`

same error with me

**Comment by remy** [comment]
@ArmaanTechDeveloper did you try the fix (literally the last comment): `npm config set script-shell powershell`?
