### ISSUE TITLE
[ERROR] RUN npm install -g nodemon

### ISSUE THREAD

**Issue by ffakenz** [remy/nodemon#1664]
- `nodemon -v`: n/a
- `node -v`: n/a
- Operating system/terminal environment:  MacOs (darwin/amd64) /zsh
- Using Docker? What image: Docker Engine - Community Version: 19.03.5
- Command you ran: 
```
npm install -g nodemon
```

### Expected behaviour
install nodemon

### Actual behaviour
in some Dockerfile:
```
Step 9/11 : RUN npm install -g nodemon
 ---> Running in 1aeffe18a7d6
npm ERR! Unexpected end of JSON input while parsing near '...25DIOthpiaHNIthsjEFQD'
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-22T14_46_49_215Z-debug.log
ERROR: Service 'api-mockserver' failed to build: The command '/bin/sh -c npm install -g nodemon' returned a non-zero code: 1
```

### Steps to reproduce
run:
```
npm install -g nodemon
```

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
you might have to share the dockerfile, but this isn't a problem with nodemon. I partly suspect you can't do a global install from the dockerfile, but I don't know docker well enough to say or not.

In particular the `Unexpected end of JSON input while parsing near '...25DIOthpiaHNIthsjEFQD'` makse me think it's something in the docker env.

**Comment by ffakenz** [comment]
Thanks a lot for the help and support @remy NPM registry was down. 
Now i was able to pull it and works perfectly !
Appreciate the consideration.
Regards!
