### ISSUE TITLE
[QUESTION] Can it restart app without files changed?

### ISSUE THREAD

**Issue by Serhioromano** [remy/nodemon#1665]
Let's say I have an app, and it is running in production. At some point for some reason, it fails because of some user actions that might not be even reproduced. Can I restart the app without changing files?

**Comment by remy** [comment]
You would have to write a bespoke script to use nodemon as a required module: https://github.com/remy/nodemon/blob/master/doc/requireable.md

Of course, this is theoretical because you wouldn't run a tool for development in production.

**Comment by Serhioromano** [comment]
Thank you. That is to complicated. ш found a script called forever, which does exactly what I need.

**Comment by remy** [comment]
Yep, forever is better suited to exactly what you're trying to do 👍
