### ISSUE TITLE
Failing test on Node 12.14.1?

### ISSUE THREAD

**Issue by DanielRuf** [remy/nodemon#1670]
It seems some test is failing on Node 12.14.1 which looks like an issue with chokidar.

https://travis-ci.org/remy/nodemon/builds/640516797
https://travis-ci.org/remy/nodemon/jobs/640516798#L471

Woth 12.13.0 it still works:
https://github.com/DanielRuf/nodemon/pull/1
https://travis-ci.com/DanielRuf/nodemon/builds/146513225

I'm not yet sure why this is the case.

**Comment by DanielRuf** [comment]
Not stale.

**Comment by DanielRuf** [comment]
Not stale.

**Comment by DanielRuf** [comment]
Still not stale.

**Comment by DanielRuf** [comment]
Still not stale.

**Comment by remy** [comment]
I've fixed this…sort of. Certainly it passes if you re-run enough times! It's part race condition, part "nodemon's test fork a lot of sub-processes that then fork the script to check and eventually gets messed up".

**Comment by DanielRuf** [comment]
Great to read that it works now @remy =) I think this can be improved in the future so it's more stable then. But that is another issue.
