### ISSUE TITLE
Crash when extension watchlist specified in package.json

### ISSUE THREAD

**Issue by kjhx** [remy/nodemon#1676]
- `nodemon -v`: 2.0.2
- `node -v`: 13.0.1
- Operating system/terminal environment: macOS 10.15.3 / Hyper 3.0.2
- Using Docker? What image: NA
- Command you ran: `nodemon .`

### Expected behaviour
`nodemon` is expected to run with the given parameters I have in `nodemonConfig`, as specified later in the issue.

### Actual behaviour
`nodemon` fails to start, throwing the error seen below.

### Steps to reproduce
1. Add `ext` array (with some extensions) to `nodemonConfig` in `package.json`. Here's an example, taken straight from my `package.json`:
```
"nodemonConfig": {
    "ignore": [
      "sessions/*"
    ],
    "ext": [
      "js",
      "scss",
      "hbs"
    ],
    "verbose": "true"
  }
```
2. Run `nodemon .`

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.
```
/Users/kjhx/Documents/Develop/express-template/node_modules/nodemon/lib/config/exec.js:205
  extension = (extension.match(/[^,*\s]+/g) || [])
                         ^

TypeError: extension.match is not a function
    at exec (/Users/kjhx/Documents/Develop/express-template/node_modules/nodemon/lib/config/exec.js:205:26)
    at mutateExecOptions (/Users/kjhx/Documents/Develop/express-template/node_modules/nodemon/lib/config/load.js:236:25)
    at /Users/kjhx/Documents/Develop/express-template/node_modules/nodemon/lib/config/load.js:86:7
    at callback (/Users/kjhx/Documents/Develop/express-template/node_modules/nodemon/lib/config/load.js:177:5)
    at /Users/kjhx/Documents/Develop/express-template/node_modules/nodemon/lib/config/load.js:230:5
    at callback (/Users/kjhx/Documents/Develop/express-template/node_modules/nodemon/lib/config/load.js:177:5)
    at /Users/kjhx/Documents/Develop/express-template/node_modules/nodemon/lib/config/load.js:217:5
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
```

**Comment by breytex** [comment]
I can confirm this issue on 2.0.2.

**Comment by clemsos** [comment]
Same issue here

**Comment by remy** [comment]
Anyone working on this?

**Comment by albertopoljak** [comment]
Same here..

**Comment by pqvst** [comment]
It seems the extension list should be specified as a comma-separated list instead of an array. This works for me:

```
"ext": "js,json,md"
```
