### ISSUE TITLE
STDIN breaks inconsistently after refreshing from an error state

### ISSUE THREAD

**Issue by josh-hemphill** [remy/nodemon#1677]
- `nodemon -v`: ^1.19.4
- `node -v`: v13.3.0
- Operating system/terminal environment: Windows/Git Bash
- Using Docker? What image: 
- Command you ran: nodemon -e js --exec "node ..\\external\\secret.js | node server.js"

### Expected behaviour
Run consistently, at least always give me an error.

### Actual behaviour
Somehow, I get trapped getting errors if my code produces an error in a refresh.
Sometimes, not consistent with any other events that I can tell, I keep getting the error below every time I try and refresh. I can open a new shell terminal, I can close/reopen all shell terminals on the system, but every time I try and run the command it spits out this error.
If I wait for another 5-10min, it seems to just go away on its own.  

I'm getting an error from node's built-in fs module:
internal/fs/utils.js:227
    throw err;
Error: EOF: end of file, read
errno: -4095,
  syscall: 'read',
  code: 'EOF'

### Steps to reproduce
Run a express server that blocks on being initialized from data from stdin, then add a throw at the beginning, save/refresh through nodemon, remove the throw and attempt to run again.
Like I said this seems to be entirely unpredictable; so sometimes I'll have to add/remove the throw a couple times or restart my shell.

```javascript
// Source file
const objectToWrite = { somedata:'someval' }
process.stdout.write(JSON.stringify(objectToWrite));
process.stdout.end('\n');
// I've messed around with various STDIO implementations
// and it doesn't seem to have any affect the error.

// Receiving file
const fs = require('fs')
let envTmp = fs.readFileSync(0).toString();
// breaks on fs utils here ^
	envTmp = JSON.parse(envTmp);
```

---
<details><summary>Dump Text</summary>

<p>

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js
--------------
node: v13.3.0
nodemon: 1.19.4
command: C:\Program Files\nodejs\node.exe bin\nodemon.js -e js --exec node ..\secret.js | node server.js --dump
OS: win32 x64
--------------
```lang-json
{
  run: false,
  required: false,
  timeout: 1000,
  options: {
    exec: 'node ..\\secret.js | node server.js',
    dump: true,
    ignore: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**',
      re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/
    ],
    watch: [ '*.*', re: /.*\..*/ ],
    ignoreRoot: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**'
    ],
    restartable: 'rs',
    colours: true,
    execMap: { py: 'python', rb: 'ruby', ts: 'ts-node' },
    stdin: true,
    runOnChangeOnly: false,
    verbose: false,
    signal: 'SIGUSR2',
    stdout: true,
    watchOptions: {},
    execOptions: {
      script: null,
      exec: 'node ..\\secret.js | node server.js',
      args: [],
      scriptPosition: null,
      nodeArgs: undefined,
      execArgs: [],
      ext: 'js',
      env: {}
    },
    monitor: [
      '*.*',
      '!**/.git/**',
      '!**/.nyc_output/**',
      '!**/.sass-cache/**',
      '!**/bower_components/**',
      '!**/coverage/**',
      '!**/node_modules/**'
    ]
  },
  load: [Function (anonymous)],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  signal: 'SIGUSR2',
  command: {
    raw: {
      executable: 'node ..\\secret.js | node server.js',
      args: []
    },
    string: 'node ..\\secret.js | node server.js'
  }
}
```
</p>
</details>

**Comment by remy** [comment]
Can you provide a pared down code sample to run? Otherwise I can't reproduce.

**Comment by josh-hemphill** [comment]
Updated the post with the code used.

**Comment by josh-hemphill** [comment]
So in the time since, I've been getting the error pretty consistently when executing if I run it as an npm script, or directly via the terminal.
However when I have debugging enabled for node `node --inspect-brk=127.0.0.1:9229 server.js`, it works just fine. So it works under VSCode debugging whether in launch or attach mode. 

So it only breaks when not being debugged...  つ・_・つ

Also, I don't think I actually provided the whole `EOF` error, so here it is too.
<details><summary>EOF Error</summary>

<p>

```lang-js
internal/fs/utils.js:230
    throw err;
    ^

Error: EOF: end of file, read
    at Object.readSync (fs.js:564:3)
    at tryReadSync (fs.js:353:20)
    at Object.readFileSync (fs.js:390:19)
    at C:\*******\server.js:6:18
    at Object.<anonymous> (C:\*******\server.js:20:3)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  errno: -4095,
  syscall: 'read',
  code: 'EOF'
}
[nodemon] app crashed - waiting for file changes before starting...
```

</p>

</details>

**Comment by josh-hemphill** [comment]
I just refactored my code to wrap the whole thing in a `.then()` to use the normal `process.stdin` and now it doesn't seem to have any issues. 

Does nodemon try and detect if `stdin` is being used? Maybe it just missed `fs.readFileSync(0)`?
