### ISSUE TITLE
nodemon.emit('quit') does not work

### ISSUE THREAD

**Issue by moonformeli** [remy/nodemon#1678]
- `nodemon -v`: 2.0.2
- `node -v`: 12.14.0
- Operating system/terminal environment:  Mac OS Mojave
- Using Docker? What image: No
- Command you ran: The examples are below

### Expected behaviour
The nodemon should have been killed

### Actual behaviour
The nodmone isn't killed

### Steps to reproduce
```ts
// package.json
"nmon": "nodemon --config nodemon.dev.json"

// nodemon.dev.json
{
  "verbose": true,
  "watch": ["src/server/test.ts"],
  "exec": "ts-node --project tsconfig.dev.json src/server/test.ts",
  "ext": "ts",
  "env": {
    "DEBUG": "*"
  }
}

// test.ts
import nodemon from 'nodemon';

/* do some work */

nodemon.emit('quit');
```

The nodemon isn't killed like this.
![image](https://user-images.githubusercontent.com/25758965/74608662-80384580-5126-11ea-9bf3-cb4ce6bc71a2.png)

And what is worse is it keeps restarting the server if I remove `watch` property in `nodemon.dev.json`.

What am I missing?

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
The emit quit is to quit the subprocess not to stop nodemon. If you want to end nodemon watching you need to reset (I _think_).

**Comment by moonformeli** [comment]
Do you mean I need to reset the nodemon again?
I want to kill the nodemon completely, not to restart it

**Comment by remy** [comment]
If you're requiring nodemon, then to "quit nodemon" since it's part of your
code now, you need to quit your own program.
