### ISSUE TITLE
dot-prop vulnerability issue

### ISSUE THREAD

**Issue by PAnilReddy** [remy/nodemon#1682]
We wanted to know when can we get the fix for dop-prop vulnerability.
I see that the version of "update-notifier" is bumped up, which will sove this issue.
(refering to https://github.com/remy/nodemon/pull/1672/files)
Can we know when this will be released as we use nodemon and dot-prop is vulnerable and hence our product.

**Comment by remy** [comment]
Please can you review the change and let me know whether there's any breaking changes in the bump from 2 to 4 in update-notifier - then I'll be happy to jump in and merge.

Please also pass this back to the "we" that you refer to: nodemon is a development tool and the code doesn't leak into the memory or processes that run your software. Therefore, unless you're requiring nodemon _inside_ of your product, your product is unaffected by any vulnerability from the dot-prop module.

If however you _are_ using nodemon as a required module, then I'll expect this is a high priority to you (the "we" you mention) and you'll be keen to run the review on update-notifier.

I've updated the PR, please feel free to jump in there.
