### ISSUE TITLE
Allow apps to use own `--config` flag

### ISSUE THREAD

**Issue by brettz9** [remy/nodemon#1686]
- `nodemon -v`: 2.0.2
- `node -v`: 10.19.0
- Operating system/terminal environment:  Mac 10.15.2
- Using Docker? What image: No.
- Command you ran: `nodemon ./bin/cli.js --config myAppsConfig.js`

### Expected behaviour

While I understand there is a `--config` option, I'd like to avoid having to refactor my own app. Maybe `nodemon` could accept an argument like `--noNodemonConfig` which would disable checking `--config` (if you didn't want to deprecate `--config` entirely and just expect `--nodemonConfig` which would be nicely namespaced).

### Actual behaviour

`nodemon` reports that my JS file is poorly formed (nodemon is looking for a JSON file whereas my app uses `--config` with JS). There may have been no error if my app call had pointed to a JSON config, but this would still be a problem as `nodemon` would be treating that file as its own config (and perhaps not passing on the `--config` flag to my app).

### Steps to reproduce

1. Use nodemon with a `config` flag in the expectation it is only passed on to the app: `nodemon ./bin/cli.js --config myAppsConfig.js`
---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Use `--` to stop nodemon from eating arts, then place your arguments after this, so it reads `nodemon mycli -- --config=myConfig`

**Comment by brettz9** [comment]
Ah, yes, much appreciated, thanks a lot!

**Comment by courtneynguyen** [comment]
@remy  Can you do set the flag, `--` via the config option?
