### ISSUE TITLE
Restart event providing all filepaths to --exec

### ISSUE THREAD

**Issue by 8eecf0d2** [remy/nodemon#1688]
Following on from https://github.com/remy/nodemon/issues/227 which discussed passing the  changed filenames into the `--exec` script, the addition of [events](https://github.com/remy/nodemon/blob/master/doc/events.md) should have resolved this but does not seem to be working as documented when using the cli.

- `nodemon -v`:
```
2.0.2
```
- `node -v`:
```
v10.17.0
```
- Operating system/terminal environment: (`system_profiler SPSoftwareDataType`)
```
System Version: macOS 10.14.6 (18G103)
Kernel Version: Darwin 18.7.0
```

- Command you ran:
```bash
nodemon --watch **/*.uml --exec "echo files: $*"
```

### Expected behaviour
Only the updated filepaths are provided on restart.
```bash
nodemon --watch **/*.uml --exec "echo files: $*"
files: foo.uml bar.uml
# update foo.uml
files: foo.uml
```

### Actual behaviour
All of the watched filepaths are provided on restart.
```bash
nodemon --watch **/*.uml --exec "echo files: $*"
files: foo.uml bar.uml
# update foo.uml
files: foo.uml bar.uml
```
### Steps to reproduce
```bash
touch foo.uml bar.uml
nodemon --watch **/*.uml --exec "echo files: $*"
# update foo.uml
```

**Comment by remy** [comment]
As per the discussion you reference from 7 years ago, you can use nodemon as a required module to get the list of files changed. 

The exec arg doesn't get this - which is intended behaviour.
