### ISSUE TITLE
nodemon --exec causes warning and limitation of starting the server in ubuntu (18.04 bionic weaver)

### ISSUE THREAD

**Issue by esentai8** [remy/nodemon#1691]
I am setting up a basic server using node.js. When I use nodemon only, everythin works fine, however when I download babel packages (@babel/node @babel/cli @babel/core @babel/preset-env etc) I have to user babel-node after nodemon command so that babel translated older js to es 6. Right when I add --exec to nodemon I get warning message in the terminal about denied permission. Somehow --exec part leads to this warning and doesn't let the server run

- `nodemon -v`:2.0.2
- `node -v`:12.16.1
- Operating system/terminal environment: Ubuntu (Bionic Weaver 18.04)
- Using Docker? What image: No
- Command you ran: npm run dev where dev script in package.json is set to "nodemon babel-node --exec src/server.js"

### Expected behaviour

server should start and keep running

### Actual behaviour

sh: 1: src/server.js Permission denied

### Steps to reproduce

npm run dev

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Your arguments are wrong: nodemon babel-node --exec src/server.js

This says: "use src/index.js to run the script called babel-node".

I think you want: 

  nodemon --exec babel-node src/index.js
