### ISSUE TITLE
Dependent packages are not getting updated with latest version of nodemon

### ISSUE THREAD

**Issue by Sarita-persi** [remy/nodemon#1694]
Below is the nested packages I have on my package-lock.json 

Here even if in package.json I have latest nodemon version still its dependent packages are taking older versions hence throwing errors in my Scan Reports to update the version of package "strip-json-comments".
 
"nodemon" : 2.0.2 (latest)
{
    "update-notifier" : "version": "2.5.0" (latest should be - 4.1.0)
    {
        "latest-version": "version": "3.1.0" (latest should be - 5.1.0)
        {
            "package-json": "version": "4.0.1" (latest should be - 6.5.0)
            {
                "registry-auth-token": "version": "3.4.0" (latest should be - 4.1.1)
                {
		    "rc" : "version": "1.2.8" (already latest)
                    {
                        "strip-json-comments": "~2.0.1" (latest should be - 3.0.1)

**Comment by remy** [comment]
The update-notifier dep was at 2.x. There's a release going live this minute that bumps to 4.x which would create shuffle down the tree to update those deps.
