### ISSUE TITLE
Nodemon doesn't want to run file

### ISSUE THREAD

**Issue by jn531** [remy/nodemon#1698]
- Operating system/terminal environment: debian 9, terminal MATE
- Using Docker? What image: i don't know
- Command you ran:
nodemon index.js

when I want to run this file, appears the answer:
 ```
 Usage: nodemon [nodemon options] [script.js] [args]

  See "nodemon --help" for more.
```

sorry for my English, I'm from Poland

**Comment by remy** [comment]
And what happens when you run `node index.js` in the same location?
