### ISSUE TITLE
nodemon --inspect does not work

### ISSUE THREAD

**Issue by maxnest2006** [remy/nodemon#1699]
Hello! I can not understand why `nodemon --inspect` does not work.
The necessary logs are displayed:
```
Debugger listening on ws://127.0.0.1:9229/*****
For help, see: https://nodejs.org/en/docs/inspector
```
But connecting from the built-in Chrome inspector fails.
Although `node --inspect` works fine.
```
node 12.4.0
nodemon 2.0.3
```

**Comment by martincpt** [comment]
Any solution for this?

**Comment by mrmaxnest** [comment]
There was no problem. I inadvertently tried to debug the code that completes instantly.
