### ISSUE TITLE
What this is error about

### ISSUE THREAD

**Issue by karanloona** [remy/nodemon#1708]
![error4](https://user-images.githubusercontent.com/39923277/80030946-9ab3e400-8506-11ea-9bec-76c2b32b419d.png)

The debug.log file:- 

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\karanloona\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.13.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle testback@1.0.0~prestart: testback@1.0.0
6 info lifecycle testback@1.0.0~start: testback@1.0.0
7 verbose lifecycle testback@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle testback@1.0.0~start: PATH: C:\Users\karanloona\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\work\mern\testback\node_modules\.bin;C:\Users\karanloona\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Python38\Scripts\;C:\Python38\;C:\Program Files\Python37\Scripts\;C:\Program Files\Python37\;C:\Users\karanloona\AppData\Local\Programs\Python;C:\Windows\System32;C:\xampp\php;C:\composer;C:\Users\karanloona\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\karanloona\AppData\Roaming\npm;C:\Program Files\nodejs\;
9 verbose lifecycle testback@1.0.0~start: CWD: D:\work\mern\testback
10 silly lifecycle testback@1.0.0~start: Args: [ '-c', 'nodemon index.js' ]
11 info lifecycle testback@1.0.0~start: Failed to exec start script
12 silly lifecycle testback@1.0.0~start: Returned: code: -4058  signal: null
13 info lifecycle testback@1.0.0~start: Failed to exec start script
14 verbose stack Error: testback@1.0.0 start: `nodemon index.js`
14 verbose stack spawn bash ENOENT
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
14 verbose stack     at onErrorNT (internal/child_process.js:467:16)
14 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
15 verbose pkgid testback@1.0.0
16 verbose cwd D:\work\mern\testback
17 verbose Windows_NT 10.0.18363
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\karanloona\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v13.13.0
20 verbose npm  v6.14.4
21 error code ELIFECYCLE
22 error syscall spawn bash
23 error file bash
24 error path bash
25 error errno -4058
26 error testback@1.0.0 start: `nodemon index.js`
26 error spawn bash ENOENT
27 error Failed at the testback@1.0.0 start script.
27 error This is probably not a problem with npm. There is likely additional logging output above.
28 verbose exit [ -4058, true ]

**Comment by remy** [comment]
Something is hosed in your node_modules directory.

I'd be inclined to remove the entire directory and reinstall. This looks specific to your system and not nodemon (happy to reopen the issue if this a nodemon specific problem though).
