### ISSUE TITLE
Question: can I format the stdout of the subcommand?

### ISSUE THREAD

**Issue by mrmanc** [remy/nodemon#1713]
- `nodemon -v`: 2.0.3
- `node -v`: v13.12.0
- Operating system/terminal environment: MacOS
- Using Docker? What image: node/alpine
- Command you ran: n/a

I’m using a config file to intercept events and highlight errors using ANSI colours, but the output of the actual command I’m running still emits using the default colours. Is it possible to intercept stdout in the config file and prepend some colour codes?

**Comment by remy** [comment]
You need to require nodemon directly and either modify the colour stream or add to the plain text log stream

**Comment by mrmanc** [comment]
Got it… thank you!
