### ISSUE TITLE
nodemon does not relay env variables loaded from file (env-cmd) [Maybe a config Issue]

### ISSUE THREAD

**Issue by Codermar** [remy/nodemon#1717]
- `nodemon -v`: 2.0.3
- `node -v`: v12.16.3
- Operating system/terminal environment: MacOs
- Using Docker? What image: 
- Command you ran:

From package.json I run `yarn dev:watch:asc` which has the script entry below 

```"dev:watch:asc": "env-cmd -e dev-asc concurrently --kill-others \"yarn:dev:client\" \"yarn:dev:server:watch:asc\""```

Which uses the dev:server:watch script which is this:
```"dev:server:watch:asc": "env-cmd -e dev-asc nodemon ./src/server/index | bunyan --color"```

The package env-cmd is similar to cross-env allowing you to setup variables that are saved in a file. which is useful for me because I run an app with multiple tenants which have a couple of env vars setup differently. i.e. CONFIG_FILE_PATH

### Expected behaviour
Nodemon should honor and relay the env vars set from a previous script if they are performed in the same combined command.

### Actual behaviour
Nodemon runs but it ignores the env variables I set in the first script

### Steps to reproduce
NOTE: I can provide a repro repo if this is not just a configuration issue that a nodemon option maybe able to solve.
I tried adding env-cmd call in the execMap and it works but then I don't have a practical way to specify multiple tenants
---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Hi there, can you provide a pared down version of code that replicates the issue? This will help me grok the problem properly so that I can look to a fix.
