### ISSUE TITLE
Wildcards on paths to watch aren't matched

### ISSUE THREAD

**Issue by EmiSan1998** [remy/nodemon#1721]
- `nodemon -v`: v2.0.4
- `node -v`: v10.19.0
- Operating system/terminal environment: Ubuntu 20 on WSL running on Windows Terminal
- Using Docker? What image: 
- Command you ran: npx nodemon

### Expected behaviour
I'm trying to have Nodemon to watch the "src" subfolder of a serires of Angular libraries contained in the same directory without having to watch the whole library source, this way I can link some libraries to an Angular project, work on the libraries (which are on build --watch therefore they are rebuilt each time I save) and have the main project reloaded only when the library rebuild is completed (not when I save the source).
The confiuration which I'm using is
` 
"nodemonConfig": {
    "watch": [
      "../angular-libs-src/**/dist/"
    ],
    "ext": "html, css, js, ts"
  }
`
and the directory are organized this way

```
angularProject
|
|__angular-libs-src
    |
    |__ lib1
    |   |__ dist
    |__ lib2
    |   |__ dist
    |__ lib3
        |__ dist
```

### Actual behaviour
Nodemon not reloads the Angular project when one of the watched libraries is rebuild (therefore the content of the dist directory changes)

I want to know if the current version of Nodemon allows to use path wildcard on watch, if I'm using 
wildcards properly and if the feature isn't currently implemented if you would like me to implement it.

**Comment by remy** [comment]
Can you run with `DEBUG=nodemon:* nodemon <your args>` - this will list all the files it's watching and you'll be able to check whether it's actually watching those directories or not.
