### ISSUE TITLE
Specifying --signal results in "Cannot read property 'join' of null" on process restart

### ISSUE THREAD

**Issue by broofa** [remy/nodemon#1722]
```
$ nodemon -v
2.0.4

$ node --version
v12.10.0

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G95

$ cat index.js
while (true) {
}

$ nodemon --signal KILL index.js
[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js`
rs
/Users/kieffer/.nvm/versions/node/v12.10.0/lib/node_modules/nodemon/lib/monitor/run.js:366
      debug('sending kill signal to ' + pids.join(', '));
                                             ^

TypeError: Cannot read property 'join' of null
    at /Users/kieffer/.nvm/versions/node/v12.10.0/lib/node_modules/nodemon/lib/monitor/run.js:366:46
    at ChildProcess.<anonymous> (/Users/kieffer/.nvm/versions/node/v12.10.0/lib/node_modules/nodemon/node_modules/pstree.remy/lib/tree.js:34:7)
    at ChildProcess.emit (events.js:209:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

### Expected behaviour

Typing "rs\n" should restart the process

### Actual behaviour

Nodemon crashes with trace, above

### Steps to reproduce

* Run nodemon as above
* type "rs\n" to restart process
* **Crash**

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by broofa** [comment]
Figured this out.  I needed to specify `--signal SIGKILL`, not `--signall KILL`.  Closing, but it might be worth adding an assertion to validate that `sig` is [defined here](https://github.com/remy/nodemon/blob/496c3353c45362fb5cd010b73160925659005a0d/lib/monitor/run.js#L362).

**Comment by remy** [comment]
Validation: good shout, specifically as I'll know if the value is undefined. Cheers.
