### ISSUE TITLE
Question about release with undefsafe@2.0.3

### ISSUE THREAD

**Issue by PradoGuilherme** [remy/nodemon#1724]
Hey @remy,

I saw that you update `package.json` and `package-lock.json` with the `undefsafe@2.0.3`, but I didn't found it on the release `nodemon@2.0.4` which was performed on that day.

The release `nodemon@2.0.4` should contain this upgrade of undefsafe? 
If not, would you mind giving me an ETA of this upgrade version?

Best regards, thanks.

**Comment by remy** [comment]
Nodemon 2.x has always pointed to the latest 2.x.x version of undefsafe (thanks to semver), so all versions of nodemon carry the patched version.
