### ISSUE TITLE
Nodemon is starting process twice.

### ISSUE THREAD

**Issue by DevNoahh** [remy/nodemon#1725]
- `nodemon -v`: 2.0.4
- `node -v`: v14.2.0
- Operating system/terminal environment: Raspberry Pi Running on Raspbian Terminal (linux arm)
- Using Docker? What image: 
- Command you ran: nodemon bot.js

### Expected behavior
Runs a Discord Bot that I have made and restarts on file changes

### Actual behavior
It works, except nodemon is running my Bot twice, and making commands to the bot duplicate.

### Steps to reproduce

Simply starting your application
---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

{
  run: false,
  system: { cwd: '/home/pi/Desktop/NorCal' },
  required: false,
  dirs: [ '/home/pi/Desktop/NorCal' ],
  timeout: 1000,
  options: {
    dump: true,
    ignore: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**',
      re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/
    ],
    watch: [ '*.*', re: /.*\..*/ ],
    monitor: [
      '*.*',
      '!**/.git/**',
      '!**/.nyc_output/**',
      '!**/.sass-cache/**',
      '!**/bower_components/**',
      '!**/coverage/**',
      '!**/node_modules/**'
    ],
    ignoreRoot: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**'
    ],
    restartable: 'rs',
    colours: true,
    execMap: { py: 'python', rb: 'ruby', ts: 'ts-node' },
    stdin: true,
    runOnChangeOnly: false,
    verbose: false,
    signal: 'SIGUSR2',
    stdout: true,
    watchOptions: {},
    execOptions: {
      script: 'bot.js',
      exec: 'node',
      args: [],
      scriptPosition: 0,
      nodeArgs: undefined,
      execArgs: [],
      ext: 'js,mjs,json',
      env: {}
    }
  },
  load: [Function (anonymous)],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  signal: 'SIGUSR2',
  command: {
    raw: { executable: 'node', args: [ 'bot.js' ] },
    string: 'node bot.js'
  }
}

**Comment by DevNoahh** [comment]
Allow me to note that this is only happening on one file/project. All other projects are working fine with nodemon.

**Comment by DevNoahh** [comment]
This is happening with everything I run using nodemon with.

**Comment by remy** [comment]
@devnoahh and you're on node 14 too?

**Comment by DevNoahh** [comment]
Nodemon: 2.0.4
Node: v14.2.0

**Comment by DevNoahh** [comment]
Do you have any suspicions as to why?

**Comment by remy** [comment]
Node 14 is my suspicion - it's the common thread and the new factor.

**Comment by DevNoahh** [comment]
should I try an earlier version of node?

**Comment by DevNoahh** [comment]
@remy Switched to Node Version 13.0.1, working as of right now. So I am assuming it is Node 14. So far, everything is fine. If for some reason it does happen again on 13, I will let you know.

**Comment by alinwyr** [comment]
I have the same problem

**Comment by DevNoahh** [comment]
@alinwyr What os are you using. I can guide you toward a temporary fix

**Comment by alinwyr** [comment]
OS：Ubuntu 18.04.4 LTS 
node：v13.14.0
nodemon: v2.0.4

**Comment by alinwyr** [comment]
Thank you for your guidance。I've had this problem for days

**Comment by DevNoahh** [comment]
Ok, go to your terminal  run `npm install -g n`
Then type, `sudo n 13.0.1`
Then try, should work.
@alinwyr
