### ISSUE TITLE
Nodemon doesn't restart on file delete

### ISSUE THREAD

**Issue by creativiii** [remy/nodemon#1726]
- `nodemon -v`: 2.0.4
- `node -v`: v14.2.0
- Operating system/terminal environment: Linux Ubuntu 20.04
- Using Docker? What image: N/A
- Command you ran: N/A

### Expected behaviour
According to [this issue](https://github.com/remy/nodemon/issues/400), Nodemon should restart when a file is deleted as it does when a file is added.

### Actual behaviour
Nodemon doesn't restart at all. 
I'm unsure if this feature was added at some point and then removed or if this is a problem with my setup but I've not been able to get Nodemon to restart on file deletion.

It works just fine when I edit or add files.

Is there a workaround for this?

### Steps to reproduce

1. Have Nodemon watch your project root:
2. Delete a file
3. Nodemon doesn't restart

**Comment by remy** [comment]
Can you try the exact same process with node 13 or node 12?

**Comment by creativiii** [comment]
> Can you try the exact same process with node 13 or node 12?

Tried this on both `12.18.0` as well as `13.14.0`. Results were the same.
This is the command I'm using to watch:
```
    "start:dev": "nodemon --ext html,js,css --watch . --exec 'webpack-dev-server'",
```

**Comment by creativiii** [comment]
I've rolled back to `nodemon@1.4.2` out of curiosity and restart doesn't happen on file deletion.

**Comment by JGJP** [comment]
Sorry but why was this closed? This seems to be a valid issue and I'm experiencing the same issue with directories and files being added also.

**Comment by remy** [comment]
@JGJP it's closed because no one tried to fix it. It's what happens (the stalebot finds issues that are stale, that no one seems to care about, and closes them).

**Comment by JGJP** [comment]
Not personally a fan of using stalebot if nobody will judge the validity of the actual issue after the stale tag is added, especially if it doesn't even wait a month. I doubt that people looking to contribute will check closed issues.

**Comment by JGJP** [comment]
Also checking the issues and seeing 6 open vs 1333 closed makes it look like this repo doesn't need any help

**Comment by remy** [comment]
@JGJP noted, but that's just you. I've been running this project for a decade and only added the stalebot in the last 19 months. There's been 2 or maybe 3 significant fixed by people who aren't me. Also, I do judge and add not stale on important issues (you can see this). So, like I said, noted, but I'm afraid these are my rules for making this project even vaguely manageable.

**Comment by JGJP** [comment]
So nodemon not reacting to file deletion is not an important issue?

**Comment by remy** [comment]
In my decade of using nodemon, I've never needed the functionality. I'm that same time this issue was raised, but apparently (as you said) not important enough to warrant anyone wanting to change nodemons behaviour. 

So, I guess, you're right.

**Comment by JGJP** [comment]
I personally think it's fine for you to not fix it, but you keep bringing up the fact that nobody submitted a PR. Put in the perspective of this repo being 10 years old, I think 24 days is a really small window to give for a PR to be submitted. It's also possible that people just decided to use something like onchange instead, or in combination (as I did)

**Comment by elitan** [comment]
@remy Could this issue be solved with:


```js
watcher.on('unlink', filterAndRestart);
```

here: https://github.com/remy/nodemon/blob/main/lib/monitor/watch.js#L85

It seems to match what [chokidar](https://github.com/paulmillr/chokidar) is using: https://github.com/paulmillr/chokidar/blob/master/lib/constants.js#L12

**Comment by a-i-joe** [comment]
FYI the npm package `watch` reacts to file deletions

**Comment by markulaw** [comment]
@remy 
I added the line:
```js
 watcher.on('unlink', filterAndRestart);
```
directly under:
```js
watcher.on('change', filterAndRestart);
```
in /lib/monitor/watch.js

and it seems to "just work' - server properly restarts on file removal, and changes are reflected in the app. I also didn't find any issues in the log (tested on nodemon 3.0.2).

I honestly did not expect this to be that simple. Is there anything I am missing, or is it safe to make a pull request?

**Comment by remy** [comment]
@markulaw as long as it still restarts normally with a change, then you're good for a pr (I can't imagine that change would cause issues though). Good work 👍

**Comment by markulaw** [comment]
Thank you for your quick reply! I will prepare a pull request shortly :)
