### ISSUE TITLE
[nodemon] Internal watch failed: ELOOP: too many symbolic links encountered, stat 'SOME_PATH'

### ISSUE THREAD

**Issue by mehdinourollah** [remy/nodemon#1731]
- `nodemon -v`: 2.0.4
- `node -v`: v14.4.0
- Operating system/terminal environment: Windows Subsystem Linux ( WSL ) [ uname  -r :  "4.4.0-19041-Microsoft"]
- Command you ran: set DEBUG=true & nodemon ./bin/www

### Expected behaviour

Works as expected no matter of what types of files are inside the project

### Actual behaviour

I'm writing an ExpressJS app and I need to create e Symlink and check it via  my app but when I have created my Symlink (via WSL) suddenly the nodemon crashes with this error: 
[nodemon] Internal watch failed: ELOOP: too many symbolic links encountered, stat '/mnt/d/MYPROJECT_DIR/SOFTLINK'
PS. I didn't send any request and the error shows up the moment I created the symlink with Linux ( ln -s SRC DSC)

I know this is just for development tool and I have no problem at deployment on the server but I need to report this issue

**Comment by remy** [comment]
Can you retest with node 12 or 13 and confirm whether you still see the
issue?

**Comment by Digicrat** [comment]
I'm seeing this same issue.  For me this was with Node 12.4 and nodemon 2.0.4 under OSX.  

In my case, apparently one symbolic link is too many (from a /lib/something.js to /htdocs/lib/something.js).  In this case, adding "--ignore htdocs" to my nodemon invocation is good enough a solution for now.

As a test, I verified that if the symlink points to a file outside of the monitored folder nodemon is perfectly happy.  

Ideally nodemon should look at the path to a symlink before parsing it and automatically ignoring symlinks whose destination is within the watched folder.
