### ISSUE TITLE
Nodemon just produces an error when executing nodemon index.js

### ISSUE THREAD

**Issue by DAVE4547** [remy/nodemon#1735]
- `nodemon -v`:
- `node -v`: 12.18.2
- Operating system/terminal environment: Windows / Powershell
- Using Docker? What image: 
- Command you ran: nodemon index.js

### Expected behaviour
Run index.js

### Actual behaviour
produces this error:
```
nodemon : File C:\Users\user\AppData\Roaming\npm\nodemon.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ nodemon
+ ~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```
I have looked at the link but I don't really know what I am doing when it goes down to that stuff
I have tried reinstalling nodemon and it still isn't working correctly

### Steps to reproduce
I don't know how to reproduce this

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
You need to find out how to run scripts on windows:

> because running scripts is disabled on this system.

Can't help you with that (and isn't a nodemon issue I'm afraid).

**Comment by DAVE4547** [comment]
sorry for the misunderstanding i have been using nodemon for months before and I didn't change anything so I didn't think it was an issue with me but I will look into fixing it
