### ISSUE TITLE
依情況而異：  GPS IP 位址 您

### ISSUE THREAD

**Issue by asdasd637** [remy/nodemon#1736]
- `nodemon -v`:
- `node -v`:
- Operating system/terminal environment: 
- Using Docker? What image: 
- Command you ran:

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by asdasd637** [comment]
你知我知天知

stale[bot] <notifications@github.com>於 2020年7月25日 週六，11:59寫道：

**Comment by remy** [comment]
I'm afraid I can't read the subject that's been provided (and there's nothing in the body). This repo uses English, if you're able to resubmit a translated issue I'd be happy to accept it (Google translate even).
