### ISSUE TITLE
Nodemon not able to run electron environment

### ISSUE THREAD

**Issue by talhaanees** [remy/nodemon#1739]
- `nodemon -v`: 2.0.4 & 2.0.2
- `node -v`: 10.13.0
- Operating system/terminal environment: Windows / Powershell
- Using Docker? What image: 
- Command you ran: 
  "electron-dev": "concurrently \"cross-env BROWSER=none npm run react-start\" \"wait-on http://localhost:3000 && npm run electron-watch\"",
  "electron-watch": "nodemon --watch ./electron.js \"npm run electron-start\"",
  "electron-start": "electron .",

### Expected behaviour
Nodemon will run command " npm run electron-start " and the electron process will start.

### Actual behaviour
Nodemon tries to run command `node "npm run electron-watch" electron.js` 

### Steps to reproduce
I don't know how to reproduce this

### Additional Info
I am making an electron-react app. I have used nodemon before in a similar electron-react app (but with full control over webpack). 
This time around I am working with re-scripts in order to not eject my app. 
In the previous project nodemon successfully starts and watches the process and executes the right command:
`npm run electron-start`
However, with re-scripts and all, it's executing:
`node "npm run electron-watch" electron.js` (where electron.js is my main in package.json) and this causes a non electron environment error 

Is there a way to tell nodemon to not treat the command as a node command? Or my understanding of the problem is not correct?

**Comment by remy** [comment]
Use `nodemon --exec "npm run electron-start` - it should do the trick
