### ISSUE TITLE
A pity

### ISSUE THREAD

**Issue by danjoa** [remy/nodemon#1744]
See https://github.com/remy/nodemon/issues/1189 

I indeed planned to support both personally, and more.... but seeing that attitude, I'm afraid, I'd rather go for an alternative. 
You are doing good work, worth being supported with donations and more, but I'd suggest you think twice about that way of promotion @remy

**Comment by remy** [comment]
Genuinely don't believe on you. Sorry (but not sorry).

And of course please do use an alternative. That's the joy of the web and sharing code, you always have options.
