### ISSUE TITLE
Please respond, I want to rid of messages which prints on every change.

### ISSUE THREAD

**Issue by sahilrajput03** [remy/nodemon#1745]
This is not a problem, but for me its a problem. It is like, I don't like to see messages like 
$ nodemon amazing.js
```[nodemon] clean exit - waiting for changes before restart
[nodemon] restarting due to changes...
[nodemon] starting `node amazing.js`
PROGRAM'S OUPUTT!!``
If there's any option I can disable these messages, please please let me know.!!!!1

**Comment by remy** [comment]
"Please respond"?

Have you read the help screen? I mean, it's right there. The quiet flag. In future start with the help as you'll get along faster.

**Comment by sahilrajput03** [comment]
![image](https://user-images.githubusercontent.com/31458531/89200646-f42fb280-d5cd-11ea-804f-3407c431ed54.png)
I do see the help earlier, and it was not there., and thanks  LOT LOT LOT.
♥♥♥♥♥♥♥♥♥♥♥♥
For helping me out.

**Comment by remy** [comment]
"All the options are documented under: nodemon --help options"

**Comment by sahilrajput03** [comment]
Oh, thanks a lot, I never knew that too. Thanks a lott...!!!

**Comment by sahilrajput03** [comment]
> "All the options are documented under: nodemon --help options"

O man, actually I now see that last line...., godd, mybad!!!
