### ISSUE TITLE
Missing dependencies when installing

### ISSUE THREAD

**Issue by alexandruhog** [remy/nodemon#1749]
- `nodemon -v`: NaN (could not install it)
- `node -v`: 12.18.3
- Operating system/terminal environment: Windows 10 + CMD and Gitlab Docker Workers
- Using Docker? What image: Docker Dind (Gitlab)
- Command you ran: npm ci or npm install or npm install nodemon

### Expected behaviour

Nodemon package gets installed

### Actual behaviour
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@szmarczak%2fhttp-timer - Not found
npm ERR! 404
npm ERR! 404  '@szmarczak/http-timer@^1.1.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'got

and

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@sindresorhus%2fis - Not found
npm ERR! 404
npm ERR! 404  '@sindresorhus/is@^0.14.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'got'

### Steps to reproduce
npm install nodemon
---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
You'll need to check your own connection settings as it's local to your machine and not related to nodemon:

<img width="1735" alt="Screenshot 2020-08-06 at 11 44 42" src="https://user-images.githubusercontent.com/13700/89523089-3a596180-d7da-11ea-8fb9-d1148a3eaeb0.png">
