### ISSUE TITLE
Add option to auto restart on error

### ISSUE THREAD

**Issue by throrin19** [remy/nodemon#175]
Hello, if we have an error, nodemon wait file modification or manually rs command but I run command in production server and I can not afford to let the server down for even just a few minutes. Would it be possible to add an option to automatically restart the server without any external help?

**Comment by mcjohnalds** [comment]
Nodemon is only meant for development. This will restart app.js whenever it exits:

```
while true; do node app.js; echo "Crashed. Restarting..."; done
```

But I would recommend learning about `pm2` or `forever` for running apps in production.

**Comment by remy** [comment]
What @mcjohnalds said

**Comment by d4nyll** [comment]
The following set of npm scripts will mimic what nodemon is doing, but using [PM2](Unitech/pm2):

```
"scripts": {
    "log": "./node_modules/.bin/pm2 log",
    "reset": "yarn run stop && ./node_modules/.bin/pm2 delete all && ./node_modules/.bin/pm2 flush",
    "start": "yarn run watch && yarn run log",
    "stop": "./node_modules/.bin/pm2 stop all",
    "watch": "./node_modules/.bin/pm2 start src/index.js --watch --interpreter ./node_modules/.bin/babel-node"
  }
```
PM2's `--interpreter` flag is similar to nodemon's `--exec` flag. Here I am using it to run `babel-node`

**Comment by j0hnm4r5** [comment]
You can also do it simply with `forever index.js`

**Comment by GoodClover** [comment]
Any updates on this in 2020?

Having the ability for it to restart on an error would be great, preferably with the delay.
I t would be good to have a config option, not just a command line argument.

**Comment by remy** [comment]
Yes, there was: https://github.com/remy/nodemon/issues/175#issuecomment-335336592
