### ISSUE TITLE
Docs: Better (cli/js) options documentation.

### ISSUE THREAD

**Issue by Izhaki** [remy/nodemon#1753]
# The issue

[nodemon-webpack-plugin](https://github.com/Izhaki/nodemon-webpack-plugin) is a simple webpack plugin that launches nodemon.

The plugin simply pass-through a user-provided configuration object to the `nodemon` function.

Users repeatedly ([#2](https://github.com/Izhaki/nodemon-webpack-plugin/issues/2), [#8](https://github.com/Izhaki/nodemon-webpack-plugin/issues/8), [#89](https://github.com/Izhaki/nodemon-webpack-plugin/issues/89), [#117](https://github.com/Izhaki/nodemon-webpack-plugin/issues/117), [#123](https://github.com/Izhaki/nodemon-webpack-plugin/issues/123)) find it hard to figure out how to provide options to this function due to lack and disperse documentation.

I have added an [example on nodemon-webpack-plugin's README](https://github.com/Izhaki/nodemon-webpack-plugin#with-config), but questions keep on coming.

**It seems highly reasonable that such documentation should exist in this repo and not the plugin's one.** Because it is the `nodemon` function API that needs documenting - this has nothing to do with the plugin.

Related pages on this repo:

 - https://github.com/remy/nodemon#config-files
 - https://github.com/remy/nodemon/blob/master/doc/requireable.md
 - https://github.com/remy/nodemon/blob/master/doc/sample-nodemon.md
 - https://github.com/remy/nodemon/blob/master/doc/cli/options.txt

What I normally do is look at the latter, then search the code to confirm the option is programmatically supported.

# Possible solutions

It would probably be beneficial to create a central markdown page with all the various options, with their cli and json/js variants. Something along the lines of https://www.typescriptlang.org/docs/handbook/compiler-options.html.

**Comment by Izhaki** [comment]
@MaxmaxmaximusAWS This is a Good First Issue so feel free to contribute to the documentation in this repo?

**Comment by remy** [comment]
Why is this a problem or issue on nodemon rather than the webpack thing?

**Comment by Izhaki** [comment]
Because the API is that of `nodemon`, not the plugin. The plugin uses the API of nodemon, as-is (it takes an object and simply pass it on to `nodemon`). If the nodemon API is documented on another repo, you have two sources of truth. The API lives in one repo (nodemon), the documentation in another (the plugin).

To be honest, you can ignore the plugin story altogether, and instead consider the issue raised here to be:

> Can we have documentation for the options available when using nodemon as a requirable?

**Comment by remy** [comment]
Feel free to pr against the wiki then: https://github.com/remy/nodemon/wiki - not sure what's missing from the cli, IIRC it's all there on --help options, but happy to take a pr on that too if it's sensible.

**Comment by olsonpm** [comment]
I got here before the wiki page looking for the documentation.  No idea why it's so hard to find.  For future googlers having the same trouble I did, docs are here

https://github.com/remy/nodemon/wiki/As-a-required-module
