### ISSUE TITLE
Nodemon doesn't watch node_modules in non root directory even if the path is included in nodemon.json

### ISSUE THREAD

**Issue by ParaSpl01t** [remy/nodemon#1755]
I'm using this **folder structure :**
```
(node project root)/
│
├── node_modules/
│   ├── <module1>/*
│   └── <modulex>/*
├── app/
│   ├── node_modules/
│   │   └── customMod.js
│   ├── render.js
│   └── render2.js
├── nodemon.json
├── package.json
└── server.js
```
**nodemon.json :**
```
{
	"watch": [
		"./*",
		"./app/node_modules/*"
	]
}
```
whenever I run `nodemon server.js` I get the following **output :**
```
[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): **/* app/node_modules/**/*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
Opened on port : 8080
```
Server restarts everytime I make changes to any file like `server.js` or `app/render.js`. but changes to `app/node_modules/customMod.js` doesn't restart server.
nodemon ignores all changes to the root `node_modules` as it should. but shouldn't it watch `app/node_modules` folder because I explicitly told it to watch there?
**OS :** Manjaro Linux

**Comment by remy** [comment]
IIRC you need to override the "rootIgnore" (or something like that). Have a search around the faq and wiki

**Comment by ParaSpl01t** [comment]
> IIRC you need to override the "rootIgnore" (or something like that). Have a search around the faq and wiki

Thanks. Adding `"ignoreRoot": ["node_modules"]` to nodemon.json fixes the issue.
