### ISSUE TITLE
Why not support config.js

### ISSUE THREAD

**Issue by jsonchou** [remy/nodemon#1757]
Hi,

``` js
// nodemon.config.js
const watchList = require('./projects')

module.exports = {
    verbose: true,
    // https://github.com/remy/nodemon#monitoring-multiple-directories
    // watch: ['dax/_common/mapping', 'dax/**/api/mapping'],
    watch: watchList,
    ext: 'js,ts',
    ignore: [],
    execMap: {
        ts: 'ts-node --project ./build/mocker/tsconfig.mock.json'
    }
}
```

**<code>config.js</code>**  just output a standard JSON stream as **<code>config.json</code>**, why not support config.js. 
 
It's there any way to set watch value dynamically  before nodemon starts running?

**Comment by remy** [comment]
It didn't exist when I wrote nodemon back in 2009.

And as per the current [design principles](https://github.com/remy/nodemon/#design-principles) there's no decent reason to add it.
