### ISSUE TITLE
Nodemon is not outputting the console.log when running with babel-node 

### ISSUE THREAD

**Issue by shubhsk88** [remy/nodemon#1759]
- `nodemon -v`:2.0.4
- `node -v`:12.15.0
- Operating system/terminal environment: Windows 

- Command you ran: `nodemon --exec babel-node src/index`

### Expected behavior
I have been trying to run nodemon with es6 modules and according to the code it should console.log out my statement

### Actual behavior
The nodemon is not outputting anything in the console.log and just showing `starting `babel-node src/index.js` whole the time. I am not able to figure out what will be the error because when I am executing the same code without nodemon it is outputting the console.log and neither it is showing any error inside my terminal

### Steps to reproduce
run `yarn start` with `console.log` inside `src/index.js` file

---

below is my `package.json` file
```json
"main": "index.js",
 "license": "MIT",
  "devDependencies": {
    "@babel/core": "^7.11.6",
    "@babel/node": "^7.10.5",
    "@babel/preset-env": "^7.11.5",
    "nodemon": "^2.0.4"
  },
  "scripts": {
    "start": "nodemon --exec babel-node src/index"
  },
  "dependencies": {
    "express": "^4.17.1"
  }
```
below is my `.babelrc` file:

`
{
  "presets": ["@babel/preset-env"]
}
`

**Comment by mikaelbad12** [comment]
I'm with the same problem, somebody got the solution?

**Comment by nishanktiwari17** [comment]
Try removing all the node_modules and reinstalling them. Worked for me

**Comment by ShashankIIITN** [comment]
i added "/" this after the address to my database and it worked...lol
