### ISSUE TITLE
When run command in nodemon.json, PM2 cannot detect its own config

### ISSUE THREAD

**Issue by Hongbo-Miao** [remy/nodemon#1761]
- `nodemon -v`: 2.0.4
- `node -v`: 14.3.0
- Operating system/terminal environment: macOS
- Using Docker? What image: No
- Command you ran: `nodemon --config nodemon.json`

with file **nodemon.json**

```json
{
  "ext": "ts",
  "execMap": {
    "js": "yarn build && pm2 start ecosystem.config.js --env development"
  }
}
```

### Expected behaviour

When I run

```sh
nodemon --config nodemon.json
```

[PM2](https://github.com/Unitech/pm2) should be able to detect its own config file **ecosystem.config.js**.

### Actual behaviour

PM2 failed to detect **ecosystem.config.js**.

However, note if I run

```sh
nodemon --ext ts --exec "yarn build && pm2 start ecosystem.config.js --env development"
```

directly, PM2 is able to detect the its own config file **ecosystem.config.js**.

### Steps to reproduce

Add **nodemon.json**

```json
{
  "ext": "ts",
  "execMap": {
    "js": "yarn build && pm2 start ecosystem.config.js --env development"
  }
}
```

Add **ecosystem.config.js**

```js
module.exports = {
  apps: [
    {
      name: 'server',
      script: './build/index.js',
      env_development: {
        NODE_ENV: 'development',
      },
    },
  ],
};
```

Add **index.js** at `/build/index.js`

If PM2 can detect **ecosystem.config.js** file, it will use the path `/build/index.js` from the config file, otherwise it will use default location and file `/index.js` and says it does not exist.

Run the 
---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

```js
[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts
--------------
node: v14.3.0
nodemon: 2.0.4
command: /Users/hm/.nvm/versions/node/v14.3.0/bin/node /Users/hm/.config/yarn/global/node_modules/.bin/nodemon --config nodemon.json --dump
cwd: /my-app/server
OS: darwin x64
--------------
{
  run: false,
  system: { cwd: '/my-app/server' },
  required: false,
  dirs: [ '/my-app/server' ],
  timeout: 1000,
  options: {
    configFile: 'nodemon.json',
    dump: true,
    execMap: {
      js: 'yarn build && pm2 start ecosystem.config.js --env development',
      py: 'python',
      rb: 'ruby',
      ts: 'ts-node'
    },
    ignore: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**',
      re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/
    ],
    watch: [ '*.*', re: /.*\..*/ ],
    monitor: [
      '*.*',
      '!**/.git/**',
      '!**/.nyc_output/**',
      '!**/.sass-cache/**',
      '!**/bower_components/**',
      '!**/coverage/**',
      '!**/node_modules/**'
    ],
    ignoreRoot: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**'
    ],
    restartable: 'rs',
    colours: true,
    stdin: true,
    runOnChangeOnly: false,
    verbose: false,
    signal: 'SIGUSR2',
    stdout: true,
    watchOptions: {},
    execOptions: {
      script: 'index.js',
      exec: 'yarn build && pm2 start ecosystem.config.js --env development',
      args: [],
      scriptPosition: 0,
      nodeArgs: undefined,
      execArgs: [],
      ext: 'ts',
      env: {}
    }
  },
  load: [Function (anonymous)],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [ '/my-app/server/nodemon.json' ],
  watchInterval: null,
  signal: 'SIGUSR2',
  command: {
    raw: {
      executable: 'yarn build && pm2 start ecosystem.config.js --env development',
      args: [ 'index.js' ]
    },
    string: 'yarn build && pm2 start ecosystem.config.js --env development index.js'
  }
}
--------------
```

**Comment by Hongbo-Miao** [comment]
Activiate

**Comment by remy** [comment]
Honestly I've no idea how pm2 starts and how it runs - and I'm pretty sure you're one of the few that is combining nodemon with pm2 (since one is a dev tool and one is a prod tool meant to do similarish things…).

Anyway, maybe try with ` start ./ecosystem.config.js` otherwise I'm really not sure. If you use `DEBUG=nodemon,nodemon:*` as an env value you might find out what's going on.

I'm not sure I can debug or resolve this - sorry.

**Comment by Hongbo-Miao** [comment]
No problem, still thanks @remy !
I sometimes use both to test locally to catch issues before deploying to production such as this issue https://github.com/pinojs/pino/issues/491 that pino does not work with PM2.
With nodemon, it just helps me save some time to watch code change.
