### ISSUE TITLE
Nodemon installation error

### ISSUE THREAD

**Issue by scurlly** [remy/nodemon#1762]
Every time I try Installing nodemon  on windows 10 I get this error:

npm install -g nodemon
npm ERR! Unexpected end of JSON input while parsing near '...dirp":"~1.3.0","async'

I tried turning off the antivirus and clearing the npm cache but it doesn't work.

**Comment by remy** [comment]
Isn't this an npm issue? Nodemon code hasn't run at this point. Hopefully you can get some support from them.
