### ISSUE TITLE
Both processes keep running after terminal killed

### ISSUE THREAD

**Issue by manen** [remy/nodemon#1763]
- `nodemon -v`: 2.0.4
- `node -v`: v12.18.2
- Operating system/terminal environment: Fedora 32, both VSCode integrated terminal and gnome-shell
- Using Docker? What image: none
- Command you ran: nodemon .

### Expected behaviour
I expected my program to stop running after the terminal is killed

### Actual behaviour
The program kept running, while the terminal was already shut down.

### Steps to reproduce

1. nodemon .
2. Kill the terminal, by closing it
3. See that the program is still running (from system monitor processes or if it's a server then that it's still serving)

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

node: v12.18.2
nodemon: 2.0.4
command: /home/manen/.nvm/versions/node/v12.18.2/bin/node /home/manen/.nvm/versions/node/v12.18.2/bin/nodemon . --dump
cwd: [working directory]
OS: linux x64
--------------
```
{
  run: false,
  system: { cwd: [working directory] },
  required: false,
  dirs: [ [working directory] ],
  timeout: 1000,
  options: {
    dump: true,
    ignore: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**',
      re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/
    ],
    watch: [ '*.*', re: /.*\..*/ ],
    monitor: [
      '*.*',
      '!**/.git/**',
      '!**/.nyc_output/**',
      '!**/.sass-cache/**',
      '!**/bower_components/**',
      '!**/coverage/**',
      '!**/node_modules/**'
    ],
    ignoreRoot: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**'
    ],
    restartable: 'rs',
    colours: true,
    execMap: { py: 'python', rb: 'ruby', ts: 'ts-node' },
    stdin: true,
    runOnChangeOnly: false,
    verbose: false,
    signal: 'SIGUSR2',
    stdout: true,
    watchOptions: {},
    execOptions: {
      script: '.',
      exec: 'node',
      args: [],
      scriptPosition: 0,
      nodeArgs: undefined,
      execArgs: [],
      ext: 'js,mjs,json',
      env: {}
    }
  },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  signal: 'SIGUSR2',
  command: { raw: { executable: 'node', args: [ '.' ] }, string: 'node .' }
}
```

**Comment by acidiney** [comment]
it solved my problem

```js

const httpServer = server.listen(process.env.PORT, function () {
  console.log(kleur.yellow('[Application]: Application running 😊'))
})

httpServer.close(() => process.exit())
``

This issue is related to #1748 and #1734, you can check for additional information

**Comment by remy** [comment]
The terminal closing isn't a graceful exit, it's more of a SIGKILL which when sent to nodemon it immediately ends not allowing time to actually send a close to the subprocess. Some systems will have time, others won't. It's system specific. 

If there's a PR that can work around this (I'd be surprised, but), happy to accept it.
