### ISSUE TITLE
nodemon keeps restarting server when worker thread is used in Express app

### ISSUE THREAD

**Issue by bjfletcher** [remy/nodemon#1764]
- `nodemon -v`: 1.19.4
- `node -v`: 12.6.2
- Operating system/terminal environment: macOS Catalina
- Using Docker? What image: nope
- Command you ran: nodemon server/app.js

### Expected behaviour
nodemon to start the server and then wait for any changes

### Actual behaviour
nodemon starts the server and keeps restarting it even though there's not been any change

### Steps to reproduce

I added worker thread to some Express app (web server) at which point nodemon kept restarting the server. I removed worker thread then nodemon didn't keep restarting the server.

I put together a simple main.js and a worker.js to try and reproduce this, however it worked ok. So I think it's something to do with the fact that the app is Express.

Interestingly, if I run `nodemon -w server/app.js server/app.js` then it doesn't keep restarting.

I thought I'd raise this issue and see if anyone else experiences the same.

It's not urgent and I can survive without nodemon but certainly it'd be nice to have a nodemon that doesn't do this. :)

PS thanks for a great tool, we all love it! 💟 

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

```sh
$ nodemon server/app.js
[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server/app.js`
App listening on port 3000!
[nodemon] restarting due to changes...
[nodemon] starting `node server/app.js`
App listening on port 3000!
[nodemon] restarting due to changes...
# ... again, again and again
```

<details>
<summary>Dump output:</summary>

```
[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
--------------
node: v12.16.2
nodemon: 1.19.4
command: /usr/local/bin/node /Users/ben.fletcher/code/ids-homepage-analyser/node_modules/.bin/nodemon --dump server/app.js
cwd: /Users/ben.fletcher/code/ids-homepage-analyser
OS: darwin x64
--------------
{
  run: false,
  system: { cwd: '/Users/ben.fletcher/code/ids-homepage-analyser' },
  required: false,
  dirs: [ '/Users/ben.fletcher/code/ids-homepage-analyser' ],
  timeout: 1000,
  options: {
    dump: true,
    ignore: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**',
      re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/
    ],
    watch: [ '*.*', re: /.*\..*/ ],
    ignoreRoot: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**'
    ],
    restartable: 'rs',
    colours: true,
    execMap: { py: 'python', rb: 'ruby', ts: 'ts-node' },
    stdin: true,
    runOnChangeOnly: false,
    verbose: false,
    signal: 'SIGUSR2',
    stdout: true,
    watchOptions: {},
    execOptions: {
      script: 'server/app.js',
      exec: 'node',
      args: [],
      scriptPosition: 0,
      nodeArgs: undefined,
      execArgs: [],
      ext: 'js,mjs,json',
      env: {}
    },
    monitor: [
      '*.*',
      '!**/.git/**',
      '!**/.nyc_output/**',
      '!**/.sass-cache/**',
      '!**/bower_components/**',
      '!**/coverage/**',
      '!**/node_modules/**'
    ]
  },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  signal: 'SIGUSR2',
  command: {
    raw: { executable: 'node', args: [ 'server/app.js' ] },
    string: 'node server/app.js'
  }
}
--------------
```
</details>

**Comment by remy** [comment]
If you run with `nodemon -V` (and your other arguments) it'll show you what is triggering the reload. I suspect there's a file being touched by your server running.

Let me know how you get on.

**Comment by bjfletcher** [comment]
@remy Yay!

Thanks for looking at this and the suggestion, so the app creates a temporary JSON file which was why 👋 

BTW the `[nodemon] files triggering change check: <temporary file>` output with `-V` is really useful, perhaps this can become part of the normal output (not `-V`)? To save people from wondering what exactly caused the reload trigger.
