### ISSUE TITLE
Shouldn't the "exit" event be triggered when stopping nodemon manually?

### ISSUE THREAD

**Issue by mkvlrn** [remy/nodemon#1766]
- `nodemon -v`: 2.0.4
- `node -v`: 14.11.0
- Operating system/terminal environment:  Manjaro Linux / ZSH
- Using Docker? What image: No
- Command you ran: nodemon src/index.ts, ctrl+C

---

This is most likely not a bug, but a misunderstanding on my part and please forgive me if so, but I rather take my chances asking here (because StackOverflow will mock the question for hours and NOT answer it).

Perhaps I misunderstood the documentation where it says the exit event is triggered when the "child process has cleanly exited (ie. no crash)". Is that not what happens when I stop nodemon from the command line?

To clarify, I start a no-build DB container with docker-compose in my dev script along with nodemon, and it works perfectly. All I want is to trigger a `docker-compose down` after nodemon exits.

Edit: It's an express application, if that's important.

---

### Expected behaviour
"exit" event to be triggered when stopping nodemon using ctrl+C
```
// the configuration
{
 ...
 "events": {
    "exit": "docker-compose -f docker-compose.dev.yml down"
  }
}
```

### Actual behaviour
event is not triggered

### Steps to reproduce
* start container and nodemon with said configuration
* stop nodemon with ctrl+C

**Comment by remy** [comment]
This can take a PR, but one thing I suspect there won't be time to actually receive the signal to handle it properly.
