### ISSUE TITLE
Nodemon app crashed...(it crashes almost everytime)😫

### ISSUE THREAD

**Issue by 5hre9a** [remy/nodemon#1767]
- `nodemon -v`:
- `node -v`:
- Operating system/terminal environment: 
- Using Docker? What image: 
- Command you ran:

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by srujana-55** [comment]
Yes, the same problem occurs everytime though!

**Comment by remy** [comment]
See labels.
