### ISSUE TITLE
Uncaught 'ios: command not found: ps'

### ISSUE THREAD

**Issue by jameslinimk** [remy/nodemon#1768]
**Using play.js**
Uncaught 'ios: command not found: ps'

Works on pc, not play.js. Is there any way to add compatibility?

**Comment by remy** [comment]
What is play.js? Though your error says iOS - please tell me you're not running code from iOS...?

**Comment by jameslinimk** [comment]
> What is play.js? Though your error says iOS - please tell me you're not running code from iOS...?

Its a js ide for ios. It works fine for me, but its just this that causes a problem

**Comment by remy** [comment]
I don't intend to support iOS. iOS is also reporting that it has `ps`. So you can either install `ps` (no idea how you do that on iOS) or you can set an env value `NO_PS=1`
