### ISSUE TITLE
Add option to watch AST

### ISSUE THREAD

**Issue by bernardoadc** [remy/nodemon#1770]
This way, small unmeaningful changes won't cause to reload server (";", spaces, changing variable names in some cases). It will reload only if "compiled" code is different.

I can do a PR with some guidance, if this proposal is accepted

**Comment by remy** [comment]
This is way out of scope for nodemon, plus it would bind nodemon forever more to the language of the AST. 

It's not a terrible idea, just not a good match for nodemon.

Thank you all the same.
