### ISSUE TITLE
Giving 'N' for terminating nodemon terminates it

### ISSUE THREAD

**Issue by manoj997** [remy/nodemon#1771]
The issue seems to be when nodemon is running and I hit the termination command (Ctrl + C) , it prompts a question whether to terminate or not. When I press 'N', which stands for don't wanna terminate, the process terminates.

- `nodemon -v`: 2.0.2
- `node -v`: 10.16.0
- Operating system/terminal environment: Linux & Windows
- Using Docker? What image: Not Using Docker
- Command you ran: Ctrl + C

### Expected behaviour
The process should be continuing 

### Actual behaviour
The process terminates

### Steps to reproduce
* Start Nodemon
* Terminate using Ctrl +C
* In the question that is prompted, press *N*

**Comment by remy** [comment]
Why are you doing ctrl+c without wanting the process to end?

**Comment by manoj997** [comment]
@remy what if it is an accidental action? Perhaps the user might have another cmd/terminal open so instead of Ctrl + C there, and accidentally makes it in the nodemon terminal? And moreover, if there is a prompt to ask whether to terminate the process or not, there should be a functional flow when pressed 'N'. Otherwise no point of that prompt in the first place.

**Comment by remy** [comment]
If the user accidentally stops nodemon, then they're already at the prompt and they'll start it again. I mean, that's the worst that can happen, right? 

This is a windows specific thing (no other OS asks if you meant to enter a control combination) and with the current bespoke stdin in handler it's convoluted to change

**Comment by remy** [comment]
If the user accidentally stops nodemon, then they're already at the prompt and they'll start it again. I mean, that's the worst that can happen, right? 

This is a windows specific thing (no other OS asks if you meant to enter a control combination) and with the current bespoke stdin in handler it's convoluted to change

**Comment by manoj997** [comment]
@remy happened on Windows and Linux! if you are lazy that's fine no reasons necessary. Removing the use of nodemon.

Regards,
Manoj

**Comment by manoj997** [comment]
@remy Worked both on linux and Windows! Please take an action on this
