### ISSUE TITLE
nodemon.json ignore not respecting "*.yaml.dec"

### ISSUE THREAD

**Issue by preston-wagner** [remy/nodemon#1772]
- `nodemon -v`: 2.0.4
- `node -v`: v10.14.1
- Operating system/terminal environment: mac/bash
- Using Docker? What image: 
- Command you ran: `nodemon index.js --config nodemon.json`

### Expected behaviour
After adding `"ignore": ["*.yaml.dec"]` to nodemon.json, expected that server would not restart when a file named secrets.yaml.dec was created or destroyed.

### Actual behaviour
Creating secrets.yaml.dec caused the server to restart.

**Comment by remy** [comment]
Can you run with `--verbose` and trigger the error capturing the output and posting here?

**Comment by remy** [comment]
Can't replicate and no information was given to replicate.

Here's my gist with files to (attempt and fail) to replicate: https://gist.github.com/remy/dba615c4486f4ac0abdde5f58164df53
