### ISSUE TITLE
Can nodemon clear logs like other libraries does, like ts-node-dev on restart with --clear flag ?

### ISSUE THREAD

**Issue by sahilrajput03** [remy/nodemon#1775]
- `nodemon -v`: 2.0.4
- `node -v`: 12.18.0
- Operating system/terminal environment: 
- Using Docker? What image: NO
- Command you ran: I didn't find any related command for this.

### Expected behaviour

It should clear the console on every restart it does.

### Actual behaviour

Currently it just piles up latest ran logs and all previous logs together.

### Steps to reproduce
Using commadn - `nodemon anyfile.js`, it can be reproduced.

---

**Comment by remy** [comment]
The faq has literally the "frequently" asked questions - and that [one is number 1](https://github.com/remy/nodemon/blob/master/faq.md#how-to-clear-the-console-on-restart)

**Comment by sahilrajput03** [comment]
Amazing!!! thanks remy, it is second time you made my day, thanks a lot!!! 😍😍😎😎😋😋
