### ISSUE TITLE
Nodemon: Concurrent browser reloading <feature>

### ISSUE THREAD

**Issue by Kenludiaz** [remy/nodemon#1776]
Hello,
I am a novice programmer.
I was wondering why is there not a feature to simultaneously
reload the server and the browser? Is it a bad idea/feature?

Sorry if the answer to my question is obvious,

@Kenludiaz

**Comment by remy** [comment]
Nodemon is about reloading a process when files change. You could use nodemon to restart your entire browser when files change, but I suspect you (nor anyone) wants that. 

I'd suggest look at a tool like live-reload or similar.

**Comment by rayfoss** [comment]
Nodemon is the default watcher on CodeSandbox's Node.js. It uses express to print Hello World. Glitch has as a similar set-up.

The wording on the ReadMe.md stating this has been tuned for Web Servers like Express makes it sound like there might be some reverse-proxy livereload script tag injection going on.
