### ISSUE TITLE
Entrypoint script is filtered out, preventing restart

### ISSUE THREAD

**Issue by nprbst** [remy/nodemon#1779]
```
→ nodemon -v
2.0.4

→ node -v
v12.18.4

→ uname -mprs
Darwin 19.6.0 x86_64 i386

→ cat nodemon.json 
{
  "verbose": true,
  "watch": ["index"],
  "ext": "ts,js,json",
  "ignore": ["*.test.ts"],
  "delay": "1",
  "env": {
    "NODE_ENV": "development"
  },
  "execMap": {
    "ts": "ts-node"
  }
}

→ cat index.ts 
const main = () => {
  console.log("Hello World");
};
main();

→ nodemon
...
Hello World!
[nodemon] clean exit - waiting for changes before restart
[nodemon] files triggering change check: index.ts
[nodemon] changes after filters (before/after): 1/0
```

### Expected behaviour

Changes to the entrypoint script should trigger restart.

### Actual behaviour

Changes to the entrypoint script do not trigger restart. Entrypoint script is filtered out due to a bug in `watch.js`. PR coming shortly.

### Steps to reproduce

See above terminal history.

**Comment by remy** [comment]
Um, this actually correct. There's no match on the rules - because the nodemon config says to restart on a file called `index`, but your file is `index.js`.

The `watch` is either for filenames (like `index.js`) or for directories (like `./src/*`).

To summarise: this isn't a bug.
