### ISSUE TITLE
Add option for custom stdin commands beyond 'rs'

### ISSUE THREAD

**Issue by vostrnad** [remy/nodemon#1781]
I use nodemon for rebuilding my project on file changes. Sometimes after my build finishes, I'd like to run some additional build steps that I don't usually need when developing, and since nodemon already listens for the 'rs' command, it sounds like there should be an option for custom shorthand commands. What do you think? Or would this be easier accomplished some other way?

**Comment by remy** [comment]
Best to have your program listen for the stdin events and have nodemon pass them directly through (this also means you're not tightly coupled to nodemon in your own code).
