### ISSUE TITLE
Vulnerability

### ISSUE THREAD

**Issue by MatteoTasinato** [remy/nodemon#1783]
Hi, nodemon contains a high vulnerability caused by dot-prop package (nodemon > update-notifier > configstore > dot-prop) I checked the chain and the vulnerability has been fixed until update-notifier then updating this library the vulnerability will be fixed. Is it possible? Thanks for the attention.

https://www.npmjs.com/advisories/1213

**Comment by remy** [comment]
Update your local deps, they're out of date: https://snyk.io/test/npm/nodemon
