### ISSUE TITLE
[nodemon] Internal watch failed: Circular symlink detected

### ISSUE THREAD

**Issue by AlexeyPlodenko** [remy/nodemon#1786]
- `nodemon -v`: 2.0.5
- `node -v`: 12.19.0
- Operating system/terminal environment: 
- Using Docker? What image: node:lts-alpine
- Command you ran: CMD ["nodemon", "--config", "/app/src/ScheduleService-nodemon.json", "/app/src/ScheduleService/index.js"]

Before this hell started, Nodemon was working fine. I have deleted all Docker images and caches and re-build everything from scratch. So the versions should be the latest.

### Expected behaviour
Nodemon should be monitoring files without issues.

### Actual behaviour
Nodemon reports an error:
...
[nodemon] Internal watch failed: Circular symlink detected: "/sys/class/cpuid/cpu0/subsystem" points to "/sys/class/cpuid"
...
[nodemon] Internal watch failed: Circular symlink detected: "/sys/class/bdi/0:85/subsystem" points to "/sys/class/bdi"
...

### Steps to reproduce
Start the image.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by AlexeyPlodenko** [comment]
Another re-build from scratch has solved the issue.

This issue can be closed.

Thank you.

**Comment by tomhuntley** [comment]
Getting a similar issue here:

- Docker Image:  osgeo/gdal:ubuntu-small-latest (based on ubuntu:20.04)
- `node -v`: v10.19.0
- `nodemon -v`: 2.0.6
- Command: nodemon -L /my-app/index.js

[nodemon] Internal watch failed: Circular symlink detected: "/usr/bin/X11" points to "/usr/bin"

**Comment by delivey** [comment]
Getting a similar issue:

- `node -v`: 6.14.8
- Command: `nodemon --watch src -e js,ts --exec "npm run compile"`

[nodemon] Internal watch failed: Circular symlink detected: "C:\Users\user\AppData\Local\Application Data" points to "C:\Users\user\AppData\Local"

**Comment by andrewlew1s** [comment]
@tomhuntley did you resolve this? Getting the same `"/usr/bin/X11" points to "/usr/bin"` error

**Comment by tomhuntley** [comment]
@andrewlew1s no, i couldn't resolve it. I've had to temporarily run the app outside docker while developing. It seems ok for me on windows.

**Comment by remy** [comment]
Can you add the following to your `nodemon.json` and let me know how you get on:

```
{
  "watchOptions": {
	"followSymlinks": false
  }
}
```

**Comment by AlexeyPlodenko** [comment]
Tried. And without any luck. The same problem still persists.

**Comment by remy** [comment]
@AlexeyPlodenko can you provide a pared down repo to replicate from?

**Comment by andrewlew1s** [comment]
> Can you add the following to your `nodemon.json` and let me know how you get on:
> 
> ```
> {
>   "watchOptions": {
> 	"followSymlinks": false
>   }
> }
> ```

Can confirm problem still persists after adding this to `nodemon.json`

**Comment by AlexeyPlodenko** [comment]
@remy Here you go https://hub.docker.com/r/alexeyplodenko/paired-down-repo

**Comment by remy** [comment]
@AlexeyPlodenko okay, not being a docker user, can you provide instructions? Assume I know nothing about Docker (which is accurate) (utterly aside, it's [pared down](https://www.collinsdictionary.com/dictionary/english/pared-down))

**Comment by deusilva** [comment]
I am running a nodejs application inside a docker container.

I solved creating a nodemon.json on my project root with this content:
```
{
  "watch": ["src"],
  "ext": "js"
}
```

The watch option only update when anything on my src folder changes. Without it, nodemon watches all files of the system, generating the error. Maybe a possible fix is to make nodemon observe by default the files on current directory and subdirectories.

**Comment by dougecomp** [comment]
I am running a nodejs application inside a docker container.

I solved creating a nodemon.json on my project root with this content:

{
  "watch": ["src"],
  "ext": "js"
}
The watch option only update when anything on my src folder changes. Without it, nodemon watches all files of the system, generating the error. Maybe a possible fix is to make nodemon observe by default the files on current directory and subdirectories.

**Comment by gabrielpetersson** [comment]
@dougecomp works great!

**Comment by AlexeyPlodenko** [comment]
We are also using a nodemon.json configuration file:
```
{
  "watch": [
    "APIService/",
    "shared/"
  ],
  "ext": "js,json"
}
```
And it does not sort the issue.

**Comment by haydenlinder** [comment]
> I am running a nodejs application inside a docker container.
> 
> I solved creating a nodemon.json on my project root with this content:
> 
> ```
> {
>   "watch": ["src"],
>   "ext": "js"
> }
> ```
> 
> The watch option only update when anything on my src folder changes. **_Without it, nodemon watches all files of the system, generating the error._** Maybe a possible fix is to make nodemon observe by default the files on current directory and subdirectories.

I'm a little confused here. According to the [docs](https://github.com/remy/nodemon#monitoring-multiple-directories):
> **_By default nodemon monitors the current working directory._** If you want to take control of that option, use the --watch option to add specific paths ...

So which one is true? I think it would be helpful if someone could explain why this only happens in a Docker container.

**Comment by haydenlinder** [comment]
Okay I just solved this, although tbh I am not exactly sure what exactly caused the issue in the first place.
Seems to be a Docker configuration issue though, not an issue with nodemon.

1. Change dockerfile like so:
```dockerfile
 FROM node:14.15.0
 # add this line
 WORKDIR /app 
 # change second '.' to '/app'
 COPY . /app 
 RUN npm install 
 CMD npm run dev
```

2. Build the image and then run it in a container with interactive terminal (optional), mounting a volume from the current host directory (pwd) to the WORKDIR (/app) in the container:
```bash
docker build -t imagename:tag .
docker run -it -p 1234:1234 -v $(pwd):/app imagename:tag
```

Or, with docker-compose.yml

```yml
version: '3.6'
services:
  server:
    build: .
    volumes:
    - .:/app
    ports:
    - "3000:3000"
```
Then run 
```bash
docker-compose up --build
```

**Comment by remy** [comment]
@haydenlinder do you think this (your solution) belongs in the FAQ?

**Comment by haydenlinder** [comment]
@remy probably wouldn't hurt to add it to a 'using with Docker' section.

**Comment by puschmie** [comment]
I ran into the same issue yesterday and found this thread. None of the suggested solutions worked.

Turned out I hadn't installed nodemon in the host directory before building the docker container. I didn't think this would matter, since I had nodemon in my package.json and with a certain WORKDIR and COPY configuration it would start but then crash with the same error as mentioned in the beginning of this thread. What I did to solve it is:

In the Dockerfile (backend being the subdirectory where the node code is located)
`FROM node:12-alpine
WORKDIR /backend
COPY package.json ./
COPY package-lock.json ./
COPY . .
RUN npm install`

Mount ./backend to /backend volume in docker-compose.yml
`volumes:
      - './backend:/backend'`

Then I ran 
`npm install nodemon`
in ./backend before building the container.

Could it be that the suggested solution didn't work because of how I mounted the volume?

I'm also really confused by your solution @haydenlinder 
Shouldn't `WORKDIR` set the working directory so `COPY . .` would copy into the specified directory?

**Comment by haydenlinder** [comment]
@puschmie, if you used
```
WORKDIR /backend
            ^ where to create the project in the container
```

then you need 

```
COPY . /backend 
-----^  ^ where to spit it out in container
|
where on your machine to copy code relative to Dockerfile 
```

assuming your file structure is like this:
```
project/
    docker-compose.yml
    backend/
        Dockerfile
.
.
.
```

**Comment by iannotian** [comment]
You can use a relative file path with `COPY` after setting a `WORKDIR`. So `COPY . .` will also work in lieu of `COPY . /backend`.
