### ISSUE TITLE
.nodemonignore breaks with symlinks from outside project

### ISSUE THREAD

**Issue by zyklus** [remy/nodemon#179]
I have the following structure:

```
- project
|-- public
   |-- external --> symlink to something outside of project
```

my .nodemonignore file says to ignore `public`.  It ignores all files in public _except_ those that are in `external`

I keep getting messages that nodemon is restarting due to the file in the actual path of `external` being changed.

I can't figure out how to get nodemon to ignore that directory since it's outside of the project root.  I can't make it ignore `/home/user/path/to/external`, so...???

**Comment by Kerumen** [comment]
Bump, I also have this issue today.
