### ISSUE TITLE
Nodemon version 2.0.6 is not logging consoles 

### ISSUE THREAD

**Issue by mukundlalge100** [remy/nodemon#1791]
Hi ,

I had updated nodemon to 2.0.6  latest version but nodemon is not printing any logs . But with node command i am able to see logs . I am not sure what is going wrong . 
- `nodemon -2.0.6`:
- `node -14.15.0`:
- Operating system/terminal environment:- Windows 10  
- Command you ran: nodemon App.js

[nodemon] 2.0.6
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node App.js`

Above logs are printing and it is visible in git bash ,command prompt,powershell . 

**Other application logs are getting printed but is it not visible may be color of logs are not correct or something . I have copied those lines which are blanks and pasted in notepad , so these blanks lines are my application logs . But for git bash ,command prompt,powershell it is only showing blanks lines .** 

I hope I explained issue in right way ,because it is really weird issue.

**Comment by remy** [comment]
Can you provide a simplified version of `App.js` that replicates the issue? If not, it can't be debugged by anyone.
