### ISSUE TITLE
nodemon ignores changes in watched directories

### ISSUE THREAD

**Issue by elspecal** [remy/nodemon#1793]
Hi! I'm working with a dead simple Express app in WSL 2 Ubuntu. Project resides on a mounted NTFS partition and its structure is the following:
```
app.js
models
|__author.js
|__book.js
node_modules
|__...
nodemon.json
package-lock.json
package.json
schema
|__schema.js
```
Now I cannot for the life of me figure out how to make Nodemon restart the server upon changes to files under 'models' and 'schema' directories. It is only triggered by changes in files that are in the root folder like app.js and nodemon.json. The nodemon.json is only 3 LOC:
```
{
  "watch": [ "schema", "models", "./" ]
}
```
Before that I tried `nodemon --watch schema/ --watch models --watch . app`. No luck. Seems like a bug to me. 

- Operating system/terminal environment:  **WSL2 Ubuntu on Win10 19042.572**
- Using Docker? **No**
- Command you ran: `nodemon app`

Here is the output of `nodemon --dump`:

```
[33m[nodemon] 2.0.6[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching path(s): schema/**/* models/**/* **/*[39m
[33m[nodemon] watching extensions: js,mjs,json[39m
--------------
node: v15.0.1
nodemon: 2.0.6
command: /home/<me>/.nvm/versions/node/v15.0.1/bin/node /home/<me>/.nvm/versions/node/v15.0.1/bin/nodemon --dump
cwd: /mnt/e/dev/graphql_exercise/server
OS: linux x64
--------------
{
  run: false,
  system: { cwd: '/mnt/e/dev/graphql_exercise/server' },
  required: false,
  dirs: [
    '/mnt/e/dev/graphql_exercise/server/schema',
    '/mnt/e/dev/graphql_exercise/server/models',
    '/mnt/e/dev/graphql_exercise/server'
  ],
  timeout: 1000,
  options: {
    dump: true,
    watch: [ 'schema', 'models', './', re: /schema|models|\.\// ],
    ignore: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**',
      re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/
    ],
    monitor: [
      '/mnt/e/dev/graphql_exercise/server/schema/**/*',
      '/mnt/e/dev/graphql_exercise/server/models/**/*',
      '/mnt/e/dev/graphql_exercise/server/**/*',
      '!**/.git/**',
      '!**/.nyc_output/**',
      '!**/.sass-cache/**',
      '!**/bower_components/**',
      '!**/coverage/**',
      '!**/node_modules/**'
    ],
    ignoreRoot: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**'
    ],
    restartable: 'rs',
    colours: true,
    execMap: { py: 'python', rb: 'ruby', ts: 'ts-node' },
    stdin: true,
    runOnChangeOnly: false,
    verbose: false,
    signal: 'SIGUSR2',
    stdout: true,
    watchOptions: {},
    execOptions: {
      script: 'index.js',
      exec: 'node',
      args: [],
      scriptPosition: 0,
      nodeArgs: undefined,
      execArgs: [],
      ext: 'js,mjs,json',
      env: {}
    }
  },
  load: [Function (anonymous)],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [ '/mnt/e/dev/graphql_exercise/server/nodemon.json' ],
  watchInterval: null,
  signal: 'SIGUSR2',
  command: {
    raw: { executable: 'node', args: [ 'index.js' ] },
    string: 'node index.js'
  }
}
--------------
```

### Expected behaviour
Server restart on changes in files in root folder as well as "schema" and "models" directories.

### Actual behaviour
Nodemon ignores changes to files in some directories and triggered by changes to those directly in the root folder.

### Steps to reproduce
Specify watch directories either via command line arguments or in nodemon.json.

**Comment by oviecodes** [comment]
@elspecal try the following
{
  "ignore": [ "*.coffee" ],
  "watch": [ "server/*.coffee", "test/" ]
}
Since they are directories put a foward-slash in front of the directory name. That should work fine.

**Comment by elspecal** [comment]
I'm confused by your code. Is ignoring files with .<ext> extension and then explicitly telling Nodemon to watch them in the root folder supposed to somehow solve my problem? 'server' is the name of the root folder in my case so Nodemon should not find it this way. I suspect that I'm missing something here... As for putting the slash after the directory names, I tried both ways and it does not seem to make any difference.

**Comment by oviecodes** [comment]
@elspeca, I was just showing how you could ignore files and watch them, since you need to watch files, you just need the watch part of the code above
Try
"watch": [ "schema/*", " models/*" ]
If this doesn't work, then maybe check your Nodemon.json config.

**Comment by oviecodes** [comment]
@elspecal I was just show you how you could watch files or ignore them, since u just need to watch files then try what's in the watch part of the code above. You're not suppose to ignore file you want to watch, that was just an example. The files in schema and models directory aren't they .js files. Nodemon automatically watches .js files. Just run Nodemon app.js or nodemon server.js, it'll watch all files with .js extension.

**Comment by elspecal** [comment]
Yes I started with that, just straight running it as `nodemon app.js` expecting it'll do what I want it to do. However it does not comply.

**Comment by Skyclo** [comment]
I can confirm that I am too having the issue. It was working just fine yesterday and nothing has changed since then (I haven't even restarted my PC yet.) Even when including or excluding watched files/extensions (by invoking `nodemon index.js`), changes are not watched. I am running WSL1 on Windows 10 ver. 2004. It works completely fine in Powershell, Windows CMD, and on Linux. I am assuming that the issue is with WSL and not nodemon.

**Comment by elspecal** [comment]
In the wake of that previous comment I looked for the issue on wsl and it turns out that the project needs to reside on the linux root file system in case of wsl2. now that i moved the project from '/mnt/e/...' to '/home/...', Nodemon is working as expected.
