### ISSUE TITLE
very confusing name

### ISSUE THREAD

**Issue by biocrypto730** [remy/nodemon#1795]
When i was learning to code, i thought the name of this program was "no demon". i had no idea why that was the name but i figured i would learn it eventually. like how a "Bug" in code used to be actual bugs back in the day, i figured there was a similar story for "demons".

A little later i realized that this was like "daemon". and it was a great feature to me, that i could create a "daemon" without having to actually make one, just by calling "no daemon". I didn't know how to make a "daemon", i had always used the "no daemon". this "nodemon" was great.

Finally, after easily creating a number of daemons, because they are not hard to make, i realize today it is called "node daemon".  There's not a lack of a daemon because it is a daemon itself. There's no "no" daemon, it's the "node daemon".

This isnt on the web anywhere but I think i'm right. Can you officialize this somewhere? Am I even right?

**Comment by remy** [comment]
Close, but no dice: https://github.com/remy/nodemon#pronunciation
