### ISSUE TITLE
Question: Is it possible to execute separate commands based upon different watch sets?

### ISSUE THREAD

**Issue by b4git** [remy/nodemon#1796]
Just wanted to know if it is possible to execute separate commands based upon which directory or files changed.

For example, want to achieve something like this:
```
nodemon --watch ./dir1 --exec "command for changes in dir1 only" --watch ./dir2 --exec "command for changes in dir2 only" --watch ./directory3 --exec "command only when directory3 content changes etc."

```

Currently, if a command is entered like above, it is only watching and executing the last command.

**Comment by b4git** [comment]
Currently I am running different shells or subshells to achieve it.

**Comment by remy** [comment]
I missed this original question, but in short: no. This sounds like it's more suited to a tool like npm scripts.
