### ISSUE TITLE
Nodemon doesn't kill Node Child Processes

### ISSUE THREAD

**Issue by Xenfo** [remy/nodemon#1799]
- `nodemon -v`: 2.0.6
- `node -v`: 14.13.1
- Operating system/terminal environment: Windows 10
- Command you ran: `npm run start:dev` --> `nodemon bin/app.js`

### Expected behavior
For Nodemon to kill child processes.

### Actual behavior
Nodemon leaves the child running.

### Steps to reproduce
Create node exec child with a specified LocalTunnel URL.
After a few reruns, the LocalTunnel URL is taken because Nodemon didn't kill it.

**Comment by remy** [comment]
Please provide code to replicate with - pared down to the minimum script.

**Comment by Xenfo** [comment]
1) index.js
```
import express from 'express';
import bodyParser from 'body-parser';
import localtunnel from 'localtunnel';

export const app = express();
const PORT = 3000;

app.use(bodyParser.json());

app.listen(PORT, () => console.log(`Server running on port ${PORT}`));

(async () => {
    const tunnel = await localtunnel({ port: 3000, subdomain: 'customURL' });

    console.log(tunnel.url);
})();
```

2) nodemon index.js

3) rs

4) rs

Notice that the original URL, customURL, changed to some random string now. If you Control + C and restart Nodemon you have the URL back.
