### ISSUE TITLE
nodemon index.js -L now required to observe changes on Big Sur?

### ISSUE THREAD

**Issue by bonbonio** [remy/nodemon#1803]
Hello,

````
npm: 6.14.8
node: 14.15.1
nodemon: 2.0.6
````

I have just upgraded to use MacOS Big Sur and I notice that nodemon no longer seems to correctly watch file changes on a Node project.

After some trial and research, it now works if I use this;

````
nodemon index.js -L
````

This never used to be used, and I can't see how my file system is legacy? Is this a bug; or do I need to change a setting in VS Code or something?

Hope this helps anyone with the problem.

**Comment by remy** [comment]
I don't have Big Sur to test with myself, but I suspect the file watching component is down to how Chokidar operates.

Can you post the result of `npm ls chokidar` in the directory you have nodemon installed? There will be a version - i.e. for me (though I'm in a dev mode, so the output is slightly different):

```
└─┬ nodemon@0.0.0-development -> /Users/remy/dev/nodemon
  └── chokidar@3.4.0  extraneou
```

**Comment by bonbonio** [comment]
Thanks for the quick reply.

````
projectxx-xxx@1.0.0 /System/Volumes/X/X/X/xx-xxx
└─┬ onchange@7.1.0
  └── chokidar@3.4.3 
````
