### ISSUE TITLE
Nodemon restarts even without any changes

### ISSUE THREAD

**Issue by feline87** [remy/nodemon#1805]
- `nodemon -v`: 2.0.6
- `node -v`: 12.16.12
- Operating system/terminal environment: 
- Using Docker? What image: 
- Command you ran: Holding down Ctrl + S in Visual Studio Code

### Expected behaviour
No restarts if the file hasn't changed

### Actual behaviour
The application restarts even when the file hasn't changed at all

### Steps to reproduce
Hold down Ctrl + S in Visual Studio Code and watch the "restarting due changes..." message spamming the terminal.
[nodemon] restarting due to changes...
[nodemon] starting `node index index.js`
[nodemon] restarting due to changes...
[nodemon] starting `node index index.js`
[nodemon] restarting due to changes...
[nodemon] starting `node index index.js`
[nodemon] restarting due to changes...
[nodemon] starting `node index index.js`
[nodemon] restarting due to changes...
[nodemon] starting `node index index.js`
[nodemon] restarting due to changes...
[nodemon] starting `node index index.js`
[nodemon] restarting due to changes...
[nodemon] starting `node index index.js`
Listening to port 8080
---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Run with `nodemon -v` and you'll get _why_ it's restarting. I'd be prepared to bet that your `index.js` is generating a file in the working directory.

You've not provided any code by which anyone can test with, so I'm going to assume (for the moment) that this is the case and will close.

Happy to re-open if that's not the case and you're able to provide pared down code to replicate with.

Thanks!
