### ISSUE TITLE
not working with npm-run-all --parallel in v2.0.6

### ISSUE THREAD

**Issue by danny007in** [remy/nodemon#1808]
`"scripts": {`
     `"watch": "npm-run-all --parallel watch-css watch-js",`
   ` "watch-css": "nodemon --watch build/scss -e scss -x \"npm-run-all css-lint css\"",`
   ` "watch-js": "nodemon --watch build/js -e js -x \"npm-run-all js-lint js\""`
  `}`

no working with [npm-run-all](https://www.npmjs.com/package/npm-run-all)
Extra reference check and run `npm run dev` [AdminLTE](https://github.com/ColorlibHQ/AdminLTE/tree/791daf70f9d17ec4987580238e675bbe0847c3b1)

**Comment by remy** [comment]
This feels like a question that should be directed at the npm-run-all maintainers. 

If you use nodemon directly, it works as intented. I can know anything about how some other product works, sorry.

**Comment by danny007in** [comment]
> 
> 
> This feels like a question that should be directed at the npm-run-all maintainers.
> 
> If you use nodemon directly, it works as intented. I can know anything about how some other product works, sorry.

It was working fine in nodemon v2.0.4

**Comment by remy** [comment]
You've not described what isn't work and I both don't use npm-run-all or am familiar with it. So you'll need to provide a working example before [looking at the diff](https://github.com/remy/nodemon/compare/v2.0.4...v2.0.6) is any use.

You've just said "no working with" - so does that mean it doesn't run? Does it mean it doesn't restart? Does it mean you get errors… provide some context and we (you and I) can look at it. Provide no context and there's no use.

**Comment by danny007in** [comment]
> 
> 
> You've not described what isn't work and I both don't use npm-run-all or am familiar with it. So you'll need to provide a working example before [looking at the diff](https://github.com/remy/nodemon/compare/v2.0.4...v2.0.6) is any use.
> 
> You've just said "no working with" - so does that mean it doesn't run? Does it mean it doesn't restart? Does it mean you get errors… provide some context and we (you and I) can look at it. Provide no context and there's no use.

I checked once again, it was not the issue of nodemon version.
Is issue of nodejs v14.
nodemon works fine in nodejs v12, but not in nodejs v14 latest
