### ISSUE TITLE
Keeps Prompting me to update when I am already updated

### ISSUE THREAD

**Issue by GaddMaster** [remy/nodemon#1809]
- `nodemon -v`: 2.0.6
- `node -v`: 12.18.0
- Operating system/terminal environment: Windows 10
- Using Docker? What image: 
- Command you ran: CTRL + C (Twice to stop process in cmd)

### Actual behaviour: Ask em to update to 2.0.6

Install node mon and use for a while, happens eventually and many times when stopping cmd server process

**Comment by remy** [comment]
Try removing your `~/.config/configstore/update-notifier-nodemon.json` - not sure where exactly it lives in Windows, but it's reading that file. My guess is that somehow that file doesn't exist or there's write permissions that are wrong. This should solve the issue.
