### ISSUE TITLE
Question: Is it possible to change the label `[nodemon]` and color of the message?

### ISSUE THREAD

**Issue by cawa-93** [remy/nodemon#1813]
My app uses 3-4 nodemon watchers at a time. This leads to confusion in the log.
```
[nodemon] starting ...
[nodemon] starting ...
[nodemon] starting ...

...

[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
```

It would be great to be able to set your own label and color for each nodemon's watchers so that they can be distinguished in the log.
```
[proccess-1] starting ...
[proccess-2] starting ...
[proccess-3] starting ...

...

[proccess-1] restarting due to changes...
[proccess-2] restarting due to changes...
```

_P.S. I'm sorry if I write in the wrong place. I did not find where to ask questions._

**Comment by remy** [comment]
You asked in the right place, but the answer is _technically_ yes, but it requires that you use nodemon as a required module and _you_ control the printed output.

Out of the box (or rather directly on the command line), it's not possible.

Hope that answers your question.
