### ISSUE TITLE
Option to restart without file changes detected

### ISSUE THREAD

**Issue by andrisi** [remy/nodemon#1814]
Sometimes apps exit gracefully on error, and need to be restarted - eg. kept alive - even if there is no change in the files, as the cause of the exit is external to the app. Please add a config option to rerun the app automatically, perhaps with an optional delays. Thanks.

**Comment by remy** [comment]
If this is set as an option, then it would actually be auto-restarting the user code regardless of errors, which is more akin to tools like pm2 or upstart. nodemon is for development and I can't see how this would be a useful (or even sensible) addition for a tool that's intended exclusively for development.

Am closing the issue, but happy to discuss if you think I've missed some important factor.

**Comment by andrisi** [comment]
Sure, I understand, if nodemon is only/strictly development.

**Comment by r3wt** [comment]
@remy i humbly beg you to reconsider your stance that this is "only for development". managing signals is hard enough for one process manager, let alone doing it in the same app for multiple ones. i really want to use nodemon for production. we've finally got our signal handling right between the main process and its child processes which are java, the only problem is when we need to programmatically restart the server ocassionally. i had tried to do that, only to be greeted with nodemon message:

> [nodemon] clean exit - waiting for changes before restart

I have one question, if i do the PR for your library and its up to your standards, would you atleast consider accepting it?
