### ISSUE TITLE
Pass in a variable via package.json

### ISSUE THREAD

**Issue by goktugyil** [remy/nodemon#1818]
I call the function start and it calls nodemon.

package.json
```
"start": "nodemon",
```

nodemon.json
```
"exec": "ts-node app.js",
```

However, I want to pass in a variable, specifically `--inspect=0.0.0.0` for memory debugging. 

How can I pass this variable inside nodemon? 

I tried creating a second command `"exec2": "ts-node --inspect=0.0.0.0 app.js",` and call "nodemon --exec2"
I tried other stuff, but have failed. 

---

Ideally I'll have something like this:
package.json
```
"start": "nodemon",
"startinspect": "nodemon execinspect",
```

nodemon.json
```
"exec": "ts-node app.js",
"execinspect": "ts-node --inspect=0.0.0.0 app.js",
```

**Comment by remy** [comment]
You want `--config` to point to a different config file. See `nodemon --help` for usage.
