### ISSUE TITLE
[Guidance] How to watch based on pattern? 

### ISSUE THREAD

**Issue by arpowers** [remy/nodemon#1819]
Looking for a bit of guidance on Nodemon watching. 

In our use case, we'd only like to have the server restart if the changed file has the word "server" in it somewhere (there is some overhead to server restart ~10s)

In the documentation, it's clear we can ignore based on glob, but not watch. Is this possible? How should this be achieved?

**Comment by remy** [comment]
What have you tried so far? I'm not entirely sure glob watch support is in there … but it might be that support is there without my knowing (i.e. accidentally).

**Comment by Isaius** [comment]
You can do it with nodemon.json file like that:

```json
{
  "watch": [],
  "execMap": {
    "server-*.js": "nodemon server-test.js"
  }
}
```

Then, any change in a file named "server-" will restart the application and trigger the `nodemon server-test.js`
You can try with these two files:

server-test.js
```js
while(true){
  // nothing to do, just keep alive
}
```
server-2.js
```js
console.log("Restarting...")
```
Try add more lines in the server-2.js file.

**Comment by arpowers** [comment]
@Isaius @remy thanks guys, that should work great!
