### ISSUE TITLE
Server not starting after changes

### ISSUE THREAD

**Issue by MickieBlair** [remy/nodemon#1820]
- `nodemon -v`: 2.0.6
- `node -v`: v14.15.3
- Operating system/terminal environment: Windows 10/ 
- Using Docker? What image: no docker
- Command you ran: codemon server.js --verbose

### Expected behaviour
[nodemon] starting `node server.js`

after the restart

### Actual behaviour

blair@BlairM MINGW64 ~/Desktop/UdemyWebBootcamp/express_server
$ nodemon server.js --verbose
[nodemon] 2.0.6
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 10712 to restart
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
[nodemon] forking
[nodemon] child pid: 17752
[nodemon] watching 3 files

Example app listening at http://localhost:3000
[nodemon] files triggering change check: server.js
[nodemon] matched rule: **\*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] server.js

[nodemon] files triggering change check: server.js
[nodemon] matched rule: **\*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] server.js

### Steps to reproduce

server.js

const express = require('express');
const app = express();
const port = 3000;

app.get('/', (req, res) => {
  res.send('Hello Tnbnbnbnfdsdfsdfsdfbnhis!');
});

app.listen(port, () => {
  console.log(" ");
  console.log(`Example app listening at http://localhost:${port}`);
});

package.json

{
  "name": "express_server",
  "version": "1.0.0",
  "description": "a server",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  },
  "author": "Mickie",
  "license": "ISC",
  "dependencies": {
    "express": "^4.17.1"
  }
}

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by m-s-morgan** [comment]
I'm seeing this same issue. Manually pressing enter will continue the restart, but that's obviously not a solution.

**Comment by remy** [comment]
Can you try node@12 - just to rule out the possibility of it being node - since this is the absolute base level interaction and it would normally work fine.

@m-s-morgan I'm not sure what you're referring to - the OP doesn't mention having to press enter…

**Comment by MickieBlair** [comment]
The exact same thing happens when I try with the following node version.   Pressing enter doesn't work for me at all.  It just advances a blank line.   I tried reading the other posts from regarding the past issues and none of the other solutions from the prior ones seems to help.  It seems like all the ones I read were windows of course.   So I am pretty hopeless about being able to use nodemon.

node -v :   v12.13.0

$ nodemon -v:  2.0.6

{
  "name": "express-node12",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.17.1"
  }
}

blair@BlairM MINGW64 ~/Desktop/UdemyWebBootcamp/express-node12
$ nodemon server.js --verbose
[nodemon] 2.0.6
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 18408 to restart
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
[nodemon] forking
[nodemon] child pid: 14152
[nodemon] watching 3 files

Example app listening at http://localhost:3000
[nodemon] files triggering change check: server.js
[nodemon] matched rule: **\*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] server.js



[nodemon] files triggering change check: server.js
[nodemon] matched rule: **\*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] server.js

**Comment by m-s-morgan** [comment]
@remy sorry for the confusion. I was simply stating that I'm experiencing similar behavior where the server will attempt to restart after changes, but will hang at "restarting due to changes..." Pressing enter will proceed with the restart in my case but it doesn't seem to do so for @MickieBlair

**Comment by danny007in** [comment]
Also https://github.com/remy/nodemon/issues/1826 check this
