### ISSUE TITLE
How to configure nodemon.json to run node with arguments which contains space 

### ISSUE THREAD

**Issue by chucklu** [remy/nodemon#1823]
- `nodemon -v`: 2.0.6
- `node -v`: v12.18.0
- Operating system/terminal environment:  win10/cmd.exe
- Command you ran:

Configuration in nodemon.json

```
  "events": {
	"exit": "node printdate.js \"cleanly exited\""
  }
```

### Expected behaviour

I test the node command `node printdate.js "cleanly exited"` successfully  with cmd.exe, and the output is

> cleanly exited at 2021-01-06 17:32:42 408ms UTC+8

The parameters were 

```
[
  'node.exe',
  'printdate.js',
  'cleanly exited'
]
```

### Actual behaviour
'display at 2021-01-06 17:32:42 408ms UTC+8
The parameter generated by nodemon were

```
[
  'C:\\Program Files\\nodejs\\node.exe',
  'C:\\workspace\\Edenred\\UK\\Connect_Incentive_Frontend\\vueSrc\\printdate.js',
  '"cleanly',
  'exited"'
]
```

**What happened here? why the last parameter was divided into two parts?**

### Steps to reproduce

The content of printdate.js  is as following
```js 
//console.log(process.argv);
var myArgs = process.argv.slice(2);
//console.log('myArgs: ', myArgs);

const dateTime = require('date-time');
var currentTime = dateTime({local: true, showTimeZone: true, showMilliseconds: true});
console.log(`${myArgs[0]} at ${currentTime}`)
```

**Comment by remy** [comment]
This seems to be windows specific (if anyone wants to have a shot) - also it's not clear from original post if this is spaces in nodemon args or nodemon events.

Running on mac/linux:

```
nodemon -- "testing"                                                                                                                       
[nodemon] master: 2967726673496ae6cf35904cb4e83013c6e2ccd3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js testing`
testing at 2021-01-06T10:21:04.104Z
[nodemon] clean exit - waiting for changes before restart
cleanly exited at 2021-01-06T10:21:04.166Z
```

index.js:

```
//console.log(process.argv);
var myArgs = process.argv.slice(2);
//console.log('myArgs: ', myArgs);

var currentTime = new Date().toJSON()
console.log(`${myArgs[0]} at ${currentTime}`)
```

nodemon.json:

```json
{
  "events": {
    "exit": "node index.js \"cleanly exited\""
  }
}
```

**Comment by chucklu** [comment]
@remy But I can execute `node printdate.js "cleanly exited"` through cmd.exe on Windows correctly.

**Comment by remy** [comment]
@chucklu remember you're also going through npm

**Comment by chucklu** [comment]
@remy  Do you mean this is a bug of npm?

**Comment by caesay** [comment]
Make sure you are not mix-matching single and double quotes: 

```
  "scripts": {
    "start": "nodemon index.js \"cleanly exited\""
  },
```

Ran with `npm start` works just fine on my Windows system, however by replacing the double quotes with single quotes I can re-produce what you have experienced.

**Comment by chucklu** [comment]
@caesay  Thanks, I will check it. I did not notice that @remy  had already modified the exit script in previous comment.

Currently I encounter another issue, which blocked me to confirm the escape double quotes

> [nodemon] clean exit - waiting for changes before restart
> internal/modules/cjs/loader.js:969
>   throw err;
>   ^
> 
> Error: Cannot find module 'C:\workspace\vueSrc\index.js'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }

**Comment by chucklu** [comment]
@caesay  Still did not work, use the same script as you provided 
```
"exit": "node printdate.js \"cleanly exited\""
```
What I got is as following, still break at the space
```
"cleanly at 2021-03-25 10:51:11 121ms UTC+8
```

**Comment by chucklu** [comment]
@remy  @caesay

**Comment by remy** [comment]
The commit that closed this issue (early) adds the fix for windows for this particular issue. The release should auto tag this issue, but if not it'll be in 2.0.11.

**Comment by chucklu** [comment]
@remy  Thanks for you fix, it works now with the following configuration section in nodemon.config

> "exit": "node printdate.js \"cleanly exited\""
