### ISSUE TITLE
nodemon --exec causes an app crash on Windows with Node v15.15.1

### ISSUE THREAD

**Issue by wesdse001** [remy/nodemon#1827]
Happy new year all! I recently upgraded node to version `15.5.1` from `14.15.3`. Now when I start my app using the following script. I get an error.

```
"scripts": {
  "start": "nodemon --exec babel-node src/index.js"
},
```

Here are the dependencies I have:

```
"@babel/cli": "^7.12.10",
"@babel/core": "^7.12.10",
"@babel/node": "^7.12.10",
"nodemon": "^2.0.6"
```

- `nodemon -v`: 2.0.6
- `node -v`: 15.5.1
- Operating system/terminal environment: Windows Powershell
- Command you ran: `nodemon --exec babel-node src/index.js`

### Expected behaviour

The app should start. This works on node version `14.15.3` using a windows computer.

### Actual behaviour

The following error occurs:

```
[nodemon] starting `babel-node src/index.js`
'babel-node' is not recognized as an internal or external command, operable program or batch file.
[nodemon] app crashed - waiting for file changes before starting...
```
Note: I tested this out on my macOS computer, no error occurs, even on node version `15.5.1`, so, this seems to be a windows error.

Thanks you for your help!

**Comment by danny007in** [comment]
cause is devDep and dev not updated.
And in node 14.x https://nodejs.org/docs/latest-v14.x/api/deprecations.html#DEP0134 by starting from there many functions deprecated

**Comment by danny007in** [comment]
Deprecated lists are 

- https://nodejs.org/docs/latest-v14.x/api/deprecations.html#DEP0144

**Comment by remy** [comment]
Depreciation does not mean doesn't work.

Also, the devdeps are not installed by user but by the developers of nodemon (sum total is 1= me), so those have no impact.

That's to say: that's super unlikely to be the issue.

**Comment by wesdse001** [comment]
Hi @remy and @danny007in I modified my command to the following and it worked:

```
nodemon --exec ./node_modules/.bin/babel-node src/index.js
```

On windows machines, it seems you have to specify the absolute path to babel-node to get it working.

I got this solution from here [https://stackoverflow.com/a/65859915](https://stackoverflow.com/a/65859915)

**Comment by gameprogrammingsteven** [comment]
This comes up if you're using Windows in the React: Zero to Full Stack lesson 9.6 on O'Reilly's learning. I'm getting the same error with the same line. Removing "npx" and using the full path, as wes said above, I'm confirmed is working. I just did it. You may find a bunch of people going here due to that material on the Safari Books/OReilly media. This info should help future people with similar issues
