### ISSUE TITLE
Error when running via Vscode and type is pwa-node

### ISSUE THREAD

**Issue by yaronlevi** [remy/nodemon#1828]
Hi (-:

I want to use the built-in latest node debugger in Vscode so I've set type = pwa-node in the vscode launch options like so:

![image](https://user-images.githubusercontent.com/5398977/104089661-45c52300-5279-11eb-936d-cb98c737376e.png)

and now I am getting the error:

unable to run executable: "node"

![image](https://user-images.githubusercontent.com/5398977/104089687-68573c00-5279-11eb-9f55-4b0f9bd214cb.png)

Any idea what wrong and how do we get Nodemon to run fine with pwa-node?

**Comment by remy** [comment]
It says in your screenshot: `unable to run executable "node"`

I'd remove nodemon from the workflow first and make sure that you can call a script that can then run node in that mode (I'm not familiar with the pwa-node debugging mode) - and then I suspect it'll come together.

**Comment by gurnoor-garry** [comment]
1. Open powershell as Administrator
2. paste this code : set-executionpolicy remotesigned
3.hit enter
