### ISSUE TITLE
Nodemon is not restarting server upon change.

### ISSUE THREAD

**Issue by farhan2077** [remy/nodemon#1830]
Following the tutorial by thenetnija, I set up an express app with nodemon installed globally. Last time I tried it was working. About a month later, today I tried to do the same but nodemon is not working. If I run `nodemon app` it starts the `localhost:3000` server. But whenever I make any change to any any `ejs` file, nodemon doesn't restart the server automatically. I have to refresh manually. I tried uninstalling and reinstalling the latest version of nodemon globally but that didn't work either.
- `nodemon -v`: 2.0.7
- `node -v`: 14.15.0
- Windows 10 -v2004 (build -19041.388)
- Not using docker 
- command I am using - `nodemon app`

This is what in my terminal appears when I run `nodemon app` -
```
D:\Project_Web\node_blog_test>nodemon app
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
(node:13924) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by caesay** [comment]
From your logs, nodemon is: 
> [nodemon] watching extensions: js,mjs,json

You mentioned that if you change a `ejs` file it does not restart: that should be expected. If you wish for nodemon to watch this file, please specify which extensions you would like to watch with the `-e` argument. For example

> nodemon app.js -e js,ejs

**Comment by farhan2077** [comment]
Thank you @caesay. Now it's working.
