### ISSUE TITLE
does nodemon support hmr updates without restarting?

### ISSUE THREAD

**Issue by zcaudate** [remy/nodemon#1831]
I was redirected to ask here from https://github.com/Izhaki/nodemon-webpack-plugin/issues/126

I've been playing around with `react-blessed-hot-motion`
and it does something very similar to [nodemon-webpack](https://github.com/gaearon/react-blessed-hot-motion/blob/master/server.js#L50), though only restarting the app on a `running` flag and then deferring to [hmr](https://github.com/gaearon/react-blessed-hot-motion/blob/master/src/index.js#L29) for the hot code reloading.

Since this repo is 5 years old, what's the best way of getting this to work with the newest version of nodemon?

**Comment by remy** [comment]
This repo is 10 years old.

HMR is out of scope for nodemon and very specific to a very small subset of developers.

You can use nodemon as a required module (as I'd imagine nodemon-webpack might do) so you'd be able to extend on top of nodemon. 

Hope that helps.
