### ISSUE TITLE
Can't run nodemon with --inspect flag

### ISSUE THREAD

**Issue by Lukasz199312** [remy/nodemon#1832]
In package.json i have this `"dev": "nodemon --inspect"`. and in nodemon.json
```
{
    "watch": ["src"],
    "ext": ".ts,.js",
    "ignore": [],
    "exec": "ts-node ./bin/www"
  }

```
with this configuration my server starts without debug mode.

**Comment by civts** [comment]
I may have had the same problem.  
Ts-node has a particular syntax for passing the --inspect argument ([link](https://github.com/TypeStrong/ts-node#programmatic))

Try to:
1. remove `--inspect` from your `"dev": "nodemon --inspect"`
1. replace `ts-node ./bin/www` with `node -r ts-node/register --inspect ./bin/www`

This should fix the problem.

After that, you may also consider moving `./bin/www` in the package.json script, ending up with the following:

- nodemon.json:
  ```json
  {
    "watch": ["src"],
    "ext": ".ts,.js",
    "ignore": [],
    "exec": "node -r ts-node/register --inspect"
  }
  ```
- package.json:
  ```json
  ...
  "scripts" : {
    "dev": "nodemon ./bin/www"
  }
  ...
  ```

**Comment by remy** [comment]
> replace ts-node ./bin/www with node -r ts-node/register --inspect ./bin/www

☝️ this.

Thank you @civts 👍

**Comment by bmaupin** [comment]
I didn't have a separate nodemon.json folder, so I just appended `-r ts-node/register --inspect` to the end of my nodemon script in package.json, e.g.

```json
    "dev": "nodemon --watch src src/index.ts -r ts-node/register --inspect",
```
