### ISSUE TITLE
nodemon not fails to restart my server

### ISSUE THREAD

**Issue by Joshuajee** [remy/nodemon#1833]
When i start my server with nodemon index.js, it runs fine, but when i make changes to my script it logs that it is restarting the server due to changes,  but it doesn't restart the server and and i will have to terminate the process and rerun the command before my changes get acknownledged, the only time automatic reload works is when there is an error in my script, when the command was first ran, it automatically reloads but once the script runs successfully it stops restarting the server.

- `nodemon -v2.0.7`:
- `node -v8.1.1`:
- `Operating system/windows10`
- `Command you ran: nodemon index.js`

### Actual behaviour
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js`
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...

### Steps to reproduce
nodemon index.js

**Comment by caesay** [comment]
I do not think you have provided enough information, as the issue is likely specific to your project. Can you post small project on GitHub which replicates/demonstrates this issue with steps to reproduce?

**Comment by Joshuajee** [comment]
it is a very large project it also has reactjs as a sub directory

**Comment by caesay** [comment]
Please create a minimal number of steps to reproduce the issue. You can do this by detailing the steps here or by creating a new small repository containing _only_ the code needed to re-create the issue.

**Comment by Joshuajee** [comment]
i created a nodejs project, in my package.json file i add "dev: nodemon index.js" to the script object,
this is the script object from package.json below
 "scripts": {
    "start": "node index.js",
    "dev": "nodemon index.js",
    "game": "npm run start --prefix game_ui",
    "train": "node game_env/index.js"
  },
then i went to cmd to run `npm run dev`
the code ran but whenever i made a change to my code the server fails to restart

**Comment by Joshuajee** [comment]
Fixed it, turns out i just needed to add
C:/windows/system32 to my path
