### ISSUE TITLE
nodemon executable (nodemon, nodemon.cmd) files are not available with yarn

### ISSUE THREAD

**Issue by hckhanh** [remy/nodemon#1834]
I figured out when I try to upgrade from nodemon 1 to 2. It removed the executable files from `.bin` in `node_modules`

- `nodemon -v`: 2.0.7
- `node -v`: 14.15.4
- Operating system/terminal environment: Windows 10
- Using Docker? What image: No
- Command you ran: yarn start

### Expected behaviour
When I try to run the nodemon with yarn. I get this error:

```
'nodemon' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
```

### Actual behaviour
nodemon should run smoothly

### Steps to reproduce
1. Install nodemon from Yarn
2. Add `nodemon src/index.js --exec babel-node -e js` to `start` script in `package.json`

```json
"scripts": {
    "start": "nodemon src/index.js --exec babel-node -e js"
  },
```

But when I try to install nodemon with `npm`, the executable files have existed.

**Comment by caesay** [comment]
I was unable to reproduce this on my Win10 system with npm 6.9.0, node 10.16.0, yarn 1.22.10.
`yarn add nodemon` correctly added the files to `.bin` and could be used normally.
