### ISSUE TITLE
User home paths (tilde '~') not working for watch path globs

### ISSUE THREAD

**Issue by mkormendy** [remy/nodemon#1835]
**nodemon**: 2.0.6
**node**: 14.9.0
**Operating system/terminal environment:** MacOS (VSCode debugging)
**Command you ran:** `npm nodemon`
**Project nodemon.json:**
```json
{
  "watch": [
    "src",
    "~/some-folder-in-my-user-home-directory/a-file.ext"
  ],
  "exec": "some other command",
  "signal": "SIGTERM",
  "outputCapture": "all"
}
```

### Expected behaviour
Watch the folder/file(s) in the path that exists in my user directory.

### Actual behaviour
Nothing in that user directory path is watched.

### Steps to reproduce
Easily recreated based on what I provided above.

**Comment by mkormendy** [comment]
This also occurs on a Windows-style path as well: `$HOME\some-folder-in-my-user-home-directory\a-file.ext`

**Comment by remy** [comment]
@mkormendy you've gotta comment on the issue to get the stalebot to back off rather than drop an emoji. Equally it doesn't look like anyone, yourself included, picked this up. My comment (this text) will give the issue another 14 days grace.

**Comment by mkormendy** [comment]
Silly stale bot 🤣

**Comment by mkormendy** [comment]
Did this actually get fixed?

**Comment by auroraisluna** [comment]
Nope, if a folder has a tilde (~) nodemon will not look for changes there.

**Comment by mkormendy** [comment]
@auroraisluna that seems like quite a large oversight. There are a large number of users that commonly store projects and assets in common user folders that can be easily referenced in a path with (~).

**Comment by auroraisluna** [comment]
> @auroraisluna that seems like quite a large oversight. There are a large number of users that commonly store projects and assets in common user folders that can be easily referenced in a path with (~).

I have a folder structure as follows: 
```fix
C:/path/to/project/
     /folder1/
          /test.mjs
     /folder2/
         /anothertest.mjs
     /~/
         /tildetest.mjs
```

And whenever updating/saving the code inside `/~/tildetest.mjs` there is no update by nodemon, while a change to `test.mjs` or `anothertest.mjs` reloads just fine.

**Comment by mkormendy** [comment]
Tilde is often a reserved filesystem path character for user home folders.

**Comment by auroraisluna** [comment]
> Tilde is often a reserved filesystem path character for user home folders.

That is true, but that doesn't explain why nodemon does not refresh.
