### ISSUE TITLE
Feature Request: pause watching

### ISSUE THREAD

**Issue by wolflu05** [remy/nodemon#1836]
would it be possible to add a command (e.g. `ps`) to pause the watch mode and then I can make changes without having to pause the whole process? And then you can start the watch mode again with another command and reloads it directly.

**Comment by remy** [comment]
For comparison, if a pause/restore is implemented:

- switch to terminal
- type "ps"
- hit enter (now paused)
- return to terminal
- type "ps" (to unpause)
- hit enter

Keys presses for pause/restore: 6

The same effect with current workflow:

- switch to terminal
- ctrl+c (now paused)
- return to terminal
- cursor up once
- hit enter

Keys presses for pause/restore: 3

I don't think it makes sense to add functionality to do something the terminal does out of the box going by the comparison above.

**Comment by wolflu05** [comment]
I think it makes sense because I just want to stop watching and keep the process alive.

**Comment by wolflu05** [comment]
I think another point is that I start nodemon with concurrently. So if I hit Ctrl+C as suggested, the other processes will also be killed.
