### ISSUE TITLE
Feature Request: Flag to set environment variables on cli

### ISSUE THREAD

**Issue by cinderblock** [remy/nodemon#1838]
I've looked for if this exists and not found anything.

### Requested API Example

```bash
nodemon --env MY_VAR=asdf --exec something
```

I know there are *other* ways to achieve this, but I think this deserves a first class cli argument.

Is this something that would be accepted if a PR were made?

**Comment by remy** [comment]
Literally less characters to do it today *without* "first class" support:

```
MY_VAR=asdf nodemon --exec something
```

**Comment by cinderblock** [comment]
That does not work on Windows.

Your method is also incompatible with setting environment variables that `nodemon` itself listens to.

So, is this something that would be accepted if a PR were made?

**Comment by remy** [comment]
Why would nodemon listen to env values?

Also, why not use the config? *Another* way to set env values...

https://github.com/remy/nodemon#design-principles - this also guides the necessity for new features, and since env values are already possible it really doesn't warrant a new feature.

**Comment by cinderblock** [comment]
> Why would nodemon listen to env values?

That's your department, I believe. https://github.com/remy/nodemon/search?q=process.env&type=code

> Also, why not use the config? _Another_ way to set env values...

Because I use that config for other things. Specifically, I use `nodemon`  a lot in my projects. A (default) config file is for cli users that want to type a short command and have a bunch of settings be automatically set. In a script, where I type it once ever, I'd rather set the explicit flags I want at the invocation. Yes, I could have dedicated config files for each scripted usage of `nodemon` that is different but that would clutter my project's file tree.

> https://github.com/remy/nodemon#design-principles - this also guides the necessity for new features, and since env values are already possible it really doesn't warrant a new feature.

Forgive my persistence but, by that logic, why even have cli arguments besides `--config`?

I'm voicing my opinion that I think a cli flag for setting environment variables would be valuable and not significantly confusing. I'm curious if others agree.

Of course, this is your project. Do what you will.

**Comment by caesay** [comment]
The proposition usually used (ex `MY_VAR=asdf nodemon ...`) does not work on windows, however usually `cross-env` is used in this case: 

> cross-env MY_VAR=asdf nodemon --exec something

**Comment by remy** [comment]
@caesay this is a good candidate for the FAQ - I'm definitely a fan of leveraging existing tools that make the work easier 👍
