### ISSUE TITLE
configure NODE_ENV variable when starting node server

### ISSUE THREAD

**Issue by rolandjitsu** [remy/nodemon#184]
I've been looking for some ways to set <code>NODE_ENV=development</code> before starting node server, something like <code>NODE_ENV=development node server.js</code>, with nodemon, but I have failed in doing such.

I couldn't find a clear way of doing it and I would like to use nodemon and be able to do so as it integrates pretty good with grunt watch and concurrent.

If there isn't already a way to do it, would it be possible to add this feature ?

**Comment by VanHumbeeckA** [comment]
@chintanp Problem with 
```
    set NODE_ENV=development && nodemon server.js
```
is that your `NODE_ENV` is now "development " (attention to the space in the end!!!)
I still haven't found a way to do this one-liner without the added space of your NODE_ENV variable..

**Comment by remy** [comment]
Doesn't

NODE_ENV=production nodemon

Work? I'm using this for other variables and I changed the code many months
ago to suck through the env values.

**Comment by VanHumbeeckA** [comment]
@remy Sure, that would work, but not on windows :)

**Comment by remy** [comment]
Is anyone else having this problem on windows, and actually is this issue
isolated to windows?

**Comment by David-99** [comment]
It's definitely isolated to windows, thought I was hitting the same problem. But t'was due to me being a touch of a n00b in node. Fixed my problem and then ran 

'$ NODE_ENV=development ./node_modules/nodemon/bin/nodemon.js ./src/server/app.js'

or when run from an npm  task:
'$ NODE_ENV=development nodemon ./src/server/app.js'
 
on both my mac and Linux machines.  - no problems. I'll agree that 2 unique nodes is a small sample size to conclude that this could only be a windows problem.  But I thought that might help.

**Comment by brugnara** [comment]
@VanHumbeeckA I owe you a beer. You saved my day with the &&-with-spaces-before trick. Thanks!

**Comment by siddo420** [comment]
I have a slightly different problem. 

I have this NODE_ENV var configured in nodemon.json and because of that nodemon does not respect the NODE_ENV value provided on command line.

I think command line value should take precedence over config file.

**Comment by ummahusla** [comment]
@VanHumbeeckA Thank you!

**Comment by Noor0** [comment]
how can i set the `process.env.PORT` while starting node server

**Comment by vanhumbeecka** [comment]
@Noor0 same as the other example.
Meanwhile, I've found a npm package which makes it easier to write npm scripts for both linux based systems and windows. You can install it with ```npm install --save-dev cross-env```.

When you have the ```cross-env``` package, you can write your npm scripts like so
```
cross-env PORT=3000 NODE_ENV=development node server/index.js
```
This will work on all Linux systems, Mac and Windows.

**Comment by kuncevic** [comment]
In case of vscode you can do just this in `launch.json` `"configurations"`:
```
"env": {
    "NODE_ENV": "test"
}
```

**Comment by AbdelrahmanHafez** [comment]
There's an issue with using `set NODE_ENV=DEV&& nodemon app.js` on windows, and that is it sets the NODE_ENV variable globally to DEV.

Correct me if I am wrong, but I expected something like `node NODE_ENV=DEV app.js` would work on the process only.

If not, is there any way I can achieve this without setting the variable globally? Like on this process only.

**Comment by remy** [comment]
@AbdelrahmanHafez no, that second example wouldn't work in Windows at all. On Windows, IIRC, you set the environment variable for the single session, but it does affect the lifetime of the session (so not really "global"). Otherwise, you'll want to do some reading around Windows handling of environment variables (I suspect this thread is a bit off topic for what you're after)

**Comment by AbdelrahmanHafez** [comment]
Thank you, will read some about the subject.

**Comment by him666** [comment]
maybe someone can benefit of my experience later, what i used for OSX and Windows, i mainly do yarn electron-dev for  OSX and yarn electron-windev for Windows 10 64 bits
`"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "electron-dev": "concurrently \"BROWSER=none yarn start\" \"wait-on http://localhost:3000 && electron .\"",
    "electron-windev": "concurrently \"set BROWSER=none&& yarn start\" \"wait-on http://localhost:3000 && electron .\""
  },`

**Comment by kristinn93** [comment]
None of the above solutions worked for me
I was trying to pass `SSR`, `NODE_ENV` and `TIER` to `node dist/server.js`
```bash
# package.json script
"SSR=true NODE_ENV=dev TIER=staging nodemon dist/server.js"
```

After changing to this it works fine
```bash
# package.json script
"nodemon --exec 'SSR=true NODE_ENV=dev TIER=staging node dist/server.js' dist/server.js"
```

**Comment by DEVAbhinav** [comment]
Do we have feature of setting `NODE_ENV=staging nodemon app.js` environment variable now?

**Comment by mijatovicmile** [comment]
This solution worked for me on Window OS:

in `package.json` file 
```
"scripts": {
    "dev": "set NODE_ENV=development&& nodemon app.js",
    "prod": "set NODE_ENV=production&& nodemon app.js"
  },
```

and then `npm run dev` or `npm run prod` depending on which environment you want to start 

Result is: 
```
[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
The server is up and running on port 5000 in production mode.
The server is up and running on port 5001 in production mode.
```
or 
```
[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
The server is up and running on port 3000 in development mode.
The server is up and running on port 3001 in development mode.
```

If I run `npm dev` or `npm prod` **without** `run`, I got this error 

```
Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, doctor, edit,
    explore, get, help, help-search, i, init, install,
    install-test, it, link, list, ln, login, logout, ls,
    outdated, owner, pack, ping, prefix, profile, prune,
    publish, rb, rebuild, repo, restart, root, run, run-script,
    s, se, search, set, shrinkwrap, star, stars, start, stop, t,
    team, test, token, tst, un, uninstall, unpublish, unstar,
    up, update, v, version, view, whoami

npm <command> -h     quick help on <command>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Mile\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@5.6.0 C:\Program Files\nodejs\node_modules\npm

```


My environment `config.js` 

```
/**
 * Create and export environment configuration with https support
 * 
 * Staging environment
 * Production envirorment
 */

// Container for all environments
var environments = {};

// Development (default) environment
environments.development = {
  'httpPort': 3000,
  'httpsPort': 3001,
  'envName' : 'development'
};

// Production environment
environments.production = {
  'httpPort': 5000,
  'httpsPort': 5001,
  'envName' : 'production'
};

// Determine which environment was passed as a command-line argument
var currentEnvironment = typeof(process.env.NODE_ENV) == 'string' ? process.env.NODE_ENV.toLowerCase() : '';

// Check that the current environment is one of the environments above, if not default to staging
var environmentToExport = typeof(environments[currentEnvironment]) == 'object' ? environments[currentEnvironment] : environments.staging;

// Export the module
module.exports = environmentToExport;

```

**Comment by bkarakashev** [comment]
> Is anyone else having this problem on windows, and actually is this issue
> isolated to windows?
> On 1 Apr 2015 13:59, "VanHumbeeckA" [notifications@github.com](mailto:notifications@github.com) wrote:
> 
> > @remy https://github.com/remy Sure, that would work, but not on windows
> > :)
> > —
> > Reply to this email directly or view it on GitHub
> > [#184 (comment)](https://github.com/remy/nodemon/issues/184#issuecomment-88469746).

Yes I am also having this issue on Windows

**Comment by bkarakashev** [comment]
> &&

What if you have multiple ENVs like ``` set ENV set SOMETHING_ELSE&& nodemon``` 
is that how should I do it?

**Comment by chovy** [comment]
`NODE_ENV=development npx nodemon index.js` isn't picking up the environment variable.

**Comment by FreddyJD** [comment]
> `NODE_ENV=development npx nodemon index.js` isn't picking up the environment variable.

Just try exporting your environments 

```
export NODE_ENV=development
```

Or if you are in windows you could try this:
```
SET NODE_ENV=development
```

**Comment by Emediongabara** [comment]
[nodemon] starting `if [[ $NODE_ENV == 'production' ]]; then node ./bin/www; else nodemon ./bin/www; fi`
$NODE_ENV was unexpected at this time.
[nodemon] app crashed - waiting for file changes before starting...HOW CAN I RESOLVE THIS  ISSUE

**Comment by MansurAliKoroglu** [comment]
For windows,

@bkarakashev Yes I can use more than one like:
`SET AB=CD&& SET EF=GH&& nodemon nodemon ./bin/www`

Also if anyone want to use reserved characters, just write environment variables in double quotes.

```
"scripts": {
    "start": "SET \"DATABASE_URL=postgres://user:password@localhost:3205/DBNAME\"&& nodemon ./bin/www"
  },
```

**Comment by ackvf** [comment]
`nodemon.json`
```
{
  "env": {
    "NODE_ENV": "development"
  }
}
```

**Comment by chsrinu** [comment]
Typically the options to control nodemon are passed in via the CLI and are
  listed under: nodemon --help options

  nodemon can also be configured via a local and global config file:

  * $HOME/nodemon.json
  * $PWD/nodemon.json OR --config <file>
  * nodemonConfig in package.json
  
  referred from nodemon/doc/cli/help.txt

**Comment by mirzaumersaleem** [comment]
> @chintanp Problem with
> 
> ```
>     set NODE_ENV=development && nodemon server.js
> ```
> 
> is that your `NODE_ENV` is now "development " (attention to the space in the end!!!)
> Just don't add the space after the NODE_ENV variable, just straight to &&:
> 
> ```
>     set NODE_ENV=development&& nodemon server.js
> ```

Thanks

**Comment by bradenmitchell** [comment]
Using `NODE_ENV=development nodemon src/index.js` does not work for me on macOS (Catalina 11.4) and Node v14.
How come other macOS users are saying this works?
