### ISSUE TITLE
Stop running nodemon programmatically

### ISSUE THREAD

**Issue by lioaslan** [remy/nodemon#1842]
- `nodemon -v`: 1.19.3
- `node -v`: 12.20.2
- Operating system/terminal environment: Ubuntu 18.04
- Using Docker? What image: 
- Command you ran: `nodemon index.js`

### Expected behaviour
Stop running

### Actual behaviour
Nodemon restart
![image](https://user-images.githubusercontent.com/24852182/108817147-07e24b00-75ea-11eb-8ce6-c2e965d95ad7.png)

### Steps to reproduce
- Create file `index.js`
```javascript
"use strict";

const readline = require("readline");

const rl = readline.createInterface({
  input: process.stdin, // or fileStream
  output: process.stdout,
});

const BASE_HOST = "127.0.0.1";

const deployment = async (start) => {
  if (!process.env.ENV_MACHINE && process.env.PG_HOST !== BASE_HOST) {
    console.log(
      "\x1b[36m%s\x1b[0m",
      `You're connecting to a different database. Do you want to continue (yes/no)? `
    );
    for await (const line of rl) {
      if (line === "yes") {
        console.log("Server will start now...");
        break;
      }
      if (line === "no") {
       /* process.once("SIGUSR2", function () {
          gracefulShutdown(function () {
            process.kill(process.pid, "SIGUSR2");
          });
        });  */
        return;
      }

      console.log(`Answer should be 'yes' or 'no'`);
    }
  }
};

deployment();
```
- Install nodemon
- run `nodemon index.js`
- Type 'no' -> enter

I tried to kill `SIGUSR2` following the document but it still didn't work. I wonder `gracefulShutdown` function need to be imported or not.

**Comment by remy** [comment]
If you want to control nodemon then your code has to spawn nodemon. This can be done by requiring it and using the events to control.

Otherwise this particular functionality is out of scope as the sub process (yours) can't control the main process.
