### ISSUE TITLE
Nodemon detects change but doesn't restart

### ISSUE THREAD

**Issue by Jarco-dev** [remy/nodemon#1844]
- `nodemon -v`: 2.0.7
- `node -v`: v14.16.0
- Operating system/terminal environment: Windows 10
- Using Docker? What image: 
- Command you ran: nodemon

### Expected behaviour
index.js is restarted when saving the file

### Actual behaviour
PS C:\Users\light\OneDrive\Bureaublad\testing> nodemon
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js`
Running for 1s
Running for 2s
[nodemon] restarting due to changes...
Running for 3s
Running for 4s

### Steps to reproduce

---

Index.js
```js
let runTime = 0;

setInterval(() => {
    runTime++
    console.log(`Running for ${runTime}s`);
}, 1000);
```

package.json
```json
{
  "name": "testing",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "nodemon": "^2.0.7"
  }
}
```

run command: `nodemon`

**Comment by emanual4real** [comment]
I am also having issues.  It stopped working on a couple of my express.js APIs.  Only thing i did was update nodemon.  Tried installing some older versions and couldn't get it working again.

`node -v v14.15.3`
`nodemon -v 2.0.7`
`  "scripts": {
    "start:dev": "nodemon ."
}`

**Comment by emanual4real** [comment]
I'm trying different versions with same results which makes me think maybe something environmental but I'm at a loss.  In this example I started with a `console.log` then I deleted it and after restart the `console.log` still appeared.
![image](https://user-images.githubusercontent.com/7506967/109665344-0e1d7d80-7b3c-11eb-95aa-6431c6c62c05.png)

**Comment by emanual4real** [comment]
Here's a different environment I haven't touched in quite some time.  Same app, appears to work.  
![image](https://user-images.githubusercontent.com/7506967/109670927-9d795f80-7b41-11eb-832c-45090a335f61.png)

**Comment by emanual4real** [comment]
Appears to be working after upgrading node to 14.16.x

![image](https://user-images.githubusercontent.com/7506967/109678404-9570ee00-7b48-11eb-8097-c586ed132c7a.png)

**Comment by Jarco-dev** [comment]
It has magicly started working for me again and haven't really had issues since but I've heared / seen multiple people having this random thing so i feel like this might still be a issue to keep in mind if not feel free to close it
