### ISSUE TITLE
Nodemon Increased CPU and Memory usage

### ISSUE THREAD

**Issue by skyfyx** [remy/nodemon#1845]
- `nodemon -v`: 2.0.7
- `node -v`: 15.11.0
- Operating system/terminal environment: Windows 10 X64
- Command you ran: npm run start ( nodemon server.js )

Hi I have just installed nodeJs, ExpressJS (v: 4.17.1) and Nodemon. But when i launch my project with this command "npm run start" (  link to "nodemon server.js" ). I can see my server nodeJS use more and more my cpu and my "Ram" until crash with "heap out of memory". 
When I launch the nodeJs server without Nodemon I don't have this problem ( it takes 10Mo of Ram)

Thanks for your help

Ps: sorry for my poor english..

**Comment by inieves** [comment]
I am seeing the same issue.  Any solutions or fixes?
