### ISSUE TITLE
nodemon is leaving one node instance running when it exits?

### ISSUE THREAD

**Issue by tciuro** [remy/nodemon#185]
Hi Remy,

I launch nodemon like this:

```
Mac:webserv tito$ nodemon app.js 
15 Jun 13:05:08 - [nodemon] v0.7.8
15 Jun 13:05:08 - [nodemon] to restart at any time, enter `rs`
15 Jun 13:05:08 - [nodemon] watching: /Users/tito/Desktop/Tests/webserv
15 Jun 13:05:08 - [nodemon] starting `node app.js`
Express server listening on port 8080 in development mode
```

I can see two instances of node showing up in Activity Monitor (Mac OS X). If I terminate nodemon via Control-C, one instance is left behind. When I fire nodemon again I get the following:

```
Mac:webserv tito$ nodemon app.js 
15 Jun 13:07:10 - [nodemon] v0.7.8
15 Jun 13:07:10 - [nodemon] to restart at any time, enter `rs`
15 Jun 13:07:10 - [nodemon] watching: /Users/tito/Desktop/Tests/webserv
15 Jun 13:07:10 - [nodemon] starting `node app.js`
Caught exception: Error: listen EADDRINUSE
```

Is this expected? Is there anything I can do to make sure nodemon kills the two processes it created when it launched?

Thanks!

**Comment by andyfleming** [comment]
I'm experiencing something similar to @bjmiller on OS X.

**Comment by kobenauf** [comment]
Same here, WIndows 10 running from cygwin.  I noticed if I do run from a cmd window instead it functions correctly, but it would be much preferable for me to run from cygwin.

**Comment by vizo** [comment]
Same here on Linux Ubuntu 16.04 in cluster mode

**Comment by ericsoco** [comment]
I'm seeing the same on OSX, just started recently and don't have a clear repro.`ctrl+c` to kill the process, but sometimes it's lingering in the background. Specifically, I'm watching files and when I change them via other scripts, all of a sudden my rebuild process kicks off because the `nodemon` background process sees the changes. Took me a bit to understand what was happening, though I'm still not clear on why.

**Comment by killroy42** [comment]
I've experienced this for a while. Sometimes I end up with 10-20 node.exe and cmd.exe processes in my process list that I have to kill manually.

**Comment by petr001** [comment]
the same issue here 🙁

**Comment by theninj4** [comment]
I can reliably reproduce this:

First up, in the code we're monitoring, bind to a TCP port, and bind to the SIGUSR2 signal:
```javascript
process.on('SIGUSR2', () => { })
```

Second, create a `.nodemon` file to use a different process signal (we're using SIGUSR2):
```
{
  "signal": "SIGHUP"
}
```

Third, start nodemon and kick it into the background:
```
nodemon --config ./nodemon.json --watch . server.js &
```

From this point, here's the process tree:
```
$ ps
PID   USER     TIME   COMMAND
    1 root       0:00 sh
    6 root       0:00 node /usr/bin/nodemon --config ./nodemon.json --watch . serv
   20 root       0:00 sh -c node server.js
   21 root       0:00 node server.js
```

Modify a file, let nodemon restart things, you'll get an error about trying to bind to TCP we're using, the new process will die and it'll sit waiting for changes before it brings up another process.

Viewing the process tree at this point shows we successfully killed PID 20, but it didn't propagate to PID 21, which is our NodeJS process:
```
$ ps
PID   USER     TIME   COMMAND
    1 root       0:00 sh
    6 root       0:00 node /usr/bin/nodemon --config ./nodemon.json --watch . serv
   21 root       0:00 node server.js
```

I'm guessing there are some edge cases whereby nodemon deviates from the `.nodemon` config?

**Comment by theninj4** [comment]
I found my issue above - my container didn't contain the `nodemon.json` config file. Adding the file to the container fixed the issue.

**Comment by Ankiewicz** [comment]
how do you kill nodemon when it wont shut off?

**Comment by eduardrock** [comment]
Same here. When I Ctrl+C or get an error on node, it leaves a process running when it's stopped on console. So I have to kill it manually every time.

**Comment by juan-carlos-correa** [comment]
How can we resolve this issue?

**Comment by andyfleming** [comment]
Here's my workaround:

**Setup**

```bash
npm uninstall -g nodemon
npm install -g pm2
```

**Workflow**

```bash
pm2 start --watch . --name=my-process index.js
pm2 logs my-process
```

----

Works great. Problem solved.

**Comment by juan-carlos-correa** [comment]
@andyfleming  thanks! that's nice option (y)

**Comment by DiegoRBaquero** [comment]
I can't believe this is still not fixed.

**Comment by remy** [comment]
@DiegoRBaquero happy to look at tests and a PR to merge if you can point me in its direction.

**Comment by heisian** [comment]
Yeah i'm not sure what the issue is here, when you fork a child process from just a bare node script and you kill the parent, node automatically kills the child gracefully. Something else is amiss here...

**Comment by heisian** [comment]
@remy Glancing at the code (and literally a 5-second glance) I see you have `spawn.js` and call `child_process.spawn`.

This is the only way for non-node executables but when running specifically a node child process, `fork` should be used. You get the benefits of IPC as well as automatic garbage collection when the parent dies.

I would suggest having a switch to use `child_process.fork` whenever a `.js` file is being run, or when the executable is `node`.

**Comment by heisian** [comment]
@remy here's my PR to fix the issue:
https://github.com/remy/nodemon/pull/1134

I'm guessing you'll edit it to be more consistent with the rest of the script but the concept is there, and I no longer get an `Error [ERR_IPC_CHANNEL_CLOSED]: channel closed` when the parent process dies.

**Comment by remy** [comment]
@heisian I need to revert this change for nodemon@1.x but it'll go in as part of nodemon@2.0.0 - because it doesn't work with node@4 (in `tests/config/env.js`), but I'm dropping support for node@4 in nodemon@2 (I accidentally did it in 1.12.3 but it _should_ have been a major bump).

**Comment by remy** [comment]
All live in latest nodemon (in nodemon@1.x - I pushed a workaround for node@4 which uses spawn).

**Comment by heisian** [comment]
@remy Okay. Looking at the `child_process.fork` history, the `stdio` option was only introduce in `v6.4.0`, so that may be the reason.

**Comment by angularturk** [comment]
Also command below works fine;

pm2 start npm --watch --name=myapp -- start

**Comment by heisian** [comment]
@angularturk that's a completely different module and doesn't provide any utility to this thread.
