### ISSUE TITLE
QUESTION | Preload node module with nodemon

### ISSUE THREAD

**Issue by lat94** [remy/nodemon#1851]
Is it possible to preload a node module in `nodemon` the same way it can be done using `node`?
Let's say I'm within `package.json`, inside `scripts` object, and I want to run my script, preloading  `dotenv` I'd use `-r`(short for require) :
```json
scripts: {
    "dev":" node -r dotenv/config your_script.js dotenv_config_path=/custom/path/to/your/env/vars"
}
```

How can it be done in `nodemon`? 
If it's not possible, I think it would become a great new feature.

**Comment by remy** [comment]
`nodemon -r dotenv/config your_script.js …` 👈  like that
