### ISSUE TITLE
Feature Request: javascript configuration file rather than json file

### ISSUE THREAD

**Issue by tommy-lettieri** [remy/nodemon#1852]
- `nodemon -v`: 2.0.6
- `node -v`:  v14.15.3
- Operating system/terminal environment: Lubuntu / bash
- Using Docker? What image: NA
- Command you ran: nodemon ./src/index.ts

Instead of using a static json file it would be nice to be able to use a javascript file. This would allow for comments and dynamic configurations. The dynamic configuration would also let you build upon configurations if for example, you want to have a base nodemon config and then a second one that just cleared the console on restart.

In my case I have a small playground in the codebase that I sometimes use to script in some data to test with. It uses all the same code and isn't really a module case. What I would like is:
1. The server only restarts when the main source is touched (by using "ignore" on the playground directory)
2. The playground restarts when any of the source changes

To accomplish this I would like a base nodemon config, let's call it `.nodemonrc.js` that includes all shared configurations (shared ignores, typescript configs, etc)
Then I would like to have a second file `playground.nodemonrc.js` that requires nodemonrc, and returns a modified version of the original which would be used by the playground

I built a test to exemplify my case:
[nodemon_test.zip](https://github.com/remy/nodemon/files/6394985/nodemon_test.zip)
`npm start` uses a normal nodemon.json file and works
`npm run start:desired` tries to use a js file that is built off of a second js file and results in an error (since it is trying to parse json)
```
[nodemon] Failed to parse config /home/luigi/workspace/nodemon_test/clear.nodemonrc.js
SyntaxError: Unexpected token c in JSON at position 0
    at JSON.parse (<anonymous>)
    at /home/luigi/workspace/nodemon_test/node_modules/nodemon/lib/config/load.js:208:23
```

**Comment by red-tt-bear** [comment]
I only took a quick look, but couldn't you just replace the json parsing here with a require statement?
https://github.com/remy/nodemon/blob/d33f5f449f678c5481e1e9d5cec59aa679802b25/lib/config/load.js#L193

I've seen other libraries like eslint and sequelize allow a js file or a json file

**Comment by mattalexx** [comment]
Wish I'd seen it sooner, I agree. Not sure why there would be a problem with adding this feature...
