### ISSUE TITLE
nodemon SecurityError

### ISSUE THREAD

**Issue by Hasintha-git** [remy/nodemon#1856]
nodemon vershion - 2.0.7

nodemon : File C:\Users\Hasintha\AppData\Roaming\npm\nodemon.ps1 cannot be loaded because running scripts is disabled on this system. For more information,   
see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ ~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by remy** [comment]
I guess you'll need to give it access. This isn't a nodemon thing but a windows security thing. I'd start with the link that was given to you in the error.
