### ISSUE TITLE
bash: nodemon: command not found

### ISSUE THREAD

**Issue by Kevin-Aaaquil** [remy/nodemon#1857]
Recently I updated from node 15 to node 16.2.0, before running my code i ran a 
```
rm -rf node_modules package-lock.json && npm install
```
but even after that i am getting a 
```
bash: nodemon: command not found
```
I use git bash for my terminal and my nodemon version is 2.0.7
![Screenshot 2021-05-31 220051](https://user-images.githubusercontent.com/73784677/120221292-c7831080-c25b-11eb-852a-7a1933e2aa79.png)

**Comment by remy** [comment]
Since you installed nodemon locally, you'll need `npx nodemon`, or to install it globally using `npm i -g nodemon`
