### ISSUE TITLE
Unable to install Nodemon

### ISSUE THREAD

**Issue by Marcell-BTS** [remy/nodemon#1859]
As i type "npm install nodemon" i get this error.

npm ERR! 403 403 Forbidden - GET https://registry.npmjs.org/anymatch/-/anymatch-3.1.2.tgz
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.
npm ERR! 403
npm ERR! 403 It was specified as a dependency of 'chokidar'
npm ERR! 403

npm ERR! A complete log of this run can be found in: (File.log)

![ErroNodemon](https://user-images.githubusercontent.com/74062806/120472962-e62cf880-c37c-11eb-8ffc-0a43bf19ea2e.png)

File.log:
[2021-06-02T11_27_39_224Z-debug.log](https://github.com/remy/nodemon/files/6584108/2021-06-02T11_27_39_224Z-debug.log)

Anyone may know why is it happening?

**Comment by remy** [comment]
> In most cases, you or one of your dependencies are requesting a package version that is forbidden by your security policy.

☝️ that?

You should try to access the URL (you pasted) directly, I suspect you'll see a 403 forbidden. This means your network set up is blocking it (and indeed nothing related to nodemon).
