### ISSUE TITLE
Does not wait for child process termination when using node's "--inspect" option

### ISSUE THREAD

**Issue by Wesitos** [remy/nodemon#1861]
- `nodemon -v`: 2.0.7
- `node -v`: 14.17.2
- Operating system/terminal environment: Ubuntu
- Command you ran: `nodemon --inspect=9223 index.js`

### Expected behaviour
Nodemon should wait for the child process termination before starting a new process.

### Actual behaviour
When using node's "--inspect" option, Nodemon does not wait for the process termination before starting a new process.

### Steps to reproduce
Run `nodemon --inspect index.js` and trigger a restart
Contents of index.js

```js
console.log('Started:', process.pid);

process.on('SIGUSR2', () => {
  // Delay process termination
  setTimeout(() => {
    console.log('Shutting down:', process.pid);
    process.exit(0);
  }, 100);
});

// This is only to keep the process alive
setTimeout(() => {}, 100000);
```

![image](https://user-images.githubusercontent.com/651048/120876240-48504e00-c575-11eb-9e5c-58d9d6cb36a3.png)

It works fine when the "--inspect" option is not used
![image](https://user-images.githubusercontent.com/651048/120876190-ea236b00-c574-11eb-8af6-6f32b76e6266.png)

**Comment by Wesitos** [comment]
It also happens when "spawn" is forced. (`nodemon --spawn index.js`).

**Comment by Wesitos** [comment]
I looks that the delayed termination in the "grandchild" (the node process) does not delay the termination of the `sh` process (the "child" process) which is what nodemon uses to determinate when **all the child processed** have terminated.

**Comment by cbix** [comment]
Probably #1050 and #1346 related, which unfortunately have never really been fixed ;)

**Comment by remy** [comment]
Not for anyone who actually wants to try to fix this - this is a linux specific bug - doesn't happen on macos.

Could be related to how node's debugger releases the sub process.

**Comment by Wesitos** [comment]
I think it's because sh does not propagates signals to a _blocking_ child processes (https://unix.stackexchange.com/a/196053) at least in linux, I have no way of testing this on macos. And the way nodemon runs a process (using "spawn") outside windows is running `sh -c`. I think this could be fixed by spawning the child process in a bit more complex sh script (with proper signal handling).

**Comment by jkirkham-ratehub** [comment]
As @Wesitos mentioned, most shells on *nix platforms do not pass on signals.
Why is nodemon using an intermediary `sh` process when spawning a child process?  (Sorry, I haven't read through past issues yet to see if there is a valid reason/requirement for this.)
I think the fix may be to spawn the process directly without an intermediate `sh` process.

This is also relevant for running in Docker containers.  For security reasons you want to minimize the footprint of your containers so having an otherwise unneeded requirement on `sh` doesn't make sense.
