### ISSUE TITLE
UI enhancement In dark mode, description box as well as text color both are white

### ISSUE THREAD

**Issue by alishahzil** [remy/nodemon#1862]
In dark mode when we write a description and select the description box both text and box background color change into white which makes it difficult to see
 
![Screenshot 2021-06-05 121349 - Copy](https://user-images.githubusercontent.com/52203884/120883824-d7eb1080-c5f8-11eb-9e5d-64285ac3b137.png)

**Comment by remy** [comment]
Wrong repo ☺️
