### ISSUE TITLE
Audit error High

### ISSUE THREAD

**Issue by timbielawski-equine** [remy/nodemon#1864]
There is an audit error with normalize-url a dependency of update-notifier

Can you please update update-notifier

thanks

**Comment by remy** [comment]
I don't know what an audit error is. But if you're referring to vulns, there's not. You need to update your own deps: https://snyk.io/test/npm/nodemon

**Comment by timbielawski-equine** [comment]
I get this path - update-notifier have updated their deps? 


 │ Path          │ nodemon > update-notifier > latest-version > package-json >  │
│               │ got > cacheable-request > normalize-url    


# Run  npm update normalize-url --depth 7  to resolve 1 vulnerability
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ normalize-url                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nodemon [dev]                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nodemon > update-notifier > latest-version > package-json >  │
│               │ got > cacheable-request > normalize-url                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1755                            │
└───────────────┴──────────────────────────────────────────────────────────────┘

**Comment by remy** [comment]
You've not included the versions so I can't tell you what you're looking at.

`npm ls normalize-url` will give you the version. 

<img width="670" alt="Screenshot 2021-06-10 at 08 58 35" src="https://user-images.githubusercontent.com/13700/121487497-0cc8e000-c9ca-11eb-96b5-366a43b54a00.png">

I refer you to my original comment though.

**Comment by timbielawski-equine** [comment]
Thanks for your help -- I appreciate it

└─┬ nodemon@2.0.7
  └─┬ update-notifier@4.1.3
    └─┬ latest-version@5.1.0
      └─┬ package-json@6.5.0
        └─┬ got@9.6.0
          └─┬ cacheable-request@6.1.0
            └── normalize-url@4.5.0

**Comment by timbielawski-equine** [comment]
I killed node_modules and re installed - fixed

Thank you for your help

└─┬ nodemon@2.0.7
  └─┬ update-notifier@4.1.3
    └─┬ latest-version@5.1.0
      └─┬ package-json@6.5.0
        └─┬ got@9.6.0
          └─┬ cacheable-request@6.1.0
            └── normalize-url@4.5.1
