### ISSUE TITLE
Nodemon is not detecting file changes in WSL2 Windows environment 

### ISSUE THREAD

**Issue by chriswoodle** [remy/nodemon#1866]
May be related to #1802

- `nodemon -v`: 2.0.7
- `node -v`:  v12.16.1
- Operating system/terminal environment: 
WSL2 Debian, Windows Terminal
```
Edition	Windows 10 Pro
Version	20H2
Installed on	‎6/‎2/‎2020
OS build	19042.1052
Experience	Windows Feature Experience Pack 120.2212.2020.0
```
- Command you ran: `nodemon index.js`

### Expected behaviour
When saving a file, nodemon should restart the application. 

![image](https://user-images.githubusercontent.com/11614325/122490077-1d232100-cfaf-11eb-92d1-0d6c66964f63.png)

### Actual behaviour
When running from a WSL2 terminal (Debian), nodemon does not detect the file changes. I've tested in both the Windows Terminal and the integrated VSCode terminal. 
![image](https://user-images.githubusercontent.com/11614325/122490061-109ec880-cfaf-11eb-973b-53edf338ced2.png)

### Steps to reproduce

I have created a sample Express app here: https://github.com/chriswoodle/nodemon-1567 that shuts down the express server once the application is signaled to stop.

```
git clone https://github.com/chriswoodle/nodemon-1567.git
cd nodemon-1567
npm install
npm start
touch index.js
```

I'm guessing that this is probably a [chokidar](https://github.com/paulmillr/chokidar) issue, similar to #1802, but I'm not really sure how to investigate.

**Comment by remy** [comment]
Can you try with nodemon@latest and if that errors can you try with nodemon@debug?

**Comment by chriswoodle** [comment]
> 
> 
> Can you try with nodemon@latest and if that errors can you try with nodemon@debug?

I've tried both with same result, the process just does not restart in WSL. Regular windows CMD/Powershell are fine.
