### ISSUE TITLE
process kill not caught when running nodemon

### ISSUE THREAD

**Issue by SinanAkkoyun** [remy/nodemon#1869]
- `nodemon -v`: lts
- `node -v`: lts
- Operating system/terminal environment:  Windows 10 / VSC / Windows Console
- Using Docker? What image: /
- Command you ran: nodemon --watch src --no-stdin src/index.js

### Expected behaviour
Hit CTRL C and expect the catch below to work
Discord bot should send message that it stopped (it does without running nodemon and hitting CTRL C

### Actual behaviour
Discord bot sometimes (rarely) makes it to the end of sending message before nodemon stops

### Steps to reproduce
```js
['SIGHUP', 'SIGINT', 'SIGQUIT', 'SIGILL', 'SIGTRAP', 'SIGABRT',
 'SIGBUS', 'SIGFPE', 'SIGUSR1', 'SIGSEGV', 'SIGUSR2', 'SIGTERM'
].forEach(function(element, index, array) {
    process.on(element, async function() { await shutdown(); });
})

async function shutdown() {
    await botManager.stop()
//there is a discord bot send message inside stop
    process.exit(1)
}
```

---

**Comment by remy** [comment]
Try nodemon@debug - it's merged but not live until I can sort out the release issue.

**Comment by remy** [comment]
Unless I hear otherwise, I'll assume fixed with the latest release: nodemon@2.0.9

**Comment by RA80533** [comment]
@remy, it doesn't appear that anything related to asynchrony was changed in the latest release. Did you intend to push code to the branch prior to its release that contained fixes relating to this?

**Comment by remy** [comment]
@RA80533 the .9 release ships with a windows program called `windows-kill.exe` that is used to stop processes "properly" in windows. However, there is an open issue that you might find affecting (potential stacktrace showing?).
