### ISSUE TITLE
[feature request] add `--no-spawn` to force forking method

### ISSUE THREAD

**Issue by pincman** [remy/nodemon#1871]
use fork execute `ts`,is work fine,but should add some args
 **execa.node is some to fork**
```typescript
 execa.node(`./src/main.ts`, undefined, {
            stdio: 'inherit',
            cwd: path.resolve(__dirname, '..', '..'),
            extendEnv: true,
            nodeOptions: execArgs,
        });
```
but nodemon , `fork` can not be used,just `spawn`
```typescript
 const runner = nodemon({
            script: 'src/main.ts',
            exec: 'node',
            ext: 'js,json,ts',
            watch: ['src'],
            ignore: ['.git', 'node_modules', 'dist', 'scripts'],
            nodeArgs: execArgs,
            // execMap: {
            //     ts: args.debug ? `${exec} --inspect=${args.debug_port}` : exec,
            // },
            env: {
                NODE_ENV: process.env.NODE_ENV ?? 'development',
            },
            cwd: path.resolve(__dirname, '..', '..'),
            spawn: false,
            verbose: true,
            // stdout: false,
        });
```
so,in subprocess runned by nodemon,I can use `process.send` method,it will be undefined
```typescript
// main.ts
console.log(typeof process.send);
```

finally, I found the problem where its in run.js

```javascript
const shouldFork =
    !config.options.spawn &&
    !inBinPath &&
    !(firstArg.indexOf('-') === 0) && // don't fork if there's a node exec arg
    firstArg !== 'inspect' && // don't fork it's `inspect` debugger
    executable === 'node' && // only fork if node
    utils.version.major > 4 // only fork if node version > 4
```
"**don't fork if there's a node exec arg**" , why?
 if execute ts,must require some module like `ts-node/register`,`tsconfig-paths/register` or `@swc/register`, why not fork?
`const execArgs = ['-r', '@swc/register', `-r`, 'module-alias/register'];`

**Comment by remy** [comment]
I'm not entirely sure I understand your use case (but I'm guessing it's linked to the other issue you've raised at least).

I can say that this logic has been battle tested pretty hard so there's a reason why each line is there (but I can't recall beyond the comments off the top of my head).

However, I'm not adverse to accepting a pull request that adds an inverted flag to complement the `--spawn` as `--no-spawn` which would force `shouldFork` to be `true` (needs to be added to the help `docs/cli/options.txt`).

**Comment by pincman** [comment]
@remy set `spawn: false` to force `shouldFork` to `true` in node is best solution😀

**Comment by remy** [comment]
Sure, sorry - I meant on the command line. Again, I suspect you're coming from it via the other issue you raised (which you're using nodemon programatically) - so your suggestion on the `spawn: false` in the config is definitely correct.

**Comment by pincman** [comment]
@remy 
currently I temporarily solved it by hack way
now,another question is how can I get the what subprocess sended like `process.on('message')`?
the follow code can't get it

```typescript
 runner.on('message', (msg) => {
            console.log(msg === 'started');
        });
```

main.ts
```typescript
if (process.send) process.send('started');
```
