### ISSUE TITLE
v2.0.8 [Windows 10] globally installed nodemon broken (looking for windows-kill.exe locally)

### ISSUE THREAD

**Issue by Ericarthurc** [remy/nodemon#1872]
With the new 'windows-kill' merge in version 2.0.8 it brakes globally installed nodemon restarts. It says it is looking for the windows-kill binary in the local node_modules folder, but obviously if I am running nodemon from a global install, it's package wont be in the local node_modules

 Here is the error I receive; and you can see I dont have nodemon installed locally on this project
<img width="1920" alt="nodemon2 0 8" src="https://user-images.githubusercontent.com/22304079/123841287-389dfe00-d8c4-11eb-92bc-70b7980b4b36.PNG">
<img width="1920" alt="nodemon2 0 8ver" src="https://user-images.githubusercontent.com/22304079/123841293-3b005800-d8c4-11eb-824e-1497a8ed16cf.PNG">

Here is the same project using nodemon 2.0.7; and the global nodemon works fine
<img width="1920" alt="nodemon2 0 7" src="https://user-images.githubusercontent.com/22304079/123841301-3c318500-d8c4-11eb-8184-ab3401f65269.PNG">

- `nodemon -v`: 2.0.8
- `node -v`: 16.4.0
- Operating system/terminal environment:  Windows 10
- Command you ran: nodemon src/main.ts

### Steps to reproduce
Install nodemon with `npm i -g npm@latest`, verify its version 2.0.8 with `nodemon -v` then run nodemon without a local project install

I want to clarify, that a local install within the project will work with v2.0.8; its just when you try to run it from a global only install

**Comment by remy** [comment]
cc'ing @countzero - looks like this is simple to replicate, would be good to solve this quickly - I might be able to work it out too myself…

**Comment by remy** [comment]
@Ericarthurc thanks for the clear explanation 👍

**Comment by unshDee** [comment]
Glad to see the issue's been raised here (didn't find anything related to it until I landed here). I had installed nodemon globally today, and faced the same problem whenever I updated my code.
- `nodemon -v`: 2.0.8
- `node -v`: 14.17.1

**Comment by remy** [comment]
For my own reference, this is the line in question: https://github.com/remy/nodemon/pull/1853/files#diff-5421faa69288694e0e190b2e6108ec30df01af1b84c6c2d68274f2a31596768eR350

Needs to be "smart".

**Comment by remy** [comment]
Can folks here try both local and global installs of nodemon@debug - I'm trying to get my local windows environment running so I can test it myself too.

**Comment by remy** [comment]
I'm 90% sure this is fixed in the debug build so I'm going to ship it.
