### ISSUE TITLE
nodemon 2.0.9 \node_modules\nodemon\bin\windows-kill.exe is not compatible with the version of Windows 8.1 32-bit

### ISSUE THREAD

**Issue by meganathan-codenatives** [remy/nodemon#1876]
This version of \node_modules\nodemon\bin\windows-kill.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
(node:4396) UnhandledPromiseRejectionWarning: Error: Command failed: start "windows-kill" /min /wait "\node_modules\nodemon\bin\windows-kill.exe" -SIGINT 3752
This version of \node_modules\nodemon\bin\windows-kill.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at kill (\node_modules\nodemon\lib\monitor\run.js:360:5)
    at Function.run.kill (\node_modules\nodemon\lib\monitor\run.js:425:7)
    at Bus.<anonymous> (\node_modules\nodemon\lib\monitor\run.js:495:7)
    at Bus.emit (events.js:327:22)
    at restartBus (\node_modules\nodemon\lib\monitor\watch.js:228:7)
    at FSWatcher.filterAndRestart (\node_modules\nodemon\lib\monitor\watch.js:212:16)
    at FSWatcher.emit (events.js:315:20)
    at FSWatcher.emitWithAll (\node_modules\chokidar\index.js:540:8)
(node:4396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection,
use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2

**Comment by remy** [comment]
Can you install `npm i -g nodemon@debug` and try with this version and let me know the outcome?

**Comment by meganathan-codenatives** [comment]
> Can you install `npm i -g nodemon@debug` and try with this version and let me know the outcome?

Yes, It's working now. Thanks

**Comment by aguspriyatin80** [comment]
Yes, it works. Thank you very much.

> Can you install `npm i -g nodemon@debug` and try with this version and let me know the outcome?

Yes, it works. Big thanks

**Comment by dineshyadav19** [comment]
> Can you install `npm i -g nodemon@debug` and try with this version and let me know the outcome?

Hello @remy. I have been scratching my head over this issue and finally, I came across this solution. Thank You.
