### ISSUE TITLE
nodemon with required module

### ISSUE THREAD

**Issue by niko-achilles** [remy/nodemon#1877]
- `nodemon -v`: 2.0.9
- `node -v`: 14, lts latest
- Operating system/terminal environment: Linux
- Using Docker? What image: node alpine
- Command you ran: nodemon
- In my package.json `scripts` is define as follows:
```
"scripts": {
    "dev": "nodemon",
    "lint": "eslint . --fix",
    "prestart": "npm run lint",
    "start": "node -r ./libs/useLibrary.js index.js"
  },
```

### Expected behaviour
nodemon shoulkd execute node -r ./libs/useLibrary.js index.js

### Actual behaviour
nodemon executes node index.js, but not the required module `useLibrary.js` as specifies in the start command : `node -r ./libs/useLibrary.js index.js`

### Steps to reproduce
define package.json
"scripts": {
    "dev": "nodemon",
    "lint": "eslint . --fix",
    "prestart": "npm run lint",
    "start": "node -r ./libs/useLibrary.js index.js"
  },
```
CMD : npm run dev


---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
It's because nodemon looks for an index file before moving on to looking at npm scripts. So in this case it finds the script and runs it and never moves on to the start script.

To work around this, add the explicit command to the dev script.

**Comment by niko-achilles** [comment]
@remy thank you so much for the fast reply. It worked like `"dev": "nodemon -r ./libs/useLibrary.js index.js"`
By the way before raising the issue , i have read the documentation of nodemon, but i did not find the execution priority of nodemon. 
E.g. as you described : `nodemon looks for an index file before moving on to looking at npm scripts`
