### ISSUE TITLE
ts-node not found with yarn 2 

### ISSUE THREAD

**Issue by H01001000** [remy/nodemon#1878]
- `nodemon -v`: 2.0.9
- `node -v`: v14.17.0
- Operating system/terminal environment: Windows 10 / powershell
- Using Docker? What image: No
- Command you ran: yarn run nodemon src/index.ts

### Expected behaviour
Able to run ts-node

### Actual behaviour
'ts-node' is not recognized as an internal or external command,
operable program or batch file.

### Steps to reproduce
Run nodemon with yarn 2 enviroment

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by H01001000** [comment]
I tried to change the ts-node command with yarn ts-node, It can run the first time, but it fails when restart, it stuck at `[nodemon] restarting due to changes...`

**Comment by remy** [comment]
Can you re-test by removing nodemon to ensure you can run as expected without it. Mostly because this sound like a yarn or a ts-node issue though.

**Comment by H01001000** [comment]
Yes, everything runs fine with using ts-node only `yarn ts-node file`.

**Comment by remy** [comment]
Please provide a pared down code example and as per the issue source text, assume I know nothing about typescript and yarn (I don't use either of these and I'm guessing I'll be the only one to attempt to find out what's wrong - so I'll need clear and simple steps to follow to replicate.).

**Comment by H01001000** [comment]
`npm install --global yarn`
init a project
`yarn init`
set yarn to version 2 (berry)
`yarn set version berry`

There is two installation strategy for yarn 2, keep using node_modules and [Plug'n'Play (PnP)](https://yarnpkg.com/features/pnp), which I found both didn't work, by default it uses Pnp.

For using node_modules
add a line in .yarnrc.yml file
`nodeLinker: node-modules`
Then install deps
`yarn add -D nodemon typescript ts-node @types/node`
Add script a custom script in package.json
`"dev": "nodemon index.ts"`
Make a index.ts file (leave it empty for now)
then run the script
`yarn dev`

At here I get `'ts-node' is not recognized as an internal or external command,
operable program or batch file.`

Then I found I need add yarn before the node or ts-node this case https://yarnpkg.com/getting-started/migration

So I create nodemon.json and add
```
{
    "exec": "yarn run ts-node"
}
```
(Use exec here for simplicity)

then run `yarn dev` again
which work fine

but it seems not restarting on file that continues run which at here I use express
install express
`yarn add express`
`yarn add -D @types/express`

in index.ts I put
```
import express from "express" ;
const app = express();

app.listen(8080, () => {
    console.log("listening");
} );
```

then run `yarn dev`

At first time it can start, but then after change the file and save, it stay at `[nodemon] restarting due to changes...`

**Comment by hands8142** [comment]
Add 
`
{
  "signal": "SIGKILL",
  "exec": "yarn run ts-node"
}
`

**Comment by H01001000** [comment]
I tested it, it solve my issue thanks.

**Comment by clintontristan** [comment]
didnt work for me
