### ISSUE TITLE
Update glob-parent for high-security vulnerability

### ISSUE THREAD

**Issue by MattKiazyk** [remy/nodemon#1880]
- `nodemon -v`: 2.0.0
- `node -v`: v12.16.1
- Operating system/terminal environment: MacOS 11.14
- Using Docker? What image: 
- Command you ran: N/A

### Expected behaviour
nodemon, in it's latest version, shouldn't have any security issues. 

### Actual behaviour
```
 "dependencies": {
    "chokidar": "^3.2.2",
```
Depends on `glob-parent` 5.1.0 which is has a high severity alert https://github.com/advisories/GHSA-ww39-953v-wcq6.

While users can easily update their lock to the latest `glob-parent` the upstream nodemon should also have the latest.

**Comment by remy** [comment]
nodemon doesn't depend on chokidar@3.2.2 - and you're nodemon is out of date.

For details, please see this dependency chart: https://snyk.io/test/npm/nodemon?tab=dependencies
