### ISSUE TITLE
Scripts disabled error on server initialization

### ISSUE THREAD

**Issue by Dallasdaboss** [remy/nodemon#1885]
So on Windows 10 in VSCode, I went to a new terminal (after installation) and typed "nodemon index.js" and entered it, it then produced an error saying:

` nodemon : File [PATH.TO.NPM]\npm\nodemon.ps1 cannot be loaded because running scripts is disabled on this system. For 
 more 
 information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.`

**Comment by remy** [comment]
Literally googled your error: https://stackoverflow.com/questions/63423584/how-to-fix-error-nodemon-ps1-cannot-be-loaded-because-running-scripts-is-disabl#63424744
