### ISSUE TITLE
Antivirus block

### ISSUE THREAD

**Issue by hd321kbps** [remy/nodemon#1890]
Dr.Web Antivirus blocks Nodemon version higher than 2.0.7.
Reboot doesn't work.
![image](https://user-images.githubusercontent.com/9886849/124983908-3f094400-e041-11eb-9333-560393c799ed.png)

**Comment by remy** [comment]
1. `windows-kill.exe` isn't a virus.
2. Perhaps stick to 2.0.7.

If this becomes a wider issue, then I'll at ways of making the dependency an opt-in.
