### ISSUE TITLE
Severe Vulnerability in a package use indirectly by nodemon (normalize-url)

### ISSUE THREAD

**Issue by FarzanRNobakht** [remy/nodemon#1894]
- Versions: v12.14.1
- `nodemon -v`:2.0.12
- Operating system/terminal environment (powershell, gitshell, etc): Linux bash
- Using Docker? What image: No
- Command you ran: yarn audit

### Expected behaviour
No vulnerability detected when running yarn audit

### Actual behaviour
By running yarn audit in a project that uses nodemon as a dev dependency
we will be informed that normalize-url that is used indirectly by nodemon has a high severity  vulnerability( it is not really clear for me, how much impact this has when used in nodemon )

 ```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ normalize-url                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.5.1 <5.0.0 || >=5.3.1 <6.0.0 || >=6.0.1                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nodemon                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nodemon > update-notifier > latest-version > package-json >  │
│               │ got > cacheable-request > normalize-url                      │
├───────────────┼──────────────────────────────────────────────────────────────┤                                                                                        
│ More info     │ https://www.npmjs.com/advisories/1755                        │
└───────────────┴──────────────────────────────────────────────────────────────┘ 
```

### Steps to reproduce
in any node project first add nodemon and then run yarn audit:
yard add --dev nodemon
yarn audit

**Comment by remy** [comment]
Please actually test your own environment instead of copy and pasting these reports. You haven't updated your own deps …

**Comment by sudhxnva** [comment]
@FarzanRNobakht run `yarn upgrade nodemon` to fix the issue.
