### ISSUE TITLE
use readline in function on('close',fun) error

### ISSUE THREAD

**Issue by ToDreamAndDream** [remy/nodemon#1896]
var reader = fs.createReadStream("./src/file1.js");
var writer = fs.createWriteStream("./src/file2.js");
const rl = readline.createInterface({
    input: reader,
    output: writer
})
rl.on("close", (data) => {
    fs.writeFile(path.resolve('./newFile.js'), '', (err) => {
        console.log(err)
    })
})

（In this case,use nodemon Compile, it will enter an infinite loop）

**Comment by remy** [comment]
1. this code doesn't run.
2. you're watching js files, so when you write a js file you're triggering the restart.
3. run `nodemon -w index.js` to _only_ watch that file
