### ISSUE TITLE
[nodemon] Internal watch failed: Circular symlink detected

### ISSUE THREAD

**Issue by koitoror** [remy/nodemon#1897]
- Versions: 
- `nodemon -v`:  "^2.0.12"
- `node-v`: "v16.4.2"
- Operating system/terminal environment (powershell, gitshell, etc):  hyperjs
- Using Docker? What image: FROM node:16-slim
- Command you ran:
❯ docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d 

### Expected behaviour
To watch for backend files

### Actual behaviour
Throws the above error on and exits running image on docker 
![image](https://user-images.githubusercontent.com/35098691/126856707-713c1fbe-4b2f-456c-bb0f-23031a302f98.png)

### Steps to reproduce
run nodemon and watch a to serve using express a file on docker with node:16 slim image and  you get the error

actually specified on `nodemon.json` file the folder to watch but it still watches all '.' 

```
[nodemon] 2.0.6

[nodemon] to restart at any time, enter `rs`

[nodemon] watching path(s): *.*

[nodemon] watching extensions: js,mjs,json

[nodemon] starting `node --experimental-modules backend/server.js`


[nodemon] Internal watch failed: Circular symlink detected: "/sys/class/bdi/1:0/subsystem" points to "/sys/class/bdi"

```
---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
You need to a) not watch the path with the circular link, b) fixing the circular link.
