### ISSUE TITLE
Security Error

### ISSUE THREAD

**Issue by krishnaUIDev** [remy/nodemon#1898]
When i try to run nodemon i am getting access denied error. Its look like trying to download somefile into the Windows machine and company firewall is blocking. Is their any alternative solution??

Version: 2.0.7￼￼

**Comment by remy** [comment]
With zero information, I can only say: no idea. 

Nodemon tries to check if it's up to date, so it's possibly that. Otherwise I'd suggest you check for what's being requested, possibly something on your machine has been compromised, but there's nothing else in nodemon
