### ISSUE TITLE
Feature Rquest idea: Blue-green deployment with nodemon

### ISSUE THREAD

**Issue by jonnytest1** [remy/nodemon#1899]
### Feature request
run blue green deplyoment with nodemon 
this would basically include a reverse proxy that only switches servers once they are fully running 

- parrallel server processes
- reverse proxy
- healthchecks
- port config

**Comment by remy** [comment]
Sorry, way outta scope. Nodemon is for development, any hacking on top of that is welcome, but this kind of functionality won't be baked in.
