### ISSUE TITLE
OSX Nodemon not in Path

### ISSUE THREAD

**Issue by medoix** [remy/nodemon#190]
When installed on OSX using "npm install -g nodemon" it installs to "/usr/local/share/npm/bin" so i needed to add this path to the /etc/paths file for it to work. Not sure if its a bug but thought i would post it.

**Comment by macgera** [comment]
Problem with homebrew doesn't help mt. Install nodemon and always have 

`michael:~$ nodemon`
`-bash: nodemon: command not found`

**Comment by macgera** [comment]
Also:

```
/usr/local/Cellar/node/0.12.7/libexec/npm/bin/nodemon -> /usr/local/Cellar/node/0.12.7/libexec/npm/lib/node_modules/nodemon/bin/nodemon.js
nodemon@1.4.1 /usr/local/Cellar/node/0.12.7/libexec/npm/lib/node_modules/nodemon
├── minimatch@0.3.0 (sigmund@1.0.1, lru-cache@2.6.5)
├── touch@1.0.0 (nopt@1.0.10)
├── ps-tree@0.0.3 (event-stream@0.5.3)
└── update-notifier@0.3.2 (is-npm@1.0.0, semver-diff@2.0.0, string-length@1.0.1, chalk@1.1.1, configstore@0.3.2, latest-version@1.0.1)
```

After i create link

`ln -s /usr/local/Cellar/node/0.12.7/libexec/npm/bin/nodemon /usr/local/bin/`

End everything works for me. Maybe this help somebody...
