### ISSUE TITLE
nodemon opens windows-kill.exe but doesn't restart process

### ISSUE THREAD

**Issue by xsalazar** [remy/nodemon#1903]
### Versions
- Versions: `node@v12.2.0, win32@10.0.19043`
- `nodemon -v`:
```bash
$ npm view nodemon version
2.0.12
```
- Operating system/terminal environment (powershell, gitshell, etc):
  - Powershell terminal
```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1023
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1023
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

  - VSCode IDE
    - Version: 1.58.2 (system setup)
      Commit: c3f126316369cd610563c75b1b1725e0679adfb3
      Date: 2021-07-14T22:10:15.214Z
      Electron: 12.0.13
      Chrome: 89.0.4389.128
      Node.js: 14.16.0
      V8: 8.9.255.25-electron.0
      OS: Windows_NT x64 10.0.19043

### Expected behaviour
Application would restart as normal, killing process and rerunning `npm start` which kicks off `nodemon` using `nodemon.json` config

### Actual behaviour
Application starts as normal and I see the proper output in VSCode debug console.
![image](https://user-images.githubusercontent.com/14851080/127701983-725e6f62-8abe-4658-8c7a-9ddc7e84de30.png)

Changing the `src/index.ts` (uncommenting the code to add the "Hello World" endpoint) and saving the file does the following:
- Prints `[nodemon] restarting due to changes...` to the VSCode debug window
- Opens the `windows-kill.exe` window, minimized on my toolbar
- Nothing else and doesn't restart the application

The changes are not redeployed, and the only way to proceed is to kill the process manually.
![image](https://user-images.githubusercontent.com/14851080/127702133-7f9da5ff-991b-46f6-9ee0-0eae44407496.png)

### Steps to reproduce
I have attached this sample project here as the most basic application I could get to reproduce this issue.
- [nodemon-example-windows-kill.zip](https://github.com/remy/nodemon/files/6909628/nodemon-example-windows-kill.zip)

#### Manual Steps
If you wish to do this from scratch, the steps I followed were:
- Make empty, temporary directory
- `npm init -y`
- `npm i -D typescript ts-node nodemon @types/node @hapi/hapi`
- `npx tsc --init`
- Create `nodemon.json`
```json
{
  "watch": ["src"],
  "ext": "ts",
  "exec": "node -r ts-node/register src/index.ts"
}
```
- Update `package.json` start script
```json
"scripts": {
  "start": "nodemon"
},
```
- Create `.vscode/launch.json`
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Server",
            "type": "pwa-node",
            "outputCapture": "std",
            "request": "launch",
            "runtimeArgs": [
                "run-script",
                "start"
            ],
            "runtimeExecutable": "npm",
            "skipFiles": [
                "<node_internals>/**"
            ],
        },
    ]
}
```

- Create sample Hapi server. Taken directly from https://hapi.dev/tutorials/?lang=en_US
```typescript
"use strict";

const Hapi = require("@hapi/hapi");

const init = async () => {
  const server = Hapi.server({
    port: 3000,
    host: "localhost",
  });

  server.route({
      method: 'GET',
      path: '/',
      handler: (request, h) => {
          return 'Hello World!';
      }
  });

  await server.start();
  console.log("Server running on %s", server.info.uri);
};

process.on("unhandledRejection", (err) => {
  console.log(err);
  process.exit(1);
});

init();
```
---

```
{
  run: false,
  system: { cwd: 'c:\\OpenSesame\\tmp\\nodemon-example' },
  required: false,
  dirs: [ 'c:\\OpenSesame\\tmp\\nodemon-example\\src' ],
  timeout: 1000,
  options: {
    dump: true,
    watch: [ 'src', re: /src/ ],
    exec: 'node -r ts-node/register src/index.ts',
    ignore: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**',
      re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/
    ],
    monitor: [
      'c:\\OpenSesame\\tmp\\nodemon-example\\src/**/*',
      '!**/.git/**',
      '!**/.nyc_output/**',
      '!**/.sass-cache/**',
      '!**/bower_components/**',
      '!**/coverage/**',
      '!**/node_modules/**'
    ],
    ignoreRoot: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**'
    ],
    restartable: 'rs',
    colours: true,
    execMap: { py: 'python', rb: 'ruby', ts: 'ts-node' },
    stdin: true,
    runOnChangeOnly: false,
    verbose: false,
    signal: 'SIGUSR2',
    stdout: true,
    watchOptions: {},
    execOptions: {
      script: null,
      exec: 'node -r ts-node/register src/index.ts',
      args: [],
      scriptPosition: null,
      nodeArgs: undefined,
      execArgs: [],
      ext: 'ts',
      env: {}
    }
  },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [ 'c:\\OpenSesame\\tmp\\nodemon-example\\nodemon.json' ],
  watchInterval: null,
  signal: 'SIGUSR2',
  command: {
    raw: { executable: 'node -r ts-node/register src/index.ts', args: [] },
    string: 'node -r ts-node/register src/index.ts'
  }
}
```

**Comment by mchammer01** [comment]
👋🏻 Something similar is happening to me.
I use Node.js version 16 to run a docs site locally on my Windows 10 machine. I run commands to install all the required dependencies, and to create static assets. I can see the running server on localhost:4000 in my browser when I start it, and usually, I can make changes to the site content and immediately see my updates on localhost:4000. This is no longer happening.

![windows-kill](https://user-images.githubusercontent.com/42146119/128910149-98fa3b22-68ef-4ddd-9caf-67ae9ca77b37.png)

I get a `windows-kill` window that remains open, and localhost:4000 is not updated with my changes. I have to kill the process and restart the server to see the latest updates. I have to resort to doing that every time I make changes to the site content, which is a bit of a nuisance.

I am not an engineer/developer but a colleague of mine who is told me that the issue is most likely to be with nodemon, and advised me to add a comment to this issue.
 
Can someone help?

**Comment by xsalazar** [comment]
@mchammer01 we were able to work around this issue by doing the following (you mentioned you're not a developer, but maybe this will still be helpful)

- If you have a `nodemon.json` config file, set `"signal": "SIGKILL"` or if you're launching from CLI configuration, `--signal SIGKILL` should have the same result

(apologies for the hard ping) @remy I noticed there was no further patches recently after the release to bundle this locally (v0.2.8), so I want to try to understand why we could still be seeing this?

**Comment by mchammer01** [comment]
@xsalazar 👋🏻 - thanks for the tip, I will definitely give your workaround a go!
Thanks again 🙇🏻 🙂

**Comment by mchammer01** [comment]
I can confirm that adding `"signal": "SIGKILL"` to the repo's _nodemon.json_ file fixes the issue 😀 🎉

**Comment by remy** [comment]
@mchammer01 if I can get the time today, I'll push a debug version of nodemon to npm that switches to using this signal on Windows by default to see if we can nail this issue once and for all.

**Comment by mchammer01** [comment]
That would be awesome @remy, thank you so much ✨ 🙇🏻 
Also, a big thank you to @xsalazar for the workaround in the mean time 🙇🏻

**Comment by mattpollard** [comment]
👋🏻 @remy, gentle bump... is this something you've been able to look into or may be able to look into soon? 🙏🏻

**Comment by LovingGarlic** [comment]
Also had this issue and the `"signal": "SIGKILL"` workaround worked for me as well.

**Comment by mattpollard** [comment]
One other potential workaround: we've tried starting our server with `npm start -- --signal SIGKILL`, and that also seems to get the correct signal to nodemon.

**Comment by remy** [comment]
I've been revisiting these as dropping briefly and I can't replicate at all.

Here's a screenshot showing my windows version, which is pretty darn close to the versions originally posted:

<img width="834" alt="Screenshot 2021-09-22 at 13 57 44" src="https://user-images.githubusercontent.com/13700/134347827-af101536-f8b3-499e-99ec-700eb398782f.png">

The one big difference I noticed is that the screenshots of the OP had the node debugger attaching, which mine didn't - but I followed the directions but kept inside of powershell rather than spawning from VSCode as I wanted to ensure I had the right version.

So, either we put this down to the FAQ, or someone can provide the missing bit so I can replicate fully (sorry).

**Comment by xsalazar** [comment]
@remy would you be able to see if you _can_ replicate the issue inside VSCode? Anecdotally, this DID work prior to the windows-kill changes and only broke after, so it seems related.

**Comment by remy** [comment]
@xsalazar I couldn't run PowerShell 5 in VSC, it was running PS7 - I'm not in Windows often enough to know why or how to change it. 

But agree - there's definitely a link to the windows-kill - but prior to that, the reports were that the sub process wouldn't shutdown - so I think it goes deeper.

I'll try VSC now - again though - I need other's help to find and solve this as I've been coming up empty on these related issues for months now.

**Comment by remy** [comment]
<img width="1536" alt="Screenshot 2021-09-22 at 22 35 55" src="https://user-images.githubusercontent.com/13700/134425330-d02b9982-2744-4e1d-941e-eb5b03b5b696.png">

Running in VSC, PS7, node@16, nodemon@latest - cannot replicate.

I believe there's a real problem here, but I can't replicate, so …

**Comment by xsalazar** [comment]
@remy Thanks for the response; super appreciate it. I'll try to find some time this week to dig in again -- it sounds like the only thing missing from your test above is the VSCode debugger, so maybe that's where the breakdown is happening?

**Comment by immortalmind2016** [comment]
i solved this issue inside this pr : https://github.com/remy/nodemon/pull/1938
you can check it

**Comment by peterbe** [comment]
> Can people following this thread test with `npm i nodemon@debug` and confirm if this works or not - this is the latest change with @immortalmind2016's changes.

We tried. Technically, I remote-tried asking a Windows contributor to try `npm i nodemon@debug` and then she was able to use `nodemon server.mjs` the same way we're doing it for "unix". As of that upgrade there was no longer a need to use `nodemon --signal SIGKILL server.mjs`.

**Comment by remy** [comment]
@peterbe 

> We tried. Technically, I remote-tried asking a Windows contributor to try `npm i nodemon@debug` and then she was able to use `nodemon server.mjs` the same way we're doing it for "unix". As of that upgrade there was no longer a need to use `nodemon --signal SIGKILL server.mjs`.

Just to clarify, are you saying it's working as expected with that build?

**Comment by peterbe** [comment]
@remy 

> Just to clarify, are you saying it's working as expected with that build?

Yes.

**Comment by GusGF** [comment]
Yes this worked for me too.
