### ISSUE TITLE
While Installing Package Nodemon

### ISSUE THREAD

**Issue by Abdulrauf-vhora** [remy/nodemon#1908]
nvm version: 0.38.0,
node version : 16.6.2

Error i get,
******************************************
npm ERR! code ECONNREFUSED
npm ERR! syscall connect
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to http://localhost:4873/nodemon failed, reason: connect ECONNREFUSED 127.0.0.1:4873
npm ERR!     at ClientRequest.<anonymous> (/Users/CS003/.nvm/versions/node/v16.6.2/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:110:14)
npm ERR!     at ClientRequest.emit (node:events:394:28)
npm ERR!     at Socket.socketErrorListener (node:_http_client:447:9)
npm ERR!     at Socket.emit (node:events:406:35)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR!  FetchError: request to http://localhost:4873/nodemon failed, reason: connect ECONNREFUSED 127.0.0.1:4873
npm ERR!     at ClientRequest.<anonymous> (/Users/CS003/.nvm/versions/node/v16.6.2/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:110:14)
npm ERR!     at ClientRequest.emit (node:events:394:28)
npm ERR!     at Socket.socketErrorListener (node:_http_client:447:9)
npm ERR!     at Socket.emit (node:events:406:35)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '127.0.0.1',
npm ERR!   port: 4873,
npm ERR!   type: 'system',
npm ERR!   requiredBy: '.'
npm ERR! }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/CS003/.npm/_logs/2021-08-17T12_25_03_354Z-debug.log
![Screenshot 2021-08-17 at 5 59 51 PM](https://user-images.githubusercontent.com/80057142/129726159-b9cc6ef2-7ebd-438f-aade-ecf5d0772dd6.png)

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
See errors, this is unrelated to nodemon
