### ISSUE TITLE
Wrong watch behavior when executing npm tasks

### ISSUE THREAD

**Issue by koutsenko** [remy/nodemon#1911]
OS: Windows
Situation: if I pass the package.json npm task to nodemon like that:
 
     "start:verbose": "node dist/index.js", 
     "watch:verbose": "nodemon --watch --exec npm run start:verbose",
 
Application do not terminates fully during wach restarts. All async tasks created with node-schedule are still running, so every restart stacks tasks more and more. So if I change npm task to similar like

     "watch:verbose": "nodemon --watch --exec node dist/index.js",

All is working fine. What's matter? I can build a minimal repro if need.

**Comment by kurochin143** [comment]
Can confirm, I have the same problem when running an express app. The previous instance remain and the next instance complains of the address already being used.
I know the previous instance still runs because I can still access endpoints, but without the changes.
