### ISSUE TITLE
Nodemon not restarting (not recognising file changes) in WSL2 - Ubuntu-18.04, when project directory is in Windows filesystem.

### ISSUE THREAD

**Issue by flatline-studios** [remy/nodemon#1913]
- Versions:  node@v16.7.0, linux@5.10.16.3-microsoft-standard-WSL2
- `nodemon -v`: 2.0.12
- Command you ran:
`nodemon app.js`

### Expected behaviour
When I change something (adding `console.log('')`) to `app.js` the server should restart.

### Actual behaviour
Nodemon doesn't do anything

### Things to note
This worked last night, and when I logged back on to my PC this morning, it's just stopped registering file changes. I'm at a real loss here.

```
❯ nodemon app.js
[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`

NodeJS server started!
```

And that's it. I can run `rs`, to manually restart the node server, which works fine:

```
rs
[nodemon] starting `node app.js`

NodeJS server started!
```

But no matter which file, how many, or how much I change a file, there's no automatic restarts.

**Comment by remy** [comment]
Can't replicate and doesn't contain enough information to help.

<img width="1399" alt="Screenshot 2021-09-22 at 14 09 54" src="https://user-images.githubusercontent.com/13700/134349568-cd9428fb-cf94-4a91-aed1-7816648afbaf.png">

**Comment by flatline-studios** [comment]
Sorry, I was rushed before when I created the issue, to give some more details...

nodemon is being run through WSL2, in Ubuntu-18.04.

The files are being changed within Windows 10, 20H2, in WebStorm.

`nodemon` is installed globally within WSL, and the Node/NPM interpreter in WebStorm is setup correctly.

It did work, and then it just stopped without any changes taking place.

Are there some logs or something I can grab to try and shed some light on this? It seems like `nodemon` in WSL can't see changes being generated in Windows anymore.

Oh, and the project directory is in the Windows NTFS filesystem, so is accessed via `/mnt/c/path/to/project`.

Any ideas?

Switching my interpreter over to the Windows Node executable, and again installing `nodemon` globally within Windows, works just fine.

**Comment by remy** [comment]
@flatline-studios if you run `nodemon -V` you'll get verbose logs, but if you run with the env of `DEBUG=nodemon,nodemon:*` you'll get detailed debugging.

Screenshots or videos also help here to see exactly what your environment looks like - there's always extra clues in those.

**Comment by wazp** [comment]
I think this might be related to `inotify` not working between the linux filesystem and windows right now. There's an open bug about it over at the WSL repo: https://github.com/microsoft/WSL/issues/4739

**Comment by resonancedesigns** [comment]
I can replicate this on my system with what I believe is in a similar WSL2 environment, I had the same issue. A simple work-around for me was to add the -L (legacy watch) argument to the command.

![Image 1](https://user-images.githubusercontent.com/3256035/153373773-d7dc1737-71bd-478c-8fb1-c7c0e368050e.png)

**Comment by pagoru** [comment]
Please, disable this shitty bot, this still occurs.

**Comment by remy** [comment]
Work around provided by @resonancedesigns above. This is a WSL2 issue and way beyond the reach of nodemon (I've personally tried to replicate but can't, thus I can't debug it), but the work around is acceptable.

**Comment by AngelRaymondi** [comment]
Same issue. Using `nodemon [your_file] --legacy-watch` worked for me.

**Comment by AhmedElTabarani** [comment]
The issue appears to me when I switch from Windows to Linux Fedora

I use `--watch` and it worked for me

`nodemon app.js --watch`

**Comment by beingadish** [comment]
> I can replicate this on my system with what I believe is in a similar WSL2 environment, I had the same issue. A simple work-around for me was to add the -L (legacy watch) argument to the command.
> 
> ![Image 1](https://user-images.githubusercontent.com/3256035/153373773-d7dc1737-71bd-478c-8fb1-c7c0e368050e.png)

Thanku this solution just worked for me!
