### ISSUE TITLE
Feature: Restart within node application

### ISSUE THREAD

**Issue by xp4xbox** [remy/nodemon#1921]
It would be very useful to have the ability within your node application to restart itself instead of manually typing `rs`.

**Comment by remy** [comment]
You can do this using a required nodemon and manually handling signals.

It's out of scope for the main project, hut certainly doable if it's something you need.

**Comment by xp4xbox** [comment]
I tried writing to the stdin using process.stdin.write("rs\n") but it seems that it's not possible to do so in nodejs
