### ISSUE TITLE
Auto-Restart by Crash

### ISSUE THREAD

**Issue by Justman10000** [remy/nodemon#1924]
The function that the applications restart should they crash is still missing!

**Comment by remy** [comment]
This was and never will be a feature of nodemon - that's not what it's for.

**Comment by Justman10000** [comment]
> 
> 
> This was and never will be a feature of nodemon - that's not what it's for.

Nun, es wäre Schwachsinn, dies nicht einzubauen... Es ist extrem unpraktisch bei der Bot Entwicklung, da meine Bots nicht gerade selten abstürzen!

**Comment by remy** [comment]
nodemon was never designed to restart on crash - this is the kind of thing you want to use forever for.

From inception back in 2010 it was designed to restart upon save - helping the developer and development process.

Restarting on crash would suggest this could be used in production - which it is not meant for. Again, there are _other_ tools for that.

**Comment by Justman10000** [comment]
> Again, there are _other_ tools for that.

And what would they be?

**Comment by remy** [comment]
forever? pm2? I heard there's this tool call goo-gle that might help, not 100% sure though…

**Comment by Justman10000** [comment]
> 
> 
> forever? pm2? I heard there's this tool call goo-gle that might help, not 100% sure though…

PM2 is dirt! Only a maximum of 4 processes are supported, if you want or need more, they are extremely money-loving!

**Comment by ww9** [comment]
> nodemon was never designed to restart on crash - this is the kind of thing you want to use forever for.
> 
> From inception back in 2010 it was designed to restart upon save - helping the developer and development process.
> 
> Restarting on crash would suggest this could be used in production - which it is not meant for. Again, there are _other_ tools for that.

Just wanted to comment that I spent half an hour trying to restart a nodejs process on crash using nodemon for a development environment.

It would be nice if the documentation stated clearly that it intentionally does not support this feature. It would probably save a great deal of collective time and frustration.

https://github.com/foreversd/forever seems unmaintained as they state:

> For new installations we encourage you to use [pm2](https://pm2.keymetrics.io/) or [nodemon](https://nodemon.io/)

Looks like pm2 it is then.
