### ISSUE TITLE
Ignore specific file type in directory and all sub-directories?

### ISSUE THREAD

**Issue by amhassen97** [remy/nodemon#1940]
I have been trying to ignore a specific file type in a directory and all its subdirectories, however nodemon keeps reloading regardless.

### Expected behaviour
For example, I am trying to ignore all js files in the views directory as well as any subdirectories. I am currently using a nodemon.json file with the following config object:

`{
    "verbose": true,
    "ignore": ["views/*.js", "views/**/*.js"],
    "ext": "js, ejs, json"
}`

### Actual behaviour
Nodemon still reloads on saving any js file in any subdirectory of the "views" folder.

**Comment by immortalmind2016** [comment]
please write the command you ran

**Comment by amhassen97** [comment]
I restarted and it seems to be working now. Seems I misunderstood the console logs, nodemon was not actually restarting, just running a file check to check if reload needs to be done. Apologies for the confusion.

**Comment by amhassen97** [comment]
Turns out I had forgotten the last change I made to the config file. The original glob pattern does not work, however the following does: 

`
{
    "verbose": true,
    "ext": "js, ejs, json", 
    "ignore": ["views\\**\\*.js"]
}
`
I am not sure why, but it may have something to do with the backslashes in the file paths matching the pattern check.
