### ISSUE TITLE
Terminate batch job (Y/N)? 

### ISSUE THREAD

**Issue by husseinsalah1** [remy/nodemon#1942]
- Versions: node@v14.8.0, win32@10.0.19043
- `nodemon@2.0.13`:
- Operating system/terminal environment (powershell, cmd): 
- Using Docker? What image: no
- Command you ran:
nodemon -e ts -x ts-node index.ts

### Expected behaviour

```
[nodemon] restarting due to changes...
[nodemon] starting `ts-node index.ts`
```

### Actual behaviour

```
[nodemon] restarting due to changes...
^CTerminate batch job (Y/N)?
[nodemon] starting `ts-node index.ts`
```

### Steps to reproduce
- change ts file

**Comment by crossan007** [comment]
- Duplicates https://github.com/remy/nodemon/issues/1351
- Relates to https://github.com/remy/nodemon/issues/1720
- Mentioned at https://github.com/remy/nodemon/issues/1109#issuecomment-341129880

**Comment by crossan007** [comment]
This happens _conditionally_ based on how nodemon was installed:

https://github.com/remy/nodemon/issues/1720#issuecomment-772556075
