### ISSUE TITLE
Nodemon not logging fatal errors when in quiet mode

### ISSUE THREAD

**Issue by mprast** [remy/nodemon#1945]
- Versions: `node@v16.2.0, linux@5.2.8-200.fc30.x86_64`
- `nodemon -v`: 2.0.14
- Operating system/terminal environment: bash 
- Using Docker? What image: N/A
- Command you ran: `yarn run nodemon -q <my_script.js> `

This is perhaps more of a feature request than a bug, but I recently ran into an issue where one of my services was crashing with no output - it turned out the root cause was the nodemon had run out of file watchers. In normal operation nodemon will log `[nodemon] Internal watch failed: ENOSPC: System limit for number of file watchers reached` when that happens, but in this case I was running nodemon with `-q` to reserve stdout for the spawned node process, and in quiet mode nodemon silently exits instead of logging the error. Judging from [this function](https://github.com/remy/nodemon/blob/0823f18435e43639f3b6b9f296b7385e99cffa3b/lib/utils/index.js#L36) this is intentional.

Not logging fatal errors when in quiet mode is surprising behavior to me, and caused a good bit of confusion when trying to figure out what was causing this particular problem. You may want to consider logging errors that are guaranteed to make nodemon exit, since at that point figuring out what happened seems like a higher priority than keeping stdout clean anyway.

Thanks for taking a look!

### Expected behaviour
Nodemon suppresses output but logs something if it crashes

### Actual behaviour
ALL Nodemon output is suppressed

**Comment by remy** [comment]
Errors don't go via the log.debug method, so it's not that function you've linked to - something else is at play.

Can you replicate consistently? (I'd imagine watching a disproportionate amount of files would do the trick, perhaps with some other system running at the same time).

If you can, we're going to debug it from your machine because I'm sure I won't be able to replicate what you're seeing myself.

**Comment by mprast** [comment]
@remy I actually can repro consistently, but after adding more ignore paths to my `nodemon.json` I was able to get myself under the file watcher limit, so this ticket is really more of a suggestion rather than a blocking issue for me. 

I can try to get a stack trace if that would help, but based on the error message and the way I'm seeing quiet mode implemented I'm almost certain the offending line is [here](https://github.com/remy/nodemon/blob/0823f18435e43639f3b6b9f296b7385e99cffa3b/lib/monitor/watch.js#L111). Looks like this line calls `utils.log.error`, and it appears the [quiet mode hook](https://github.com/remy/nodemon/blob/0823f18435e43639f3b6b9f296b7385e99cffa3b/lib/utils/index.js#L36) is replacing _every_ method on `utils.log` with a noop.

Happy to provide more context tomorrow if needed!
