### ISSUE TITLE
Feature Request: delay between restarts for multiple file change events

### ISSUE THREAD

**Issue by 9ae8sdf76** [remy/nodemon#1952]
- Versions: node@v16.6.1, darwin@20.6.0
- `nodemon -v`: 2.0.13
- Operating system/terminal environment (powershell, gitshell, etc): macOS Big Sur 11.6.1 (20G224) / zsh 5.8 (x86_64-apple-darwin20.1.0)
- Using Docker? What image: n/a
- Command you ran: `nodemon app.js`

### Expected behaviour
Saving a file that exists on Google Drive will only trigger one restart of the nodemon app.

### Actual behaviour
Any number of restarts may occur; in other words, I might get lucky and have one restart, or over the course of a few seconds, I may get several restarts. 

### Steps to reproduce
Save a file on Google Drive that is being watched by nodemon. Since it's intermittent, it may take a few saves before seeing the unintended behavior.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

```
[nodemon] 2.0.13
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
--------------
node: v16.6.1
nodemon: 2.0.13
command: /usr/local/Cellar/node/16.6.1/bin/node /usr/local/bin/nodemon --dump
cwd: /Volumes/GoogleDrive/My Drive/ITIS-5166 Network-based Application Development/module10
OS: darwin x64
--------------
{
  run: false,
  system: {
    cwd: '/Volumes/GoogleDrive/My Drive/ITIS-5166 Network-based Application Development/module10'
  },
  required: false,
  dirs: [
    '/Volumes/GoogleDrive/My Drive/ITIS-5166 Network-based Application Development/module10'
  ],
  timeout: 1000,
  options: {
    dump: true,
    ignore: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**',
      re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/
    ],
    watch: [ '*.*', re: /.*\..*/ ],
    monitor: [
      '*.*',
      '!**/.git/**',
      '!**/.nyc_output/**',
      '!**/.sass-cache/**',
      '!**/bower_components/**',
      '!**/coverage/**',
      '!**/node_modules/**'
    ],
    ignoreRoot: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**'
    ],
    restartable: 'rs',
    colours: true,
    execMap: { py: 'python', rb: 'ruby', ts: 'ts-node' },
    stdin: true,
    runOnChangeOnly: false,
    verbose: false,
    signal: 'SIGUSR2',
    stdout: true,
    watchOptions: {},
    execOptions: {
      script: 'app.js',
      exec: 'node',
      args: [],
      scriptPosition: 0,
      nodeArgs: undefined,
      execArgs: [],
      ext: 'js,mjs,json',
      env: {}
    }
  },
  load: [Function (anonymous)],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  signal: 'SIGUSR2',
  command: {
    raw: { executable: 'node', args: [ 'app.js' ] },
    string: 'node app.js'
  }
}
--------------
```

**Comment by remy** [comment]
Isn't this just the --delay option?

**Comment by 9ae8sdf76** [comment]
> Isn't this just the --delay option?

Ah. Well, in my defense, it's not in the `--help` output, and I didn't think to look on the github docs. My apologies. However, it appears these extraneous events are coming in well after saving the file on GoogleDrive.

**Comment by remy** [comment]
You missed the bold text at the end of the help: 

<img width="841" alt="Screenshot 2021-11-09 at 13 05 11" src="https://user-images.githubusercontent.com/13700/140929268-38831a6c-7311-4db4-b544-90f9a9d62d02.png">

There's a lot of options and it was getting overwhelming - so "extra" options are tucked in `--help options`.
