### ISSUE TITLE
nodemon config has a timestamp in it, conflicting with Bazel caching

### ISSUE THREAD

**Issue by Aghassi** [remy/nodemon#1955]
https://github.com/remy/nodemon/blob/54784ab842a220777958cf590a49c5d9721f9834/bin/postinstall.js#L24

This step makes this file non cacheable because the timestamp changes on every install/run. While this is working as intended, I'm posting more as a paper trail in case someone runs across this also.

**Comment by Aghassi** [comment]
This problem still exists. Closing this automatically is not helpful

**Comment by remy** [comment]
It was closed because it was idle and no one tried sending an PRs or proposed any code changes. Is all I can say, sorry.

**Comment by Aghassi** [comment]
I'll have to load into my brain where we caught this, but basically the package invalidating the post install step every week is non hermetic and causes us to have to reinstall things. My current suggestions would be (and I'm happy to try and contribute these)

1. Add an environment variable that skips this `last` check and warns the users that they are out of date OR
2. Allow us to pass a unique name or something so the configstore gets a consistent unique string instead of one that randomly changes once a week

In both cases, it avoids stamping an arbitrary date time into a file on disk that is then used to check things on postinstall. Would either of those suggestions be acceptable changes?
