### ISSUE TITLE
nodemon does not restart server, stuck on  --->   [nodemon] restarting due to changes...

### ISSUE THREAD

**Issue by JoeyFlaum** [remy/nodemon#1956]
- Versions: 
- `nodemon -v`:2.0.15
- Operating system/terminal environment (powershell, gitshell, etc):  node@v16.13.0, win32@10.0.19043 / Git Bash
- Using Docker? What image: No
- Command you ran:
npm start

### Expected behaviour

Expected behavior is nodemon restarting the server after saving changes in the js/json files.

server.js file 
```
const http = require('http');

const server = http.createServer((req, res) => {
  res.setHeader('Content-type', 'text/plain');
  res.write('Hello');
  res.end();
});

const PORT = 3000

server.listen(PORT, () => console.log(`Server is running on port ${PORT}`));

```
package.json
```
{
  "name": "nodejs",
  "version": "1.0.0",
  "description": "learn HTTP",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "nodemon server.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/JoeyFlaum/Node.js.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/JoeyFlaum/Node.js/issues"
  },
  "homepage": "https://github.com/JoeyFlaum/Node.js#readme",
  "devDependencies": {
    "nodemon": "^2.0.15"
  }
}

```

### Actual behaviour
```
$ npm start

> nodejs@1.0.0 start
> nodemon server.js

[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
Server is running on port 3000
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...

```
### Steps to reproduce
1)   Start the server with `npm start` command.

2)   save either the package.json file or server.js file

3) nodemon does not restart the server.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.
```
> nodejs@1.0.0 start
> nodemon --dump server.js

[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
--------------
node: v16.13.0
nodemon: 2.0.15
command: C:\Program Files\nodejs\node.exe D:\Joey\WebDev\NodeJs\node_modules\nodemon\bin\nodemon.js --dump server.js   
cwd: D:\Joey\WebDev\NodeJs
OS: win32 x64
--------------
{
  run: false,
  system: { cwd: 'D:\\Joey\\WebDev\\NodeJs' },
  required: false,
  dirs: [ 'D:\\Joey\\WebDev\\NodeJs' ],
  timeout: 1000,
  options: {
    dump: true,
    ignore: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**',
      re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/
    ],
    watch: [ '*.*', re: /.*\..*/ ],
    monitor: [
      '*.*',
      '!**/.git/**',
      '!**/.nyc_output/**',
      '!**/.sass-cache/**',
      '!**/bower_components/**',
      '!**/coverage/**',
      '!**/node_modules/**'
    ],
    ignoreRoot: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**'
    ],
    restartable: 'rs',
    colours: true,
    execMap: { py: 'python', rb: 'ruby', ts: 'ts-node' },
    stdin: true,
    runOnChangeOnly: false,
    verbose: false,
    signal: 'SIGUSR2',
    stdout: true,
    watchOptions: {},
    execOptions: {
      script: 'server.js',
      exec: 'node',
      args: [],
      scriptPosition: 0,
      nodeArgs: undefined,
      execArgs: [],
      ext: 'js,mjs,json',
      env: {}
    }
  },
  load: [Function (anonymous)],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  signal: 'SIGUSR2',
  command: {
    raw: { executable: 'node', args: [ 'server.js' ] },
    string: 'node server.js'
  }
}
--------------
```

**Comment by remy** [comment]
Can you also run with `--verbose` so we can see what's triggering the restart.

Also, are you running in the bare terminal or via an IDE like VS Code (sorry, all these things add to complexity it turns out).

**Comment by JoeyFlaum** [comment]
@remy 
```

$ npm start

> nodejs@1.0.0 start
> nodemon --verbose server.js

[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 4420 to restart 
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json  
[nodemon] starting `node server.js`
[nodemon] forking
[nodemon] child pid: 13760
[nodemon] watching 3 files
Server is running on port 5000
```

I am using the VS Code Bash terminal. 

```
$ git --version
git version 2.33.1.windows.1

```

![image](https://user-images.githubusercontent.com/58762590/142217185-a2d87d4d-e4e5-4c3a-8da5-586eb8f172f5.png)

**Comment by remy** [comment]
Sorry, that wasn't very clear. What I need to see with verbose is when it's restarting as it should show what files are triggering the restart.

**Comment by JoeyFlaum** [comment]
@remy 

Is this what you are looking for?
```
$ npm start

> nodejs@1.0.0 start
> nodemon --verbose server.js

[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 3700 to restart 
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json  
[nodemon] starting `node server.js`
[nodemon] forking        
[nodemon] child pid: 8524
[nodemon] watching 3 files
Server is running on port 5000
[nodemon] files triggering change check: server.js
[nodemon] matched rule: **\*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] server.js
```

**Comment by remy** [comment]
Yes, but with the restart loop happening ... I'm assuming it's still a problem?

**Comment by JoeyFlaum** [comment]
> Yes, but with the restart loop happening ... I'm assuming it's still a problem? 

Yes, it is still stuck. The terminal code I pasted is after saving the server is file. The console output does not show up/ server restart does not happen.

Thanks for the help!

**Comment by chris-strudel** [comment]
I'm seeing this behavior as well.  I wonder if it's a Node version thing.

Windows 10
Node 14.18.1

> nodemon --verbose app.js

[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 8460 to restart
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
[nodemon] forking
[nodemon] child pid: 16772
[nodemon] watching 3 files
[nodemon] files triggering change check: app.js
[nodemon] matched rule: **\*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] app.js

**Comment by stettdev** [comment]
I am also experiencing this behavior and `rs` command won't work either.

Windows 10, Node 16.13.1

```npx nodemon app.js -V
[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 16128 to restart
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json  
[nodemon] starting `node app.js`
[nodemon] forking
[nodemon] child pid: 21348
[nodemon] watching 43 files
[nodemon] files triggering change check: app.js
[nodemon] matched rule: **\*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] app.js

[nodemon] files triggering change check: app.js
[nodemon] matched rule: **\*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] app.js
```

**Comment by lorand-horvath** [comment]
Is this issue similar/the same as https://github.com/remy/nodemon/issues/1971 ?

**Comment by JoeyFlaum** [comment]
> Is this issue similar/the same as https://github.com/remy/nodemon/issues/1971 ?
> 
> Are you guys using Git Bash as a terminal under VSCode? That might seem to be the common issue... it's a Unix shell emulated on Windows.... so not native functionality AFAIK. Try switching the terminal to CMD or PowerShell in VSCode, if you're on Windows.

I tried PowerShell and CMD. Does the same thing...

**Comment by zorridge** [comment]
I added the variables below to Path in system variables and it fixed the problem for me

`C:\Windows; C:\Windows\system32; C:\Windows\System32\Wbem`

**Comment by siva-kishor** [comment]
> I added the variables below to Path in system variables and it fixed the problem for me
> 
> `C:\Windows; C:\Windows\system32; C:\Windows\System32\Wbem`

Thanks @zorridge . I was facing the same issue and it actually resolved the problem.

**Comment by octorchard** [comment]
Hi, it appears that the problem is not related to a specific shell, but is related to the folders mentioned by @zorridge not being in the `path` on Windows. 

I encountered this same issue while setting the `path` variable in my VSCode settings.

Therefore, if you are using a custom shell/setting the `path` environment variable, please ensure that the above mentioned folders **are available in the `path`**.

Thanks.

**Comment by ash-js** [comment]
> I added the variables below to Path in system variables and it fixed the problem for me
> 
> `C:\Windows; C:\Windows\system32; C:\Windows\System32\Wbem`

Adding that path doesn't solve my problem ...
nodemon 2.0.15
node v16.13.2
running powershell on vscode

**Comment by mihail-valkov** [comment]
> Adding that path doesn't solve my problem ...

I also have this problem. My Path vars seem ok, as suggested above. 
I reproduced it with the simplest express app:

app.js:
```
const express = require('express');
const app = express();
const PORT = process.env.PORT || 5000;
app.listen(PORT, console.log(
    `Server started on port ${PORT}`));
```
package.json:
```
{
  "dependencies": {
    "express": "^4.17.3"
  },
  "devDependencies": {
    "nodemon": "^2.0.15"
  }
}
```
I also tried my app with **pm2** latest. And it crashes upon killing the process:

09:29:35 PM2      | pid=4536 msg=failed to kill - retrying in 100ms
09:29:35 PM2      | Process with pid 4536 could not be killed
09:29:35 PM2      | app=app id=0 pid=4536 could not be stopped

Then I tried again **nodemon** and when it hanged I killed the node child process manually with:
`kill PID`

and then it restarted monitoring successfully.
I also tested this with Git Bash with absolutely the same behaviour.
I also tested with nodemon 1.9 with absolutely the same behavior.

Versions:
nodemon 2.0.15

Visual Studio Code:
Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z (4 days ago)

Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by JoeyFlaum** [comment]
> > I added the variables below to Path in system variables and it fixed the problem for me
> > 
> > `C:\Windows; C:\Windows\system32; C:\Windows\System32\Wbem`
> 
> Adding that path doesn't solve my problem ...
> nodemon 2.0.15
> node v16.13.2
> running powershell on vscode

+1

**Comment by mattstief** [comment]
> I am also experiencing this behavior and `rs` command won't work either.
> 
> Windows 10, Node 16.13.1
> 
> ```
> [nodemon] 2.0.15
> [nodemon] to restart at any time, enter `rs`
> [nodemon] or send SIGHUP to 16128 to restart
> [nodemon] watching path(s): *.*
> [nodemon] watching extensions: js,mjs,json  
> [nodemon] starting `node app.js`
> [nodemon] forking
> [nodemon] child pid: 21348
> [nodemon] watching 43 files
> [nodemon] files triggering change check: app.js
> [nodemon] matched rule: **\*.*
> [nodemon] changes after filters (before/after): 1/1
> [nodemon] restarting due to changes...
> [nodemon] app.js
> 
> [nodemon] files triggering change check: app.js
> [nodemon] matched rule: **\*.*
> [nodemon] changes after filters (before/after): 1/1
> [nodemon] restarting due to changes...
> [nodemon] app.js
> ```
I had this same issue. I found a workaround here https://github.com/remy/nodemon/issues/573. I changed the signal used and it works now: `nodemon --signal SIGINT app.js`.

**Comment by yashrajbothra** [comment]
> 

Hey, Can you provide the full path of server.js??

Thanks

**Comment by RiverBeaver** [comment]
> I added the variables below to Path in system variables and it fixed the problem for me
> 
> `C:\Windows; C:\Windows\system32; C:\Windows\System32\Wbem`

Thank you vwry much. This really helped
