### ISSUE TITLE
write to stderr

### ISSUE THREAD

**Issue by basaran** [remy/nodemon#1958]
- Versions: 2.0.15
- Linux 

Nodemon outputs information to `stdout` during execution. Such as:

```
nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node ./src/bin/server.js`
```

It's common to use pipelines during development and in production. Outputting to stdout forwards the lines to the next program in chain.

### Expected behaviour

Nodemon should perhaps output to stderr, and let the user to decide if they would like to pass it onto the next program in chain.

### Actual behaviour

Nodemon outputs to stdout.

### Steps to reproduce

nodemon ./src/something.js | tee out.txt

here, the out.txt should only receive the output from the application being executed, and not the nodemon itself.

I can work on PR if you are interested.

**Comment by remy** [comment]
I tried hard to leave stderr alone to allow for user code to make use of it. Equally stdout for nodemon can be silenced using `-q`.

For anyone wanting to push all nodemon messaging through stderr they're able to require nodemon as a dep and reroute the messages.

If there was going to be a PR, it should let a config option (which means adding help text, defaults and checking it works in the required method too) that would put logging on stderr (and would need tests) - I don't think it's a small PR, but if it's written properly I'd be happy to merge.

I'm going to close this issue for now (as I've answered the original points), and don't mind either way if you want to take a shot at a pr 👍
