### ISSUE TITLE
Nodemon keeps running in the background once I close the terminal window.

### ISSUE THREAD

**Issue by mdc-1** [remy/nodemon#1964]
When I close the terminal in which I'm running nodemon to execute my code, nodemon keeps runing my aplication in the background like nothing happened, I can still go to localhost:3000 and find my app running as always, eventhough the terminal has already being closed. Besides using computing resources in the background when I don't want to, the main problem is that when I try to open a new terminal and restart the very same app (with the same localhost port being used), nodemon crashes because the localhost port was already in use! Of course! that makes sense because nodemon doesn't want terminate itself as a good boy. I could run a linux command to close that port to be able to restart my same app later using nodemon, but I guess that would only kill the localhost port, nodemon would still be alive, persisting like the freaking terminator from the future, working for skynet... nothing can stop him... 

- Versions: node v17.3.0, nodemon 2.0.15
- Operating system/terminal environment: Ubuntu 20.04, Terminal
- Command you ran:     nodemon app

### Expected behaviour
Nodemon stops working once the terminal closes. No more running in the background, no more locking localhost ports.
### Actual behaviour
Nodemon keeps running in the background once the terminal is closed, keeps using localhost ports

**Comment by lorand-horvath** [comment]
Ctrl+C twice to close nodemon, before killing the terminal. That's what I do - no more terminators from the future :-)

**Comment by mdc-1** [comment]
Thanks. that's what I do now as well, unfortunately. But sometimes I forget and get into trouble again. :)
