### ISSUE TITLE
macos下无法使用globstar语法

### ISSUE THREAD

**Issue by likaia** [remy/nodemon#1966]
我想使用xx/**/*来匹配xx目录下的所有文件，我用的命令是：nodemon --watch backend/**/* -e ts,tsx --exec ts-node ./backend/index.ts

运行后显示找不到模块文件，详细报错：

backend/apis/imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.resolve (internal/modules/cjs/helpers.js:80:19)

![image](https://user-images.githubusercontent.com/35120858/148234612-da41599d-75f0-4bab-8b3c-d6ffcaa3274b.png)

- Versions: node: v12.11.1
- `nodemon -v`: 2.0.13
- Operating system/terminal environment (powershell, gitshell, etc):  macos

**Comment by likaia** [comment]
解决方案是：用/*来替代/**/*

即：nodemon --watch backend/**/* -e ts,tsx --exec ts-node ./backend/index.ts

**Comment by remy** [comment]
Run this without nodemon with the same command, i.e. `ts-node ./backend/index.ts` - I believe you'll have the same issue.

I'm happy to re-open the issue if you do still have the issue and you're able to provide pared down example code to replicate with.
