### ISSUE TITLE
Make node-mon the only legal pronunciation for this package

### ISSUE THREAD

**Issue by zS1L3NT** [remy/nodemon#1970]
I have an irritating friend who keeps calling this no-demon. Please update the pronunciation config so that node-mon is the only proper way to pronounce this package because this is a node-monitor

**Comment by TechSupportz** [comment]
I very much agree. This is a very pressing issue for all of us

**Comment by PuttTim** [comment]
I am the supposedly irritating friend, I believe it is called no-demon because it keeps the demons of node.js away from my packages.

**Comment by zS1L3NT** [comment]
IT'S NODE-MON

**Comment by UnscriptedLogic** [comment]
I find this issue very irrelevant and unimportant. Anyone and everyone should have their own way of pronouncing it.

**Comment by remy** [comment]
You know this is documented, right? https://github.com/remy/nodemon#pronunciation

And intentional.
