### ISSUE TITLE
Lockup in postinstall on M1 Macs running docker

### ISSUE THREAD

**Issue by Fmstrat** [remy/nodemon#1972]
- `nodemon -v`: Latest (installing issue)
- `node -v`: 11.15.0
- Operating system/terminal environment: M1 MacOS Monterey
- Using Docker? What image: Yes, node:11-alpine
- Command you ran: `docker run --rm -ti -v "$PWD":/src -w /src --platform linux/amd64 node:11-alpine sh`

### Expected behaviour
`npm install` completes

### Actual behaviour
`npm install --save nodemon` sits forever during post-install. `npm install --save --ignore-scripts nodemon` works.

### Steps to reproduce
Pretty basic, really. Run the above docker command, then the npm install command.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by toddtarsi** [comment]
@Fmstrat - Just wanted to say here, a workaround for me was to pass in an env var for SUPPRESS_SUPPORT="true"

**Comment by remy** [comment]
@toddtarsi I'd love that to be added to the FAQ if you wanted to do a PR
