### ISSUE TITLE
NODEMON SKIPPING OPTIONAL DEPENDENDENCY "fsevents"

### ISSUE THREAD

**Issue by Onwurah121** [remy/nodemon#1973]
- Versions: Node Version: 14.18.1
- `nodemon -v`: 2.0.15
- Operating system/terminal environment (powershell, gitshell, etc): Win(10) OS/Hyper terminal
- Using Docker? What image: No
- Command you ran: "npm i -g nodemon"

### Expected behaviour

Installation complete

### Actual behaviour

> nodemon@2.0.15 postinstall C:\Users\Edmund Obinna\AppData\Roaming\npm\node_modules\nodemon
> node bin/postinstall || exit 0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\nodemon\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ nodemon@2.0.15
added 116 packages from 53 contributors in 46.372s

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
The issue described is "installation completes", yet it does. The warning is to let you know the *optional* dep wasn't installed - for the reasons it gave (which I can see is it's used for a different OS). So, as per the log from npm, this isn't an issue.
