### ISSUE TITLE
Feature request: Allow --watch to override default extension watch list

### ISSUE THREAD

**Issue by kilbiller** [remy/nodemon#1977]
- Versions: node@v16.13.2, linux@4.19.104-microsoft-standard
- `nodemon -v`: 2.0.15
- Operating system/terminal environment (powershell, gitshell, etc): wsl2
- Using Docker? What image: -
- Command you ran: -

### Expected behaviour

`nodemon --watch 'src/**/*.ts'` should set extension watch list to ts
`nodemon --watch 'src/**/*.{ts,tsx}'` should set extension watch list to ts,tsx

### Actual behaviour

You have to set --ext manually

---
Hi,
I was trying to use nodemon to compile some typescript files with esbuild but I had a hard time figuring out that you needed to change --watch and --ext at the same time (and --exec but that's another issue).
I think that would give a better DX, but feel free to close if you don't.

**Comment by remy** [comment]
The --watch is meant for directories not extensions. Add extensions via the process *and* adding (arbitrary) additions to extensions (such as "if I watch tsx also watch ts) is messy (I've got a feeling I tried it before and failed).

It's exactly why you have control using the --ext arg.
