### ISSUE TITLE
Parsing string argument to Nodemon has issues with nested quotes; allow an array argument instead?

### ISSUE THREAD

**Issue by timspro** [remy/nodemon#1980]
- Versions: 
- `nodemon -v`:
- 2.0.15
- Operating system/terminal environment (powershell, gitshell, etc): 
- Mac Monterrey, Bash
- Using Docker? What image: 
- No
- Command you ran:

In JavaScript,

``nodemon(`./src/run.js --headers '{"a": "b"}'`)``

### Expected behaviour

Nodemon runs Node.js with `./src/run.js` script providing custom arguments of '--headers' and '{"a": "b"}'

### Actual behaviour

The '{"a": "b"}' argument is ignored.

In `cli/index.js`, stringToArgs() splits '{"a": "b"}' into '{"a": and "b"}'. The former arg starts a new group, however, stringToArgs() doesn't bother to check if it is matching a group when it starts a new one. As a result, the former arg is ignored and since the latter arg is part of a group that is not closed, it is ignored as well.

A fix would be to change line 24 in `cli/index.js` to `if (!open && (lead === '"' || lead === '\'')) {`

Additionally,:

stringToArgs() cannot handle escaped quotes if the surrounding quotes are of the same kind i.e. '{"a": "' b"}' which when split would be '{"a":, "', and b"}'. Even if the other issue were fix, the algorithm being used would cause the last part to still be ignored. 

### Steps to reproduce

I ended up getting around this by accessing the parse() function in cli/index.js directly and passing an array argument. It would be nice if this was documented somewhere or `lib/nodemon.js` allowed an array argument like: 
```js
if (Array.isArray(settings)) { // not sure if this is the project's preferred way to check for this
  settings = cli.parse(settings);
} else if ...
```

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by sweetkane** [comment]
Hello. I am a senior studying CS at the University of Michigan. I am supposed to make an open source contribution for my Software Engineering class, and I would love to take care of this issue if it hasn't been fixed already. Could you possibly reassign it to me?
