### ISSUE TITLE
[Bug, Discussion] Invalid parsing of the 'exec' parameter in Windows

### ISSUE THREAD

**Issue by TheDechev** [remy/nodemon#1983]
### Info

- `node -v`:  **v17.3.0**
- `nodemon -v`: **2.0.15**
- Operating system/terminal environment (powershell, gitshell, etc): **Windows** (shell not important)
- Using Docker? **N/A**
- Command you ran:

1. Set the `exec` parameter in the local configuration file (nodemon.json):
```
{
    "exec": "/C/Program Files/nodejs/node"
}
```

2. Run any node application, e.g.:
```
nodemon app.j
```

### Expected behaviour

The `exec` parameter should be parsed and converted to:
`\C\Program Files\nodejs\node`

### Actual behaviour

- The exec parameter is parsed using `split(' ')` ([here](https://github.com/remy/nodemon/blob/main/lib/monitor/run.js#L80)) , thus it separates the path and converts it to:
`\C\Program Files/nodejs/node`
- The application crashes because it attempts to access an invalid path:
```
The system cannot find the path specified.
[nodemon] app crashed - waiting for file changes before starting...
```

### Steps to reproduce

Create a configuration file (nodemon.json) and set the exec paramter to a path containing blank spaces. (just like the example above)

-------

### Summary

I have a few ideas, but both of them have some sort of a downside-
- Introduce `execArr` parameter which'll allow setting an executable with arguments in an array.
Downside - will be too similar to the `execMap `parameter.

- Split `exec `parameter to `execPath `and `execArgs`.
Downside - that would break API.

What do you guys think?

**Comment by TheDechev** [comment]
ping

**Comment by TheDechev** [comment]
@remy, relevant or not interesting?

**Comment by remy** [comment]
Just reading this, the arg doesn't look valid:

```
"exec": "/C/Program Files/nodejs/node"
```

Shouldn't it be:

```
"exec": "/C/Program\ Files/nodejs/node"

// or

"exec": "'/C/Program Files/nodejs/node'"
```

**Comment by remy** [comment]
Assume the above changed fixed the issue - happy to hear otherwise.

**Comment by TheDechev** [comment]
You are completely right @remy, my bad, thanks!
