### ISSUE TITLE
nodemon do not kill older process

### ISSUE THREAD

**Issue by SDAdham** [remy/nodemon#1987]
Hello, I have the same issue as https://github.com/remy/nodemon/issues/1435 and I am on the latest version

- Versions: 
- `nodemon -v`: `2.0.15`
- Operating system/terminal environment (powershell, gitshell, etc): openSUSE Tumbleweed latest version
- Using Docker? What image: N/A
- Command you ran: 

### Expected behaviour

It should terminate the old process before jumping into the new one once the code is changed.

### Actual behaviour

It doesn't terminate and so I get that the port is still used.

### Steps to reproduce

It's not happening all the time, but I do often just do `rs` and when memory builds up due to bad cleanup, I'd have to terminate nodemon completely and re-run it from scratch.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
You'll need to provide information on how to replicate with pared down code, otherwise nothing can be done with this issue except for closing it

**Comment by SDAdham** [comment]
Unfortunately there is nothing more i can give and not sure how i can replicate this. Feel free to close if you cannot help. thanks.

**Comment by remy** [comment]
If you're unable to replicate then yeah, I won't be able to replicate to even begin to understanding any fix.
