### ISSUE TITLE
passing command line options to scripts

### ISSUE THREAD

**Issue by andrisi** [remy/nodemon#1988]
Command line options are not passed fully to scripts, or the way to do so is seeminly missing from the docs. Single hypen params seem to be dropped.

node: 16.13
nodemon: 2.0.6

### Steps to reproduce

`nodemon mc.js --worker -s 0 10 --qdbg --dbg`

### Expected behaviour

`[nodemon] starting `node  mc.js --worker -s 0 10 --qdbg --dbg`

Pass command line options to the script in full.

### Actual behaviour

`[nodemon] starting `node mc.js --worker 10 --qdbg --dbg`

Some are ignored.

**Comment by yi-ge** [comment]
I have the same problem.

**Comment by yi-ge** [comment]
```javascript
      args: [
        '--experimental-specifier-resolution=node',
        ...argv
      ],
      script: 'src/main.ts',      
```

You can add command line options like this.

**Comment by yi-ge** [comment]
```javascript
execArgs: [
        '--no-warnings',
        '--experimental-vm-modules',
        '--experimental-specifier-resolution=node',
        '--loader',
        'ts-node/esm'
      ],
```
or this.
