### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by marcusl-s** [remy/nodemon#1990]
<img width="1440" alt="Screen Shot 2022-03-18 at 19 26 43" src="https://user-images.githubusercontent.com/35894743/159093981-a5f9973f-c2c0-42db-b369-0947bbc2c02b.png">

**Comment by remy** [comment]
That's *your* app crashing, not nodemon

**Comment by marcusl-s** [comment]
Ok! Thank you!
