### ISSUE TITLE
Unknown requests are being made to access personal and system information.

### ISSUE THREAD

**Issue by ayushpratap2494** [remy/nodemon#1991]
- `nodemon -v`: 2.0.15
- `node -v`:  12.13.0
- Operating system/terminal environment:  windows 10/ vs code terminal
- Using Docker? What image: none
- Command you ran: nodemon index

### Expected behaviour

Should just start the node.js server on the specified port 3000

### Actual behaviour

After starting the server, several unknown requests are being made to the localhost:3000
Trying to access user personal and system information like passwords, environmental variables, 
Trying to access several scripts which definitely seems to be some security issue.

### Steps to reproduce

I am attaching the screenshots for the same. All these requests are not made by me.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.
<img width="501" alt="issue1" src="https://user-images.githubusercontent.com/32447637/159249803-7b789b8e-6723-4f05-936b-4c610935de69.png">
<img width="512" alt="issue2" src="https://user-images.githubusercontent.com/32447637/159249808-8edb9890-3650-4e16-90a6-00e647da35b1.png">
<img width="566" alt="issue3" src="https://user-images.githubusercontent.com/32447637/159249811-cce06d6a-1434-4224-a83d-e6b2f776438a.png">

**Comment by remy** [comment]
So, first, nodemon isn't doing this. But for your reassurance, run the same script *without* nodemon (ie just use node), and do you see the same thing?

**Comment by ayushpratap2494** [comment]
I tried to reproduce the same issue by simply running using node but could not reproduce it.
It is only happening if running using nodemon.

**Comment by remy** [comment]
You're going to need to provide a screen recording of running both with nodemon and without. I need to *see* what's happening. I'll reopen for the short term, but I'm certain this is coming from outside of nodemon.

**Comment by ayushpratap2494** [comment]
Sure Thanks ! I will share recording when I am able to reproduce the same issue again ! You may close this as of now.

**Comment by remy** [comment]
When you do, again, make sure you show kicking off nodemon and the requests coming in, then end the nodemon process and kick off with node within the same window - i.e. try to minimise the number of changing variables.
