### ISSUE TITLE
Nodemon spawns package.json main if target file doesn't exist

### ISSUE THREAD

**Issue by joshkel** [remy/nodemon#1996]
- Versions: node@v14.19.1, darwin@21.4.0
- `nodemon -v`: 2.0.15
- Operating system/terminal environment (powershell, gitshell, etc): macOS zsh
- Using Docker? What image: No.
- Command you ran:

```
nodemon path/to/missing.js
```

### Expected behaviour

An error message that `path/to/missing.js` doesn't exist.

### Actual behaviour

Nodemon prints a confusing (to me, at least) message then spawns whatever script is listed as the package.json's `"main"` (in this example, `index.js`):

```
[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node path/to/missing.js index.js`
```

### Steps to reproduce

Run `nodemon path/to/missing.js` within a project that has an appropriate `"main"` entry in its package.json.

**Comment by remy** [comment]
This is intended, and iirc, documented, behaviour.

**Comment by joshkel** [comment]
Thanks for the quick reply.

I see where it's documented to use `"main"` if no script is given, but I don't see where it's documented that arguments that don't refer to existing files are instead passed to Node for `"main"`.

I ran across this because I had problems in my TypeScript compilation setup, and so Nodemon launched two different processes depending on whether TypeScript was functioning properly. This seems undesirable.

More generally, I'm confused by Nodemon's behavior here. If I run

```
nodemon first second -- third fourth
```

and none of (first, second, third, fourth) exist, and package.json's main is `./index.js`, then Nodemon does the following:

* generates a command line of `first second index.js third fourth`
* decides that, since `first` doesn't start with `-`, it can fork instead of exec
* discards `first`, on the assumption that it's what Node.js should be executing
* spawns index.js with a process.argv of [['/usr/bin/node', '/path/to/index.js', 'second', './index.js', 'third', 'fourth']`

which doesn't seem correct.

Possible ideas / suggestions:

* Nodemon could take some sort of `--file` or `--script` option to explicitly specify the file to spawn and fail if it doesn't exist, or some sort of option to disable the behavior of checking package.json for main and scripts.start, or some sort of option to specify a different path to package.json (so you could use `--package-json /dev/null` to disable checking main and scripts.start)? Given the (understandable) desire to not add more options to Nodemon, I'm guessing you're not interested in doing this.
* Disable forking whenever Node.js arguments are specified, instead of only if the first Node.js argument starts with a '-'? (I'm not sure how to make "Node.js arguments" work otherwise.)
* Update [execFromPackage](https://github.com/remy/nodemon/blob/v2.0.15/lib/config/exec.js#L15) to log a message if it decides to use package.json's main or script.start, to help explain what's going on?

If none of these are worth doing, or if they have tradeoffs or disadvantages that make them undesirable, then I totally understand. Thank you for your time.

**Comment by remy** [comment]
I think actually stating that `main` is being used from the package is an excellent idea (in the hope that it clarifies what's going on to the user). Would you mind opening a new ticket suggesting that? (I'm on my phone and about to go to bed, otherwise I'd quickly do it myself).

And I agree on your `nodemon first second ...` example it's not super clear what's going on - that's one of the edge cases that over the years I've come to the conclusion that there's no single right way to handle it.

**Comment by joshkel** [comment]
@remy Done; see #1997. Thanks again for your help.
