### ISSUE TITLE
State when package.json's main or scripts.start is used

### ISSUE THREAD

**Issue by joshkel** [remy/nodemon#1997]
As discussed in #1996, it would be nice if Nodemon's startup messages included text indicating when it's using the script from package.json's main or scripts.start.

**Comment by paulkre** [comment]
I'm not sure if this is the correct issue, but I've got a problem with this behaviour too. My `package.json` has the "main" field set to "lib/mod.js". When I run `nodemon lib/run.js`, nodemon tries to execute the command `node lib/run.js lib/mod.js` which obviously fails. How is this the intended behaviour? Have I done something wrong?
