### ISSUE TITLE
Error: Cannot find module 'D:\nodemon\bin\nodemon.js'

### ISSUE THREAD

**Issue by SuMiT788** [remy/nodemon#2005]
- Versions:  node@v14.17.6, win32@10.0.19043
- `nodemon -v`: 2.0.16
- Operating system/terminal environment (powershell, gitshell, etc):  powershell
- Using Docker? What image: No
- Command you ran: npm run dev

### Expected behaviour
Nodemon working fine

### Actual behaviour
When 'npm run dev' command is executed, getting 'Error: Cannot find module 'D:\nodemon\bin\nodemon.js'. When tried to run 'nodemon ./src/app.ts', getting ''ts-node' is not recognized as an internal or external command'.

### Steps to reproduce
I am new to TypeScript and was checking how it works, created a simple app.ts file, and added express to listen on port 5000. But when I try to start the server with 'npm run dev' getting 'Error: Cannot find module 'D:\nodemon\bin\nodemon.js'.

{
  "name": "typescript",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node ./dist/app.js",
    "dev": "nodemon ./src/app.ts",
    "build": "tsc -p ."
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.18.1"
  },
  "devDependencies": {
    "@types/express": "^4.17.13",
    "@types/node": "^17.0.31",
    "nodemon": "^2.0.16",
    "ts-node": "^10.7.0",
    "typescript": "^4.6.4"
  }
}

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by DiogoJP202** [comment]
Hello! check your parent folder name - the folder name or any file name should not contain any symbol like %^&*#$ if contains means this kind of error will occur
