### ISSUE TITLE
The token '||' is not a valid statement separator in this version.

### ISSUE THREAD

**Issue by ArmaanTechDeveloper** [remy/nodemon#2007]
nodemon isn't installing on my project
- Operating system/terminal environment (powershell): 
- Versions: latest
- Command you ran: npm install nodemon --save-dev

### Expected behaviour
npm should install nodemon and save it to the dev dependencies

### Actual behaviour
shows the error 

npm ERR! code 1
npm ERR! path C:\Users\Armaan\AppData\Roaming\npm\node_modules\nodemon
npm ERR! command failed
npm ERR! command powershell -c node bin/postinstall || exit 0
npm ERR! At line:1 char:22
npm ERR! + node bin/postinstall || exit 0
npm ERR! +                      ~~
npm ERR! The token '||' is not a valid statement separator in this version.
npm ERR!     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
npm ERR!     + FullyQualifiedErrorId : InvalidEndOfLine

### Steps to reproduce
idk

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.
![image](https://user-images.githubusercontent.com/69575439/167264292-fd4ca4a3-b8d4-4362-9fd9-0a5c692b80b6.png)

**Comment by remy** [comment]
What's your powershell version? (Not sure it'll help, but it help)

**Comment by ArmaanTechDeveloper** [comment]
> What's your powershell version? (Not sure it'll help, but it help)

actually i figured out the issue 
The issue is in the powershell which npm is using by default even if you try to install nodemon from command prompt you get the same error because npm in the background is using powershell inside cmd too 

so i changed the default shell used by npm to command prompt using - "npm config set script-shell cmd"
and then the installation works 
after the installation gets complete i reverb back to the default powershell using - "npm config set script-shell powershell"

For those who are having the same issue i have attached a list of commands in the picture (refer to that and hopefully your issue gets fixed) 
![image](https://user-images.githubusercontent.com/69575439/169260137-579201ab-6111-42c6-9494-328c6670f515.png)
also remy , 
if it can be fixed then try to fix it please ( if you want to generate this error put your command shell to powershell and then try to install it ) powershell version i am using is -  5.1.19041.1645

**Comment by bektigalan** [comment]
i already tried using cmd and powershell, even bash in windows 10 
![image](https://user-images.githubusercontent.com/7407859/189627528-6eecb7a2-4efe-4d60-bab4-a0999710404f.png)
i install it using yarn, problem solved, somehow
