### ISSUE TITLE
Code that ran yesterday is crashing today with output "Killed"

### ISSUE THREAD

**Issue by rstoermer** [remy/nodemon#2017]
- Versions: 
- `nodemon -v`: 2.0.16
- Operating system/terminal environment (powershell, gitshell, etc): Docker Container running in Kubernetes cluster
- Using Docker? What image: node:16-buster
- Command you ran: "npx nodemon ./src/app.ts"

### Expected behaviour

Nodemon starts process 

### Actual behaviour

Code that worked yesterday with nodemon isn't working anymore and just reporting "Killed" in terminal. The container is not crashing instantly, but after 10 - 15 seconds. However the first line in my entry file is never reached, so I assume an error in nodemon. The same code is running without nodemon when doing "node ./dist/app.js" after building the js files.

I am starting via skaffold with a Helm deployment in a Kubernetes cluster...

nodemon.json
```json
{
    "verbose": true,
    "ignore": ["*.json", "node_modules", "/src/types"],
    "signal": "SIGTERM",
    "execMap": {
        "ts": "node --require ts-node/register"
    }
}
```

Waiting for deployments to stabilize...
 - nextor-remote-rene:deployment/data-broker-deployment: waiting for rollout to finish: 1 old replicas are pending termination...
 - nextor-remote-rene:deployment/data-broker-deployment is ready.
Deployments stabilized in 16.661 seconds
Port forwarding service/data-broker-service-clusterip in namespace nextor-remote-rene, remote port 6551 -> http://127.0.0.1:6551
Watching for changes...
[data-broker] [nodemon] 2.0.16
[data-broker] [nodemon] reading config ./nodemon.json
[data-broker] [nodemon] to restart at any time, enter `rs`
[data-broker] [nodemon] or send SIGUSR2 to 18 to restart
[data-broker] [nodemon] ignoring: *.json temp/**/* logs ./node_modules/**/* node_modules_production types/hl7/**/*
[data-broker] [nodemon] watching path(s): *.*
[data-broker] [nodemon] watching extensions: ts,json
[data-broker] [nodemon] starting `ts-node ./src/app.ts`
[data-broker] [nodemon] spawning
[data-broker] [nodemon] child pid: 31
[data-broker] [nodemon] watching 115 files
[data-broker] Killed
[data-broker] [nodemon] app crashed - waiting for file changes before starting...

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by rstoermer** [comment]
Alright, found the error. The memory limit we were setting in Kubernetes was too low. It would be better if nodemon would be a bit more expressive than just saying: "Killed"

**Comment by remy** [comment]
The `killed` message came from your code, not from nodemon. You can see this from your logged output:

```
[data-broker] [nodemon] spawning
[data-broker] [nodemon] child pid: 31
[data-broker] [nodemon] watching 115 files
[data-broker] Killed
[data-broker] [nodemon] app crashed - waiting for file changes before starting...
```

Everything from nodemon is prefixed with `[nodemon]`.
