### ISSUE TITLE
moderate advisory in dependency

### ISSUE THREAD

**Issue by newhouse** [remy/nodemon#2023]
I am on `nodemon` v`2.0.16` and `yarn audit` tells me that there's a vuln in one of the dependencies:

https://github.com/advisories/GHSA-pfrx-2q88-qq97

```sh
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Got allows a redirect to a UNIX socket                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ got                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=11.8.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nodemon                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nodemon > update-notifier > latest-version > package-json >  │
│               │ got                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1075647                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

I have no clue if `update-notifiier` and the rest of the tree-on-down have updated to fix this...but when they do it'd be great if you could update this!

Thanks for the great library!

**Comment by danepowell** [comment]
Here's the problem: https://github.com/yeoman/update-notifier/issues/218

update-notifier needs to update its dependency on latest-version in order to fix this, but it seems somewhat unlikely to happen given the lack of development (last commit over a year ago) and lack of response to similar issues (https://github.com/yeoman/update-notifier/issues/216, https://github.com/yeoman/update-notifier/issues/214)

Seems like the real solution here is https://github.com/remy/nodemon/issues/1961

**Comment by gaborszita** [comment]
I created a pull request for this, it should fix it.

**Comment by remy** [comment]
releasing now.

**Comment by lorand-horvath** [comment]
Just wanted to mention a directly related issue I opened regarding the vulnerability in the `got` package https://github.com/sindresorhus/got/issues/2067

Thanks @gaborszita and @remy !

**Comment by francisdb** [comment]
@remy is there an open related issue/pr we can track?

**Comment by gaborszita** [comment]
> @remy is there an open related issue/pr we can track?

This project plans to drop update-notifier and there is an open issue for it https://github.com/remy/nodemon/issues/1961. I think updates will go there.
