### ISSUE TITLE
nodemon 2.0.16 in windows doesnot restart after changes

### ISSUE THREAD

**Issue by f9rajiv** [remy/nodemon#2025]
- Versions: 
- node- 16.15.1
- `nodemon - 2.0.16
- Operating system/terminal environment (powershell, gitshell, etc): windows/cmd
- Using Docker? What image: no
- Command you ran:

### Expected behaviour
after changes in app.js and saving the file it must restart the changes 
but this doesnot happen and freeze the cmd line

### Actual behaviour
problem area

![Screen Shot 6-23-2022 at 10 08 AM](https://user-images.githubusercontent.com/57870252/175208621-9728c6b7-6282-433c-b490-20ff5f895e28.png)

json file
![image](https://user-images.githubusercontent.com/57870252/175208974-7473b363-2399-4ff4-baba-626b44a2cf18.png)

file directory-may be look like little mess
![image](https://user-images.githubusercontent.com/57870252/175209042-10bd7141-42fa-4ccf-999b-03376e2e52b4.png)

server listen from this file 
![image](https://user-images.githubusercontent.com/57870252/175209689-b5e6de00-b1f8-462d-96f3-edb61487a4b1.png)

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Can you run `DEBUG=nodemon:* nodemon app.js` and share the output after a change to you files is made (ie. when it should restart). That'll help to debug.

**Comment by f9rajiv** [comment]
sorry I cannot get ,Do I need to run [DEBUG=nodemon:* nodemon app.js ](url) in cmd or what ?
as I am beginner I'm completely lost
