### ISSUE TITLE
nodemon 2.0.17 not starting and showing require error

### ISSUE THREAD

**Issue by Rishikant181** [remy/nodemon#2030]
Here is the error shown when I start nodemon

npm WARN exec The following package was not found and will be installed: nodemon@2.0.17
rettiwt-api-1  | [0]
rettiwt-api-1  | [0] 2:40:33 PM - Found 0 errors. Watching for file changes.
rettiwt-api-1  | [1] /root/.npm/_npx/c08057651e53e122/node_modules/nodemon/bin/nodemon.js:15
rettiwt-api-1  | [1]   require('update-notifier')({ pkg }).notify();
rettiwt-api-1  | [1]   ^
rettiwt-api-1  | [1]
rettiwt-api-1  | [1] Error [ERR_REQUIRE_ESM]: require() of ES Module /root/.npm/_npx/c08057651e53e122/node_modules/update-notifier/index.js from /root/.npm/_npx/c08057651e53e122/node_modules/nodemon/bin/nodemon.js not supported.
rettiwt-api-1  | [1] Instead change the require of index.js in /root/.npm/_npx/c08057651e53e122/node_modules/nodemon/bin/nodemon.js to a dynamic import() which is available in all CommonJS modules.
rettiwt-api-1  | [1]     at Object.<anonymous> (/root/.npm/_npx/c08057651e53e122/node_modules/nodemon/bin/nodemon.js:15:3) {
rettiwt-api-1  | [1]   code: 'ERR_REQUIRE_ESM'
rettiwt-api-1  | [1] }
rettiwt-api-1  | [1]
rettiwt-api-1  | [1] Node.js v18.4.0

I am not using a local nodemon installation, but using npx to use it

**Comment by elrumordelaluz** [comment]
Oops, seems that we opened two related on the same issue at the same time :)

Linking here #2031 in case the other details could be useful.

**Comment by caiokawasaki** [comment]
Same here

**Comment by DanSuthWMW** [comment]
Downgrading to nodemon 2.0.14 resolved for me in the meantime

**Comment by remy** [comment]
2.0.18 is available now - goes back to update-notifier@5.x
