### ISSUE TITLE
Nodemon reading from stdin clashes with executed app.

### ISSUE THREAD

**Issue by richburdon** [remy/nodemon#2050]
- Versions: node@v16.14.0, darwin@21.4.0
- `nodemon -v`: 2.0.19
- Operating system/terminal environment (powershell, gitshell, etc): OS/X; iTerm
- Using Docker? What image: No
- Command you ran: `nodemon --exec`

### Expected behaviour

Executed program (custom CLI using `ink`) can consume stdin.
It would be useful to have a command line flag to prevent nodemon from reading from stdin.

### Actual behaviour

```
 ERROR  Raw mode is not supported on the current process.stdin, which Ink uses as input stream by default.
        Read about how to prevent this error on https://github.com/vadimdemedes/ink/#israwmodesupported
```

### Steps to reproduce

N/A

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
You mean it would be nice to have this feature? https://github.com/remy/nodemon/blob/main/doc/cli/options.txt#L16

Yep, way ahead of you...
