### ISSUE TITLE
only  save file and file content is not change,the nodemon restart ?

### ISSUE THREAD

**Issue by Valar103769** [remy/nodemon#2058]
[detail](https://github.com/esbuild-kit/tsx/issues/84)

**Comment by remy** [comment]
@Valar103769 I'm afraid that's not detailed at all. Please provide actual detail on what you're seeing and code to replicate, otherwise no one can (or will) help. Thanks.

**Comment by wlkns** [comment]
I'd guess this is when pressing save (with no actual changes) nodemon triggers a restart - but this is behaviour many developers such as myself want.

**Comment by Valar103769** [comment]
> 


> @Valar103769 I'm afraid that's not detailed at all. Please provide actual detail on what you're seeing and code to replicate, otherwise no one can (or will) help. Thanks.
```
while( `command + s`){the nodemon restart} 
```
it doesn't matter whit code

**Comment by Valar103769** [comment]
> 

why do you want this behavior?

**Comment by Valar103769** [comment]
> I'd guess this is when pressing save (with no actual changes) nodemon triggers a restart - but this is behaviour many developers such as myself want.

why do you want this behavior?

**Comment by wlkns** [comment]
> why do you want this behavior?

Often I watch a single file or directory that I'll make changes outside of, switching back and saving the original file (with no changes made) to trigger the nodemon restart that I'm after.

I'll counter your question — why would you not want this behaviour? Why are you saving a file with no changes?

In my opinion this is not an issue/bug.

**Comment by Valar103769** [comment]
> Why are you saving a file with no changes?

The habit of writing code, hh, if you need to perform a long build task after restart, it will be a waste of time,
now

File changes, trigger watch
The file has not changed trigger the watch
speechless

**Comment by wlkns** [comment]
To counter your reasoning - change your habits?
