### ISSUE TITLE
Nodemon not starting app nor crashing

### ISSUE THREAD

**Issue by jlong5795** [remy/nodemon#2065]
- Versions: node@{process.version}@21.6.0
- `nodemon -v`: 2.0.20
- Operating system/terminal environment (powershell, gitshell, etc): MacOS Monterey v12.6 / iterm2
- Using Docker? What image: yes: FROM --platform=linux/amd64 node:16.3.0
- Command you ran: "dev": "nodemon -e ts  --exec \"npm run buildAndRun\""  ---> "buildAndRun": "tsc && node dist/index.js"

### Expected behaviour
Expect nodemon to start node application and once loaded see a terminal readout that server is running listing the port

### Actual behaviour
nodemon logs out that it's starting, names the command, then does nothing beyond that. No crash, no error, no restart

### Steps to reproduce
Behavior is the same when run as part of the docker compose command and on the local machine. Application does not hang so on Intel MacBook

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by cvvkshcv** [comment]
"dev": "nodemon -e ts --exec "npm run buildAndRun"", <-- The error can be because of " double quotes you used,, try ' single quote "nodemon -e ts --exec 'npm run buildAndRun'"
