### ISSUE TITLE
Website/index.js || Website Footer and UI Changing

### ISSUE THREAD

**Issue by Shubhamjain287** [remy/nodemon#2070]
I would like to contribute in nodemon website where i can improve the UI of [https://nodemon.io/](url) Website and Change the Footer so its Looks Good With Same Functionaility but different User Interface / User Experience...
Kindly Assign this Issue to me ...

**Comment by remy** [comment]
What UI?

But sure, feel free to share any mocks here if you like.

**Comment by adhilroshan** [comment]
i would like to work on this
