### ISSUE TITLE
Is `nodemon` will be replaced by Node.js v18.11.0?

### ISSUE THREAD

**Issue by fzn0x** [remy/nodemon#2072]
Hi @remy, is nodemon will be replaced by Node v18.11.0? AFAIK most people using nodemon only for watching changes from the main file. If yes, we need to announce it on the Nodemon README anyways. If no...

Is there still any benefits from nodemon when Node v18.11.0 [--watch](https://nodejs.org/dist/latest-v18.x/docs/api/cli.html#--watch) flag is released (except from someone that is using the previous versions of Node from v18.11.0)?

**Comment by remy** [comment]
No, node's native watch won't replace nodemon. Nodemon has a much broader use case. Things like watching TS projects, or reloading with `--inspect` or using python and not node...the list goes on. 

Sorry, but that was a bit of a naive question.

**Comment by fzn0x** [comment]
> No, node's native watch won't replace nodemon. Nodemon has a much broader use case. Things like watching TS projects, or reloading with `--inspect` or using python and not node...the list goes on.
> 
> Sorry, but that was a bit of a naive question.

Thanks for the answer!

**Comment by fzn0x** [comment]
naive questions challenge assumptions and allow you to build models of systems. I'm just questioning what people questioning right now around me, your answer should help.

**Comment by fzn0x** [comment]
> No, node's native watch won't replace nodemon. Nodemon has a much broader use case. Things like watching TS projects, or reloading with `--inspect` or using python and not node...the list goes on.
> 
> Sorry, but that was a bit of a naive question.

Naive questions challenge assumptions and allow you to build models of systems. I'm just questioning what people questioning right now around me, your answer should help.

Sorry if that is a 'bad' naive question.

Reference around me: https://pawelgrzybek.com/til-node-v18-11-0-comes-with-a-watch-mode-so-you-might-not-need-nodemon/

**Comment by rafipiccolo** [comment]
i did some tryings with node 19 and the --watch options.
i was only using nodemon to watch my main script and all of it's imported files.
For my usecase, i will indeed delete nodemon as it is completely redondant.

if people expect to watch non js/imported files : translation files, images, ... or anything else. 
node --watch doesnt support that and nodemod is still needed

**Comment by sgoodluck** [comment]
> Sorry, but that was a bit of a naive question.

The first half of your comment was helpful; this part is unprofessional.

**Comment by erfanium** [comment]
`--watch` is working well with typescript project
