### ISSUE TITLE
Not restarting after file creation in watch directory

### ISSUE THREAD

**Issue by aboe026** [remy/nodemon#2074]
- Versions: node@v16.13.2, win32@10.0.22621 
- `nodemon -v`: 2.0.19
- Operating system/terminal environment (powershell, gitshell, etc): Git Bash for Windows
- Using Docker? What image: No
- Command you ran: nodemon --watch build --exec 'yarn node build/src/index.js'

### Expected behaviour
Nodemon should restart when a file is created in the watch directory

### Actual behaviour
Nodemong does not restart when files are created in the watch directory

### Steps to reproduce
See this minimum reproduceable scenario repository: https://github.com/aboe026/nodemon-file-creation-restart 

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by aboe026** [comment]
This problem is still persisting

**Comment by remy** [comment]
It doesn't look like anyone in the community wants to pick this up, and I'm not particularly into it as a feature. 

I'll try to get around to adding it to the docs (though I have a feeling you can pass chokidar config, which might work as work around - feel free to check the config too) 👍
