### ISSUE TITLE
install nodemon in windows 11

### ISSUE THREAD

**Issue by pedramjazayeri** [remy/nodemon#2077]
Hi,
How do I can install nodemon in anaconda(windows 11)?
thx

**Comment by WWSK** [comment]
Тоже не работает.
![image](https://user-images.githubusercontent.com/23173147/199079961-dad23493-9fe9-47e2-96c9-50c5120623c2.png)

**Comment by remy** [comment]
`npm install nodemon` or `npm install -g nodemon`.

If these are erroring, like @WWSK's screenshots, then it's worth raising an issue with npm - as that process handles the actual install process.

**Comment by WWSK** [comment]
Oh yeah ! I had to reboot to update the system.
