### ISSUE TITLE
Global .nodemonignore file

### ISSUE THREAD

**Issue by mikemorris** [remy/nodemon#208]
The biggest impediment to including nodemon in my daily workflow is the lack of support for a global `.nodemonignore` file in the user's home directory. I tend to work on many different projects, and using command line arguments or configuring individual `.nodemonignore` files just to exclude files in the `.git` directory or temporary `.swp` and `.swo` files created by `vim` is a bit of a hassle.

**Comment by felixsanz** [comment]
@remy what do you think about .nodemonrc and .nodemonignore now? it is possible?

**Comment by remy** [comment]
@felixsanz the nodemon.json landed a long while ago, which supports both local and global settings.

**Comment by felixsanz** [comment]
@remy yea i know, i was proposing them for consistency. usually config files start with a dot and end with rc. Would be nice to hide it from the folder actually. But i think this is a hard thing to change now. Thanks for input!

**Comment by remy** [comment]
Ah, gotcha. Yeah, I appreciate that there's a lot of dotfiles. I can't remember quite why I didn't go down that path - I think it was because I'd never seen a hidden `.json` file (though I'm sure they exist).
