### ISSUE TITLE
need IPv6 Address over nodemon(Wireless LAN adapter Wi-Fi:)

### ISSUE THREAD

**Issue by bcapd7363q** [remy/nodemon#2080]
- Versions: 19.0.1
- `nodemon -v`:2.0.20
- Operating system/terminal environment (powershell, gitshell, etc): dev file kali linux
- Using Docker? What image: kali
- Command you ran: cdrom bootx64.efi

### Expected behaviour
You can now view predator-sense in the browser.  
   Local:            http://localhost:3000        
   On Your Network:  http://192.168.1.3:3000 
   IPv6 Address. . . . . . . . . . . : 2401:4900:1c0f:b763:18c9:44cf:5b41:1f6c
   Temporary IPv6 Address. . . . . . : 2401:4900:1c0f:b763:8035:406e:958f:e5e2
   Link-local IPv6 Address . . . . . : fe80::18c9:44cf:5b41:1f6c%13
   IPv4 Address. . . . . . . . . . . : 192.168.1.3
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : fe80::1%13
### Actual behaviour
You can now view predator-sense in the browser.  
  Local:            http://localhost:3000        
  On Your Network:  http://192.168.1.3:3000 

### Steps to reproduce
dont know yet please check vue over laravel on docker and get the nessary help .
please check https://github.com/bcapd7363q/jupiter/tree/location . where i need your help over efi file placed at dev folder

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Sorry, but this isn't related to nodemon. 

You'll get the same result with node. 

I recommend posting question to whatever framework you're using.
