### ISSUE TITLE
Compatible with latest mac os?

### ISSUE THREAD

**Issue by JrodMc** [remy/nodemon#2087]
- Versions: 
- `nodemon -v`:
- Operating system/terminal environment (powershell, gitshell, etc): 
- Using Docker? What image: 
- Command you ran:
node v = 18.12.1
npm v = 8.19.2
mac os Ventura 13
also tried on mac os monterey 12.6.1

### Expected behaviour
npm install nodemon installs nodemon

### Actual behaviour
error 13...might need permissions

worked with Apple support.  Can install other software, problem is isolated to nodemon
tried using sudo for install.  Appeared to work but when tried running the nodemon app crashed
### Steps to reproduce

Is nodemon compatible with mac os??

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Firstly test if you can install other software in the same way. 

Secondly the install process is npm and nothing to do with nodemon itself, so I suggest you raise an issue there. 

If it didn't run or errored under the new OS, then that would be nodemon. The installation is taken care of by npm.

**Comment by JrodMc** [comment]
I can install other things in the same manner.  Problem only with nodemon.  Tried on another mac computer and had same issue with same Error 13.
I will try reaching out to npm
