### ISSUE TITLE
Watching changes in relative folders using glob fails

### ISSUE THREAD

**Issue by atlanteh** [remy/nodemon#2093]
- Versions: node@v16.14.0, linux@5.10.102.1-microsoft-standard-WSL2
- `nodemon -v`:  2.0.20
- Operating system/terminal environment (powershell, gitshell, etc): powershell
- Using Docker? What image:  No
- Command you ran:
```nodemon``
```
///nodemon.json
{
    "watch": [
        "src",
        ".env",
        "../pr-*/dist"
    ],
    "ext": "js,ts,json",
    "ignore": [
        "src/**/*.{spec,test}.ts"
    ],
    "exec": "ts-node --transpile-only src/index.ts"
}
```

### Expected behaviour
Rebuild of pr-library triggers change

### Actual behaviour
Nodemon doesn't detect this change

### Alternatives
In watch array stating each one of the folders explicitly `.../pr-library/dist`

**Comment by armediagroup** [comment]
@remy this is still an issue for us

**Comment by atlanteh** [comment]
Still an issue @remy

**Comment by atlanteh** [comment]
Still an issue @remy is there a solution to this?

**Comment by atlanteh** [comment]
Still iasue
