### ISSUE TITLE
Killing the terminal running nodemon doesn't kill the running node process

### ISSUE THREAD

**Issue by jeengbe** [remy/nodemon#2095]
- Versions: `node@v18.12.0, linux@5.15.79.1-microsoft-standard-WSL2`
- nodemon -v: `2.0.20`
- Operating system (powershell, gitshell, etc): `Ubuntu 22.04.1 LTS (WSL 2)`
- Terminal environment: `VSCode 1.75.0-insider (Terminal): /bin/bash`
- Command you ran: `nodemon index.js`

### Steps to reproduce

Using the simplest alive-check:
```js
const fs = require("fs");

setInterval(() => {
  fs.writeFileSync("log.txt", new Date().toUTCString());
}, 1000);
```

When killing the terminal via the (see below) kill terminal button, the node process continues to run and happily prints the current date into the file even though the terminal is long gone.

This is not the case when running `node index.js` directly and killing the terminal.

![image](https://user-images.githubusercontent.com/51749023/212532393-84785149-9daa-4672-9e65-a5c8ccbeb78a.png)

### Additional info

Running `ps -e | grep node`
before kill:
```
26288 pts/4    00:00:00 node
26301 pts/4    00:00:00 node
```
after kill:
```
26288 ?        00:00:00 node
26514 ?        00:00:00 node
```

**Comment by remy** [comment]
I'm pretty sure that's unavoidable - the terminal nuking doesn't allow time for nodemon to tidy the sub process - so it's not a clean exit. 

I genuinely don't think this can be avoided (which is why I'm closing the issue) - I'd be happy to add the FAQ stating this. Sorry I can't be more useful.
