### ISSUE TITLE
vscode launch config

### ISSUE THREAD

**Issue by sravanthbaratam** [remy/nodemon#2097]
- `nodemon -v`: 2.0.20
- `node -v`: 16.15.0
- Operating system/terminal environment: 
- Using Docker? What image:  no
- Command you ran:
launch.config
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}\\server.js",
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "runtimeExecutable": "${workspaceFolder}/node_modules/nodemon/bin/nodemon.js",
        }
    ]
}
```

### Expected behaviour
start the session

### Actual behaviour
open the server.js file instead.

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by sravanthbaratam** [comment]
The issue might not be related to nodemon directly but posting to find a solution for launching in vscode. If it is completely not relevant please close the issue. Thanks.

**Comment by atlanteh** [comment]
You should probably use type = `node-terminal`. I'm using nodemon using package.json script and it works great for me. I'm guessing that using nodemon should also work in this case

```
{
            "command": "yarn start:dev",
            "name": "Debug Server",
            "request": "launch",
            "type": "node-terminal"
}
```
