### ISSUE TITLE
Should not able to install nodemon globally

### ISSUE THREAD

**Issue by santoshmanaguli** [remy/nodemon#2109]
1. I do have nodemon installed in my package.json file but still its does not recognize it and gives an error: 'nodemon: command not found'
(I did only npm install nodemon)

2. After that I did try npm install --save-dev nodemon and the changes that reflected in my package.json was <"devDependencies": {"nodemon": "^2.0.21"}> and still it gave me same above error

3. Finally I install it globally and it worked.

But my question is when I do have nodemon installed in my package.json file then I should not be allowed to install it globally and It should recognize the dependency

Correct me if I am wrong, or if I am missing somethings

- `nodemon -v`: 2.0.21
- `node -v`: 14.21.3
- Operating system/terminal environment: Ubuntu 22.04.2 LTS
- Using Docker? What image: No
- Command you ran: nodemon <application file>

**Comment by remy** [comment]
How are you running the local dependancy?

**Comment by santoshmanaguli** [comment]
nodemon <file name>

**Comment by santoshmanaguli** [comment]
`nodemon <file_name>`
