### ISSUE TITLE
Creating or Deleing file/directory causes nodemon to reload even though its ignored

### ISSUE THREAD

**Issue by LiamKarlMitchell** [remy/nodemon#211]
So I have this in my .nodemon ignore
/scripts/*

And in the /scripts/ directory when I create,delete a file nodemon reloads.
When I just edit and save a file nodemon does not reload.

It is desirable that nodemon does not reload as this scripts directory can have files created at runtime and executed.

Did I do something wrong with my ignore file?
I am using nodemon v0.7.10 and node v0.10.16 and Windows 7

Apart from this nodemon has been working great for me.

**Comment by mmaalo** [comment]
I'm having this exact same problem, as subfolders are created or deleted nodemon restarts even when I have ignored the parent folder in nodemon.json or package.json.
