### ISSUE TITLE
Error: Unknown or unexpected option: --trace-warnings

### ISSUE THREAD

**Issue by jzombie** [remy/nodemon#2112]
- Versions: 
node@v16.18.1, linux@5.19.0-40-generic
- `nodemon -v`:
- 2.0.22
- Operating system/terminal environment (powershell, gitshell, etc): 
VSCode Terminal /  Bash / Ubuntu
- Using Docker? What image: 
- Command you ran:

```
nodemon --trace-warnings src/index.ts
```

### Expected behaviour

Debug w/ warning traces.

### Actual behaviour

Error: Unknown or unexpected option: --trace-warnings

### Steps to reproduce

nodemon --trace-warnings src/index.ts

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by madtrick** [comment]
For the record, this keeps happening. I just ran into it with  `--trace-uncaught`
