### ISSUE TITLE
How to watch for package changes when node_modules is huge?

### ISSUE THREAD

**Issue by skalinkin** [remy/nodemon#2113]
When I set   "ignoreRoot": [".git"] in nodemon.js

I am getting the following error 

[nodemon] Internal watch failed: ENOSPC: System limit for number of file watchers reached, watch '/usr/local/upgrade-manager/node_modules/@babel/types/lib/definitions'

I do not really need to watch whole node_modules. I need to watch my company scope packages.

How to configure nodemon to watch particular scope dir in node_modules?

**Comment by ValentinGurkov** [comment]
I'm facing something similar, I only want to watch for changes in my workspace dependencies in `node_modules`.
Unfortunately, I can't offer good solutions. 
You can modify the `watch` array to include only workspace packages using their real location in the repo, not in the `node_modules` folder.

Or modify `ignoreRoort` to exclude the `node_modules` except a few folders (I haven't tested this yet) like ``node_modules/!(workspace-package)/**/*``

What is even worse is that these solutions are not at all flexible. If we could configure `nodemon` with a `.js` file, it might be possible to have this done in a bit more extensible way (like reading your workspace dependencies from `package.json`).

**Comment by remy** [comment]
@ValentinGurkov you can require in nodemon as a module and control what it's watching.

The bottom line is that watching a huge number of files isn't viable with nodemon and something that's so much of an edge case that I can't support.

Though as I said, you can certainly require _in_ nodemon, or possibly attempt it with node's native file watch and reload - not sure it would be any better though…
