### ISSUE TITLE
Security advice semver

### ISSUE THREAD

**Issue by NormandoHall** [remy/nodemon#2119]
https://github.com/advisories/GHSA-c2qf-rxjj-qqgw

```
nodemon  1.4.10-alpha.1 - 1.4.10-alpha.3 || >=1.14.10
  Depends on vulnerable versions of semver
  Depends on vulnerable versions of simple-update-notifier
```

**Comment by wellwelwel** [comment]
A lot of packages use `semver` in versions earlier than `7.5.2`.

I resolved it temporally by:

### YARN
> package.json
```json
"resolutions": {
  "**/semver": "^7.5.2"
}

```
- Then
```sh
rm -f "yarn.lock"
yarn install
```

- Checking
```sh
yarn audit
```

---

### NPM
> package.json
```json
"resolutions": {
  "semver": "7.5.2"
}
```

- Then
```sh
npm i -D npm-force-resolutions
npx npm-force-resolutions
```

- Checking
```sh
npm audit
```

**Comment by wellwelwel** [comment]
@remy

Currently, the `nodemon` supports the NodeJS starting at version **8**:
https://github.com/remy/nodemon/blob/6787871d521eef65c2bc7a62234e3736bf6fcc35/package.json#L11-L13

---

After the security patch by `semver` in `^7.5.2`, the [support starts from Node 10](https://github.com/npm/node-semver/blob/7fdf1ef223826b428d7f8aaf906e9eeefa9469f9/package.json#L47-L49).

> It may be necessary to release a major version due to breaking changes.

**Comment by fluentmoheshwar** [comment]
> A lot of packages use `semver` in versions earlier than `7.5.2`.
> 
> I solved it temporally by:
> 
> ### YARN
> > package.json
> 
> ```json
> "resolutions": {
>   "**/semver": "^7.5.2"
> }
> ```
> 
> * Then
> 
> ```shell
> yarn install
> ```
> 
> * Checking
> 
> ```shell
> yarn audit
> ```
> 
> ### NPM
> > package.json
> 
> ```json
> "resolutions": {
>   "semver": "7.5.2"
> }
> ```
> 
> * Then
> 
> ```shell
> npm i -D npm-force-resolutions
> npx npm-force-resolutions
> ```
> 
> * Checking
> 
> ```shell
> npm audit
> ```

you could also use (doesn't require `npm-force-resolutions`): 

```json
"overrides": {
        "semver": "7.5.2"
 }
 ```

**Comment by joaomoreno** [comment]
A better approach:

```json
	"overrides": {
		"nodemon": {
			"simple-update-notifier": {
				"semver": "^7.5.2"
			}
		}
	}
```

**Comment by zang3tsu88** [comment]
> A better approach:
> 
> ```json
> 	"overrides": {
> 		"nodemon": {
> 			"simple-update-notifier": {
> 				"semver": "^7.5.2"
> 			}
> 		}
> 	}
> ```

Thanks, but this one doesnt fix the issue. Out of 3 moderate vulnerabilities it leaves 2. 
The previous one helped.
