### ISSUE TITLE
[3.0] *.ts files watch stopped to work by default

### ISSUE THREAD

**Issue by rentalhost** [remy/nodemon#2124]
- Versions: 3.0
- Operating system/terminal environment (powershell, gitshell, etc): Powershell
- Using Docker? What image: No

**Comment by remy** [comment]
Thanks. I suspect I know what the regression is. I'll try to get it out at the start of the week. 

Is it a simple .ts file that doesn't work?

**Comment by rentalhost** [comment]
Yes, I just running like: `nodemon src/index.ts serve` before, it still works, but when I change `.ts` files it is just ignored. I believe that it must be added to: 

https://github.com/remy/nodemon/blob/f219dccbf0ab9a48a3f84edb75d620e3a61a9f36/lib/config/defaults.js#L26

**Comment by remy** [comment]
My feeling is that the line needs to be removed.

I did test it with the listed extensions but didn't test with .ts (which is
picking up the extension from the execMap).

**Comment by remy** [comment]
Fix is going up now.
