### ISSUE TITLE
'nodemon' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by AshisheKumar** [remy/nodemon#2126]
- Versions: 
- `nodemon -v`:
- Operating system/terminal environment (powershell, gitshell, etc): 
- Using Docker? What image: 
- Command you ran:

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by mvaibhav77** [comment]
Hi @AshisheKumar,

Can you please provide a little more information of what command your ran and what errors are you facing. It is difficult to understand your situation if you do not provide any information.

I'll get back to you after you provide necessary code and errors in the issue.

**Comment by Adidem23** [comment]
Which Operating System you are using . If you are using Windows then You have to chnage to change your security settings in powershell after that nodemon will work

**Comment by Dani-ctrl-n** [comment]
Hey people, when I try to run to nodemon it tells me that the command in not found, and when I try to install it globally it says "A complete log of this run can be found in: ...." it only works when I install it using npm i --save-dev nodemon. I want to use it globally, any help ?

**Comment by donoftime2018** [comment]
Did you check if nodemon was installed to package.json/package-lock.json? Try running npm i nodemon where your Dockerfiles are located at and recreate the Docker images.

**Comment by remy** [comment]
I think @AshisheKumar has left the building - thanks others for trying to help and get more information. I've seen people have trouble previously but it's always been windows and some funky set up.

Going to close. Hopefully someone can be find the "definitive" solution to this (if you search closed issues, you'll see this again). If we do find the answer, please send me a PR into the FAQ 🙏
