### ISSUE TITLE
V2 to V3 Migration

### ISSUE THREAD

**Issue by BarishSarac** [remy/nodemon#2130]
Hello,

I have nodemon@2.0.22 installed in my package.json and need to upgrade to nodemon@3.0.0 to address security vulnerability per snyk. Is there any breaking update for nodemon for this migration that everyone should know?

**Comment by hochoy** [comment]
As per the v3 release changelog, the only breaking change is that the tests no longer cover Node 8. 

https://github.com/remy/nodemon/releases
![Screen Shot 2023-09-05 at 2 13 58 PM](https://github.com/remy/nodemon/assets/12564636/a4085f88-1f4f-4297-828a-e8fd7ce3c1cb)
