### ISSUE TITLE
When I Use Nodemailer to send rest password to email the nodemailer crashed app server and the server are down but the message send 

### ISSUE THREAD

**Issue by alanbarznji** [remy/nodemon#2132]
these is my send function const nodemailer = require("nodemailer"); const SendEmail = async (get) => {   const transport = nodemailer.createTransport({     service: "gmail",     host: process.env.PROCESS_HOST,     port: process.env.PROCESS_PORT,     secure: true,     requireTLS: true,     auth: {       user: process.env.PROCESS_EMAIL,       pass: process.env.PROCESS_PASSWORD,     },     tls: {       // do not fail on invalid certs       rejectUnauthorized: false,     },   });   const mailOpts ={     from: "degrees <email>",     to: get.email,     subject: get.subject,     text: get.message,   };       await transport.sendMail(mailOpts,(error, info) => {   if (error) {     console.error('Error sending email:', error);     window.location.reload(true);   } else {     console.log('Email sent successfully:', info.response);   } })  console.log(mailOpts,"kaka"); }; module.exports = SendEmail;  

and these my hundle post
if(req.body.email){  try{
    SendEmail({
      email: user.email,
      subject: "Reset your password",
      message: `Hello ${user.name},\n You have requested a password reset.\n Your Code is :${resetCode}\n Please use it within the next`,
    });  
  } 
   catch (error) {
        user.resetCode = undefined;
        user.expires = undefined;
        user.isVerified = undefined; 
           await user.save();
           return next(new ApiError("There is an error in sending email", 500));
    }}

**Comment by abhishektiwari47** [comment]
Hi can i work on this?

**Comment by remy** [comment]
I'm not even sure this is actually a nodemon issue, seems specific to nodemailer (literally doesn't mention nodemon in replication details).

Happy to reopen issue if there's replication details.
