### ISSUE TITLE
Adding copy button to the code given on main website

### ISSUE THREAD

**Issue by sarmadhamdani02** [remy/nodemon#2134]
### Expected behavior
On the main [website](https://nodemon.io/), on the installation code, we can add a copy button. 
So that, the user will simply click on the button and the installation code will automatically be copied to the clipboard. Or, te other possible thing we can do is that the user can simply click all over that section (where the code is) and the code will be copied.

### Actual behavior
Right now there is no copy button.
![image](https://github.com/remy/nodemon/assets/111639663/725724eb-0b07-46ce-ab43-9b0662532282)

### Steps to reproduce
We can simply use some CSS and JS to add this feature.

Kindly, let me know if I can start working on it.
Also, please let me know will this issue be accepted in HacktoberFest.

Regards.

**Comment by vibh1103** [comment]
Hi @sarmadhamdani02 ,
can you assign this task to me and also add the tag HacktoberFest ?

**Comment by subhranil002** [comment]
Hey! @remy ... Can you please assign this task to me ?

**Comment by sarmadhamdani02** [comment]
Hello everyone, I want to apologize for any confusion. I submitted that issue with the hope of being assigned to work on it. 🙏🙂

**Comment by remy** [comment]
Unwanted, sorry. These are features for the sake of features.
