### ISSUE TITLE
⭐ [FEATURE REQUEST] : Add Scroll to Top Button to NODEMON Webpage

### ISSUE THREAD

**Issue by subhranil002** [remy/nodemon#2135]
### Overview:
I noticed that the nodemon website currently lacks a "Scroll to Top" button, which can significantly enhance user experience. This button allows users to easily return to the top of the page without the need to manually scroll, providing a smoother navigation experience.

### Steps To Resolve:
- Make Scroll to Top button using HTML & CSS
- Stick it to it's right place using CSS
- use a small script of JS to make it functional

### Visual Explanation:
![Screenshot 2023-09-28 161459](https://github.com/remy/nodemon/assets/106914208/2ff06934-d495-455e-bec8-752539440907)

**Comment by subhranil002** [comment]
Hey! @remy ... Can you please assign me the task ?

**Comment by zaidiyazdan** [comment]
Hii Can i work on it?

**Comment by remy** [comment]
Sorry, but this is unwanted. There's a scroll bar on every single window that allows user to scroll up, let alone mouse actions etc. 

Adding a button is just bad ux.
