### ISSUE TITLE
An error "Error: watch ENOSPC"

### ISSUE THREAD

**Issue by jamlfy** [remy/nodemon#214]
``` console
20 Oct 16:40:37 - [nodemon] v0.7.10
20 Oct 16:40:37 - [nodemon] to restart at any time, enter `rs`
20 Oct 16:40:37 - [nodemon] watching: /my/proyect/server
20 Oct 16:40:37 - [nodemon] exception in nodemon killing node
Error: watch ENOSPC
    at errnoException (fs.js:1019:11)
    at FSWatcher.start (fs.js:1051:11)
    at Object.fs.watch (fs.js:1076:11)
    at Object.watchFileChecker.check (/usr/lib/node_modules/nodemon/nodemon.js:160:6)
    at ready (/usr/lib/node_modules/nodemon/nodemon.js:49:22)
    at /usr/lib/node_modules/nodemon/nodemon.js:63:11
    at ChildProcess.exithandler (child_process.js:641:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
20 Oct 16:40:37 - [nodemon] reading ignore list
20 Oct 16:40:37 - [nodemon] exception in nodemon killing node
Error: watch ENOSPC
    at errnoException (fs.js:1019:11)
    at FSWatcher.start (fs.js:1051:11)
    at fs.watch (fs.js:1076:11)
    at checkTimer (/usr/lib/node_modules/nodemon/nodemon.js:467:27)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by ahnbizcad** [comment]
I've fixed this with this command https://github.com/ember-cli/ember-cli/issues/1240#issuecomment-47855317

but is updating the package the recommended way?

I'm wondering why it got like this in the first place. I'm using node version manager with 
node 0.12.0
npm 2.7.0
ember 0.2.0

**Comment by jkarttunen** [comment]
@ahnbizcad  
Maybe because of 
https://github.com/joyent/node/wiki/API-changes-between-v0.10-and-v0.12#resource-management  ?

**Comment by uttampanara** [comment]
>The system has a limit to how many files can be watched by a user. You can run out of watches pretty quickly if you have Grunt running with other programs like Dropbox.

# The post suggest running this to increase the number of watches that are available.

    echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

**Comment by wesleycoder** [comment]
I'm having this issue with `"nodemon": "^1.4.1"` and `"node": "0.12.7"` :disappointed:

**Comment by remy** [comment]
Please try with #625

**Comment by wesleycoder** [comment]
Tried with `alpha` but still getting `ENOSPC`...
My `sysctl.conf` has `fs.inotify.max_user_watches=10000`.
If I change it to `524288` it works, but in my "dev-server" I'll not able to change it.

**Comment by remy** [comment]
How many files are you trying to watch? i.e. how many are under your
working directory?

**Comment by wesleycoder** [comment]
Not many, 30 at max.
But i think nodemon is trying to watch `node_modules` at the root of the project.
Below is the config passed to nodemon (I'm using it as a node module):
```
nodemon({
	script: 'server/server.js',
	watch: [
		'server/',
		'common/'
	],
	ext: 'js json coffee'
});
```
the server folder has:
7 coffee files
5 json files
and the common folder has just 1 json file...

**Comment by remy** [comment]
Yeah...so run `find . | wc -l` and what does that number give you? Though, it's supposed to ignore `node_modules` by default, it's possible it's not being taken into consideration.

**Comment by wesleycoder** [comment]
Running `find . | wc -l` on the root of the project gives me `18266` but when I remove `node_modules` and `bower_components` gives just  `320`.

**Comment by remy** [comment]
Okay, so I think that the watch *is* including the `node_modules` - this is part of the #625 refactor and needs to be fixed.

**Comment by remy** [comment]
@wesleycoder can you try with the latest `nodemon@dev` (it should be version `1.5.0-alpha4`) and run with `DEBUG=nodemon <your normal nodemon command>` then paste up the full output.

**Comment by wesleycoder** [comment]
Whoa!
It works!
No errors!
Thanks!

**Comment by ankibalyan** [comment]
This might be because of your system reach out of user can watch files. you can use the following command line in ubuntu 
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`
or try
`npm dedupe`

Ref to [this stackoverflow](http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc)

**Comment by ikrum** [comment]
@ankibalyan  
@uttampanara 

it works !

echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

**Comment by rafaelfvalim** [comment]
works for me too !
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

**Comment by mouthzipper** [comment]
Same here ! :+1: 
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

**Comment by meghjoshi** [comment]
Run this command

`echo fs.inotify.max_user_watches=582222 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

**Comment by ahmdsolmn** [comment]
Another possible solution is to add a `nodemon.json` configuration file in your root folder and specify ignore patterns for example:
`nodemon.json`
```
{
  "ignore": [
    "*.test.js", 
    "dist/*"
  ]
}
```
- Note that by default `.git`, `node_modules`, `bower_components`, `.nyc_output`, `coverage` and `.sass-cache` are ignored so you don't need to add them to your configuration.

**Comment by rayfoss** [comment]
The fs notify trick doesn't seem to work on a docker container... at least not Alpine 3.8, I get the same ENOSPC error. It's becoming more important as tools get deprecated and we still need to maintain legacy products
