### ISSUE TITLE
Workflows failing - not even getting to tests…

### ISSUE THREAD

**Issue by remy** [remy/nodemon#2147]
I've no idea why this fails - it used to work, but now, goodness knows why, it just doesn't: https://github.com/remy/nodemon/actions/runs/7063972871/job/19231053266

**Comment by ayatweb** [comment]
npm run-script
Lifecycle scripts included in nodemon@0.0.0-development:
  test
    npm run lint && npm run spec

available via `npm run-script`:
  commitmsg
    commitlint -e
  coverage
    istanbul cover _mocha -- --timeout 30000 --ui bdd --reporter list test/**/*.test.js
  lint
    eslint lib/**/*.js
  spec
    for FILE in test/**/*.test.js; do echo $FILE; TEST=1 mocha --exit --timeout 30000 $FILE; if [ $? -ne 0 ]; then exit 1; fi; sleep 1; done
  postspec
    npm run clean
  clean
    rm -rf test/fixtures/test*.js test/fixtures/test*.md
  web
    node web
  semantic-release
    semantic-release
  prepush
    npm run lint
  killall
    ps auxww | grep node | grep -v grep | awk '{ print $2 }' | xargs kill -9
