### ISSUE TITLE
 I need some assistance. it‘s not a bug but  I didn't find the discussion tag. So I have to raise a question as an issue:does nodemon support running ts files?

### ISSUE THREAD

**Issue by Henrycheheng** [remy/nodemon#2148]
i remember a time when nodemon could run ts files,but today i use pnpm init a project, and tsc --init, and then execute an index.ts demo error as follows, how can I run ts file in nodemon
![image](https://github.com/remy/nodemon/assets/48849602/7aef3a95-b0f5-47a4-b438-6d023914d0af)

**Comment by Henrycheheng** [comment]
The dependencies and configurations are shown below
![image](https://github.com/remy/nodemon/assets/48849602/3be2821c-76ca-4950-a948-ee74ea8aa2c5)

**Comment by Henrycheheng** [comment]
The observation I made was that the node code failed to validate the .ts file, resulting in an error being thrown.
![image](https://github.com/remy/nodemon/assets/48849602/005221e3-91fc-40d3-9bbe-0435efbe2130)

**Comment by remy** [comment]
Not sure if this is nodemon or something else (I don't regularly use TS and when I do, it's typically with Deno, so I don't have all the tooling to mess with). 

The file you've included a screenshot at the end, that's not from nodemon is it? 

Not sure if this a documentation issue or something else can be done… happy to take advice.

**Comment by Henrycheheng** [comment]
Thank you for your reply. My last screenshot is indeed not an error caused by nodemon. In fact, node itself does not support ts files under esm. Thank you very much for your advice, I will give deno a try. Thank you again for your help，I have no more questions and I will close this issue soon.
