### ISSUE TITLE
Nodemon support for native .env file loading

### ISSUE THREAD

**Issue by marcesdan** [remy/nodemon#2153]
Node.js 20 introduced native support for loading environment variables from .env files. This eliminates the need to use an external module like dotenv.

However, Nodemon does not seem to take advantage of this feature. To use an .env file with Nodemon, developers must set the NODE_ENV_FILE environment or use the dotenv module.

Is there any way to specify the environment file for Nodemon without using an external configuration?

Something like 

`"dev": "nodemon src/index.ts --env-file=.env`

**Comment by CharlyTalavera** [comment]
Hi! Does any one know how to accomplish this?

**Comment by remy** [comment]
@marcesdan _how_ does node 20 take advantage of this? Is there a command line arg? If there is then it can live along side the "manual" support that nodemon provides (remember that nodemon provides backward support **as far back** as it can go, and not just for latest node versions).

**Comment by remy** [comment]
Sorry, I forgot that nodemon doesn't add dotenv by default and this (what you say doesn't work) does actually work:

```
$ cat index.js
console.log(process.env.USERNAME);
console.log(process.env.DOES_THIS_WORK);

$ node index.js
undefined
undefined

$ nodemon --env-file=.env index.js
[nodemon] 3.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node --env-file=.env index.js`
nodemon
yes
[nodemon] clean exit - waiting for changes before restart
^C%

$ cat .env
USERNAME=nodemon
DOES_THIS_WORK=yes
```

Node that node options need to go before filenames are slurped.

**Comment by thelements** [comment]
@remy How to supply same argument using typescript.
Seems for .js it works, for .ts it breaks.

example running: `nodemon --env-file=.env.local index.ts`
throws > 

`Error: Unknown or unexpected option: --env-file`

**Comment by remy** [comment]
You're asking me how typescript works... which I can't tell you because I don't use TypeScript. 

Remove nodemon from your process and repeat using the flag, or whatever you like. Do you still get the error? If you do, it's nothing to do with nodemon.

**Comment by thelements** [comment]
> mon from your process and repeat using the flag, or whatever you like. Do you still get the error? If you do, it's nothing to do with nodemon.

yeah, yup same thing without nodemon works.

**Comment by mikeyamato** [comment]
I was finally able to read environmental variables natively using TypeScript without the need for any other packages (e.g. dotenv) by doing the following at the root: 

`package.json`
```json
{
  "scripts": {
    "start": "nodemon index.ts" // <-- update file name to your entry point
  },
}
```

`nodemon.json`
```json
{
  "execMap": {
    "ts": "node --env-file=.env"
  }
}
```

`.env`
```env
HELLO="WORLD"
```

`process.env.HELLO` will spit out `WORLD`. I know this thread is closed but hopefully this helps someone.

**Comment by thelements** [comment]
> I was finally able to read environmental variables natively using TypeScript without the need for any other packages (e.g. dotenv) by doing the following at the root:
> 
> `package.json`
> 
> ```json
> {
>   "scripts": {
>     "start": "nodemon index.ts" // <-- update file name to your entry point
>   },
> }
> ```
> 
> `nodemon.json`
> 
> ```json
> {
>   "execMap": {
>     "ts": "node --env-file=.env"
>   }
> }
> ```
> 
> `.env`
> 
> ```dotenv
> HELLO="WORLD"
> ```
> 
> `process.env.HELLO` will spit out `WORLD`. I know this thread is closed but hopefully this helps someone.
> <img alt="Screenshot 2024-09-25 at 12 27 35" width="91" src="https://private-user-images.githubusercontent.com/27756216/370870204-fca7646e-d302-4697-8da8-6bc526d2568e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNzE3NzEsIm5iZiI6MTcyNzM3MTQ3MSwicGF0aCI6Ii8yNzc1NjIxNi8zNzA4NzAyMDQtZmNhNzY0NmUtZDMwMi00Njk3LThkYTgtNmJjNTI2ZDI1NjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE3MjQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMDcxNmFkMGVmM2U3OTlhZmVkZWMxNmVkNDkyZDVhNmQ2NzY5NmFhZTQ3MDZkY2Y2YmY0OGU2ZDdkMzgyNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v3Slp6O-DvTjW0UrEvqkkLcUO49UA2Z2Z0wr-fRJC9I">

With Node 20, We now have default `--watch` option which removes dependecy on nodemon itself. 
https://nodejs.org/docs/v20.17.0/api/cli.html#--watch

**Comment by Farzane2630** [comment]
> I was finally able to read environmental variables natively using TypeScript without the need for any other packages (e.g. dotenv) by doing the following at the root:
> 
> `package.json`
> 
> ```json
> {
>   "scripts": {
>     "start": "nodemon index.ts" // <-- update file name to your entry point
>   },
> }
> ```
> 
> `nodemon.json`
> 
> ```json
> {
>   "execMap": {
>     "ts": "node --env-file=.env"
>   }
> }
> ```
> 
> `.env`
> 
> ```dotenv
> HELLO="WORLD"
> ```
> 
> `process.env.HELLO` will spit out `WORLD`. I know this thread is closed but hopefully this helps someone.
> 
> <img alt="Screenshot 2024-09-25 at 12 27 35" width="91" src="https://private-user-images.githubusercontent.com/27756216/370870204-fca7646e-d302-4697-8da8-6bc526d2568e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODUyNTIsIm5iZiI6MTczMTQ4NDk1MiwicGF0aCI6Ii8yNzc1NjIxNi8zNzA4NzAyMDQtZmNhNzY0NmUtZDMwMi00Njk3LThkYTgtNmJjNTI2ZDI1NjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA4MDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmYzU2MTlhMzk3MzM3OTY5NzQyYzc3NjlhMTI3OWY0MTcyZTc5YmVlNmQ0NjM2YzZhYjY5YmJjYjVlYzY0NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hsBa5OKSboFTRdJ_cLWHv0pNpI5JHe5K7Om_pCfte-I">


Thank you so much. That worked for me. But I wonder why is this the case? I didn`t have problem in other projects.

**Comment by stevenyuser** [comment]
> I was finally able to read environmental variables natively using TypeScript without the need for any other packages (e.g. dotenv) by doing the following at the root:
> 
> `package.json`
> 
> ```json
> {
>   "scripts": {
>     "start": "nodemon index.ts" // <-- update file name to your entry point
>   },
> }
> ```
> 
> `nodemon.json`
> 
> ```json
> {
>   "execMap": {
>     "ts": "node --env-file=.env"
>   }
> }
> ```
> 
> `.env`
> 
> ```dotenv
> HELLO="WORLD"
> ```
> 
> `process.env.HELLO` will spit out `WORLD`. I know this thread is closed but hopefully this helps someone.
> 
> <img alt="Screenshot 2024-09-25 at 12 27 35" width="91" src="https://private-user-images.githubusercontent.com/27756216/370870204-fca7646e-d302-4697-8da8-6bc526d2568e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyMTk3MzksIm5iZiI6MTczNjIxOTQzOSwicGF0aCI6Ii8yNzc1NjIxNi8zNzA4NzAyMDQtZmNhNzY0NmUtZDMwMi00Njk3LThkYTgtNmJjNTI2ZDI1NjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA3VDAzMTAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZWRjNzBlM2RhZTZlOTAwYzZhMmNmYTViZWViZjNjYTRlOTAxY2U2YTJkYzU1NTg3MTc3M2VkNTI5ZmI2MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QoqPjsOiT-n2UG8NzcWDA5QjlJOMpRfzw-t6pHxzXAU">

This didn't work for me, but this did (as referenced [here](https://github.com/umberto-fontanazza/kiruna-explorer/issues/21#issuecomment-2494146115)):
`package.json`
```json
{
  "scripts": {
    "start": "nodemon --exec node --env-file=.env-r ts-node/register index.ts" // <-- update file name to your entry point
  }
}
```
No need for a `nodemon.json` config file.
