### ISSUE TITLE
Passing an array into ext config

### ISSUE THREAD

**Issue by lunavod** [remy/nodemon#2189]
When using `nodemon.json`, it is possible to pass an array into `watch` property, but not into `ext`. This is probably expected behavior, but it is not intuitive for a first-time user. 

- `nodemon -v`: 3.1.0
- `node -v`: v21.2.0
- Operating system/terminal environment:  Windows
- Using Docker? What image: 
- Command you ran: nodemon

### Expected behaviour
Nodemon works as usual, watching provided extensions

### Actual behaviour
`TypeError: extension.match is not a function`

### Steps to reproduce
 - Create a `nodemon.json` config with the following content:
```json
{
  "ext": ["foo", "bar"]
}
```
 - Run `nodemon`

**Comment by mauroobento** [comment]
According to [Nodemon docs](https://github.com/remy/nodemon/blob/master/doc/sample-nodemon.md), there is no array in `ext`, only in `options`, as you can see

```markdown

... 
{
  "restartable": "rs",
...
  "ext": "js,json"
}
```

**Comment by lunavod** [comment]
Yeah, it is more of a feature request. Or at least to get maintainer's opinion about this so I could maybe implement it myself and make a pull request

**Comment by remy** [comment]
Correct me if I'm wrong, but the `nodemon.json` is created by the author, right? If that's the case, why would the author be using an array instead of a string?

It's not a big change, but I just want to work out if there's actually a problem or a need, over something that's just a preference.
