### ISSUE TITLE
Ability not to signal the whole subtree of a process

### ISSUE THREAD

**Issue by Jomshir98** [remy/nodemon#2191]
- Versions: node@v18.18.2, multiple platforms (Linux, Windows) 
- `nodemon -v`: 3.1.0
- Operating system/terminal environment (powershell, gitshell, etc): multiple platforms (Linux, Windows) 
- Using Docker? What image: No 
- Command you ran: `nodemon --enable-source-maps -r dotenv/config dist/index.js`

### Expected behaviour
Nodemon allows signaling the main process that it should stop. This process then does necessary cleanup like saving pending data into development database, stops the database or other services and then cleanly exits.
This in turn is noticed by Nodemon and the process is restarted.

### Actual behaviour
Nodemon sends the signal to the whole process subtree of the command. As the application starts its own database, the database receives the termination command as well and stops before the main process has chance to finish cleaning up, getting it stuck until timeout happens.

### Steps to reproduce
Start any process from inside the watched application that is needed during cleanup phase or that needs special cleanup - not being killed by a signal.
Example of this is setup using `mongodb-memory-server` package.

### Reasoning
This behavior is problematic if the main watched process starts anything external, because no application expects its children to be killed by a different process that is higher up the chain.
If a process starts a subprocess, it should also be responsible for cleaning up the subprocesses and be allowed to do so in the correct order.

I understand that in some cases it might be beneficial to kill the whole subtree - such as if there is a chance of it getting stuck, but then this prevents correct cleanup for applications that do need to cleanup properly, making nodemon unusable for such projects.
That is why I am proposing to make this an option, for example: `--only-signal-main`

**Comment by remy** [comment]
Really the immediate question that jumps to mind is why is your main process responsible for spawning the database. 

That aside, you can, in theory, achieve this yourself using the `sigusr2` signal capture: https://github.com/remy/nodemon?tab=readme-ov-file#controlling-shutdown-of-your-script

**Comment by Jomshir98** [comment]
Whether or not using `SIGUSR2` works depends on the exact implementation of how specific spawned subprocess handles the signal (in fact not just the spawned subprocess, but any subprocess of that one as well), which is rarely documented, especially not for any transitive subprocesses (which might not be documented at all).

> Really the immediate question that jumps to mind is why is your main process responsible for spawning the database.

In my concrete case it is because the server normally connects to a real production database, but during develoment (which is also when I want to use nodemon) it spawns its own, correctly configured DB, so the developers don't need to set it up themselves - instead they just run the `dev` script that does it for them.

The question then might also be why not to start it outside nodemon... Well, to this I have two answers:
- There would be need to communicate things like dynamically chosen port or autogenerated credwntials to the process and this would need some bigger framework to do that nicely; wheres if the server is the one that manages db run, it gets these "for free"
- Sometimes it is useful to run the databse only in memory, or have multiple instances with independant dbs (such as during unit testing) - doing things this way just allows reusing the code everywhere instead of having a special solution for each path

Also note, that database is only one such example. Another (for me) common one is working with puppeteer - a framework for running browsers with automation. Browsers are notorious for spawning many subprocesses and there is no documentation on how they behave when some of them receive a specific signal, in arbitrary order.

**Comment by remy** [comment]
You have control of the top level process, so you can hook the signal. Have you tried this, to then gracefully handle your mongo-memory-thing then exit your own process?

**Comment by Jomshir98** [comment]
I did - that is why I made this issue - it is not possible. My top process does hook the signal and does correctly handle it.
Problem is, that I _don't_ have control about any child processes and the way nodemon does the signaling it signals all the children directly - so in a way that I literally can't hook without modifying the children.
Even making a wrapper around children is not a possible solution - because nodemon gets whole subtree and signals all processes in it, it will simply bypass any wrapper.

**Comment by Jomshir98** [comment]
Ref: https://github.com/remy/nodemon/blob/f8e3b8cc95872aeacd1eea52adf2512c12a461c7/lib/monitor/run.js#L403-L429 (only linux part for simplicity, same logic applies to Windows path)
The comments in the code literally say that - "we use psTree to kill the full subtree of nodemon".
What I'm looking for is having a flag that will prevent this behavior and instead only "kill" the parent - letting it do the cleanup for any potential children.

If you agree with that, I would be willing to make a PR that implements this behavior.

**Comment by Jomshir98** [comment]
In the optimal world it would actually be the other way around than it is currently - the behavior of nodemon should be to _only_ kill the parent - in that case any child of that parent should be monitoring `SIGHUP` signal and exit itself if the parent died - the responsibility should be on the child.
The whole problem is, that some programs don't do this and the current workaround might be needed in specific cases. 
The current behavior basically prefers doing the "non-ideal" thing, thinking all processes will not handle this correctly.

One possible solution could be getting a subprocess tree of the main process, then killing _only_ the main process, waiting a short timeout, and if any child is still alive then force-killing those (because by the time parent exists it should have cleaned up the children already) - no matter the signal/code the parent exited with.
There are however other problems with this approach - namely race conditions. If the parent starts a new child process between the resolution of the process tree and the kill (no matter if before or after the signal is sent/delivered), then these new processes won't be killed, because by that point there is no way to find them.

**Comment by Jomshir98** [comment]
I honestly think that a flag is the best solution here - what you are talking about (detecting if process does handle the signal) is in a way also a flag - it is just set by the OS (if you do manage to get it) instead of being set explicitly by the user.
I think having a flag for "I want to handle the signal myself" is better solution than changing this behavior implicitly based on this info.
Also that info might be unreliable and obscure for the user - if there is a framework around the application, then the framework itself might handle the signal without the actual developer handling it - so the resulting behavior would be unexpected for the developer... 
And there definitely isn't a way to know if it was the developer who got to handle the signal or if it was some framework.

What I mean is: Node.js for example by itself always handles the signal - it is just matter that if there is no JS callback for it, then it proceeds to shut down by itself. From the view of the OS it still however is a handled signal not resulting in directly killed process.

**Comment by Jomshir98** [comment]
Yet another possible solution would be going closer to the containerization frameworks (e.g. how Docker is able to reliably stop the whole container no matter what processes and when are started inside it).
On linux this could be achieved by becoming a child subreaper (see [prctl(2)](https://man7.org/linux/man-pages/man2/prctl.2.html), `PR_SET_CHILD_SUBREAPER`) - which would cause any orphaned children to be re-parented to this process, so it could then collect them and "reap" them when desired (instead of the orphans being re-parented to `1`/`init` and being undiscoverable after that by nodemon).
While this solution would solve this issue, it is very platform dependent (I don't have nearly enough Windows knowledge to say how one could approach this there) and it would almost definitely require having a native binary to do this.

Yet another possible solution would be to literally use a container to run the development server(s) and their children - it is a technology that already exists and is very well tested. I however thing, that that goes way past of what Nodemon is intended to do...
