### ISSUE TITLE
not working with Node.js version 20.12.x

### ISSUE THREAD

**Issue by kireerik** [remy/nodemon#2194]
```
ELIFECYCLE Command failed with exit code 3221226505.
```

With Node.js version 20.11.x it is working.

- Versions: Windows (10)
- `nodemon -v`: 3.1.0
- Operating system/terminal environment (powershell, gitshell, etc): cmd
- Using Docker? What image: No.
- Command you ran: nodemon

closes https://github.com/getsentry/sentry-javascript/issues/11453

**Comment by remy** [comment]
<img width="732" alt="SCR-20240418-mmld" src="https://github.com/remy/nodemon/assets/13700/3de6746c-e91c-445b-90c2-2c6ee00124e0">

Does not error as per the detail given in the original issue. 

Will close shortly unless there's any additional (or _any_ ) details.

**Comment by remy** [comment]
Actually will close and reopen later if any details are offered. This doesn't read like a nodemon issue (but…again, very little info).

**Comment by kireerik** [comment]
With 20.11.x it works.
With 20.12.x it is not working.

**Comment by remy** [comment]
<img width="692" alt="SCR-20240419-obnj" src="https://github.com/remy/nodemon/assets/13700/d636e98e-4dac-4595-ad8e-bcf5f2fb0ee8">

It is according to the directions you offered.

**Comment by kireerik** [comment]
Seems like this issue occurs (with Node.js version 20.12.x) when the [`--env-file` option](https://nodejs.org/docs/latest/api/cli.html#--env-fileconfig) is used (example `--env-file .env`).

**Comment by remy** [comment]
<img width="592" alt="SCR-20240422-kshn" src="https://github.com/remy/nodemon/assets/13700/f550f31b-15bf-409d-a54f-71c5521a5ec9">

Also no.

**Comment by kireerik** [comment]
Did you use version 20.12.x?

We have a setup like this:
`start` script in packages/`package`/package.json:
- `nodemon --env-file=.env src/index.mjs`

> .env file is in packages/`package`
> nodemon is installed for the `package` workspace

command to reproduce the issue: `pnpm --filter package start`

Removing ` --env-file=.env` from the start script makes it start properly with Node.js version 20.12.x as well.

**Comment by remy** [comment]
You can see I used node 20 from my previous screenshot.

Provide a pared down repo to replicate the issue then I can look at this properly because so far you've drip fed me information on what you're seeing and it's not helpful (ie. now adding that you're using pnpm is another variable).

**Comment by kireerik** [comment]
The issue happens with Node.js version 20.12.x.

**Comment by remy** [comment]
No, it doesn't: https://github.com/remy/nodemon/issues/2194#issuecomment-2066755817

It's happening on your machine and you've not provided details to replicate.

Last time I ask for details to replicate.

**Comment by kireerik** [comment]
Seems like I was able to reproduce it. It looks like it happens when the `.env` file contains a variable that is at least 292 characters long and when the value is provided in (double or single) quotes.
Example:
```
test="abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabca"
```

Not using quotes at all works as expected.
