### ISSUE TITLE
Nodemon Internal watch failed 

### ISSUE THREAD

**Issue by samiramrullah** [remy/nodemon#2200]
I am using nodemon with nodejs, it works fine in windows and ubuntu but it throws an error on mac stating "[nodemon] Internal watch failed: UNKNOWN: unknown error, watch 'project path/5000;'

* It also creates a port file named "5000;" on it's. on the project folder. 
It crashes the server.

Node version: 20.12.1
nodemon version: 3.1.0

* These is the snapshot of the file being created with port number 5000;
<img width="234" alt="Screenshot 2024-05-06 at 9 01 35 PM" src="https://github.com/remy/nodemon/assets/74055996/a5a25afb-2506-4f56-bd56-44d4eafd11bd">

Below snapshot shows the error
![B472D396-B5C5-4659-BDFF-B1F435DD44DB_1_201_a](https://github.com/remy/nodemon/assets/74055996/21216d6b-68a3-4b60-9aef-022309d1fe47)

Node : Getting same error even if I'm changing the port number server.listen()

**Comment by remy** [comment]
What directory are you running nodemon from? Also, can you create a repo to replicate this?

**Comment by harshnayangithub** [comment]
i'm also facing the same issue in mac it's creating a 4000 file 
![image](https://github.com/remy/nodemon/assets/126700987/43e5efb0-ca6f-426f-941c-75d0dc74332e)
![image](https://github.com/remy/nodemon/assets/126700987/54d1384a-78d7-4553-aea8-19dab39a9f41)
I'm running it in the server directory as expected 
![image](https://github.com/remy/nodemon/assets/126700987/5ce4e4bc-1dad-4a2d-b0d5-321793b20058)

**Comment by bhan0234** [comment]
i am facing the same issue

**Comment by remy** [comment]
@bhan0234 if you don't provide any informatio on how to replicate, then "I'm facing the same issue" is really not very helpful.

Marking as stale (which should auto remove when there's a comment with code to replicate).
