### ISSUE TITLE
nodemon does not restart the server ([nodemon] restarting due to changes...)

### ISSUE THREAD

**Issue by philip045** [remy/nodemon#2201]
- Versions: 
- `nodemon -v` :latest
- Operating system/terminal environment (powershell, gitshell, etc): powershel
- Using Docker? What image: no
- Command you ran: nodemon server.js

### Expected behaviour
Restart the server when changing the server codes
![fsdfdsfdsfs](https://github.com/remy/nodemon/assets/169137068/d0b9c9fd-c5c2-4808-aced-8361beb6cb47)

### Actual behaviour
when i use app.listen() function in express.js , nodemon not work and must rerun it,
please help me and i do all solution in internet, and not worked...
![Capturefdsfdsf](https://github.com/remy/nodemon/assets/169137068/f06c60c9-141e-43e2-bcec-7473d76c4682)

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Your server (unrelated to node) is not releasing the port, so it's not restarting.

Try running nodemon with `--spawn` flag, i.e. `nodemon --spawn` - not sure it'll make any difference, but there's not much to go on here, and I'm fairly sure there's something specific about your setup that's blocking the stopping of the process.

A couple of extra things you can try:

1. Change the port (you're reading the `process.env.PORT`)
2. Try running without nodemon (on the original port) and then do ctrl+c in the terminal (don't close the terminal in VS Code, just send the keys) - see what happens.

**Comment by bipin0x01** [comment]
Facing the same issue since last couple of weeks. Any other references for this issue ?

**Comment by ahmadelafify** [comment]
My solution for my team was to overwrite the restart event command in the config with a `kill` command. hope this helps someone else!

`nodemon.json`:
```{
  ...,
  "ext": ".js,.json,.ts",
  "events": {
    "restart": "kill $(pgrep -f server/main.ts)"
  },
  ...
}
```
