### ISSUE TITLE
Question not a bug - How to restart app on crash

### ISSUE THREAD

**Issue by moomoo-dev** [remy/nodemon#2202]
I'm trying to have nodemon restart my app when it crashes... is this a possibility .. and if so how do I do it?

**Comment by remy** [comment]
Nodemon, intentionally, doesn't support this. It's used for development rather than to keep crashing apps from restarting. Something like pm2 might be a good match to your needs.

**Comment by moomoo-dev** [comment]
Thank you. I got Pm2 working, but I was hoping that this would work as well. I'll just use Pm2 :( LOL
