### ISSUE TITLE
Number of restart events differs from the number of exec.

### ISSUE THREAD

**Issue by novellat** [remy/nodemon#2213]
- Versions: node@v18.18.2, darwin@23.5.0
- `nodemon -v`: 3.1.4
- Operating system/terminal environment (powershell, gitshell, etc): zsh on mac
- Using Docker? What image: no
- Command you ran:

```
const nodemon = require('nodemon');

nodemon({
  ext: 'js, jsx, ts, tsx, json, md',
  ignore: ['node_modules'],
  watch: ['./plugins'],
  exec: 'echo changed?????',
}).on('restart', (...args) => {
  console.log('CHANGE!!!!!!', args[0]);
});
```

### Expected behaviour

expected the numbe of "changed?????" to be equal to "CHANGE!!!!!!".
### Actual behaviour

 But there's more restart events than the script calls.

---

**Comment by remy** [comment]
Possibly firing on overlapping triggers.

What's the actual impact of the problem you're seeing?

**Comment by novellat** [comment]
The main thing is that I need to exec some relatively long running command on changes and would like to minimize the number of restarts. So mostly performance impact (why run my long running command more than necessary)

**Comment by novellat** [comment]
What do you mean by overlapping triggers? I only have this one nodemon script running

**Comment by novellat** [comment]
Actually, feel free to close the ticket. I made a workaround around my problem - basically triggered several nodemons on different directories and then the whole logic is more straightforward and I don't need to any shenannigans like this, just a simple nodemon calls.
