### ISSUE TITLE
Advice, not a bug.

### ISSUE THREAD

**Issue by Digital-Pig-LLC** [remy/nodemon#2214]
Let me preface this with, logically this should work, and if I need to really dig into it I will, I'm just looking for some advice on where to start.
I have a node app running in a Debian 12 container, on Windows (should make no odds).
My app dev env is IntelliJIDEA.
When I save new code, nodemon is not restarting, and I understand why. So, what I came up with is this:
On save, execute a "docker exec" command, which send a shell command to call a shell script.
The shell script is as follows:
```
PID=`ps aux | grep nodemon | grep -v grep | awk '{print $2}' | tail -n 1
echo -e "rs\n" > /proc/$PID/fd/0
```

The idea is simply...get the PID of nodemon, send input to it
Given this nodemon output:
```
npm start

> article-repo-lister@1.0.0 start
> nodemon -e js,twig -x ./bin/www app.js

[nodemon] 3.1.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,twig
[nodemon] starting `./bin/www app.js`
```
...after running the script, I simply see a new line, like so:
`rs

`
So, the rs + newline is being sent to the process, but is not seen by nodemon.

I know, I'm probably cray-cray, I just love following thoughts like this even if I don't end up using it. I guess I need to know how is the input received when I simply use the keyboard as opposed to using the script.

Thanks! Sorry for the lengthy explanation.

- `nodemon -v`: 3.1.4
- `node -v`: 22.5.1
- Operating system/terminal environment: Debian 12 Bash
- Using Docker? What image: Yes, node:latest
- Command you ran: nodemon -e js,twig -x ./bin/www app.js

### Expected behaviour
nodemon restarts

### Actual behaviour
no change

### Steps to reproduce
The above contains everything.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by Digital-Pig-LLC** [comment]
Is it really nodemon that receives the "rs" input, or is it node? Hmmm!

**Comment by ankhzet** [comment]
@Digital-Pig-LLC just do something like `touch .nodemon`, where `.nodemon` is added to the the watched extensions list and `git`-ignored. As a result, nodemon would detect changes and restart.

**Comment by Digital-Pig-LLC** [comment]
Thanks @ankhzet I'll give that a try.
