### ISSUE TITLE
YAML file passed to -w does not trigger restart when it changes

### ISSUE THREAD

**Issue by rjray** [remy/nodemon#2216]
- Versions: node@v22.6.0, linux@6.8.0-40-generic
- `nodemon -v`: 3.1.4
- Operating system/terminal environment (powershell, gitshell, etc): Linux, bash, yarn 1.22.22
- Using Docker? What image: no
- Command you ran: `nodemon -w src/openapi.yaml -w src src/server.ts`

### Expected behaviour
A change to the file `src/openapi.yaml` should cause nodemon to restart the watched process

### Actual behaviour
Changes to the YAML file have no effect

### Work-around
Passing `--ext yaml,ts` causes the file to trigger restarts when it changes. However, I expected that an explicitly-specified file would not need to be further enabled by `--ext`.

**Comment by remy** [comment]
ACK - this is actually a bug, though not entirely apparent. If you run nodemon in the `src` directory and ask it to run as `nodemon -w ./openapi.yaml -w . ./server.ts` it works, but if you're watching in a sub-directory it doesn't - as you're experiencing. 

I'm trying to work on a fix for this.

**Comment by remy** [comment]
I wrote a fix last night but it's not fully passing tests (but I think those tests need to be updated).

I've published a dev build if you want to try it out though - if you install using `npm install nodemon@dev` you should be able to test it out.

**Comment by rjray** [comment]
Tried it and it worked. Will watch for an updated release.

**Comment by rjray** [comment]
Commenting to keep this alive. Any estimate on the next release?

**Comment by remy** [comment]
I'm still trying to scrape the time to get the tests to pass (I've marked as not-stale to prevent the bot from closing). The code change is there, but there's a lot of tests that fail (in the match logic) due to the change, and I'm trying to work out which are false negatives and which are real. Definitely going in soon…ish!

**Comment by remy** [comment]
That's going up in the latest release now 👍
