### ISSUE TITLE
Migrating from PM2 to NodeMon

### ISSUE THREAD

**Issue by RUSHt** [remy/nodemon#2219]
### Expected behaviour

When I start an app.js using nodemon I get logs to ssh console, this works.

### Actual behaviour

Should ssh drop then on reconnect there are no logs. (it's an EC2 instance).

### Desired behaviour

$ nodemon app.js --logs          // ie, restart logging 

I've read the docs & can't see how to resume logging.

Peter

**Comment by remy** [comment]
nodemon doesn't run in the background in deamon mode - you'll need your own tooling for that. So when you disconnect your ssh connection to ec2, the process stops, and hence so do the logs.
