### ISSUE TITLE
Types are missing ignore option

### ISSUE THREAD

**Issue by ChristophP** [remy/nodemon#2223]
The defined types are missing the `ignore` options so typescript complains about it
https://github.com/remy/nodemon/blob/main/index.d.ts#L105-L118

### Expected behaviour
The types should include `ignore`

**Comment by remy** [comment]
I'm not a TS dev, so won't really know, off the top of my head, how this should be done. Assume it's not covered the existing types file?

**Comment by ChristophP** [comment]
Hi @remy,

> Assume it's not covered the existing types file?

Exactly.
Judging from this example in the docs https://github.com/remy/nodemon/blob/master/doc/sample-nodemon.md
`ignore` should be an array of strings but it's missing in the types file. Which looks like this
```ts
export interface NodemonConfig {
  /* restartable defaults to "rs" as a string the user enters */
  restartable?: false | String;
  colours?: Boolean;
  execMap?: { [key: string]: string };
  ignoreRoot?: string[];
  watch?: string[];
  stdin?: boolean;
  runOnChangeOnly?: boolean;
  verbose?: boolean;
  signal?: string;
  stdout?: boolean;
  watchOptions?: WatchOptions;
}
```
Simply adding a line to the structure like this should do the trick

```ts
export interface NodemonConfig {
  ...
  ignore?: string[];
  ...
}
```

**Comment by ChristophP** [comment]
Would you accept a PR for this?

**Comment by remy** [comment]
Happy to take a PR, or I should be able to get it up today asit looks like a single line - but you might be in a better position to test it works the way you'd expect.
