### ISSUE TITLE
Website revamp

### ISSUE THREAD

**Issue by Muhammad-Owais-Warsi** [remy/nodemon#2225]
I would like to redesign the Nodemon website to enhance the experience and overall look. Currently I have follwoing design in my mind.
Let me know your thoughts !

![Screenshot from 2024-09-25 02-36-40](https://github.com/user-attachments/assets/b7e0ad19-2e11-44bc-9d05-f381e468c1a4)

**Comment by Anurag0218** [comment]
is anyone working on it? If not, can I take it up?

**Comment by remy** [comment]
I honestly don't see the point. I know that sounds harsh, but there *isn't* an experience on the website, so there's nothing really to enhance. 

I appreciate the thought, but I'll pass, thank you.

**Comment by Muhammad-Owais-Warsi** [comment]
@remy Thanks for the consideration.
