### ISSUE TITLE
Nodemon Website Revamp

### ISSUE THREAD

**Issue by swaparup36** [remy/nodemon#2229]
The current website of nodemon looks very basic. As nodemon is widely used, so I think that the website of nodemon should have a really good looking website. It should have a good looking UI for tutorial of how to use nodemon in your projects. Rest all that the current website has, needs to be fit in a good UI. 

We can implement this design given bellow.
![Screenshot 2024-10-04 112431](https://github.com/user-attachments/assets/681f8e80-4735-46f0-b227-e45bd1bb3ca9)

**Comment by remy** [comment]
Curious who "we" is.

Curious how the lays out on mobile.

Curious as to what UI you're adding, since there's no actual user interface on the existing site (it's just pure content)

Curious as to what tutorial you'd add.

**Comment by swaparup36** [comment]
I used "We" because the decision to revamp the website depends on you and I will make the new one.

On mobile it will look like 
![Screenshot 2024-10-05 223150](https://github.com/user-attachments/assets/98dcee32-63bb-4f88-88bf-8ce3e99899ee)


When a user goes to the website it should appear more presentable to the user. That is what I want to make.

Tutorial means, the command to install nodemon and how to use it in the project. Not much, just a small instruction.

**Comment by remy** [comment]
I'm fine, thanks. All I see is a low contrast reskin of what's already there (plus a burger menu that's hiding content). 

I'm not sure what's prompting the recent glut of requests to redesign, but I'm not particularly interested. 

I appreciate the effort, but no thanks.
