### ISSUE TITLE
Missing types

### ISSUE THREAD

**Issue by zAlweNy26** [remy/nodemon#2231]
- Versions: bun@v1.1.29, linux@6.5.0-1027-oem
- `nodemon -v`: 3.1.7
- Operating system/terminal environment (powershell, gitshell, etc): ubuntu/bash
- Using Docker? What image: oven/bun

### Expected behaviour
The `NodemonConfig` interface is missing `legacyWatch`, `dump` and some others.

### Actual behaviour
Unable to add these options without extending the interface manually in my project.

I can open a PR if it's ok :)

**Comment by remy** [comment]
I appreciate a PR, thanks 🙏

**Comment by ravin00** [comment]
Try updating your nodemon to the latest and do type casting is necessary.
