### ISSUE TITLE
Error :  listen EADDRINUSE: address already in use

### ISSUE THREAD

**Issue by udhayakumarcp** [remy/nodemon#2233]
- Versions: node@v14.21.3, linux@6.8.0-45-generic 
- `nodemon -v`: 3.1.7 (tried in all version, facing the same issue )
- Operating system/terminal environment (powershell, gitshell, etc):  Ubuntu 24.04.1 LTS
- Using Docker? What image: No
- Command you ran: nodemon

### Expected behaviour

The application should run

### Actual behaviour

Facing the address in use error

![image](https://github.com/user-attachments/assets/689b2ca1-501e-4abd-92f3-1c0cbfba99fa)

### Steps to reproduce

- Do the folwing in the Ubuntu 24 LTS
- Install node 14 LTS
- Install the nodemon as Dev dependencies by ` npm i -D nodmeon@latest`
- Add the script in the `package.json` file `watch: nodemon`
- Add the below config file in the project root
```
{
  "watch": ["app", ".env"],
  "ext": "ts",
  "ignore": ["app/**/*.spec.ts"],
  "exec": "ts-node ./app/index.ts",
  "env": {
    "NODE_ENV": "development"
  }
}
```
- Run the app by the command ` npm run watch`

**Comment by Satvik1769** [comment]
have you tried restarting your computer, may be there is an instance running beforehand so you would have to kill it
before trying to run again on same port

**Comment by udhayakumarcp** [comment]
> have you tried restarting your computer, may be there is an instance running beforehand so you would have to kill it before trying to run again on same port

I tried lsof. Also, it is not working even I chnage the ports to listern
 lsof -i tcp
COMMAND     PID        USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node       5486 udhayakumar   23u  IPv4  40887      0t0  TCP *:3001 (LISTEN)
code-384f 25910 udhayakumar    9u  IPv4 305639      0t0  TCP localhost:37065 (LISTEN)
code-384f 25910 udhayakumar   12u  IPv4 304746      0t0  TCP localhost:37065->localhost:35124 (ESTABLISHED)

**Comment by ravin00** [comment]
I think some different address is already running in the terminal i think that's the issue. So if you basically have the localhost to run on the port 3000 it should run their but since the port 3000 is already running that's why the the localhost is running on 3001

**Comment by udhayakumarcp** [comment]
> I think some different address is already running in the terminal i think that's the issue. So if you basically have the localhost to run on the port 3000 it should run their but since the port 3000 is already running that's why the the localhost is running on 3001

I tried with ports 3000, 3001, 3002, 3003, 3004, 3005. Also, tried by rebooting

**Comment by udhayakumarcp** [comment]
> have you tried restarting your computer, may be there is an instance running beforehand so you would have to kill it before trying to run again on same port

Restarting is worked.
