### ISSUE TITLE
Can't run nodemon on the background - process immediately stopped

### ISSUE THREAD

**Issue by RealYukiSan** [remy/nodemon#2234]
- Versions: node@v22.7.0, linux@6.10.7-arch1-1
- `nodemon -v`: 3.1.7
- Operating system/terminal environment (powershell, gitshell, etc): `linux/bash`
- Using Docker? What image: no
- Command you ran: `npx nodemon main.js &`

### Expected behaviour

nodemon process run in the background

### Actual behaviour

process immediately stopped

### Steps to reproduce

run `npx nodemon main.js &`

### Logs

```
[user@server d-net]$  npx nodemon main.js &
[1] 546628
[nodemon] 3.1.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node main.js`
(node:546656) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a u
serland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
HTTPS server running on port 6969

[user@server d-net]$  jobs
[1]+  Stopped                 npx nodemon main.js
[user@server d-net]$ 
```

**Comment by codicecustode** [comment]
npx nodemon might be trying to interact with the terminal , and this causes it to be stopped when it's running in the background.
using pm2 might be solve your issue

**Comment by remy** [comment]
If you're trying to keep the process running, pm2 is better suited. 

But as @codicecustode suggested, it might be npx and it's worth ruling that out by running the `bin` directly or installing globally

**Comment by RealYukiSan** [comment]
Yeah, tried running it directly from `./node_modules/.bin/nodemon` but somehow it still stopped and not working.

I will use `pm2` instead, closing the issue.
