### ISSUE TITLE
Pass filename as parameter to executable?

### ISSUE THREAD

**Issue by tarruda** [remy/nodemon#227]
Hi, first of all, thanks for this very useful program. 

I'm working on a project that has haskell and c++ files, I'm using nodemon to automatically recompile and re-run tests on changes.

The only issue is that I just want to recompile my project when a c++ file changes. Most of the times I'm only changing haskell files, so its fine to just run the test script.

Is there a way to pass the name of the modified filename to the executable? This way I can improve my workflow by avoiding unecessary recompilations.

**Comment by bduffany** [comment]
I think it would be super convenient to be able to do this via the CLI, and not have to write a JS file.
