### ISSUE TITLE
Nodemon throws an exception while starting an app

### ISSUE THREAD

**Issue by sbusa** [remy/nodemon#246]
Hi,

There seems to be a new issue with nodemon with the latest code. 

It throws an exception while restarting an app.

Logs:
2 Jan 00:09:18 - ^[[33m[nodemon] v1.0.1^[[39m
2 Jan 00:09:18 - ^[[33m[nodemon] to restart at any time, enter `rs`^[[39m
2 Jan 00:09:18 - ^[[33m[nodemon] watching: /^[[39m
2 Jan 00:09:18 - ^[[32m[nodemon] starting `coffee /lib/node_modules/cloudflash/app.coffee`^[[39m
exception in nodemon killing node
Error: EBADF, read

If appropriate, please file an error: http://github.com/remy/nodemon/issues/new

Please provide your comments.

Thanks,
-Siva

**Comment by jacobrossdev** [comment]
I'm getting this same issue now at version 2.0.19

`events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: read EBADF
    at Pipe.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'EBADF',
  code: 'EBADF',
  syscall: 'read'
}
`
