### ISSUE TITLE
Infinite restarting...

### ISSUE THREAD

**Issue by camj256** [remy/nodemon#249]
Not sure what changed, I was pushing some changes to my server today and now it keeps restarting.

I was using .nodemonignore to ignore public/\* but its not working anymore. It will load up just fine the first time but as soon as I push an update and it should restart it gets stuck in a loop.

(Note: there are files in public that get generated on startup.)

I tried using your nodemon.json setup but I get the same thing.

If I use the command line and just --ignore public/\* it works fine.

Thanks!

**Comment by RandomMaker** [comment]
I'm running into this issue right now too.

Here is a dump of my nodemon:

`Brandons-MacBook-Pro:MuchoMonitor brandonchow$ nodemon --dump
10 Feb 13:39:22 - [nodemon] v1.3.6
10 Feb 13:39:22 - [nodemon] to restart at any time, enter `rs`
10 Feb 13:39:22 - [nodemon] watching: *.*
--------------
node: v0.10.33
nodemon: v1.3.6
command: node /usr/local/bin/nodemon --dump
cwd: /Users/brandonchow/Desktop/Development/MuchoMonitor
OS: darwin x64
--------------
{ run: false,
  system: 
   { cwd: '/Users/brandonchow/Desktop/Development/MuchoMonitor',
     useFind: true,
     useWatch: false,
     useWatchFile: false },
  required: false,
  dirs: [ '/Users/brandonchow/Desktop/Development/MuchoMonitor' ],
  timeout: 1000,
  options: 
   { dump: true,
     ignore: 
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions: 
      { script: '',
        exec: 'nodemon',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor: 
      [ '*.*',
        '!/Users/brandonchow/Desktop/Development/MuchoMonitor/.git/**/*',
        '!/Users/brandonchow/Desktop/Development/MuchoMonitor/node_modules/**/*',
        '!bower_components',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command: { raw: { executable: 'nodemon', args: [] }, string: 'nodemon' } }
--------------`

**Comment by remy** [comment]
@RandomMaker this issue is closed. Can you create a new issue with details on how to replicate? Your dump is useful, but doesn't help replicate the issue (though it does tell me what versions you're running).
