### ISSUE TITLE
nodemon does not work even for the simplest case :(

### ISSUE THREAD

**Issue by olliefr** [remy/nodemon#269]
I've just installed node.js v0.10.24 and nodemon v1.0.10 on OS X Mavericks via homebrew and when I start it with `(~)$ nodemon Documents/monitor.js` it outputs the following.

```
17 Jan 19:59:31 - [nodemon] v1.0.10
17 Jan 19:59:31 - [nodemon] to restart at any time, enter `rs`
17 Jan 19:59:31 - [nodemon] watching: *.*
17 Jan 19:59:31 - [nodemon] starting `node Documents/monitor.js`
Oh no! Oh my! It's a Gruffalo!
Server running at http://127.0.0.1:8000/
```

I can connect to the server from the browser but when I edit and save monitor.js, nodemon does not pick up those changes. 

The contents of `monitor.js` is the following. I change the response text, save, reload in browser... and no change happens :-1: 

```
// rPi Monitor
console.log("Oh no! Oh my! It's a Gruffalo!");

var http = require('http');

var server = http.createServer(function (request, response) {
  response.writeHead(200, {"Content-Type": "text/plain"});
  response.end("Oh no! Oh my! The Gruffalos have a web server!\n");
});

server.listen(8000);

console.log("Server running at http://127.0.0.1:8000/");
```

**Comment by RayPS** [comment]
Attempt to reading through all the issues, finally found this one, I'm so surprised that **watching a single js file** is a rare case of nodemon and it's not the default behavior.

When I run `$ nodemon ~/Desktop/Scripts/task.js` I expect only watching the file I inputted, but then I got watching directory in the entire directly with `watching path(s): *.*` and some other extensions/files I didn't ask for. That was so counterintuitive and confusing for me. I've tried to disable the watch by editing the config to `watch: []` or `watch: null` and `ext: ""`. I'm sure I must be missing something.

I really hope there will be an option to watch a single file. For example `$ nodemon --only ./backend/api.js`. That would be nice.
