### ISSUE TITLE
High CPU usage on large project

### ISSUE THREAD

**Issue by TimNZ** [remy/nodemon#280]
Refer to #205 for background info on progressive slower restarts on Windows.

Installed 1.0.3 on Windows 7x64 and now relatively high fluctuating cpu usage (always between 10->60% on one CPU) for the same large project. With 0.7.x I just had the slow down but little to no cpu usage on monitoring, with increasing slowness over time for restarts.

**Comment by iMerica** [comment]
I just went from 250% CPU utilization to 20% by adding the argument ` --ignore node_modules/`.
