### ISSUE TITLE
Running required nodemon multiple times

### ISSUE THREAD

**Issue by remy** [remy/nodemon#286]
Will fix this https://github.com/JacksonGariety/gulp-nodemon/issues/6

Currently if you require nodemon, it's a static, so you can require multiple times (or rather - it makes no difference).

I'm not sure what to do right now, whether nodemon should return a new instance (which is potentially a lot of work...possibly) or whether nodemon internally tracks multiple monitors (which is potentially messy).

Would love any community input, ideas and help to code this up if possible.

**Comment by let4be** [comment]
a whole year passed and issue is not resolved ^^
The same problem, any workaround?

**Comment by Darzu** [comment]
For my project, I think we ended up using https://github.com/substack/watchify or the built-in Gulp watch features.

**Comment by ratson** [comment]
@remy Is there any plan to add this feature?

**Comment by stevenvachon** [comment]
Hello?

**Comment by remy** [comment]
No, not without a PR.

**Comment by simison** [comment]
We've been using [concurrently](https://www.npmjs.com/package/concurrently) together with `gulp-nodemon`: https://github.com/Trustroots/trustroots/blob/master/package.json#L22

**Comment by mjy78** [comment]
If you're using gulp to launch nodemon you can use [node-multi-process](https://github.com/juanfran/gulp-multi-process) to launch multiple instances. See example here https://github.com/JacksonGariety/gulp-nodemon/issues/6#issuecomment-330788506
