### ISSUE TITLE
nodemon cannot run in background with nohup?

### ISSUE THREAD

**Issue by leoliaolei** [remy/nodemon#296]
I use `nohup nodemon server.js &`. It seems nodemon is killed soon.

**Comment by nswish** [comment]
nohup nodemon app.js </dev/null &
works for me! 
thanks!

**Comment by rodrigogds** [comment]
nohup nodemon app.js </dev/null &
works for me too!
Thank you very much ;-)

**Comment by tux-world** [comment]
i can put it to background, but after close ssh connection, nodemon stopped, because after connecet to ssh again i dont have any package on background

```Last login: Mon Jul 25 10:01:35 2016 from 46.224.238.119
chapar@ubuntu:~$ fg
-bash: fg: current: no such job```

**Comment by Fistynuts** [comment]
Another possible solution:

`nohup nodemon -I app.js`

The -I switch prevents nodemon from attempting to use STDIN, which isn't allowed under nohup as there's no input stream.

**Comment by barraponto** [comment]
@Fistynuts interesting -- but I don't see the `-I` option when I run `nodemon --help`. Doc issue?

**Comment by MahdiPishguy** [comment]
@barraponto please use `tmux` terminal emulator and run nodejs application inside that

**Comment by MahdiPishguy** [comment]
@leoliaolei you can use nodemon with `tmux`

**Comment by NigeAtAnd** [comment]
@remy Feel free to close this issue, using the `-I` switch fixes it.

**Comment by remy** [comment]
I've got an faq item to merge, so I'll add this to the FAQ too. 

👍

**Comment by TinoSM** [comment]
For those trying to use it (I don't have the -I switch yet), you can also try with the command "screen" if your distribution has it (AWS has it), it opens a deattached shell which wont die even if your ssh dies (plus you can recover it later)

**Comment by ashish-patidar-rau** [comment]
> nohup nodemon app.js </dev/null &
> works for me!
> thanks!

thanks this is work for me
