### ISSUE TITLE
can't using readline with nodemon

### ISSUE THREAD

**Issue by ygaradon** [remy/nodemon#303]
hey tried to use ProgressBar from [node-progress](https://github.com/visionmedia/node-progress)
it's wasn't showing 
after more investigation i find out that i can't use `readline` in nodemon

```
rl = require('readline').createInterface({
  input: process.stdin,
  output: process.stdout
});

rl.write('hello world');
```

running `nodemon app.js` will not show the hello world message

**Comment by mik01aj** [comment]
I'm using `nodemon v1.3.7` and still have problems with readline. For example, when I run my script with nodemon, pressing arrows produces `^[[A^[[A^[[D^[[D^[[^C` in the console. And when I use plain node they handle cursor navigation as usual.

**Comment by oNaiPs** [comment]
I have same problem as @mik01aj on OSX, any insights on that? I'm thinking that isTTY is not returning the right value when running the script through nodemon

**Comment by arichiardi** [comment]
the problem is still there with `1.11.0`. I tried both `-I` and `restartable` to no avail.

**Comment by Eeemil** [comment]
The problem persists in `nodemon v1.18.10`

**Comment by remy** [comment]
The problem is not related to the issue raised 5 years ago. If there's a new issue, please raise with full details on how to replicate.
