### ISSUE TITLE
Coffeescript files aren't watched when Nodemon is started with a JS file

### ISSUE THREAD

**Issue by leppert** [remy/nodemon#312]
Coffeescript files appear to only be watched when Nodemon is started using a Coffeescript file, [contrary to the docs](https://github.com/remy/nodemon#specifying-extension-watch-list).

Everything works properly when you explicitly specify the extensions to watch with `nodemon -e js,coffee,litcoffee`

For reference, here's a [StackOverflow user experiencing the trouble](http://stackoverflow.com/questions/15470334/autocompile-coffee-files-and-reload-project).

**Comment by radkodinev** [comment]
The wording in question is confusing. It definitely made me think nodemon would watch for changes in my .coffee files but it actually didn't. Which led to frustration and caused me to stop using nodemon. The docs sound so confident to the extent I didn't try listing the coffee extension (until now) and I assumed nodemon just has a bug or something.

**Comment by remy** [comment]
This is a bug. It *should* monitor coffee script out of the box. Problem
is, I don't use cs at all, so I never check this. I'd be happy to have
someone help to get this back on as default.
