### ISSUE TITLE
Support “delay” option in `nodemon.json` config file

### ISSUE THREAD

**Issue by OliverJAsh** [remy/nodemon#324]
It appears that the `delay` option is currently not recognised.

**Comment by jamiehutber** [comment]
:+1:

**Comment by andrei-cocorean** [comment]
The delay option works in the config file, but it takes the number of millis instead of seconds.

**Comment by remy** [comment]
Is this a docs thing that could be updated?

**Comment by StanleyGoldman** [comment]
+1 update the doc

**Comment by Alex-Aralis** [comment]
yes, pleas update the docs
