### ISSUE TITLE
nodemon restarts over and over when clock is set back

### ISSUE THREAD

**Issue by jodonnell** [remy/nodemon#329]
I set my clock on OSX backwards an hour for testing purposes, when I went to start nodemon it kept restarting over and over again.

**Comment by remy** [comment]
Can you test with nodemon 1.3.x? I've added the ability to *try* to detect clock drifting...

**Comment by srlmproductions** [comment]
I have a similar issue. I'm my server is running on a platform that is ~5 seconds behind my development system. I have a `grunt watch` setup to `rsync` changed files to the server, where `nodemon` is watching the files. After `rsync` updates the files, `nodemon` restarts the server.

Nice and clean, except for that ~5 second lead time. That causes `nodemon` to restart in a loop until the time catches up. I could use `--delay` as a hack, but I can't guarantee a consistent offset (not to mention the delay is annoying).

I don't really have a proposed solution to this, but thought I'd mention in case it's helpful.

**Comment by cfjedimaster** [comment]
I have a similar issue as well. Somehow I have a file that has a modified time in the future. Don't ask me how - I have no idea. nodemon considers it a change and restarts in an infinite loop.

**Comment by remy** [comment]
Please try the build here #625 and feedback against the issue #625.

**Comment by remy** [comment]
#625 closes and released in `nodemon@1.4.2`
