### ISSUE TITLE
Add ability to watch a single file

### ISSUE THREAD

**Issue by Aaronius** [remy/nodemon#334]
I might just be missing something, but it looks like I can't tell nodemon to watch a single file.  I tried to configure nodemon to watch the following (I'm running nodemon through grunt-nodemon):

```
[
    "server",
    "!server/views",
    "app.js"
]
```

Here's is the grunt output:

```
Running "nodemon:dev" (nodemon) task
Verifying property nodemon.dev exists in config...OK
File: [no files]
Options: restartable="rs", verbose=false, watch=["server","!server/views","app.js"], env={"NODE_ENV":"development"}, ext="js json"
```

Which, in my particular case, results in:

```
[nodemon] watching 26,446 files - this might cause high cpu usage. To reduce use "--watch".
```

When I remove the `app.js` entry, the warning goes away. I believe the `app.js` rule ends up watching much more than just `app.js`.

I added `console.log(JSON.stringify(config));` to `lib/config/index.js` just before `ready(config)` is called and this is the output:

```
{
   "run":false,
   "system":{
      "cwd":"/Users/aahardy/dev/totem",
      "useFind":true,
      "useWatch":false,
      "useWatchFile":false
   },
   "required":true,
   "dirs":[
      "/Users/aahardy/dev/totem/server",
      "/Users/aahardy/dev/totem"
   ],
   "timeout":1000,
   "options":{
      "restartable":"rs",
      "verbose":false,
      "watch":[
         "server",
         "!server/views",
         "app.js"
      ],
      "env":{
         "NODE_ENV":"development"
      },
      "ext":"js,json",
      "script":"bin/www",
      "ignore":[
         ".git",
         "node_modules/**/node_modules"
      ],
      "execMap":{
         "py":"python",
         "rb":"ruby"
      },
      "stdin":true,
      "stdout":true,
      "execOptions":{
         "script":"bin/www",
         "exec":"node",
         "ext":"js,json",
         "env":{
            "NODE_ENV":"development"
         },
         "execArgs":[

         ]
      },
      "monitor":[
         "/Users/aahardy/dev/totem/server/**/*",
         "!/Users/aahardy/dev/totem/server/views/**/*",
         "app.js",
         "!/Users/aahardy/dev/totem/.git/**/*",
         "!node_modules/**/node_modules"
      ]
   },
   "lastStarted":0,
   "loaded":[

   ],
   "command":{
      "raw":{
         "executable":"node",
         "args":[
            "bin/www"
         ]
      },
      "string":"node bin/www"
   }
}
```

The `monitor` value shows `app.js` instead of a full path. I looked at `rulesToMonitor()` in `lib/monitor/match.js` and it appears to somewhat ignore paths that aren't directories.

I would love to be able to watch single files correctly. Thanks!

**Comment by netpoetica** [comment]
I personally still see this issue even with newest nodemon 1.17.5. If I tell it to watch one single file, w/ verbose mode it tells me it is watching 3000 files:

```
nodemon --verbose --inspect=6860 ./dist/app.js --watch
```

watches 5000+ files

```
nodemon --verbose --inspect=6860 ./dist/app.js --watch ./dist/app.js
```

watches 3000+ files.

I have tried removing configuration from nodemon.json to make sure sure ext isn't competing here, with same results. It must be looking in the dist/ directory completely, not just the dist/app.js file

**Comment by justinphilpott** [comment]
Any movement on this?
