### ISSUE TITLE
Proposal: ignore node_modules by default (again)

### ISSUE THREAD

**Issue by remy** [remy/nodemon#339]
Ref #230 

This has come up before, and though most people voted for ignoring `node_modules` in the end, the default ignore is `node_modules/**/node_modules` - which is actually causing high overheads still, i.e. #146.

I'm proposing, in a minor version bump, that nodemon ignores `node_modules` by default, and if users want to watch these by default, then they can include it as an additional watch in their global `nodemon.json` file quite easily.

I'd like input as a +1 or -1 and reasons why if appropriate.

I'm a +1 based on my own usage and the issues raised on github.

**Comment by KidkArolis** [comment]
@oncletom did you find a solution for restarting on symlinked module changes?

**Comment by oncletom** [comment]
@KidkArolis nope (and have not looked further — don't have this use case anymore)
