### ISSUE TITLE
[edited] use fsevents for faster reload response time on mac

### ISSUE THREAD

**Issue by simonexmachina** [remy/nodemon#342]
Have you looked at using [chokidar](https://www.npmjs.org/package/chokidar) to get a fast non-polling watcher implementation on OS X?

**Comment by Hossrod** [comment]
Is this still being considered? I just started using a mac (new mac book pro, OSX 10.11.1) and the delay is killing me. :)

On my windows machines, when I save in text editor, nodemon is pretty instant everytime, but on mac it's inconsistent, ranging from almost instant to several seconds. Most the time taking more than 3-4 seconds. When it is fast, it's usually when I just did another save just a few seconds ago.
