### ISSUE TITLE
'node' is not recognized as an internal or external command.

### ISSUE THREAD

**Issue by gnetsys** [remy/nodemon#346]
After closing the shell without exiting nodemon I get this error.

"'node' is not recognized as an internal or external command." when using nodemon

**Comment by heneryville** [comment]
I'm able to reproduce this issue from cygwin, but not from the normal windows command prompt. @gnetsys Where you using cygwin?

**Comment by gnetsys** [comment]
Yes, I was using cgywin but I have switched to node for windows.

**Comment by heneryville** [comment]
The funny thing is that node is indeed on my path in both CMD and cygwin. nodemon works fine from CMD, but not from cygwin.

@remy I think you can just call this cygwin weirdness and close. The workaround is to run from the standard windows command prompt.

**Comment by remy** [comment]
Yep, recommendation: use git shell.
