### ISSUE TITLE
Doesn't watch any directory under ../

### ISSUE THREAD

**Issue by efolio** [remy/nodemon#352]
Hi,

I work with the following project structure (not by choice…):
./core
./core/server.js
./custom
./custom/brand
./custom/brand/app.js

Platform:
Latest kubuntu, latest node (v0.10.28)

Command executed:
$ cd core
$ nodemon -V --watch ../custom server.js
12 Jun 15:22:15 - [nodemon] v1.2.0
12 Jun 15:22:15 - [nodemon] to restart at any time, enter `rs`
12 Jun 15:22:15 - [nodemon] ignoring: .git node_modules bower_components .sass-cache
12 Jun 15:22:15 - [nodemon] watching: /home/etienne/work/custom/**/*
12 Jun 15:22:15 - [nodemon] watching extensions: js
12 Jun 15:22:15 - [nodemon] starting `node server.js`
12 Jun 15:22:15 - [nodemon] child pid: 26693
12 Jun 15:22:15 - [nodemon] watching 1,432 files

Issue:
Nodemon doesn't restart the process if I save/overwrite any .js file inside ./custom.

Did I miss something or is there a real issue here?

Thanks in advance,

**Comment by bspot** [comment]
This doesn't work for me, with neither 1.3.5 nor 1.3.0-7, on Linux.

Minimal test case:

    mkdir -p test/a test/b
    echo 'setInterval(function() {console.log(".");}, 1000);' | tee test/a/a.js test/b/b.js
    cd test/a
    nodemon -w ../ a.js

Now

    touch test/a/a.js

will trigger a reload, while

    touch test/b/b.js

will not.

**Comment by remy** [comment]
This is a good simple test case that I can work with. I'll investigate.

If anyone else wants to investigate too, I'd be very grateful (as will
others in this thread).

**Comment by remy** [comment]
Just a heads up, I've found the fix and have it working, but my dev environment was totally borked which lead me down Red Herring Alley. You should see a fix coming in a day or so that fixes this.

**Comment by TroyWorks** [comment]
using 1.71 I still get this issue on windows 8.1, where a file in a parent directory (e.g. ../index2.html) or a sibling directory ../sibling/file) do not trigger chanages.  I tested by moving index2.html from place to place, inside the working director it works, anywhere else it doesn't.  This is the nodemon.json used.

{
  "restartable": "rs",
  "ignore": [
    ".git",
    "node_modules/**/node_modules"
  ],
  "verbose": true,
  "execMap": {
    "js": "iojs"
  },
  "watch": [
    "staticserver.js",
    "nodemon.json",
    "../index2.html",
    "public/env.js"
  ],
  "env": {
    "NODE_ENV": "development"
  },
  "ext": "js json html"
}

9 Oct 11:20:25 - [nodemon] 1.7.1
9 Oct 11:20:25 - [nodemon] reading config c:\Users\troyworks\Documents\Projects\frontend\nodemon.json
9 Oct 11:20:25 - [nodemon] to restart at any time, enter `rs`
9 Oct 11:20:25 - [nodemon] ignoring: c:\Users\troyworks\Documents\Projects\frontend\.git/**/* c:\Users\troyworks\Documents\Projects\frontend\node_modules/**/* bower_components .sass-cache c:\Users\troyworks\Documents\Projects\frontend\.git/**/* node_modules/**/node_modules
9 Oct 11:20:25 - [nodemon] watching: staticserver.js nodemon.json ../index.html public/env.js
9 Oct 11:20:25 - [nodemon] watching extensions: js,json,html
9 O
