### ISSUE TITLE
Unable to --exec "node ..."

### ISSUE THREAD

**Issue by tillda** [remy/nodemon#354]
I have troubles doing this:

nodemon -exec "node --debug server.js -p 6401 -e development" --watch ./server

Instead I get an error: Error: Cannot find module '/Users/...../server/node --debug server.js -p 6401 -e development'

I know that I may use the "direct" execution of server.js, but I still think that it is reasonable to expect that variant might be used.

**Comment by remy** [comment]
Can you give this another test with nodemon 1.3.x, I did a load of work on the exec parser so it might be fixed.

**Comment by tillda** [comment]
When I try:

nodemon --exec "node --debug apiserver.js -p 6401 -e development" --watch .

on the latest 1.3.2 it seems like the syntax isn't recognised. It outputs Usage and --help hint.

When I add --dump it writes this:

21 Jan 17:17:11 - [nodemon] v1.3.2
21 Jan 17:17:11 - [nodemon] to restart at any time, enter `rs`
21 Jan 17:17:11 - [nodemon] watching: *.*
--------------
node: v1.0.2
nodemon: v1.3.2
command: node /usr/local/bin/nodemon --dump --exec node --debug apiserver.js -p 6401 -e development --watch .
cwd: /Users/michal/Projects/Monaco/apiserver
OS: darwin x64
--------------
{ run: false,
  system:
   { cwd: '/Users/michal/Projects/Monaco/apiserver',
     useFind: true,
     useWatch: false,
     useWatchFile: false },
  required: false,
  dirs: [ '/Users/michal/Projects/Monaco/apiserver' ],
  timeout: 1000,
  options:
   { dump: true,
     exec: 'node --debug apiserver.js -p 6401 -e development',
     watch: [ '.', re: /\./ ],
     ignore:
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions:
      { exec: 'node',
        execArgs: [ '--debug apiserver.js -p 6401 -e development' ],
        script: null,
        args: [],
        scriptPosition: null,
        nodeArgs: undefined,
        ext: 'js',
        env: {} },
     monitor:
      [ '*.*',
        '!.git',
        '!/Users/michal/Projects/Monaco/apiserver/node_modules/**/*',
        '!bower_components',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command:
   { raw:
      { executable: 'node',
        args: [ '--debug apiserver.js -p 6401 -e development' ] },
     string: 'node --debug apiserver.js -p 6401 -e development' } }
--------------
