### ISSUE TITLE
Add restart-on-crash functionality to the required module API

### ISSUE THREAD

**Issue by wearhere** [remy/nodemon#364]
This issue differs from #175 in that I am not proposing to modify the `nodemon` binary's options, but rather the API of the required module (i.e., because I can't use `forever`).

It is not currently possible to restart my app when it crashes when using the required module e.g. `gulp-nodemon`. I can detect the crash by listening for the `crash` event, but then (as far as I can tell) there is no way to force `nodemon` to immediately start the app again. Rather, `nodemon` will only restart the app if its files change.

(Emitting `restart` from within the `crash` event handler does not work because of how `nodemon` currently restarts a process, which is to kill it and respond to its exit.)

I can think of a couple of ways to fix this:
1. Add a boolean flag `restartOnCrash` to the module's options, which would do what the name suggests.
2. Add either a `start` or `restart` method to the module, to be called from within a `crash` event handler. (I'm not sure what the semantics should be here, again because `nodemon` currently expects a process to-be-restarted to be alive.)
3. Make `reset` public (it doesn't seem to be currently), so I could teardown `nodemon` and repeat its setup.

Here is a minimal `gulpfile` which demonstrates my use case and my workaround using `reset`:

``` js
var gulp =  require('gulp'),
  nodemon = require('gulp-nodemon');

function runServer() {
  var demon = nodemon({ script: 'app.js' });
  demon.on('crash', function() {
    demon.reset();
    runServer();
  });
}

gulp.task('default', function() {
  runServer();
});
```

I'm glad to try my hand at fixing this if you let me know what direction you prefer.

**Comment by monothorn** [comment]
If it helps anyone , the following snippet can be used inside crash event for nodemon as shown

```
nodemon = require('gulp-nodemon');
nodemon.on('crash', function () {
        console.error('Application has crashed!\n');
       nodemon.emit('restart', 10) // restart the server in 10 seconds
    })
```

**Comment by FishOrBear** [comment]
```
var nodemon = require('nodemon');
function start()
{
    nodemon({
        script: "dist/server.js"
    });
    nodemon.on("crash", start)
}

start();
```
