### ISSUE TITLE
Source map support

### ISSUE THREAD

**Issue by tad-lispy** [remy/nodemon#374]
Is there a way to use source maps and debug coffee sources in node-inspector while running nodemon? That would be cool.

**Comment by ashishsc** [comment]
I also wonder about source maps for transpiled ES6 code. I use [babeljs](https://github.com/babel/babel) and it would be great if I could see those the source maps in the debugger.

**Comment by mt0erfztxt** [comment]
@remy yes, coffeescript has [cli option](http://coffeescript.org/#usage) for that `coffee-script -m`.
