### ISSUE TITLE
trying to watch parent directory doesn't work...

### ISSUE THREAD

**Issue by A-Zak** [remy/nodemon#377]
when I pass --watch ../ (or anything similar) it converts the dots into astrikses...
/:

**Comment by djengineerllc** [comment]
Same issue for me too.  I even tried putting in the absolute path and it doesn't work either.

**Comment by tnrich** [comment]
Anybody have a solution for this one?

**Comment by tleb** [comment]
```shell
mkdir -p /foo/bar
cd /foo/bar
nodemon -w ../
```

The result:

```
[nodemon] 1.9.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /foo/**/*
```

And it's the expected behaviour: we are watching anything in `/foo`, even if it is in subdirectories.

**Comment by unckleg** [comment]
Same problem here.

**Comment by tleb** [comment]
What behaviour have you got? What do you expect?

**Comment by unckleg** [comment]
When i try to watch ( ../ ) parent directory there is no response from nodemon on change.
Watching just works for files that are nested or in root of package.json file.

**Comment by keshavsaharia** [comment]
This seems to be working correctly in nodemon version 1.19.1 with both `--watch ..` and `--watch ../`.
