### ISSUE TITLE
I would like the ability to set a success and failure command.

### ISSUE THREAD

**Issue by wraithan** [remy/nodemon#380]
Currently I do things like making a bash script to check the return code of a command, then calls [`osx-notifier`](https://www.npmjs.org/package/osx-notifier) in various ways so I can see an alert when my unit tests fail or if my webserver crashes, etc.

I think it could be neat to offer `--success "command"` and `--failure "command"` akin to how `--exec "command"` works. If this is outside of scope of `nodemon`, I completely understand and could see a `nodemon` wrapper providing this capability.

**Comment by remy** [comment]
I'm going to close this. You've got a good solution by requiring nodemon, but also you can now set commands to run from the new events nodemon config which ...might need the exit code passed into the exit event but should do the job (see the readme for the event usage).
