### ISSUE TITLE
Using wildcards in nodemon execute command

### ISSUE THREAD

**Issue by jayasimhan** [remy/nodemon#384]
I use nodemon to push code to my remote server. When I use a wildcard in my execute command, it is not recognized as a wildcard but simply as a string. 

Example: 

This doesn't work
`nodemon -w projects/example/ -x "scp projects/example/* jay@server.com:/var/www" -e ".js"`

This works.
`nodemon -w projects/example/ -x "scp projects/example/app.js jay@server.com:/var/www" -e ".js"`

**Comment by remy** [comment]
Can you give this another try? I've changed the way nodemon runs the exec command so it could/should work (nodemon 1.3.x)
