### ISSUE TITLE
Way to see what directories are causing nodemon to watch so many files

### ISSUE THREAD

**Issue by ilanbiala** [remy/nodemon#388]
I  have a project that I don't think could have 20,000+ files unless we're including `node_modules/`, but nodemon ignores that by default. I think it makes sense for nodemon to also log how many files are in each of the folders in the same directory as the gulpfile. That way, a user can clearly see if he/she forgot a folder and it will tell him how many it has, so he doesn't have to spend time guessing to find out most likely that he forgot to ignore something.

**Comment by ilanbiala** [comment]
@remy any roadmap for 1.3 release?

**Comment by remy** [comment]
I'm literally whack-a-mole-ing my way through the last bugs, then I'll
merge it all together. Paid client work has slowed dev down, but it's
happening!

**Comment by ilanbiala** [comment]
@remy any progress on this?
