### ISSUE TITLE
Delete doesn't trigger a restart event

### ISSUE THREAD

**Issue by amjibaly** [remy/nodemon#400]
Is deleting a file not supposed to trigger a restart event? How can I capture a file being deleted? I've tried the following:

```bash
$ node
> require('nodemon')({ext: '*.*', exec: 'true', ignore: false, watch: process.cwd()}).on('restart', console.log);
```

Now, when I `touch abc` I see a `console.log` message, but nothing happens when I `rm abc`.

**Comment by pghalliday** [comment]
+1

**Comment by remy** [comment]
Please try with dev version. Details in #625

**Comment by pghalliday** [comment]
cool, i'll take a look - thanks :)

**Comment by remy** [comment]
#625 closes and released in `nodemon@1.4.2`

**Comment by JulianKniephoff** [comment]
Am I missing or misunderstanding something? I am running `nodemon@1.11.0` but deleting a watched file still does not trigger a restart for me. :thinking:

**Comment by darkguy2008** [comment]
Same here with 1.17.4

**Comment by etamponi** [comment]
Same here

**Comment by FireController1847** [comment]
Same here
