### ISSUE TITLE
nodemon doesn't like process.exit

### ISSUE THREAD

**Issue by Offirmo** [remy/nodemon#401]
This must be a linux feature I don't know but I find it strange enough to file an issue.

In [Controlling shutdown of your script](https://github.com/remy/nodemon#controlling-shutdown-of-your-script), nodemon doc states that we can listen to SIGUSR2 to clean exit.

However such a script doesn't work :
```javascript
process.once('SIGUSR2', function(code) {
	console.log('* SIGUSR2 detected');
	process.exit(0);
});

setInterval(function() {
	console.log('still alive...');
}, 2 * 1000);
```
nodemon detects this as `[nodemon] clean exit - waiting for changes before restart` or occasionally triggers the ECONNRESET (#397) or `Cannot read property 'pid' of null` (#390) 

However, by using the self kill technique, it works :
```javascript
process.once('SIGUSR2', function(code) {
	console.log('* SIGUSR2 detected');
	process.kill(process.pid, 'SIGUSR2');
});
```

Shouldn't nodemon handle app exit after it sends it SIGUSR2 ?

What is the difference between exiting and self-killing ?

**Comment by edi9999** [comment]
would like to see something like that merged :-)

**Comment by mariokostelac** [comment]
It is just not supposed to work.

If you look at the http://man7.org/linux/man-pages/man7/signal.7.html (and find Async-signal-safe functions), you will see the explanation.

```
A signal handler function must be very careful, since processing elsewhere may be interrupted at
some arbitrary point in the execution of the program. POSIX has the concept of "safe function".
If a signal interrupts the execution of an unsafe function, and handler calls an unsafe function,
then the behavior of the program is undefined.

POSIX.1-2004 (also known as POSIX.1-2001 Technical Corrigendum 2) requires an implementation 
to guarantee that the following functions can be safely called inside a signal handler:

... some functions including _exit, but not exit itself ...
```

The `exit` function is just not safe and you can not know the result of calling it from a signal handler. However, sending the same signal from a signal handler bound with 'once' works fine (because `kill` is safe).

**Comment by zygis** [comment]
I tried kill current process with SIGTERM instead Exit... Same problem...

**Comment by mariokostelac** [comment]
@zygis with the technique written in readme file (in nodejs, let's leave golang on a side for a moment)?

**Comment by zygis** [comment]
Sorry for delayed answer. Looks like problem gone, probably version updated. Today nodemon starting new process without waiting until process exit... But this is different issue :smile:

**Comment by remy** [comment]
@zygis I'm going to close then, but can you raise a new issue. Can you also let me know the full OS you're running on, because I've seen the same issue when running inside the node:slim docker, but it turned out it was because the `kill -S USR2SIG` wasn't supported at the OS level... :whale:

**Comment by zygis** [comment]
OS ubuntu 14.04 inside openVZ container (proxmoxVE). But this issue not very big problem. I using nodemon only for live testing with console.
