### ISSUE TITLE
Color issues on Windows 8

### ISSUE THREAD

**Issue by DannyBen** [remy/nodemon#405]
Hey,

Not sure if it is the same as issue #95 or not, but in any case, two items in this issue:
1. On Windows, the color is not reverted back to the default (screenshot below).
2. I would really like the ability to disable colors. 

![nodemon](https://cloud.githubusercontent.com/assets/2405099/4861007/846e7d18-60fe-11e4-8b12-083ab9c2d897.png)

Thanks.

**Comment by Nexum** [comment]
+1 thank you for nodemon!

**Comment by remy** [comment]
`nodemon --no-colors` landed in nodemon@1.6.0
