### ISSUE TITLE
Ignore directory but whitelist some subdirectories under it

### ISSUE THREAD

**Issue by raine** [remy/nodemon#421]
I'd like to not watch node_modules/ for changes, with the exception of some modules that I have `npm link`ed and develop concurrently with my app.

Any idea how to accomplish this? Thanks.

**Comment by avesus** [comment]
If I `require()` any file from within an ignored directory, nodemon doesn't restart my server. I was looking for a whitelist option without luck. Adding `watch` parameter explicitly asking nodemon to track a file within an ignored directory doesn't help at all, moreover, it's necessary to add `'*'` watch patch to keep it working. @remy ?

**Comment by Tim15** [comment]
Any updates on this?
