### ISSUE TITLE
Nodemon unresponsive on Ubuntu 14.04

### ISSUE THREAD

**Issue by Protosac** [remy/nodemon#422]
It installs smoothly, no errors. But using ANY commands with nodemon returns nothing. Not even an error. It's like it's not even there. Uninstalling and reinstalling doesn't fix it. Nodejs works just fine. Passing any command to nodemon, even nodemon -h or nodemon --dump returns a new line in the CLI and does absolutely nothing.

**Comment by remy** [comment]
Are we calling it a day on this issue now? I definitely think it's something to do with npm rather than node (we've seen other people having issues with forever and other scripts).

I'll add this to the FAQ, and use your final comment about using NVM to install instead of nodejs.

**Comment by sushiluvce** [comment]
apt-get install nodejs-legacy works fine :) ... thanks

**Comment by oosswwaalldd** [comment]
Just Edit the file /usr/local/bin/nodemon and change "node" for "nodejs". That worked for me!

**Comment by charleswhchan** [comment]
@ghost is right:  `apt-get install nodejs-legacy`

From the [nodejs-legacy package description|https://launchpad.net/ubuntu/trusty/+package/nodejs-legacy]:
> This package contains a symlink for legacy Node.js code requiring
> binary to be /usr/bin/node (not /usr/bin/nodejs as provided in Debian).

**Comment by markhinch** [comment]
I had the exact same issue and for me it happened after I changed my global node directory to rather be located in my home directory (so as not to have to sudo -g commands). That could be coincidental, but in any case, @oosswwaalldd nailed it for me:

> Just Edit the file /usr/local/bin/nodemon and change "node" for "nodejs". That worked for me!

(Except, of course, the path for me is not /usr/local/bin/nodemon but instead ~/.npm-packages/bin/nodemon

**Comment by princetoncollins** [comment]
I got a big problem!
I'm on Ubuntu 14.04 OS.
I've installed npm, nodejs, and nodemon like this:
`sudo apt-get install npm`
`sudo npm install nodejs`
`sudo npm install -g nodemon`

Everything installs just fine, no errors... but...

running `nodemon server.js` while in one of my app folders where my 'server.js' file is basically returns nothing at all. No error or any indication that there might be a problem? It simply makes the command line go to a new line after running it. 
Running `nodemon -v` also returns nothing. 

I can use `nodejs server.js`. That will get my server running, which is all good and well, but... 
I miss my nodemon!

Is there anyone that can help me with this problem?

**Comment by princetoncollins** [comment]
Read the posts here and ghost's suggestion to `apt-get install nodejs-legacy` worked for me.
Thanks, ghost! :)

**Comment by PaoloVeloce** [comment]
Found a solution in FAQ for nodemon here

https://github.com/remy/nodemon/blob/master/faq.md

Try to re-install adding --unsafe-perm to the arguments:
<code> sudo npm install -g nodemon --unsafe-perm </code>

That works for me

**Comment by elhardoum** [comment]
For me it doesn't work with `nodemon app.js` but it works with `nodemon npm start`.
