### ISSUE TITLE
Wish: HISTORY.md or Changelog.md

### ISSUE THREAD

**Issue by markstos** [remy/nodemon#428]
I'd be great to have a Changelog or HISTORY.md. This standard feature of software projects makes it easy for users to see the important changes been versions and decide whether not to upgrade. 

This request was previously filed in #262 and later closed, but current versions still lack a Changelog.

**Comment by ilanbiala** [comment]
@remy you realize that there is no description about what changed on that page..it just lists the versions you tagged and doesn't necessarily mean they were published on npm...please set something up. Take a look at this as a starting point https://github.com/ajoslin/conventional-changelog.

**Comment by remy** [comment]
All versions I tag are on npm.

**Comment by ilanbiala** [comment]
@remy I'm not saying that you do that, but it can happen, so the versions aren't guaranteed to be available.
