### ISSUE TITLE
execute command automatically on restart

### ISSUE THREAD

**Issue by benkaiser** [remy/nodemon#432]
I have a command to refresh the currently focussed browser window, and would like to be able to hook it into nodemon. Is there any chance an option could be added to the `nodemon.json` to run a command on restart?

Thanks a bunch! been using nodemon for months and love it!

**Comment by benkaiser** [comment]
Looks like the latest works fine, so a simple `sudo npm install -g nodemon@latest` fixed it.

Thanks @remy

**Comment by remy** [comment]
@benkaiser can you confirm what version nodemon is at? I got a bit confused with npm so latest might be pre-release, it might be 1.2.1...

**Comment by benkaiser** [comment]
Npm reports installing 1.2.1 but then nodemon --version returns 1.3.0-6.

and when I run `which nodemon` it gives me `/usr/bin/nodemon` as it should.

```
$ npm install -G nodemon@latest
nodemon@1.2.1 node_modules/nodemon
├── minimatch@0.3.0 (sigmund@1.0.0, lru-cache@2.5.0)
├── ps-tree@0.0.3 (event-stream@0.5.3)
└── update-notifier@0.1.10 (semver@2.3.2, chalk@0.4.0, request@2.51.0, configstore@0.3.2)
$ nodemon --version            
v1.3.0-6
```
