### ISSUE TITLE
Doesn't ignore 'node_modules/` by default anymore

### ISSUE THREAD

**Issue by ilanbiala** [remy/nodemon#440]
Gulp-nodemon doesn't ignore `node_modules/` by default anymore. I had to add it to the `ignore: []` to ignore the 25,000 files there...

**Comment by backflip** [comment]
I have the same issue with nodemon (the non-gulp version).

Not working: ```nodemon```
Not working: ```nodemon --ignore "node_modules"```
Working: ```nodemon --ignore "node_modules/"```

Turns out I had an old version installed in ```/usr/local/bin/nodemon``` which took precedence over the one installed with npm.
