### ISSUE TITLE
`\n` sequence in `--exec` argument needs a lot of escaping

### ISSUE THREAD

**Issue by gfxmonk** [remy/nodemon#448]
Let's say I want to print something nice whenever nodemon triggers. Something really exciting, like:

    line1
    line2

In the shell, this would be:

    $ echo -e "line1\nline2"

In nodemon, I tried this:

    $ ./bin/nodemon.js -x 'echo -e "line1\nline2"'

(prints `line1line2`)

OK, so I guess I need to escape that backslash:

    $ ./bin/nodemon.js -x 'echo -e "line1\\nline2"'

(prints `line1line2`)

Third time's a charm?

    $ ./bin/nodemon.js -x 'echo -e "line1\\\nline2"'

(prints `line1line2`)

_4th_ time's a charm?

    $ ./bin/nodemon.js -x 'echo -e "line1\\\\nline2"'

success.

I am not sure what's causing this, but it feels to me like the amount of escaping required here is unreasonable.

For bonus points, if you try using double-quotes on the outside, and single quotes on the inside, you need a whopping _seven_ backslashes before it works:

    $ ./bin/nodemon.js -x "echo -e 'line1\\\\\\nline2'"

(prints `line1line2`), while:

    $ ./bin/nodemon.js -x "echo -e 'line1\\\\\\\nline2'"

works.

(all tested on current HEAD, 43ad1d82a2880bcc89913e58f3b44f0c26077d67)

**Comment by gfxmonk** [comment]
> The example in the end of your comment isn't correct.

> $ echo 'line1\nline2'

> Is not the equivalent to

> spawn('echo', ['-e', 'line1\\nline2'],{ stdio: ['pipe', process.stdout, process.stderr] });

> It's the equivalent to:

> spawn('echo', ['-e', '\'line1\\nline2\''],{ stdio: ['pipe', process.stdout, process.stderr] });

No, that's not true.

Here, I'll use `strace` to dump the actual syscall arguments to `execve`:

    $ strace -eexecve echo -e 'line1\nline2'
    execve("/usr/bin/echo", ["echo", "-e", "line1\\nline2"], [/* 70 vars */]) = 0

    # my code: produces the exact same syscall
    $ cat /tmp/mine.js 
    require('child_process').spawn('echo', ['-e', 'line1\\nline2']);
    $ strace -f -eexecve node /tmp/mine.js 2>&1 | fgrep /usr/bin/echo
    [pid  4380] execve("/usr/bin/echo", ["echo", "-e", "line1\\nline2"], [/* 69 vars */]) = 0
    
    # your code: includes literal single quote characters
    $ cat /tmp/yours.js 
    require('child_process').spawn('echo', ['-e', '\'line1\\nline2\'']);
    $ strace -f -eexecve node /tmp/yours.js 2>&1 | fgrep /usr/bin/echo
    [pid  4411] execve("/usr/bin/echo", ["echo", "-e", "'line1\\nline2'"], [/* 69 vars */]) = 0

So my echo command is equivalent to the JS code I provided - it's making the exact same syscall. The JS code you provided is equivalent to:

    $ strace -eexecve echo -e "'line1\\nline2'"
    execve("/usr/bin/echo", ["echo", "-e", "'line1\\nline2'"], [/* 70 vars */]) = 0

(note the single quotes _inside_ the double quotes in both the bash command and the strace output)

> Using quotes simply doesn't map one to one to JavaScript

I'm afraid I have no idea why that would be relevant. You're saying that shell syntax and JS syntax are different, which is definitely true. But (as far as I know):
 - bash (obviously) takes shell syntax
 - nodemon's arg-parsing code splits on spaces and expects special characters to be slash-escaped or surrounded by quotes, so that's also shell-style syntax
 - nodemon's command executing code pumps everything through `sh`, which is again shell-style syntax.

So I'm not really sure where JS syntax even comes into it, aside from when writing test cases. Is that what you meant? It doesn't _sound_ like it, since you seem to be trying to find a command line argument which is represented the same way in both shell syntax and JS, but I don't know why you want that.

**Comment by remy** [comment]
To confirm - *I am doing this for tests*, because if I can't test it, I can't say it works.

So, in your example, now change your simple script to read the command that you want to run (in node) from the CLI. It would read *something* like this (note, that I've not tested this, it could be wrong):

```bash
cat /tmp/mine.js 
var args = process.argv[2]; // get everything after the script
var cmd = args.split(' ').shift(); // assumes simple space split
var arg = args.split(' ').slice(1);·
require('child_process').spawn(cmd, arg, { stdio: ['pipe', process.stdout, process.stderr ] });
```

And run `/tmp/mine.js` with the echo command, *something* like this:

```bash
node /tmp/mine.js "echo -e 'line1\nline2'"
```

This is the crux of the escape character bug. 

Also - **I am not running this through the `sh` solution** - I'm running this through the original spawn method. I'm *trying* and failing to support this case, because I can't capture what's passed through on the command line fully. The reason it worked when you checked out the earlier commit (prior to the `sh` change), is because there's a bug in the `parseExecutable` that's masking the real issue.

**Comment by remy** [comment]
Right, circling right back to the original issue, this is down to a bug in my parser. This line: https://github.com/remy/nodemon/commit/acf4d61c791f4d620fcf4fa5508ec6d12490a593#diff-923eb16b02782fddeffbb6a92c297ea6R25 should *not* be skipping the `\` character (which meant it was being lost).

[This version](https://github.com/remy/nodemon/blob/fix/exec-parser/lib/config/exec.js#L8) of `exec.js:parseExecutable` fixes the parsing issue. 

I'm trying to address your bugs one at a time, because the overlap in the bugs is causing an insane amount of confusion. Feel free to contribute test that are specific to the problem on the PRs.

**Comment by gfxmonk** [comment]
Thanks, yeah I apologize for the overlapping issues, but not being very familiar with how the parsing works I can't really tell which issues are in the parsing code and which are on the `spawn()` code.

I did write this test case (for test/fork/run.test.js), which I think covers this specific issue. I used `node` instead of `echo` for the testing due to the platform differences with the `-e` flag:

    var echoWithNode = process.execPath + ' -e "console.log(process.argv[1])" ';
    ;[
      '"line1\\nline2"',
      "'line1\\nline2'",
      "line1\\\\nline2",
    ].forEach(function(cmd) {
      it('should pass '+cmd+' through correctly', function (done) {
        var found = false;
        var p = run({
          exec: 'bin/nodemon.js',
          args: ['-q', '--exec', echoWithNode + cmd]
        }, {
          error: function (data) {
            p.send('quit');
            done(new Error(data));
          },
          output: function (data) {
            process.stdout.write(data);
            if (data.trim() === 'line1\\nline2') {
              found = true;
            }
          }
        });

        p.on('message', function (event) {
          if (event.type === 'start') {
            setTimeout(function () {
              p.send('quit');
              done();
              assert(found, '"OK" message found');
            }, 500);
          }
        });
      });
    });


Your commit b905ffae7d9ba1e8c3c49eeab3ecc59ccadbc1c7 already passes these tests, so that's a good sign.

I'm not sure whether more focused unit tests would be appropriate - as far as I can tell this sort of thing can be broken fairly easily by incorrect parsing _or_ incorrect flags to the actual `spawn` function, so testing only one half of that process (e.g just testing the parsing) is unlikely to be very useful.
