### ISSUE TITLE
Using a real throttle instead of a delay

### ISSUE THREAD

**Issue by edi9999** [remy/nodemon#451]
I need to use a delay because of multiple file changes. However, the current option waits for the specified time before starting to run the script. I would expect it to work like a throttle, eg: when the first file changes it gets executed once. Then, if an other file changes during that time, it will get executed only if the last file that was changed has been changed during the last n seconds.

Does that make more sense to you too ?

**Comment by remy** [comment]
Sure, that makes sense. Want to have a crack at a pull request?

**Comment by remy** [comment]
Implemented via #452
