### ISSUE TITLE
Nodemon doesn't work if `ps` is not installed on system

### ISSUE THREAD

**Issue by olalonde** [remy/nodemon#454]
```bash
...
5 Jan 16:27:16 - [nodemon] watching 20 files
rs
exception in nodemon killing node
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

----------------------------------------------------------
If appropriate, please file an error with the output from:
$ node /app/node_modules/.bin/nodemon --verbose --remote index.js --dump
At http://github.com/remy/nodemon/issues/new
----------------------------------------------------------
```

psTree uses the `ps` utility but it is not necessarily available on all systems. It would be good if that dependency could be removed.

**Comment by remy** [comment]
This is a slimmed down system isn't it. Darnit. 

I guess it could do a test for `ps` command line support, then just kill the parent process (which works most of the time).

**Comment by olalonde** [comment]
>I guess it could do a test for ps command line support, then just kill the parent process (which works most of the time).

Yep, I think that would be good enough for now :+1:

**Comment by remy** [comment]
I've got an offline branch of this working.
