### ISSUE TITLE
.nodemonignore ignored if nodemon.json defined

### ISSUE THREAD

**Issue by cazgp** [remy/nodemon#456]
I have symlinked .gitignore to .nodemonignore, and have also created nodemon.json to specify other settings. However, the presence of nodemon.json causes .nodemonignore to be ignored, even though the "ignore" field is not set in the json file. .nodeignore works perfectly when the nodemon.json is not there.

A very basic example of the nodemon.json is:

    {
        "verbose": "true",
        "ext": "coffee,js,json"
    }

Is this expected behaviour or a bug? If it's expected behaviour, please update the documentation as a gotcha!

**Comment by remy** [comment]
This is expected. nodemon.json supersedes the .nodemonignore method.
