### ISSUE TITLE
Ignore response code?

### ISSUE THREAD

**Issue by gavD** [remy/nodemon#466]
Hi,

I am running some unit tests with:

```bash
nodemon -L --exec "bin/kahlan" -e php --delay 1ms
```

Kahlan has a feature which allows me to run a subset of my test suite, which I am using, and it works great, except using that feature causes it to return a response code of -1 so NodeMon reports it as a crash.

This isn't a problem with NodeMon as such, but it would be great if I could get it to ignore the response code. Is there a switch for this?

Thanks,
- Gavin

**Comment by remy** [comment]
Isn't any non-zero response considered "command failed to execute"?

**Comment by gavD** [comment]
Yes it is, I guess I'll live with it in this case, might take it up with
Kahlan instead

**Comment by remy** [comment]
Happy for me to close this then?

**Comment by AKST** [comment]
Because I like to use nodemon mostly for recompiling haskell code and running tests suites, whenever the GHC encounters a type error it exit with exit code 1 and normally when my tests fail it exits in a similar fashion.

Is there still a way to ignore exit code?
