### ISSUE TITLE
Update docs to include events in nodemon.json

### ISSUE THREAD

**Issue by remy** [remy/nodemon#470]

**Comment by iamwave007** [comment]
I updated my nodemon to the most recent on. it started to break
When I use   nodemon server.js    in one of my apps, it comes up error likes this: 
20 Jan 04:13:13 - [nodemon] starting `server.js server.js`
sh: server.js: command not found
20 Jan 04:13:13 - [nodemon] app crashed - waiting for file changes before starting...


this doesn't happen to all apps. Why?

**Comment by iamwave007** [comment]
my bad. my package.json is messed up. it's all good
