### ISSUE TITLE
Option to prevent restarts while process is running

### ISSUE THREAD

**Issue by jamesshore** [remy/nodemon#473]
I'm trying to use nodemon along with a build script (not Grunt or Gulp, though). If nodemon detects a change while the build is running, it kills the build and restarts. This can cause problems in some cases. I'd like it to wait for the build to complete before starting another one.

Is there an option for nodemon to wait until the current process has exited before starting a new one? If not, can it be added?

**Comment by remy** [comment]
Using the delay will denounce until changes stop occurring. That might do
the trick.

**Comment by jamesshore** [comment]
That's actually a bit different. I want the build to occur again, I just don't want the process to be killed.

Current behavior:
1. I change a source file
2. Build starts
3. I change another source file.
4. Build is killed and left in bad state
5. Build is restarted and fails due to bad state

Desire behavior:
1. I change a source file
2. Build starts
3. I change another source file.
4. Nothing happens, but another build is queued up.
5. First build ends.
6. New build starts.
7. (etc)

**Comment by remy** [comment]
This is very bespoke. I can see delay letting you touch a file, touch another then when you're completely done, it builds.

Other than that, I think the proposed middleware in #310 might help solve your problem?

**Comment by jamesshore** [comment]
#310 looks like the same motivation but I don't understand how the middleware would help. Basically, I'm trying to avoid the "kill" part of nodemon's "when change occurs, kill process, wait for it to exit, and start a new one." Instead, I want the behavior, "when change occurs, wait for process to exit and start a new one." 

I can use the 'delay' option to achieve this result, but it's a race condition. I'd have to keep tweaking it as my build times changed.

I think this behavior would be valuable for anybody who wants to use nodemon with short-lived scripts that are assumed to run to completion. I previously wrote my own script to do this, and I can go back to it, but I think others would benefit from this feature and I'd rather use nodemon than reinvent the wheel.
