### ISSUE TITLE
doesn't honor command line argument order

### ISSUE THREAD

**Issue by morganrallen** [remy/nodemon#477]
The nodemon command line is described in --help as

```
Usage: nodemon [options] [script.js] [args]
```

The problem is, that is one of the `[args]` contains a valid nodemon argument, it is handled by nodemon rather than being passed to the application.

example:

```
nodemon -q index.js --help
````

This I'd expect to show the index.js help message, instead I get the nodemon help.

**Comment by remy** [comment]
No, this is normal (and happens in othersl scripts). Because you can put your script anywhere or even omit it, nodemon reads it's own args then ignores everything it doesn't recognise.

What you need is (the standard) `--` switch.

```
nodemon -q index.js -- --help
```

(In fact, this switch was in the nodemon help!)
