### ISSUE TITLE
TypeError: Cannot read property 'pid' of null

### ISSUE THREAD

**Issue by not-implemented** [remy/nodemon#478]
A very rare error when doing file-system updates very frequently:

    $ nodemon -x npm test
    ...
    ...
    23 Jan 10:13:48 - [nodemon] restarting due to changes...
    make: *** [test] Error 1
    23 Jan 10:13:48 - [nodemon] restarting due to changes...
    npm ERR! Test failed.  See above for more details.
    npm ERR!23 Jan 10:13:48 - [nodemon] restarting due to changes...
     not ok code 0
    23 Jan 10:13:48 - [nodemon] app crashed - waiting for file changes before starting...
    exception in nodemon killing node
    TypeError: Cannot read property 'pid' of null
        at ChildProcess.<anonymous> (/opt/nodejs/v0.10.30/lib/node_modules/nodemon/lib/monitor/run.js:135:46)
        at ChildProcess.emit (events.js:98:17)
        at maybeClose (child_process.js:756:16)
        at Process.ChildProcess._handle.onexit (child_process.js:823:5)

    ----------------------------------------------------------
    If appropriate, please file an error with the output from:
    $ node /opt/nodejs/v0.10/bin/nodemon -x npm test --dump
    At http://github.com/remy/nodemon/issues/new
    ----------------------------------------------------------

    $ node /opt/nodejs/v0.10/bin/nodemon -x npm test --dump
    23 Jan 10:21:22 - [nodemon] v1.2.1
    23 Jan 10:21:22 - [nodemon] to restart at any time, enter `rs`
    23 Jan 10:21:22 - [nodemon] watching: *.*
    --------------
    node: v0.10.30
    nodemon: v1.2.1
    command: node /opt/nodejs/v0.10/bin/nodemon -x npm test --dump
    cwd: /home/mplomer
    OS: linux x64
    --------------
    { run: false,
      system:
       { cwd: '/home/mplomer',
         useFind: false,
         useWatch: true,
         useWatchFile: false },
      required: false,
      dirs: [ '/home/mplomer' ],
      timeout: 1000,
      options:
       { scriptPosition: null,
         exec: 'npm',
         dump: true,
         script: 'test',
         args: [],
         ignore:
          [ '.git',
            'node_modules',
            'bower_components',
            '.sass-cache',
            re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
         watch: [ '*.*', re: /.*\..*/ ],
         restartable: 'rs',
         execMap: { py: 'python', rb: 'ruby' },
         stdin: true,
         verbose: false,
         stdout: true,
         execOptions:
          { script: 'test',
            exec: 'npm',
            args: [],
            nodeArgs: undefined,
            ext: 'js',
            env: {},
            execArgs: [] },
         ext: 'js',
         monitor:
          [ '*.*',
            '!.git',
            '!node_modules',
            '!bower_components',
            '!.sass-cache' ] },
      load: [Function],
      reset: [Function: reset],
      lastStarted: 0,
      loaded: [],
      command:
       { raw: { executable: 'npm', args: [ 'test' ] },
         string: 'npm test' } }
    --------------

**Comment by remy** [comment]
Thanks. I'm on holidays atm but I can imagine where this issue is and should be relatively simple to fix (unless you want to take a crack at a pull request, it just needs to test the child has a pid in `run.js` referred to in the trace you posted).

**Comment by remy** [comment]
This looks to be fixed in the latest nodemon (1.3.2) as it now [checks for the child](https://github.com/remy/nodemon/blob/master/lib/monitor/run.js#L192) before accessing the `pid`.

If you upgrade using `npm install nodemon@latest` you'll get the fix.
