### ISSUE TITLE
Not restarting for some files on Windows because of case issues

### ISSUE THREAD

**Issue by hgwood** [remy/nodemon#482]
On Windows, Nodemon will not restart the app on file changes if `process.cwd()` returns a path starting with a lower case driver letter.

This is caused by 2 divergent ways of processing paths :
- In `watch.js`, on line 249, the drive letter of watched files is forced to upper case.
- In `match.js`, on line 55, `process.cwd()` is used to resolve paths for rules, without any further processing.

=> drive letter case differ, and paths don't match.

Since the Windows file access API is always case insensitive (whatever the file system is, as far as I can tell), paths comparison should ignore case. Note that minimatch supports a `nocase` option that could be used when running on Windows, instead of manually messing around with the drive letter case.

Tested on 1.3.0-7 under Windows 7 64 bits, but references to code above refer to master, where it looks unchanged.

**Comment by remy** [comment]
Thanks for the detailed issue. Do you think you'd want to have a crack at a
PR, it sounds like you might be in a good position to test and confirm the
fix?

**Comment by hgwood** [comment]
I'll see what I can do. :)

**Comment by remy** [comment]
:heart: awesome!
