### ISSUE TITLE
Unignore files

### ISSUE THREAD

**Issue by yosheeck** [remy/nodemon#487]
Is there a way to un-ignore node_modules in local file ?

When I'm making changes in node_modules, nodemon ignores them. And it is impossible to make nodemon watch those changes.

**Comment by remy** [comment]
[watch](https://github.com/remy/nodemon#monitoring-multiple-directories) should work, no?

**Comment by yosheeck** [comment]
No, it looks like watch is "applied" before ignore is applied. So, ignore has "higher priority".
If I put a* to ignore-list, then putting abc to watch-list does nothing.

**Comment by harscoet** [comment]
+1

**Comment by amitport** [comment]
:+1:

**Comment by tomfun** [comment]
How to ignore a directory, but except some files, my attempt:
```json
{
  "verbose": false,
  "delay": 200,
  "watch": [
    ".",
    "build/frontend/components/html/"
  ],
  "ignore": [
    "src/",
    "build/frontend/",
    "node_modules/",
    "typings/",
    "public/"
  ]
}
```
