### ISSUE TITLE
high cpu usage if I use ignore parameter

### ISSUE THREAD

**Issue by icebob** [remy/nodemon#493]
If i use -i parameter to ignore some files, it cause high CPU usage.
Cmd: `nodemon server.js -e js -i gulpfile.js`
nodemon v1.3.6
os: win7 x86

**Comment by remy** [comment]
Are you able to debug and also provide detailed information on what's
causing the high CPU usage?

**Comment by icebob** [comment]
Is it help you?
```
3 Feb 12:15:50 - [nodemon] v1.3.6
3 Feb 12:15:50 - [nodemon] to restart at any time, enter `rs`
3 Feb 12:15:50 - [nodemon] watching: *.*
--------------
node: v0.10.35
nodemon: v1.3.6
command: node C:\Users\norbi\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.js server.js -e js -icwd: D:\Store\mindbooks
OS: win32 ia32
--------------
{ run: false,
  system:
   { cwd: 'D:\\Store\\mindbooks',
     useFind: false,
     useWatch: false,
     useWatchFile: true },
  required: false,
  dirs: [ 'D:\\Store\\mindbooks' ],
  timeout: 1000,
  options:
   { ignore: [ 'gulpfile.js', re: /gulpfile\.js/ ],
     dump: true,
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions:
      { script: 'server.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor: [ '*.*', '!gulpfile.js' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command:
   { raw: { executable: 'node', args: [ 'server.js' ] },
     string: 'node server.js' } }
--------------
```

**Comment by remy** [comment]
No a great deal. It just gives me your config, but says nothing about the
source of the issue.

**Comment by remy** [comment]
Again, are you able to include any information on the high cpu - perhaps from the task manager? Also, can you replicate this with a simplified repo that I could use to test against?

**Comment by icebob** [comment]
Ok, i'm trying to reproduce...

**Comment by icebob** [comment]
OK, i can reproduce this problem. If I have a lot of modules in node_modules, the problem is appear.
I making a sample repo...

**Comment by icebob** [comment]
This is a sample repo: https://github.com/icebob/nodemon-highcpu-test
Before you test, please run `npm install`, that you have many installed modules in node_modules folder too.
After it, if you exec `noproblem.bat`, it's running normally, no cpu usage.
But if you exec `highcpu.bat`, the cpu usage is 100%.
![image](https://cloud.githubusercontent.com/assets/306521/6040165/0eabfd6e-ac6f-11e4-8915-0a2040e84078.png)

**Comment by remy** [comment]
Looks like this should be good to help me diagnose.

I'll fire up my windows VM and let you know how it goes.

**Comment by remy** [comment]
I've started to test this, but the build is taking AGES. On top of which, the `package.json` is invalid (the name can't have a space in it). Any chance you can resubmit a repo that replicates that doesn't include so many dependencies? Or maybe that's the issue? 

My `npm install` has been running for 15 minutes and still not finished (and there's a bunch of errors which I suspect means it'll bail anyway).

I'm going to give up the install if it takes another 10 minutes. I hope you're able to create a simplified repo for me to test with.

Cheers,

– Remy

**Comment by remy** [comment]
Can you post me a tiny bit of extra information, and *try* one additional thing.

Firstly, when you start up the script, can you paste the output of `nodemon server.js -e js -i gulpfile.js -V` up the first natural pause (I'm specifically looking for the line that reads "watching N files").

Secondly, can you try running the following and check the CPU usage: `nodemon server.js -e js -i gulpfile.js -i node_modules`

**Comment by icebob** [comment]
Result of `nodemon server.js -e js -i gulpfile.js -V`:
```
11 Feb 15:11:23 - [nodemon] v1.3.6
11 Feb 15:11:23 - [nodemon] to restart at any time, enter `rs`
11 Feb 15:11:23 - [nodemon] ignoring: gulpfile.js
11 Feb 15:11:23 - [nodemon] watching: *.*
11 Feb 15:11:23 - [nodemon] watching extensions: js
11 Feb 15:11:23 - [nodemon] starting `node server.js`
11 Feb 15:11:23 - [nodemon] child pid: 4636
11 Feb 15:11:28 - [nodemon] watching 0 files
```
and the second command is good. It's running properly with low CPU.

**Comment by remy** [comment]
Yeah, I think I figured it out when I realised you had so many deps on the project. The fact it's saying it's watching "0 files" is suspicious/wrong! :)

Glad it's sorted.

**Comment by icebob** [comment]
But why working well, if I don't use the `-i` flag? In this case doesn't watch the node_modules?

**Comment by remy** [comment]
Can you repeat the question? I didn't understand quite what you were asking.

**Comment by icebob** [comment]
My base problem was, if I run nodemon with ignore parameter `nodemon server.js -e js -i gulpfile.js`, it caused high CPU. But if I skip ignore parameter `nodemon server.js -e js`, it's running normally.

So if I skip -i parameter, nodemon doesn't watch the node_modules folder?

**Comment by mkyung** [comment]
I have the same problem as well, using gulp

    gulp.task "nodemon", ->
        child = spawn("nodemon", [
            "-e"
            "coffee"
            "-i"
            "./static/private/*/**"
            "--harmony"
            "server.coffee"
        ], cwd: process.cwd())
        child.stdout.pipe(process.stdout)
        child.stderr.pipe(process.stderr)
