### ISSUE TITLE
Express 4

### ISSUE THREAD

**Issue by VVCepheiA** [remy/nodemon#494]
The start command for Express 4 should be 
```sh
$ nodemon bin/www
```
or just
```sh
$ nodemon
```
due to the change in package.json in Express 4. I spent ~10 mins on it so to save some Googling for others, I think it would be nice to add it in the README.

**Comment by remy** [comment]
I've no idea what your setup is.

Please include a test repo or directions to replicate.

**Comment by VVCepheiA** [comment]
@remy Hi, by __default__ I mean http://expressjs.com/starter/generator.html

**Comment by VVCepheiA** [comment]
@remy  To further simplify the setup to save your time, please just use the following lines. 
```sh
$ npm install express-generator -g
```
```sh
$ express default
```
```sh
$ cd default && npm install
```
```sh
$ nodemon app.js 3000
```

**Comment by remy** [comment]
I followed these directions, and you're right that `nodemon app.js 3000` does nothing, but equally, `node app.js 3000` does nothing too.

But when I run `nodemon` it *does* work.

The same when I follow the directions that `express-generator` gives:

```
DEBUG=default:* ./bin/www
```

This says to run with the env value `DEBUG` and run `./bin/www` under (we assume), node.

So we put nodemon in front of the executable:

```
$ DEBUG=default:* nodemon ./bin/www
4 Feb 10:21:29 - [nodemon] v1.3.6
4 Feb 10:21:29 - [nodemon] to restart at any time, enter `rs`
4 Feb 10:21:29 - [nodemon] watching: *.*
4 Feb 10:21:29 - [nodemon] starting `node ./bin/www`
  default:server Listening on port 3000 +0ms
GET / 304 170.569 ms - -
GET /stylesheets/style.css 304 6.205 ms - -
```

I don't think there's anything misleading here. You can't run your express app using `node app.js`, so it stands to reason that nodemon can't run it either.

**Comment by VVCepheiA** [comment]
I know `nodemon` does work... So is `nodemon bin/www`. That's why I put it in my very first comment: "The start command for Express 4 should be  `$ nodemon bin/www` or just `$ nodemon `". 
 For `nodemon ./server.js localhost 8080 ` (from the README) I couldn't really see the different between app.js and server.js. I might be wrong though.
Anyway, I was not here to argue but just trying to offer simple improvement suggestions, since I couldn't find them there at first and I thought other people using Express 4 might want it. However, totally fine if you don't think it necessary so let's stop here. @remy Thanks for your time.

**Comment by remy** [comment]
Ah, okay, I see where we've gone wrong. The server.js was (supposed to be)
a contrived example, rather than specific to any framework.

I'll update the readme to that effect, but also add a point about express
in the FAQ.

Cheers.
