### ISSUE TITLE
How to disable first time "--exec"?

### ISSUE THREAD

**Issue by txchen** [remy/nodemon#495]
I am using nodemon like this:
nodemon -w xxxx --exec "my build command"

After launching this command, build command will be triggered. I want to avoid this "first time" trigger, since nothing has changed yet. Any hints?

**Comment by remy** [comment]
Use the shell to test if you've run once already or not.

**Comment by txchen** [comment]
could you please share an example how we can write this shell?

**Comment by remy** [comment]
Afraid not. Stackoverflow is probably the best place for that.

You just want a script that runs in a loop and if the loops has run once
already, then run your script.

**Comment by txchen** [comment]
Write a bash which loop in one line is not easy to read, IMHO. I am using the tool in npm script, and creating another .sh looks too heavy.

But never mind, I have found another tool called [rewatch](https://www.npmjs.com/package/rewatch) which behaves like I described.
Basically I think it is more natural to "detect the change, then trigger something".

Close this one, and hope my information can be useful to others.

**Comment by jgoux** [comment]
I think the -x option shouldn't trigger the first time.
As @txchen said, it watches for change, so when you start the command, nothing has changed yet.
If you look at node-sass watch option for example, it doesn't trigger until there is a change.

**Comment by remy** [comment]
`-x` is used to run the script. So since nodemon runs and restarts, you're saying that it shouldn't run. If this was used to run a node app (for instance), the server would *only* start when you *restarted* which doesn't make sense.

I'd be open to a `-X` option added (expanded to `--exec-on-change`) via a PR. I'm not 100% sure of what's involved in the change, but it would also have to come with tests.

**Comment by Jokero** [comment]
I'm also wondered that `nodemon` immediately executes a command although files were not changed

**Comment by KATT** [comment]
Reviving this old issue. 

I wanna have a stab at implementing this, could I get some pointers where to look?

**Comment by KATT** [comment]
`--on-change-only`
