### ISSUE TITLE
"rs" not working with windows node 0.12.0 [edited]

### ISSUE THREAD

**Issue by grbspltt** [remy/nodemon#499]
When manually restarting nodemon with `rs` in the console, it immediately exits with this error:

```
exception in nodemon killing node
Error: write after end
    at writeAfterEnd (_stream_writable.js:167:12)
    at Socket.Writable.write (_stream_writable.js:214:5)
   at Socket.write (net.js:625:40)
    at ReadStream.ondata (_stream_readable.js:540:20)
    at ReadStream.emit (events.js:129:20)
    at readableAddChunk (_stream_readable.js:163:16)
    at ReadStream.Readable.push (_stream_readable.js:126:10)
    at TTY.onread (net.js:529:20)

----------------------------------------------------------
If appropriate, please file an error with the output from:
$ node C:\Users\Kevin\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.js --dump
At http://github.com/remy/nodemon/issues/new
----------------------------------------------------------
```

Running node v0.12.0

**Comment by grbspltt** [comment]
Dump log:
OS: win32 ia32
--------------
{ run: false,
  system:
   { cwd: 'C:\\nodeProj\\Dashboard',
     useFind: false,
     useWatch: false,
     useWatchFile: true },
  required: false,
  dirs: [ 'C:\\nodeProj\\Dashboard' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions:
      { script: 'index.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor:
      [ '*.*',
        '!.git',
        '!C:\\nodeProj\\Dashboard\\node_modules/**/*',
        '!bower_components',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command:
   { raw: { executable: 'node', args: [ 'index.js' ] },
     string: 'node index.js' } }
--------------

**Comment by grbspltt** [comment]
Downgraded to node v0.10.35 and this error goes away.

**Comment by remy** [comment]
Cheers - I'll start testing 0.12.x and add it to the travis tests.
