### ISSUE TITLE
Not able to start nodemon server: Exception in nodemon killing node

### ISSUE THREAD

**Issue by rohit13** [remy/nodemon#504]
## Error:

13 Feb 12:15:50 - [nodemon] v1.3.7
13 Feb 12:15:50 - [nodemon] to restart at any time, enter `rs`
13 Feb 12:15:50 - [nodemon] watching: _._
13 Feb 12:15:50 - [nodemon] starting `node C:\mykad\server.js`
exception in nodemon killing node
Error: spawn cmd ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)
## Output from nodemon --dump:

13 Feb 12:26:44 - [nodemon] v1.3.7
13 Feb 12:26:44 - [nodemon] to restart at any time, enter `rs`
13 Feb 12:26:44 - [nodemon] watching: _._

node: v0.12.0
nodemon: v1.3.7
command: node C:\Users\rohitsha\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.js --dump
cwd: C:\Program Files\nodejs
OS: win32 x64

{ run: false,
  system:
   { cwd: 'C:\Program Files\nodejs',
     useFind: false,
     useWatch: false,
     useWatchFile: true },
  required: false,
  dirs: [ 'C:\Program Files\nodejs' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /.git|node_modules|bower_components|.sass-cache/ ],
     watch: [ '_._', re: /._.._/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions:
      { script: null,
        exec: 'node',
        args: [],
        scriptPosition: null,
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor:
      [ '_._',
        '!.git',
        '!C:\Program Files\nodejs\node_modules/*_/_',
        '!bower_components',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command: { raw: { executable: 'node', args: [] }, string: 'node' },
  offset: 0 }

**Comment by rohit13** [comment]
Why nobody is commenting anything on this issue? Have I missed out on any procedure?

**Comment by remy** [comment]
Can you share the code or a way to replicate what you're seeing on windows?

**Comment by gcmicah** [comment]
hello, I'm having the same problem I'm running Win 7 Prof. Any help is appreciated. 

C:\nodejs\myRESTAPI>nodemon server.js
25 Mar 13:56:34 - [nodemon] v1.3.7
25 Mar 13:56:34 - [nodemon] to restart at any time, enter `rs`
25 Mar 13:56:34 - [nodemon] watching: *.*
25 Mar 13:56:34 - [nodemon] starting `node server.js`
exception in nodemon killing node
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

----------------------------------------------------------
If appropriate, please file an error with the output from:
$ node C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.j
s server.js --dump
At http://github.com/remy/nodemon/issues/new
----------------------------------------------------------

Here is the dump:

--------------
node: v0.10.33
nodemon: v1.3.7
command: node C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\nodemon\bin\no
demon.js server.js --dump
cwd: C:\nodejs\myRESTAPI
OS: win32 ia32
--------------
{ run: false,
  system:
   { cwd: 'C:\\nodejs\\myRESTAPI',
     useFind: false,
     useWatch: false,
     useWatchFile: true },
  required: false,
  dirs: [ 'C:\\nodejs\\myRESTAPI' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions:
      { script: 'server.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor:
      [ '*.*',
        '!.git',
        '!C:\\nodejs\\myRESTAPI\\node_modules/**/*',
        '!bower_components',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command:
   { raw: { executable: 'node', args: [ 'server.js' ] },
     string: 'node server.js' },
  offset: 0 }
--------------

**Comment by keberox** [comment]
Hi, I am having the same issue.
I am using OS: win32 x64

pretty much the same dumb data as added on previous comments.

I am running an Express app straight out of the WebStorm templates.
I can run it well by simply running:
node bin/www

the app runs well, but if I run:
nodemon bin/www

28 Apr 13:24:18 - [nodemon] starting `node bin/www`
exception in nodemon killing node
Error: spawn cmd ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

nodemon is a nice tool, I hope I will get it to work.
BTW, same app runs fine on Mac OSx.

Thanks!

**Comment by keberox** [comment]
So the Code is the Express App template from WebStorm  and this is the dump data
--------------
node: v0.12.2
nodemon: v1.3.7
command: node C:\node_packages\npm\node_modules\nodemon\bin\nodemon.js bean\www --dump
cwd: C:\ccviews\crmh_Ecommerce_Web_v57.0.0_2\vob\APP_Ecomm\Ecommerce_Web\webServer
OS: win32 x64
--------------
{ run: false,
  system:
   { cwd: 'C:\\ccviews\\crmh_Ecommerce_Web_v57.0.0_2\\vob\\APP_Ecomm\\Ecommerce_Web\\webServer',
     useFind: false,
     useWatch: false,
     useWatchFile: true },
  required: false,
  dirs: [ 'C:\\ccviews\\crmh_Ecommerce_Web_v57.0.0_2\\vob\\APP_Ecomm\\Ecommerce_Web\\webServer' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions:
      { script: 'bean\\www',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor:
      [ '*.*',
        '!.git',
        '!C:\\ccviews\\crmh_Ecommerce_Web_v57.0.0_2\\vob\\APP_Ecomm\\Ecommerce_Web\\webServer\\node_modules/**/*',
        '!bower_components',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command:
   { raw: { executable: 'node', args: [ 'bean\\www' ] },
     string: 'node bean\\www' },
  offset: 0 }
--------------

**Comment by rodrigo-barraza** [comment]
Have also been getting these errors no matter what solutions I try to apply online.

C:\dev\monochro.me>nodemon server.coffee --dump
22 May 02:28:41 - [nodemon] v1.3.7
22 May 02:28:41 - [nodemon] to restart at any time, enter `rs`
22 May 02:28:41 - [nodemon] watching: *.*
--------------
node: v0.10.32
nodemon: v1.3.7
command: node C:\Users\Rodrigo\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.js server.coffee --dump
cwd: C:\dev\monochro.me
OS: win32 x64
--------------
{ run: false,
  system:
   { cwd: 'C:\\dev\\monochro.me',
     useFind: false,
     useWatch: false,
     useWatchFile: true },
  required: false,
  dirs: [ 'C:\\dev\\monochro.me' ],
  timeout: 1000,
  options:
   { dump: true,
     execMap: { coffee: 'node_modules/.bin/coffee', py: 'python', rb: 'ruby' },
     ignore:
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions:
      { script: 'server.coffee',
        exec: 'node_modules/.bin/coffee',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'coffee',
        env: {},
        execArgs: [] },
     monitor:
      [ '*.*',
        '!C:\\dev\\monochro.me\\.git/**/*',
        '!C:\\dev\\monochro.me\\node_modules/**/*',
        '!C:\\dev\\monochro.me\\bower_components/**/*',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [ 'C:\\dev\\monochro.me\\nodemon.json' ],
  command:
   { raw:
      { executable: 'node_modules/.bin/coffee',
        args: [ 'server.coffee' ] },
     string: 'node_modules/.bin/coffee server.coffee' },
  offset: 0 }
--------------

**Comment by creeperyang** [comment]
Wow, same problem in win7. Everything is ok with osx.

**Comment by 3masks** [comment]
this helped me github.com/remy/nodemon/issues/616

**Comment by Petr73ru** [comment]
The same problem but I can't solve it with #616.
