### ISSUE TITLE
Whitelist patterns the same way ignore is defined right now

### ISSUE THREAD

**Issue by Rush** [remy/nodemon#507]
I am using nodemon to restart my rails environment but the extension only inclusion includes too much files since rails is able to handle some of them by itself, I would appreciate more advanced way to add inclusion patterns.

**Comment by remy** [comment]
Like a config file?

**Comment by Rush** [comment]
Yeah, config file or patterns like `*_job.rb`

**Comment by remy** [comment]
...so put that in the config file. You need to read around nodemon.json
