### ISSUE TITLE
Ignore a folder from being watched but include certain sub directories

### ISSUE THREAD

**Issue by kojiwakayama** [remy/nodemon#514]
I have the following files:
```
./ignore/foo/bar.js
./ignore/include/index.js
```

I want to ignore './ignore/\*' but include './ignore/include/\*'

I have the following ignore setting in nodemon.json:
```
  "ignore": [
    "ignore/*",
    "!ignore/include/*"
  ]
```

When I run nodemon I get this output:
```
[nodemon] ignoring: ignore/**/* !ignore/include/**/*
```

When I make changes to './ignore/include/index.js', nothing happens.

I logged ignore and match in lib/monitor/match.js:

console.log(ignore):
```
[ 'ignore/*',
  '!ignore/include/*',
  re: /ignore/.*|!ignore/include/.*/ ]
```

console.log(match):
```
[ '.', '!ignore/*', '!!ignore/include/*' ]
```

Any help is appreciated.

koji

**Comment by remy** [comment]
Have you tried to reverse the logic, and only using watch?

**Comment by kojiwakayama** [comment]
Ok, thank you. I could use watch but that's not what I want to do. It would be nice with negated glob patterns in the ignore list. Closing this issue.

**Comment by wprater** [comment]
is there a way to do this using the default node_modules ignore pattern?  I just want to watch one node_module that's linked locally.

**Comment by remy** [comment]
@wprater I'm not sure it is, it ignores the `node_modules` at the root of the pattern. [This](https://github.com/remy/nodemon/blob/master/faq.md#what-has-precedence-ignore-or-watch) might help a bit though.
