### ISSUE TITLE
No ability to turn of watching

### ISSUE THREAD

**Issue by dimsmol** [remy/nodemon#516]
I'm using nodemon with gulp and I have a set of tasks that should be run sequentially on file change.
I'm using gulp's watch and send restart from one of these tasks to nodemon.
All is fine except that in this scenario I don't need nodemon to watch any files, because gulp already does it.

Unfortunately there is no way to turn off watching in nodemon.

Moreover, I cannot even make it watch as little as possible - it always adds something like **/ to the paths I provide.
Of course I can use "ignore" option, but it would be much better to be able to specify that I don't need to watch anything at all.

PS It also would be cool to be able to specify what exactly I want to watch without unexpectedly adding prefixes or enforcing defaults (nodemon is very aggressive on this).

**Comment by remy** [comment]
Can you replicate this without using gulp (as its a totally separate
project which does its own thing with nodemon)?

**Comment by dimsmol** [comment]
I think I can.
But how I supposed to turn off watching? I just didn't find such an option.
And all my attempts to use options like `watch: false`, `watch: []`, `watch: ''`, `watch: ['']` (and so on) have failed.
I traced the sources and found that nodemon uses default dirs to watch on any attempt to provide some kind of "nothing" as an option.

For instance:

* [this line](https://github.com/remy/nodemon/blob/master/lib/utils/merge.js#L36) applies defaults even when empty list is intentionally provided
* [this line](https://github.com/remy/nodemon/blob/master/lib/config/index.js#L57) adds `*.*` to watch list even if defaults weren't applied (will prevent empty watch list even if previous item will be fixed)

Also it looks like [this line](https://github.com/remy/nodemon/blob/master/lib/monitor/match.js#L161) adds `**/` prefix to rules, so you cannot specify some concrete file or directory, it will forcefully become `**/somedir`

**Comment by clearjs** [comment]
`watch: ['./taehtohethonatheththetuheathtehtethethetthtehtehetehttehetett']` works for me, but there definitely exist easier ways :)

**Comment by remy** [comment]
You can now do `watch: false` to optionally *not* watch anything. This is rather specific to your problem, but it was simple to add.

**Comment by amyjie** [comment]
Thanks!

**Comment by KostyaTretyak** [comment]
@remy , thank you for `watch: false` but why `watch: true` doesn't work? =)
Throw an error:

```text
$ nodemon -e ts --exec ts-node --project examples/tsconfig.json -r tsconfig-paths/register examples/10-openapi/main.ts
/srv/git/ditsmod/ditsmod/node_modules/nodemon/lib/rules/add.js:58
  rule = (rule || '').replace(reEscComments, '^^')
                      ^

TypeError: (rule || "").replace is not a function
    at add (/srv/git/ditsmod/ditsmod/node_modules/nodemon/lib/rules/add.js:58:23)
    at normaliseRules (/srv/git/ditsmod/ditsmod/node_modules/nodemon/lib/config/load.js:154:15)
    at ready (/srv/git/ditsmod/ditsmod/node_modules/nodemon/lib/config/load.js:102:9)
    at /srv/git/ditsmod/ditsmod/node_modules/nodemon/lib/config/load.js:118:7
    at callback (/srv/git/ditsmod/ditsmod/node_modules/nodemon/lib/config/load.js:179:5)
    at /srv/git/ditsmod/ditsmod/node_modules/nodemon/lib/config/load.js:219:5
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
error Command failed with exit code 1.
