### ISSUE TITLE
FAQ entry for `forever` needs to be updated

### ISSUE THREAD

**Issue by nwinkler** [remy/nodemon#523]
The FAQ entry for combining `nodemon` with `forever` needs to be updated. It currently reads:

```
forever nodemon --exitcrash server.js
```

I have found that this does not work - it looks like the `forever` syntax has changed. You need to provide the `start` command and tell it to use `nodemon` instead of `node` using the `-c` option:

```
forever start -c nodemon --exitcrash server.js
```

This allowed me to start the server, but when I stopped the process using `forever stopall`, I found that `nodemon` had exited, but left the `node server.js` process running. It looks like you need to tell `forever` to send a `TERM` signal instead of a `KILL` signal:

```
forever start --killSignal=SIGTERM -c nodemon --exitcrash server.js
```

When started like this, calling `forever stopall` or stopping through `forever stop <uid>`, both `nodemon` and the started `node` process are killed.

Can you please update the FAQ to reflect this? I was struggling with getting this to work due to the outdated documentation. I'm using `forever` v0.14.1 and `nodemon` v1.3.7.

**Comment by remy** [comment]
I'll take a PR if that's cool. I don't use forever at all, so I'm not the authority! :-\

**Comment by nwinkler** [comment]
Fair enough :-)

I've provided a PR (#525).

**Comment by remy** [comment]
Awesome. Thanks :+1:

**Comment by nwinkler** [comment]
You're welcome!
