### ISSUE TITLE
How to stop nodemon?

### ISSUE THREAD

**Issue by blacksonic** [remy/nodemon#533]
I require nodemon to use it with gulp in my dev stack. Is it possible to stop the process started by nodemon with a command?

**Comment by remy** [comment]
Yes: https://github.com/remy/nodemon/blob/master/doc/events.md#using-nodemon-events

**Comment by blacksonic** [comment]
My problem that it stops the child process, but the main process keeps going... how to unsubscribe every event listener?

**Comment by zak39** [comment]
Hello @blacksonic :)

How have you resolve this problem ?

I has a project on NodeJS and I use Jenkins. But I am should to kill the process NodeJS for the pipeline of Jenkins ^^'
