### ISSUE TITLE
nodemon try to charge node but is nodejs

### ISSUE THREAD

**Issue by ffranjavier** [remy/nodemon#540]
HI!

Maybe this bug is from my install of node, but when I install in Ubuntu node.js the command for run is 'nodejs' not 'node', when I try to run nodemon, the exec.js file is looking for 'node' not for nodejs, I change the line numer #98 to 'nodejs' but I don't know if this is ok?

Thanks!

**Comment by remy** [comment]
Install the node legacy thing, I recommend reading the digital ocean docs, they're very good. It'll give you the proper `node` command.
