### ISSUE TITLE
debug option in config is not being recognised

### ISSUE THREAD

**Issue by phelma** [remy/nodemon#541]
Setting the config to include CLI options like `$ nodemon --verbose --debug` by setting `nodemon.json` to
```
{
  "verbose": true,
  "debug": true
}
```

The verbose setting is activated but the debug setting is not.

*May be similar to #324*

**Comment by remy** [comment]
Debug is not a nodemon argument, which is why it's not recognised.

**Comment by phelma** [comment]
Please can you explain? From the readme:

>You can also pass the debug flag to node through the command line as you would normally:

>    nodemon --debug ./server.js 80

**Comment by remy** [comment]
Debug is a node argument, the docs show a simple example.

**Comment by phelma** [comment]
OK Thanks.
Where can I specify the node arguments without passing in as a command argument? I am using nodemon in gulp.

**Comment by remy** [comment]
I didn't write the gulp wrapper to nodemon, so I don't know.

I'm guessing `nodeArgs`, but I don't know how the gulp wrapper works.

**Comment by neoadventist** [comment]
@remy any solution to this? the docs make it seem like you can just put a `--debug` statement in there and it will set a breakpoint. Are you saying this is not the case?
