### ISSUE TITLE
Nodemon is not restarting my app

### ISSUE THREAD

**Issue by thedug** [remy/nodemon#542]
I'm running node-mon via grunt-nodemon and it is not picking up my changes..

The server.js starts an express app.

    nodemon: {
      dev: {
        script: 'app/server.js',
        options: {
          nodeArgs: ['--debug'],
          ext: 'js,html',
          watch: 'app'
        }
      }

**Comment by thedug** [comment]
legacyWatch fixed the issue. What exactly does legacyWatch do?

**Comment by remy** [comment]
Change the watch method since file watching is a bit of a dark art!
