### ISSUE TITLE
Repeatedly getting Error: spawn ENOMEM

### ISSUE THREAD

**Issue by foxx** [remy/nodemon#545]
For some reason, I keep getting this randomly;

```
exception in nodemon killing node
Error: spawn ENOMEM
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at exports.spawn (child_process.js:995:9)
    at Object.exports.execFile (child_process.js:689:15)
    at exports.exec (child_process.js:649:18)
    at changeFunction (/tmp/tmp.vbu2aTaMqK/nodemon/lib/monitor/watch.js:93:7)
    at module.exports [as _onTimeout] (/tmp/tmp.vbu2aTaMqK/nodemon/lib/monitor/watch.js:289:5)
    at Timer.listOnTimeout (timers.js:110:15)

----------------------------------------------------------
If appropriate, please file an error with the output from:
$ node /vagrant/docs/node_modules/.bin/nodemon -w ./app/sass/ -q -e * -x npm run build:compass --dump
At http://github.com/remy/nodemon/issues/new
----------------------------------------------------------
```

Debug info:

```
nodemon == 1.3.7
node == 0.12.2
OS == Ubuntu 14.04.2 LTS
kernel == vagrant-ubuntu-trusty-64 3.13.0-49-generic
```

Note: the files being watched are situated on a vboxsf mount (used by vagrant for shared folders). Dmesg shows no vboxsf module errors etc. The output from `--dump` is blank.

**Comment by foxx** [comment]
Ah, `ENOMEM` is lack of memory.. seems there is a memory leak somewhere, though I'm not sure if this is my own application or `nodemon`. I'll keep an eye on `top` and post results when it crashes again (happens every few hours).

**Comment by foxx** [comment]
Confirmed memory leak `nodemon`, although I'm not too sure why because surely someone else would have raised this already? I'm going to try [this] to pin point the leak.

[1]: http://www.nearform.com/nodecrunch/self-detect-memory-leak-node/

**Comment by terbooter** [comment]
I got same issue.

**Comment by foxx** [comment]
For what it's worth, I gave up trying to use `nodemon` and instead used `chokadir` directly;

```
var PUBLIC_PATHS = ['./app/sass/**/*.scss', ]
var CHOKIDAR_OPTS = {usePolling: true, ignoreInitial: true}
chokidar.watch(PUBLIC_PATHS, CHOKIDAR_OPTS)
  .on('all', function(event, path) {
    logger.debug("livereload: detected event '%s' on %s", event, path);
    logger.info("livereload: Sending refresh to browser");
  });
```

Little bit more work, but well worth it.

**Comment by remy** [comment]
@foxx I'm going to close this, but since your comment, I've moved `chokidar` inside of nodemon to replace the custom watching methods. :)
