### ISSUE TITLE
using debug module when running under nodemon

### ISSUE THREAD

**Issue by kellyrmilligan** [remy/nodemon#546]
on the latest nodemon, running it under gulp nodemon. using the debug module and starting my app with the DEBUG env variable, no console output appears. starting with with just node the output appears. is there a way to do both?

**Comment by kellyrmilligan** [comment]
here's my gulpfile

nodemon({
    script: './bin/www',
    ext: 'js, jsx, hbs',
    nodeArgs: [gulp.env.debug ? '--debug' : ''],
    env: {
      DEBUG: 'DEBUG=*',
      'NODE_ENV': 'development'
    },
    cwd: '.',
    ignore: [
      'node_modules/**'
    ],
    stdout: true,
    watch: [
      'data/**/*',
      'views/**/*',
      'config/**/*',
      'app.js',
      'app/**/*',
      'setup/**/*',
      'lib/**/*',
      'middleware/**/*'
    ]
  })
    .on('change', [
      'webpack-exp'
    ])
    .on('restart', function () {
      console.log('server restarted!');
    });

**Comment by piecioshka** [comment]
@kellyrmilligan please wrap your code by 3xbacktick, ex:
```
alert(1)
```

**Comment by payne8** [comment]
I take it there is no update to this issue?
