### ISSUE TITLE
run nodemon with harmony extensions

### ISSUE THREAD

**Issue by donniev** [remy/nodemon#547]
what is the correct way to configure nodemon to start node with the harmony extensions

**Comment by remy** [comment]
How do you run Node with harmony extensions?

**Comment by donniev** [comment]
node --harmony mycode.js

**Comment by remy** [comment]
So...this should work: `nodemon --harmony mycode.js`

**Comment by remy** [comment]
Or make it default to using harmony: https://github.com/remy/nodemon/blob/master/doc/sample-nodemon.md

**Comment by TravelingTechGuy** [comment]
@remy : with Express 4, the way it's installed by `express-generator`, the `main` script is `./bin/www`. Adding `"execMap": { "js": "node --harmony" }` to nodemon.json doesn't help, as the file's extension is empty. I tried replacing js with `*` or an empty string, but saw in the code you're expecting an extension. Any workaround, other than manually specifying `nodemon --harmony`?

**Comment by TimonSotiropoulos** [comment]
I am having the same issue as @TravelingTechGuy , did anyone manage to figure out a solution to this issue? (I am also running a ./bin/www script)

**Comment by TravelingTechGuy** [comment]
What ended up working for me, is leaving the extension field empty.
```
"execMap": {
    "": "gulp && node --harmony"
  }
```

As you can see, I'm having nodemon build and run my code on change. 
With Node v4 this flag may be superfluous on my build machine, but some other users still require it as they're using older versions.
