### ISSUE TITLE
Display (w/ or w/o path) which file has changed and triggered restart

### ISSUE THREAD

**Issue by jagged3dge** [remy/nodemon#551]
Would it be possible to have nodemon display which file has been changed to trigger a restart? I'm sure this would be most helpful especially when the output is piped to and consumed by another process.

I'm not sure if this feature exists already.
If it is, someone please kindly tell me how to get it working with the latest nodemon npm package.
If it isn't already implemented, is there any interest for this feature?

My request spawns from watching `grunt serve` output that shows file changes like below:

```
>> File "app\scripts\controllers\registration.js" changed.
```

Nodemon could provide something like this:

```
16 May 06:31:29 - [nodemon] "app\scripts\controllers\registration.js" changed.
16 May 06:31:29 - [nodemon] restarting due to changes...
```

It'd be great to have something like this from nodemon as well.

**Comment by remy** [comment]
See docs around events. It's supported.

**Comment by qiulang** [comment]
I read https://github.com/remy/nodemon/blob/master/doc/events.md but still can't where did the document record that. But it is easy to do that by` --verbose ` switch

**Comment by xinbenlv** [comment]
> I read https://github.com/remy/nodemon/blob/master/doc/events.md but still can't where did the document record that. But it is easy to do that by`--verbose` switch

same here.... I think it would be super helpful if @remy could make this feature more explicitly documented. An use case here is https://cmty.app/nuxt/nuxt.js/issues/c10464

**Comment by AlanSl** [comment]
`nodemon --verbose` isn't quite as good as a "show which file change caused the command to run" flag if you have a lot of 
--ignore filters in place.

I've got a `nodemon` command that runs a build script with an `--ignore` on the build target directory and the `--verbose` output fills up with hundreds of lines like:

```
[nodemon] files triggering change check: build/some/ignored/file.js
[nodemon] changes after filters (before/after): 1/0
[nodemon] files triggering change check: build/another/ignored/file.js
[nodemon] changes after filters (before/after): 1/0
[nodemon] files triggering change check: build/yet/more/ignored/files.js
[nodemon] changes after filters (before/after): 1/0
```

...and there's sometimes so much output that the one crucial line about the one crucial change that wasn't filtered gets overwritten by the runner's output (ultra's spinners).

It'd be great if there was an option to only output changes that passed the filters.

**Comment by rattrayalex** [comment]
@remy can you share a link to the docs for this? Or should the issue be reopened?
