### ISSUE TITLE
interval between tests in Windows

### ISSUE THREAD

**Issue by marneborn** [remy/nodemon#555]
The default interval for fs.watch\* is 5007ms.
This means that it takes up to 5 seconds to restart in windows. That's a bit long for me...
The setTimeout used to check in "useFind" is 1000ms (config.timeout).

Can we do something like this instead?

```
var watcher = fs[watchMethod](dir, { persistent: false, interval : config.timeout }, function (event, filename) {
```

**Comment by halt-hammerzeit** [comment]
@marneborn Thanks man! You nailed it.

I was wondering why nodemon is soooo slow on detecting changes.
I changed it to 100 (milliseconds) and now it's rocket fast.
I'll make a pull request for you.

**Comment by halt-hammerzeit** [comment]
Pull request created:
https://github.com/remy/nodemon/pull/585

**Comment by marneborn** [comment]
Thanks, you may want to check out this pull request too 556
<https://github.com/remy/nodemon/pull/556>.

--watch doesn't work as advertised in windows.

-mikael

**Comment by halt-hammerzeit** [comment]
@marneborn I also noticed that the program (for some strange reason) watches the whole current directory and only when watchers fire it checks the regexp. I didn't get into much detail on that one and just proposed initializing `config.dirs` from nodemon.json

**Comment by halt-hammerzeit** [comment]
@marneborn hey, Remy has just merged the workaround for the long watch interval: you can now specify it as "watch_interval" in the nodemon.json (I set mine to 500). By the way I've just noticed that maybe the nodemon style would be like "watchInterval". It's the project author's right to decide on naming.
