### ISSUE TITLE
Error starting simple app

### ISSUE THREAD

**Issue by pedrorijo91** [remy/nodemon#557]
I'm using Ubuntu 14.04 and as you can see [here](http://stackoverflow.com/questions/21168141/can-not-install-packages-using-node-package-manager-in-ubuntu) there are some issues with the `node` package, that has been renamed `nodejs`. A solution for that was to run the command in the accepted answer:

    sudo apt-get install nodejs-legacy

Not sure if that's the reason for getting the error below but I guess it may be.

> If you do need the code (it's a very simple `express` app) I can append a gist with it

    $ node /usr/local/bin/nodemon express.js --dump
    exception in nodemon killing node
    Error: watch ENOSPC
        at errnoException (fs.js:1024:11)
        at FSWatcher.start (fs.js:1056:11)
        at Object.fs.watch (fs.js:1081:11)
        at Function.check (/usr/local/lib/node_modules/nodemon/lib/config/watchable.js:39:6)
        at alternativeCheck     (/usr/local/lib/node_modules/nodemon/lib/config/checkWatchSupport.js:33:15)
        at /usr/local/lib/node_modules/nodemon/lib/config/checkWatchSupport.js:57:11
        at ChildProcess.exithandler (child_process.js:641:7)
        at ChildProcess.EventEmitter.emit (events.js:98:17)
        at maybeClose (child_process.js:743:16)
        at Socket.<anonymous> (child_process.js:956:11)
    
    ----------------------------------------------------------
    If appropriate, please file an error with the output from:
    $ node /usr/local/bin/nodemon express.js --dump
    At http://github.com/remy/nodemon/issues/new
    ----------------------------------------------------------
    
    27 May 09:58:24 - [nodemon] v1.3.7
    27 May 09:58:24 - [nodemon] to restart at any time, enter `rs`
    27 May 09:58:24 - [nodemon] watching: *.*
    --------------
    node: v0.10.25
    nodemon: v1.3.7
    command: node /usr/local/bin/nodemon express.js --dump
    cwd: /home/pedrorijo/git/ist-canteen/server
    OS: linux x64
    --------------
    { run: false,
      system: 
       { cwd: '/home/pedrorijo/git/ist-canteen/server',
         useFind: false,
         useWatch: false,
         useWatchFile: true },
      required: false,
      dirs: [ '/home/pedrorijo/git/ist-canteen/server' ],
      timeout: 1000,
      options: 
       { dump: true,
         ignore: 
          [ '.git',
            'node_modules',
            'bower_components',
            '.sass-cache',
            re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
         watch: [ '*.*', re: /.*\..*/ ],
         restartable: 'rs',
         execMap: { py: 'python', rb: 'ruby' },
         stdin: true,
         verbose: false,
         stdout: true,
         execOptions: 
          { script: 'express.js',
            exec: 'node',
            args: [],
            scriptPosition: 0,
            nodeArgs: undefined,
            ext: 'js',
            env: {},
            execArgs: [] },
         monitor: 
          [ '*.*',
            '!.git',
            '!/home/pedrorijo/git/ist-canteen/server/node_modules/**/*',
            '!bower_components',
            '!.sass-cache' ] },
      load: [Function],
      reset: [Function: reset],
      lastStarted: 0,
      loaded: [],
      command: 
       { raw: { executable: 'node', args: [ 'express.js' ] },
         string: 'node express.js' },
      offset: 0 }
    --------------

**Comment by kazazes** [comment]
You're invoking `nodemon` incorrectly. Rather than attempt to have node run the *executable* as you are (`node /usr/local/bin/nodemon ...`), consider nodemon an alternative to `node`. See (here)[https://github.com/remy/nodemon#usage] for the correct usage.

**Comment by pedrorijo91** [comment]
Sorry, I did it well on my mac, but on Ubuntu I must have been sleeping :confused:
