### ISSUE TITLE
Restart loop

### ISSUE THREAD

**Issue by ChristianDen** [remy/nodemon#562]
Nodemon enters a restart loop

gulp = require 'gulp'
nodemon = require 'gulp-nodemon'
livereload = require 'gulp-livereload'

gulp.task 'develop', ->

  callback = ->
    livereload.changed __dirname

  options =
    script: 'build/app/server.coffee'
    ext: 'hbs coffee'
    execMap:
      coffee: (->
        if process.platform isnt 'win32'
          './node_modules/.bin/coffee'
        else
          '.\\node_modules\\.bin\\coffee.cmd'
      )()

  livereload.listen()

  nodemon(options).on 'restart', ->
    setTimeout callback, 500

--------------------------------

node: v0.10.31
nodemon: v1.3.7
command: node C:\Users\Christian.Rich\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.js --dump
cwd: C:\Users\Christian.Rich\Documents\projects\jumpin-tv-guide2
OS: win32 ia32
--------------
{ run: false,
  system:
   { cwd: 'C:\\Users\\Christian.Rich\\Documents\\projects\\jumpin-tv-guide2',
     useFind: false,
     useWatch: true,
     useWatchFile: false },
  required: false,
  dirs: [ 'C:\\Users\\Christian.Rich\\Documents\\projects\\jumpin-tv-guide2' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions:
      { script: 'app/server.coffee',
        exec: './node_modules/.bin/coffee',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'coffee',
        env: {},
        execArgs: [] },
     monitor:
      [ '*.*',
        '!C:\\Users\\Christian.Rich\\Documents\\projects\\jumpin-tv-guide2\\.git/**/*',
        '!C:\\Users\\Christian.Rich\\Documents\\projects\\jumpin-tv-guide2\\node_modules/**/*',
        '!C:\\Users\\Christian.Rich\\Documents\\projects\\jumpin-tv-guide2\\bower_components/**/*',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command:
   { raw:
      { executable: './node_modules/.bin/coffee',
        args: [ 'app/server.coffee' ] },
     string: './node_modules/.bin/coffee app/server.coffee' },
  offset: 0 }

**Comment by remy** [comment]
Please try the build here #625 and feedback against the issue #625.

**Comment by remy** [comment]
#625 closes and released in `nodemon@1.4.2`
