### ISSUE TITLE
Feature request: Watch node_modules when a package require fails

### ISSUE THREAD

**Issue by CrabDude** [remy/nodemon#564]
This is an enhancement request. I've aware that nodemon doesn't watch `node_modules` by default, and why that is (performance). That said, a common cause of crashes and needing to restart is because a dependency has been required, but not installed. It would be nice if nodemon watched for new packages being installed in this specific case.

This is not really a critical feature, but for some new developers, it can be confusing how nodemon seems to just work, but then "stops working" when the server doesn't restart after a package has been installed. I don't think this is a bug, it just seems like a common use-case that would only require watching the top level of node_modules temporarily. It would just be incredibly nice if you never had to manually restart your server / nodemon in this common scenario. Thanks for considering!

**Comment by remy** [comment]
You can control this now (as of nodemon@^1.5.0) - see the note about `ignoreRoot` [here](https://github.com/remy/nodemon#ignoring-files).

**Comment by CrabDude** [comment]
Thanks! Getting `ignoreRoot` to work was extremely confusing. An example an a little elaboration would be nice. It turns out I need both `ignore` and `ignoreRoot` to get this working:

In regards to removing the default ignoring of `node_modules`...

Does nothing (docs recommendation):
```json
{
  "ignoreRoot": []
}
```

Also does nothing:
```json
{
  "ignore": [".git"]
}
```

Also does nothing (...):
```json
{
  "ignore": [],
  "ignoreRoot": []
}
```

Works (?!):
```json
{
  "ignore": [".git"],
  "ignoreRoot": []
}
```

**Should I open another issue regarding the above?** This took about 30m of playing around to figure out what works since there is no current documentation on how to effectively use `ignoreRoot`.

```bash
$ nodemon -v
v1.6.1
```

**Comment by CrabDude** [comment]
For posterity, here's my solution to the original issue:

`nodemon.json`:
```json
{
  "ignore": [".git", "node_modules/*/node_modules/**"],
  "ignoreRoot": []
}
```

**Comment by remy** [comment]
This is sound, I'm thinking that the [default](https://github.com/remy/nodemon/blob/master/lib/config/defaults.js#L12) should actually use `ignoreRoot` and not `ignore` so that overrides have a direct impact, rather than merging by default.
