### ISSUE TITLE
nodemon app returns error "exception in nodemon killing node"

### ISSUE THREAD

**Issue by dotenorio** [remy/nodemon#565]
11 Jun 09:16:40 - [nodemon] v1.3.7
11 Jun 09:16:40 - [nodemon] to restart at any time, enter rs
11 Jun 09:16:40 - [nodemon] watching: .

node: v0.12.4
nodemon: v1.3.7
command: node C:\Users\fernando.tenorio\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.js app.js --dump
cwd: C:\Desenvolvimento\api_padrao_unico
OS: win32 x64
{ run: false,
system: 
{ cwd: 'C:\Desenvolvimento\api_padrao_unico',
useFind: false,
useWatch: false,
useWatchFile: true },
required: false,
dirs: [ 'C:\Desenvolvimento\api_padrao_unico' ],
timeout: 1000,
options: 
{ dump: true,
ignore: 
[ '.git',
'node_modules',
'bower_components',
'.sass-cache',
re: /.git|node_modules|bower_components|.sass-cache/ ],
watch: [ '.', re: /.../ ],
restartable: 'rs',
execMap: { py: 'python', rb: 'ruby' },
stdin: true,
verbose: false,
stdout: true,
execOptions: 
{ script: 'app.js',
exec: 'node',
args: [],
scriptPosition: 0,
nodeArgs: undefined,
ext: 'js',
env: {},
execArgs: [] },
monitor: 
[ '.',
'!.git',
'!C:\Desenvolvimento\api_padrao_unico\node_modules/*/',
'!bower_components',
'!.sass-cache' ] },
load: [Function],
reset: [Function: reset],
lastStarted: 0,
loaded: [],
command: 
{ raw: { executable: 'node', args: [ 'app.js' ] },
string: 'node app.js' },
offset: 0 }

**Comment by dotenorio** [comment]
Why?

**Comment by remy** [comment]
You didn't include any information on what the bug was or how to replicate,
I assumed it was just a mistake. Its why I closed with no information too.

Happy to help if you can help diagnose with what's actually happening or I
can you point you to the area of the fix.
