### ISSUE TITLE
nodemon fails to restart app and runs a lot of find processes!

### ISSUE THREAD

**Issue by ZiCog** [remy/nodemon#569]
nodemon fails to restart my crashed  app, a single js file with a simple express server.

It clogs up my PC by running many instances of find and just sits there.

node version v0.12.0
nodemon version 1.3.7
Linux Debian Jessie.

run as "nodemon server.js", no options specified anywhere.

**Comment by remy** [comment]
Please try the build here #625 and feedback against the issue #625.

**Comment by ZiCog** [comment]
Will do.

**Comment by remy** [comment]
#625 closes and released in `nodemon@1.4.2`
