### ISSUE TITLE
file watch on alpine linux

### ISSUE THREAD

**Issue by ronag** [remy/nodemon#570]
I've noticed that file watch doesn't work on alpine linux unless I use the `-L`. Anyone got any ideas as to why that may be the case and how to fix it?

**Comment by remy** [comment]
Sorry, no. Please do feel free to spelunk the code if you can make it better (honestly, I've not heard of alpine linux either...)

**Comment by heisian** [comment]
alpine linux is a pretty widely used distro for running node in Docker.
