### ISSUE TITLE
Duplicate input in REPL

### ISSUE THREAD

**Issue by Nieralyte** [remy/nodemon#572]
When a REPL is invoked from withing a script through `require('repl').start(...)` or through a debugger there's input being printed twice.

E.g. steps to reproduce:

1. Start a script with debugging enabled: `nodemon debug foo.js`
2. Switch to a REPL (type `repl`)
3. See all the input being duplicated

![nodemon_repl_dupes](https://cloud.githubusercontent.com/assets/2974980/8375480/e87700fe-1c16-11e5-8da7-704dd85c4f66.png)
http://i.imgur.com/ibezpZB.png

Windows 8.1 x64, Node 0.12.5

**Comment by remy** [comment]
Did you try this? https://github.com/remy/nodemon/blob/master/faq.md#nodemon-doesnt-work-with-my-repl

Also, REPL + nodemon is kind of a bad idea, it's super hard to get right.

**Comment by Nieralyte** [comment]
> Did you try this? https://github.com/remy/nodemon/blob/master/faq.md#nodemon-doesnt-work-with-my-repl

wow it actually worked! i'm sorry, should've read the docs first. (can't imagine development without nodemon)
