### ISSUE TITLE
Is there a way to not run a command on startup but only when files change?

### ISSUE THREAD

**Issue by khoomeister** [remy/nodemon#575]
I'm using a cluster of workers in a webapp, and I would like nodemon to watch the files, and restart those workers (via a USR2 signal) whenever a change is made.

This is what I've done:

```bash
node some-app.js &
SERVER_PID=$!

nodemon -w modules -x "kill -s USR2 $SERVER_PID"
```

The only problem is, nodemon will automatically run the command on startup.  Is there a way to disable this, and only run when files are changed?

**Comment by ericclemmons** [comment]
This is annoying to me as well.

My server is built by Webpack (part of an isomoprhic/universal setup), so my `nodemon.json` has:

```
{
  "events": {
    "start": "rm src/server.min.js && touch src/server.min.js"
  },
  "watch": [
    "src/server.min.js"
  ]
}
```

That way, when I start the server I'm not running the previous, buggy build, but start with _nothing_ and a few seconds later the proper server starts up.

As a result, each _restart_ blows away the file.  `start` is not the same as `restart`, IMO.
