### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by wangchj** [remy/nodemon#579]
----------------------------------------------------------
If appropriate, please file an error with the output from:
$ node /usr/local/bin/nodemon -e js,css,html --ignore data/ --ignore repo/ --dump
At http://github.com/remy/nodemon/issues/new
----------------------------------------------------------

wangchj@acer ~/p/myapp>         
wangchj@acer ~/p/myapp> 
node /usr/local/bin/nodemon -e js,css,html --ignore data/ --ignore repo/ --dump
6 Jul 14:28:08 - [nodemon] v1.3.7
6 Jul 14:28:08 - [nodemon] to restart at any time, enter `rs`
6 Jul 14:28:08 - [nodemon] watching: *.*
--------------
node: v0.10.25
nodemon: v1.3.7
command: node /usr/local/bin/nodemon -e js,css,html --ignore data/ --ignore repo/ --dump
cwd: /home/wangchj/proj/myapp
OS: linux x64
--------------
{ run: false,
  system: 
   { cwd: '/home/wangchj/proj/myapp',
     useFind: true,
     useWatch: false,
     useWatchFile: false },
  required: false,
  dirs: [ '/home/wangchj/proj/myapp' ],
  timeout: 1000,
  options: 
   { ignore: [ 'data/', 'repo/', re: /data/|repo// ],
     dump: true,
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions: 
      { script: './bin/www',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js,css,html',
        env: {},
        execArgs: [] },
     monitor: 
      [ '*.*',
        '!/home/wangchj/proj/myapp/data/**/*',
        '!/home/wangchj/proj/myapp/repo/**/*' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command: 
   { raw: { executable: 'node', args: [ './bin/www' ] },
     string: 'node ./bin/www' },
  offset: 0 }
--------------

**Comment by remy** [comment]
*if appropriate*. Closing due to total lack of information *about* issue.
