### ISSUE TITLE
Nodemon not starting node on restart

### ISSUE THREAD

**Issue by ovalin** [remy/nodemon#581]
Hello 
The issue I'm having is that nodemon is successfully identifying my changes and acting on them but I am not seeing any update in my browser.
I've ruled out a caching issue as I've turned off caching and tried different browsers.

If I understand nodemon output correctly its supposed to only print out "restarting due to changes..." once but I see it twice, also I don't see a line saying "starting node bin/www" after the "restarting due to changes..."

[admin@NASF09800 exptest]# nodemon bin/www
11 Jul 04:22:14 - [nodemon] v1.3.7
11 Jul 04:22:14 - [nodemon] to restart at any time, enter `rs`
11 Jul 04:22:14 - [nodemon] watching: *.*
11 Jul 04:22:14 - [nodemon] starting `node bin/www`
{}
GET / 200 22.359 ms - 3
11 Jul 04:22:23 - [nodemon] restarting due to changes...
11 Jul 04:22:23 - [nodemon] restarting due to changes...
{}
11 Jul 04:22:39 - [nodemon] restarting due to changes...
11 Jul 04:22:39 - [nodemon] restarting due to changes...
{}
GET / 200 1.761 ms - 3
{}
GET / 200 1.040 ms - 3
11 Jul 04:22:49 - [nodemon] restarting due to changes...
11 Jul 04:22:49 - [nodemon] restarting due to changes...
{}
GET / 200 1.005 ms - 3
{}
GET / 200 1.340 ms - 3

running nodemon version 1.3.7

Hope the information is enough
Thank you for your help

**Comment by remy** [comment]
Can you rerun with the --verbose flag? It'll tell you which file is
triggering the restart

**Comment by ovalin** [comment]
Here is my verbose data it looks to be triggering 4 times now for some reason.
All on the same file....
Really odd.


[admin@NASF09800 exptest]# nodemon --verbose bin/www
12 Jul 02:21:06 - [nodemon] v1.3.7
12 Jul 02:21:06 - [nodemon] to restart at any time, enter `rs`
12 Jul 02:21:06 - [nodemon] watching: *.*
12 Jul 02:21:06 - [nodemon] watching extensions: js
12 Jul 02:21:06 - [nodemon] starting `node bin/www`
12 Jul 02:21:06 - [nodemon] child pid: 9991
12 Jul 02:21:06 - [nodemon] watching 0 files
12 Jul 02:21:38 - [nodemon] files triggering change check: routes/.index.js.swp
12 Jul 02:21:38 - [nodemon] changes after filters (before/after): 1/0
12 Jul 02:21:38 - [nodemon] files triggering change check: routes/.index.js.swx
12 Jul 02:21:38 - [nodemon] changes after filters (before/after): 1/0
12 Jul 02:21:38 - [nodemon] files triggering change check: routes/.index.js.swx
12 Jul 02:21:38 - [nodemon] changes after filters (before/after): 1/0
12 Jul 02:21:38 - [nodemon] files triggering change check: routes/.index.js.swp
12 Jul 02:21:38 - [nodemon] changes after filters (before/after): 1/0
12 Jul 02:21:38 - [nodemon] files triggering change check: routes/.index.js.swp
12 Jul 02:21:38 - [nodemon] changes after filters (before/after): 1/0
12 Jul 02:21:38 - [nodemon] files triggering change check: routes/.index.js.swp
12 Jul 02:21:38 - [nodemon] changes after filters (before/after): 1/0
12 Jul 02:21:38 - [nodemon] files triggering change check: routes/.index.js.swp
12 Jul 02:21:38 - [nodemon] changes after filters (before/after): 1/0
12 Jul 02:21:41 - [nodemon] files triggering change check: routes/.index.js.swp
12 Jul 02:21:41 - [nodemon] changes after filters (before/after): 1/0
12 Jul 02:21:44 - [nodemon] files triggering change check: routes/4913
12 Jul 02:21:44 - [nodemon] changes after filters (before/after): 1/0
12 Jul 02:21:44 - [nodemon] files triggering change check: routes/4913
12 Jul 02:21:44 - [nodemon] changes after filters (before/after): 1/0
12 Jul 02:21:44 - [nodemon] files triggering change check: routes/4913
12 Jul 02:21:44 - [nodemon] changes after filters (before/after): 1/0
12 Jul 02:21:44 - [nodemon] files triggering change check: routes/index.js
12 Jul 02:21:44 - [nodemon] matched rule: **/*.*
12 Jul 02:21:44 - [nodemon] changes after filters (before/after): 1/1
12 Jul 02:21:44 - [nodemon] restarting due to changes...
12 Jul 02:21:44 - [nodemon] routes/index.js

12 Jul 02:21:44 - [nodemon] files triggering change check: routes/index.js~
12 Jul 02:21:44 - [nodemon] matched rule: **/*.*
12 Jul 02:21:44 - [nodemon] changes after filters (before/after): 1/0
12 Jul 02:21:44 - [nodemon] files triggering change check: routes/index.js
12 Jul 02:21:44 - [nodemon] matched rule: **/*.*
12 Jul 02:21:44 - [nodemon] changes after filters (before/after): 1/1
12 Jul 02:21:44 - [nodemon] restarting due to changes...
12 Jul 02:21:44 - [nodemon] routes/index.js

12 Jul 02:21:44 - [nodemon] files triggering change check: routes/index.js
12 Jul 02:21:44 - [nodemon] matched rule: **/*.*
12 Jul 02:21:44 - [nodemon] changes after filters (before/after): 1/1
12 Jul 02:21:44 - [nodemon] restarting due to changes...
12 Jul 02:21:44 - [nodemon] routes/index.js

12 Jul 02:21:44 - [nodemon] files triggering change check: routes/index.js
12 Jul 02:21:44 - [nodemon] matched rule: **/*.*
12 Jul 02:21:44 - [nodemon] changes after filters (before/after): 1/1
12 Jul 02:21:44 - [nodemon] restarting due to changes...
12 Jul 02:21:44 - [nodemon] routes/index.js

12 Jul 02:21:44 - [nodemon] files triggering change check: routes/.index.js.swp
12 Jul 02:21:44 - [nodemon] changes after filters (before/after): 1/0
12 Jul 02:21:44 - [nodemon] files triggering change check: routes/index.js~
12 Jul 02:21:44 - [nodemon] matched rule: **/*.*
12 Jul 02:21:44 - [nodemon] changes after filters (before/after): 1/0
12 Jul 02:21:44 - [nodemon] files triggering change check: routes/.index.js.swp
12 Jul 02:21:44 - [nodemon] changes after filters (before/after): 1/0

**Comment by remy** [comment]
Why are you watching */.*? Its a valid restart when you're changing a tmp
file when you're using that pattern...

**Comment by ovalin** [comment]
Sorry for the confusion I was playing around with some settings.
There are two issues I'm experiencing  1 that for some reason its picking up all changes twice regardless of what they are.  The second is that even though its picking them up its not actually restarting my nodes.

Thank you for looking at this

Here is something cleaner.

13 Jul 03:21:21 - [nodemon] v1.3.7
13 Jul 03:21:21 - [nodemon] reading config nodemon.json
13 Jul 03:21:21 - [nodemon] to restart at any time, enter `rs`
13 Jul 03:21:21 - [nodemon] ignoring: *.swp *.test.js fixtures/**/*
13 Jul 03:21:21 - [nodemon] watching: *.js
13 Jul 03:21:21 - [nodemon] watching extensions: js
13 Jul 03:21:21 - [nodemon] starting `node ./bin/www`
13 Jul 03:21:21 - [nodemon] child pid: 30332
13 Jul 03:21:21 - [nodemon] watching 0 files
This text is being changed again
GET / 304 66.335 ms - -
This text is being changed again
GET / 304 9.743 ms - -
13 Jul 03:22:08 - [nodemon] files triggering change check: routes/index.js
13 Jul 03:22:08 - [nodemon] matched rule: **/*.js
13 Jul 03:22:08 - [nodemon] changes after filters (before/after): 1/1
13 Jul 03:22:08 - [nodemon] restarting due to changes...
13 Jul 03:22:08 - [nodemon] routes/index.js

13 Jul 03:22:08 - [nodemon] files triggering change check: routes/index.js
13 Jul 03:22:08 - [nodemon] matched rule: **/*.js
13 Jul 03:22:08 - [nodemon] changes after filters (before/after): 1/1
13 Jul 03:22:08 - [nodemon] restarting due to changes...
13 Jul 03:22:08 - [nodemon] routes/index.js
This text is being changed again
GET / 304 4.998 ms - -

**Comment by remy** [comment]
Please try the build here #625 and feedback against the issue #625.

**Comment by remy** [comment]
#625 closes and released in `nodemon@1.4.2`
