### ISSUE TITLE
It is restarting my app way too slow.

### ISSUE THREAD

**Issue by McFarts** [remy/nodemon#586]
How can I increase the watch time?

For example, I edit my file and it doesn't restart the app until 2-3 seconds after I edit. I want it to restart it instantly. Hell, I can use jitBitMacro and restart it faster. 

Any idea where to change the setting so it will check if my file is modified at a faster rate? ty

**Comment by remy** [comment]
Not without knowing anything about your system. It could be any number of things like the number of files you're watching, or processes on your machine, or directories, or watch pattern, etc, etc.

**Comment by McFarts** [comment]
It's a game.js file that is less than 10kb. It's checking it way too slow, 2-3 seconds after I edit it, it restarts.

I switched to supervisor and it edits/restarts it instantly. You need to increase the watch time for checking if a file is modified or let us config it for nodemon :)

**Comment by remy** [comment]
You can configure nodemon, but you didn't tell me how you're running it, so...I'm just happy you solved your issue by switching away.

**Comment by McFarts** [comment]
I'm running it by doing:

nodemon game.js

lol

Then, when I edit my game.js file. The shit doesn't get restarted until 2-3 seconds after I edited my file, that's not right. It should be instantly.

**Comment by remy** [comment]
Sounds like its an easy fix (for you) then?

**Comment by imns** [comment]
This comes up on Google when you search for `get nodemon to restart faster`.  You should really link to the docs or reply with a common solution.
