### ISSUE TITLE
v1.3.8 introduces breaking change for gulp-nodemon

### ISSUE THREAD

**Issue by ericqweinstein** [remy/nodemon#592]
I made a [pull request](https://github.com/JacksonGariety/gulp-nodemon/pull/82) on gulp-nodemon as a temporary workaround (pinning to nodemon 1.3.7), but it looks like there may have been an error when [updating the quit listener](https://github.com/remy/nodemon/commit/15751fe4327c455822d374f52752978591925841#diff-cebf50326ac9e24a94de78bad36e77e1L321). From the comment, it looks like maybe this conditional is reversed (_i.e._ should be `if (utils.isWindows)`); this does fix the issue on *nix machines (OSX Mavericks, Ubuntu 14.04, CentOS 6.3).

**Comment by myndzi** [comment]
https://github.com/JacksonGariety/gulp-nodemon/issues/83

This may or may not be related. I just ran this down today, which is ironic since this is the second issue I've run down within a few hours from an issue being opened on a repository in as many days ;)

@remy: Recommend that if you are going to destructively capture the sigint/sigterm signals, that when you're done doing what you want to, you ensure that the signals get re-emitted via process.kill().

**Comment by myndzi** [comment]
Wait, so `restart` uses SIGINT as part of its machinery...?? How are you going to distinguish a monitored restart from a user-input CTRL+C then?

**Comment by remy** [comment]
Fuck. I had my bad feeling about that PR, but it was passing the shit tonne of insane (not good insane) tests. The PR was just refactoring that block of code, from what I could tell, just for the sake of it. 

Honestly, I don't see all the ways in which nodemon is used, I'd happily take PR on the tests to get better coverage (perhaps with gulp + grunt support in there too) - to hopefully avoid for the future.

The original PR was just fixing the `quit` event not emitting, so it might be easiest just to reverse out the commits and add the donkey code fix for the `quit` event - i.e. slap it in, even if it's repeated.

I can't do it now - I'm about to head down to beddy bye bye time - if anyone wants to get a PR in place that reverses this code and *just* emits the `quit` event, I'll merge and push right away. 

Also, looking at https://github.com/JacksonGariety/gulp-nodemon/issues/83 this particular functionality is (nearly) the same in 1.3.7: https://github.com/remy/nodemon/blob/v1.3.7/lib/monitor/run.js#L281-L284 - but again, I'm not that familiar with how it's being used both by the gulp plugin but also by users...so I'm not sure what's right here.

**Comment by remy** [comment]
Worth adding: there's a lot of tests on nodemon that are pretty straight forward, but there's also a whole bunch that require starting forked processes, changing files, waiting random amounts of time and hoping I don't hit race conditions. These ones sometimes randomly fail, and then will pass again...these are my lovingly insane tests :-\

**Comment by remy** [comment]
Something also to add, the specific [line highlighted](https://github.com/remy/nodemon/commit/15751fe4327c455822d374f52752978591925841#diff-cebf50326ac9e24a94de78bad36e77e1L321) has been this way for some time, [it's not new](https://github.com/remy/nodemon/blame/v1.3.7/lib/monitor/run.js#L321) (Dec 2013). So...it's possible something else is at play here...
