### ISSUE TITLE
nodemon restarts server if file watchers it didn't create trigger

### ISSUE THREAD

**Issue by blitmap** [remy/nodemon#596]
Hi - I'm not sure if I'm doing something improperly.

My problem is this:

I have nodemon monitoring a coffeescript nodejs "server.coffee" - the server I wrote creates file watchers of its own to detect changes in the scripts it runs and serves the output from.  nodemon restarts the server if the **server's file watchers** trigger.

This doesn't make sense to me - the server.coffee hasn't changed so nodemon shouldn't restart, but the scripts server.coffee is monitoring have.  nodemon restarts the server if watchers *it didn't create* trigger.

Is this expected behavior?

PS: Sorry about the unnecessary title changes - I was trying to make this clearer

**Comment by remy** [comment]
Please try the build here #625 and feedback against the issue #625.

**Comment by remy** [comment]
#625 closes and released in `nodemon@1.4.2`
