### ISSUE TITLE
bash|zsh: Command not found: nodemon

### ISSUE THREAD

**Issue by ilmoralito** [remy/nodemon#602]
Hi

I just install nodemon in order to use it with an express app i did:

sudo npm install nodemon -g

Then i try nodemon -h

I get zsh: command not found: nodemon

I change npm's default directory to another directory following this link https://docs.npmjs.com/getting-started/fixing-npm-permissions, i mention this for if this is related. 

I also have other global packages installed working fine, here is the list

├── bower@1.4.1
├── express-generator@4.13.1
├── grunt-cli@0.1.13
├── gulp@3.9.0
├── jshint@2.8.0
├── learnyounode@2.7.1
├── nodemon@1.4.0
├── spawn-sync@1.0.13
└── yo@1.4.7

Node version is: v0.10.40
npm version is: 2.13.2

Any idea what is happending, thanks for your time

**Comment by macgera** [comment]
Same problem with bash :/

**Comment by remy** [comment]
You're not using `sudo` are you?

**Comment by macgera** [comment]
Usually not. But problem is strange, install other packages, like example grunt or bower, everything works. In this case not. %/

**Comment by Uttammgr** [comment]
I'm facing same problem, I'm installing locally `npm install --save-dev nodemon` . I did try using the `Sudo` command to install. it correctly installed but still, problem persists. 

`-bash: nodemon: command not found`

**Comment by remy** [comment]
@Uttammgr your issue is unrelated to the first, but you've put nodemon in your local directory. As per docs, install as global if you want to run it on the CLI. The way you've done it, you can run it from scripts (mentioned…sort of…[here](https://docs.npmjs.com/misc/scripts#path)). 

i.e. it's sitting in `node_modules/.bin/nodemon`.

**Comment by Uttammgr** [comment]
@remy thank you for reminding, I completely ignored the global installation.  Silly mistake

**Comment by immoksh** [comment]
It can be solved by installing globally. 
`npm i -g nodemon`

Even I got that issue when I was installing it in my local project.

**Comment by haits293** [comment]
@immoksh I tried, and my situation is,
I did install `nodemon` by `npm i -g nodemon`
when I check with `npm list -g`, I can see nodemon sit there, but still can't use nodemon to start server
my temporary solution is install nodemon locally inside the project
`npm i --save nodemon`
then I change in package.json
`"start": "node_modules/.bin/nodemon app.js"`

**Comment by Abbas357** [comment]
Nodemon: Command not found error in window 10

**Comment by maxbuff** [comment]
Mac: if you're using nvm make sure u installed nodemon for your version globally (if you're using different versions)
