### ISSUE TITLE
restarting (rs) doesn't work for the default "echo" app

### ISSUE THREAD

**Issue by mzgol** [remy/nodemon#603]
```
$ nodemon app
31 Jul 23:31:11 - [nodemon] v1.4.0
31 Jul 23:31:11 - [nodemon] to restart at any time, enter `rs`
31 Jul 23:31:11 - [nodemon] watching: *.*
31 Jul 23:31:11 - [nodemon] starting `echo app`
app
31 Jul 23:31:11 - [nodemon] clean exit - waiting for changes before restart
rs
rs
rs





rs
```

No reaction. `nodemon` 1.4.0, io.js 2.5.0.

**Comment by mzgol** [comment]
Ah, it's `nodemon ./app.js`, not `nodemon app`... Still, the output wasn't helpful in diagnosing.

**Comment by remy** [comment]
I appreciate this issue is old, but what is in `app.js`? And why is your executable `echo app` - is there a `nodemon.json` at play here?

**Comment by remy** [comment]
I think this is fixed. There was an issue with `rs` in iojs that carried through to node 4, which I've fixed.

**Comment by mzgol** [comment]
Yeah, currently I have:
```
$ nodemon --version
v1.7.0
$ nodemon app
  Usage: nodemon [nodemon options] [script.js] [args]

  See "nodemon --help" for more.
```

so it's failing as it should instead of going into a weird echo mode. :)
