### ISSUE TITLE
Ability to pass function to exec

### ISSUE THREAD

**Issue by feus4177** [remy/nodemon#607]
It would be nice if you are using nodemon in a node script to be able to pass a javascript function to the `exec` option.

**Comment by feus4177** [comment]
I should add, I know that you can get similar functionality by attaching listeners to the `start` and `restart` events. I just think this might be a good convenience method.

**Comment by remy** [comment]
I'll close for now and consider implementation if there's a whole bunch of +1 (or consider a PR). For now, I think it's an edge case.

**Comment by ryanfitzer** [comment]
The use case I have is for doing something once my `exec` command is finished. The `start` event has no way of listening for the command(s) in the `exec` option to complete.

Maybe I'm missing something in the API that enables this feature.
