### ISSUE TITLE
nodemon works but not nodemon + [app name.js]

### ISSUE THREAD

**Issue by xtianus79** [remy/nodemon#610]
I noticed that when I do nodemon app.js it doesn't use the 3000 port and thus isn't watching anything and or changing anything.  when i go to another terminal window and do npm start this will start port 3000 node session.  

if i only use nodemon then the oppisite is true.  The nodemon is on port 3000 and restarts when there are changes and the npm start port 3000 is closed of to that command.

**Comment by remy** [comment]
Needs information about what you're trying to run.
