### ISSUE TITLE
issue or perhaps a suggestion: Is there a livereload type feature for nodemon? 

### ISSUE THREAD

**Issue by xtianus79** [remy/nodemon#611]
I am wondering if this is possible to implement alongside of nodemone and in general... i know i could use grunt and gulp for html, css, and js changes... but what about when the nodemon is finished reloading it fires off a browser refresh.

Or? would gulp or grunt take care of that in a watch livereload implementation?

**Comment by remy** [comment]
There's not. You'd want another plugin for your existing build/thing/whever system.

**Comment by anthonybrown** [comment]
Is it correct to say that nodemon relies on Livereload to reload the page?

**Comment by tleb** [comment]
nodemon doesn't reload the page, what are you talking about?
