### ISSUE TITLE
Nodemon is hijacking app's command line options

### ISSUE THREAD

**Issue by valango** [remy/nodemon#612]
My nodeJS app processes it's command-line options, but will receive only those not recognized by Nodemon himself: 
* `nodemon srv.js --initdata` works as expected, because "--initdata" is unknown for nodemon, but
* `nodemon srv.js --help` will result in ***nodemon*** help screem.

Perhaps re-defining the command-line syntax as below would solve this issue:
```
Usage: nodemon [nodemon-options] [script.js] [script-arguments-and-options]
```

**Comment by remy** [comment]
You need (as per the docs):

```shell
