### ISSUE TITLE
Restarting continously when doing "grep" on Windows

### ISSUE THREAD

**Issue by DashNY** [remy/nodemon#613]
On Windows, using "git bash sell"

If I run this command while nodemon is running:

`grep -r "looking for this" .`

I get these:

[gulp] [nodemon] restarting due to changes...
[gulp] [nodemon] restarting due to changes...
[gulp] [nodemon] restarting due to changes...
[gulp] [nodemon] restarting due to changes...
....

Perhaps nodemon looks for the Last Access Time instead of Last Modification Time.
Please advise.

**Comment by remy** [comment]
I've no idea. Try with `nodemon --verbose -e "grep -r 'look for this'"` - it'll tell you what's causing the trigger, then ignore that file.
