### ISSUE TITLE
nodemon unresponsive ubuntu 14.04

### ISSUE THREAD

**Issue by rfarina** [remy/nodemon#614]
I noticed a recent thread that was never resolved. It had to do with nodemon not being found and simply returning nothing when "which nodemon" was issued.

I found a file, ".npmrc", which contained the directory into which node related modules are placed upon install. Mine was originally set to the following:
prefix=/home/me/.nvm/v0.10.35/
This resulted in nodemon being installed into this directory structure. However, that was from an older installation of node.

I then modified this to the location into which node is installed (by nvm), which is shown below:
prefix=/home/me/.nvm/versions/node/v0.12.7/

I then ran npm install -g nodemon. Everything was then placed in the correct location and ran as expected.

As a side note, I do not know if .npmrc will automatically be created if it doesn't exist; or if nvm or npm should be updating it upon installation. However, changing the path to the current version of node and then installing nodemon seemed to do the trick.

**Comment by remy** [comment]
This is an nvm related issue, rather than nodemon. Glad you were able to resolve your problem.
