### ISSUE TITLE
nodemon don't work

### ISSUE THREAD

**Issue by Elimane42** [remy/nodemon#618]
$ C:\Program Files\nodejs\node.exe C:\Users\ELIMANE\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.js server.js --dump

**Comment by remy** [comment]
Sounds about right.

You've of course tried without nodemon?

**Comment by Elimane42** [comment]
Yes i tried command with command node and it work

**Comment by Elimane42** [comment]
Can you help me pls?

**Comment by remy** [comment]
Ah well. With "nodemon won't work" I'm pretty sure I've nothing that I can go on to help you.
