### ISSUE TITLE
do something after the process is ready

### ISSUE THREAD

**Issue by celevra** [remy/nodemon#619]
Hi,

at first thanks for the work!
i use nodemon in gulp and want to refresh my browser after nodemon has restarted my server process, but it only makes sense to refresh if the server part is ready. Is there a way to communicate with nodemon and then trigger an event?

actually i just wait a second, here is my gulp task:
```
gulp.task('nodemon', function (cb) {
	
	var started = false;
	
	return nodemon({
		script: 'socket.js'
	}).on('start', function () {
		// to avoid nodemon being started multiple times
		// thanks @matthisk
		if (!started) {
			cb();
			started = true; 
		}
		else
		{
			//if server is reloaded, also reload client, we have to wait 1 second for the reload
			setTimeout(function() { browserSync.reload() }, 1000);;
		}
	});
});
```

regards

celevra

**Comment by remy** [comment]
When your process is started the `start` event is fired. If your script loads, say, 50 required modules, it'll take approx 500ms to start. If it loads 200, it might take 2000ms, if it waits to connect to a database that's laggy, it might take 10s - the point is - there's no way of knowing what "ready" means or when that happens. It's down to your user code to notify.

Maybe one work around is log out a message from your user script, and watch for that event in `nodemon.on('stdout', fn)` then watch for the string that is echoed out by your script.

**Comment by celevra** [comment]
Thats the information i was looking for! Thank you very much
