### ISSUE TITLE
find getting executed on showWatchCount even if useFind == false

### ISSUE THREAD

**Issue by santiagoaguiar** [remy/nodemon#620]
Using latest while running on windows on git bash, `showWatchCount` is getting executed and uses `find` even if `useFind` is `false`, which causes a:

    watching <a lot of> files - this might cause high cpu usage. To reduce use "--watch".

because the argument to find mixes windows/linux path seps and just doesn't work OK.

I think the offending line is here: https://github.com/remy/nodemon/blob/master/lib/monitor/watch.js#L168, which end ups calling `showWatchCount` event when `useFind` is false.

**Comment by remy** [comment]
Yeah, I can see why this is failing, because the test for find is: is this a mac, or linux or if `fs.watch` is not supported - which none are true for 'this is windows running git bash'. 

I think the only sensible answer here is allow a user defined config override - because I can't see a way to detect all the combo environments.

**Comment by santiagoaguiar** [comment]
`useFind` does resolve to false, even if `find` is present on git bash. And currently is a good thing, since because of how the paths are passed, using `find` wouldn't work under git bash as it is.

But in any case, `showWatchCount` now only works if `find` exists, though on the code it's called after  checking that `useFind` is false. Since as far as I can see, `showWatchCount` is purely informative, wouldn't it be possible to call it only if `useFind` is true until there's an implementation that does not uses `find`?

**Comment by remy** [comment]
Please try the build here #625 and feedback against the issue #625.

**Comment by santiagoaguiar** [comment]
I tried to, but the repo has some files (`test/fixtures/some \file`, `test/fixtures/some"file`, `test/fixtures/some\"file`) which aren't valid filenames on Windows, so git can't checkout the commit, and neither can npm. I could try it out on linux but that would defeat all purpose :). 

Thanks!!

**Comment by remy** [comment]
You can't npm install? It shouldn't be pulling down the development build...or at least I didn't think it would...

**Comment by santiagoaguiar** [comment]
I may be missing something, but `npm install nodemon` brings 1.4.1, but I should be trying out the version at #625, right? I tried that using a dependency to `git://github.com/remy/nodemon.git#feature-cleanup`, but that what fails because npm has to clone it with git, which fails on windows. 

Maybe there's some alternative command I'm missing, I'm kind of new ;).

**Comment by remy** [comment]
`npm install -g nodemon@dev` will give you the developement build that I'm publishing (as per #625 explains).

**Comment by santiagoaguiar** [comment]
Thanks! Missed the reference on your comment. 

There's no warning, and the `checkWatchSupport` does not falls through the `useFind` case, so it seems it's working OK! I'll keep using this version.
