### ISSUE TITLE
After update to 1.4.1 nodemon is not starting any longer node ./bin/www

### ISSUE THREAD

**Issue by TheFive** [remy/nodemon#621]
I just use the standard generated app with the npm start script:

 "start": "NODE_ENV=development node ./bin/www"

This was no problem in 1.4.0, but now i got the error:

----% nodemon
29 Aug 21:05:08 - [nodemon] v1.4.1
29 Aug 21:05:08 - [nodemon] to restart at any time, enter `rs`
29 Aug 21:05:08 - [nodemon] watching: *.*
29 Aug 21:05:08 - [nodemon] starting `NODE_ENV=development "node ./bin/www"`
sh: node ./bin/www: No such file or directory
util.error: Use console.error instead
[nodemon] failed to start process, "NODE_ENV=development" exec not found

node ./bin/www runs fine out of the directory where i start nodemon from.

The version 1.4.0 forces me to update, so i can't use nodemon yet :-(

Christoph

**Comment by remy** [comment]
What version were you on before?

**Comment by TheFive** [comment]
Hi Remy, 
i have installed a backup, it was the version 1.4.0. But "o wonder" with the backup i get the same problem. (and no update force yet).

**Comment by TheFive** [comment]
If I change 
"start": "NODE_ENV=development node ./bin/www"

to 

"start": "node ./bin/www"

it works, so may be there is a change in the background that causes the error.

As a workaround i have created a start script, setting the environment variable and starting ./bin/www.

May be it is a problem in my development configuration, and it is caused because i installed xcode terminal apps ?.

I am working on Yosemite 10.10.5 (all updates til now).
As i have a workaround, you can close the issue, if you want.

Christoph

**Comment by remy** [comment]
Can you test it with npm install -g nodemon@1.3 ?

**Comment by TheFive** [comment]
Hi Remy,

here the result.

    30 Aug 13:01:31 - [nodemon] v1.3.8
    30 Aug 13:01:31 - [nodemon] to restart at any time, enter `rs`
    30 Aug 13:01:31 - [nodemon] watching: *.*
    30 Aug 13:01:31 - [nodemon] starting `NODE_ENV=development "node ./bin/www"`
    sh: node ./bin/www: No such file or directory
    util.error: Use console.error instead
    [nodemon] failed to start process, "NODE_ENV=development" exec not found
    exception in nodemon killing node

**Comment by remy** [comment]
So looks like its been like this for a while.

**Comment by TheFive** [comment]
Just for your information...

    -----------------------------------------
    Update available: 1.4.1 (current: 1.3.8)
    Run npm update -g nodemon to update
    -----------------------------------------
    30 Aug 13:36:01 - [nodemon] v1.2.1
    30 Aug 13:36:01 - [nodemon] to restart at any time, enter `rs`
    30 Aug 13:36:01 - [nodemon] watching: *.*
    30 Aug 13:36:01 - [nodemon] starting `NODE_ENV=development node ./bin/www`
    util.error: Use console.error instead
    [nodemon] unable to run executable: "NODE_ENV=development"


    30 Aug 13:37:08 - [nodemon] v1.1.1
    30 Aug 13:37:08 - [nodemon] to restart at any time, enter `rs`
    30 Aug 13:37:08 - [nodemon] watching: *.*
    30 Aug 13:37:08 - [nodemon] starting `NODE_ENV=development node ./bin/www`
    util.error: Use console.error instead
    [nodemon] unable to run executable: "NODE_ENV=development"

**Comment by nicothed** [comment]
I have the same issue: 1.4.0 was working fine, but now, when a file changes, it displays:
7 Sep 13:45:40 - [nodemon] restarting due to changes...
but doesn't restart! :(

I tried reverting to v1.3.0, 1.4.0 and back to 1.4.1 but it's all the same behavior now.

Maybe 1.4.1 set up a parameter somewhere that sticks even when we revert?

**Comment by alberto-f** [comment]
Hey, I just tried version 1.7.0 and while it detects when Im updating the files the browser its not updated.  Pretty much as the prev. issues were saying. Was it fixed?

**Comment by remy** [comment]
@alberto-f "the browser is not updated" - ? Updating the browser isn't part of nodemon. I suspect you're confusing this with something like live-reload...?
