### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by gs-akhan** [remy/nodemon#630]
Updated to Node4.0 and this is what I get ..
Segmentation fault: 11

**Comment by remy** [comment]
Do you think it's worth either updating nodemon or actually saying what version you're using...?

Basically, update nodemon to latest.

**Comment by gs-akhan** [comment]
Obviously that's basic thing every one does before posting an issue .
BTW for your info it is 1.5.0
Thanks

**Comment by remy** [comment]
So you're on nodemon@1.5.0 and node@4? And you're seeing a segfault?

If you are, can you run `nodemon --dump` from the directory you normally run from so I can see more details? 

I'm running this config on a mac, and have had no problems (along with Travis tests running under node@4 - so there must be something about the system I'm missing).

**Comment by james-bw** [comment]
I'm getting the same on Mac with node@4 and nodemon@1.5.1

$ node -v
v4.0.0

$ npm -v
2.14.3

$ sudo npm i nodemon -g
 
> fsevents@0.3.8 install /usr/local/lib/node_modules/nodemon/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw { dev: 16777224,
  mode: 33188,
  nlink: 1,
  uid: -2,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 63617737,
  size: 1361,
  blocks: 8,
  atime: Wed Sep 16 2015 21:50:15 GMT+1000 (AEST),
  mtime: Wed Sep 16 2015 21:50:15 GMT+1000 (AEST),
  ctime: Wed Sep 16 2015 21:50:15 GMT+1000 (AEST),
  birthtime: Wed Sep 16 2015 21:50:15 GMT+1000 (AEST) }
  SOLINK_MODULE(target) Release/fse.node
/usr/local/bin/nodemon -> /usr/local/lib/node_modules/nodemon/bin/nodemon.js
nodemon@1.5.1 /usr/local/lib/node_modules/nodemon
├── undefsafe@0.0.3
├── es6-promise@3.0.2
├── debug@2.2.0 (ms@0.7.1)
├── minimatch@0.3.0 (lru-cache@2.7.0, sigmund@1.0.1)
├── touch@1.0.0 (nopt@1.0.10)
├── ps-tree@0.0.3 (event-stream@0.5.3)
├── lodash.defaults@3.1.2 (lodash.restparam@3.6.1, lodash.assign@3.2.0)
├── chokidar@1.0.5 (arrify@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6, path-is-absolute@1.0.0, is-binary-path@1.0.1, readdirp@1.4.0, fsevents@0.3.8, anymatch@1.3.0)
└── update-notifier@0.5.0 (is-npm@1.0.0, semver-diff@2.0.0, string-length@1.0.1, chalk@1.1.1, repeating@1.1.3, latest-version@1.0.1, configstore@1.2.1)


$ nodemon --dump
Segmentation fault: 11

$ nodemon -v
Segmentation fault: 11

$ uname -a
Darwin James-iMac.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64


Thanks!

**Comment by gs-akhan** [comment]
Yup. Sorry for not responding. But this the same config I have as said by james-bw.

Thanks !

**Comment by remy** [comment]
@james-bw I've got a very similar setup, but my mac `uname` is slightly different. I'm on Yosemite, what are you on? (I lose track of the different Mac OS, I generally avoid upgrading these days to avoid the inevitable iOS UI merge...)

**Comment by yang-wei** [comment]
Same thing happen here. nodemon 1.5.1 is not working with node v4.0.

```
❯ node -v                                                                                                                                      
v4.0.0
❯ npm -v                                                                                                                                          
2.14.2                                                                                                                         
❯ uname -a                                                                                                                                        
Darwin MacBook-Air.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

> nodemon index.js
[1]    68348 segmentation fault  npm start
❯ ./node_modules/nodemon/bin/nodemon.js --debug index.js                                                                                        
[1]    68962 segmentation fault  ./node_modules/nodemon/bin/nodemon.js --debug index.js
```

 When I switch back to node v0.12.7 then it works normally.

**Comment by remy** [comment]
Can you try running with `DEBUG=nodemon,nodemon:* nodemon index.js` so we can see how far it gets before it bails.

**Comment by remy** [comment]
Can you also confirm the version of osx you're running. I think it's El Capitain in but I'm not 100% sure.

**Comment by yang-wei** [comment]
running `DEBUG=nodemon,nodemon:* nodemon index.js` also gave me the same error.

However, Nodemon works like expected when I installed it globally and use. Strange. Any idea?

I am using Yosemite.

**Comment by remy** [comment]
@yang-wei how were you including it locally? Through a regular node module or via grunt/gulp plugins?

**Comment by remy** [comment]
@james-bw can you also try `DEBUG=* nodemon --dump`

**Comment by yang-wei** [comment]
@remy Just a regular node module.

**Comment by arosequist** [comment]
I had this same issue, but it was solved by upgrading to Node v4.1.1. I'm not sure if that was the fix or just coincidental.

**Comment by mattcallanan** [comment]
> Nodemon works like expected when I installed it globally and use.

+1

```npm install -g nodemon``` fixed it for me (running Node v4.0.0 on Yosemite)

```
$ nodemon ./bin/www
Segmentation fault: 11

$ node -v
v4.0.0

$ npm install -g nodemon

> fsevents@1.0.1 install /usr/local/lib/node_modules/nodemon/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/usr/local/lib/node_modules/nodemon/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" is installed via remote
/usr/local/bin/nodemon -> /usr/local/lib/node_modules/nodemon/bin/nodemon.js
nodemon@1.7.1 /usr/local/lib/node_modules/nodemon
├── undefsafe@0.0.3
├── es6-promise@3.0.2
├── debug@2.2.0 (ms@0.7.1)
├── minimatch@0.3.0 (sigmund@1.0.1, lru-cache@2.7.0)
├── touch@1.0.0 (nopt@1.0.10)
├── ps-tree@0.0.3 (event-stream@0.5.3)
├── lodash.defaults@3.1.2 (lodash.restparam@3.6.1, lodash.assign@3.2.0)
├── update-notifier@0.5.0 (is-npm@1.0.0, string-length@1.0.1, chalk@1.1.1, repeating@1.1.3, semver-diff@2.0.0, configstore@1.2.1, latest-version@1.0.1)
└── chokidar@1.1.0 (arrify@1.0.0, path-is-absolute@1.0.0, glob-parent@2.0.0, async-each@0.1.6, is-binary-path@1.0.1, is-glob@2.0.1, readdirp@2.0.0, anymatch@1.3.0, fsevents@1.0.1)

$ nodemon ./bin/www
2 Oct 20:07:49 - [nodemon] 1.7.1
2 Oct 20:07:49 - [nodemon] to restart at any time, enter `rs`
2 Oct 20:07:49 - [nodemon] watching: *.*
...
```

**Comment by gs-akhan** [comment]
After updating to 4.1.0 every thing works fine for me..

**Comment by remy** [comment]
Close?

**Comment by gs-akhan** [comment]
Sure. :)
