### ISSUE TITLE
Segmentation fault: 11 error

### ISSUE THREAD

**Issue by iamwave007** [remy/nodemon#632]
I installed the newest version1.5.0  and it's giving me this when i run it..

**Comment by remy** [comment]
Dupe of #630 - I'm closing, please read the thread and add all the information you can to help diagnose.

**Comment by iamwave007** [comment]
Thanks it's working!

**Comment by remy** [comment]
What changed?

**Comment by iamwave007** [comment]
i don't really know, i re-installed nodemon; the first time i installed it, internet might have been interrupted.
