### ISSUE TITLE
force polling mode

### ISSUE THREAD

**Issue by moszeed** [remy/nodemon#633]
Hi,
is there a way to enable the polling mode of "chokidar" in nodemon ?

I`m on Windows 10, with a Vagrant (boot2docker) -> Docker Dev environment, using the latest Nodemon 1.5 from npm. 
But restart on file changes never happen anymore.

I am using nodemon within the scripts area of package.json:
```
"scripts": {
  "watch:js"  : "nodemon -delay 300ms -e js -w ./scripts/ -x 'npm run build:js'",
  "watch:css" : "nodemon -delay 300ms -e less -w ./styles/ -x 'npm run build:css'",
  "watch:html": "nodemon -delay 300ms -e tpl -w ./templates/ -x 'npm run build:html'",
}
```

**Comment by remy** [comment]
There isn't, but this should be exposed as an option that carries through to chokiar. nodemon used to have "legacy" mode, which is /kinda/ the same, but I can see that exposing polling would be useful.

**Comment by moszeed** [comment]
Thx. Youre awesome  =) 
It`s working !
