### ISSUE TITLE
File changes not detected since 1.4.2 in vagrant/shared diretory

### ISSUE THREAD

**Issue by mfn** [remy/nodemon#635]
I've had 1.4.1 running for months, upgraded today to 1.5.0 and backtracked until 1.4.2 which broke the file change detection feature. I assume it's because of this:

> Move to using Chokidar library for all file watching - closes many issues

I'm running nodemon on a VirtualBox shared directory (nfs) with the host system (OSX), I'm running nodemin **inside** the VM.

**Comment by remy** [comment]
Suspect, this can be fixed with this #633

I'll close as I think it's a dupe, but feel free to let me know if this is wrong (as in, you have any more information).
