### ISSUE TITLE
Nodemon not restarting on save

### ISSUE THREAD

**Issue by chewax** [remy/nodemon#638]
I don't know if is happening to anyone else. But after last update nodemon fail to restart on save.
I am  using it the same as always.
Thanks

**Comment by remy** [comment]
Environment? Version? etc etc...?

**Comment by ves-krd** [comment]
Happening here too.  nodemon -V returns watching 0 files.

**Comment by ves-krd** [comment]
Windows Server 2008 R2 Standard
nodemon v1.5.1

**Comment by remy** [comment]
Can you try with the `-L` legacy flag - it'll enable polling for watching.

**Comment by cmcarey** [comment]
I get an identical error (no detection of file save).
Using the legacy flag works.

OSX 10.10.3, node v4.1.0, nodemon 1.6.1.

**Comment by remy** [comment]
Using nodemon@1.6.1 the legacy watch flag should work. Can you all reply to
confirm (or not) as to whether you're monitoring over a network drive?

**Comment by cmcarey** [comment]
Not monitoring over a network drive.

Oddly enough, after a restart, detection (sans legacy flag, though that still works) is acting correctly.  There's occasionally a delay of 10-20 seconds, but it works now.

**Comment by remy** [comment]
@cmcarey is there any different with `-L`? Also, can you tell me how many files it says it's monitoring?

**Comment by chewax** [comment]
Hi, sorry for the lack of info. 
I am running v1.5.1 over OSX 10.10.3.
Not monitoring a network file. I am even running as sudo.
Thanks

**Comment by remy** [comment]
@chewax so, to be clear, the `-L` means that nodemon is now restarting? (this flag was dropped between 1.4 and 1.6 which is why you were missing it).

Can you confirm how many files nodemon is reportedly watching?

**Comment by chewax** [comment]
Yes with -L is working fine.

[nodemon] watching 37 files

Thanks!

**Comment by ashwinbc** [comment]
can someone please give me the command with -l as argument ?

**Comment by chewax** [comment]
Arguments are Case Sensitive. L is mayus thus:
`sudo nodemon -L`

Hope this helps
