### ISSUE TITLE
Detect changes in JSON files

### ISSUE THREAD

**Issue by pensierinmusica** [remy/nodemon#643]
Hi,

I'm using `nodemon` (v1.6.1) with Node (v4.1.0), it works perfectly but it doesn't detect changes in any ".json" files. Is this default behavior? How can it be changed?

Since in a server environment JSON files usually contain some settings, imho nodemon should restart by default when the content of a JSON file is changed.

Looking forward to hear your feedback, thanks!

**Comment by remy** [comment]
I wouldn't normally agree since you have it documented here https://github.com/remy/nodemon/blob/master/README.md#specifying-extension-watch-list but if you fix your commits I'll merge.

**Comment by pensierinmusica** [comment]
Hi @remy, thanks, I hope it's fixed now! Let me know if it all looks good to you, cheers :)
