### ISSUE TITLE
`rs` does not works after `process.exit()`

### ISSUE THREAD

**Issue by nitriques** [remy/nodemon#648]
I have a node app that calls process.exit() when some conflicted state arise. But after this, nodemon refuses to restart if the files does not changes. I think that typing `rs` should restart the monitored process even if the monitored process did exit cleanly.

You can reproduce the bug using this really simple code:

```js
'use strict';

setTimeout(function () {
	console.log('timer 1: exiting...');
	process.exit();
}, 1000);

setTimeout(function () {
	console.log('timer 2: will never appear, which is ok.');
}, 2000);
```

nodemon displays:

```
2 Sep 20:34:13 - [nodemon] v1.7.0
22 Sep 20:34:13 - [nodemon] to restart at any time, enter `rs`
22 Sep 20:34:13 - [nodemon] watching: *.*
22 Sep 20:34:13 - [nodemon] starting `node test.js`
timer 1: exiting...
22 Sep 20:34:14 - [nodemon] clean exit - waiting for changes before restart
rs

```

BTW, I am running node 0.12.7 for legacy reasons. (test was made on OS X 10.10.4)

**Comment by remy** [comment]
Live in 1.7.1 - and thank you for a well formed bug report! Easy to replicate and to debug :)

**Comment by nitriques** [comment]
My pleasure :)

Thanks for being for quick to fix it!

But is `live` meant to be `on npm` ? 'Cause right now, it ain't. But no stress, I can wait (just wanted to test...)
