### ISSUE TITLE
Not watching files

### ISSUE THREAD

**Issue by zetxx** [remy/nodemon#650]
Nodemon will not watch files if is run inside node_modules directory, for instance:

if run nodemon from /a/b/c it will watch files correctly, but
if it is run inside /a/node_modules/c it will not watch any files.

**Comment by remy** [comment]
No, it won't, you need to work with your config to override nodemon's defaults: https://github.com/remy/nodemon/blob/master/faq.md#overriding-the-underlying-default-ignore-rules

**Comment by zetxx** [comment]
i tried that, but when i remove node modules from config another issue comes out, because my project is in node_modules dir there is another node_modules dir which is in my project folder itself and i want to ignore it but it didnt work ...
