### ISSUE TITLE
Watch broken due to uncommon file path characters

### ISSUE THREAD

**Issue by kirkstrobeck** [remy/nodemon#655]
See https://github.com/remy/nodemon/issues/653#issuecomment-142973551

> Ah ha! I think I know what it is .. the file path is
> 
> ```
> /Users/kirkstrobeck/Dropbox (Personal)/Sync/git/kirkstrobeck/foo/
> ```
> 
> I believe the characters `(` and ` ` are the culprits.

Assuming this distinction was lost in the closure of the previous issue.

**Comment by gtramontina** [comment]
This one bit me too... my project directory is `~/workspaces/gtramontina.github.io` and I couldn't get `nodemon` working until I found this issue and renamed my project so I get rid of those `.` …
