### ISSUE TITLE
Sub Directories

### ISSUE THREAD

**Issue by tylorr** [remy/nodemon#66]
I running into an issue where nodemon is not restarting my app when any files in sub-directories are changed.

I am running a socketstream app
I call nodemon using the following command: `sudo nodmon app.js`

The server only restarts if I change root files

I can get the server to restart if I add watches to the command 

```
sudo nodemon -w . -w server/rpc/ app.js
```

Now it will listen to changes in the root folder and the server/rpc/ folder

**Comment by pencilcheck** [comment]
The server didn't restart when I edit one of the file in a subfolder. I'm on the latest version

**Comment by remy** [comment]
Please include full output with `DEBUG=nodemon,nodemon:*` in your environment. Otherwise I have no information at all to debug with.

**Comment by rabeesh** [comment]
@remy Same issue happens for me in Ubuntu 14.04.3 LTS

**Comment by jonataswalker** [comment]
If I include `--ext scss` (obvious, this can be anything else) then I have it fired on subdirectory.

**Comment by Hulkmaster** [comment]
got the same issue 
--ext doesnt help

**Comment by Hulkmaster** [comment]
achieved with **/*.less

full command i use
nodemon --watch **/*.less --ext less --exec 'npm run build-less'

**Comment by faraazahmad** [comment]
It says it's watching in `app/**/*` but doesn't restart when changes are made in files that are 2 levels deep.

```
> going@0.0.0 start /home/faraaz/oss/going
> nodemon --watch app/ --exec ./bin/www

[nodemon] 1.18.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /home/faraaz/oss/going/app/**/*
[nodemon] starting `./bin/www`
```
