### ISSUE TITLE
not restarting when new files are added

### ISSUE THREAD

**Issue by omnidan** [remy/nodemon#664]
I have a script that automatically `git pulls` when there are updates. The directory for that is `/home/james/git/`. I'm trying to get `nodemon` to restart a bash script when there are updates.

The command I have for this is: `nodemon -w /home/james/git --exec "bash" ./start_hubot.sh` - which is run in the `/home/james/git` directory.

It runs fine and even shows it's watching the directory:

```
30 Sep 20:31:56 - [nodemon] watching: /home/james/git/**/*
30 Sep 20:31:56 - [nodemon] starting `bash ./start_hubot.sh`
```

But when I `git pull`, it's not restarting the script. Typing `rs` and restarting manually does work, however.

**Comment by remy** [comment]
Can you re-run and report back with `DEBUG=nodemon,nodemon:* nodemon -w /home/james/git --exec "bash" ./start_hubot.sh`

**Comment by omnidan** [comment]
I tried creating two files with `touch test` and `touch test2` in the directory. `nodemon` seems to detect these files, but doesn't restart the process. Here is the full output:

```
www-data@api:/home/james/git$ DEBUG=nodemon,nodemon:* nodemon -w /home/james/git --exec "b
ash" ./start_hubot.sh
  nodemon bus new listener: reset (0) +0ms
  nodemon bus new listener: reset (0) +1ms
  nodemon bus new listener: quit (0) +4ms
  nodemon bus new listener: quit (0) +0ms
  nodemon bus new listener: restart (0) +0ms
  nodemon bus new listener: restart (0) +0ms
  nodemon bus new listener: reset (2) +1ms
  nodemon bus emit: reset +1ms
  nodemon:watch resetting watchers +0ms
  nodemon reset +0ms
  nodemon config: dirs +53ms [ '/home/james/git' ]
1 Oct 20:03:32 - [nodemon] 1.7.1
1 Oct 20:03:32 - [nodemon] to restart at any time, enter `rs`
1 Oct 20:03:32 - [nodemon] watching: /home/james/git/**/*
1 Oct 20:03:32 - [nodemon] starting `bash ./start_hubot.sh`
  nodemon spawning +2ms bash ./start_hubot.sh
  nodemon bus new listener: exit (0) +1ms
  nodemon bus new listener: exit (0) +1ms
  nodemon start watch on: /home/james/git +0ms
  nodemon start watch on: /home/james/git +0ms
  nodemon ignore dirs regex(/\.git|node_modules|bower_components|\.sass\-cache/) +0ms
  nodemon:watch watching dir: /home/james/git/.editorconfig +9ms
  nodemon:watch watching dir: /home/james/git/.hubot_history +0ms
  nodemon:watch watching dir: /home/james/git/Procfile +0ms
  nodemon:watch watching dir: /home/james/git/README.md +0ms
  nodemon:watch watching dir: /home/james/git/external-scripts.json +0ms
  nodemon:watch watching dir: /home/james/git/hubot-scripts.json +0ms
  nodemon:watch watching dir: /home/james/git/package.json +0ms
  nodemon:watch watching dir: /home/james/git/start_hubot.sh +0ms
  nodemon:watch watching dir: /home/james/git/bin/hubot +1ms
  nodemon:watch watching dir: /home/james/git/bin/hubot.cmd +0ms
  nodemon:watch watching dir: /home/james/git/scripts/example.coffee +1ms
  nodemon:watch watching dir: /home/james/git/scripts/whois.coffee +0ms

> time@0.11.4 install /home/james/git/node_modules/time
> node-gyp rebuild

make: Entering directory `/home/james/git/node_modules/time/build'
  CXX(target) Release/obj.target/time/src/time.o
  SOLINK_MODULE(target) Release/obj.target/time.node
  COPY Release/time.node
make: Leaving directory `/home/james/git/node_modules/time/build'

> ws@0.4.31 install /home/james/git/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/james/git/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory `/home/james/git/node_modules/ws/build'
[Thu Oct 01 2015 20:03:36 GMT+0200 (CEST)] INFO Connecting...
[Thu Oct 01 2015 20:03:37 GMT+0200 (CEST)] INFO Logged in as james of TouchLay, but not yet connected
[Thu Oct 01 2015 20:03:38 GMT+0200 (CEST)] INFO Slack client now connected
[Thu Oct 01 2015 20:03:38 GMT+0200 (CEST)] INFO hubot-redis-brain: Using default redis on localhost:6379
  nodemon:watch watching dir: /home/james/git/test +36s
  nodemon:watch watching dir: /home/james/git/test2 +34s
^C  nodemon bus emit: quit +17s
  nodemon bus emit: quit +9ms
```

**Comment by omnidan** [comment]
@remy any updates on this issue?

**Comment by remy** [comment]
No, sorry. Was there a PR attached?

**Comment by omnidan** [comment]
@remy nope, I found the issue and you asked me for debug output, which I posted - now I'm waiting on a fix :grin: Anyway, it seems like it detects the changes but does not restart. Doing `rs` manually works, though.

**Comment by remy** [comment]
Hmm. I think I can see the problem now: https://github.com/remy/nodemon/blob/master/lib/monitor/watch.js#L60-L61 it will only restart on change, not add. It's tricky because now we've got a chicken and egg problem: what point does an `add` trigger a restart? Not during boot, but after things have settled... is that the ready event?...

**Comment by omnidan** [comment]
@remy maybe make a flag that watches `add` too so it doesn't cause any issues for existing workflows. there should be no `add` event during boot, right?

**Comment by remy** [comment]
It adds as it watches. You can see it in your logs.

**Comment by omnidan** [comment]
@remy I'm talking about restarting on `add`, sorry if it was unclear. :sweat_smile:

**Comment by remy** [comment]
I am too.

The first is `nodemon:watch watching dir: /home/james/git/.editorconfig +9ms` in your log. Then 30 or so seconds later you touch the files, and you see `nodemon:watch watching dir: /home/james/git/test +36s`

There's no programmatic difference, but I wonder if the `ready` event might have fired between...

**Comment by omnidan** [comment]
@remy I'm kinda confused - do you need anything else from me to work on the fix? :grin:
