### ISSUE TITLE
how to pass child process/script name to events?

### ISSUE THREAD

**Issue by runofthemill** [remy/nodemon#671]
I'm using nodemon in my build process, via a packages.json script. I've looked through the documentation, but can't figure out how to pass the name of the child process/script that triggers nodemon to the events in nodemon.json. Is this possible?

Thanks!

**Comment by remy** [comment]
Do you mean `$FILENAME` seen in the exmaple here https://github.com/remy/nodemon/blob/master/doc/sample-nodemon.md ?

**Comment by runofthemill** [comment]
*palm to face*

I was trying to do this:

```
{
  "events": {
    "restart": "osascript -e 'display notification '$FILENAME' with title \"nodemon\"'"
  }
}
```

since I didn't really care for the rest of the text - not realizing that the notification needed to be between escaped quotes -_-

thanks for the help. closing this, but as an aside, is there a variable for the name of the script running? i.e. print 

```
App restarted due to 'watch-css'
```

cheers!
