### ISSUE TITLE
"npm install" hangs forever

### ISSUE THREAD

**Issue by yinrong** [remy/nodemon#676]
npm install nodemon hangs forever, which may be caused by trying to access github.com during the install process. (my network forbids access to github.com:22)

I can use nodemon then. Could anyone have a method to install nodemon with "npm install"?

**Comment by remy** [comment]
Can you change the network on your machine to install the tool?

Closing as this isn't actually anything to do with nodemon, more npm or the network.

**Comment by yinrong** [comment]
almost all npm package works find with my current network. hope nodemon could align with this.

**Comment by remy** [comment]
Nodemon doesn't do anything special with npm. Clear your npm cache and if
persists raise an issue with npm.
