### ISSUE TITLE
Nodemon and Fedora `node: No such file or directory`

### ISSUE THREAD

**Issue by markjlorenz** [remy/nodemon#68]
If you try to run
`$ nodemon server.js`

You'll get :
`/usr/bin/env: node: No such file or directory`

This is because in Fedora `node` is called `nodejs`

This can be fixed by changing: `#!/usr/bin/env node` on the first line of  `/usr/lib/node_modules/nodemon/nodemon.js` to `#!/usr/bin/env nodejs`

**Comment by andrecastilho** [comment]
Thanks, helped me very...

**Comment by marswong** [comment]
it may be better to use [nvm](https://github.com/creationix/nvm) on linux, it can save you much time from chores, tested for years :)

**Comment by niranjan470** [comment]
Hi i have same problem, when i am trying to ssh & start node from different server its throwing me error

env: node: No such file or directory

installed node as binary in centos 7 and gave path in bash_profile, it works fine when i run from save server, node version is 8.9.2
