### ISSUE TITLE
Flag to restart even on clean exit

### ISSUE THREAD

**Issue by omnidan** [remy/nodemon#683]
Unfortunately, `hubot` seems to exit with an error but has status 0 so it seems like a clean exit - would be nice if there was a flag in nodemon that allows me to still restart even on clean exit.

**Comment by remy** [comment]
Sounds like a bug in hubot.

**Comment by omnidan** [comment]
@remy yes it does seem to be a bug with the slack bridge for hubot, but it would be nice if nodemon had a flag that allows me to restart even on clean exit.

**Comment by remy** [comment]
Sorry, I don't want to add more flags to nodemon to work around a bug in another system - just trying to keep to [this](https://github.com/remy/nodemon/blob/master/CONTRIBUTING.md#sending-pull-requests).

Happy to reconsider if there's a significant +1s on this issue.

**Comment by omnidan** [comment]
@remy I wouldn't say it's just to work around a bug in another system, what if I want to rerun a program even if it exits without error?

**Comment by remy** [comment]
You can use nodemon as part of another application, so you could just wrap
it. Or just use bash to while true...

**Comment by omnidan** [comment]
@remy fine. I guess `while true` is the "best" solution then, but it doesn't allow me to listen to changes. So maybe I should just wrap `nodemon` with `while true`, but then there's still https://github.com/remy/nodemon/issues/664 :unamused:

**Comment by Mstrodl** [comment]
+1 I guess :P I have a bot that exits with 0 for an unknown reason and it's very annoying.
