### ISSUE TITLE
nodemon Starts Watching Before Previous Gulp Tasks are Done

### ISSUE THREAD

**Issue by pahund** [remy/nodemon#697]
I have a Gulp task that uses nodemon to restart my Express web app when files are changed. This worked perfectly until I updated my dependency to nodemon from 1.7.0 to 1.7.1. 

Now the nodemon watch starts before the previous Gulp tasks that build resources are done, causing nodemon to restart the app multiple times, once for each watched file.

This is what my Gulp task looks like: https://gist.github.com/pahund/40d3f4c4757ad35a2ca9

**Comment by remy** [comment]
Can you try with 1.8.

Also, I don't use gulp and don't have the build chain to get going, so you may need to debug this (if it's still an issue) and send a PR. 

Closing in hope that it's fixed (or I get a PR!) :)

**Comment by pahund** [comment]
Unfortunately, watching files does not work at all with 1.8.0 (see https://github.com/remy/nodemon/issues/685)
