### ISSUE TITLE
Option to only reload on change after crash

### ISSUE THREAD

**Issue by danieldiekmeier** [remy/nodemon#701]
Would it be possible to add an option that Nodemon will only reload the file if it has previously encountered an error?

I use Nodemon to "wrap” Gulp to stop it from crashing hard, so I don't have to restart it all the time. But I actually only want Nodemon to reload Gulp if there was an error before, because otherwise the Gulp handles the watching itself.

(Maybe my use case is stupid, and I should fix my Gulpfile.)

**Comment by remy** [comment]
We can't track the actual error that caused the crash, only the signal from the child process. So I don't think this is possible.
