### ISSUE TITLE
*reduce* delay

### ISSUE THREAD

**Issue by ORESoftware** [remy/nodemon#705]
Hi Remy et co

I read that you can add delay with the --delay option to nodemon - but I am wondering if there is a way to *reduce* the day from the default 1 second.

Is that possible? I find myself staring/watching the terminal waiting for nodemon to pick up changes and I think it has to do with the 1 second default delay amount.

is there a way to do this or am I mistaken?

**Comment by remy** [comment]
"et co"? There is no "co". It's just me here. So any help is appreciated.

What version of nodemon are you on? And OS please.

**Comment by ORESoftware** [comment]
:) a one man army - so I am on Mac OSX mavericks, nodemon v1.4.1

thanks

**Comment by remy** [comment]
Update nodemon to latest.

**Comment by ORESoftware** [comment]
ok thanks Remy is there a new option that reduces delay or is the default now less than 1 second, please explain :)

**Comment by ORESoftware** [comment]
or was I just using an old version?

**Comment by remy** [comment]
You were using an old version. The internal watch method was refactored and
so isn't anywhere near as laggy.

**Comment by ORESoftware** [comment]
muchos gracios
