### ISSUE TITLE
How to stop nodedemon from a .batch file?

### ISSUE THREAD

**Issue by wzup** [remy/nodemon#708]
I want to use Windows batch file to start a server and to stop a server. I know how to start a server from a batch file:

`START "" nodemon --debug -e js,dust,html,css,scss,rb,json`

But how to stop it the same way?

Question on Stackoverflow http://stackoverflow.com/questions/33410081/how-to-stop-nodemon-from-a-batch-file

**Comment by remy** [comment]
Not sure that's a nodemon question, but rather a windows batch file question, because really you could start anything and would want to kill it later (I'm guessing, but I think you want a windows service not a batch file). Closing (with all respect) as it's off topic.
