### ISSUE TITLE
Nodemon cant install on OSX El Capitan due security issues(apple remove full access of super user). 

### ISSUE THREAD

**Issue by jcbritobr** [remy/nodemon#713]
The new "security feature" of OSX El Capitan blocks npm to install nodemon. In El Capitan, sudo cant write on systems folder.

/usr/local/bin/nodemon -> /usr/local/lib/node_modules/nodemon/bin/nodemon.js

> fsevents@1.0.2 install /usr/local/lib/node_modules/nodemon/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/julio/.node-gyp/5.0.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/nodemon/node_modules/fsevents/.node-gyp"
make: *** No rule to make target `../.node-gyp/5.0.0/include/node/common.gypi', needed by `Makefile'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node" "--module_name=fse" "--module_path=/usr/local/lib/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64"
gyp ERR! cwd /usr/local/lib/node_modules/nodemon/node_modules/fsevents
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node --module_name=fse --module_path=/usr/local/lib/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/nodemon/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 15.0.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/nodemon/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/nodemon/node_modules/fsevents
node-pre-gyp ERR! node -v v5.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.12
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node --module_name=fse --module_path=/usr/local/lib/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64' (1)
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "nodemon"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! fsevents@1.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fsevents@1.0.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/julio/Projects/goworkspace/npm-debug.log

**Comment by jcbritobr** [comment]
It works if i pass --unsafe-perm on the command line.

**Comment by remy** [comment]
I'll add this to the FAQ.

**Comment by remy** [comment]
https://github.com/remy/nodemon/blob/master/faq.md#cant-install-nodemon-permission-issue

**Comment by Channely** [comment]
Well, it worked. ☃
