### ISSUE TITLE
Only manual reload?

### ISSUE THREAD

**Issue by Industrial** [remy/nodemon#716]
Hi. I was wondering if it's possible to have nodemon not react at all to any changes made on disk and to tell it manually when to reload.

This is what happens currently:
  1. I start gulp.
  1. It runs all the compile tasks successfully and then starts nodemon in the server task.
  1. Nodemon starts the app correctly.
  1. I make a change to a file that is not related to the `src/server/boot` directory, e.g. the `src/client/js/actions.js` file.
  1. Due to the watch task, the babel task gets triggered on this file change, writing a `build/client/js/actions.js` file.
  1. Immediately, all of a sudden, I get a lot of output from nodemon that it has detected file changes on files that I didn't do anything with and nodemon keeps restarting 10+ times in 1 second, tripping over itself.

Here is the code: https://gist.github.com/Industrial/87e3a27c432de69a218d#file-output-txt-L57

**Comment by remy** [comment]
Can you replicate the process without gulp please? Thanks.

**Comment by remy** [comment]
Can you try nodemon@1.8.1 (just released).

**Comment by connor4312** [comment]
I also have this issue. Doing actions such as `git checkout` (even to a new branch, without js changes) cause a _massive_ amount of reloads -- ~370 when I just tried it -- which eats memory and effectively locks up my computer for several minutes. This makes nodemon pretty much unusable to me.

I am on 1.8.1.
