### ISSUE TITLE
How do you pronounce `nodemon`?

### ISSUE THREAD

**Issue by ppiekarczyk** [remy/nodemon#719]
- no demon
- node mon
- node emon

I've heard everything. No one can decide if it's one or the other. How do you pronounce it? Based on the horned `n` in the readme, I can assume it's `no demon`, but i want to make sure...

**Comment by ppiekarczyk** [comment]
Damnit.

**Comment by zackexplosion** [comment]
+1

**Comment by remy** [comment]
For completeness: https://github.com/remy/nodemon#pronunciation

**Comment by sselfridge** [comment]
https://github.com/remy/nodemon/blob/master/README.md#pronunciation

New url for above link

**Comment by felixOvianet** [comment]
`node emon` ftw!

**Comment by rohitkrishna094** [comment]
I think its `no demon` right? coz the logo has horns and stuff.
