### ISSUE TITLE
Flag -L stops working in 1.8.0

### ISSUE THREAD

**Issue by jami** [remy/nodemon#720]
nodemon 1.8.0 did not get any fs changes in a vagrant/vboxfs environment. The -L Flag works perfectly for me in the version 1.7.3

nodemon: 1.8.0
node: v4.2.1
npm: 2.14.7
host: vagrant/vbox ubuntu trusty64
fs: vboxfs mount of a mac osx HFS+

**Comment by madbence** [comment]
Maybe it's related to #710? `1.8.1` was released recently that fixed that issue.
