### ISSUE TITLE
Errors in 1.8.1: FSEvents.framework

### ISSUE THREAD

**Issue by bendytree** [remy/nodemon#721]
I've been on nodemon `1.3.7` and everything was fine.

I updated to `1.8.1` today and when nodemon starts it gives me hundreds of these errors:

```
(FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
(FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
(FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
...
```

Eventually the app still runs, but only after nodemon logs a ton of these errors.

I uninstalled `1.8.1` and reinstalled `1.3.7` (`npm install nodemon@1.3.7 -g`) and it is working properly.

My setup:
- OSX 10.11.1
- NodeJS 0.10.26

**Comment by dotnetCarpenter** [comment]
I'm not seeing any error messages but nodemon --watch does not work anymore. I downgraded to 1.3.8 and it works as usual.

OSX 10.10.5
node 5.0.0
xcode-select version 2339

**Comment by remy** [comment]
@dotnetCarpenter it sounds like your issue is not related to this original issue at all, right?

**Comment by remy** [comment]
@bendytree how many files are you expecting to watch? Googling this error seems to pop up results around watching a massive amount of files due to overly generous globs.

**Comment by dotnetCarpenter** [comment]
@remy I don't know. My UX that the `--watch` flag doesn't work anymore. It could be due to issues with the FSEvents.framework on mac but could also happen for other reasons. Though I haven't had any issue on Windows or Linux.
