### ISSUE TITLE
npm WARN install Couldn't install optional dependency: 

### ISSUE THREAD

**Issue by sudeepdk** [remy/nodemon#728]
I m getting error while installing npm packages like nodemon and babel.
I have upgraded to Windows10 before upgrading it was working fine.

npm WARN install Couldn't install optional dependency: Unsupported
contactlistapp@1.0.0 D:\sudeep_dk\MEAN\node\Mean\contact_passport
└── nodemon@1.8.1

**Comment by remy** [comment]
Have you upgraded node and npm etc?

**Comment by parthmehta** [comment]
install them globally like   npm install <package_name> -g

**Comment by lokap** [comment]
I have fixed the issue like this:

Installed the latest version of npm: npm install -g npm@next
Added C:\Users\<UserName>\AppData\Roaming\npm to Windows' PATH. This must be placed before C:\Program Files\nodejs\.

**Comment by lokap** [comment]
I have fixed the issue like this:

Installed the latest version of npm: npm install -g npm@next
Added C:\Users\<UserName>\AppData\Roaming\npm to Windows' PATH. This must be placed before C:\Program Files\nodejs\.
