### ISSUE TITLE
Nodemone 'restart' Event to early ?

### ISSUE THREAD

**Issue by daslicht** [remy/nodemon#730]
Hello,

I've followed this tutorial here:

http://jpsierens.com/tutorial-livereload-nodemon-gulp/

Thats my Task:
```
gulp.task('default', function() {
    // listen for changes
    livereload.listen();
    // configure nodemon
    nodemon({
        // the script to run the app
        script: './bin/www',
        ext: 'js'
    }).on('restart', function(){
        // when the app has restarted, run livereload.
        gulp.src('app.js')
            .pipe(livereload());
            //.pipe(notify('Reloading page, please wait...'));
    })
})
```
The browser reloads as expected on file change, but the stylesheet is broken after automatic reload.
The console shows:

*GET http://localhost:3000/stylesheets/style.css net::ERR_CONNECTION_REFUSED*
If I manually refresh the browser its back again.

So I tried adding a short delay by using *setTimeout*
After that the Stylesheet is loaded as expected.

Is that the expected behavior or is the *restart* event firing to early ?
Is there a *restarted* event?

**Comment by remy** [comment]
Bind to start. Restart is to say the script is *going to* restart.

**Comment by daslicht** [comment]
Even tho I use the start event the callback is fired before the server is available, therefor live reload show a broken page.

**Comment by remy** [comment]
Of course, because how would nodemon know how long it takes for your server to do whatever it's going to do? Your script could be binding to a port, it could be blocking to do some work, it could be doing anything...

**Comment by daslicht** [comment]
hmm of course? , a callback is usually called *after* something has been called, no?

**Comment by remy** [comment]
Yes, but your script is forked, and so doesn't call back to nodemon in any
way.

**Comment by scottbert** [comment]
I'm having the same issue and I've seen a lot of horribly hacky workarounds involving settimeouts and looking for magic strings in stdout - I was wondering though, if on start it's possible to bind an event listener to the child process and then have that trigger my livereload? Something like:
server.js
```javascript
server.on('listening', function () {
        onListening(server);
        server.emit('plsreload', null);
    });
```
and then in my gulp script:
```javascript
.on('start', function(){
    var server = this;
    server.on('plsreload', function(){});
````
although this doesn't work. Is there a way to access/bind listeners to the child process on start?

**Comment by daslicht** [comment]
I meanwhile just use nodemon cli , and no Gulp , Grunt anymore.
When the server restarts socketio just emmits an event to refresh the browser :) done

**Comment by ramasilveyra** [comment]
Came here searching for the same, and found that #822 will save us 😃
