### ISSUE TITLE
Nodemon Default Behaviour

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [remy/nodemon#733]
I'm writing a tool that uses nodemon, and am trying to run the _start_ script in debug mode. Unfortunately, the only way I have found that works is to run `nodemon --debug`, and to warn the user to remove the _main_ attribute in their _package.json_ file. `nodemon --exec "npm start"` doesn't work, because there is no way to set the debug flag/port with `--exec`.

My question is: Why is _main_ the preferred default behaviour over executing the _start_ script? 

The _start_ script is meant to be an entry point into the users application, whereas the _main_ attribute declares the entry point for modules that wish to use this module as a dependency. Would it not make more sense to give priority to the _start_ script over the main attribute?

I believe the corresponding snippet of code can be found [here](https://github.com/remy/nodemon/blob/b292ae74b7c43407a52ce2d33d36ff218f4245ed/lib/config/exec.js#L21).

**Comment by ErisDS** [comment]
I'm running into the same issue. I have a module which both comes with a web server and can be used as a module in its own right. In the package.json I have:

```
"main": "lib",
  "scripts": {
    "start": "node server.js",
  },
```

If I'm running with nodemon, I'd need it to use my start script to start the server, but it tries to execute "lib".

For now, I'm working around this by specifying the following in a `nodemon.json`, however as @Ian-Stewart-Binks has pointed out I don't think this is always an option.

```
{
  "exec": "npm start"
}
```

Ideally, I believe that the default behaviour should fall through from:
- nodemon.json settings
- package.json 'start' script
- package.json 'main' (maybe?)
- attempt something obvious like `index.js`

I :heart: nodemon, and would be happy to have a go at providing a fix for this if there is consensus that the change to prefer `start` scripts over `main` is wanted?

**Comment by remy** [comment]
I guess what we're saying here is the priority (of finding the executable) is:

1. via nodemon.json/CLI args
2. via npm start method
3. via `node .` equivalent (which also has it's own cascade)

@ErisDS if you want to brave the code, I'd be happy for you to make this change and send the PR. I don't think it's a breaking change...but maybe I could be convinced otherwise..?

**Comment by ErisDS** [comment]
Sounds like we're on the same page, I think this counts as a bug fix :)

**Comment by slashhuang** [comment]
nodemon defaults to execute package.json main file .
came across the same problem

**Comment by ryanburnette** [comment]
Sometimes I would like to be able to tell nodemon to do something other than the entry point.

**Comment by remy** [comment]
@ryanburnette you can: `nodemon foo.js`

**Comment by ryanburnette** [comment]
I was getting behavior where that would call nodemon on the entry point and the script provided in the argument. That might not make any sense. I'll try to produce a simple test case.

**Comment by ryanburnette** [comment]
I tried to duplicate the behavior I was experiencing in a reduced test and I was unable to.
