### ISSUE TITLE
Cannot install nodemon

### ISSUE THREAD

**Issue by KevinBurton** [remy/nodemon#736]
I tried to do npm install -g nodemon and I get an error. When I try to run nodemon I get
C:\Windows\System32>node C:\Users\Kevin\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.js --dump
exception in nodemon killing node
Error: Cannot find module 'configstore'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Kevin\AppData\Roaming\npm\node_modules\nodemon\node_modules\update-notifier\index.js:4:19)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)

----------------------------------------------------------
If appropriate, please file an error with the output from:
$ C:\Program Files (x86)\nodejs\node.exe C:\Users\Kevin\AppData\Roaming\npm\node_modules\nodemon\bin\nodemon.js --dump
At http://github.com/remy/nodemon/issues/new
----------------------------------------------------------

Here are the versions that I am working with:

C:\Windows\System32>node --version
v5.1.0
C:\Windows\System32>npm --version
3.3.12

Ideas?

**Comment by remy** [comment]
- Have you tried node 4?
- When you tried a local version, did you `npm install` before you ran `node bin/nodemon.js`
- Have you tried other global modules?

Sounds like a node/npm issue here, rather than specific to nodemon (so will close for now).

**Comment by KevinBurton** [comment]
I have not tried node 4. Do you think it is a node version issue? Nodemon doesn't work with 5?

I haven't tried a local version.

I installed express-generator globally. It seems to work.

**Comment by remy** [comment]
Nodemon should work with node 5, but your problem is with npm and the
install process, rather than node or nodemon.

**Comment by KevinBurton** [comment]
Forgive the ignorance. But doesn't npm come with node? What can be done differently than 'npm install -g nodemon'?
