### ISSUE TITLE
Binding to SIGUSR2 in my app doesn't restart process correctly

### ISSUE THREAD

**Issue by jishi** [remy/nodemon#740]
In my app I'm utilizing the SIGUSR2 signal to signal my app from an external shell. However, when I bind a listener to this event, the nodemon restarting fails completely, leaving it hanging. I'm not sure why that is, since I would expect nodemon to have it's own listener for this (since it is used to restart, somehow).

For my specific user case, I don't actually need this signal if I run it through nodemon, but is there any good way to identify if my script is running through nodemon? That would allow me to skip the event binding in that case.

Seems like all the workarounds require you to exit the process yourself on a SIGUSR2 signal, but since my application isn't supposed to do that, I'm not able to use that. Why is it that a custom SIGUSR2 handler will block the restart of the process? Is it because you check if there are listeners on the process and bypass your own handler in that case?

**Comment by nathanredblur** [comment]
Something similar happen to me. Check this easy example.

I just have a express application and also I'm listening ```SIGUSR2``` to help me to identify errors when the app is running in remote server in production environment. 

```
// in app.js
var app= require('express')();
app.get('/', function(req, res){
  res.end('Hello World');
});
app.listen(3000);
console.log('running...');

process.on('SIGUSR2', function () {
    console.log('Taking heap snapshot, to control errors in remote server production');
});
```

On run with nodemon I see two logs:
```
running...
Taking heap snapshot, to control errors in remote server production
```

But on restar nodemon (saving or manually with 'rs') I only have one
```
Taking heap snapshot, to control errors in remote server production
```

My workaround was just put a local Environment var to disable that listener when I'm working in my local computer no matter if my NODE_ENV is 'development' or 'production'.

like this.
```
if (!process.env.noSnapshot) {
  process.on('SIGUSR2', function () {
    console.log('Taking heap snapshot, to control errors in remote server production');
  });
}
```

But I don't know if exist a better way. 
I hope this help someone.
