### ISSUE TITLE
Is it possible to pass the changed files array to the running script?

### ISSUE THREAD

**Issue by zeke** [remy/nodemon#742]
Hi @remy! Thanks for writing nodemon. I've been using it happily on the command line for a long time, but am just now trying it out programmatically. Given the following code:

``` js
nodemon({
  script: 'app.js',
  ext: 'js json'
});

nodemon.on('restart', function (files) {
  console.log('App restarted due to: ', files);
});
```

Is there a way for `app.js` to receive that `files` object?

If there was an event that fired before the restart occurred, then it would be possible to do something hacky like serialize the array into an environment variable so `app.js` could get a hold of it...

**Comment by zeke** [comment]
I don't need this anymore, nor can I even remember why I needed it! :)

**Comment by remy** [comment]
Ha! Always happy to close issues like that 👍
