### ISSUE TITLE
How to cleanly exit nodemon

### ISSUE THREAD

**Issue by edwardhorsford** [remy/nodemon#751]
We have a situation where we would like to completely quit node and nodemon.

We are using `process.exit(0)` to cleanly exit node. When this happens, we also want nodemon to quit. Instead it stays running and monitoring the directory.

How do we cleanly exit nodemon from within the app?

**Comment by NerdPad** [comment]
+1

Would like to know this as well.

**Comment by dundalek** [comment]
I was looking for this too. I found a workaround that might be helpful.

If you exit with `process.exit(2)` it will cause nodemon also to exit. Nodemon will print stack trace so you might also hook into `error` event to make it clean, e.g.:
```js
nodemon(...)
  .on('error', function(code) {
    if (code !== 2) {
      console.log('Exited with error code: ', code);
    }
  });
```

if you don't want to or can't modify the child process it should be possible to run it like `your_command || exit 2` to make it work.

More details: https://github.com/remy/nodemon/issues/627

**Comment by stevenvachon** [comment]
In tests, I cannot fully kill a nodemon process. `emit('quit')` only triggers the listener(s) and:

```js
nodemon(...).on('quit', function(){ this.reset() })
```
causes:
```
Assertion failed: (0), function uv_close, file ../deps/uv/src/unix/core.c, line 173.
```

**Comment by joeytwiddle** [comment]
There has been some debate about removing the quit behaviour on exit code 2.

So I would not recommend this technique, if you can find an alternative way.

**Comment by OoDeLally** [comment]
What is the state of this?
When `process.exit(2)` I get 
```
[nodemon] app crashed - waiting for file changes before starting...
```
then I have to `Ctrl+C` a second time to actually kill it.

1- Is it the expected behavior?
if yes, is a `app crashed` red message really appropriate? `Ctrl+C` is not a "crash" per se.
2- Any way to nicely quit everything in one key stroke (not twice) and without a scary crash message?
Thanks!

**Comment by remy** [comment]
@OoDeLally exit(2) is a crash code (from your script), so if you're catching the exit code inside your program and using exit 2, then nodemon is behaving exactly as it should. 

A clean exit code is 0, anything above is a bad exit code, and nodemon will catch it. 

Also, this issue was raised 3 years ago, so is unrelated to your original question.

**Comment by OoDeLally** [comment]
Thank you @remy. `process.exit(0)` indeed quit nicely the nodejs process, but not nodemon.
Is there a way to gracefully quit both `nodejs` and `nodemon` at once, given that I do capture `stdin`.
Thank you

**Comment by remy** [comment]
Quitting nodemon is done using ctrl-c (if you're capturing stdin - then
it's ctrl-c twice). nodemon isn't automatically exited (wasn't sure if
that's what you were asking, but it shouldn't exit as it's meant for
development).

**Comment by edwardhorsford** [comment]
@remy it's some years since I raised this (and I no longer work for that bit of gov that used it).

My use case was where the app's code has determined that nodemon should be quit. How should the app go about quitting nodemon? I think we had a situation where we asked the user a question in the terminal, and if they responded negatively, we then wanted to fully quit - at the time, we couldn't work out how to quit nodemon programatically.

**Comment by remy** [comment]
Darn, I didn't realise I was commenting on a 3 year old issue (I was doing it via email).

Bottom line: unless you require nodemon as a dep, nodemon will not exit. This is expected behaviour.

**Comment by BobFrankston** [comment]
It may be an old issue but one that is still relevant. I run a number of daemons using nodemon and they don't have a command line. When I run directly under node I can tell the program to exit itself but how do I do that with nodemon?

**Comment by joeytwiddle** [comment]
I think the neatest way to implement this might be to let callers _opt in_ to an exit code that would cause nodemon to quit. For example:

```
nodemon --kill-code 222 ...
```

Would cause nodemon to close if the child process exits with code 222.

**Comment by remy** [comment]
Firstly you're commenting on an issue from 4 years ago (and closed).

Secondly, you can use the OS to do this without having to add to nodemon:

```
nodemon || exit 222
```

**Comment by BobFrankston** [comment]
I know it's an old issue.  But it's not clear that it has been resolved. Note that I'm using Windows.

In the meantime I've taken a different approach that doesn't depend on nodemon.

**Comment by heymartinadams** [comment]
It seems strange to me that nodemon doesn’t provide a clean, programmatic way to exit itself.

**Comment by poikilos** [comment]
Ok, what's the "..." guys? I can't seem to get this done using:
```JavaScript
nodemon = require("nodemon");

  nodemon()
  .on('error', function(code) {
    if (code !== 99) {
      console.log('Exited with error code: ', code);
      process.exit(99)
    }
  });
```

I get:
```
/home/owner/git/node-ticket-manager/node_modules/nodemon/lib/nodemon.js:37
  if (settings.verbose) {
               ^

TypeError: Cannot read property 'verbose' of undefined
```

**Comment by molten-firescar96** [comment]
Using a separate file to import nodemon and call the main process addresses the original issue, how to exit nodemon cleanly.

```javascript
// run-main.mjs
import nodemon from 'nodemon';
nodemon(`<nodemon args> main.mjs ${process.argv.slice(2).join(' ')}`);
nodemon.on('exit', process.exit);
```

**Comment by molten-firescar96** [comment]
Starting the main script via a proxy seems to address the original question, how to make sure nodemon ends when the child process ends.

```javascript
// run-main.mjs
import nodemon from 'nodemon';

const mainArgs = process.argv.slice(2).join(' ');
nodemon(`<nodemon arguments> extensions/main.mjs ${mainArgs}`);
let ignoreExit = false;
nodemon.on('restart', () => {
  ignoreExit = true;
}).on('exit', () => {
  if(ignoreExit) {
    ignoreExit = false;
    return;
  };
  process.exit();
});
```

**Comment by mprast** [comment]
For anyone who stumbles on this thread in the future - there now appears to be an [--exitcrash flag](https://github.com/remy/nodemon/blob/main/faq.md#using-nodemon-with-forever) which will [cause nodemon to exit if the child process crashes](https://github.com/remy/nodemon/blob/5c0b472e9422b0b9fdabbc61bb9a14ebe50511fd/lib/monitor/run.js#L243).
