### ISSUE TITLE
Issues running nodemon from a module in a command-line tool on Windows

### ISSUE THREAD

**Issue by endquote** [remy/nodemon#761]
Given node 5.4.1, npm 3.3.12, latest Windows 10 x64, and this package:

package.json

```
{
  "version": "1.0.0",
  "name": "nodemon-test",
  "bin": {
    "nodemon-test": "start.js"
  },
  "dependencies": {
    "nodemon": "^1.8.1"
  }
}
```

start.js

```
#! /usr/bin/env node

var nodemon = require('nodemon');
var path = require('path');

console.log(path.join(__dirname, 'server.js'));
nodemon({
    script: path.join(__dirname, 'server.js')
});
```

server.js

```
console.log('hi from server.js');
```
- From the package directory, run `npm link`
- Run `cd \` to get out of the source directory
- Run `nodemon-test`
- See `hi from server.js`
- Delete linked folder from `C:\Program Files\nodejs\node_modules`
- Return to the source directory
- Run `npm install -g`
- Run `cd \` to get out of the source directory
- Run `nodemon-test`
- See the following output:

```
C:\>nodemon-test
C:\Program Files\nodejs\node_modules\nodemon-test\server.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'C:\"C:\Program'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

Somehow the current working directory of the console is being added to the beginning script path.

I can't tell if this is a nodemon bug or something I'm doing wrong, but I don't have this issue on Mac.

**Comment by endquote** [comment]
Could be related to this.
https://github.com/nodejs/node-v0.x-archive/issues/25895

**Comment by mAmged** [comment]
+1
