### ISSUE TITLE
Possible to watch package.json scripts with nodemon?

### ISSUE THREAD

**Issue by corysimmons** [remy/nodemon#768]
I couldn't find anything about it in the docs or faq, but it'd be awfully cool to do something like:

```
"scripts": {
  "start": "nodemon --packagescript runeverything",
  "runeverything": "npm-run-all --parallel server:* styles:* scripts:*"
}
```

Did I overlook something or is this not in Nodemon?

If it's not in nodemon, is it not for a reason or can it be added as a feature?

**Comment by remy** [comment]
This isn't a feature of nodemon, if I'm reading you correctly and you want nodemon to read the `package.script` executable. nodemon will look for the `package.script.start` but nothing else - it's really just looking for a way to start your script, that's all.

**Comment by corysimmons** [comment]
No, I'm sorry my example wasn't clear at all.

I think what I was asking was can Nodemon execute package.json scripts?

```js
"scripts": {
  "start": "nodemon *.html 'npm run saySomething'",
  "saySomething": "echo 'You edited html'"
}
```
