### ISSUE TITLE
Should support unicode extensions

### ISSUE THREAD

**Issue by alice0meta** [remy/nodemon#769]
I tried `nodemon -e ζ ./server.js "$@"`; https://github.com/remy/nodemon/blob/master/lib/config/exec.js#L158 threw an error (currently https://github.com/remy/nodemon/blob/3480f37aab325b6ae4e17058078742d586724860/lib/config/exec.js#L158 ); I changed that line to `extension = extension.match(/[\wζ]+/g).join(',');` and it works fine now. Please change the regex to be something more permissive, like `/[^,.\s]+/g`.

**Comment by remy** [comment]
Can you send a PR with a test passing. Thanks.

**Comment by alice0meta** [comment]
I haven't interacted with github much and don't know how to do that. Please change the regex from `/[\wζ]+/g` to `/[^,.\s]+/g` or something else that’s blacklist-based instead of whitelist-based.

**Comment by alice0meta** [comment]
@remy explained that he WONTFIX

**Comment by alice0meta** [comment]
It's unclear if this should be kept open. I apologize to anyone else who has this issue; I was unable to even get clarification if the maintainers of nodemon care about it.

**Comment by remy** [comment]
<img width="794" alt="screen shot 2016-02-25 at 09 59 13" src="https://cloud.githubusercontent.com/assets/13700/13316128/73899554-dba6-11e5-948e-201b7a4c61c3.png">

**Comment by alice0meta** [comment]
Thank you. I'll check back later to see if this seven-character fix has been implemented.

**Comment by remy** [comment]
https://github.com/remy/nodemon/issues/769#issuecomment-178439145

**Comment by deckar01** [comment]
Fixed in https://github.com/remy/nodemon/pull/789.

Thanks @remy for working on the test.

Thanks @alice0meta for finding a solution to this issue.
