### ISSUE TITLE
how do I immediately restart server on crash?

### ISSUE THREAD

**Issue by mpint** [remy/nodemon#771]
I'm testing nodemon in a production environment, where my aim is to immediately restart the server on crash.  

However, when I simulate a server crash with `kill -9 <pid>`, nodemon prints this message, `[nodemon] app crashed - waiting for file changes before starting...`

Is it possible to force nodemon to restart without waiting?  Couldn't find anything in the docs or sample configs.  Thanks!

**Comment by remy** [comment]
It's not possible, nodemon is designed for development process, rather than keeping your process from crashing. If you need this, I'd recommend looking at forever (node), or upstart (unix tool) - though you probably want to look at why you're crashing rather than hiding it. Good luck!

**Comment by mpint** [comment]
@remy, thanks for the fast reply!  Love the tool by the way (for development :-)
