### ISSUE TITLE
Prefer global: should be installed with -g

### ISSUE THREAD

**Issue by woodyrew** [remy/nodemon#772]
I'm not sure if this is a dupe, I had a search but didn't see it.

Nodemon's currently set to `"preferGlobal": "true"` in `package.json` and produces:
```
prefer global nodemon@1.8.1 should be installed with -g
```

A better practice *at the moment* is to install in your devDependancies and run on a per project basis either via node scripts or directly via `./node_modules/.bin/nodemon`.

I'm happy to provide a PR for the change including documentation if this is something you think is worthwhile.

**Comment by remy** [comment]
I don't think it should have a doc change, but I can remove the `preferGlobal`. Reasoning: most devs will just want a cli util to do the job.

More advanced devs are using this as a devDep and in their `scripts.start` their using `nodemon lib/app ...etc`.

So removing the flag will remove the warning.

**Comment by woodyrew** [comment]
I concur; sounds good.
