### ISSUE TITLE
random 404 errors when using nodemon

### ISSUE THREAD

**Issue by selfagency** [remy/nodemon#774]
for some reason when i use nodemon for local development (`nodemon bin/www -e js,hbs,scss` specifically), vs `npm start`, i get random, inconsistent 404 errors on the various assets in my node/express project's public folder on my local machine when loading my page in-browser. every time i refresh the page, an entirely different set of icons/fonts/scripts throw a 404. this doesn't happen if i just use `npm start` and it only happens on my desktop computer (mac pro). it works fine on my laptop (macbook pro). any idea what's causing this and how to resolve?

**Comment by remy** [comment]
What's the contents of you npm start?

**Comment by selfagency** [comment]
```{
  "name": "nylon-web",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "basic-auth": "^1.0.3",
    "body-parser": "~1.13.2",
    "cookie-parser": "~1.3.5",
    "datejs": "0.0.2",
    "debug": "~2.2.0",
    "dotenv": "^1.2.0",
    "express": "~4.13.1",
    "hbs": "~3.1.0",
    "morgan": "~1.6.1",
    "node-sass-middleware": "0.8.0",
    "restler": "^3.4.0",
    "serve-favicon": "^2.3.0"
  }
}```

**Comment by selfagency** [comment]
oh looks like if i don't specify a path it works just fine

**Comment by selfagency** [comment]
except now for some reason node restarts every time i refresh my page

**Comment by selfagency** [comment]
i take it back, it's still not working

**Comment by remy** [comment]
Unless you explain what is not working, how is anyone supposed to be able to help you?

**Comment by selfagency** [comment]
as i explained before, i get random 404 errors for no explicable reason

![screenshot 2016-02-07 16 56 16](https://cloud.githubusercontent.com/assets/2541728/12875581/fbc41a96-cdbb-11e5-8e09-d17b428d8baa.png)

and nodemon restarts every time it loads a page, even though no files have changed

![screenshot 2016-02-07 16 59 25](https://cloud.githubusercontent.com/assets/2541728/12875589/2da1f128-cdbc-11e5-8221-aaaa6d939262.png)

**Comment by remy** [comment]
Run with `--verbose` and disable your own logging, so we can see what's causing it to restart.

The 404s, I'm guessing are because nodemon is restarting your process.

**Comment by selfagency** [comment]
I discovered the issue. I had been using `nodemon bin/www -e js,hbs,scss,css` for some reason and the css files were regenerating in the background constantly while I was making changes. After remove `css` from monitoring everything runs fine.
