### ISSUE TITLE
Ability to set polling interval

### ISSUE THREAD

**Issue by benmvp** [remy/nodemon#775]
Loving nodemon! The `--legacy-watch` flag was a lifesaver for running in my Docker environment.

I'd like the ability to control the polling interval as right now it feels too slow. Looking at the [watch code](https://github.com/remy/nodemon/blob/f5d1a04cc80f1bc963c20627177e545be42aeee7/lib/monitor/watch.js#L52-L56) it uses `chokidar.watch()` and that accepts and optional [`polling` property](https://github.com/paulmillr/chokidar/tree/94edfdd2785a7fedd2f355430b586e7814f344b9#performance).

Could `--legacy-watch` optionally take a numeric value that when specified not only activates the polling but overrides the default interval?

Thanks!

**Comment by remy** [comment]
I could, via a PR.

**Comment by benmvp** [comment]
Cool! Wasn't sure cuz the guidelines say new command line options were discouraged.

**Comment by krzkaczor** [comment]
In case your looking for an answer. Just use: `--polling-interval`.
