### ISSUE TITLE
Nodemon Issue

### ISSUE THREAD

**Issue by calvinphung** [remy/nodemon#781]
Hi, i am new to Node.JS and Nodemon. I've been following https://blog.udemy.com/node-js-tutorial/#7_3 tutorials for Node.JS to get a better understand of it. I am running into an issue though when i try to start nodemon.

Here's my error:

![image](https://cloud.githubusercontent.com/assets/17181809/12983608/f46b6782-d0b7-11e5-856c-015b4392209a.png)

Thank you!

**Comment by hstonge** [comment]
This doesn't seem related to nodemon... Does the error occurs if you just run `node`? If yes then, the error is in your code, not nodemon.

**Comment by remy** [comment]
Indeed what @hstonge said. I'll close this issue. @calvinphung you're probably better off confirming it's actually node (as we suspect) and getting in touch with something like the StackOverflow community. Good luck!
