### ISSUE TITLE
An idea about better ignore

### ISSUE THREAD

**Issue by iliakan** [remy/nodemon#782]
I have both client-side and server-side `.js`-files in my project.
Some `.js` used at both sides.

If I use `watch` to track all js-files, my node is reloaded when I edit client-side stuff. 
I can explicitly list client-only things in `ignore`, that somewhat helps, but requires maintenance.

I have another suggestion.

What if nodemon checked `require._cache` on modified js-files, like.. To see if they are really used by the server. And only reload if that's so? No need to explicitly list client-only stuff.

Current nodemon does not allow to make ignore a function, but if it could, then implementation would be straightforward.

**Comment by remy** [comment]
That would require running inside of your process which nodemon doesn't do. There is a similar tool that does do this though, but if forget what it's called. If you search for nodemon on npm they added nodemon as a keyword to their app.
