### ISSUE TITLE
nodemon crash with no reason

### ISSUE THREAD

**Issue by emps** [remy/nodemon#783]
my app crashes with no any reason since nodejs 4.2.6 (including)

it never heppen befor till 4.2.4 (including)

im now using 4.3.0 still problem happen i dont know if its nodemon or nodejs 
but the problem happen with new versions of nodejs

**Comment by remy** [comment]
No stack trace?

**Comment by emps** [comment]
no

**Comment by remy** [comment]
So...you run nodemon, and there's no output. How are you sure it's crashing? Are you reading the exit signal?

**Comment by joshmanders** [comment]
This is happening to me all of the sudden. Literally no error in the app or nothing, just `app crashed - waiting for file changes before starting...`

![](https://i.imgur.com/eA3ltde.png)

**Node:** v6.9.1
**npm:** v3.10.8
**Nodemon:** v1.9.2
**Yarn:** v0.16.1
**macOS:** 10.12 (16A323)
