### ISSUE TITLE
Dipak Chavda

### ISSUE THREAD

**Issue by Dipak2912** [remy/nodemon#784]
root@wk11:/var/www/html/pro# node /usr/bin/nodemon -v --dump
exception in nodemon killing node
Error: Cannot find module 'configstore'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/nodemon/node_modules/update-notifier/index.js:4:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

---

If appropriate, please file an error with the output from:
$ node /usr/bin/nodemon -v --dump

**Comment by remy** [comment]
So you're missing a key module from the install.

Can you paste the output of `node -v` and `npm -v`.

**Comment by Dipak2912** [comment]
Hello Remy,

Regret for late reply.

Please find attached screen-shot of node and npm version.

I am using ubuntu 14.04 LTS. It's not related to ubuntu but still I give you for your information.

Thank you,
Dipak
--------------------------------------------
On Wed, 17/2/16, Remy Sharp <notifications@github.com> wrote:

 Subject: Re: [nodemon] Dipak Chavda (#784)
 To: "remy/nodemon" <nodemon@noreply.github.com>
 Cc: "Dipak2912" <dips_mca09@yahoo.com>
 Date: Wednesday, 17 February, 2016, 6:51 PM
 
 So you're missing a key
 module from the install.
 
 Can you paste the output of node -v and
 npm -v.
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by Dipak2912** [comment]
Hello Remy

I forgot to attach images.

Node version : v0.10.37
NPM version : v3.3.4


Thank you,
Dipak


--------------------------------------------
On Wed, 17/2/16, Remy Sharp <notifications@github.com> wrote:

 Subject: Re: [nodemon] Dipak Chavda (#784)
 To: "remy/nodemon" <nodemon@noreply.github.com>
 Cc: "Dipak2912" <dips_mca09@yahoo.com>
 Date: Wednesday, 17 February, 2016, 6:51 PM
 
 So you're missing a key
 module from the install.
 
 Can you paste the output of node -v and
 npm -v.
 
 —
 Reply to this email directly or view
 it on GitHub.
