### ISSUE TITLE
The --ext param does not work properly.

### ISSUE THREAD

**Issue by karloluis** [remy/nodemon#786]
![image](https://cloud.githubusercontent.com/assets/4258614/13204171/889f0686-d89f-11e5-9ee7-ead8524acc25.png)

The command shown is `nodemon ./bin/www -e css,ejs,js,json`, while the app runs correctly it would only restart for the first param on the list. The rest of the file types are show as being interpreted as execution parameters. I've also tried `nodemon --exec ./bin/www -e css,ejs,js,json` with the same result.

**Comment by tleb** [comment]
Have you tried `nodemon -e css,ejs,js,json ./bin/www`? I haven't tried, but `nodemon -h` says `Usage: nodemon [options] [script.js] [args]`

**Comment by karloluis** [comment]
I just have, it does the same. See image.
![image](https://cloud.githubusercontent.com/assets/4258614/13204500/19341666-d8a8-11e5-93d7-6941a6899f4f.png)

**Comment by tleb** [comment]
I tried your first command, and it gives me:

```
# in a random folder or a folder with a package.json without a main property
> nodemon ./bin/www -e css,ejs,js,json
  Usage: nodemon [nodemon options] [script.js] [args]

  See "nodemon --help" for more.

# in a folder with a package.json with a main property
> nodemon ./bin/www -e css,ejs,js,json
[nodemon] 1.9.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./bin/www src/index.js`
```

There is definitely an undocumented behaviour somewhere.

**Comment by karloluis** [comment]
I've identified the source of the problem. I'm using a terminal emulator package for Atom and it appears to be the cause of the problem. Running these commands from the Windows shell produce the desired results.

Therefore, I'm closing this issue due to the above reasons. Another ticket will be filed under the appropriate repository. Thanks for the help @tleb
