### ISSUE TITLE
Still does not support unicode file extensions

### ISSUE THREAD

**Issue by alice0meta** [remy/nodemon#792]
Re https://github.com/remy/nodemon/issues/769#issuecomment-178439145 , an appropriate pull request has already been created. The maintainers of nodemon must either state that they are unwilling to support non-english languages, or leave this open.

I tried `nodemon -e ζ ./server.ζ "$@"`; https://github.com/remy/nodemon/blob/master/lib/config/exec.js#L158 threw an error (currently https://github.com/remy/nodemon/blob/3480f37aab325b6ae4e17058078742d586724860/lib/config/exec.js#L158 ); I changed that line to `extension = extension.match(/[^,.\s]+/g).join(',');` and it works fine now. Please change the regex to be something blacklist-based like this.

**Comment by remy** [comment]
Reported abuse.
