### ISSUE TITLE
How to start node after build stage

### ISSUE THREAD

**Issue by Diokuz** [remy/nodemon#797]
Hi there!

I have two tasks: 1) build server (with webpack) 2) launch server (with nodemon).
They have to be running in parallel. But for the first few seconds there is no build file (which nodemon is launching) and I have an error:

``` bash
[nodemon] starting `node ./build/server.js index.js`
module.js:341
    throw err;
    ^

Error: Cannot find module '/Users/dm.kuznetsov/square/build/server.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
[nodemon] app crashed - waiting for file changes before starting...
```

Is there a way to tell nodemon to launch server for the first time only after the server `server.js` file will appear on filesystem?
Like:
1) Webpack starting to build `server.js`
2) [in parallel] nodemon start to look for for `server.js`, but no file exists -> waiting for file
3) Webpack completes to build `server.js`
4) nodemon get _dirChange_ event and starts `node server.js` for the first time.

**Comment by tleb** [comment]
What about this?

```
nodemon -x "webpack-command with arguments && node" -w "webpack-input-to-watch" build/server.js
```

Basically, you watch for changes in the input folder and when this happens, webpack does its things then node is executed. I used to use this to cd into a dir, to change the cwd.

**Comment by Diokuz** [comment]
You mean launch webpack each time files changed? No, its not good. Webpack `--watch` option much more efficient.

**Comment by tleb** [comment]
Gulp then?

**Comment by andreasi** [comment]
Hi. I saw above that you wrote the following
nodemon \
    -x "webpack-command with arguments && node" \
    -w "webpack-input-to-watch" \
    build/server.js

where did you write this. In your command line or in a file?
Thank you!

**Comment by tleb** [comment]
This is a command. You can write it directly in your terminal or you can put it in a script file. You can also put it in a npm script.
