### ISSUE TITLE
When I run nodemon it tries running the files in the parent folder

### ISSUE THREAD

**Issue by harksha** [remy/nodemon#800]
This is the second time I want to try nodemon on different project and it behaves the same for both. 
I'm running win10 x64 nodemon 1.9.1 and node v5.4.1
Basically, running the server file with the node command in that directory runs fine, but doing it with nodemon throws an error, because it looks like it's running from its parent dir. 
![image](https://cloud.githubusercontent.com/assets/1499693/13463649/8fe65a3e-e08d-11e5-8c4a-245c7b81aaa1.png)

**Comment by remy** [comment]
This is odd, it's resolving the `server.js` in the parent.

Can you paste your `package.json` as a starting point for debugging?

**Comment by harksha** [comment]
@remy sorry for the delay. currently package.json is just a simple starting point for the project, anyway here it is: 

`{
  "name": "mean-stuff",
  "version": "1.0.0",
  "description": "training",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "me",
  "license": "ISC",
  "dependencies": {
    "express": "^4.13.4",
    "jade": "^1.11.0"
  }
}`

**Comment by tleb** [comment]
And it is located in `C:\Projects\mean-stuff`, not `C:\Projects`? Is there any `package.json` in `C:\Projects`?

**Comment by harksha** [comment]
@tleb no, C:\Projects doesn't have any files floating around by themselves.
