### ISSUE TITLE
False positive on Windows 7 x64

### ISSUE THREAD

**Issue by andig** [remy/nodemon#803]
I'm using grunt-nodemon@0.4.1 which relies on nodemon@1.9.1 as comes bundled with node-red. nodemon keeps restarting with false positive `[nodemon] nodes\core\storage\50-file.js` which definitely isn't changing. 
Update: excluding that file/folder triggers other false positives. I'm pretty certain that its not the files that get updated.

**Comment by halt-hammerzeit** [comment]
I'm having false positives on Windows too, but that's up to the backing library which is called `chokidar` and they aren't cooperative

**Comment by andig** [comment]
> I'm having false positives on Windows too, but that's up to the backing library which is called chokidar and they aren't cooperative

Happy to ask there, too- is there already an open issue?

**Comment by halt-hammerzeit** [comment]
Nope, I opened an issue a while ago, and it was immediately closed saying something like "Windows support is not a priority".
So i guess there'll be no solution.

**Comment by andig** [comment]
I've tried instrumenting the code. Watching 2 dirs works fine with chokidar but triggers changes when executed by nodemon inside node-red. I'm suspecting that chokidar may not be the culprit in my case but I'm failing to find the differences.

**Comment by andig** [comment]
It seems the false positives get triggered by ctime, for example below:

      atime: Tue Feb 16 2016 15:57:05 GMT+0100 (Mitteleuropäische Zeit),
      mtime: Tue Feb 16 2016 15:57:05 GMT+0100 (Mitteleuropäische Zeit),
      ctime: Sun Mar 13 2016 22:11:21 GMT+0100 (Mitteleuropäische Zeit),

Obviously ctime can't be after mtime. It remains unclear why this happens inside node-red but not when running chokidar natively.

**Comment by halt-hammerzeit** [comment]
(in my case webpack somehow triggered false positives. it was something like `atime`)

**Comment by andig** [comment]
Are you able to produce this with a script just using chokidar, not nodemon? I ain't- running chokidar itself works fine sofar...

**Comment by halt-hammerzeit** [comment]
Nah, i'm not being so persuasive with that issue, it happens only when i
run it all for the first time.
