### ISSUE TITLE
Issue with running Nodemon from multiple users in Linux

### ISSUE THREAD

**Issue by roman-io** [remy/nodemon#804]
I run into an issue when running multiple services with Nodemon from different users.
Example from my code, that executed via `child_process.spawn`:

```
var services = [
        {
          name: 'proxy',
          cmd: 'nodemon',
          args: ['--legacy-watch', '--watch', 'server', './server/bin/proxy.js'],
          options: { cwd: '/opt/software/', silent: false, stdio: 'inherit', uid: 0 }
        },
        {
          name: 'server',
          cmd: 'nodemon',
          args: ['--legacy-watch', '--watch', 'server', './server/bin/server.js'],
          options: { cwd: '/opt/software/', silent: false, stdio: 'inherit', uid: 1000 }
        }
];
```

I'm getting the following error:
`Error: EACCES: permission denied, open '/home/vagrant/.config/configstore/update-notifier-nodemon.json'`

It seems like Nodemon assumes that only one user can run services with Nodemon, and it defines strict permissions on `update-notifier-nodemon.json` and it cannot be read by other users.

**Comment by remy** [comment]
That's right. Maybe stagger the start?
