### ISSUE TITLE
Ext option doesn't work for "multi-segment" extensions

### ISSUE THREAD

**Issue by mostr** [remy/nodemon#810]
Hey,

I'd like to use nodemon to re-run my tests on **test files** change only. The problem is I use `[foo].test.ts` naming schema for my test files (and I keep them right next to my source files) and nodemon seems to be treating `--ext test.ts` option as if it was plain `.ts` (it reruns command every time _any_ `ts` file changes).
This is my full line from `package.json`

`nodemon --watch lib/ --ext test.ts --exec npm run test`

Any tips on this or is this feature not supported yet?

**Comment by remy** [comment]
Hmm, I see what you're trying to do. I suspect it's working out the extension based on `test.ts` and making it `ts` as you suggest. Could be fixed with a PR, I think you need to look in `lib/config/exec.js` and if you can include a separate test to make sure it does what you expect?

Thanks!
