### ISSUE TITLE
on v 1.9.1 stoped working -w in combination with -x

### ISSUE THREAD

**Issue by syzer** [remy/nodemon#811]
tested on mac
in bash
and in fish

**Comment by remy** [comment]
I can't replicate with the detailed you included. Can you provide actual details or how to replicate?

**Comment by syzer** [comment]
nodemon -x 'cat README.md | python --version' -w ./
if you change any file in ./ .... the script -x will not be re-run

**Comment by syzer** [comment]
BTW thanks for making nodemon, use it for years, this is first real bug i found in it.
