### ISSUE TITLE
[Question] Watch the changes of a uniq js file

### ISSUE THREAD

**Issue by flashios09** [remy/nodemon#812]
Hi,
Thanks for this awesome tool, before i have to restart the node server manually 
I have a question, i want to watch only a uniq file **server.js**, i want to restart the node server only if i update this file
What option i have to use ? --ignore or --watch ?
Thanks

**Comment by tleb** [comment]
```fish
nodemon -x "echo foo" -w foo
```

Works for me. `-w` is short for `--watch`.
