### ISSUE TITLE
nodemon keeps looking for index.js file even if i specified otherwise, thus throwing error.

### ISSUE THREAD

**Issue by maotora** [remy/nodemon#820]
Hello, 
when i run `nodemon ./build`
I get **Error:** Cannot find module `/path/to/project/home/index.js` while i've explicitly specified that it should check in the build/ directory, this is persisting even when i write `nodemon ./build/index.js`.

In the `build/index.js` i only have a `console.log('hello world');` string.

Note: this error is not in `nodemon: 1.8.1`. 

Am I missing something?

**Comment by tleb** [comment]
I just can't reproduce your problem:

```bash
mkdir build
echo 'console.log("Hello World")' > build/index.js
nodemon ./build
```

Which starts nodemon:

```
[nodemon] 1.9.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./build`
Hello World
[nodemon] clean exit - waiting for changes before restart
```

It seems you didn't give us all the information. Is there anything special you didn't mention?

**Comment by maotora** [comment]
yeah, i'm sorry but i'm just stupid sometimes.
I just placed nodemon in scripts and after multiple attempts of installing and unistalling nodemon
I ended up running `nodemon` instead of `npm run nodemon` ..
Thank you for taking your time tho, you opened my eyes. hehehe

**Comment by nullivex** [comment]
I know it might not be relevant but I had this issue.

The problem was that I copied a config file off of stackoverflow like follows:

```package.json
"scripts": {
    "dev": "nodemon --config nodemon.json"
  },
```

```nodemon.json
{
    "verbose": true,
    "execMap": {
        "js": "node --harmony"
    },
    "script": "server.js",
    "ext": "js mustache"
}
```

The issue is that the package.json really needs to be

```package.json
"scripts": {
    "dev": "nodemon --config nodemon.json server.js"
  },
```

**Comment by hseritt** [comment]
FWIW, I ran into this same error but added the following as a script in packages.json:

`"start": "nodemon -w server server/server.js"`

After this, I could run: `npm start` successfully.
