### ISSUE TITLE
Nodemon stratup fails

### ISSUE THREAD

**Issue by ghaddon1** [remy/nodemon#828]
Started getting Nodemon startup failure. Not sure what changed to cause this error. Have tried reinstall of Node, NPM and NPM install and different versions of Nodemon.

Thanks,
Gary

**I'm running the following environment:**
Windows 10
Node 4.4.3
NPM 3.8..8
Nodemon 1.9.2  <---- The following is installed a global

**Here is npm-debug.log**

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Users\Gary\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.8.8
3 info using node@v4.4.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle Base@0.1.0~predev: Base@0.1.0
6 silly lifecycle Base@0.1.0~predev: no script for predev, continuing
7 info lifecycle Base@0.1.0~dev: Base@0.1.0
8 verbose lifecycle Base@0.1.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle Base@0.1.0~dev: PATH: C:\Users\Gary\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Gary\WebstormProjects\ReactHM\node_modules.bin;C:\Program Files\nodejs;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files\nodejs\;C:\Program Files\MongoDB\Server\3.2\bin\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile64\;C:\Program Files\Git\bin;C:\Program Files (x86)\Notepad++\;C:\Users\Gary\AppData\Local.meteor\;C:\Users\Gary\AppData\Roaming\npm
10 verbose lifecycle Base@0.1.0~dev: CWD: C:\Users\Gary\WebstormProjects\ReactHM
11 silly lifecycle Base@0.1.0~dev: Args: [ '/d /s /c', 'nodemon server.js' ]
12 silly lifecycle Base@0.1.0~dev: Returned: code: 1  signal: null
13 info lifecycle Base@0.1.0~dev: Failed to exec dev script
14 verbose stack Error: Base@0.1.0 dev: `nodemon server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Gary\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:244:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Gary\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid Base@0.1.0
16 verbose cwd C:\Users\Gary\WebstormProjects\ReactHM
17 error Windows_NT 10.0.10586
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Users\Gary\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "dev"
19 error node v4.4.3
20 error npm  v3.8.8
21 error code ELIFECYCLE
22 error Base@0.1.0 dev: `nodemon server.js`
22 error Exit status 1
23 error Failed at the Base@0.1.0 dev script 'nodemon server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Base package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     nodemon server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Base
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Base
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Petr73ru** [comment]
The same problem!

**Comment by ghaddon** [comment]
Problem solved......
