### ISSUE TITLE
Infinite restarting

### ISSUE THREAD

**Issue by GenaANTGOfficial** [remy/nodemon#829]
Hi, Guys! After upgrade nodemon and node i getting next problem:
**Node.js version: 6.0.0**

`npm start

> Appname@1.3.0 start /home/baddad/Projects/Appname
> NODE_ENV=development nodemon app.js -e js,marko,json --trace-sync-io --verbose

[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] ignoring: .git .nyc_output .sass-cache bower_components coverage /home/baddad/Projects/Appname/node_modules/**/*
[nodemon] watching: *.*
[nodemon] watching extensions: js,marko,json
[nodemon] starting `node app.js --trace-sync-io`
[nodemon] child pid: 20375
[nodemon] watching 2,134 files
[nodemon] files triggering change check: application/frontend/home/home.marko.js
[nodemon] matched rule: **/*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] application/frontend/home/home.marko.js

[nodemon] starting `node app.js --trace-sync-io`
[nodemon] child pid: 20383
[nodemon] files triggering change check: application/frontend/home/home.marko.js
[nodemon] matched rule: **/*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] application/frontend/home/home.marko.js

[nodemon] starting `node app.js --trace-sync-io`
[nodemon] child pid: 20391
[nodemon] files triggering change check: application/frontend/home/home.marko.js
[nodemon] matched rule: **/*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] application/frontend/home/home.marko.js

[nodemon] starting `node app.js --trace-sync-io`
[nodemon] child pid: 20399
[nodemon] files triggering change check: application/frontend/home/home.marko.js
[nodemon] matched rule: **/*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] application/frontend/home/home.marko.js
`

**Comment by RafaPegorari** [comment]
sudo npm install -g nodemon

Work for me.

**Comment by GenaANTGOfficial** [comment]
need to add `"ignore": ["*.marko.js"]` to **nodemon.js**

**Comment by dionisoros** [comment]
My solution: add nodemonConfig in package.json file in order to stop infinite loop. In package.json:
"nodemonConfig": { "ext": "js", "ignore": ["*.test.ts", "db/*"], "delay": "2" }, "scripts": { "start": "nodemon" }
