### ISSUE TITLE
Add "listening" or "ready" event

### ISSUE THREAD

**Issue by pensierinmusica** [remy/nodemon#832]
Hi @remy!

Would you be so kind to add the `listening` event to [nodemon states](https://github.com/remy/nodemon/blob/master/doc/events.md)?

You can get it directly from Node: https://nodejs.org/api/net.html#net_event_listening

This is needed for example when using [gulp-nodemon](https://github.com/JacksonGariety/gulp-nodemon), since starting the Node server can be part of multiple tasks and you don't want to run something like [browsersync](https://github.com/BrowserSync/browser-sync) until the server is actually listening.

I tried using the `start` event, but when the browser loads the server is not listening yet, so you get a blank page and need to manually reload, which is annoying.

Thanks in advance for adding this!

Cheers

**Comment by remy** [comment]
Urm...but nodemon doesn't listen. It doesn't even use the `net` module.

**Comment by pensierinmusica** [comment]
Mmm, I see. Is there a way then for the app code to interact with Nodemon and decide when to trigger some `ready` event that could be integrated in a Gulp task?

**Comment by gggauravgandhi** [comment]
Share your `gulp file` or integration of `gulp-nodemon`

**Comment by pensierinmusica** [comment]
Hi,

This is the way I wish it could work:

```js
// Start server
gulp.task('server', function (cb) {
  $.nodemon({
    script: serverPath,
    watch: serverPath
  })
  .on('ready', cb);
});
```

But for now I'm stuck with a less elegant solution:

```js
// Start server
gulp.task('server', function (cb) {
  $.nodemon({
    script: serverPath,
    watch: serverPath
  })
  .on('start', function () {
    setTimeout(cb, 500);
  });
});
```

**Comment by vlkosinov** [comment]
@pensierinmusica you can parse stdout and trigger event (call callback) on specific message:

```js
gulp.task('server', function (cb) {
    const readyMessage = 'server started';

    nodemon({
        script: serverPath,
        watch: serverPath,
        stdout: false
    })
    .on('stdout', function (stdout) {
        console.log('server stdout:', stdout.toString());

        const isReady = stdout.toString().includes(readyMessage);
        if (!isReady) { return; }
        cb();
    });    
});
```

**Comment by vlkosinov** [comment]
@remy close? :)

**Comment by sandro-pasquali** [comment]
@pensierinmusica for my case I found it useful to simply start browsersync from the server itself. So, `child_process.exec('gulp <post-start-task-chain-head>')` at the point when you know your server is ready (say, `listen`).

**Comment by RichardsonWTR** [comment]
I am having a similar issue. I reported in [Browsersync repo](https://github.com/BrowserSync/browser-sync/issues/1219).
Can anyone help me on this?

**Comment by pensierinmusica** [comment]
Thanks @vlkosinov and @sandro-pasquali for your suggestions! I ended up adopting a modified version of what @vlkosinov suggests. @sandro-pasquali method also looks nice, but decided to keep the logic of Gulp inside `gulpfile.js`, and not split with the main server script.

So this is the solution I adopted:

```js
gulp.task('server', function (cb) {
  $.nodemon({
    script: serverPath,
    watch: serverPath,
    stdout: false
  })
  .on('stdout', function (mess) {
    console.log(mess.toString());
    cb();
  })
  .on('stderr', function (err) {
    console.err(err.toString());
  });
});
```

I guess we can close this issue now, thanks everyone!
