### ISSUE TITLE
New to Nodemon, I feel like I'm missing something...

### ISSUE THREAD

**Issue by kgraves** [remy/nodemon#838]
Hey guys, I have scoured the internet and haven't found a setup that's satisfying. I feel like I'm missing something, so maybe some of you can enlighten me.

I'm building a web app and want to monitor all of my code for changes (seems like the usual use case with nodemon), but I also want to monitor my `.scss` files.

I was under the impression (or at least assumed) that I could run one nodemon process, and have all of this done. I have something working, but am forced to run two nodemon processes. The first process monitors `.scss` files and compiles on any changes. The other process monitors all code files and `.css` files, and will restart the web app. The following is my current setup:

* package.json:

```json
...
"scripts": {
  "build-css": "gulp css",
  "start": "nodemon bin/www",
  "watch-scss": "nodemon -e scss -x \"npm run build-css\""
},
...
```

* nodemon.json

```json
{
  "env": {
    "NODE_ENV": "development",
    "PORT": 3030
  },
  "ext": "js json jade css html",
  "verbose": true
}
```

**Is there any way I can consolidate this down into a single nodemon process? Advice? Comments?**

**Comment by urugator** [comment]
If I understand right, you want to monitor for all files, restart the app when any of them changes and additionaly run gulp task if one of the changed files was .scss file.

One option would be to listen for "restart" event, check for presence of ".scss" file and run gulp task programatically. In that case you have to use nodemon as requireable module:
```javascript
const nodemon = require('nodemon');
nodemon(options).on('restart', function (files) {
  // check files passed in param
  // execute whatever necessary
});
```
Or you can check [gulp-nodemon](https://github.com/JacksonGariety/gulp-nodemon)

**Comment by kgraves** [comment]
Thanks for the quick reply @urugator. I'm definitely going to play with the methods that you talked about, and then comment again in the next day or two. I previously saw gulp-nodemon, but thought that was a little too much for such a simple use case that I have.

For now, if anyone is interested, I setup a simple shell script that runs a gulp task when `$FILENAME` has an `.scss` extension. I then wire up the restart event to run my script:

```bash
{
  "env": {
    "NODE_ENV": "development",
    "PORT": 3030
  },
  "events": {
    "restart": "./scripts/compile_css.sh"
  },
  "ext": "js json jade css scss html",
  "verbose": true
}
```

**Comment by urugator** [comment]
Where do you get the $FILENAME? Are the filenames of changed files somehow passed to compile_css.sh script?

Btw, if you're insterested how I currently solve compiling client side resources, than I simply run compilation (in your case gulp taks) asynchronously at the beginning of the app script.
This means that resources are compiled at every app restart, even if they weren't changed, but the compilation process doesn't block the main app, so it doesn't really matter.
It also doesn't really matter that app is restarted even when only client side resources have been changed, because the app restart is always faster than compilation process in my case.

**Comment by kgraves** [comment]
`$FILENAME` is an environment variable populated by [nodemon](https://github.com/remy/nodemon/blob/6ccb29864c7a17b578a5a09b9a2dd382bbb41066/lib/spawn.js#L32). Every time a file is changed, each `events` entry is run with the environment variable set to the file path.

There are a couple examples in the repo [here](https://github.com/remy/nodemon/blob/6ccb29864c7a17b578a5a09b9a2dd382bbb41066/doc/sample-nodemon.md) and [here](https://github.com/remy/nodemon/blob/6ccb29864c7a17b578a5a09b9a2dd382bbb41066/test/fixtures/global/nodemon.json)
