### ISSUE TITLE
Restart not working on file change

### ISSUE THREAD

**Issue by karlbateman** [remy/nodemon#839]
Hi All,
Does not seem to be working for me anymore? Included is some info, hope it helps 😄 

**Version**

```
Nodemon v1.9.2
```

**Command**

```bash
[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `NODE_ENV=dev node --use-strict app -c "node --use-strict" app`
Working[3000]
```

**Additional Info**

```bash
nodemon -V --dump app.js 
[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] ignoring: /Users/karlbateman/Projects/NodeJS/api/.git/**/* .nyc_output coverage /Users/karlbateman/Projects/NodeJS/api/node_modules/**/*
[nodemon] watching: *.*
[nodemon] watching extensions: js,json
--------------
node: v5.1.0
nodemon: 1.9.2
command: /Users/karlbateman/.nvm/versions/node/v5.1.0/bin/node /Users/karlbateman/.nvm/versions/node/v5.1.0/bin/nodemon -V --dump app.js
cwd: /Users/karlbateman/Projects/NodeJS/api
OS: darwin x64
--------------
{ run: false,
  system: { cwd: '/Users/karlbateman/Projects/NodeJS/api' },
  required: false,
  dirs: [ '/Users/karlbateman/Projects/NodeJS/api' ],
  timeout: 1000,
  options: 
   { verbose: true,
     dump: true,
     ignore: 
      [ '.git',
        '.nyc_output',
        'coverage',
        'node_modules',
        re: /\.git|\.nyc_output|\-cache|coverage|node_modules/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot: 
      [ '.git',
        '.nyc_output',
        'coverage',
        'node_modules' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     stdout: true,
     execOptions: 
      { script: 'app.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js,json',
        env: {},
        execArgs: [] },
     monitor: 
      [ '*.*',
        '!/Users/karlbateman/Projects/NodeJS/api/.git/**/*',
        '!.nyc_output',
        '!coverage',
        '!/Users/karlbateman/Projects/NodeJS/api/node_modules/**/*' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  command: 
   { raw: { executable: 'node', args: [ 'app.js' ] },
     string: 'node app.js' } }
--------------
[nodemon] exiting
```

Regards,
[@karlbateman](https://github.com/karlbateman)

**Comment by remy** [comment]
You mention *anymore*. What's changed? I'll look at that first.

**Comment by karlbateman** [comment]
Nothing, I know it would be a new version since I last used it? But I can't remember the version previously which was working for me. None of my code has changed, it seems that this has decided to just stop working?

**Comment by JuanCaicedo** [comment]
I'm experiencing this too, but on two projects both using 1.9.2 😕. 

In [this project](https://github.com/JuanCaicedo/oboe.js-website), restart works (running `$ nodemon -e js,md,scss,handlebars --exec 'node build-static.js' -V`). It says it is watching 465 files.

In [this other project](https://github.com/JuanCaicedo/juancaicedo.github.io/tree/metalsmith), restart does not work (running `$ nodemon -e js,md,scss,handlebars,hbt --exec 'node index.js' -V`). It says it is watching 0 files.

@karlbateman could you try adding the `-V` flag to see if your also says watching 0 files?

**Comment by karlbateman** [comment]
I can confirm that running the command with the `-V` flag does indeed show that `0 files` are being watched. @JuanCaicedo thanks for pointing that out 😄

**Comment by remy** [comment]
Damnit - I'm able to replicate and I finally managed to work out what was going wrong.

It's Chokidar (which is the underlying file watch system), it doesn't like the directory name: `juancaicedo.github.io` but changing it to `juancaicedo` does work.

I've been wanting to send a PR to Chokidar to fix this but I've not had the time at all, and it requires the fix in two places (for multiple OSs).

I'm going to close, but only because we have a work around, not a solution 😦

**Comment by JuanCaicedo** [comment]
Weeeeird, but thanks for the fix! @karlbateman does your directory have something similar?

**Comment by karlbateman** [comment]
No, mine is just a standard express application.

**Comment by remy** [comment]
@karlbateman do you have a public repo that I replicate this with?

**Comment by karlbateman** [comment]
@remy Hey, please see [this repo](https://github.com/karlbateman/nodemon-issue). I hope it helps :smile:

**Comment by paulmolluzzo** [comment]
@remy (and for anyone finding this issue) I don't have a public repo you can test on, but I can confirm that changing the _root_ directory name to not have an `_` fixes the issue for me. I changed it from `some_repo` to `somerepo` and that got it working.

**Comment by VincentPuget** [comment]
I had the same issue. 
My root directory was named "mysite.git" and nodemon was watching 0 file. I had renamed my root directory without the dot and nodemon now works as expected.
