### ISSUE TITLE
Ignoring src/ in docker container won't trigger restart

### ISSUE THREAD

**Issue by adam-beck** [remy/nodemon#847]
I'm working on a React application that also includes a Hapi server -- in `src/` and `server/` respectively. The server is in a node docker container. The container starts with a script: `nodemon -L server/server.js` and with no `nodemon.json` file changing files in `server` directory triggers a restart. Unfortunately, changing front-end files in `src` _also_ triggers a server restart.

So I created a `nodemon.json` file and ignored the `src/` directory and things broke. The server no longer restarts. I can include a `"watch": ["server/*"]` and things work as expected. But, I'm still confused as why simply ignoring the `src` directory (which includes no server related files) would break the restarting of nodemon.

If I don't run this in a docker container then there isn't an issue. 

**Dump**

```
node: v5.9.0
nodemon: 1.9.2
command: /usr/local/bin/node /usr/src/app/node_modules/.bin/nodemon --dump
cwd: /usr/src/app
OS: linux x64
--------------
{ run: false,
  system: { cwd: '/usr/src/app' },
  required: false,
  dirs: [ '/usr/src/app' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '.git',
        '.nyc_output',
        '.sass-cache',
        'bower_components',
        'coverage',
        'node_modules',
        '.git',
        'node_modules/**/node_modules',
        'dist',
        'src',
        re: /\.git|\.nyc_output|\.sass\-cache|bower_components|coverage|node_modules|\.git|node_modules\/.*.*\/node_modules|dist|src/ ],
     verbose: false,
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot:
      [ '.git',
        '.nyc_output',
        '.sass-cache',
        'bower_components',
        'coverage',
        'node_modules' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     stdout: true,
     execOptions:
      { script: 'index.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js,json',
        env: {},
        execArgs: [] },
     monitor:
[ '*.*',
        '!/usr/src/app/.git/**/*',
        '!.nyc_output',
        '!.sass-cache',
        '!bower_components',
        '!coverage',
        '!/usr/src/app/node_modules/**/*',
        '!/usr/src/app/.git/**/*',
        '!node_modules/**/node_modules',
        '!dist',
        '!/usr/src/app/src/**/*' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [ '/usr/src/app/nodemon.json' ],
  watchInterval: null,
  command:
   { raw: { executable: 'node', args: [ 'index.js' ] },
     string: 'node index.js' } }
```

**Comment by LasseNisted** [comment]
I had a similar problem with a "src" directory. By changing "--ignore src/" to "--ignore ./src/" it started working again.
The reason is that my entire source tree sits below another folder names src. You have a similar pattern: /usr/src/app/src.
The regular expression shown in the dump:
` re: /\.git|\.nyc_output|\.sass\-cache|bower_components|coverage|node_modules|\.git|node_modules\/.*.*\/node_modules|dist|src/ ],
`
Ends up ignoring your entire directory tree.

**Comment by adam-beck** [comment]
Thanks! That makes perfect sense. Don't know how I missed the regular expression in the dump. 

Do you think this should be the desired behavior? I don't think it's too much to ask users to use more explicit relative positions but it still seems a little strange to me that it will look *anywhere* in the path for the given directory.

**Comment by LasseNisted** [comment]
It was not the behavior I expected. At least it could be documented more clearly. The examples in:
https://github.com/remy/nodemon#ignoring-files
are not elaborate enough. An example or two would help.
