### ISSUE TITLE
Using nohup with nodemon

### ISSUE THREAD

**Issue by yosserO** [remy/nodemon#850]
Hi Im trying to use nodemon with nohup.
I know there is already an issue about this, but I tried every proposed solution without any success.

When I start the server.js file without nohup everything works well and the changes affecting the directory are detected by nodemon.

If I run it using nohup, the website is shown everything works well but the changes are not detected.

I'm getting this in the nohup.out file:

[33m[nodemon] 1.9.2[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching: _._[39m
[32m[nodemon] starting `node ./server.js localhost 3000 nohup`[39m
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
    at Error (native)

Thank you

**Comment by qomosoloto** [comment]
same problem ...

**Comment by Pratikmehta1729** [comment]
Same issue ,

**Comment by wzzz** [comment]
Same issue
