### ISSUE TITLE
Nodemon restarts on other .js file save 

### ISSUE THREAD

**Issue by TomVance** [remy/nodemon#853]
When editing two JS files at the same time: _server.js_ and _app.js,_ nodemon restarts after saving _app.js_ even when I run: _nodemon server.js_

**Comment by akwuh** [comment]
@TomVance and [it's correct](https://github.com/remy/nodemon#monitoring-multiple-directories) due to nodemon's default watch option is ['*.*'], so when not specifying watch option manually it will watch all files in current directory.
Must be closed.
