### ISSUE TITLE
Restart not working in Dropbox directory

### ISSUE THREAD

**Issue by mindvox** [remy/nodemon#872]
Hi @remy,

I just thought I would mention it, but my previous issues with nodemon not working, stem from having my projects within a Dropbox directory. Nodemon runs without error, however it does not restart on file changes.

Please let me know if I can be of any further assistance in helping to resolve this.

Regards K 😃

**Comment by gaprl** [comment]
@karlbateman it seems like the problem is actually with the folder name: 

> `~/Dropbox (Personal)/project/folder`

If your Dropbox folder has a similar setup, watch won't work properly because of ` `, `(` and `)` in the path.

I removed the (Personal) from my folder's name and it seems to be working now :)

**Comment by karlbateman** [comment]
@gaprl Yes I agree, we have this issue with our Business dropbox as the directory name is `Dropbox (CompanyName)`, Nodemon doesn't work. Perhaps the path needs to be escaped?
