### ISSUE TITLE
Ignore is not working

### ISSUE THREAD

**Issue by ErraticFox** [remy/nodemon#877]
I'm running the nodemon line from `npm start` from my `package.json`. The line is `nodemon --ignore 'lib/options.json'`. This does start nodemon, but it does not ignore the `options.json` file. I've also tried `'./lib/options.json'` still no luck. Any reason?

**Comment by remy** [comment]
If you want it to ignore the `package.json`, then you'll need to do (something like) `nodemon --ignore package.json`. Or you can list the assets you want to ignore in a `nodemon.json` file in the root of your project.

Hope that clarifies (closing the issue, I suspect you're just putting your config in the `options.json` file).
