### ISSUE TITLE
Allow .env file to be specified via cli flag

### ISSUE THREAD

**Issue by mettjus** [remy/nodemon#878]
It would be very useful if a path to a `.env` file could be specified without the need of creating an additional `nodemon.json` to inject environment variables. Right now there are a number of workarounds (eg: using Foreman or running commands such as `env $(cat .env) nodemon app.js`) to achieve this but they are all less than optimal.
Something like `nodemon --env-file .env app.js` would be great!

**Comment by remy** [comment]
Why not use npmjs.com/dotenv to read this enviroment file instead?

**Comment by mettjus** [comment]
You mean inside the app? I normally use .env as a placeholder for environment variables I later inject in my docker containers. Another way I sometimes work around the impossibility of specifying the env file via flag is using dotenv inside a guplfile for dev only purposes, but of course avoiding it would be much more comfortable :)

**Comment by yanneves** [comment]
This could become too convoluted. Also, you may prefer to use [dotenv-safe](https://github.com/rolodato/dotenv-safe), which would warrant another argument like `--env-sample-file`.

To make use of dotenv right now in Nodemon, I'd suggest using:
```bash
nodemon --exec "node -r dotenv/config" script.js
```

AFAIK, there's no config in Nodemon for passing command-line options to Node, along the lines of:
```bash
node [options] script [arguments]
```

Maybe that's something that should be supported (or already is)?

**Comment by mettjus** [comment]
The `nodemon --exec "node -r dotenv/config" script.js` trick is a valid workaround, IMHO. Thanks @yanneves.

**Comment by yanneves** [comment]
No problem!

**Comment by maxfrigge** [comment]
In case anyone else needs it :)

This works: `nodemon --exec 'node -r dotenv/config' dist/server.js dotenv_config_path=config.env`

**Comment by j0hnm4r5** [comment]
And if you were also using something like esm, you'd do it like this: `nodemon --exec 'node -r esm -r dotenv/config' index.js`

**Comment by 09wattry** [comment]
I was able to do this by providing the path option to my .env file in my execution script. I used a relative path, which worked, or you could use the path resolve() function to get an absolute path.

```javascript
const { resolve } = require('path');
const envPath = resolve(process.cwd(), '../.env');

require('dotenv').config({ path: envPath });
```
