### ISSUE TITLE
Code reloading inside Docker generates a lot of zombie processes

### ISSUE THREAD

**Issue by castarco** [remy/nodemon#881]
Hello,
I have a docker image with a `CMD` command like this:

```
CMD ["nodemon", "-w", "/app/src", "/app/src/server.js"]
```

And the `/app` directory is mounted from outside the container, mapped to a host directory.

Recently we have discovered that every time nodemon detects a change inside the monitored directory (in this case is `/app/src`), and restarts the server, it doesn't kill the older process, but leaves it in `defunct` state.

This is very problematic because we reach the limit of allowed processes when we're developing.
Any idea of what we're doing wrong? or any solution?

Thank you for your time and effort.

**Comment by mvaker** [comment]
+1, also experiencing this issue. It may also be related with #882

**Comment by srgl** [comment]
+1
node 4.5.0
nodemon 1.10.2
docker 1.12.1
official docker image argon

**Comment by tuxx42** [comment]
+1

**Comment by bdharrington7** [comment]
This still happens. #882 is not related. 

nodemon 1.18.4
node 8.11.4

Docker container is based on Ubuntu 14.04.1 LTS

**Comment by trxcllnt** [comment]
@bdharrington7 I haven't encountered this issue. Here's how I have things set up:

First define an entrypoint shell script. In this example, the entrypoint is going to start a zeit micro server, so I've named it `./entrypoints/micro.sh`. I've also parameterized watching with nodemon, using `--inspect`, and beautifying logs via environment variables. We are also running node with `esm` to runtime interop between commonjs and esmodules. Apologies for my terrible bash.

```sh
#!/bin/sh
set -o errexit

# env vars:
# DEBUG_REFRESH - execute via nodemon
# DEBUG_INSPECT - run node with the `--inspect` flag
# PRETTY_LOGS - run output through pino-pretty

# use node to resolve the path to these binaries in the closest
# node_modules to our cwd instead of the mono-repo root
micro=$(node -e "process.stdout.write(require.resolve('micro/bin/micro'))");
pretty=$(node -e "process.stdout.write(require.resolve('pino-pretty/bin'))");
kill_port=$(node -e "process.stdout.write(require.resolve('kill-port/cli') + ' -k 9228/tcp')");
watch=$(node -e "process.stdout.write(require.resolve('nodemon/bin/nodemon') + ' --delay 80ms')");

# "$@" here is the docker container `CMD` entry
start_server="$micro -l tcp://0.0.0.0:80 $@";

if [ "$DEBUG_INSPECT" = "true" ] ; then
    start_server="node -r esm --inspect=0.0.0.0:9228 $start_server";
    if [ "$DEBUG_REFRESH" = "true" ] ; then
        start_server="$watch --exec $kill_port; $start_server";
    fi
elif [ "$DEBUG_REFRESH" = "true" ] ; then
    start_server="$watch $start_server";
else
    start_server="node -r esm $start_server";
fi

if [ "$PRETTY_LOGS" = "true" ] ; then
    exec  $(echo "$start_server") | $pretty;
else
    exec  $(echo "$start_server");
fi
```


Then copy the entrypoint script into your container, create an ENTRYPOINT layer, and make your `CMD` point to the raw path to your server's index file (e.g. `./path/to/your/server.js`).

You can add a `#! /usr/bin/env node` directive to the top of your server index file (as well as  `chmod +x` it). If you're not using `micro` to launch your server, this will ensure the entrypoint's `exec` invocation makes the your server's node process the new pid 1 (if none of the env vars are true).

```dockerfile
# FROM your/container etc
# <your dockerfile here>
COPY ./entrypoints/micro.sh /entrypoints/micro.sh
RUN chmod +x /entrypoints/micro.sh
ENTRYPOINT ["/entrypoints/micro.sh"]
CMD ["./path/to/your/server.js"]
```

To verify, here's the process list for one of the containers I do this way (no env vars set):
```sh
$ docker-compose exec -T dataset ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
auser         1  3.1  0.2 809468 168760 ?       Ssl  00:38   0:03 node -r esm /opt/graphistry/node_modules/micro/bin/micro.js -l tcp://0.0.0.0:80 ./index.js
auser        67  0.0  0.0  34400  2868 ?        Rs   00:39   0:00 ps -aux
```
