### ISSUE TITLE
Cannot clone and checkout branch due to fixture filenames on Windows

### ISSUE THREAD

**Issue by AlmirKadric** [remy/nodemon#885]
This project is not usable on `Windows` as some of the test fixtures have filenames with unsupported characters. This causes `Git` to break during it's checkout phase.

An example fixture filename is `some\"file`

**Comment by pombredanne** [comment]
and this and the dupe #900 make scancode choke https://github.com/nexB/scancode-toolkit/issues/413 when scanning nodemon
