### ISSUE TITLE
Clean exit, waiting for changes

### ISSUE THREAD

**Issue by ErraticFox** [remy/nodemon#886]
I have a bot for a chat room that I run with nodemon in the background. I haven't changed or touched anything with the bot in the last week or two, but it keeps going to the "Clean exit, waiting for changes" and I keep have to restart it with `rs`, which is quite annoying when it's suppose to be up all the time. Any reason it keeps clean exiting?

**Comment by remy** [comment]
It means your chat bot is exiting cleanly (ie without an exception). I'm
assuming your bot shouldn't be shutting down?
