### ISSUE TITLE
babelrc not being picked up anymore

### ISSUE THREAD

**Issue by 0x80** [remy/nodemon#887]
I upgraded from nodemon 1.9 to 1.10 and now it seems that .babelrc is not picked up anymore by the babel-node exe. 

This is my nodemon.json content:

``` json
{
  "execMap": {
    "js": "babel-node"
  }
}
```

**Comment by MikeBarnhardt** [comment]
I am on 1.10.* and don't have this issue. Can you post your .babelrc file? Could be a json formatting issue...

**Comment by 0x80** [comment]
```
{
  "presets": ["es2015", "react", "stage-0"],
  "plugins": ["transform-runtime", "add-module-exports", "transform-decorators-legacy"]
}
```

**Comment by MikeBarnhardt** [comment]
Spent some time messing around with a new project and started running into errors myself again.

It seems like pointing nodemon to a directory `nodemon src/server` instead of a file `nodemon src/server/index.js` would cause it to run without the `execMap` option (probably because it doesn't know if it's a js file or not). Can you confirm if this solves your problem?

**Comment by 0x80** [comment]
I'm starting nodemon on a file directly, but via an `npm start` script in package.json. And I have nodemon installed as a project dependency rather then globally , so it's resolving to `./node_modules/.bin/nodemon`

**Comment by MikeBarnhardt** [comment]
I am doing the same exact thing as you and it works fine for me.

Here is my nodemon.json file:
```json
{
  "env": {
    "NODE_ENV": "development",
    "PORT": "8001"
  },
  "execMap": {
    "js": "babel-node",
    "jsx": "babel-node"
  },
  "ext": "js jsx json",
  "ignore": [
    ".git/",
    "node_modules/"
  ],
  "watch": [
    "src"
  ]
}
```

And my .babelrc:
```json
{
  "presets": ["es2015", "react", "stage-2"]
}
```

I'm using the following versions:
```json
{
    ...
    "babel-cli": "^6.11.4",
    "babel-preset-es2015": "^6.13.2",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-2": "^6.13.0",
    ...
    "nodemon": "^1.10.2",
    ...
}
```

And my npm script:
```json
"scripts": {
    ...
    "demon": "nodemon src/server/index.js"
    ...
}
```

If updating your packages doesn't work then there must be some other issue causing it not related to those packages.

**Comment by 0x80** [comment]
Ok I will try to take a closer look soon, but I'm in the middle of a hectic project launch, followed by holidays. So not entirely sure if that will be very soon...
