### ISSUE TITLE
Unexpected mouse output running blessed

### ISSUE THREAD

**Issue by kenwheeler** [remy/nodemon#890]
What up @remy !

Just released https://github.com/FormidableLabs/webpack-dashboard , and some users that are running their stuff with nodemon are reporting that mouse movement is leaking into their terminal. Any ideas on how to mitigate this?

I tried passing quiet and no-std-in flags, but with no luck.

Thanks!

**Comment by remy** [comment]
Is there a simple project I can run the dashboard against to try to replicate? I can't think of any reason this would happen, but I'm guessing a quick node vs nodemon shows it occurring.

Also, in the "simple project" assume I have zero knowledge of webpack! :)

**Comment by bmv437** [comment]
This is one of the starter kits a lot of people are using, myself included.
https://github.com/davezuko/react-redux-starter-kit

Just gotta hook in `webpack-dashboard` as defined in the README
The files you're looking are in the `server/` directory.

**Comment by remy** [comment]
So…I've got something running, but like I said, I have zero knowledge on this stuff and I tend to attract bugs…

This is what the snippet of my `server/main.js` looks like (note that I've required in the dashboard at the top of the code out of view in this gist): https://gist.github.com/remy/9dbd34d4ae6e6f8fbb6d5354a8c42469#file-main-snippet-js-L13

And note that the line I highlight is different from the README in the dashboard project. The code was complaining that I was trying to read `publicPath` from an `undefined` object, so I _think_ it's supposed to come from `webpackConfig`.

And this is the result of the dashboard (which loads fine, but then goes a bit…acidy):

<img width="1280" alt="screen shot 2016-08-17 at 21 01 31" src="https://cloud.githubusercontent.com/assets/13700/17751313/87a8e7be-64be-11e6-8720-d83653f327b7.png">

I'm guessing this is the logging not be told to STFU but I was just following the directions in the dashboard project.

I'm going to go ahead and run with nodemon to see what happens (I use zsh already which I saw a number of people reported in https://github.com/FormidableLabs/webpack-dashboard/issues/16.

I'll let you know how I get on. If you've got any tips on how to fix the output.

**Comment by remy** [comment]
Huh. Okay, confirmed it's happening. I'll start kicking the tyres of nodemon to see why. Suspect it's linked to redirecting stdout streams…but we'll see.

**Comment by remy** [comment]
Little bit further along. The issue is with https://github.com/chjj/blessed - running the examples through nodemon have the same effect.

**Comment by remy** [comment]
Okay, got a working solution, just not sure what the impact is on _everything_ else.

**Comment by remy** [comment]
I've pushed a branch. I've got to tap out this evening, but I'll keep an eye on the tests to see what happens (I ran them locally but some bailed, and I'm never sure if it's local env or what…).

The branch definitely fixes the issue you're seeing with the dashboard and mouse movement, but whether it breaks some other use, I'm not sure as yet

**Comment by remy** [comment]
So, the tests are failing because when I use `inherit` for the `stdio` of the child, it seems that nodemon can't talk to the forking process (the test itself) using `process.send` anymore (which is used to check the progress of the tests).

I'll have to try to create a parred down test to replicate (which ain't gunna be fun)… will keep you in the loop.

**Comment by remy** [comment]
Okay, seriously, I need to hit the sack. But I _think_ I've got a fix. It's going up in https://github.com/remy/nodemon/pull/892

**Comment by joefiorini** [comment]
@remy Is there a new issue to track this since it was reverted for #894/#895?

**Comment by hawkins** [comment]
Would it be possible to use the `stdin=inherit` if a certain option is passed into nodemon's settings? I.e., `nodemon({stdinInherit: true})` or similar?

I am also trying to use nodemon with blessed and using the fix from #892 worked for my blessed project.
