### ISSUE TITLE
Need to save two times to really restart the server

### ISSUE THREAD

**Issue by Aurelsicoko** [remy/nodemon#893]
Hi guys!

I have an issue that makes me crazy... I can't figure out what happen! I'm using Nodemon through a command line. What I'm trying to do seems pretty simple. Here are my files:

`command-start.js`. 

``` js
// I can execute this file through the command `project start` in my terminal.
module.exports = () => {
  nodemon({
    script: 'server.js',
    ext: 'js json'
  });

  nodemon.on('restart', function (files) {
    console.log('Restarting due to changes...');
    console.log();
  });
}
```

`server.js`

``` js
process.chdir(__dirname);

(() => {
  const app = require('app');
  app.start();
  console.log('Server started');
})();
```

When I save changes in my file, the log `Restarting due to changes...` is displayed. But nothing happens. Then, I save the same file again without doing anything else, the log `Restarting due to changes...` is displayed and the `server.js` is restarted as well (the log `Server started` is displayed).

I can't understand why I have to save my file two times to really restart the server... Any idea?

---
- nodemon: `1.10.0`
- node: `6.4.0`
- npm: `3.10.3`

**Comment by kimthangatm** [comment]
I also encountered this problem at `nodemon 1.10.2, node 4.4.5`. I change version to 1.10.1 and nodemon work

sudo npm i -g nodemon@1.10.1

**Comment by Aurelsicoko** [comment]
@kimthangatm: Thanks for your answer! I will try it soon. I switched to `forever-monitor` meanwhile.
