### ISSUE TITLE
[Question] - Customize logging level

### ISSUE THREAD

**Issue by IOAyman** [remy/nodemon#896]
Does `nodemon` support different logging levels (something like silent, normal or verbose) for different events?

**i.e:**
_onStart:_ normal logging output
_onRestart:_ silent, no output
_onCrash:_ verbose output

**Comment by remy** [comment]
From the cli, yes: 

- no args: normal output
- `-q`: quiet aka silent 
- `-V`: verbose

If you're requiring nodemon, then you can pass these options but also manage the output yourself on the events.

**Comment by IOAyman** [comment]
Thank you @remy.
