### ISSUE TITLE
Can nodemon run different command by watching different file?

### ISSUE THREAD

**Issue by simonchan2013** [remy/nodemon#897]
Hello, does this can do something like that: if I update file a.js, and then run command A, and if I update b.js then run command B

maybe the nodemon.json should like this

``` json
{
  "scripts": [
    {
      "watch": "a.js",
      "exec": "node ./index.js"
    },
    {
      "watch": "b.js",
      "exec": "npm run build && node ./index.js"
    }
  ]
}
```

I check the documents and google it, but didn't find the solution, can nodemon do something like this? wish your response, thanks

**Comment by sydneyzh** [comment]
I was looking for the same thing. At this point I can only combine the building scripts for a and b and watch them at the same time.

**Comment by githubjosh** [comment]
this would be pretty handy

**Comment by MrFeroyan** [comment]
Any updates on this?
