### ISSUE TITLE
Nodemon not restarting if main file has no extension

### ISSUE THREAD

**Issue by aalexgabi** [remy/nodemon#904]
I have a js file without extension and when it's content changes nodemon doesn't restart it. I saw that we can specify file extension list but shouldn't the main file be supported with a shebang?

Any ideas how to fix this?

**Comment by remy** [comment]
It's not a great answer, if this is a node project, you can give it an extension, and just alias inside of your package.json (the same way nodemon does). If it's not…im not sure. Sorry.

**Comment by aalexgabi** [comment]
I fould a workaround:
```
$ nodemon --watch file-without-extension file-without-extension
```

**Comment by entozoon** [comment]
This problem does still exist. The workaround is fine but it is an unexpected problem regardless

**Comment by yanicakj** [comment]
@aalexgabi The issue with that workaround is nodemon will no longer watch parent directories (for example, if you use `--watch /bin/www` all files outside bin are not watched, which is problematic.

**Comment by Nemesarial** [comment]
I created some node-based githooks and was using nodemon to rerun on changes. I added a lib folder with some shared code. 
when I run `nodemon -w .githooks/ .githooks/pre-commit` nodemon catches changes in `.githooks/*` but does not restart when `.githooks/pre-commit` is changed

I then tried `nodemon -w .githooks/pre-commit`. This sees changes to `.githooks/pre-commit` but nothing else.

I then tried `nodemon -w .githooks/pre-commit -w .githooks/ .githooks/pre-commit`. This sees changes to `.githooks/*` but not changes to `.githooks/pre-commit`

Frustrating...

**Comment by entozoon** [comment]
So it should be re-opened, right?

**Comment by remy** [comment]
Happy to reopen with a PR.

**Comment by broofa** [comment]
Submitting PR.

FWIW, my use case for this is that I need to run a script that does `docker build` any time a file in the current directory changes.  If I do`nodemon --ext "*" -x build.sh`, it doesn't restart when`Dockerfile` changes .  Nor does using `--ext Dockerfile` work.
