### ISSUE TITLE
Nodemon is not updating any changes in www file

### ISSUE THREAD

**Issue by gunnu9** [remy/nodemon#906]
I am new to Node.js .
I have installed node.js and nodemon  and when i make any changes in www file, it does not show the changes in cmd prompt, but when i rs , it shows the changes.

**Comment by gunnu9** [comment]
![image](https://cloud.githubusercontent.com/assets/18192951/18512416/9fcb4c38-7a4e-11e6-9384-ef36ae53dc7e.png)

**Comment by stigok** [comment]
You can manually add the path to your `www` when running nodemon with the `-w` flag.

```
$: cd myrepo
$: nodemon -w bin/www
```
