### ISSUE TITLE
[nodemon] Internal watch failed: watch ENOSPC

### ISSUE THREAD

**Issue by StCremer** [remy/nodemon#907]
After restarting Nodemon with the same file got this Error.
Os: CentOs 7
[nodemon] 1.10.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node telefumSearcher.js`
[nodemon] Internal watch failed: watch /home/st.cremer/Сайты/telefumsearcher ENOSPC

**Comment by cnadeau** [comment]
Had the same problem with node 0.10.46

I found out that this problem started in nodemon 1.4.2, 1.4.1 works fine for us

**Comment by showzyl** [comment]
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
...
[nodemon] Internal watch failed: watch ENOSPC

**Comment by remy** [comment]
Googling `ENOSPC` refers to disk space and a lack thereof. Could be a temp drive, could be something else, but that error is coming from node.

**Comment by phuongleduy** [comment]
you can use ps -ef | grep node to find the process id

and then sudo kill -9

**Comment by dontito94** [comment]
This work for me

echo fs.inotify.max_user_watches=582222 
 sudo tee -a /etc/sysctl.conf 

 sudo sysctl -p

**Comment by keshrirai** [comment]
This is not working nodemon ....why.. ?????
[nodemon] 1.17.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
[nodemon] Internal watch failed: watch /media/keshri/Documents/Express/project ENOSPC

**Comment by dontito94** [comment]
@keshrirai have you tried this? its works for me.
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

**Comment by lenikhilsingh** [comment]
@dontito94 , thanks a lot man. It worked. I'm curious to know more about it. Can you please explain the function of that command?

**Comment by madanpandey97** [comment]
@  dontito94  what function you have used, please explain

**Comment by dontito94** [comment]
@madanpandey97  echo fs.inotify.max_user_watches=524288 it increase the number of watches of nodemon as you made some changes in your project

**Comment by abejide001** [comment]
@dontito94  worked for me, thanks.

**Comment by dontito94** [comment]
thanks bro @chan1di

**Comment by OrionStark** [comment]
@dontito94  Thanks dude hahahaha...

**Comment by Zircoz** [comment]
Thanks man @dontito94

**Comment by simba999** [comment]
It works for me. Thanks, @dontito94.
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

**Comment by cantdocpp** [comment]
thank you @dontito94 you've saved me

**Comment by yacineMTB** [comment]
This is probably because we are killing the proc in a way that doesn't make it stop watching the folder. There's probably a more graceful way of dealing with it than simply adding the allowed watchers.. that limit is set for a reason

**Comment by nerkn** [comment]
> This is probably because we are killing the proc in a way that doesn't make it stop watching the folder. There's probably a more graceful way of dealing with it than simply adding the allowed watchers.. that limit is set for a reason

@yacineMTB  I just restarted computer

**Comment by nerkn** [comment]
@yacineMTB i just restarted the computer

**Comment by tbhaxor** [comment]
> @keshrirai have you tried this? its works for me.
> echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

Why do i always have to execute this command before nodemon ?

**Comment by dontito94** [comment]
@tbhaxor  it increase the number of watches of nodemon as you made some changes in your project and  configure kernel parameters at runtime

**Comment by dontito94** [comment]
> > @tbhaxor it increase the number of watches of nodemon as you made some changes in your project and configure kernel parameters at runtime
> 
> Maybe thats why because originally `/etc/sysctl.conf` doesnt exists in my OS
> Btw: my os is Arch Linux 4.19-Manjaro

Yeah sure! so just do execute at a time before nodemon

**Comment by shashanksaxena** [comment]
@dontito94 Great thanks !

**Comment by Ankitacse** [comment]
step1)
sudo npm install mongodb@latest

step2)
echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen

step3)
sudo apt-get update

step4)
 echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse

step5)
sudo apt-get install MongoDB

step6)
nodemon serve

hopefully, it solved the same error I am facing while working on Angular8 with Nodejs and using MongoDB as a database.

for fetching above steps I follow the following links:-
1)https://docs.mongodb.com/v3.0/tutorial/install-mongodb-on-debian/
2)https://stackoverflow.com/questions/28945921/e-unable-to-locate-package-mongodb-org.
3)https://stackoverflow.com/questions/34733340/mongodb-gpg-invalid-signatures
that's all .. :)

**Comment by demonta1111** [comment]
It appears that my max ports weren’t configured correctly. I ran the following code and it worked…

echo fs.inotify.max_user_watches=582222 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
What this command does is to increase the number of watches allowed for a single user. By the default the number can be low (8192 for example). When nodemon tries to watch large numbers of directories for changes it has to create several watches, which can surpass that limit.

You could also solve this problem by:

sudo sysctl fs.inotify.max_user_watches=582222 && sudo sysctl -p

If Still Not Working Please Look For this Solution [Icetutor](https://icetutor.com/question/node-js-getting-error-nodemon-internal-watch-failed-watch-enospc/)

**Comment by dezentechorg** [comment]
@dontito94 Great, Worked for me. thanks !
