### ISSUE TITLE
folders with suffix .git not detecting changes

### ISSUE THREAD

**Issue by jas99** [remy/nodemon#916]
Hi @remy 

I use .git suffix for my git projects. When I try to use nodemon on lets say folder `Projectxx.git`; they changes won't get detected.

Thx

**Comment by rjmunro** [comment]
I have a related problem as I have a file in my project called coverage.js, and it is getting ignored by the (undocumented) ignoreRoot entry "coverage". I think the entries in ignoreRoot should only match exact folder names, not partial names or file names.

**Comment by mattlyons0** [comment]
I think how Nodemon handles ignoring file/folder names is a problem. It uses the ignore-by-default package and fuzzy ignores those names. This means anything with '.git' in the absolute path ignored, the same goes for anything containing 'coverage' or 'node_modules' in the absolute path. I think this is a problem as all of the cases is in the ignore-by-default package were meant (under my understanding) to be used only for exact matches. I will look into making a PR to fix this

**Comment by remy** [comment]
Yeah, the PR added a new regexp without any real explanation as to what it did, but more importantly, it [didn't actually test that it worked](https://github.com/remy/nodemon/pull/922#issuecomment-254048653). I'd be more than happy to reopen.

**Comment by dominykas** [comment]
A workaround while the fix is being worked on is to [override default ignored folders](https://github.com/remy/nodemon/blob/master/faq.md#overriding-the-underlying-default-ignore-rules), e.g. place the below in `nodemon.json`:

```
{ 
  ignoreRoot: [ '.nyc_output', '.sass-cache', 'bower_components', 'coverage', 'node_modules' ]
}
```

The above keeps the current defaults, but excludes `.git`.
