### ISSUE TITLE
proper way to set ignore patterns

### ISSUE THREAD

**Issue by antonioaltamura** [remy/nodemon#917]
in my nodemon.json I set 

```
  "ignore": [
    ".git",
    "/node_modules/**/node_modules",
    "/public/*",
    "/data/**/*"
  ]
```

but I see a nodejs server reload when I change a file in `public`, `data` and `node_modules` too
I even tried to set cli parameters `nodemon.js --ignore 'public/**/*.js'`

**Comment by staminna** [comment]
@antonioaltamura Did you manage to find a workaround on this?
