### ISSUE TITLE
Nodemon watching Zero files if set in nodemon config

### ISSUE THREAD

**Issue by bohrasankalp** [remy/nodemon#919]
I have issues with nodemon module. Either it watches 10K+ files, or if I ignore the files in nodemon.json config then it watches zero files.
'nodemon.json'

``` json
{
    "verbose"    : true,
    "legacyWatch": true,
    "ignore"     : [
        "app/*",
        "node_modules/*",
        "ionic/*",
        "db/*",
        "logs/*",
        "uploads/*",
        "dump/*",
        "SalesiusRestApi/*",
        "SalesiusApp/*",
        "salesius/*"
    ]
}
```

In this config it ignores everything. The watch count is zero. My output is,

```
[nodemon] 1.10.2
[nodemon] reading config /home/sony/Desktop/node/all/db/nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] ignoring: /home/sony/Desktop/node/all/db/.git/**/* .nyc_output .sass-cache bower_components coverage /home/sony/Desktop/node/all/db/node_modules/**/* app/**/* node_modules/**/* ionic/**/* db/**/* logs/**/* uploads/**/* dump/**/* SalesiusRestApi/**/* SalesiusApp/**/* salesius/**/*
[nodemon] watching: *.*
[nodemon] watching extensions: js,json
[nodemon] starting `node server.js`
[nodemon] child pid: 13548
[nodemon] watching 0 files
```

In case I remove ignore option, the watch count reaches to 10K files.

**Comment by jonmaim** [comment]
I had the same problem, _i.e._, `[nodemon] watching 0 files`. Following your observation that if you remove the entries in the ignore field it's working again, I was able to narrow it down to a single directory causing the problem. 

Surprisingly, adding a `./` at the beginning of that specific directory path solved the problem.

**Comment by xGouley** [comment]
Thank you @jonmaim ! with the same process, I found that the "test" folder in the ignore field was blocking everything...
