### ISSUE TITLE
Is nodemon not supporting socket?

### ISSUE THREAD

**Issue by Chanran** [remy/nodemon#923]
When I use the newest nodemon to run my react hot refresh project, chrome gives the error:[WDS] Disconnected! .Then I use node to run my project,hot refresh function does work! (BTW,I rarely add issue in github,if I say something wrong,please forgive me...)

**Comment by bertmsk** [comment]
Same problem with Socket.IO 
it seems app started but not listening socket

**Comment by Chanran** [comment]
@bertmsk I found [this issue](https://github.com/glenjamin/webpack-hot-middleware/issues/21).It seems webpack's problem.
