### ISSUE TITLE
[nodemon] Internal watch failed: watch ENOSPC

### ISSUE THREAD

**Issue by showzyl** [remy/nodemon#925]
[nodemon] 1.10.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
...
[nodemon] Internal watch failed: watch ENOSPC

**Comment by remy** [comment]
http://lmgtfy.com/?q=ENOSPC

**Comment by nxdiiode** [comment]
This version of Node is misleading about `ENOSPC` (no space): We actually just hit the maximum number of watchers for files.

Newer versions of **Node** i.e. 11.0.0+ give a feedback of a better quality instead:
`[nodemon] Internal watch failed: ENOSPC: System limit for number of file watchers reached, watch '/a/filename/where/it/ran/out/of/watchers'`

* Check that **all** watched files and subfolders need to be watched (don't forget dot files).
* If you really need to watch so many files (> 8000), increase the number of threads.
https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers
https://github.com/remy/nodemon/issues/907 mentions the following permanent modification:
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`
