### ISSUE TITLE
how to watch only folder creation?

### ISSUE THREAD

**Issue by craigcosmo** [remy/nodemon#927]
What do you put in the config so that nodemon only watches for new folder creation. For example

Root foolder 'app', nodemon will watch change in app folder. Now in app folder I create a new folder called component. As soon I create the folder, server will restart. But If I create a file call index.js in component, I do not want the restart. How do you config nodemon for just this behavior?

**Comment by knight** [comment]
How about putting:  
```
{
   "ignore": ["*.js"]
}
```
?

**Comment by craigcosmo** [comment]
thanks

**Comment by craigcosmo** [comment]
sorry, i didn't work. It seem like nodemon only cares about files, not folder. Because when I used the ignore config. I created a folder inside the project, the server does not restart.
