### ISSUE TITLE
Internal watch failed: watch ENOSYS

### ISSUE THREAD

**Issue by ptrenty** [remy/nodemon#928]
I'm pretty new to this, so forgive me if I'm missing something obvious, but I can't find any guidance on how to sort this problem out.  I'm on v1.11.0 running on an iSeries and every node I try to start with nodemon gives me the same message as in the title.

**Comment by remy** [comment]
I can't easily Google right now, but what does the ENOSYS error mean?

**Comment by ptrenty** [comment]
I'm stumped on that one too.  Google isn't much help.  The only results that come back point to some other issues here, but nothing that I found helpful.

**Comment by herr-turbo** [comment]
After days of searching, I think I found a solution.
I wasn't able to run directly Nodemon by yyping
`nodemon src/app.js`

So on Node14 I found a workaround, adding a script line in package.json
` ... ,
  "main": "./src/app.js",
  "scripts": {
    ...,
    "serve": "nodemon -L"
  },`

Then run your application by typing
`npm run serve`

And voilà !

It seems to run in legacy mode.

Note : In node 10 this worked too (but not in node 14) even if my main file is src/app.js
`"serve": "nodemon server.js"`
