### ISSUE TITLE
-w flag is not correctly passed?

### ISSUE THREAD

**Issue by danger89** [remy/nodemon#930]
Hi,

I'm using nodemon also for Cloud9 instance. But somehow the `-w` flag used for the workspace directory is not correctly exported to the node instance.. 
I use:
`/usr/bin/nodemon /var/www/c9.melroy.org/html/server.js -p 8181 -w /media/data/cloud9_workplace`

See attachment:
![strange](https://cloud.githubusercontent.com/assets/628926/19807659/76d1feda-9d21-11e6-9033-d2472b484b16.png)

Any idea?

Kind regards,
Melroy van den Berg

Related:
https://github.com/c9/core/issues/376

**Comment by mistralol** [comment]
Does /usr/bin/nodemon /var/www/c9.melroy.org/html/server.js -- -p 8181 -w /media/data/cloud9_workplace

Work?

**Comment by danger89** [comment]
Well, actually the solution is here from nightwing:
https://github.com/c9/core/issues/376#issuecomment-263035038

By using `--`.

**Comment by mistralol** [comment]
So bug can be closed then?

**Comment by danger89** [comment]
Correct :+1:
