### ISSUE TITLE
nodemon continuously restarting

### ISSUE THREAD

**Issue by anikrish** [remy/nodemon#934]
Hi,

I run nodemon 1.11.0 version. It keeps continuously running. Below is the output of nodemon --dump
Please help to fix this issue.

### nodemon --dump
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
--------------
node: v0.12.2
nodemon: 1.11.0
command: node /usr/local/bin/nodemon --dump
cwd: /Users/akris46/dev/eacquisitionscardapp
OS: darwin x64
--------------
{ run: false,
  system: { cwd: '/Users/akris46/dev/eacquisitionscardapp' },
  required: false,
  dirs: [ '/Users/akris46/dev/eacquisitionscardapp' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '.git',
        '.nyc_output',
        '.sass-cache',
        'bower_components',
        'coverage',
        'node_modules',
        re: /\.git|\.nyc_output|\.sass\-cache|bower_components|coverage|node_modules/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot:
      [ '.git',
        '.nyc_output',
        '.sass-cache',
        'bower_components',
        'coverage',
        'node_modules' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     stdout: true,
     execOptions:
      { script: 'app.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js,json',
        env: {},
        execArgs: [] },
     monitor:
      [ '*.*',
        '!/Users/akris46/dev/eacquisitionscardapp/.git/**/*',
        '!.nyc_output',
        '!.sass-cache',
        '!bower_components',
        '!coverage',
        '!/Users/akris46/dev/eacquisitionscardapp/node_modules/**/*' ] },
  signal: 'SIGUSR2',
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  command:
   { raw: { executable: 'node', args: [ 'app.js' ] },
     string: 'node app.js' } }
--------------

**Comment by Nilegfx** [comment]
- try to do nodemon --verbose app.js and see which files keep changing (most probably in background jobs/extensions/OS events ..etc) 
- make sure that there is not application updating any file in your project, for example, Visual studio code or some of its extensions could force nodemon to restart as they modified/checking files in background.

**Comment by adiachenko** [comment]
I am getting the same issue on Windows 10 with node v6.9.1. No idea how to debug this.

```
C:\dev\nodeapp>npm start

> @ start C:\dev\nodeapp
> nodemon --verbose --watch app.js

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] ignoring: .git .nyc_output .sass-cache bower_components coverage C:\dev\nodeapp\node_modules/**/*
[nodemon] watching: app.js
[nodemon] watching extensions: js,json
[nodemon] starting `nodemon --verbose --watch app.js`
[nodemon] child pid: 13332
[nodemon] watching 1 files
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] ignoring: .git .nyc_output .sass-cache bower_components coverage C:\dev\nodeapp\node_modules/**/*
[nodemon] watching: app.js
[nodemon] watching extensions: js,json
[nodemon] starting `nodemon --verbose --watch app.js`
[nodemon] child pid: 11212
[nodemon] watching 1 files
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] ignoring: .git .nyc_output .sass-cache bower_components coverage C:\dev\nodeapp\node_modules/**/*
[nodemon] watching: app.js
[nodemon] watching extensions: js,json
[nodemon] starting `nodemon --verbose --watch app.js`
[nodemon] child pid: 12632
[nodemon] watching 1 files
^CTerminate batch job (Y/N)? Terminate batch job (Y/N)? Y
```

**Comment by jeblister** [comment]
Hello, i fix the same problem by adding this [nodemon.json](https://github.com/remy/nodemon/blob/master/doc/sample-nodemon.md) config file.

**Comment by heshamelmasry77** [comment]
where exactly in the project i add this file

**Comment by dotspencer** [comment]
My two bits... Try updating nodemon.
I was using v1.11 and upgrading to v1.18.3 fixed the issue.

**Comment by Ji-Won-Coder** [comment]
비슷한 문제가 있는데, 매초마다 다시 시작되지만 빌드 파일의 TS 파일에서 변경 사항을 가져 오지 않고 자바 스크립트가 내 TS 파일의 변경 사항을 가져 오지 않고 그렇게 실행된다는 것입니다. !!!!!
