### ISSUE TITLE
when fs.writeFile , then server will be restart

### ISSUE THREAD

**Issue by Super-Meng** [remy/nodemon#936]
when fs.writeFile , then server will be restart,
 I use koa2, and nodemon start the server, use any fs write, the server will restart ,
but use node or pm2 will not  :(

**Comment by manuel-di-iorio** [comment]
You have to add the folder into you are writing, in the ignored paths of `nodemon.json`

**Comment by tvquangdn** [comment]
me too, solution of mine and it run, no restart:  change folder of your image on server to another place. For example,in Vuejs, don't use folder in static to store image, it force vue restart.
