### ISSUE TITLE
"[nodemon] app crashed" error occuring on new machine.

### ISSUE THREAD

**Issue by katsuragi545** [remy/nodemon#940]
I recently got a new computer and have made it my development machine. Inside my package.json file I have a custom script as follows:

`"static-watch": "nodemon --watch ./client --ext html,css --exec \"gulp deploy-client\" -V",`

On my previous development machine, this command worked by calling `npm run static-watch` from a command prompt. However, this script/command no longer works when I try it on my new machine. The full error is: 

```
No gulpfile found
[nodemon] app crashed - waiting for file changes before starting...
```

The gulpfile is definitely there - I can run gulp deploy-client from a command prompt and it works perfectly fine. Does anyone have any ideas on why this is happening?

**My version info:**
node: 5.5.0
npm 3.9.6
gulp CLI - 3.9.1
gulp Local version - 3.9.1

**Comment by katsuragi545** [comment]
Refer to this SO post to resolve this issue: http://stackoverflow.com/questions/27026014/npm-always-using-home-directory-as-current-working-directory

**Comment by LunaBawa** [comment]
I have a similar issue here ... need help

![image](https://cloud.githubusercontent.com/assets/11213175/22701873/3605a3b4-ed5f-11e6-8692-931e76beba90.png)
