### ISSUE TITLE
Watching specific files?

### ISSUE THREAD

**Issue by slavafomin** [remy/nodemon#943]
Hello!

Thank you for this great module!

However, how do I watch for specific files?

Here's my `nodemon.json`:

```json
{
  "watch": [
    "./config/",
    "./src/",
    "./package.json",
    "./server.js",
    "./.env"
  ],
  "verbose": true
}
```

It works perfect for the specified directories (i.e. `config` and `src`), but specified files are not trigerring the restarts.

I'm getting the following output when the file is changed:

```bash
[nodemon] files triggering change check: package.json
[nodemon] changes after filters (before/after): 1/0
```

So, how do I watch for specific files and not directories?

Thanks!

**Comment by slavafomin** [comment]
Eh, hello?

**Comment by slavafomin** [comment]
Stumbled upon my own question when I was searching for a solution after about half a year.

How do I make nodemon to watch for `.env` file? Even if I specify it in `ext` option, it's not tracked.

@remy Could you please clarify this? Thank you.

**Comment by danielmahon** [comment]
Try adding the file extensions to the "ext" option:
https://github.com/remy/nodemon#specifying-extension-watch-list

**Comment by vladano** [comment]
Hi,
I have the same problem.
If you for example define environment variables inside file "variables.env" and after that you add dat "env" extension to be watched by nodemon, for example :
nodemon --ext js,env,gql --exec babel-node server.js
It will work fine and that's OK.
If you try to define define environment variables inside file ".env", I don't know how to configure nodemon to watch that specific file name ".env" ?!
Doe's anyone has idea how to fix this?

Thanks

**Comment by skirankumar7** [comment]
> Hi,
> I have the same problem.
> If you for example define environment variables inside file "variables.env" and after that you add dat "env" extension to be watched by nodemon, for example :
> nodemon --ext js,env,gql --exec babel-node server.js
> It will work fine and that's OK.
> If you try to define define environment variables inside file ".env", I don't know how to configure nodemon to watch that specific file name ".env" ?!
> Doe's anyone has idea how to fix this?
> 
> Thanks

nodemon webpack-server.js --watch **path/to/yourfile/example/.env.dev**

It works for me.

**Comment by robjweiss** [comment]
Worked for me by simply specifying the watch option in my config like this:

```
{
  "watch": ["src", ".env"]
}
```
