### ISSUE TITLE
nodemon output doesn't respect console colours with msysgit

### ISSUE THREAD

**Issue by steveworkman** [remy/nodemon#95]
Hi Remy,

Really, really small cosmetic bug (lowest of low priority), but with msysgit on Win 7 x64 the nodemon process outputs the standard grey on black colours to the terminal. That's normally fine, but I've got the console to be black on white so I can tell which window the server console is! Twitpic here: http://t.co/0Eb85BoF

In the picture, the top set of output is from the standard node runtime.

It's just a tad annoying. If you need me to do any testing just let me know.

**Comment by matanshukry** [comment]
I am having this problem as well; I tried tracking it down, and reached to nodejs.
Specifically this issue : https://github.com/nodejs/node/issues/2333

as far as I can tell, if I'm adding the line
```
process.stdout.isTTY = true;
```
at the start of my app, all colors outputs are working.

So the issue persists, but as far as I can tell it's a nodejs issue and not a nodemon one.

**Comment by remy** [comment]
You can disable colours using `--no-colors` through the cli, or add it as an option using `noColors: true`.
