### ISSUE TITLE
Nodemon start event triggered more than once

### ISSUE THREAD

**Issue by brunokrebs** [remy/nodemon#950]
I'm using nodemon `start` event to trigger some commands - e.g. `npm run whatever`. But, whenever I have nodemon running and I change a file that is it's watch, this `start` event is emitted again, alongside with `restart` event.

Actually, I just made a test over here, configuring my `nodemon.json` as:

```json
{
  "events": {
    "start": "echo '-------------------- start'",
    "restart": "echo '-------------------- restart'"
  }
}
```

And I saw nodemon echoing start first, then restart. Wasn't it supposed to emit the `start` only once, at the first start?

If this behaviour is indeed what was expected by design, how could I trigger a command only once, after startup?

**Comment by huangyanxiong01** [comment]
I have also encountered the same problem
