### ISSUE TITLE
the SIG prefix is not valid according to the POSIX standard

### ISSUE THREAD

**Issue by knight** [remy/nodemon#956]
Nodemon fails to reload the application it supervises.

When nodemon detects a change in the watched directory it tries to signal the child using the following (let's assume the child's pid is 123):
`/bin/sh -c kill -s SIGUSR2 123`
/bin/sh under most of the linux distros is attached like this:
`/bin/sh -> /bin/bash`
which triggers in strict POSIX compliance. A POSIX compliant shell won't understand the SIG  prefixes. Following this discussion http://unix.stackexchange.com/questions/199360/kill-sigstop-invalid-signal-specification-error-in-bash-script I successfully reproduced the behavior.
You can either start bash using the --posix option or start /bin/sh
Then `kill -s SIGTERM 123 or kill -s SIGUSR 123 `will yield:
`bash: kill: SIGTERM: invalid signal specification`
or 
`/bin/sh: 2: kill: invalid signal number or name: SIGTERM`
respectively. Similar things happen when the ps utility is installed.

The problem current codebase has is that it tries to pass the SIG* constants when constructing the signaling command and it tries to use a strictly POSIX shell at the same time.

I'm trying to run nodemon 1.11.0 under amazon linux and debian jessie.

**Comment by remy** [comment]
What's the fix for this, and are you happy to make a PR for it?

**Comment by knight** [comment]
So far I have just a work around: I'm taking an advantage of the fact that SIG is just a prefix https://github.com/knight/nodemon/commit/b0669a112291a491f8757575758b43cf3a378667. I think that the commandline emitting code needs to be at least properly wrapped so that the SIG constants are translated.

**Comment by knight** [comment]
I'm not sure why the tests fail on 0.10 and 4 versions of node.
