### ISSUE TITLE
Feature request to add whitespace to log between restarts

### ISSUE THREAD

**Issue by cmawhorter** [remy/nodemon#959]
This is a really tiny annoyance and feel free to close.

nodemon writes this between restarts:

```
...probably some error stack...
[nodemon] restarting due to changes...
[nodemon] starting `node ....`
...probably the same error stack...
```

If there was a flag to add some whitespace between restarts or maybe even completely clear, it would make my life just a tiny bit better.

The result might be something like:

```
...probably some error stack...
[nodemon] restarting due to changes...





[nodemon] starting `node ....`
...probably the same error stack...
```

**Comment by woutrbe** [comment]
Not exactly what you wanted, but I've been doing something similar with this:

nodemon.json
```
"events": {
		"restart" : "node foo.js"
	}
```

foo.js
```
console.log(' ');
console.log(' ');
console.log(' ');
console.log(' ');
console.log(' ');
```

Gives you:
```
[nodemon] restarting due to changes...
[nodemon] starting `node index.js --debug`





...whatever your index.js outputs
```

**Comment by cmawhorter** [comment]
that's a way better workaround, thanks!   also, i'm glad to see i'm not alone

**Comment by cmawhorter** [comment]
cool, just gave it a shot and that works.  `"restart": "clear"` also works as expected.  I'd say that's good enough.
