### ISSUE TITLE
Not Detecting Changes on Linux

### ISSUE THREAD

**Issue by mcqj** [remy/nodemon#963]
Fairly simple use case, using from CLI:-
nodemon --watch src build.js

nodemon does not detect any file changes. Turning on the debug flag causes the app to crash

running nodemon 1.11.0 on node 6.9.3

linux distro is mint 17

**Comment by mcqj** [comment]
An update on this - I was able to turn on --verbose option. This tells me that nodemon is actually seeing the file changes but doesn't re-run the app.

[nodemon] files triggering change check: src/assets/css/main.css
[nodemon] matched rule: **/home/john/playground/metalsmith/mysite/src/**/*
[nodemon] changes after filters (before/after): 1/0

**Comment by knight** [comment]
Looks like the problem described in #956.

**Comment by mcqj** [comment]
It does look like its the same or related issue. However, I tried the fix proposed in #957 and it does not fix the issue for me.

**Comment by mcqj** [comment]
After further testing of #957 it does in fact cure the problem for me. I mis-configured my extensions option when I was testing. Closing this issue as I believe it is a duplicate of #956
