### ISSUE TITLE
the project does not clone correctly on windows

### ISSUE THREAD

**Issue by knight** [remy/nodemon#964]
There are certain fixtures which cannot be checked out on windows. 
This is output of `git status` 
```
        deleted:    "test/fixtures/some \\file"
        deleted:    "test/fixtures/some\"file"
        deleted:    "test/fixtures/some\\\"file"
```

`"` `\` and some other characters are not supported on windows platform. 
A possible work-around: 
The tests which use the above files could be marked as skipped and the presence of the files could be ensured in the tests' setup.

**Comment by knight** [comment]
Naturally skipping on Windows only.

**Comment by remy** [comment]
Yeah, I'm aware. Sorry, I can't help at the moment. I'd take a PR that helps resolve this, but the files are needed for testing (and testing on windows, yes, is damn tricky!).
