### ISSUE TITLE
How to specify a path to watch in a config file?

### ISSUE THREAD

**Issue by wzup** [remy/nodemon#965]
So your docs says how to specify a path from a command line:
```
nodemon --watch app --watch libs app/server.js
```

But docs say nothing about how to specify a path to watch in a config file.

Here is a use case.
An Expressjs app has `bin/www` file. Since it has no extension it is not possible to set up `nodemon` to watch that file by its extension. Question being, how to specify a path in a config file?

Here is a config file. How do I configure `nodemon` to watch `bin/www` with this config file?
```
{
    "restartable": "rs",
    "verbose": true,
    "env": {
        "NODE_ENV": "development",
        "DEBUG": "app:*",
        "DEBUG_COLORS": true
    },
    "ignore": ["routes/___*.js", "routes/___*.html"],
    "debug": true,
    "ext": "js dust html css scss rb json htpasswd",
    "exec": "node --debug=5850 ./bin/www"
}
```

**Comment by remy** [comment]
Have you tried adding an array called `watch` with a list of the dirs you
want to watch?
