### ISSUE TITLE
If the directory being watched gets removed nodemon stops working.

### ISSUE THREAD

**Issue by ohjames** [remy/nodemon#978]
I would expect nodemon to monitor for the watched directory being removed and recreated, then to restart watching against the new directory at the old location. Due to this it can't be used with compilers like `tsc` that remove the output directory before compiling.

**Comment by joeytwiddle** [comment]
Yes, we are having the same problem. We are watching the `dist` folder:
```
--watch dist
```

But some build processes will completely remove that folder and then recreate it. When this happens, nodemon stops watching it. Understandable I guess.

Is there any alternative? I considered something like this:
```
--watch . --ignore node_modules --glob 'dist/**/*'
```

but the `--glob` option does not exist, yet. :wink:

For now, I guess I will use this:
```
--watch . --ignore node_modules --ignore src --ignore logs --ignore ...
```

I would suggest one of the following solutions:
1. Detect when a folder is removed, and start watching its replacement.
2. Provide a `--glob` option, as a workaround.
3. Clearly document this "gotcha", and provide a recommended workaround (e.g. the multiple ignores above). This is probably the easiest option!
