### ISSUE TITLE
Nodemon not restarting automatically

### ISSUE THREAD

**Issue by Malekai** [remy/nodemon#979]
After installing nodemon, nodemon watches the directory but does not restart at all for any changes. I have tried to install an earlier version, but still no luck. 

This is what my terminal looks like.

![screen shot 2017-02-12 at 6 58 29 pm](https://cloud.githubusercontent.com/assets/16912505/22899440/d9f1ee36-f1f8-11e6-8995-e4fd65ffb485.png)
![screen shot 2017-02-12 at 6 58 43 pm](https://cloud.githubusercontent.com/assets/16912505/22899448/ddfcb1f0-f1f8-11e6-8b27-cdc6c39b1b74.png)

**Comment by markelog** [comment]
Created repo with similar issue - https://github.com/markelog/nodemon-issue

**Comment by michaelBenin** [comment]
@remy we are having the same issue in our project with latest nodemon where files and directories are mixed. Hope that helps! Thanks again for this awesome project!

**Comment by yongzhihuang** [comment]
Can reproduce on Ubuntu as well. Node 5.6.0

**Comment by michaelBenin** [comment]
@remy looks like the config needed to be updated on our end, @markelog try adding /* to the watched directory.

**Comment by drihup** [comment]
Same problem here on Ubuntu 14.04, Node 6.10.1, nodemon v1.11.0
