### ISSUE TITLE
[question] exception in nodemon killing node with EC2

### ISSUE THREAD

**Issue by Rolandvl** [remy/nodemon#98]
Hi,

I used to this command on mac os x , with no problem
       /usr/bin/nohup nodemon site.js &
But when I'm doing the same cammond on an Amazon Linux AMI
I get :

16 May 08:33:37 - [nodemon] exception in nodemon killing node
Error: EBADF, read
16 May 08:33:37 - [nodemon] app crashed - waiting for file changes before starting...

Am I doing something wrong ?

Thanks,
Roland.

**Comment by wjamyers** [comment]
artjock commented on Jun 5, 2012
"I had the same issue on Ubuntu, but nohup nodemon app.js </dev/null & helped me"

This got me going.  I guess this problem is specific to running nodemon on an AWS Ubuntu server.  Thanks, artjock!
