### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by markelog** [remy/nodemon#980]
Latest commit was four months ago, even though there is 234 open issues, 14 open pull requests, `node 7` is not being tested whereas `node .10` is still in the matrix, really outdated dependencies and consistently failing CI runs for all pull request no matter what changed in them.

And big issues like that - https://github.com/remy/nodemon/issues/979 are not addressed

**Comment by remy** [comment]
Alive: yes.
Working for a tonne of cases: yes
Loads of open issues (including random questions and utterly out of date stuff): yes
Activily developed: no
Activily closing issues: sometimes, but mostly no
Feeling guilt and pressure even though the single author has never made a penny for the work in over 6 years: yes (social pressures, eh?)

Any other questions (likely, yes).

**Comment by remy** [comment]
Also, the issue you're referring to, if you read it, you'll realise there's no information on what the actual issue is. My bet: configuration error on the user side. But honestly there's other people can can, and should, help. Sorry, probably not what you wanted to hear.

**Comment by remy** [comment]
Re: tests failing, I suggest understanding why. It's not related to the deps, it's related to race conditions and complicated configurations and Travis being one OS. To be honest there's an argument for stripping some tests out.

Finally, this issue really isn't contributing anything except to attempt to shame me, the author of nodemon. So, well done 👍

**Comment by markelog** [comment]
> Finally, this issue really isn't contributing anything except to attempt to shame me, the author of nodemon. So, well done 

Dude! No-no, that wasn't my premise at all, I really-really appreciate the work you have done with `nodemon` and other high profile projects you have been working on (specifically but not limited to jsbin), I can't express enough, how these module and services help me in my day-to-day stuff.

I fully realise that you don't own anybody anything, that this is for free and all that, big thank you and stuff, would buy you a case of beer if I would lucky enough to meet you in person.

With that being said, I phrase the issue in that way, so it wouldn't look like I think that since that project wasn't updated in couple months means that it's forgotten, I have faced either similar or the same issue as in #979, which made me switch to other module and being a fan of this module I was genially concern about its health status.

If that helps, I can provide a repo with repro steps for #979 and can provide a pull request for updating dependencies, travis configuration, adapting to new nodes and etc; not sure if I have the time to figure out the race conditions, but I can at least try do that, what I wouldn't want to see is those efforts to be in vain (like https://github.com/remy/nodemon/pull/938) hence this issue

**Comment by remy** [comment]
Okay…sorry for the rant, it's not the first time I've had a bit of a pile on, you caught me! And thank you for a reasonable reply!

If you can replicate the #979 issue then that would be great, because then we can get to the bottom of the issue. I'm going to guess that it's a new version of node and potentially linked to chokidar, which _might_ be fixed with a dep bump. I'd be happy to take a PR that updates deps, and possibly ends support for node @ 0.x - I don't know if there's any numbers on usage (though I personally use 0.10 for jsbin for instance).

**Comment by markelog** [comment]
Created repo with similar issue as in #979 - https://github.com/markelog/nodemon-issue
Related issues – https://github.com/remy/nodemon/issues/981, #982, #983, #984
