### ISSUE TITLE
Consider switching from jscs/jshint to eslint

### ISSUE THREAD

**Issue by markelog** [remy/nodemon#983]
If accepted, we need to decide on eslint config

**Comment by remy** [comment]
I'm open to this, but it needs to be in an atomic PR/commit. I'm just wary it might touch a lot of files (which is fine) but I just want to keep the merge limited to linting changes.

**Comment by markelog** [comment]
It definitely will, no fear though, I already had experience with implementing such configs into big/medium code-bases in one commit, excluding proprietary systems, I can name for example grunt, jquery, wikimedia.

We only need to settle on what kind of code-style do you prefer :)
