### ISSUE TITLE
Mitigate `MaxListenersExceededWarning` error in tests

### ISSUE THREAD

**Issue by markelog** [remy/nodemon#988]
Observing this at the test run
>  require-able
    ✓ should prioritise options over package.start (140ms)
    ✓ should know nodemon has been required
(node:27038) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit
    ✓ should restart on file change (1228ms)
    ✓ should be restartable (1100ms)

Need to figure out why and what is happening and fix it

**Comment by remy** [comment]
Heh, yeah, I couldn't work this out either!

**Comment by remy** [comment]
I'd recommend using the latest nodemon, but if this is happening upon load,
then it's likely to be your own code.

The tests throw this error when nodemon is required an restarts *a lot*
during the tests.
