### ISSUE TITLE
nodemon.json question

### ISSUE THREAD

**Issue by RifeWang** [remy/nodemon#993]
I used express framework , and then installed nodemon and writed a nodemon.json file :
```
{
    "restartable": "rs",
    "ignore": [
        ".git",
        "node_modules/**/node_modules"
    ],
    "verbose": true,
    "execMap": {
        "": "node",
        "js": "node --harmony"
    },
    "watch": ["*.*"],
    "env": {
        "NODE_ENV": "development",
        "PORT": "3000"
    },
    "ext": "js json",
    "legacy-watch": false
}
```
then, I writed `nodemon` in my command line and it worked! But my question is I did not specify start file input like /bin/www , how does it kown this , and if i want to specify a nother start file , how to write in nodemon.json?

**Comment by vidhu** [comment]
You must have a `{ "main": "app.js" }` in your `package.json`
