### ISSUE TITLE
Arguments containing pipe character aren't propagated correctly

### ISSUE THREAD

**Issue by aikoven** [remy/nodemon#995]
```bash
nodemon ./index.js "foo|bar"
```
Above command gives
```
sh: bar: command not found
```
The logs says
```
[nodemon] starting `node index.js foo|bar`
```

I couldn't quickly find a place to put failing test to, but if you point me to it, I could make a PR.

**Comment by remy** [comment]
Can you try slipping `--` in front of your argument to see if the quotes
still get slurped?

**Comment by aikoven** [comment]
Yep, it behaves the same way.

I've tracked the problem down to `utils.stringify` call which only adds quotes if there's a space in the argument.
