### ISSUE TITLE
I figured out why the infinite restart was happening

### ISSUE THREAD

**Issue by ORESoftware** [remy/nodemon#996]
I bet this happens to your users a bit -

the `npm start `value in my case was ./run.sh, aka:

```
  "scripts": {
    "start": "./run.sh",
  },
```

but my run.sh would start nodemon if NODE_ENV==development !!

so when nodemon started, it would keep launching itself. Thus the infinite nodemon loop of death.

I think the default of using npm start is OK, but it would be nice if by default settings also had nodemon logging that it was running npm start. I didn't know that this was the default, but it makes sense for this to be the default

just FYI, my guess is this is the most common reason for infinite nodemon. Personally I think NPM scripts aren't so great. I'd rather use bash in general.

I think the docs should make more of a point of demonstrating how to define the executable for nodemon to launch, especially if this is available in `nodemon.json`

**Comment by remy** [comment]
Makes sense to echo out how it's running the script 👍

**Comment by ORESoftware** [comment]
yeah, does that echo come out of the nodemon box how can I do that?
