### ISSUE TITLE
force exit when not using nodemon programmatically

### ISSUE THREAD

**Issue by terencechow** [remy/nodemon#998]
I am using nodemon from `package.json` which simply runs `nodemon` and I have a `nodemon.json` that tells nodemon to ignore a bunch of folders and run a specific js file.

On a specific type of error I would like to force nodemon to quit. I see that if we used nodemon programmatically we could do: 

`nodemon.emit('quit');`

Is there a way to do this non-programmatically? I tried `process.exit(1)` but nodemon did not respond

**Comment by remy** [comment]
Not really. Nodemon is for continuous development, so this doesn't really fit the pattern of use. Sorry.

**Comment by derekshull** [comment]
I'm really needing this as well.
