### ISSUE TITLE
Nodemon kills Google Chrome process sometimes :(

### ISSUE THREAD

**Issue by ORESoftware** [remy/nodemon#999]
When I first start up Nodemon it seems to kill Chrome (I assume the same thing would happen with Mozilla, etc). Is there any way I can prevent Nodemon from killing my browser? I assume because Nodemon will kills processes associated with a particular port. It would be really nice if it didn't kill the browser though :(

**Comment by ORESoftware** [comment]
One possible way would be for Nodemon to use SIGTERM or SIGINT instead of SIGKILL - I am guessing that Chrome will handle the former 2 somehow.

**Comment by remy** [comment]
Sigterm control is coming in a PR.

**Comment by ORESoftware** [comment]
ok cool good to know :) thx
